### ISSUE TITLE
Yearly seasonality fluctuation using 8 months and 1 day of history and 8 months and 2 days

### ISSUE THREAD

**Issue by rev3ks** [facebook/prophet#1002]
I have been testing out using prophet and had really good results! Today I came across an anomaly with the forecast. I ran some different date ranges and found the point at which the behavior started to occur. In the screenshot below, on the left is the forecast and yearly seasonality using daily data from 9/4/18 to 6/4/18 inclusively. On the right is the exact same data plus one additional data point for 9/3/18.  I scanned the issue list for similar issues, but if I missed one, let me know. 

I am using version 0.4.post2, `yearly_seasonality=True, growth='linear'`

<img width="1675" alt="Screen Shot 2019-06-05 at 12 39 20 PM" src="https://user-images.githubusercontent.com/26027325/58981128-01b19880-878f-11e9-92ce-56ad0be485e4.png">

[data.csv.zip](https://github.com/facebook/prophet/files/3258640/data.csv.zip)

**Comment by vhpietil** [comment]
Because you don't have data over whole year, prophet is free to estimate anything on the months of no data. That is why even single datapoint can lead to big fluctuations where there is no data. You should not try to predict yearly seasonality without data from full year.

**Comment by VinceZJ** [comment]
why is it predicting a yearly component in the first place then? Shouldn't it just default to the trend & other components?

**Comment by vhpietil** [comment]
It does default to the other component but you have told prophet to use yearly seasonality using yearly_seasonality=True, growth='linear'
