### ISSUE TITLE
Can't fit.prophet() when updated to R 3.6.0 in macOS: storage error

### ISSUE THREAD

**Issue by laresbernardo** [facebook/prophet#1003]
I've used `prophet` a thousand times and updated to R 3.6.0 in mi macOS and now I'm getting this error when I try to fit a model: 
```
m <- fit.prophet(m, prop)
Error in get("storage", envir = as.environment(x)) : 
  object 'storage' not found
```
I uninstalled and installed from scratch, and when loaded for the first time, this is what I get:
```
library(prophet)
Loading required package: Rcpp
Loading required package: rlang
Registered S3 methods overwritten by 'ggplot2':
  method         from 
  [.quosures     rlang
  c.quosures     rlang
  print.quosures rlang
```
Here is my session info if needed:
```
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rstan_2.18.2       StanHeaders_2.18.1 ggplot2_3.1.1      prophet_0.5        rlang_0.3.4       
[6] Rcpp_1.0.1        

loaded via a namespace (and not attached):
 [1] pillar_1.4.1       compiler_3.6.0     plyr_1.8.4         prettyunits_1.0.2  tools_3.6.0       
 [6] pkgbuild_1.0.3     tibble_2.1.3       gtable_0.3.0       pkgconfig_2.0.2    cli_1.1.0         
[11] rstudioapi_0.10    parallel_3.6.0     loo_2.1.0          gridExtra_2.3      withr_2.1.2       
[16] dplyr_0.8.1        stats4_3.6.0       grid_3.6.0         tidyselect_0.2.5   glue_1.3.1        
[21] inline_0.3.15      R6_2.4.0           processx_3.3.1     tidyr_0.8.3        callr_3.2.0       
[26] purrr_0.3.2        magrittr_1.5       scales_1.0.0       ps_1.3.0           matrixStats_0.54.0
[31] assertthat_0.2.1   colorspace_1.4-1   stringi_1.4.3      lazyeval_0.2.2     munsell_0.5.0     
[36] crayon_1.3.4      
```
Any idea on why is this happening, and most important of all, how to fix it? Thanks 👍

**Comment by bletham** [comment]
I don't think that code `get("storage", envir = as.environment(x))` is istelf in prophet, so I'm wondering if the error might be coming from a dependency. Could you run `traceback()` right after the error to see where it's coming from?

It looks like R 3.6 hasn't made it into the package manager repository for me yet so I haven't been able to try and reproduce this.

**Comment by laresbernardo** [comment]
I had to reduce the amount of data so the `traceback()` results can be shown. This is what I get:
```

**Comment by laresbernardo** [comment]
I also get this error the first time I run after reseting my R session: `Error: vector memory exhausted (limit reached?)`
And when `traceback()` is run:
```
12: Module(module, mustStart = TRUE)
11: .getModulePointer(x)
10: new("Module", .xData = <environment>)$stan_fit4model1600c2a310a8b_prophet
9: new("Module", .xData = <environment>)$stan_fit4model1600c2a310a8b_prophet
8: eval(call("$", mod, paste("stan_fit4", model_cppname, sep = "")))
7: eval(call("$", mod, paste("stan_fit4", model_cppname, sep = "")))
6: object@mk_cppmodule(object)
5: .local(object, ...)
4: (new("nonstandardGenericFunction", .Data = function (object, 
       ...) 
   {
       if (is.sparc()) {
           msg <- "optimizing() will likely crash on SPARC."
           if (interactive()) 
               stop(msg, " Run in batch mode to test.")
           else message(msg)
       }
       standardGeneric("optimizing")
   }, generic = "optimizing", package = "rstan", group = list(), 
       valueClass = character(0), signature = "object", default = NULL, 
       skeleton = (function (object, ...) 
       stop("invalid call in method dispatch to 'optimizing' (no default method)", 
           domain = NA))(object, ...)))(object = new("stanmodel", 
       model_name = "prophet", model_code = "functions {\n  matrix get_changepoint_matrix(vector t, vector t_change, int T, int S) {\n    // Assumes t and t_change are sorted.\n    matrix[T, S] A;\n    row_vector[S] a_row;\n    int cp_idx;\n\n    // Start with an empty matrix.
# (...)
```
The second time I try to run exactly the same line, I get the previous error results and traceback! 👎

**Comment by bletham** [comment]
OK so the error is being thrown in rstan. The "vector memory exhausted" seems to be related to R having a maximum memory allocation limit (https://stackoverflow.com/questions/51248293/error-vector-memory-exhausted-limit-reached-r-3-5-0-macos/52612848). Maybe that changed in R3.6? Could you see what it is?

Stan does require a surprising amount of RAM to compile and fit models. Could you see if this code runs? That would help to identify if it is just the usual rstan RAM usage causing the issue, or if it may be actually something in how it is being called by prophet:
```
library(rstan)
model_code <- 'parameters {real y;} model {y ~ normal(0,1);}'
fit <- stan(model_code=model_code)  # this will take a minute
mean(extract(fit)$y)  # should be close to 0
```

**Comment by laresbernardo** [comment]
This is what I get when I run your code (tried twice, same result):
```
> fit <- stan(model_code=model_code)  # this will take a minute
Error: vector memory exhausted (limit reached?)
> mean(extract(fit)$y)  # should be close to 0
Error in extract(fit) : object 'fit' not found
```
And about the memory limit, it doesn't make much sense. In this test I used a 50 row dataset to forecast, and I'm on a 16GB RAM laptop, with a fresh RStudio session (nothing in the Global environment other than the data frame).

Thanks for your help @bletham Really appreciate it!

**Comment by bletham** [comment]
I'm not really sure what's happening here. There are a lot of stackoverflow posts addressing the "Error: vector memory exhausted (limit reached?)" error where people suggest various things, which seem to work for some but not others. It looks like there are some additional considerations for RStudio.

rstan does need about 4GB of RAM to compile the model, regardless of the size of the data. A 16GB laptop would certainly have that, but it does leave me wondering if there is something set in R that is limiting it.

Besides trying the tips scattered around stackoverflow, since this is an issue generally with rstan I'd suggest asking in the rstan issues and they might have better experience with / knowledge of this issue.

**Comment by djacobs7** [comment]
I had a similar issue.  I had to modify my ~.R/Makevars file to use clang, like so:

~.R/Makevars
```

CC=gcc
CXX=g++
CXX11=g++
CXX14=g++
cxx18=g++
cxx1X=g++
LDFLAGS=-L/usr/lib 
```

Then I did install.packages('prophet') and the problem went away.
