### ISSUE TITLE
ERROR: Complete output from command python setup.py egg_info: with installing excelLibrary

### ISSUE THREAD

**Issue by venkatasuresh06** [facebook/prophet#1004]
Hi all,
When I try to execute the command "pip install robotframework-excellibrary", I am receiving below issue. I am using Pythong 3.6.5 version. Please help me.

    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\vseelam\AppData\Local\Temp\pip-install-ewr3r34h\robotframework-excellibrary\setup.py", line 23, in <module>
        execfile(join(dirname(__file__), 'ExcelLibrary', 'version.py'))
    NameError: name 'execfile' is not defined
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\vseelam\AppData\Local\Temp\pip-install-ewr3r34h\robotframework-excellibrary\

**Comment by venkatasuresh06** [comment]
Can anyone help me?

**Comment by bletham** [comment]
This issue tracker is for a different package. Your best bet will be to go to the website for that package (https://navinet.github.io/robotframework-excellibrary/) and see what it says there about getting help.
