### ISSUE TITLE
Tuning best practice

### ISSUE THREAD

**Issue by djrscally** [facebook/prophet#1009]
Hello

I'm wondering if you can suggest a best practice for tuning the models. So far I've been performing a simultaneous randomized search over `changepoint_prior_scale`, `seasonality_prior_scale`, `holidays_prior_scale` and `fourier_order` for each seasonal component. At the moment this results in problems like high error rates for holiday dates, presumably because the tuning process achieved the best results by prioritising the values for the other two prior scale params over the holidays one. I think that that can probably be improved by sequentially tuning, say, `changepoint_prior_scale`, then `seasonality_prior_scale`, then `holidays_prior_scale`, then the `fourier_orders` for the seasonality components. I'm testing this now, but wanted to ask how other people are doing the same thing.

Thanks
Dan

**Comment by germayneng** [comment]
personally when i am tuning parameters, i will do a visual EDA to see if it makes sense. After which , i will continue on using cross validation (walk forward cv) to test if the parameters are indeed good. Prophet's internal cv is really good and also allows you to do diagnosis on your model. I would love to hear how others are doing as well

**Comment by bletham** [comment]
This is something that really needs to be documented better (#660) in terms of what reasonable ranges for things are. One thing that I would note is that a logarithmic scale seems to work best for the prior scales. So you might do the random search over, for instance, x \in [-3, 2] and then take the actual prior scale as 10**x. 

I also would heartily 2nd @germayneng's comment on visual inspection. I think that is especially a great way to figure out if the seasonality fourier orders need to be adjusted. It will likely be pretty clear just from looking at the fit to the history if the seasonality is way too smooth and so the fourier_order needs to be increased. If there are very rapid seasonal changes that aren't being captured by seasonality then increasing fourier_order could be useful, but maybe it's just a several-day spike for a holiday, and would be better modeled as a holiday effect. Looking at the data is I think the best way to figure that sort of thing out.
