### ISSUE TITLE
Best Practice for Feature Engineering with Prophet

### ISSUE THREAD

**Issue by rydevera3** [facebook/prophet#1010]
Hello!

Currently, I am using prophet to do forecasting. I believe I can get better results by adding external features as well as deriving features from the series itself and adding them as extra regressors. What are some best practice for deriving features from the series itself and incorporating them into Prophet?

**Comment by bletham** [comment]
I'm not sure I totally understand what you mean by deriving features from the series itself, what sort of things do you have in mind?

The model is
```
y = trend(t) + seasonality(t) + beta * regressor(t)
```
where the parameter `beta` is fit along with the other model components. So generally extra regressors will be useful when they are linearly correlated with y.

**Comment by rydevera3** [comment]
@bletham - thank you for getting back to me - what I had in mind was something like this  - https://tsfresh.readthedocs.io/en/latest/

**Comment by bletham** [comment]
I see, these are all statistics computed by aggregating the time series over some window.

As can be seen in the formula in my comment above, you have to have a value of the extra regressor for every value of the time series. You also have to know the value of the extra regressor for all of the future time points that you want to forecast. So unless the feature of the time series is somehow easier to forecast than the time series itself, there won't be any way to get value from this. It's hard for me to come up with an example of when that would be the case.
