### ISSUE TITLE
Error while installing fbprophet in Windows

### ISSUE THREAD

**Issue by Jamuthira-R** [facebook/prophet#1014]
Hi all,

  I have installed Python 2 and I tried installing fbprophet. There are some errors while installing the module. So, I switched to Python 3 and I tried the installation. Still, I got errors. One of the errors is to install Microsoft Visual C++ in version 14.0. Even after installing Microsoft Visual C++ 14.0, I am not able to install fbprophet. Please help me to get through this. Thank you in advance.

Best Regards,
Jamuthira R

**Comment by andrewng88** [comment]
Maybe you can try Anaconda.

**Comment by Jamuthira-R** [comment]
Hi @andrewng88,

 Thank you for your suggestion. I will try **Anaconda** and let you know.

Best Regards,
Jamuthira R

**Comment by bletham** [comment]
I would definitely recommend Anaconda on windows, I have personally never been able to get PyStan set up on windows outside of Anaconda.

(But if you really needed to, then first make sure PyStan is working by following these directions to install it: https://pystan.readthedocs.io/en/latest/windows.html , after which the fbprophet installation should go smoothly).
