### ISSUE TITLE
OSError: [Errno 116] Stale file handle: when installing fbprophet to Azure databricks

### ISSUE THREAD

**Issue by sauceishere** [facebook/prophet#1015]
I am trying to install fbprophet to Azure databricks, but faced the following error.

> OSError: [Errno 116] Stale file handle: '/databricks/python/lib/python3.5/site-packages/pandas'

The above error code came out after I executed the below code on Azure databricks.
```
'%sh /databricks/python/bin/pip install fbprophet'
'from fbprophet import Prophet'.
```

I have the below libraries already installed.

> fbprophet 0.5
> numpy 1.11.1
> pandas 0.24.2
> pystan 2.19.0.0

Please advise how to solve this issue, Thanks

**Comment by bletham** [comment]
I'm not familiar enough with databricks to know exactly what might be happening here. It looks like the issue might be coming from the pandas import though; in particular it looks like something deleted pandas. Could you check that it is working correctly by
```
import pandas
print(pandas.__version__)
```
