### ISSUE TITLE
Using external regressor with insufficient data

### ISSUE THREAD

**Issue by alexgawrilow** [facebook/prophet#1017]
I use weather forecast as external regressor to forecast a time series. The weather forecast is limited to 14 days into future. However I want to be able to forecast more days into future, let's say 28 days. Is there a good way to use the weather forecast for the next 14 days (day 1-14) as external regressor and somehow disable the external regressor for the following 14 days (day 15-28)? \
If there is no external regressor provided in the future DataFrame I get `ValueError: Found NaN in column temp`. To solve my problem I train 2 models: one model that uses the external regressor to forecast day 1-14 into future and one model that does not use external regressor to forecast day 15-28 into future. Is there a better approach without fitting two different models?

**Comment by vhpietil** [comment]
Do not use absolute weather but some kind of deviation from mean weather as regressor. Then the forecast long in to the future is kind of a forecast with expected weather

**Comment by bletham** [comment]
I was going to suggest basically the same thing as vhpietil, which is to use some measure of average weather for the long-term forecast. For instance if it was temperature, you only have a reasonable temperature forecast for the next 14 days, but after that you could switch to the historical average temperature for each day, or monthly average temperature.
