### ISSUE TITLE
Quarterly Seasonality with Monthly Data

### ISSUE THREAD

**Issue by cdeterman** [facebook/prophet#1018]
I have seen other issues such as #596 and I have seen in the [documentation](https://facebook.github.io/prophet/docs/multiplicative_seasonality.html) how to add quarterly seasonality.  However, those all seem to imply that I continue to work with daily data.  What if I have monthly data?  Would the approach still be the same?  There are two questions in particular I would like to touch on.

1. The 'period' argument is intended to be set as the number of days in a quarter.  Would I still use the ~91.25 value?

2. Does the quarterly seasonality discover the 'cutpoints' for the quarters on its own or are they expected to be at typical start points.  For example, typical quarters may start in January, April, July, and October.  If those vary between datasets, would it matter how I define the quarterly seasonality?

**Comment by djrscally** [comment]
@cdeterman 

1. if you have a data point per month, you would not use the 91.25 period. Instead, have the period be 3 (since there are 3 months in a quarter)
2. The seasonality start point is irrelevant. All that's really relevant is that the effect of the seasonality (I.E. a high point or a low point) be repeated every n periods, where n is the value you set when defining the seasonality.

**Comment by bletham** [comment]
Actually, the model is continuous-time and so when it comes to specifying seasonalities, the frequency of the data doesn't matter.
1. Yes, the period should still be the number of days in a quarter, ~91.25.
2. Here what @djrscally says is correct: the seasonality will learn a smooth, cyclic effect that is repeated every 91.25 (if that's the period) days, so in that sense there is no starting point.

**Comment by djrscally** [comment]
Oh TIL! My bad, thanks for the correction @bletham  :)

**Comment by cdeterman** [comment]
@bletham thank you, just to confirm, the 91.25 would apply even if the data is monthly as opposed to daily data (i.e. 1 data point per month)?

**Comment by bletham** [comment]
That's correct.
