### ISSUE TITLE
custom holidays

### ISSUE THREAD

**Issue by andrewng88** [facebook/prophet#1022]
Hi,

Unfortunately my country is not in the list hence I have to use another library ( workalendar ) to generate the dataframe called holidays

Pls advise if did this correctly.

the library created a dataframe and I labelled the columns to be
ds _( date )_ , holiday _( type )_ to conform to fb prophet.

Then I use
m=Prophet(holidays=holidays)

I didn't include lower_window and upper_window at the moment and leave it as default. 

Did I implement correctly?

Also if Saturday and Sundays are 0 as it's close, is it possible to set this

Thanks.

**Comment by daikonradish** [comment]
Do you have a code sample?

**Comment by andrewng88** [comment]
Sure

```
# import holiday library
# https://pypi.org/project/holidays/
from datetime import date
from workalendar.asia import Singapore

#initialize cal for SG holdays
cal = Singapore()

#input SG holidays for year 2019 and 2020
year_2019=pd.DataFrame(cal.holidays(2019))

#rename column 0
y2019.rename(columns={0:'ds',1:'holiday'}, inplace=True)

#initiate the Prophet instance with holiday
m=Prophet(holidays=y2019_2020)

#fit df to model
m.fit(df)
```

**Comment by daikonradish** [comment]
You seem to have done it right, see [here](https://github.com/facebook/prophet/blob/master/python/fbprophet/forecaster.py#L53). You should also look at the `component_plot` - it will show trends (it'll look like spikes) at the dates of the holidays in Singapore.

You may want to include the windows; that's usually also useful.

**Comment by andrewng88** [comment]
OK thanks got it.

By the way, do you happen to know how do one set Saturday / Sunday = 0 as perpetually closed.

**Comment by djrscally** [comment]
If you mean that the predicted value should always be 0 on those dates, there's not really a way to force the model to honour that limit. You can simply set it in the forecast dataset afterwards:

```Python
forecast.loc[forecast.yhat < 0, 'yhat'] = 0
```
