### ISSUE TITLE
How to add custom seasonality in a groupby forecast in R

### ISSUE THREAD

**Issue by PyDataBlog** [facebook/prophet#1024]
Hi I am currently stuck trying to add custom seasonality in a groupby operation in R. 

I am porting this Python code to R. Here's the python code:

```py
m = Prophet(holidays = custom_events, yearly_seasonality=False,
            weekly_seasonality=False, daily_seasonality=False)

m.add_seasonality(name='monthly', period=30.5, fourier_order=5)
m.add_seasonality(name='weekly', period=7, fourier_order=20)

m.fit(df)

future_training = m.make_future_dataframe(periods=7*30)

forecast_training = m.predict(future_training)
```

I want to use this model in R to make a groupby forecast for some groups. Here's my current code which is missing the addition of the `add_seasonality` function to the groupby operation. 

```R
df2 <- df %>% 
  group_by(some_group) %>% 
  do(predict(prophet(., 
                     holidays = custom_events,
                     yearly.seasonality = FALSE,
                     weekly.seasonality = FALSE,
                     daily.seasonality = FALSE), 
             make_future_dataframe(prophet(.,
                                           holidays = events,
                                           yearly.seasonality = FALSE,
                                           weekly.seasonality = FALSE,
                                           daily.seasonality = FALSE), 
                                   periods = 30*7))) %>%
  select(ds, some_group, yhat)
```
How can I add `add_seasonality` function in the groupby operations?

**Comment by daikonradish** [comment]
Do you mean that you wish to: 
  1. do separate predictions for all the groups?
  2. do only one global prediction, with the groups being binary indicators of some other value?

From your code snippet, it seems like you're doing (1). I would encourage you to look at [purrr](https://purrr.tidyverse.org/), whose `split` and `map` functions would seem apropos for this task

**Comment by PyDataBlog** [comment]
@daikonradish I'm trying to 1. I just am lost in between passing the data stream around the functions.

**Comment by daikonradish** [comment]
https://stackoverflow.com/questions/42820696/using-prophet-package-to-predict-by-group-in-dataframe-in-r

This directly addresses what you need.
