### ISSUE TITLE
Running fbprophet with dask

### ISSUE THREAD

**Issue by ohashmi1** [facebook/prophet#1028]
HI I just a general question if anyone has tried to run prophet on a dask cluster. I currently have a setup with 3 workers, however dask isn't distributing the work to all the workers. It seems like its running it serially. So has anyone been able to run it on a dask cluster?

My problem is I need to run at least 60000 different times series for about 2k records. What would be an efficient way to run it?

Thank you

**Comment by bletham** [comment]
I haven't used dask and don't have any suggestions to give, and unfortunately it seems noone else did either. If someone runs into this in the future feel free to re-open!
