### ISSUE TITLE
When building Prophet models should I consider differencing as a transformation to make my series stationary?

### ISSUE THREAD

**Issue by rydevera3** [facebook/prophet#1029]
Hello all!

I have been doing a lot of work around time series forecasting as of late. When my series are not stationary I consider different methods to transform the series to be stationary one of the best is often n-levels of differencing which models like ARIMA already incorporate. When I do not have a stationary series is it beneficial to use differencing before modeling with Prophet?

**Comment by daikonradish** [comment]
Prophet isn’t ARIMA. In general you don’t need to have stationarity for Prophet to work well. See #234.
