### ISSUE TITLE
How can I tune my prophet model given some live data

### ISSUE THREAD

**Issue by Saranya0721** [facebook/prophet#1030]
How to pass livedata to prophet?

**Comment by bletham** [comment]
Could you explain what you mean by live data?

**Comment by Saranya0721** [comment]
Suppose if i want find the anomaly for my system cpu %,  I have a script which will read the cpu % every 5 secs and store it in db. How to feed these every 5 secs data to prophet model. ?

**Comment by bletham** [comment]
I see, this is related to #46, which is basically how do you incrementally update a model with new data. There isn't any way to do that right now; the model has to be re-fit from scratch every time. So you'd want to set up a training job that, however often you need to update the model, pulls all of the data from the db and fits a model.
