### ISSUE TITLE
Multiple seasonalities with different modes

### ISSUE THREAD

**Issue by alexgawrilow** [facebook/prophet#1037]
I have a time series of hourly data that has a trend (t), yearly seasonality (y), weekly seasonality (w) and daily seasonality (d).\
The time series can be described by first creating an additive model of daily data

s_daily = t + y + w.

Afterwards the value for each day gets distributed multiplicatively by the daily model that consists of percentages for each hour.

s_hourly = d * s_daily = d * (t + y + w).

Is it for prophet possible to model such behaviour? When I add yearly and weekly seasonality to the prophet model as "additive" and daily seasonality as "multiplicative", only the trend component gets multiplied by the daily seasonality and afterwards the weekly and yearly seasonality are added:

s = t * d + y + w.

I need prophet to be able to first add yearly and weekly seasonality to the trend and multiply the result with the daily seasonality, like described above:

 s = d * (t + y + w).

**Comment by daikonradish** [comment]
You likely need two models; refer to #665. Here’s a suggestion, your mileage may vary:

1. First fit s_daily using your additive model
2. Then fit s_hourly using the multiplicative model, adding s_daily as a regressor.
