### ISSUE TITLE
Erratic Monthly Forecasts

### ISSUE THREAD

**Issue by cdeterman** [facebook/prophet#1043]
I have some monthly data (one data point per month) that I want to try and forecast the next year.  After some initial exploration of the docs and and issue here I used the following code.

```python
m = Prophet(weekly_seasonality=False, daily_seasonality=False)
m.add_seasonality('quarterly', period=91.25, fourier_order=8)
m.fit(train_df)

future = m.make_future_dataframe(periods=12, freq = 'M')
forecast = m.predict(future)
m.plot(forecast)
```

However, the results seem to be very erratic despite what seems initially to me like a relatively simple time series.  If you see the image below, the model fits the monthly but subsequently jumps around for the prediction.  Any insight as to why this would be the case?  How can I stabilize the forecast?
 
![image](https://user-images.githubusercontent.com/3091179/60205315-8172d600-9816-11e9-9bd2-6fe511d4675f.png)

**Comment by daikonradish** [comment]
Here are some thoughts. Your mileage may vary.

1. If all that you would like is to stabilize your forecast, you should reduce `fourier_order` and also adjust `prior_scale`. According to [this](https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#prior-scale-for-holidays-and-seasonality), the default `prior_scale` is 10, which provides little regularization.
2. It would appear to me that in fact your data may be poorly modeled by Prophet, which uses a decomposable time series model with three components: trend, seasonality and holidays (if any). In fact your data seems to follow discrete jumps. For this reason you may wish to consider more appropriate generative models. One such model could be modeling the data in two portions: one, a Poisson process to describe when there is a discrete jump in the average value of `y`. Two, a random variable to describe how much `y` changes by when there is a change in this process. It should be fairly straightforward to do this in Stan.

**Comment by cdeterman** [comment]
@daikonradish interesting, I am very much interested in your second point.  In my case, I actually know when the jumps are likely to occur (even for future scenarios).  I thought I could define the cutpoints in the `Prophet` class instantiation but that didn't help much.  If you have any further documentation or resources regarding this type of problem I would sincerely appreciate it.

**Comment by daikonradish** [comment]
'you know when the jumps are likely to occur' - is the jump time, `t`, a random variable?

Is the quantity by which the value jumps, `q`, also a random variable?

**Comment by cdeterman** [comment]
@daikonradish the jump times are know points. I can essentially set them indefinitely in to the future similar to holidays but instead they are the only points that changes can occur.  So that is not random. The quantity by which ‘y’ jumps at each of those points is the task as it could go up, down, or even stay the same. As such, that would be the random variable.

**Comment by bletham** [comment]
@cdeterman could you post the components plot for this forecast with `m.plot_components(forecast)`?

I agree with @daikonradish that this time series doesn't seem to have the sort of structure that Prophet fits well (in particular, there is no visible seasonality) but I'm still a bit surprised by what the predictions look like. I'm guessing it has something to do with the seasonalities being overfit and would like to see them.
