### ISSUE TITLE
let's say you have data for Jan 1 to Dec 31. When you make prediction for say Feb 1, does it use data from Jan 1 to Jan 31..

### ISSUE THREAD

**Issue by dakshaladia** [facebook/prophet#1047]
I am new to prophet. I want to understand how this prediction thing works and on what basis.

thank you

**Comment by bletham** [comment]
To clarify - is this Feb 1 of the year that you have data for?

For example, you have data for Jan 1 of 2018 through Dec 31 of 2018, and make a prediction for Feb 1 of 2018? Then it will be using all of the data provided (including the datapoint on Feb 1 of 2018 if there was one). It is basically a regression model, and so you can imagine if you have y and x, and you have data for x between 0 and 10 and make a prediction for x=3, it will be using all of the data for that prediction.
