### ISSUE TITLE
Outliers detection problem

### ISSUE THREAD

**Issue by doomsdays12** [facebook/prophet#1050]
Hello, 
and thank you for sharing the Prophet model.
I want to predicted the maximum value of sample data, so i don't want to ignore the outliers, but i don't know how to change the codes.
Could you help me please?
Thank you in advance.

**Comment by Alexsbuchanan** [comment]
Can you share your current code?

**Comment by doomsdays12** [comment]
I'm using open source fbprophet code.

**Comment by doomsdays12** [comment]
> Can you share your current code?
I'm using open source fbprophet code.

**Comment by doomsdays12** [comment]
> Can you share your current code?
I'm using open source fbprophet code.

**Comment by doomsdays12** [comment]
> 你能分享一下你现在的代码吗？

import pandas as pd
#import nyphon as np
from fbprophet import Prophet
import matplotlib.pyplot as plt

'''''
df = pd.read_csv('F:\Download\prophet-master (2)\prophet-master\examples\example_wp_log_peyton_manning.csv')
df = pd.read_csv('G:\Desktop\data.csv')
'''

df = pd.read_csv('G:\Desktop\dat.csv')
df.head()
#df['y']=np.log(df['y']
#x2=df['y']
m = Prophet()
m.fit(df)
future = m.make_future_dataframe(periods=20)
future.tail()
forecast = m.predict(future)
df[['y']],forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()
#forecast[['ds','yhat_upper']].tail()
fig1 = m.plot(forecast)
plt.show()
fig2 = m.plot_components(forecast)
plt.show()

x1 = forecast['ds']
#x3 = df['ds']
x2 = df['y']
y1 = forecast['yhat']
y2 = forecast['yhat_lower']
y3 = forecast['yhat_upper']
#plt.plot(x3,x2)
fig3 = plt.plot(x1,y3)
plt.show()

**Comment by doomsdays12** [comment]
> Can you share your current code?

import pandas as pd
#import nyphon as np
from fbprophet import Prophet
import matplotlib.pyplot as plt

'''''
df = pd.read_csv('F:\Download\prophet-master (2)\prophet-master\examples\example_wp_log_peyton_manning.csv')
df = pd.read_csv('G:\Desktop\data.csv')
'''

df = pd.read_csv('G:\Desktop\dat.csv')
df.head()
#df['y']=np.log(df['y']
#x2=df['y']
m = Prophet()
m.fit(df)
future = m.make_future_dataframe(periods=20)
future.tail()
forecast = m.predict(future)
df[['y']],forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()
#forecast[['ds','yhat_upper']].tail()
fig1 = m.plot(forecast)
plt.show()
fig2 = m.plot_components(forecast)
plt.show()

x1 = forecast['ds']
#x3 = df['ds']
x2 = df['y']
y1 = forecast['yhat']
y2 = forecast['yhat_lower']
y3 = forecast['yhat_upper']
#plt.plot(x3,x2)
fig3 = plt.plot(x1,y3)
plt.show()

**Comment by doomsdays12** [comment]
> Can you share your current code?

`import pandas as pd
#import nyphon as np
from fbprophet import Prophet
import matplotlib.pyplot as plt

'''''
df = pd.read_csv('F:\Download\prophet-master (2)\prophet-master\examples\example_wp_log_peyton_manning.csv')
df = pd.read_csv('G:\Desktop\data.csv')
'''

df = pd.read_csv('G:\Desktop\dat.csv')
df.head()
#df['y']=np.log(df['y']
#x2=df['y']
m = Prophet()
m.fit(df)
future = m.make_future_dataframe(periods=20)
future.tail()
forecast = m.predict(future)
df[['y']],forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()
#forecast[['ds','yhat_upper']].tail()
fig1 = m.plot(forecast)
plt.show()
fig2 = m.plot_components(forecast)
plt.show()

x1 = forecast['ds']
#x3 = df['ds']
x2 = df['y']
y1 = forecast['yhat']
y2 = forecast['yhat_lower']
y3 = forecast['yhat_upper']
#plt.plot(x3,x2)
fig3 = plt.plot(x1,y3)
plt.show()`

**Comment by doomsdays12** [comment]
In addition, i also want to know what is the noise value of fbprophet, is there room for improvement?

**Comment by bletham** [comment]
I think the best you could do here is to use the `interval_width` argument to choose a wide uncertainty interval and use that. Like:
```
m = Prophet(interval_width=0.99)
```
would make it so `yhat_upper` is the top of a 99% prediction interval for y. This means (subject to model being correct, etc.) 0.5% chance of y being greater than yhat_upper. But that assumption of the model being correct means that it won't include outliers. The model assumes normally distributed noise, and if there are very large outliers then it really has no way of predicting outliers in the future. I think you'd need a different kind of model to do that.

The fitted noise standard deviation is
```
m.params['sigma_obs'] * m.y_scale
```
from here:
https://github.com/facebook/prophet/blob/0d37a46593c7a1e0b8706be60a3d594ac3285c73/python/fbprophet/forecaster.py#L1414

**Comment by doomsdays12** [comment]
> I think the best you could do here is to use the `interval_width` argument to choose a wide uncertainty interval and use that. Like:
> 
> ```
> m = Prophet(interval_width=0.99)
> ```
> 
> would make it so `yhat_upper` is the top of a 99% prediction interval for y. This means (subject to model being correct, etc.) 0.5% chance of y being greater than yhat_upper. But that assumption of the model being correct means that it won't include outliers. The model assumes normally distributed noise, and if there are very large outliers then it really has no way of predicting outliers in the future. I think you'd need a different kind of model to do that.
> 
> The fitted noise standard deviation is
> 
> ```
> m.params['sigma_obs'] * m.y_scale
> ```
> 
> from here:
> https://github.com/facebook/prophet/blob/0d37a46593c7a1e0b8706be60a3d594ac3285c73/python/fbprophet/forecaster.py#L1414

The outliers are not too large.  
![image](https://user-images.githubusercontent.com/38744690/60751587-60ff0480-9fea-11e9-99e6-becce8c7ca9e.png)

**Comment by bletham** [comment]
Sorry, I'm not sure what you mean and what exactly you want yhat_upper to be. yhat_upper will be the upper bound of a prediction interval for y.

**Comment by doomsdays12** [comment]
> Sorry, I'm not sure what you mean and what exactly you want yhat_upper to be. yhat_upper will be the upper bound of a prediction interval for y.

I still want to know how do I improve the value of confidence interval. Thanks for your reply again.

**Comment by bletham** [comment]
If you want it to be narrower, then make the `interval_width` argument to `Prophet()` smaller (for instance, 0.5 instead of the default 0.8). If you want it to be wider, you can make that value larger. Besides that, I don't know that I have a whole lot to suggest; Changing the trend prior scale will affect the future uncertainty interval, like described here: https://facebook.github.io/prophet/docs/trend_changepoints.html#adjusting-trend-flexibility

**Comment by doomsdays12** [comment]
> If you want it to be narrower, then make the `interval_width` argument to `Prophet()` smaller (for instance, 0.5 instead of the default 0.8). If you want it to be wider, you can make that value larger. Besides that, I don't know that I have a whole lot to suggest; Changing the trend prior scale will affect the future uncertainty interval, like described here: https://facebook.github.io/prophet/docs/trend_changepoints.html#adjusting-trend-flexibility

Besides that, could you tell me how to make the figure of output only to show the yhat_upper and y.

**Comment by doomsdays12** [comment]
> If you want it to be narrower, then make the `interval_width` argument to `Prophet()` smaller (for instance, 0.5 instead of the default 0.8). If you want it to be wider, you can make that value larger. Besides that, I don't know that I have a whole lot to suggest; Changing the trend prior scale will affect the future uncertainty interval, like described here: https://facebook.github.io/prophet/docs/trend_changepoints.html#adjusting-trend-flexibility

Besides that, could you tell me how to make the figure of output only to show the yhat_upper and y.
If I want to make a change to a trend item, which part of the code should I modify? Why does the value of estimate yhat separate from confidence interval at sometimes.

**Comment by bletham** [comment]
If you want to make changes to the plot, you will just have to write your own plotting code. The plotting code is not very many lines:
https://github.com/facebook/prophet/blob/480b67b8fed05381b910bce6e7a64efba9f0d838/python/fbprophet/plot.py#L41

and you could copy it out and make edits. In particular, to show only yhat_upper and y you would have to change this line:
https://github.com/facebook/prophet/blob/480b67b8fed05381b910bce6e7a64efba9f0d838/python/fbprophet/plot.py#L76

You will need to know how to use matplotlib in order to do this.

How is confidence interval calculated: This is described at a high level in the documentation here: https://facebook.github.io/prophet/docs/uncertainty_intervals.html , for more details I'd have to refer you to Section 3.1.4 of the paper: https://peerj.com/preprints/3190.pdf

**Comment by doomsdays12** [comment]
Thank you very much for your detailed reply.
