### ISSUE TITLE
Function to fetch p-values,estimates for external regressors to determine the strength of each variable

### ISSUE THREAD

**Issue by akshaykapila20392** [facebook/prophet#1053]

**Comment by bletham** [comment]
The right way to do this would be to do MCMC sampling, which will give you an uncertainty estimate for the effect of the external regressor.  See here: https://facebook.github.io/prophet/docs/uncertainty_intervals.html#uncertainty-in-seasonality (everything describes there for seasonality is the same for extra regressors).

If the uncertainty interval for the extra regressor is different than zero, then that provides evidence that the regressor has a significant impact on y (at whatever uncertainty level is specified with `interval_width`, see a bit higher up in that same page of documentation).
