### ISSUE TITLE
If I forecast after cross validation will it give me better result? Should i use the model to forecast which i received from cross validation or the model i received after fitting the training data?

### ISSUE THREAD

**Issue by dakshaladia** [facebook/prophet#1055]

**Comment by djrscally** [comment]
The model after use in cross_validation **is** the model you received after fitting the training data. Cross validation does not alter the model fit at all, it just evaluates it.

**Comment by xiaoyaoyang** [comment]
It is good to use the CV function to simulate a rolling window forecast though..
