### ISSUE TITLE
Why is the forecast data empty

### ISSUE THREAD

**Issue by rockyCheung** [facebook/prophet#1056]
I use Logistic Regression model to forecast the trend of stock in the next 200 days. Why is the forecast data empty?

**Comment by daikonradish** [comment]
Could you please include a code snippet?

**Comment by rockyCheung** [comment]
# -*- coding:utf-8 -*-
import pandas as pd
from fbprophet import Prophet
import matplotlib.pyplot as plt
import os
from for_future import logger
import click
from datetime import *


class PredictFuture(Prophet):
    def __init__(self,
            growth='linear',
            changepoints=None,
            n_changepoints=25,
            changepoint_range=0.8,
            yearly_seasonality='auto',
            weekly_seasonality='auto',
            daily_seasonality='auto',
            holidays=None,
            seasonality_mode='additive',
            seasonality_prior_scale=10.0,
            holidays_prior_scale=10.0,
            changepoint_prior_scale=0.05,
            mcmc_samples=0,
            interval_width=0.80,
            uncertainty_samples=1000,file=None,data_frame = None,distortion = 0.001):
        
        self._distortion = distortion
        self._file = file
        if file is not None and not os.path.exists(file):
            curdir = os.path.abspath(os.path.dirname(__file__))
            self._file = os.path.join(curdir, file)
        if file is not None and  os.access(self._file, os.R_OK):
            self._df = pd.read_csv(self._file)
            self._df.head()
        elif data_frame is not None:
            self._df = data_frame
        else:
            raise Exception('Can\'t found the file %s',self._file)
        super().__init__(growth,
              changepoints,
              n_changepoints,
              changepoint_range,
              yearly_seasonality,
              weekly_seasonality,
              daily_seasonality,
              holidays,
              seasonality_mode,
              seasonality_prior_scale,
              holidays_prior_scale,
              changepoint_prior_scale,
              mcmc_samples,
              interval_width,
              uncertainty_samples)

    def seeFuture(self,periods, freq, include_history):
       
        if self.growth == 'logistic' and 'floor' in self._df:
            self._df['floor'] = self._df.apply(lambda x: self.checkCapFloor(x.cap, x.floor), axis=1)
        
        self.fit(self._df)
      
        self._future = self.make_future_dataframe(periods, freq, include_history)
        if self.growth == 'logistic':
            self._future['cap'] = self._df['cap']
            if 'floor' in self._df:
                self._future['floor'] = self._df['floor']

        predict_set = self._future.tail()
        self._forecast = self.predict(self._future)

    def getTopTail(self, top):
        forecast_set = self._forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(top)
        return forecast_set

    def drawForecast(self):
        self.plot(self._forecast);
        plt.show()
    def drawTrend(self):
        self.plot_components(self._forecast);
        plt.show()
    def saveDataFrame(self,path):
        generate_file_name = lambda name:'predict_'+ name + '.csv'
        svaeFile = os.path.join(path, generate_file_name(str(datetime.now())))
        self._forecast.to_csv(svaeFile , index=False, header=False)

    def checkCapFloor(self , cap , floor):
        if cap <= floor:
            return floor - self._distortion
        else:
            return floor

from for_future.predict import PredictFuture
import os
from for_future.stock.stockdata import StockData
from datetime import *
import pandas as pd

def test_saveDataFrame():
    curdir = os.path.abspath(os.path.dirname(__file__))
    path = os.path.join(curdir, 'sample/predict_2019-06-18 13:21:44.369742.csv')
    predict_future = PredictFuture(file=path)
    predict_future.seeFuture(periods=20, freq='D', include_history=True)
    predict_future.saveDataFrame(curdir)

def test_stock_predict():
    stock_code = '000651'
    obj = StockData(stock_code)  # 创建股票交易类对象
    data = obj.history(start='1996-11-18', end='2019-06-27')  # 获取浦发银行2019年1月份的历史数据
    # print('@@@',data)
    ds = {'ds':data['date'],'y':data['close'] ,'cap':data['high'] , 'floor':data['low'], 'low':data['low']}
    predict_data = pd.DataFrame(ds)
    #保存查询数据到csv文件
    curdir = os.path.abspath(os.path.dirname(__file__))
    generate_file_name = lambda name: 'predict_' + name + '(' +stock_code+ ')' + '.csv'
    svaeFile = os.path.join(curdir, generate_file_name(str(datetime.now())))
    predict_data.to_csv(svaeFile, index=False, header=False)
    #预测数据
    predict_future = PredictFuture(growth='logistic',data_frame=predict_data)
    # predict_future = PredictFuture(data_frame=predict_data)
    predict_future.seeFuture(periods=100, freq='D', include_history=True)
    predict_future.saveDataFrame(curdir)
    predict_future.drawForecast()
    predict_future.drawTrend()

**Comment by bletham** [comment]
Could you check that predict is being called, by looking at the values of these things:
```
predict_future._future
predict_future._forecast
```
And you can make sure the model was fit by looking at
```
predict_future.history
```
Are all of those non-empty?

**Comment by rockyCheung** [comment]
stock_code = '000651'
    obj = StockData(stock_code)  # 创建股票交易类对象
    data = obj.history(start='1996-11-18', end='2019-07-07')  # 获取浦发银行2019年1月份的历史数据
    # print('@@@',data)
    ds = {'ds':data['date'],'y':data['close'] ,'cap':data['high'] , 'floor':data['low'], 'low':data['low']}
    predict_data = pd.DataFrame(ds)
    #保存查询数据到csv文件
    curdir = os.path.abspath(os.path.dirname(__file__))
    generate_file_name = lambda name: 'predict_' + name + '(' +stock_code+ ')' + '.csv'
    svaeFile = os.path.join(curdir, generate_file_name(str(datetime.now())))
    predict_data.to_csv(svaeFile, index=False, header=False)
    #预测数据
    predict_future = PredictFuture(growth='logistic',data_frame=predict_data)

    # predict_future = PredictFuture(data_frame=predict_data)
    predict_future.seeFuture(periods=5, freq='D', include_history=True)
    predict_future.saveDataFrame(curdir)
    print(predict_future._future)
    print(predict_future._forecast)
    
**print out the result like this:**
5263 2019-07-05  58.180  56.750
5264 2019-07-06     NaN     NaN
5265 2019-07-07     NaN     NaN
5266 2019-07-08     NaN     NaN
5267 2019-07-09     NaN     NaN
5268 2019-07-10     NaN     NaN

5263 2019-07-05  57.531468  ...                         0.0  57.537265
5264 2019-07-06        NaN  ...                         0.0        NaN
5265 2019-07-07        NaN  ...                         0.0        NaN
5266 2019-07-08        NaN  ...                         0.0        NaN
5267 2019-07-09        NaN  ...                         0.0        NaN
5268 2019-07-10        NaN  ...                         0.0        NaN
Thank you for your reply~

**Comment by bletham** [comment]
Oh, I see what's happening. The issue is in
```
self._future['cap'] = self._df['cap']
```
Pandas will let you assign a column with an array of a different length, and will fill in NaNs for everything left over. For instance,
```
df = pd.DataFrame({'a': [1, 2, 3, 4]})
df2 = pd.DataFrame({'b': [1, 2, 3, 4, 5, 6, 7]})
df2['a'] = df['a']
print(df2)
#    b    a
# 0  1  1.0
# 1  2  2.0
# 2  3  3.0
# 3  4  4.0
# 4  5  NaN
# 5  6  NaN
# 6  7  NaN
```

So all of the future values are getting NaN for `cap` and `floor`, which leads to `NaN` for the prediction. If you set numeric values for future values of `cap` and `floor` this should all work.

**Comment by rockyCheung** [comment]
thank you for your replay

发自我的iPhone


------------------ Original ------------------

**Comment by rockyCheung** [comment]
Thanks for your help
