### ISSUE TITLE
Fail to install fbprophet:INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_861b75c6337e237650a61ae58c4385ef NOW.   error: command 'gcc' failed with exit status

### ISSUE THREAD

**Issue by atptour2017** [facebook/prophet#1057]
Try to install fbprophet in Centos 7 python3.6 virtualenv. But it failed:
First I installed pystan successfully. Then I run pip install fbprophet. But it always failed.

The error info:
(py36) [chendan@localhost ~]$ pip install -i https://pypi.douban.com/simple fbprophet
Looking in indexes: https://pypi.douban.com/simple
Collecting fbprophet
  Using cached https://pypi.doubanio.com/packages/33/fb/ad98d46773929079657706e6b2b6e366ba6c282bc2397d8f9b0ea8e5614c/fbprophet-0.5.tar.gz
Requirement already satisfied: Cython>=0.22 in ./.virtualenvs/py36/lib/python3.6/site-packages (from fbprophet) (0.29.11)
Requirement already satisfied: pystan>=2.14 in ./.virtualenvs/py36/lib/python3.6/site-packages (from fbprophet) (2.19.0.0)
Requirement already satisfied: numpy>=1.10.0 in ./.virtualenvs/py36/lib/python3.6/site-packages (from fbprophet) (1.16.3)
Requirement already satisfied: pandas>=0.23.4 in ./.virtualenvs/py36/lib/python3.6/site-packages (from fbprophet) (0.24.2)
Requirement already satisfied: matplotlib>=2.0.0 in ./.virtualenvs/py36/lib/python3.6/site-packages (from fbprophet) (3.1.0)
Requirement already satisfied: lunardate>=0.1.5 in ./.virtualenvs/py36/lib/python3.6/site-packages (from fbprophet) (0.2.0)
Requirement already satisfied: convertdate>=2.1.2 in ./.virtualenvs/py36/lib/python3.6/site-packages (from fbprophet) (2.1.3)
Requirement already satisfied: holidays>=0.9.5 in ./.virtualenvs/py36/lib/python3.6/site-packages (from fbprophet) (0.9.10)
Requirement already satisfied: setuptools-git>=1.2 in ./.virtualenvs/py36/lib/python3.6/site-packages (from fbprophet) (1.2)
Requirement already satisfied: pytz>=2011k in ./.virtualenvs/py36/lib/python3.6/site-packages (from pandas>=0.23.4->fbprophet) (2019.1)
Requirement already satisfied: python-dateutil>=2.5.0 in ./.virtualenvs/py36/lib/python3.6/site-packages (from pandas>=0.23.4->fbprophet) (2.8.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in ./.virtualenvs/py36/lib/python3.6/site-packages (from matplotlib>=2.0.0->fbprophet) (2.4.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ./.virtualenvs/py36/lib/python3.6/site-packages (from matplotlib>=2.0.0->fbprophet) (1.1.0)
Requirement already satisfied: cycler>=0.10 in ./.virtualenvs/py36/lib/python3.6/site-packages (from matplotlib>=2.0.0->fbprophet) (0.10.0)
Requirement already satisfied: ephem<3.8,>=3.7.5.3 in ./.virtualenvs/py36/lib/python3.6/site-packages (from convertdate>=2.1.2->fbprophet) (3.7.6.0)
Requirement already satisfied: six in ./.virtualenvs/py36/lib/python3.6/site-packages (from holidays>=0.9.5->fbprophet) (1.12.0)
Requirement already satisfied: setuptools in ./.virtualenvs/py36/lib/python3.6/site-packages (from kiwisolver>=1.0.1->matplotlib>=2.0.0->fbprophet) (41.0.1)
Building wheels for collected packages: fbprophet
  Building wheel for fbprophet (setup.py) ... error
  ERROR: Complete output from command /home/chendan/.virtualenvs/py36/bin/python3.6 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-3a803zoa/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-kzu0pupk --python-tag cp36:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/fbprophet
  creating build/lib/fbprophet/stan_model
  INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_861b75c6337e237650a61ae58c4385ef NOW.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for fbprophet
  Running setup.py clean for fbprophet
Failed to build fbprophet
Installing collected packages: fbprophet
  Running setup.py install for fbprophet ... error
    ERROR: Complete output from command /home/chendan/.virtualenvs/py36/bin/python3.6 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-3a803zoa/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-r9yg3pcq/install-record.txt --single-version-externally-managed --compile --install-headers /home/chendan/.virtualenvs/py36/include/site/python3.6/fbprophet:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/fbprophet
    creating build/lib/fbprophet/stan_model
    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_861b75c6337e237650a61ae58c4385ef NOW.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/home/chendan/.virtualenvs/py36/bin/python3.6 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-3a803zoa/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-r9yg3pcq/install-record.txt --single-version-externally-managed --compile --install-headers /home/chendan/.virtualenvs/py36/include/site/python3.6/fbprophet" failed with error code 1 in /tmp/pip-install-3a803zoa/fbprophet/

**Comment by bletham** [comment]
This usually means that the C++ compiler isn't hooked up correctly to PyStan. PyStan will successfully install even if it is not able to function correctly.

You can use this code to check that pystan is working (which I'm pretty sure it is not):
```
import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this will take a minute
y = model.sampling(n_jobs=1).extract()['y']
y.mean()  # should be close to 0
```

The reason it isn't working is because CentOS 7 does not support C++14, which is a new requirement for the latest version of PyStan.  The solution is to downgrade to PyStan 2.18: https://github.com/stan-dev/pystan/issues/583

**Comment by atptour2017** [comment]
Your are correct! Great! Thanks a lot!

**Comment by fcamuz** [comment]
Hello, I have the same problem with installing fbprophet.  I try to downgrade pytan, i get follwing error. 

ERROR: Cannot uninstall 'pystan'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

I have been searching for 3 days. I have tried to remove the folder, I could not. I try to uninstall pystan manually but I do not know-how. Can you please help me.

**Comment by bletham** [comment]
@fcamuz did you install pystan separately or was it installed automatically when installing fbprophet? Did you use pip to install fbprophet?

**Comment by parichayc** [comment]
Hi, I was facing similar issue on my Fedora 31 system, and solved it using:

**Comment by krishnafims** [comment]
In Red Hat / Cantos 7:-
--------------------------
first uninstall the pystan :- 

# sudo pip3 uninstall  pystan

then pystan install with this version:-

# sudo pip3 install pystan==2.18


Because pystan 2.19 version is not supported in RedHat / Centos 7.

**Comment by ieipi** [comment]
have the same issue and downgrade pystan to 2.18 solved the problem

**Comment by krishnafims** [comment]
Cool

**Comment by arvindharul** [comment]
conda install -c conda-forge pystan
This helped me to solve the problem

**Comment by pnmartinez** [comment]
My usual go-to "killed them all" solution worked:

```
apt-get install build-essential 
apt-get install libncursesw5-dev 
apt-get install libreadline-gplv2-dev 
apt-get install libssl-dev 
apt-get install libgdbm-dev 
apt-get install libc6-dev 
apt-get install libsqlite3-dev 
apt-get install libbz2-dev 
apt-get install libffi-dev 
apt-get install zlib1g-dev
```

Also ensure `pystan` is installed through `pip`.

**Comment by tedtran2016** [comment]
Thanks YiminYang980510! I followed your method, and I can install Prophet this way instead of "pip install prophet".

**Comment by HieuNguyenPhi** [comment]
For MacOS, I found that it worked by just installing Command Line Tools for Xcode, then installing pystan==2.19 and finally installing fbprophet with pip.

**Comment by stevenuray** [comment]
I also faced this problem running builds on Jenkins with kubernetes, if I didn't give the build agent pod enough memory/CPU it would throw this error

**Comment by fsilvestre** [comment]
Sometims it's just because you didn't installed Python Dev or Development Tools, but let's share what's working with a "minimal installation"
To compile with CentOS7:

```
yum groupinstall "Development Tools"
yum install python3-devel centos-release-scl
yum install devtoolset-11
source scl_source enable devtoolset-11
```

Then you can install prophet under your env:
```
pip install wheel
pip install numpy #To build wheel for prophet without error
pip install prophet
```

That was checked 3 times to be sure.
I don't know what specific packages from Development Tools are needed. Someone with available time could refine this.
