### ISSUE TITLE
Code Error

### ISSUE THREAD

**Issue by siddharthgarg89** [facebook/prophet#1061]
While running, the sample code provided for the R package, I get an error at the following step - 

m <- prophet(df)

Error in as.environment(where) : invalid 'pos' argument

**Comment by daikonradish** [comment]
Which sample code are you running?

Could you provide the full set of code you’re running, and if possible could you also install devtools and provide devtools::session_info?

**Comment by mafmafm** [comment]
I had the same problem. Someone can help me?

prophet::prophet(AirPassengers)
Error in as.environment(where) : invalid 'pos' argument

**Comment by bletham** [comment]
@mafmafm AirPassengers is the wrong format for the input to `prophet`; it needs to be a dataframe with columns `ds` and `y`, see https://facebook.github.io/prophet/docs/quick_start.html for example.
