### ISSUE TITLE
Mildly misleading installation instructions

### ISSUE THREAD

**Issue by djrscally** [facebook/prophet#1062]
Ref. installing on Windows. On the [installation](https://facebook.github.io/prophet/docs/installation.html) page we're told:

>On Windows, PyStan requires a compiler so you’ll need to follow the instructions. The key step is installing a [recent C++ compiler.](https://visualstudio.microsoft.com/visual-cpp-build-tools/)

The compiler link is to VS build tools, where the compiler is cl.exe. PyStan's installation page specifically says that compiler is unsupported:

>PyStan is tested against the mingw-w64 compiler which works on both Python versions (2.7, 3.x) and supports x86 and x64.
>
>Due to problems with MSVC template deduction, functions with Eigen library are failing. Until this and other bugs are fixed no support is provided for Windows + MSVC. Currently, no fix is known for this problem, other than to change the compiler to GCC or clang-cl.

**Comment by bletham** [comment]
Good catch! I just removed that, and in its place put "The easiest way to install Prophet in Windows is in Anaconda."

**Comment by djrscally** [comment]
Groovy! Easiest way is right, I tried for hours to avoid touching Anaconda and had to give in :P

**Comment by bletham** [comment]
yeah, I tried for about a day and then gave up!

**Comment by stonebig** [comment]
could i have a link to the MSVC, ssue page ? if there is one

**Comment by bletham** [comment]
@stonebig https://pystan.readthedocs.io/en/latest/windows.html#windows
