### ISSUE TITLE
Why is my yhat is the same value as y in traindata

### ISSUE THREAD

**Issue by preeyapatr** [facebook/prophet#1063]
I have run Prophet code in r which train data is monthly 2017-2018 and test is 3 months of 2019
<img width="702" alt="Capture" src="https://user-images.githubusercontent.com/52739255/60954215-d3445180-a328-11e9-8440-33c958fb606d.PNG">

Why my train data is the same value as the Y hat

**Comment by bletham** [comment]
It looks like it's pretty badly overfitting to the training data. There isn't much seasonality in this time series, but it does have a lot of changepoints for the number of data points. What does the components plot look like? I'm guessing that the trend bounces around and that the model is using trend changepoints to try and hit all of the training data. If that's the case, then you can avoid that overfitting by reducing `changepoint_prior_scale`. Similarly, if the yearly seasonality is overfit, you could reduce `seasonality_prior_scale` (which at its default value of 10 applies basically no regularization).

**Comment by preeyapatr** [comment]
@bletham  is the reason can be about my train set has only 24 months? because when I was increasing the trainset to 25 months. It will not too fit like this. Does it is the limitation of the prophet? And I think that my model is not overfitting because its prediction is pretty good (MAPE=10)

Also, This is my components plot.
![image](https://user-images.githubusercontent.com/52739255/61116092-ff450b80-a4bd-11e9-9e12-413f3191d437.png)

and I still don't understand what is the value of the component plot. According to it has 2 months of January in 2 years. So why Prophet plot it in 1 value for each month? Can you describe of Prophet component plot for me? Am I correct to understand that yearly.seasonality is mention about the season in the same month in each year?

**Comment by bletham** [comment]
The model is that
```
y_hat(t) = trend(t) + seasonality(t)
```
where `seasonality(t)` adds/subtracts a fixed amount for each day of the year. So, every year the prediction on April 1 will be the current trend + whatever the yearly seasonality value for April 1 is.

It looks like the yearly seasonality is being overfit, so try cutting down the seasonality_prior_scale to `0.1` or `0.01` or so.

See also the documentation on monthly data, which is important for understanding the seasonality plot: https://facebook.github.io/prophet/docs/non-daily_data.html#monthly-data . The short story is that you will benefit from doing MCMC.
