### ISSUE TITLE
Can I get the interval width automatically by set the lower bound of the forecast value?

### ISSUE THREAD

**Issue by AgileQiqi** [facebook/prophet#1064]
I am trying to detect the probability of reaching the target value by using Prophet. So I want to set my target value as the lower bound of the forecast by Prophet and get the interval width automatically to let me know its distribution probability. Is there any function to set the yhat_lower and adjust the interval_width automatically? Or can I get the distribution probability by giving the input of the boundary?
![image](https://user-images.githubusercontent.com/44200374/60963907-5908d280-a312-11e9-8f16-36edc1a1226f.png)

**Comment by bletham** [comment]
I think the right approach here would be to use `m.predictive_samples(future)` (Py) or `predictive_samples(m, future)` (R) to directly sample from the posterior. I'll describe the output for Py but it's basically the same thing for R. It returns a dictionary with keys 'trend' and 'yhat', and the value for each is a matrix of posterior samples of `trend` and `yhat` respectively for each of the dates in `future`. For T future values, it is a  `T x uncertainty_samples` matrix of draws from the posterior of 'yhat' on the `T` dates. For a particular row `t`, You can then see the probability that `yhat(t) > Z` by counting the % of columns that are > Z. (It sounds like it is clear to you how to go from posterior samples to the desired probability but let me know if it isn't).

The number of samples, `uncertainty_samples`, is an argument to model initialization `Prophet()` that defaults to 1000.

**Comment by AgileQiqi** [comment]
@bletham Thanks a lot. That is actually the target I want to get. Prophet is really amazing to predict.
