### ISSUE TITLE
Predict should output predictions values

### ISSUE THREAD

**Issue by Nathan-Furnal** [facebook/prophet#1065]
I'm currently using the Python API.

I believe the current behavior of the ``predict`` method is counterintuitive and unhelpful.

It forces the user to create a new dataframe through ``make_future_dataframe`` and then use ``predict`` in order the catch the relevant values.

In my opinion, it should be easier to get the ``yhat`` values with something along the lines of : 

`m.predict(periods = nbr_periods)`

which then returns a numpy array or some similar structure and is more along the line of existing libraries such as ``statsmodels``.

Then, leave it to the user to use the whole dataframe output or create new dataframes.

Thanks

**Comment by djrscally** [comment]
I disagree. Anyone using Python is likely already familiar with scikit-learn's API conventions. Prophet's `predict()` call closely models [the scitkit-learn](https://scikit-learn.org/stable/glossary.html#term-predict) one by requiring you to pass a dataframe containing the same features as the training data.

The current behaviour is probably the best choice.

**Comment by bletham** [comment]
I think for some settings (like daily data, no regressors) an interface like `m.predict(periods = nbr_periods)` would capture most of the use case, but I agree with @djrscally that the flexibility to fully control the points at which predictions are made is really vital for a other significant settings, and I think worth the extra function call.

**Comment by Nathan-Furnal** [comment]
@djrscally @bletham Then I think it'd be closer to the spirit of sklearn if we could have a ``predict`` method outputting prediction dataframe right away without having to ``make_future_dataframe`` beforehand. It would be smoother imo to rely on arguments then.

Let me know what you think

**Comment by djrscally** [comment]
@Nathan-Furnal `make_future_dataframe` is just a convenience. For all but the simplest of models, you'll have to construct a dataframe associating the regressor values to the dates you want to predict for anyway.

Consider two scenarios:

**Daily data, no regressors.** 
In this case you can just call `m.predict(periods=90)` and effectively have the `make_future_dataframe(periods=90)` call be "inside" `predict()`. That's fine

**Working days only, extra regressors for "Last working day of month" and "Last working day of quarter".**

It's now much more difficult. `make_future_dataframe` just creates a dataframe for the number of periods you specify, and you'd have to manually remove the rows which are **not** working days (like weekends and public holidays). If you want that to happen automatically inside `predict()` then you'll have to include some logic to calculate "working days" and pass in the parameters that will be needed to govern that (like the country for example). You then need a means of tying the regressor values to the dates in your future dataframe. You could pass that as a list of dictionaries like:

```
[
	'regressor_name':{
		'2019-01-01':1,
		'2019-01-02':1,
		'2019-01-03':0,
		...
	},
	'regressor2_name:{...}
]
````

But at that point, you could just pass that to `pd.DataFrame()` anyway to build the dataframe outside the `predict()` call and have the flexibility to control all the regressors or perform other operations on the future dataframe or whatever.

I still think it's better to do this outside of `predict()`, sorry. Being able to just pass a number of periods would be nice in simple cases, but I think it doesn't make sense past that.

**Comment by Nathan-Furnal** [comment]
@djrscally I see where you're coming from, I'm just usually grabbing the values straight away but I understand it might not be everyone's case, thanks for your explanations.
