### ISSUE TITLE
Update R package with new country holidays

### ISSUE THREAD

**Issue by bletham** [facebook/prophet#1068]
#1052 adds country holidays for Korea. The CSV of country holidays that ships with the R package needs to be updated to include the new holiday dates.

**Comment by ryankarlos** [comment]
@bletham I can work on this as well whilst Im dealing with #1082
Are there country holidays for other countries that need to be added to `hdays.py` ?

**Comment by bletham** [comment]
This actually isn't really related to the code. Py version uses the holiday package to dynamically generate holiday dates, but there isn't a corresponding package for the R version. So what the R version does instead is it ships with a big CSV of pre-computed holiday dates (https://github.com/facebook/prophet/tree/master/R/data-raw). That CSV is created by running this script: https://github.com/facebook/prophet/blob/master/python/scripts/generate_holidays_file.py 
So it's really a matter of running that script in Py with an fbprophet install that includes #1052, to make sure the R version includes all of the same country holidays as the Py version.

**Comment by ryankarlos** [comment]
Ok thanks - just tried running `generate_holidays_file.py` and get this error: 
`Traceback (most recent call last):
  File "scripts/generate_holidays_file.py", line 19, in <module>
    import fbprophet.hdays as hdays_part2
  File "/prophet/python/fbprophet/__init__.py", line 8, in <module>
    from fbprophet.forecaster import Prophet
  File "/prophet/python/fbprophet/forecaster.py", line 19, in <module>
    from fbprophet.models import prophet_stan_model
  File "/prophet/python/fbprophet/models.py", line 24, in <module>
    prophet_stan_model = get_prophet_stan_model()
  File "/prophet/python/fbprophet/models.py", line 20, in get_prophet_stan_model
    with open(model_file, 'rb') as f:
`FileNotFoundError: [Errno 2] No such file or directory: '/prophet/python/fbprophet/stan_model/prophet_model.pkl`

**Comment by bletham** [comment]
@ryankarlos I think python is trying to load "fbprophet" from the "fbprophet" directory and not from the installed package. If you cd to a different directory it should work.

**Comment by bletham** [comment]
Also needs update for error fixed in #1191

**Comment by ryankarlos** [comment]
@bletham Thanks - actually Im running into issues when trying to install fbprophet dev version

```
(fbprophet-dev) MacBook-Air:python ryannazareth$ python setup.py develop
running develop
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_888a84912910fa0a45b9d614b75bb8a8 NOW.
error: command 'gcc' failed with exit status 1
```
Think this maybe mentioned in #1194 and #1154. So i tried running pystan import as you suggested in https://github.com/facebook/prophet/issues/1154#issuecomment-536234712 which seems to work.

```
>>> import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this will take a minute
y = model.sampling(n_jobs=1).extract()['y']
y.mean()  # should be close to 0
>>> model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
>>> model = pystan.StanModel(model_code=model_code)  # this will take a minute
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_5944b02c79788fa0db5b3a93728ca2bf NOW.
>>> y = model.sampling(n_jobs=1).extract()['y']

Gradient evaluation took 3.8e-05 seconds
1000 transitions using 10 leapfrog steps per transition would take 0.38 seconds.
Adjust your expectations accordingly!


Iteration:    1 / 2000 [  0%]  (Warmup)
Iteration:  200 / 2000 [ 10%]  (Warmup)
Iteration:  400 / 2000 [ 20%]  (Warmup)
Iteration:  600 / 2000 [ 30%]  (Warmup)
Iteration:  800 / 2000 [ 40%]  (Warmup)
Iteration: 1000 / 2000 [ 50%]  (Warmup)
Iteration: 1001 / 2000 [ 50%]  (Sampling)
Iteration: 1200 / 2000 [ 60%]  (Sampling)
Iteration: 1400 / 2000 [ 70%]  (Sampling)
Iteration: 1600 / 2000 [ 80%]  (Sampling)
Iteration: 1800 / 2000 [ 90%]  (Sampling)
Iteration: 2000 / 2000 [100%]  (Sampling)

 Elapsed Time: 0.021896 seconds (Warm-up)
               0.023321 seconds (Sampling)
               0.045217 seconds (Total)


Gradient evaluation took 8e-06 seconds
1000 transitions using 10 leapfrog steps per transition would take 0.08 seconds.
Adjust your expectations accordingly!


Iteration:    1 / 2000 [  0%]  (Warmup)
Iteration:  200 / 2000 [ 10%]  (Warmup)
Iteration:  400 / 2000 [ 20%]  (Warmup)
Iteration:  600 / 2000 [ 30%]  (Warmup)
Iteration:  800 / 2000 [ 40%]  (Warmup)
Iteration: 1000 / 2000 [ 50%]  (Warmup)
Iteration: 1001 / 2000 [ 50%]  (Sampling)
Iteration: 1200 / 2000 [ 60%]  (Sampling)
Iteration: 1400 / 2000 [ 70%]  (Sampling)
Iteration: 1600 / 2000 [ 80%]  (Sampling)
Iteration: 1800 / 2000 [ 90%]  (Sampling)
Iteration: 2000 / 2000 [100%]  (Sampling)

 Elapsed Time: 0.022484 seconds (Warm-up)
               0.024214 seconds (Sampling)
               0.046698 seconds (Total)


Gradient evaluation took 7e-06 seconds
1000 transitions using 10 leapfrog steps per transition would take 0.07 seconds.
Adjust your expectations accordingly!


Iteration:    1 / 2000 [  0%]  (Warmup)
Iteration:  200 / 2000 [ 10%]  (Warmup)
Iteration:  400 / 2000 [ 20%]  (Warmup)
Iteration:  600 / 2000 [ 30%]  (Warmup)
Iteration:  800 / 2000 [ 40%]  (Warmup)
Iteration: 1000 / 2000 [ 50%]  (Warmup)
Iteration: 1001 / 2000 [ 50%]  (Sampling)
Iteration: 1200 / 2000 [ 60%]  (Sampling)
Iteration: 1400 / 2000 [ 70%]  (Sampling)
Iteration: 1600 / 2000 [ 80%]  (Sampling)
Iteration: 1800 / 2000 [ 90%]  (Sampling)
Iteration: 2000 / 2000 [100%]  (Sampling)

 Elapsed Time: 0.026076 seconds (Warm-up)
               0.017728 seconds (Sampling)
               0.043804 seconds (Total)


Gradient evaluation took 1e-05 seconds
1000 transitions using 10 leapfrog steps per transition would take 0.1 seconds.
Adjust your expectations accordingly!


Iteration:    1 / 2000 [  0%]  (Warmup)
Iteration:  200 / 2000 [ 10%]  (Warmup)
Iteration:  400 / 2000 [ 20%]  (Warmup)
Iteration:  600 / 2000 [ 30%]  (Warmup)
Iteration:  800 / 2000 [ 40%]  (Warmup)
Iteration: 1000 / 2000 [ 50%]  (Warmup)
Iteration: 1001 / 2000 [ 50%]  (Sampling)
Iteration: 1200 / 2000 [ 60%]  (Sampling)
Iteration: 1400 / 2000 [ 70%]  (Sampling)
Iteration: 1600 / 2000 [ 80%]  (Sampling)
Iteration: 1800 / 2000 [ 90%]  (Sampling)
Iteration: 2000 / 2000 [100%]  (Sampling)

 Elapsed Time: 0.018307 seconds (Warm-up)
               0.018461 seconds (Sampling)
               0.036768 seconds (Total)

>>> y.mean()  # should be close to 0
-0.03992276070367646
```

I have a feeling it maybe due to my gcc version - im using what comes shipped with Xcode on MacOS - however also doing a `conda install gcc` also gives the same error (think that gcc version only goes up to 4.5).   Im using Pystan 2.19 and Python 3.7.

**Comment by bletham** [comment]
This is pushed to CRAN in v0.6
