### ISSUE TITLE
Possible licensing issue: lunardate is GPL

### ISSUE THREAD

**Issue by gsbowlin** [facebook/prophet#1069]
Similar to the pystan library being GPLv3 (https://github.com/facebook/prophet/issues/1045), it would be nice if lunardate was replaced with something also not GPLv3, so that prophet could be run without it. 

https://github.com/facebook/prophet/blob/master/python/requirements.txt
https://pypi.org/project/lunardate/0.1.5/

**Comment by bletham** [comment]
I can't seem to find an alternative, but if there is we'd be happy to make a swap. In the meantime, that package is used only in the file https://github.com/facebook/prophet/blob/master/python/fbprophet/hdays.py for built-in country holidays of countries with lunar holidays. If one needed, it would not be too much effort to modify that file to remove those countries and thus remove the dependence on lunardate.

**Comment by bletham** [comment]
#1091 replaces lunardate with LunarCalendar (MIT license)

**Comment by bletham** [comment]
This has been pushed to PyPI.

However, in the process of putting this on conda forge I discovered that LunarCalendar depends on ephem which is LGPL so I'm not sure how much was actually gained here.
