### ISSUE TITLE
Holiday Effects for Sub-Daily data

### ISSUE THREAD

**Issue by JainaProudmoore123** [facebook/prophet#1070]
Hello, I have **hourly data** with **daily seasonality**. How would one go about including holiday effects like Christmas day? There is a marked increase in value on holidays like Christmas.

**Comment by bletham** [comment]
If the holiday is specified with the usual holidays interface, then it will add a constant offset for the entire day. I imagine for hourly data you probably have some shape other than constant to the actual holiday effect. If you want to allow the holiday effect on Christmas to have a generic shape (like daily seasonality), then you can use a masked seasonality. Basically what you will do is define a "ChristmasSeasonality" that is a daily seasonality but only for Christmas. See the documentation here: https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#seasonalities-that-depend-on-other-factors

It would look like
```
m.add_seasonality(
    name='ChristmasSeasonality',
    period=1,  # 1-day period
    fourier_order=4,  # This is the default for the built-in daily seasonality
    condition_name='is_Christmas',
)
```
and you would add a binary column to your history and future dataframes that is 0 if the ds is not on Christmas, and 1 if it is on Christmas.

**Comment by bletham** [comment]
When you generate the components plot, it will have a panel for the ChristmasSeasonality that will show the effect applied to every Christmas.

**Comment by izalex1** [comment]
Hi @bletham 

Thanks for your comments; they are very helpful.

We have a situation when we have hourly data, but we want to use the incorporated .add holidays from prophet function, with specific country code, and apply it to hourly data to get the impact on these specific holidays

m.add_country_holidays(country_name='UK')

The things is we receive all zeros values when we plot the components.

Do you know what could be a problem? we have downgraded pandas, and still get the error.

Thanks much

**Comment by gregorjohnen** [comment]
Hi there, if we add user defined holiday dates via a custom defined dataframe to be latter fir to sub-daily data, woul we need to resample our holiday df from daily to hourly data or will the model itself add a constant offset for every hour of the day only based on the provided date? Many thanks in advance :)
