### ISSUE TITLE
can I supply my own innovations to generate simulated paths?

### ISSUE THREAD

**Issue by argku** [facebook/prophet#1071]
Can I supply my own sets of innovations to the forecast so that it generates the predicted paths?

I'm looking for a functionality similar to arima.sim() function in R with "innov" argument.

**Comment by bletham** [comment]
The model is fairly different from ARIMA, I'd be interested to learn more details about how you intend to use this so I could make sure what I suggest is consistent with what you're trying to estimate.

In Prophet the predictive uncertainty comes from three sources: simulating future trend changes, parameter uncertainty from MCMC, and a normal noise term. These are described in more detail in the documentation here: https://facebook.github.io/prophet/docs/uncertainty_intervals.html

If you want to replace all of those with your own process for generating future paths, then you can do this just by starting from the column `yhat` in the forecast dataframe (output of `predict`) and adding your innovations to that. If you wanted to replace only the normal noise term with some other noise process, then you will need to do the simulation of future paths yourself. This is the code used in Prophet to simulate future paths:
```
df = m.setup_dataframe(future.copy())
trend = m.sample_predictive_trend(df, 0)
seasonal_features, _, component_cols, _ = m.make_all_seasonality_features(df)
s_a = component_cols['additive_terms']
s_m = component_cols['multiplicative_terms']

beta = m.params['beta'][0]
Xb_a = np.matmul(seasonal_features.values, beta * s_a.values) * m.y_scale
Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)

sigma = m.params['sigma_obs'][0]
noise = np.random.normal(0, sigma, df.shape[0]) * m.y_scale

yhat = trend * (1 + Xb_m) + Xb_a + noise
```
so if you replace `noise` whatever error process you wanted and ran this simulation a bunch of times you could construct prediction intervals that way.

(This is related to #966, which is in part about having a better interface for innovations, so having a better sense of the use case to know how that should be supported would be helpful).

**Comment by argku** [comment]
I have a case where I model multiple series, each univariately, but when predicting I supply the simulation with correlated innovations. The common drivers capture the major correlations between series, and the correlated noise gets whatever is remaining, usually rather weak, correlations. It's somewhat like SUR, but in SUR they estimate the correlations simultaneously with regression. I estimate the correlations on the residuals of the independent univariate regressions. In fact they don't even need to be regressions, these could be residuals (noise) from ARIMA model. 

That's why I was wondering if I could get the noise term from Prophet's fits of independent series that I'm forecasting, then calculate the correlation between them. Finally, when running prediction simulation I thought to generate correlated noises for series, then supply them to Prophet.

**Comment by bletham** [comment]
I see, I think this process (estimate correlation in residuals, simulate future paths with those correlations) could be implemented with the code that I pasted above. All of the noise handling happens in
```
sigma = m.params['sigma_obs'][0]
noise = np.random.normal(0, sigma, df.shape[0]) * m.y_scale
```
so the independent normals there could be replaced by an MVN draw with the estimated correlations.
