### ISSUE TITLE
Cannot install the package on the server

### ISSUE THREAD

**Issue by chiquadrat** [facebook/prophet#1075]
Hello,

when I try to install the package on the server I get the following error. Any ideas how to fix it?

> install.packages("prophet")
Installing package into ‘/home/ruser/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/prophet_0.5.tar.gz'
Content type 'application/x-gzip' length 210535 bytes (205 KB)
==================================================
downloaded 205 KB

* installing *source* package ‘prophet’ ...
** package ‘prophet’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
installing via 'install.libs.R' to /home/ruser/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-prophet/00new/prophet
Compiling model (this will take a minute...)
Writing model to: /home/ruser/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-prophet/00new/prophet/libs
Compiling using binary: /usr/local/lib64/R/bin
Warning in system(cmd, intern = !verbose) :
  running command '/usr/local/lib64/R/bin/R CMD SHLIB file3b8c5ec357eb.cpp 2> file3b8c5ec357eb.cpp.err.txt' had status 1
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! In file included from /home/ruser/R/x86_64-pc-linux-gnu-library/3.6/BH/include/boost/random/detail/integer_log2.hpp:19:0,
                 from /home/ruser/R/x86_64-pc-linux-gnu-library/3.6/BH/include/boost/random/detail/int_float_pair.hpp:26,
                 from /home/ruser/R/x86_64-pc-linux-gnu-library/3.6/BH/include/boost/random/exponential_distribution.hpp:27,
                 from /home/ruser/R/x86_64-pc-linux-gnu-library/3.6/BH/include/boost/random/gamma_distribution.hpp:25,
                 from /home/ruser/R/x86_64-pc-linux-gnu-library/3.6/StanHeaders/include/stan/math/prim/mat/prob/dirichlet_rng.hpp:5,
                 from /home/ruser/R/x86_64-pc-linux-gnu-library/3.6/StanHeaders/include/stan/math/prim/mat.hpp:292,
                 from /home/ruser/R/x86_64-pc-linux-gnu-library/3.6/StanHeaders/include/stan/math/rev/mat.hpp:12,
                 from /home/ruser/R/x86_64-pc-linux-gnu-library/3.6/StanHeaders/inclu
Error in sink(type = "output") : invalid connection
* removing ‘/home/ruser/R/x86_64-pc-linux-gnu-library/3.6/prophet’
Warning in install.packages :
  installation of package ‘prophet’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpLj32Op/downloaded_packages’

Best, Paul

**Comment by chiquadrat** [comment]
Fixed by upgrading the g++ compiler to version 8.

**Comment by bletham** [comment]
Excellent, yes this is then due to the requirement in the latest pystan of C++14, which requires a newer version of gcc.
