### ISSUE TITLE
Speed up prophet by disabling uncertainty estimation (R)

### ISSUE THREAD

**Issue by alexgawrilow** [facebook/prophet#1082]
This issue is related to issue #957 by @scasault \
I tried to speed up the calculation of the prophet model. Since I do not care about uncertainties, disabling their calculation is the easiest way to speed up prophet for me.\
Setting the default parameter  `uncertainty_samples=1000` to `uncertainty_samples=0` reduces the calculation time from 
> 8.04 s ± 310 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

 by a factor of almost 2 to: 

> 4.56 s ± 30.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

on the Peyton Manning data set from the [Quick Start](https://facebook.github.io/prophet/docs/quick_start.html#python-api).\
When setting `uncertainty_samples=0` prophet's `predict` method still calls the method `predict_uncertainty` and `predict_seasonal_components` which calculates some upper and lower uncertainty boundaries. Disabling the calculation of the uncertainties reduces the calculation time by another factor of almost 3 to:
> 1.64 s ± 8.44 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

I included some if statements in my prophet source code that check if the boolean value of `uncertainty_samples` is `False`. If so, the calculation of the uncertainties is disabled which reduces the calculation time by a factor of almost 3, otherwise the uncertainties are calculated normally. Do you think this feature is useful for other users? I could open a pull request.

**Comment by alexgawrilow** [comment]
I opened a pull request #1085 that takes care of this issue.

**Comment by bletham** [comment]
This is done for Python. Now #1085 just needs to be translated over to R to add this feature there.

**Comment by ryankarlos** [comment]
@bletham Can i have a go at adding this to R if still required ? I normally use fbprophet with Python but happy to give this a go with R ?

**Comment by bletham** [comment]
@ryankarlos that'd be great! You'll find that the R code closely parallels the Py code, and so it should require the same changes in the same equivalent places.

**Comment by csetzkorn** [comment]
Can you please tell me how to do this R? Thanks.

**Comment by bletham** [comment]
@csetzkorn `m <- prophet(uncertainty.samples = 0)`
