### ISSUE TITLE
import pystan._api failed: ImportError: DLL load failed

### ISSUE THREAD

**Issue by atptour2017** [facebook/prophet#1088]
I installed pystan followed https://pystan.readthedocs.io/en/latest/windows.html.
In this step: import pystan, an error occured:

(stan_env) C:\Users\陈丹>python
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pystan
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\Anaconda3\envs\stan_env\lib\site-packages\pystan\__init__.py", line 9, in <module>
    from pystan.api import stanc, stan
  File "d:\Anaconda3\envs\stan_env\lib\site-packages\pystan\api.py", line 13, in <module>
    import pystan._api  # stanc wrapper
ImportError: DLL load failed: 找不到指定的模块。(The English translation is: could not find the module _api.)
In fact I followed each instruction step strictly in this url. What's the problem?
I could not install pystan successfully and then prophet successfully.
My environment:
Win10 64bit
conda 4.7.10

**Comment by bletham** [comment]
I don't have a whole lot of experience getting pystan to work in Windows. The only way I've been successful is using conda forge:
```
conda install -c conda-forge pystan
```
and the same for fbprophet.
