### ISSUE TITLE
Getting NameError: name 'go' is not defined

### ISSUE THREAD

**Issue by duttasaibal** [facebook/prophet#1092]
Dear Experts,

I am getting error while running in Anaconda (Window, Python Version 3). Please find my example code and error:

Example code:

from fbprophet.plot import plot_plotly as go
import plotly.offline as py
py.init_notebook_mode()

fig = plot_plotly(m, forecast)  # This returns a plotly Figure
py.iplot(fig)

I am getting following error:

NameError                                 Traceback (most recent call last)
<ipython-input-27-4e62856f2759> in <module>
      3 py.init_notebook_mode()
      4 
----> 5 fig = plot_plotly(m, forecast)  # This returns a plotly Figure
      6 py.iplot(fig)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\fbprophet\plot.py in plot_plotly(m, fcst, uncertainty, plot_cap, trend, changepoints, changepoints_threshold, xlabel, ylabel, figsize)
    560     data = []
    561     # Add actual
--> 562     data.append(go.Scatter(
    563         name='Actual',
    564         x=m.history['ds'],

NameError: name 'go' is not defined

Kindly help me in this case.

**Comment by girmax** [comment]
I have the same issue...

**Comment by Olof-Hojvall** [comment]
If "NameError: name 'go' is not defined" is raised, the Plotly import likely failed (installing plotly is optional, so error is not thrown if that happens). One way I could se this happening is if Plotly is installed while the kernel is running and the plots are already imported. To check if that was the case, first confirm that Plotly is installed and then start a new kernel. 

(To make this clearer, there should maybe be a more descriptive error raised in Plotly functions if the import has previously failed)

**Comment by bletham** [comment]
You can verify if plotly is working by running this:
```
import plotly.graph_objs as go
```

**Comment by cast42** [comment]
I stlll get the error after importing the go object:
```python
from fbprophet.plot import plot_plotly
import plotly.offline as py
import plotly.graph_objs as go
py.init_notebook_mode()

fig = plot_plotly(m, forecast)  # This returns a plotly Figure
py.iplot(fig)
```
The error:
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-165-63b7d06ac367> in <module>
      4 py.init_notebook_mode()
      5 
----> 6 fig = plot_plotly(m, forecast)  # This returns a plotly Figure
      7 py.iplot(fig)

~/.conda/envs/feas-fcst-cogo/lib/python3.7/site-packages/fbprophet/plot.py in plot_plotly(m, fcst, uncertainty, plot_cap, trend, changepoints, changepoints_threshold, xlabel, ylabel, figsize)
    560     data = []
    561     # Add actual
--> 562     data.append(go.Scatter(
    563         name='Actual',
    564         x=m.history['ds'],

NameError: name 'go' is not defined
```
If I include the code of the function plot_plotly from fbprophet\plot.py in my notebook it works correctly. Strange.

**Comment by rritec** [comment]
Even i add code of fbprophet\plot.py function not working for me :(

**Comment by divakarhebbar** [comment]
Even I am facing the same issue. Did anyone find the solution?

**Comment by mprzydatek** [comment]
Also having the same issue.

**Comment by mprzydatek** [comment]
OK, i found the solution.

Instead of creating the go object as suggested above: 
`import plotly.graph_objs as go` (you can simply remove it)

just install ipywidgets instead, and restart the notebook:
`pip install ipywidgets`

...and here's what you should get (an interactive chart): 
<img width="882" alt="Screenshot 2019-09-17 at 23 14 33" src="https://user-images.githubusercontent.com/4595901/65080198-09ddbe80-d9a1-11e9-86b7-15b054293eac.png">

**Comment by bletham** [comment]
@mprzydatek thanks for helping debug this - it looks like `notebook` and `ipywidgets` packages are both required for plotly to work in jupyter notebook (https://github.com/plotly/plotly.py). I wasn't aware of this. We should definitely put this in the documentation.

**Comment by richardzhou666** [comment]
In my case, restarting the kernel solves the problem for me.

**Comment by Ashishkumar-hub** [comment]
Dear Experts,
In my case i have full filled all the requirements every thing plotly etc. is up to date and the code is also running well with no warnings no errors still i am not able to see the plot after the code is running. i am not sure why is this happening. can anyone suggest me something to do. i am using my laptop for completing my project the graphic card is intel default one and nvidia 820M i thought it maybe because of that so i set the default one to nvidia also but it did not work for me.

**Comment by bumblebee2311** [comment]
<img width="964" alt="Screenshot 2020-07-20 at 9 06 32 PM" src="https://user-images.githubusercontent.com/25428559/87956623-e73e9980-cacc-11ea-961d-c8b1464ec9bd.png">
Showing no output and guess what following same steps and procedure mentioned on official documentation on same dataset https://facebook.github.io/prophet/docs/quick_start.html#python-api

**Comment by bletham** [comment]
@bumblebee2311 is this in a jupyter notebook? can you verify that you have the `notebook` and `ipywidgets` packages installed?

**Comment by bumblebee2311** [comment]
> @bumblebee2311 is this in a jupyter notebook? can you verify that you have the `notebook` and `ipywidgets` packages installed?

Yes, it's in Jupiter lab notebook and I did imported ipywidgets pkg as mentioned in conversation also.

**Comment by bletham** [comment]
Can you check if non-prophet plotly plot will show? Maybe something like this:
```Python
import plotly.offline as py
import plotly.graph_objs as go

py.init_notebook_mode()

trace0 = go.Scatter(
  x=[1, 2, 3, 4],
  y=[10, 15, 13, 17]
)
data = go.Data([trace0])

py.iplot(data)
```

**Comment by bletham** [comment]
The requirements of notebook and ipywidgets were added to the quickstart doc https://facebook.github.io/prophet/docs/quick_start.html#python-api

**Comment by BadrinathMJ** [comment]
Still I am facing same problem after installing ipywidget and notebook

**Comment by BadrinathMJ** [comment]
Thank you @mprzydatek. Issue resolved with your solution

**Comment by aryankeluskar** [comment]
For those using jupy notebook, try restarting your kernel after installing plotly.
