### ISSUE TITLE
Seasonality prior scale

### ISSUE THREAD

**Issue by ChaymaeHarfoush** [facebook/prophet#1093]
Larger value allow the model to fit larger fluctuations, smaller values dampen the seasonality but **How is it working with the fourir equation**? 

Is it a scale that we multiply by the equation or not?

**Comment by germayneng** [comment]
Based on the paper, the fourier terms are generated depending on 3 things: 
1) t  --> length of forecast / fourier 
2) p  --> depends on weekly, yearly..etc
3) n --> fourier terms we can set. Default to 10

So with default 10 fourier terms, then using bayesian, beta terms 
Beta = a1,b1,...a10,b10 (2* n terms) will be found. Basically seasonality prior scale is setting the standard deviation for the normal distribution. Higher seasonality prior scale means we are setting a wider normal distribution when sampling for the 2*n terms for our fourier. 

At the end, the fourier terms will be simply the fourier generated * beta
