### ISSUE TITLE
Probability Distribution around the forecast

### ISSUE THREAD

**Issue by anand-mealpal** [facebook/prophet#1094]
Hi,
Prophet is awesome! Thank you so much for this.I'm trying to predict the day-ahead inventory. I understand that the confidence interval is controlled by the parameter `interval_width`. Is there a better way to get a probability distribution around that prediction?

Thank you!

**Comment by vefae** [comment]
Hi @anand-mealpal, did you find a way to get the probability distribution? I am also looking for that.
