### ISSUE TITLE
What is the rate of change of a change point?

### ISSUE THREAD

**Issue by ChaymaeHarfoush** [facebook/prophet#1095]
It is written in the "Trend changepoints" section that :

>  Prophet detects changepoints by first specifying a large number of potential changepoints at which the rate is allowed to change. It then puts a sparse prior on the magnitudes of the rate changes (equivalent to L1 regularization) 

**But what is the rate of change, is that the rate of a line that connects the points "true data" that is contact to the change points lines after removing the seasonality from the data set?**

**Comment by bletham** [comment]
Basically the way to think about it is that you start with a straight line that has slope `k`. At a changepoint, you are allowed to change that slope from `k` to instead be `k + delta`. "rate" in the documentation there means the slope of the trend line.

I think the figure in the documentation with the trend shown with a red line provides a good illustration: https://facebook.github.io/prophet/docs/trend_changepoints.html#automatic-changepoint-detection-in-prophet . At each one of the vertical dashed lines the slope is changed by some amount; that amount is the magnitude of the change.

**Comment by DSoot** [comment]
Don't want to sound stupid but if rate stands fo slope then any absolute delta value that is bigger than `changepoint_prior_scale` declares a change point?
