### ISSUE TITLE
Working with pystan 2.17 instead 2.18+

### ISSUE THREAD

**Issue by marcmetz** [facebook/prophet#1096]
My goal is to run `fbprophet` on `AWS Lambda`. I followed [these](https://medium.com/@amacenov/how-to-get-fbprophet-work-on-aws-lambda-c3a33a081aaf) instructions here. I use [these](https://github.com/lambci/docker-lambda) images here to create the Linux environment needed to deploy on AWS Lambda.

Trying to install `fbprophet` I get the error: `command 'gcc' failed with exit status 1`. As I  figured out now through other issues here the problem was due to the newest version (2.18) to `pystan`. Downgrading to `pystan` 2.17 resolved my issue and I could install `fbprophet` without problem.

My question/problem now is: Is that an okay solution to use an "old" version of `pystan`. It's not foreseeable if that issue is being resolved soon with my setup so I wonder if it might become a problem with my predictions when using an old version.

**Comment by miamartin8** [comment]
I am having the same issue with my gcc compiler and installing fbprophet.  How were you able to downgrade pystan?  Also was there ever an answer on whether or not we will run into any issues using an old version of pystan?

 @bletham @benmwhite

**Comment by marcmetz** [comment]
@miamartin8  [There](https://medium.com/@marc.a.metz/docker-run-rm-it-v-pwd-var-task-lambci-lambda-build-python3-7-bash-c7d53f3b7eb2) you go :)

**Comment by miamartin8** [comment]
Thanks Marc your article was very helpful.  I have already installed Pystan version 2.19.  How do I downgrade to an earlier version?  Do you have the code for that? I cannot uninstall Pystan.
