### ISSUE TITLE
Deploy fbprophet on AWS Lambda [solved]

### ISSUE THREAD

**Issue by marcmetz** [facebook/prophet#1102]
I spend some time trying to figure out how to deploy fbprophet on AWS Lambda. I am not sure if that's the right place here (?), but I wanted to share my learnings and my solution:
https://medium.com/@marc.a.metz/docker-run-rm-it-v-pwd-var-task-lambci-lambda-build-python3-7-bash-c7d53f3b7eb2

So it's not really an issue, but rather the solution to the issues I had. Of course, the creators can feel free to delete/close that issue.

**Comment by bletham** [comment]
Thanks, I'm sure this will be useful!

**Comment by LHerold** [comment]
there is in RStudio?

**Comment by KGRS** [comment]
You are excellent. Thanks a lot. This is the solution to my question. Additionally, only one library need to add to the requirements.txt file. It is holidays library. That's all. This methond is perfectly worked for me. Again thanks a lot Marc Metz.
