### ISSUE TITLE
Plotly V4 documentation adjustments.

### ISSUE THREAD

**Issue by Olof-Hojvall** [facebook/prophet#1103]
Plotly V4 was recently released with some changes that make plotting in notebooks easier. https://medium.com/@plotlygraphs/plotly-py-4-0-is-here-offline-only-express-first-displayable-anywhere-fc444e5659ee

Instead of
```
from fbprophet.plot import plot_plotly
import plotly.offline as py
py.init_notebook_mode()

fig = plot_plotly(m, forecast)  # This returns a plotly Figure
py.iplot(fig)
```
You can with 4.0 now simply run
```
from fbprophet.plot import plot_plotly
plot_plotly(m, forecast)
```
And it will display the figure in the notebook, without any changes to Prophet's Plotly code. It could be good to update the function documentation and quick start to reflect this once enough people should be on latest version. (The longer way also works with 4.0, so no rush)

**Comment by andrewng88** [comment]
@Olof-Hojvall thanks for informing. the offline thingy is sometimes PITA, if you forget to set it , it will be public. it's good that make it as a default now and yeah your codes work with prophet.

Cheers
