### ISSUE TITLE
LunarCalendar in conda forge

### ISSUE THREAD

**Issue by bletham** [facebook/prophet#1104]
#1091 switches from lunardate to LunarCalendar to compute dates of lunar holidays. For the conda forge package of fbprophet, this will require LunarCalendar to be put onto conda forge.

**Comment by bgedik** [comment]
Would there be a new release of fbprophet with this new package? Does this task block it? If so, anything we can do to make this happen sooner?

**Comment by bletham** [comment]
Yes, there will be a new release with the changed dependency, and yes we will want to make sure this is in place before the release. Adding a pure python package like this to conda forge requires a bunch of steps, but is ultimately fairly straightforward. The recipe should be pretty similar to that of lunardate (https://github.com/conda-forge/lunardate-feedstock). If someone was interested in learning how to add packages to conda forge, adding this one would be really helpful.

**Comment by sabgit** [comment]
I'll give it a try to upload LunarCalendar (https://pypi.org/project/LunarCalendar/ current version 0.0.9) to conda-forge. I hope it will speed up the release for the new version of fbprophet. Thanks.

**Comment by bletham** [comment]
I did this in https://github.com/conda-forge/staged-recipes/pull/10885
