### ISSUE TITLE
Figsize not configurable via plot

### ISSUE THREAD

**Issue by dre2004** [facebook/prophet#1107]
Hello,

I've noticed that in the source code on github that figsize is configurable for a plot, but it looks like what I installed via Pypi is missing this feature.

**Github**
`def plot(self, fcst, ax=None, uncertainty=True, plot_cap=True, xlabel='ds', ylabel='y', figsize=(10, 6)):
`

**Pypi fresh install** 
`def plot(self, fcst, ax=None, uncertainty=True, plot_cap=True, xlabel='ds', ylabel='y')`

Is this due to this feature not being released yet or is Pypi a little slow?

**Comment by bletham** [comment]
This feature was added last year in #706 but I wonder if maybe you're looking at the two different plot functions. It was not added to the method `m.plot()`, rather it was added to the function that that method calls (`fbprophet.plot.plot`), here:
https://github.com/facebook/prophet/blob/f4cb9fc4bbc8154582f67fcc722d57f5c95dfa66/python/fbprophet/plot.py#L41

You would use it like this:
```
from fbprophet.plot import plot
plot(m, fcst, figsize=(8, 4))
```

**Comment by dre2004** [comment]
Isn't this the method?
https://github.com/facebook/prophet/blob/f4cb9fc4bbc8154582f67fcc722d57f5c95dfa66/python/fbprophet/forecaster.py#L1508-L1509

**Comment by bletham** [comment]
Ah, sorry; it was added to the method there a few days after the v0.5 release (https://github.com/facebook/prophet/commit/b77f85ffd8e811c401afb1e638d93c0c244c4ab7). So it will show up on pypi with the next version push, but in the meantime you can call the plot function directly.

**Comment by dre2004** [comment]
great! thank you.
