### ISSUE TITLE
Model fit consumes all CPU starting from particular time series length

### ISSUE THREAD

**Issue by kogandaniil** [facebook/prophet#1109]
I observe a strange behavior during __MAP estimation__ (mcmc_samples=0) for time series larger than 640 elements.
It spawns lots of python processes (parallel sampling?) and significantly increases CPU utilization. This can be seen as following:
![image](https://user-images.githubusercontent.com/32837698/62928197-bf28bf80-bdc0-11e9-97df-4a1dd1e1e205.png)
I've also looked through some sources and I suppose that the only thing where it can happen stanfit4model._call_sampler (which is called in StanModel.optimizing). Can it be the wrong arguments passed to method call?
Below is the minimum code example which reproduces my issue:
```python
import numpy as np
from fbprophet import Prophet
import pandas as pd
​
length = 650
iterations = 20
​
for i in range(iterations):
    df = pd.DataFrame(
        {'ds': pd.date_range('2019-01-01', periods=length, freq='1H'),
        'y': np.random.randint(1, 100, length)}
     )
    model = Prophet()
    model.fit(df)
    future_dates = model.make_future_dataframe(periods=24, freq='H')
    forecast = model.predict(future_dates)
```
The execution is looped in sake of observability convenience.
I've tried to run this with random data and real datasets, with default model parameter settings and custom - could not see any difference in sense of my issue. 

Also here is the CPU utilization according to my monitoring:
![image](https://user-images.githubusercontent.com/32837698/62929503-4b3be680-bdc3-11e9-8401-f02e8a6a4798.png)
Here I've tried different settings (also parallel model execution with joblib.Parallel). Everytime I've run model for time series larger than 640 elements I've seen huge CPU utilization spikes with increase of CPU system time.

**Comment by kogandaniil** [comment]
fbprophet version is 0.5 (currently latest). I see this behavior also on 0.4 (don't now whether it presents on older versions)
OS: Ubuntu (18 and 14)

**Comment by kogandaniil** [comment]
Also noticed that this behavior starts from shorter time series when I run several models in parallel

**Comment by bletham** [comment]
The high CPU usage is actually coming during `predict`, not `fit`, and so is not from Stan. You can see it with this code that breaks out what is done for predicting seasonal components:

```
import numpy as np
from fbprophet import Prophet
import pandas as pd

length = 650
iterations = 20

df = pd.DataFrame(
    {'ds': pd.date_range('2019-01-01', periods=length, freq='1H'),
    'y': np.random.randint(1, 100, length)}
    )
model = Prophet()
model.fit(df)
future_dates = model.make_future_dataframe(periods=24, freq='H')

for i in range(iterations):
    df = model.setup_dataframe(future_dates.copy())
    seasonal_features, _, component_cols, _ = (
        model.make_all_seasonality_features(df)
    )
    X = seasonal_features.values
    for component in component_cols.columns:
        beta_c = model.params['beta'] * component_cols[component].values
        comp = np.matmul(X, beta_c.transpose())
        if component in model.component_modes['additive']:
            comp *= model.y_scale
        zz = np.nanmean(comp, axis=1)
        zz_lower = np.nanpercentile(
            comp, 10, axis=1,
        )
```

(original source here:
https://github.com/facebook/prophet/blob/f4cb9fc4bbc8154582f67fcc722d57f5c95dfa66/python/fbprophet/forecaster.py#L1282
)

Interestingly, it looks like most of the time is being spent doing `np.nanpercentile`. It seems that must be multithreaded on the numpy side which is why it uses all processors.

#1082 adds the ability to disable uncertainty samples, which then sidesteps that and would make it a lot faster. It hasn't been pushed to pypi yet but if you install the latest version from github you'll have that feature.

**Comment by kogandaniil** [comment]
Thank you for reply,

Now I see that the issue in predicting seasonal components phase. Yes, np.nanpercentile consumes much time here but the actual source of problem Is `np.matmul`. 
We can check this running the following code:
(This SHOULD reproduce the issue)
```python
import numpy as np
from fbprophet import Prophet
import pandas as pd

length = 650
iterations = 20

df = pd.DataFrame(
    {'ds': pd.date_range('2019-01-01', periods=length, freq='1H'),
    'y': np.random.randint(1, 100, length)}
    )
model = Prophet()
model.fit(df)
future_dates = model.make_future_dataframe(periods=24, freq='H')

for i in range(iterations):
    df = model.setup_dataframe(future_dates.copy())
    seasonal_features, _, component_cols, _ = (
        model.make_all_seasonality_features(df)
    )
    X = seasonal_features.values
    for component in component_cols.columns:
        beta_c = model.params['beta'] * component_cols[component].values
        comp = np.matmul(X, beta_c.transpose())
```
And this:
(This SHOULD NOT reproduce the issue)
```python
import numpy as np
from fbprophet import Prophet
import pandas as pd

length = 650
iterations = 20

df = pd.DataFrame(
    {'ds': pd.date_range('2019-01-01', periods=length, freq='1H'),
    'y': np.random.randint(1, 100, length)}
    )
model = Prophet()
model.fit(df)
future_dates = model.make_future_dataframe(periods=24, freq='H')

for i in range(iterations):
    df = model.setup_dataframe(future_dates.copy())
    seasonal_features, _, component_cols, _ = (
        model.make_all_seasonality_features(df)
    )
    X = seasonal_features.values
    for component in component_cols.columns:
        beta_c = model.params['beta'] * component_cols[component].values
        # comp = np.matmul(X, beta_c.transpose())
        comp = X[:,:1]
        if component in model.component_modes['additive']:
            comp *= model.y_scale
        zz = np.mean(comp, axis=1)
        zz_lower = np.nanpercentile(
            comp, 10, axis=1,
        )
```
Here `comp` can be arbitrary value of the same shape.

So the minimal reproducible example is: 
```python
import numpy as np
z = np.zeros((674,14))
z2 = np.zeros((1,14))
np.matmul(z, z2.transpose())
```
And clearly is a numpy issue

**Comment by kogandaniil** [comment]
To conclude,

https://stackoverflow.com/questions/30791550/limit-number-of-threads-in-numpy
```bash
export MKL_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
export OMP_NUM_THREADS=1
```
Seems to fix an issue

**Comment by kogandaniil** [comment]
Forgot to close, seems that no more discussion needed here

**Comment by DevMui** [comment]
I had the same issue, which this thread helped me to figure it out. Thank you.
