### ISSUE TITLE
How to extract trend and magnitude of change from forecast?

### ISSUE THREAD

**Issue by axerocks** [facebook/prophet#1113]
Is it possible to extract trend and magnitude when modeling sales over period of time. Ideally, i'd want to be able to capture trend and magnitude of forecasted sales mathematically over a certain time-period. is there an easy way to do this ?

**Comment by bletham** [comment]
Are you looking for something like the red line in the third plot here? https://facebook.github.io/prophet/docs/trend_changepoints.html#automatic-changepoint-detection-in-prophet

The trend is found in the `trend` column of the forecast dataframe (output from `predict`). The actual parameters of the piecewise linear function (slope `k`, intercept `m`, changepoint magnitudes `delta`),  are in `m.params`, but they are in a transformed space (`y` is scaled by maximum value and time is mapped to [0, 1]) which will make it difficult to use directly.

**Comment by axerocks** [comment]
Yes , that red line is what I'd like to obtain as output. I think i's still fine even if it is transformed using min_max approach. The goal is to use this trend and actual forecasted value at end of certain period. 

So let's say in my use-case; it's going to be multiple-series. We're forecasting sales by market in future time-frame. Each series will have a trend and actual forecast at the end of certain period. Would it fair to compare trend from one series to another series especially after it's been transformed?

**Comment by axerocks** [comment]
I was wondering if you can share what a simple output (predict) dataframe looks like.

**Comment by bletham** [comment]
It sounds like you want the final trend values as a function of time, in which case the `trend` column from the forecast dataframe will do it.

Probably the easiest way to check what the output looks like would be to run the quickstart example notebook: https://github.com/facebook/prophet/blob/master/notebooks/quick_start.ipynb

There if you do `print(forecast.head())`, you will get
```
          ds     trend  yhat_lower  yhat_upper  trend_lower  trend_upper  \
0 2007-12-10  8.042899    8.226266    9.476831     8.042899     8.042899   
1 2007-12-11  8.041350    7.949328    9.189117     8.041350     8.041350   
2 2007-12-12  8.039801    7.777997    9.006285     8.039801     8.039801   
3 2007-12-13  8.038252    7.720000    8.920916     8.038252     8.038252   
4 2007-12-14  8.036703    7.711115    8.989372     8.036703     8.036703   

   additive_terms  additive_terms_lower  additive_terms_upper    weekly  \
0        0.802898              0.802898              0.802898  0.352294   
1        0.552973              0.552973              0.552973  0.119638   
2        0.350326              0.350326              0.350326 -0.066677   
3        0.329804              0.329804              0.329804 -0.072245   
4        0.319306              0.319306              0.319306 -0.069576   

   weekly_lower  weekly_upper    yearly  yearly_lower  yearly_upper  \
0      0.352294      0.352294  0.450603      0.450603      0.450603   
1      0.119638      0.119638  0.433336      0.433336      0.433336   
2     -0.066677     -0.066677  0.417003      0.417003      0.417003   
3     -0.072245     -0.072245  0.402050      0.402050      0.402050   
4     -0.069576     -0.069576  0.388882      0.388882      0.388882   

   multiplicative_terms  multiplicative_terms_lower  \
0                   0.0                         0.0   
1                   0.0                         0.0   
2                   0.0                         0.0   
3                   0.0                         0.0   
4                   0.0                         0.0   

   multiplicative_terms_upper      yhat  
0                         0.0  8.845797  
1                         0.0  8.594324  
2                         0.0  8.390127  
3                         0.0  8.368056  
4                         0.0  8.356009  
```

**Comment by axerocks** [comment]
Yes, that's exactly what I want to extract. This is awesome. I assume yhat is the actual forecasted value. Correct?

In addition, is it possible to compare trend column from one series to trend column from another series?

**Comment by bletham** [comment]
Correct, yhat is the forecasted value (and is what shows up as the blue line in the plots).

I don't see anything wrong with comparing trend values from one time series to another, so long as it would be reasonable to compare their y values. The units of "trend" will be the same as the units of "y".
