### ISSUE TITLE
warning: non-zero exit status while installing prophet and rstan in Azure notebooks

### ISSUE THREAD

**Issue by harishvenkatesan96** [facebook/prophet#1115]
Hi, I am trying to install the Prophet package in R Azure Notebooks (in Azure ML Service). I tried various methods for installing the package, but it keeps throwing a warning - “non-zero exit status”. Please find below the exact configuration and steps I followed to install prophet.

I followed the RStan page (https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started) and configured the C++ toolchain as per the instruction.

![image](https://user-images.githubusercontent.com/35761352/63208879-a4738500-c0f7-11e9-8ecc-1c87339b0f77.png)

Then, I tried to install the Prophet package along with its dependencies.

![image](https://user-images.githubusercontent.com/35761352/63208881-ab01fc80-c0f7-11e9-8de9-3d25b106d7e1.png)

But, RStan and Prophet packages were not properly installed and returned a warning- non-zero exit status.

![image](https://user-images.githubusercontent.com/35761352/63208884-b1907400-c0f7-11e9-93a0-45b8aaa354d0.png)

Can you please help in installing the Prophet package without issues in R Azure Notebooks of Azure ML Service.

Below is the version of my OS and R which might be helpful in debugging the issue.

![image](https://user-images.githubusercontent.com/35761352/63208888-b9501880-c0f7-11e9-9382-3f136d044db6.png)

**Comment by bletham** [comment]
It looks like the installation failure here is during the installation of rstan. I don't have any experience with Azure notebooks and don't have any suggestions for what it takes to get rstan working on them, but I'd recommend asking over at the rstan github issue tracker and I'd expect that they'll be able to help.
