### ISSUE TITLE
Feature Request: Add support for continuous regressors

### ISSUE THREAD

**Issue by rohan-gt** [facebook/prophet#1119]
Right now Prophet only supports external regressors which are binary. If you need to use a feature like Price which a continuous variable to forecast a target variable like Demand, it is not possible using Prophet

**Comment by eromoe** [comment]
Each product have a guide price and sale price , you can use discount rate(sale_price/guide_price) , then split it into ,maybe 4 bins(aka 4 reggressor), to achive the goals .

Though, have built-in support for continuos regressors would be much better .

**Comment by vhpietil** [comment]
Isn't additional regressors what you are looking for (https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#additional-regressors). They can be continuous, they do not have to be binary.

**Comment by eromoe** [comment]
Yeah, I checked the code

> ```
> for name, props in self.extra_regressors.items():
>     standardize = props['standardize']
>     n_vals = len(df[name].unique())
>     if n_vals < 2:
>         standardize = False
>     if standardize == 'auto':
>         if set(df[name].unique()) == set([1, 0]):
>             # Don't standardize binary variables.
>             standardize = False
>         else:
>             standardize = True
>     if standardize:
>         mu = df[name].mean()
>         std = df[name].std()
>         self.extra_regressors[name]['mu'] = mu
>         self.extra_regressors[name]['std'] = std
> 
> for name, props in self.extra_regressors.items():
>     df[name] = ((df[name] - props['mu']) / props['std'])
> ```

But I found the extra reggressors would almostly stay in a constant value , see the bottom plot
![image](https://user-images.githubusercontent.com/3938751/63339129-d21a3180-c376-11e9-8e05-607882fbd2de.png)

**Comment by vhpietil** [comment]
@eromoe Could you explain a bit more what you mean by extra regressor staying at constant value. 

If you give Prophet one additional regressor, it will estimate one beta which is used to scale you external regressor and that beta is constant.

**Comment by rohan-gt** [comment]
@eromoe yes, you are right. I only looked at the code example. I missed the part where it's mentioned that continuous values can be used
