### ISSUE TITLE
Can we set a converge value in some range of a seasonality ?

### ISSUE THREAD

**Issue by eromoe** [facebook/prophet#1120]
For example, 
I have a product sale plot : 
![image](https://user-images.githubusercontent.com/3938751/63337218-2d4a2500-c373-11e9-9afa-78244a294a56.png)

This product have not been sold between  2019-05-18 -  2019-07-10 . Training data is from    2019-04-28 17:00:00 to  2019-07-19 23:00:00 .

2019-07-10, this is a changepoint which make prophet think trend become positive  , even if there are many zeros in daily seasonaliy( 21:00 to 08:00 ) , prophet still think future ( 21:00 to 08:00 ) would be a large positive number : 

![image](https://user-images.githubusercontent.com/3938751/63337253-3c30d780-c373-11e9-87fc-1d186d270290.png)

This is wrong behave for me .

What I want to achive is  adding a converge value 0 to daily seasonaliy( 21:00 to 08:00 ) . 
The idea for me is calculate rolling mean 30 days each value of ( 21:00 to 08:00 ) , set floor = 0  and cap =rolling mean  to prevent the prediction value exceed .

PS : Does adding a constant trend is another way to solve this ? Though I found this issue https://github.com/facebook/prophet/issues/614 is still opened

**Comment by kaleming** [comment]
I am also trying to deal with this trend impact.

You can try to use just the trend mean in order to keep a constant value.

    df2['yhat'] = (
            df2['trend'].mean() * (1 + df2['multiplicative_terms'])
            + df2['additive_terms']
    )

**Comment by eromoe** [comment]
Actually, my data had a strong  daily seasonality . Simply groupby hour and count would found this pattern ,
![image](https://user-images.githubusercontent.com/3938751/63410104-1cf28280-c425-11e9-869f-d38230c64ea9.png)

I'd like prophet learn this .

**Comment by bletham** [comment]
If there is a range of time where there is no data because the product was not being sold, then the better thing for Prophet would be to just leave that data out (i.e., delete that range of dates from the history dataframe) rather than have it in with 0s. But as in my comment on #1118 , the model will not always perform well on time series with small count data.
