### ISSUE TITLE
Question: is there a way to use linear growth model and still have the cap and floor features from logistic growth model?

### ISSUE THREAD

**Issue by kevinliujunyang** [facebook/prophet#1122]
Hi,

I find in the documentation that prophet can only allow logistic growth to have cap and floor feature such that there are hard bottom and ceiling for prediction. if in reality, linear growth model is a better choice for some specific practice, how can linear growth model also enjoy the features from logistic growth? can linear model prediction also have cap and floor features for prediction?

**Comment by bletham** [comment]
There isn't currently a way to do this. I suppose it would be possible by setting trend to be min(linear_trend(t), cap(t)), and the same for the floor. But I think #340 would be the preferred way of supporting this. The logistic trend will be essentially linear except at the edges where it saturates, so the difference between these trends would basically be if the trend saturates at the cap with a sharp edge, or if it asymptotes at the cap. Do you have an example time series of where this would be useful? I'm imagining that an "out of stock" situation might be one where it would not asymptote, but can't really think of others.

**Comment by bjburatti** [comment]
Is there any update about this? I check #340 and seems to be closed, thanks!

**Comment by bletham** [comment]
Yeah, we've decided to not move predictions into Stan which will make it more difficult to plug in custom Stan models. I think one could do this by tracking down all of the trend parts of the code and editing them appropriately, but I don't think we're going to have built-in support for this anytime soon.
