### ISSUE TITLE
Changing order of regressors changes the accuracy in the code. 

### ISSUE THREAD

**Issue by Shikhar2205** [facebook/prophet#1132]
Hi ,
When i am adding regressor as a feature . When I am changing the order the results are changed. Could you please verify at your end what is wrong.

**Comment by germayneng** [comment]
hi, do you have any reproducible example?

**Comment by Shikhar2205** [comment]
Actually what i am doing is
 
add_regressor('variable1')
add_regressor('variable2')
gives some error . Lets consider wmape  about 0.23

Now i changed my code just interchanged the lines.
add_regressor('variable2')
add_regressor('variable1')
gives some error . Lets consider wmape  about 0.22. HEre is a major change in the wmape metric. What i think is this should not happen right ?

**Comment by bletham** [comment]
hm, the model has a big linear component `X @ beta` for extra regressors, where each regressor is a column of X and beta are the parameter fit by the model. Conceptually the order should not matter at all, and I'm having a hard time thinking of what in the code could cause this behavior. Do you have code and data you could post that produces the issue so I can dig into it more?

**Comment by danish21h** [comment]
Hey @bletham  I have found similar issue with one of my analysis. Was this ever reported again?
