### ISSUE TITLE
Plotly Chart autoscale mode not available

### ISSUE THREAD

**Issue by RangaRaju** [facebook/prophet#1133]
for example, fbprophet_plot plots taking fixed figsize, but i want to make it autoscale instead of fixed fugure. 

i come up with a solution to implement auto scale option

for example  
def plot_plotly(m, fcst, uncertainty=True, plot_cap=True, trend=False, changepoints=False, actual=True,changepoints_threshold=0.01, xlabel='ds', ylabel='y', figsize=(900, 600)):

add these three parameters  to function showlegend=False, autosize=False, title=""

change layout variable to 

    layout = dict(
        autosize=autosize,
        showlegend=showlegend,
        yaxis=dict(
            title=ylabel
        ),
        xaxis=dict(
            title=xlabel,
            type='date',
            rangeselector=dict(
                buttons=list([
                    dict(count=7,
                         label='1w',
                         step='day',
                         stepmode='backward'),
                    dict(count=1,
                         label='1m',
                         step='month',
                         stepmode='backward'),
                    dict(count=6,
                         label='6m',
                         step='month',
                         stepmode='backward'),
                    dict(count=1,
                         label='1y',
                         step='year',
                         stepmode='backward'),
                    dict(step='all')
                ])
            ),
            rangeslider=dict(
                visible=True
            ),
        ),
    )

    if(autosize == False):
        layout.update(dict(width=figsize[0], height=figsize[1]))

    if(title != None and len(title) > 0):
        layout.update(dict(title=title))

it's works for me to auto scale the fig

**Comment by bletham** [comment]
This seems reasonable to me, go ahead and make a PR if you'd like.

**Comment by jpawitro** [comment]
the autoscale still doesn't work..
add this lines to your code, it works for me
```
fig = plot_plotly(m,forecast)
fig['layout'].height = None
fig['layout'].width = None
fig.update_layout(
         autosize = True,
)
```
