### ISSUE TITLE
Calculate aggregated confidence interval

### ISSUE THREAD

**Issue by kaleming** [facebook/prophet#1135]
Assuming I made a prediction of how many units will be sold:

![Aggregate interval](https://user-images.githubusercontent.com/51836477/64371736-b611c380-cff7-11e9-979b-3b7d2c7b4c34.jpg)

If I want to tell what is the confidence interval for a specific time interval (eg. next 10 days), what is the best approach to make this aggregation ?

I mean, "for the next 10 days, I have 90% probability the amount of units sold will be below x units" ?

**Comment by APramov** [comment]
I think this might help:
https://github.com/facebook/prophet/issues/1149

also see 
https://github.com/facebook/prophet/issues/426

**Comment by bletham** [comment]
+1 for @APramov's comment. You'll want to get predictive samples as described in https://github.com/facebook/prophet/issues/426#issuecomment-362421428 and then with those samples you can do whatever aggregations / probability computations you'd like. So here you would, for each sample path, sum over 10 days and then take the 90th percentile of that sum across samples.

**Comment by kaleming** [comment]
Thank you guys.
