### ISSUE TITLE
numexpr log given on linux machine, but not macos

### ISSUE THREAD

**Issue by mattc-eostar** [facebook/prophet#1138]
`INFO:numexpr.utils:Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.`

This does not cause any major issues, but I am curious as to why this would come up. I developed a system on a Mac and then replicated the environment and repo on a Linux box to run overnight.

This log keeps showing up, but have never seen it before. I have used Prophet v0.4 on this box before with no problem. Is this a v0.5 thing?

I am using a multiprocessing pool to speed the up work over thousands of time series.

Thanks!

**Comment by bletham** [comment]
fbprophet doesn't use numexpr directly, so this must be coming from however you're using multiprocessing. I'm not familiar with numexpr, but from the message it sounds like it uses an environment variable NUMEXPR_MAX_THREADS which, if not set, defaults to some fraction of available cores (here 8 out of 12). It seems pretty innocuous to me.

**Comment by miamartin8** [comment]
@mattc-eostar I am having the same issue on linux with multiprocessing.  I have 56 cores, but NumExpr is enforcing 8.  I tried to set the cores with the code below, but it is still using 8 cores.  Did you figure out how to use all of your cores with multiprocessing?
`numexpr.set_num_threads(numexpr.detect_number_of_cores())`

**Comment by mattc-eostar** [comment]
> @mattc-eostar I am having the same issue on linux with multiprocessing. I have 56 cores, but NumExpr is enforcing 8. I tried to set the cores with the code below, but it is still using 8 cores. Did you figure out how to use all of your cores with multiprocessing?
> `numexpr.set_num_threads(numexpr.detect_number_of_cores())`

I ended up setting the environment variable within the Dockerfile for my image:
`NUMEXPR_MAX_THREADS=64`

Things seems to be working properly so no major concern there.

**Comment by PilarLF** [comment]
> NUMEXPR_MAX_THREADS=64

How did you solve it?
