### ISSUE TITLE
Peak hours seasonality in sub-daily data

### ISSUE THREAD

**Issue by dagap** [facebook/prophet#1143]
I am currently collecting some sensor data at  5 minutes interval and have data for the last 5 days. So, at the moment it only makes sense to do daily seasonality modelling, I think.

So, the data I have covers 2 weekend days and I do notice that there is a drop in the measurements over the weekend. Since, I am not fitting weekly seasonality at the moment, would it make sense to add the weekends as a holidays in this case? I am new to TS modelling, so wondering what might be a good way to approach this.

Secondly, I see peaks during the peak hour times. Would this be covered by enabling the daily seasonality or does one also add sub-daily seasonal components for typical peak hour kind of trends.

Lastly, if I do want to play around with some sub-daily seasonalities like 4 hour interval, do I need to define the period in days i.e. (period=4.0/24.0)?

**Comment by bletham** [comment]
Day-of-week effects: With sub-daily data, there are two ways to handle day-of-week effects. The first is to enable weekly seasonality. What this will do is learn a day-of-week pattern that will be added to the daily seasonality. So if there is a decrease on the weekends, it will learn how much to subtract on the weekend days.

That does, however, assume that the shape of the daily seasonality is the same on weekends and weekdays, and that the day-of-week effect is just an offset. Often times there can actually be a difference in the shape of the seasonality on weekends vs. weekdays, in which case you would probably want to fit separate daily seasonalities for weekends vs. weekdays. The documentation describes how to do this here: https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#seasonalities-that-depend-on-other-factors

Basically, you would create a pair of binary indiciators to your dataframe, "is_weekday" and "is_weekend". "is_weekday" is 1 if that row is on a weekday and 0 for a weekend, and vice versa for "is_weekend". Then,
```
m = Prophet(daily_seasonality=False)
m.add_seasonality(name='weekday_daily', period=1, fourier_order=4, condition_name='is_weekday')
m.add_seasonality(name='weekend_daily', period=1, fourier_order=4, condition_name='is_weekend')
```

Note that this would be in the place of the normal daily seasonality, so you'd want to disable that when instantiating the model.

Peaks: If you have a peak at some point during the day that is consistent across days (i.e., occurs at the same time each day), then it should be captured by the daily seasonality. If it is a very sharp peak and the model seems to be smoothing it out too much, then see https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#fourier-order-for-seasonalities .

Seasonality period: That's correct, period is in units of days and can be fractional, so 4/24. would fit a 4-hour cycle.
