### ISSUE TITLE
Preprocessing extra regressors

### ISSUE THREAD

**Issue by amw5g** [facebook/prophet#1144]
Similar to prior questions (#234, #1029) but a little different- I'm getting fair results from prophet prior to including extra regressors.  I'm at the point where I want to consider regressors, but they are also highly seasonal.  

My plan is to identify & remove season & trend (i.e. `stldecompose`) for each regressor as a preprocessing step before including those as candidate features into the prophet model  I don't have any empirical justification for that, it just *felt* right.  It allows me, in absence of having forecasts for each of my regressors, to simply set their forecasted value to 0, or roll some recent values forward.

Is this preprocessing suggested or necessary?  I'd appreciate perspectives from more experienced forecasters.

**Comment by bletham** [comment]
I'd be really interested to hear empirically how things look with and without doing seasonality/trend removal from the regressor.

The reason for wanting to do this (make it so setting it to 0 is a reasonable future value for regressors that are not known in the future) makes a ton of sense.

I'd expect that removing seasonality would not have any effect; Prophet should be able to pick up the seasonality without getting it from the regressor.

But de-trending the regressor seems like it could hurt things. I suppose it depends on what we think the effect on `z` on `y` is: does the trend in `z` drives trends in `y`? If so it seems that we should leave it in. De-trending `z` would basically say that it is the fluctuations in `z` around its trend that drives `y`. I can imagine there would be situations where this is the case, but I'd expect more often that the trend in `z` is probably of interest for `y`.

It seems like de-trending and then using 0 as a future forecast value would be equivalent to not de-trending, and then using the mean of some small window at the end as the future forecast value. I'd expect this to do better with Prophet, but I'd be really interested to hear if anyone has experience trying this out.

**Comment by amw5g** [comment]
I'm providing some empirical results based on my data at hand.  I can't get into the specifics, but you can think of it as fairly analogous to daily hotel check-in volumes or movie theater visitation.  The training data is just shy of 2.5 years (1/1/2016 through 5/31/2019), and the out-of-sample data is nearly 4 months (6/1/2019 through 9/21/2019).  My goal is to predict the dependent variable 28 days in advance.

There is obvious annual as well as weekly seasonality, and a known slight upward trend in the time series.  The regressors include: weather (obvious annual seasonality, but no weekly nor material trend); and two other covariates that are similar to advance sales volumes.   You can consider these regressors as something like, "for date X/X/XXXX, what were the advance sales volumes 28-days in advance?".  Like the dependent variable, they have annual & weekly seasonality.  One has a stronger initial trend that flattens out, while the other has a slight upward trend.

I am testing a model with holidays only (`H`), a model with unprocessed regressors (`H+R`), a model with holidays + deseasonalized regressors (`H+Rd`), and a model with holidays + deseasonalized  & de-trended regressors (`H+Rdd`).  My evaluation criteria are MAPE and the correlation between predicted & known values, assessed on the holdout sample.

```
H, MAPE: 57.7% (this is highly variable with each fit, has me a little concerned....)
H, corr: 0.84

H+R, MAPE: 32.0%
H+R, corr: 0.83

H+Rd, MAPE: 71.8%
H+Rd, corr: 0.83

H+Rdd, MAPE: 47.6%
H+Rdd, corr: 0.83
```
Extrapolating from this, I'd say that my data are best modeled without any preprocessing of the extra regressors.  Which is a little disappointing, because it means I'll need to have real values for future time periods.  I can't rely on a rolling average (i.e., it won't produce meaningful seasonal or trend values), nor a dummy value that represents no deviance from a seasonal, trend-adjusted default.
