### ISSUE TITLE
Convert Uncertainty Intervals for daily forecasts to weekly Uncertainty Intervals (R)

### ISSUE THREAD

**Issue by Gfroz** [facebook/prophet#1149]
Hello,

i have a very similar question as in this post: https://github.com/facebook/prophet/issues/426 

But since i am using R and not Python i am not able to follow the steps in this post because i have quit bad programming skills.

Can anyone help me with some codes / functions for R such that i can convert the yhat_upper and yhat_lower values for daily forecasts to aggregated weekly yhat_lower and yhat_upper values?

For yhat i can simply sum it up but for yhat_lower and yhat_upper it is not that simple.

**Comment by Gfroz** [comment]
Hello again,

i would really need help for my question because it is an important thing for my masters thesis. Therefore i can offer 20 euro amazon credit/voucher as expense allowance for the person that is able to help me and find the required code for R :) 

(Sorry for english mistakes)

Thanks again and best regards!

**Comment by APramov** [comment]
@Gfroz , lol no need to give away money - it will certainly not be in the spirit of the prophet library's open source nature, at least in my opinion.

Let's look at this, I'll try to help. Tell you what - if it fixes your problem, then you can donate 20 euro to a charity of your choice :)

I looked at the python code and @bletham  answer and it should work roughly if you do this (this is for yhat_upper/yhat_lower).

Let's say your data has working days only and you want to predict the next 40 days (this makes 8 weeks)

1) Run your prophet model  (myfit) on your daily data
2) Create a dataframe for predictions, say forecast_df that will have 40 rows.
3) run predictive_samples(myfit, forecast_df)

You will get (by default) a list with yhat and trend as elements. Out of this, you take the yhat and you will obtain a matrix that is of dimensions: (40, 1000) (The 1000 is by default - it gives the number of posterior samples, you can increase that number).

So this means that for every day, you have 1000 samples from the posterior. Aggregate (**sum**) over each sample for every week in your future period. So you do this for days 1 to 5 (this is the first week), then for days 6 - 10 (week 2) and so on.

So you end up with a (new) matrix that is of dimensions (8, 1000). Each row corresponds to a week. Now, you take the percentile (say 20th and 80th) for each row and this will give you the respective interval for the weekly forecast.

**Comment by Gfroz** [comment]
Thank you very very much for you answer! :) I will try it at the latest on monday, since i am not sure if i can use R this weekend. I will answer again as soon as i tried out the procedure that you told me :)

**Comment by APramov** [comment]
Do try and let us know :)

**Comment by Gfroz** [comment]
I just tried it out and the procedure works nice for me, the weekly yhat_lower and yhat_upper values make sense :) 

I still have one more question. Since i want to forecast the next 51 weeks for my data, is there a simple way to create a dataframe for this 51 weeks containing the 3 columns yhat, yhat_lower and yhat_upper for each week? Such that i do not have to write 51 times:
"quantile(colSums(posterior_samples[1:7, ]), probs = c(0.1, 0.9))" for each week?

**Comment by APramov** [comment]
@Gfroz , maybe something like this (51 weeks with 5 days = 255 days):
```
x <- seq(from =1, to = 5*51, by = 5)
y <- seq(from = 5, to = 5*51, by =5)

loop_indices <- cbind(x,y)
```

And then you can do a loop over the "loop_indices" matrix, such that you would have something like this

`store_values <- matrix(0, nrow = 51, ncol = 1000)`

```
for( i in 1:nrow(loop_indices){
   store_values [i, ] = quantile(colSums(posterior_samples[loop_indices[i, 1]:loop_indices[i, 2], ]), probs = c(0.1, 0.9))"
}
```

So if it works, please close the issue and keep up that promise of donating the 20 euro to a charity of your choice if you were serious about it :P

@bletham, maybe an idea would be to integrate such "upscaling" between frequencies (say moving from daily to weekly) as a part of the code, so that people can do it automatically if they have daily data but want something different. What do you think about it? It seems to be requested often enough both in R and Python.

I will try to work on it.

**Comment by Gfroz** [comment]
@APramov , Unfortunately your code doesn't really work for me.

When i run it, the store_values matrix still contains only zeros. 

And i also have a question about it, why should the store_values matrix have 1000 columns? Because finally i want to have a matrix/dataframe/whatever which contains 3 columns (and 51 rows of course) for yhat, yhat_lower and yhat_upper.

Would be very happy if you can help me again :) Unfortunately, my programming skills are not that good.

Thank you again! :)

**Comment by APramov** [comment]
Good point, I forgot that you are already doing the quantiles in the line of code that I have given. So it should be 2 columns and not 1000 (with the quantile for hte yhat lower weekly, quantile for hte yhat upper weekly)

**Comment by Gfroz** [comment]
@APramov , Thank you for editing. When i simply copy and past you code (the for-loop) than unfortunately it is still not working. ("Error: unexpected '{' in "for( i in 1:nrow(loop_indices){"")

I think a second ")" bracket was missing in the beginning of the for-loop, so i added it. 
--> for( i in 1:nrow(loop_indices)){.............

Then the error disappeared but when i run the code the store_value matrix is still filled with only zeros and R jumps to a new line that begins with a "+" sign instead of ">" sign as usual. Unfortunately i do not know what this means and what the mistake is here. 

Would be very happy about some final help :)

Thank you!

**Comment by APramov** [comment]
I edited the code. When you have a series of "+" it is, as you say, due to an unclosed bracket somewhere. Press escape and run the whole code again.

**Comment by APramov** [comment]
I am putting the whole example again. Note that you *should not* use my model fit (use a model that fits your data well), it is just an example to illustrate the aggregation of the weekly forecasts.

```
library("xts")
library("tidyverse")
library("prophet")
raw_data <- as.xts(Nile)
clean_ts <- as_tibble(data.frame("ds" = index(raw_data),
                                 "y" = raw_data))


#fit prophet -  I just used a simple model as an example, without
# trying to have a good fit or run #diagnostics
#you put your model here of course.

set.seed(1234)
myfit <- prophet(clean_ts,
                 growth = "linear",
                 yearly.seasonality = FALSE,
                 weekly.seasonality = FALSE,
                 daily.seasonality = FALSE,
                 changepoint.prior.scale = 1,
                 n.changepoints = 25)


future <- make_future_dataframe(myfit, periods = 255, 
                                freq = "year", 
                                include_history = FALSE)
fcst <- predict(myfit, future)

posterior_samples_yearly <- predictive_samples(myfit,future)$yhat #posterior samples


#this gives you the lower and upper interval for the first four "5-year" periods, at 80% 
# (0.1 and 0.9) for lower and upper respectively

#the first 5 year period
quantile(colSums(posterior_samples_yearly[1:5, ]), probs = c(0.1, 0.9)) 

#the second 5 year period
quantile(colSums(posterior_samples_yearly[6:10, ]), probs = c(0.1, 0.9)) 

#the 3rd
quantile(colSums(posterior_samples_yearly[11:15, ]), probs = c(0.1, 0.9)) 

#the 4th
quantile(colSums(posterior_samples_yearly[16:20, ]), probs = c(0.1, 0.9)) 


# put it in a loop
x <- seq(from = 1, to = 255, by = 5)
y <- seq(from = 5, to = 255, by = 5)
loop_indices <- cbind(x,y)

# create an empty container to store your values (say that you sample 1000 times from the posterior)
store_values <- matrix(0, nrow = 51, ncol = 2)


# And then you can do a loop over the "loop_indices" matrix, such that you would have something like this
for( i in 1:nrow(loop_indices)){
  store_values [i, ] = quantile(colSums(posterior_samples_yearly[loop_indices[i, 1]:loop_indices[i, 2], ]), probs = c(0.1, 0.9))
}

```

**Comment by Gfroz** [comment]
@Gfroz , Thank you very much again, now it is working for me! :) 

Your idea for the charity donation instead of my offer is very nice and i will now think about an organization during the next days where i can do this online and will finally let you know about my decision. :) I will close this thread now.

Best regards,
Gfroz

**Comment by APramov** [comment]
That's great to hear @Gfroz , keep us updated ;) Cheers

**Comment by shai14** [comment]
> @Gfroz , lol no need to give away money - it will certainly not be in the spirit of the prophet library's open source nature, at least in my opinion.
> 
> Let's look at this, I'll try to help. Tell you what - if it fixes your problem, then you can donate 20 euro to a charity of your choice :)
> 
> I looked at the python code and @bletham answer and it should work roughly if you do this (this is for yhat_upper/yhat_lower).
> 
> Let's say your data has working days only and you want to predict the next 40 days (this makes 8 weeks)
> 
> 1. Run your prophet model  (myfit) on your daily data
> 2. Create a dataframe for predictions, say forecast_df that will have 40 rows.
> 3. run predictive_samples(myfit, forecast_df)
> 
> You will get (by default) a list with yhat and trend as elements. Out of this, you take the yhat and you will obtain a matrix that is of dimensions: (40, 1000) (The 1000 is by default - it gives the number of posterior samples, you can increase that number).
> 
> So this means that for every day, you have 1000 samples from the posterior. Aggregate (**sum**) over each sample for every week in your future period. So you do this for days 1 to 5 (this is the first week), then for days 6 - 10 (week 2) and so on.
> 
> So you end up with a (new) matrix that is of dimensions (8, 1000). Each row corresponds to a week. Now, you take the percentile (say 20th and 80th) for each row and this will give you the respective interval for the weekly forecast.
> 
> I just played a little bit with **yearly** toy data, that I aggregated over 5 year periods, just to keep the same structure. So imagine that I was interested in producing forecasts for a 5 year period but my data is yearly. I just picked a default R dataset that is yearly, you pick yours of course.
> 
> ```
> library("xts")
> library("tidyverse")
> raw_data <- as.xts(Nile)
> clean_ts <- as_tibble(data.frame("ds" = index(mydata),
>             "y" = mydata))
> 
> 
> #fit prophet -  I just used a simple model as an example, without
> # trying to have a good fit or run #diagnostics
> #you put your model here of course.
> 
> set.seed(1234)
> myfit <- prophet(clean_ts,
>                  growth = "linear",
>                  yearly.seasonality = FALSE,
>                  weekly.seasonality = FALSE,
>                  daily.seasonality = FALSE,
>                  changepoint.prior.scale = 1,
>                  n.changepoints = 25)
> 
> 
> future <- make_future_dataframe(myfit, periods = 40, 
> freq = "year", 
> include_history = FALSE)
> fcst <- predict(myfit, future)
> 
> posterior_samples_yearly <- predictive_samples(myfit,future)$yhat #posterior samples
> 
> 
> #this gives you the lower and upper interval for the first four "5-year" periods, at 80% 
> # (0.1 and 0.9) for lower and upper respectively
> 
> #the first 5 year period
> quantile(colSums(posterior_samples_yearly[1:5, ]), probs = c(0.1, 0.9)) 
> 
> #the second 5 year period
> quantile(colSums(posterior_samples_yearly[6:10, ]), probs = c(0.1, 0.9)) 
> 
> #the 3rd
> quantile(colSums(posterior_samples_yearly[11:15, ]), probs = c(0.1, 0.9)) 
> 
> #the 4th
> quantile(colSums(posterior_samples_yearly[16:20, ]), probs = c(0.1, 0.9)) 
> ```

**Comment by shai14** [comment]
Hi,
Thanks for sharing this. I have some issues. 
1. I fit my model on log(y), so I think I need to convert the forecast first to exp(fc$yhat), before adding those. Right? But how to convert for yhat_lower and yhat_upper?
2. If I follow ur code without converting them the colsums adds up all log values, so that will be wrong with my little understanding. So I changed all values of 'posterior_samples_yearly' to exp(posterior_samples_yearly) before taking quantile. But the issue is then quantile on lower end is coming more than yhat, is it possible?
