### ISSUE TITLE
Unable to install prophet on my new VM

### ISSUE THREAD

**Issue by venkateshkunda** [facebook/prophet#1154]
Installing collected packages: fbprophet
  Running setup.py install for fbprophet ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/rh/rh-python36/root/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-abz4utdw/fbprophet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-abz4utdw/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-8c52bv1_/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-abz4utdw/fbprophet/
    Complete output (9 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/fbprophet
    creating build/lib/fbprophet/stan_model
    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_861b75c6337e237650a61ae58c4385ef NOW.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/rh/rh-python36/root/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-abz4utdw/fbprophet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-abz4utdw/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-8c52bv1_/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by bletham** [comment]
It looks like pystan is not working. You can check this with:
```
import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this will take a minute
y = model.sampling(n_jobs=1).extract()['y']
y.mean()  # should be close to 0
```

The issue would be that gcc is not configured correctly. Check out the Linux section here for a list of extra packages you should be sure to have: https://facebook.github.io/prophet/docs/installation.html . And also make sure your VM has at least 4GB of memory.

**Comment by venkateshkunda** [comment]
I am getting when I try running the above code,

-------------------------------------------------------------------------------------------------
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_5944b02c79788fa0db5b3a93728ca2bf NOW.
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/unixccompiler.py", line 128, in _compile
    extra_postargs)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/pystan/model.py", line 349, in __init__
    build_extension.run()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/unixccompiler.py", line 130, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

**Comment by venkateshkunda** [comment]
I intsalled all the compilers mentioned in Linux section, I am still getting the error

-------------------------------------------------------------------------------------------------
 a good idea. Try `pip3 install --user` instead.
Collecting fbprophet
  Using cached https://files.pythonhosted.org/packages/33/fb/ad98d46773929079657706e6b2b6e366ba6c282bc2397d8f9b0ea8e5614c/fbprophet-0.5.tar.gz
Requirement already satisfied: Cython>=0.22 in /usr/local/lib64/python3.6/site-packages (from fbprophet)
Requirement already satisfied: pystan>=2.14 in /usr/local/lib64/python3.6/site-packages (from fbprophet)
Requirement already satisfied: numpy>=1.10.0 in /usr/local/lib64/python3.6/site-packages (from fbprophet)
Requirement already satisfied: pandas>=0.23.4 in /usr/local/lib64/python3.6/site-packages (from fbprophet)
Requirement already satisfied: matplotlib>=2.0.0 in /usr/local/lib64/python3.6/site-packages (from fbprophet)
Requirement already satisfied: lunardate>=0.1.5 in /usr/local/lib/python3.6/site-packages (from fbprophet)
Requirement already satisfied: convertdate>=2.1.2 in /usr/local/lib/python3.6/site-packages (from fbprophet)
Requirement already satisfied: holidays>=0.9.5 in /usr/local/lib/python3.6/site-packages (from fbprophet)
Requirement already satisfied: setuptools-git>=1.2 in /usr/local/lib/python3.6/site-packages (from fbprophet)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.6/site-packages (from pandas>=0.23.4->fbprophet)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/site-packages (from pandas>=0.23.4->fbprophet)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/site-packages (from matplotlib>=2.0.0->fbprophet)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/site-packages (from matplotlib>=2.0.0->fbprophet)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib64/python3.6/site-packages (from matplotlib>=2.0.0->fbprophet)
Requirement already satisfied: ephem<3.8,>=3.7.5.3 in /usr/local/lib64/python3.6/site-packages (from convertdate>=2.1.2->fbprophet)
Requirement already satisfied: six in /usr/local/lib/python3.6/site-packages (from holidays>=0.9.5->fbprophet)
Requirement already satisfied: setuptools in /usr/lib/python3.6/site-packages (from kiwisolver>=1.0.1->matplotlib>=2.0.0->fbprophet)
Installing collected packages: fbprophet
  Running setup.py install for fbprophet ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-gaqlijt7/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-gphg2a0s-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/fbprophet
    creating build/lib/fbprophet/stan_model
    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_861b75c6337e237650a61ae58c4385ef NOW.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-gaqlijt7/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-gphg2a0s-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-gaqlijt7/fbprophet/

**Comment by bletham** [comment]
OK, so the issue is definitely on the PyStan side of things and specifically with gcc.

Can you check what version of gcc you have installed? Make sure it is at least 5.4.0 in order to use PyStan 2.19 (see #930).
