### ISSUE TITLE
why my prediction is just a linear line here

### ISSUE THREAD

**Issue by giabbb** [facebook/prophet#1155]
![Rplot](https://user-images.githubusercontent.com/55897667/65800966-e3104c80-e145-11e9-8d6f-a5cee689ca0d.png)

Hi, I am pretty new to prophet, can anyone think of anyway to improve my prediction? 

I am using 2017 -2018 monthly data to predict first seven months of 2019
I used this dyplot.prophet()  to plot the graph and the prediction seems to be a straight line vs the actual dots varies up and down. 

I am open to any thoughts and suggestions. Thanks!

**Comment by vhpietil** [comment]
That might very well be the best prediction based on your data. Observations seem to be quite random without clear seasonality

**Comment by bletham** [comment]
+1 for @vhpietil's assessment. By default Prophet will not enable yearly seasonality until there are at least 2 years of data, and this is 1 month short of that. You could do
```
m = Prophet(yearly_seasonality=True)
```
to see how it looks with yearly seasonality, but I don't see any clear patterns here and I think straight line plus random noise might be about the best forecast that can be made from these data.

(If you do enable yearly seasonality, be sure that your prediction dataframe also has monthly frequency, as described here: https://facebook.github.io/prophet/docs/non-daily_data.html#monthly-data ).

**Comment by giabbb** [comment]
> +1 for @vhpietil's assessment. By default Prophet will not enable yearly seasonality until there are at least 2 years of data, and this is 1 month short of that. You could do
> 
> ```
> m = Prophet(yearly_seasonality=True)
> ```
> 
> to see how it looks with yearly seasonality, but I don't see any clear patterns here and I think straight line plus random noise might be about the best forecast that can be made from these data.
> 
> (If you do enable yearly seasonality, be sure that your prediction dataframe also has monthly frequency, as described here: https://facebook.github.io/prophet/docs/non-daily_data.html#monthly-data ).

Thank you for your reply! I added one more month of data and I got edgy lines instead of one straight line.  I thought 201701-201812 was already two years of data when I ran it in the first place..

**Comment by APramov** [comment]
@giabbb , I just want to give you my take on this  (I realize that this is a prophet github issue page, but still ;) ) - it seems to me that it might be worth a try to model your data with an (s)arima type of process or an exponential smoothing model. I don't see a clear function of time here (which is what prophet is good at). If you are using R, you might take a look at the the "ets" package that features automatic model selection much like prophet and see if you wouldn't get something that makes you feel more comfortable with the model fit.

**Comment by paolobighignoli** [comment]
> +1 for @vhpietil's assessment. By default Prophet will not enable yearly seasonality until there are at least 2 years of data, and this is 1 month short of that. You could do
> 
> ```
> m = Prophet(yearly_seasonality=True)
> ```
> 
> to see how it looks with yearly seasonality, but I don't see any clear patterns here and I think straight line plus random noise might be about the best forecast that can be made from these data.
> 
> (If you do enable yearly seasonality, be sure that your prediction dataframe also has monthly frequency, as described here: https://facebook.github.io/prophet/docs/non-daily_data.html#monthly-data ).

You truly saved my life with `yearly_seasonality`. Thanks a lot
