### ISSUE TITLE
Prophet : Is holiday impact estimated independent of dayoftheweek effect

### ISSUE THREAD

**Issue by RJASROTIA** [facebook/prophet#1157]

**Comment by RJASROTIA** [comment]
hello.. how does prophet interpret moving holidays along with weekly seasonality . E.G. I am forecasting hotel bookings at daily level , let's say Easter fell on wednesday last year and this year it fell on a monday. We would expect more bookings to happen last year on wednesday (since people are not traveling as easter is falling in the middle of the week), however next year we would expect less bookings on easter (since it falls on a monday which falls close to a weekend and hence people would be traveling and not booking). Would prophet take into account this effect ? Or would we need an additional regressor like 'proximity of holiday to a weekend' ?

**Comment by trevor-pope** [comment]
When defining your holidays df, you can give a list of dates that the holiday occurs on, so you can specify which dates Easter falls on each year. IIRC the default US holiday dataframe has moving holidays accounted for.

**Comment by RJASROTIA** [comment]
I understand that we can provide a dataframe with a list of dates on which the holiday falls. .. but the question is more about whether the effect of the holiday is considered independent of the dayoftheweek effect.  Easter falling on a wednesday should have a different impact from Easter falling on a weekend. Is this accounted for in prophet?

**Comment by sammourad** [comment]
@RJASROTIA holidays' effect is independent from weekly seasonality. If combined they don't reflect the changes you see in the data, you can exclude Easter from the holidays dataframe and create two separate regressors for it: easter_weekday and easter_weekend. If you have long enough time-series that might do it for you.

**Comment by patelmohitj91** [comment]
Related doubt about this topic, I separated each of my holidays in the holiday dataframe such that christmas is treated differently than thanksgiving. However, I see that all throughout the timeseries prediction, effect on each christmas date is same and each thanksgiving is the same, both however being different than each other. How is that valid? How can the effect of 2015 christmas be same in 2019?
![Screen Shot 2019-10-02 at 9 45 25 AM](https://user-images.githubusercontent.com/15958059/66063986-6391cd00-e4f9-11e9-83d3-ba25dc7c4372.png)

**Comment by trevor-pope** [comment]
Assuming that your data has a yearly seasonality, then it is perfectly valid to have repeated effects on Christmas. What are you expecting to happen? Also, it would be useful to see what data you are putting into the model.

**Comment by patelmohitj91** [comment]
I cant share the exact data but can share certain observations. For example, when I see the holiday effects documentation on fbProphet's official page, I see this 
![Screen Shot 2019-10-02 at 10 25 28 AM](https://user-images.githubusercontent.com/15958059/66066755-fa14bd00-e4fe-11e9-9a21-9a09ce77e415.png)

My data does have yearly seasonality as evidenced by this plot: 

![Screen Shot 2019-10-02 at 10 26 41 AM](https://user-images.githubusercontent.com/15958059/66066830-27fa0180-e4ff-11e9-94ab-d051dcbda2cc.png)

Sorry if the chart is unclear, I can post a clearer aggregated view if this doesn't help.

My expectation is to see some variance in the holiday effect component of the prediction for each year..

**Comment by trevor-pope** [comment]
If I am correct, the reason the Prophet example has changing holidays is because they are modeling two different holidays (Superbowls and Playoff games) that align at different times. The actual superbowl effect is the same, and you will notice that the superbowl spike is the same for most years, except when there is a playoff game.

**Comment by patelmohitj91** [comment]
Ah got it! makes sense now. Thanks a lot for this explanation!

**Comment by RJASROTIA** [comment]
> @RJASROTIA holidays' effect is independent from weekly seasonality. If combined they don't reflect the changes you see in the data, you can exclude Easter from the holidays dataframe and create two separate regressors for it: easter_weekday and easter_weekend. If you have long enough time-series that might do it for you.

@sammourad That seems like a good idea. However , I am struggling to understand why would I need to do this if the holiday effect is indeed 'independent' of weekly  seasonality.  If the pure easter effect is calculated independent of weekly seasonality (i.e. assuming no effect of the day of the week) then why should it matter to prophet whether easter is on a sunday or on a weekday in order to estimate the impact correctly.

**Comment by bletham** [comment]
@RJASROTIA the holiday effect fit by the model assumes that it is a constant effect that is added every time that holiday occurs (or, with multiplicative seasonality, a constant % change). So the holiday effect for Easter will be exactly the same every year. With weekly seasonality the model will also fit day-of-week effects, but those are also assumed to be constant: Every Saturday has the same day-of-week effect. So Easter-on-Saturday will have as its effect Easter_effect+Saturday_effect. I think what you looking for is an interaction effect, where Easter-AND-Saturday should be different than just summing the two effects. The model will not on its own try to fit interaction effects.

The way to model this would be to remove the Easter holiday, and instead put in two holidays: "Easter_on_weekday" and "Easter_on_weekend", where you have split the Easter dates across these two holidays according to whether it lands on a weekday or weekend. This will allow the model to learn a separate effect for Easter on a weekday and Easter on a weekend.

**Comment by RJASROTIA** [comment]
@bletham : Thanks for the input. Makes a lot of sense.
