### ISSUE TITLE
[r] dyplot.prophet should pass ... to dygraphs::dySeries(...)

### ISSUE THREAD

**Issue by adrfantini** [facebook/prophet#1158]
As per title. Currently, `dyplot.prophet`  does not pass `...` onward to the plotting function, so you cannot set the title, axis labels, etc.
Ideally instead one could be able to do `dyplot.prophet(m, fc, main = "my own title")`.

**Comment by bletham** [comment]
Seems like a useful improvement, go ahead and make a PR and I'll merge!

**Comment by bletham** [comment]
This is pushed to CRAN in v0.6
