### ISSUE TITLE
Prophet models are big. How to reduce/compress it ? 

### ISSUE THREAD

**Issue by atthom** [facebook/prophet#1159]
I was unable to find any references on this issue on the documentation, so I post my issue here.

My Prophet models' sizes are around 40-50Mo of disk space when pickle-compressed. This seems unusually large for a single time series model. Is there any way or workaround to reduce the memory usage of the prophet models?

Due to its size, I think that the model generated is much more complex than it should be. Is it some kind of overfitting?

**Comment by APramov** [comment]
Weird' I haven't seen such big models but then again I also have not ran very big models. Maybe if you save only what you are interested in from the model fit (e.g. I think that the fit includes the original data, which you maybe do not need - maybe the original data is the one making the model be so big in terms of Megabytes?)

Regarding overfitting: it is impossible to say without looking at the parameters that you fit the model with and at least some in-sample/out-of-sample fit metrics. Maybe you could compute those and share them here?

**Comment by atthom** [comment]
I'll try to make a minimal reproducible example

**Comment by atthom** [comment]
![image](https://user-images.githubusercontent.com/14034413/65972001-71980d00-e469-11e9-86c3-2a30458d88ea.png)

This is something I made up very quickly with a dataset of 5*10^5 rows, the model is around 10Mo  with all default parameters. And pickle is probably compressing the data.

**Comment by sammourad** [comment]
That's a lof of data I'm guessing most of the size is coming from it. The training data is saved in the history attribute of the model `model.history`.

**Comment by atthom** [comment]
Is `model.history` needed for the model to work correctly? 

You're right model.history is a dataframe of shape `(158631, 5)` so probably the training data and the evolution of some metrics during the fitting process.
   
could I clear the dataframe `model.history` after fitting? And my memory problem would be solved :)

**Comment by APramov** [comment]
> 
> 
> Is `model.history` needed for the model to work correctly?
> 
> You're right! `model.history` is a dataframe of shape `(158631, 5)` so it probably saves the training data and the evolution of some metrics during the fitting process.
> 
> could I clear the dataframe `model.history` after fitting? And my memory problem would be solved :)

Yeah, this is what I suggested in my first post - from the model fit, store only the stuff that you need and not the whole fit that includes the history :) , e.g. just the forecasts for the next 5 days, or just the estimated parameters etc. - whatever you would need for your application.

**Comment by sammo** [comment]
+1 to @APramov 's suggestion. So if you need to generate a forecast once and then store the model, you can drop the `model.history` data frame.  If you need to generate forecasts based on the fitted model, the data frame will be required. You can check it out in [the code here](https://github.com/facebook/prophet/blob/e1a2b9c2977a0817eb245c704d2e478211585886/R/R/prophet.R#L1334).

**Comment by ahartikainen** [comment]
Have you considered using compression with `gzip`

    import gzip
    with gzip.open("path/to/file", "wb") as f:
        pickle.dump(model, f)

**Comment by bletham** [comment]
`model.history` has the history in its original form (except with NaNs filtered), along with columns that have the scaled versions of these used in model fitting. It is stored for two uses: `m.plot()` includes the training data as black dots, `cross_validate(m)` does cross validation on the training data. Both of these use `m.history`. If you do not need either of these functionalities, then you could wipe `m.history` and you can still make predictions.

The model also stores `model.history_dates` which has all of the dates in the history, including those that had `y` as NaN and so were filtered out of `model.history`. This is used in `make_future_dataframe` if `include_history=True`, so you can wipe this if you don't need that functionality.

(One thing to note about wiping `m.history`: `predict` verifies that the model has been fit prior to predicting by checking for `m.history` to be not-None (https://github.com/facebook/prophet/blob/e1a2b9c2977a0817eb245c704d2e478211585886/python/fbprophet/forecaster.py#L1167), so to wipe `m.history` you should set it to something that is not None)

**Comment by atthom** [comment]
Thank you very much for all your answers.
I only need to store the statistical model. I already store the training data somewhere else.
My models are big because my training set is big. So clearing `model.history` and `model.history_dates` really solve the problem. 
I close the issue.

**Comment by jake221** [comment]
In my case, I cannot reduce the model size even if I replace the model.history and model.history_dates. I check the source code for predict function and the Prophet Model object, finding that the model.stan_backend is useless in prediction stage and I try to set it as None before saving the model. This really works! I also use gzip as @ahartikainen suggested. Finally I reduce the original model from 30MB to 2KB! Really amazing!

model.history = 0
model.history_dates = 0
model.stan_backend = None

**Comment by bletham** [comment]
@jake221 this is related to #1384, which is that a change in v0.6 greatly increased the pickle size.

I just added json serialization in #1415 which will be the recommended way of storing models in the future (and much smaller than pickles). But until that is pushed out, clearing `stan_backend` is the way to go.

**Comment by yeya24** [comment]
I tried clearing out model history and history dates but seems like the saved model will be just empty. Is it expected or it is not required to clean up history anymore?
`model.history = 0
model.history_dates = 0`
