### ISSUE TITLE
R cross_validation using as.difftime for "3 hours"

### ISSUE THREAD

**Issue by TheXu** [facebook/prophet#1160]
I wanted to see if there was more documentation on R's cross_validation function using the as.difftime function within the "units" parameter.

Specifically, I am forecasting every **3 hours on 3 hour time step data**, and I want to compute **cross validations for every 3 hours**, instead of by every hour. I am having trouble setting this up correctly, and I have experimented with using the as.difftime() function from base R

I have tried:
* `prophet_cvts <- cross_validation(m, initial = 2920, period = 6, horizon = 12, units = as.difftime("03:00:00"))`

` Error in as.difftime(horizon, units = units) : invalid units specified `
*  `prophet_cvts <- cross_validation(m, initial = 2920, period = 6, horizon = 12, units = as.difftime(3, format="%H", units="hours"))`

` Error in as.difftime(horizon, units = units) : invalid units specified `
*  `prophet_cvts <- cross_validation(m, initial = 2920, period = 6, horizon = 12, units = as.difftime(3*12, format="%H", units="hours"))`

`Error in as.difftime(horizon, units = units) : invalid units specified `

I have looked at https://github.com/facebook/prophet/issues/516, but that doesn't deal with the cross_validation function. https://github.com/facebook/prophet/issues/586 gives examples for monthly data.

Any help would be appreciated on this! Thank you!

Edit 1:
I have some fake data here to highlight my issue. I'm still not sure how the as.difftime function works for creating units of "3 hours"

```
library(xts)
library(zoo)
library(dplyr)
library(prophet)
#' Make data
tmp=zoo(rnorm(1000), as.POSIXct("2010-02-1")+(1:10000)*60)
#' Resample to 3 hours
tmp <- data.frame(tmp[endpoints(tmp, "hours", 3)]) %>%
  tibble::rownames_to_column("ds")
colnames(tmp) <- c("ds", "y")

#' Run Prophet model
m <- prophet(tmp)
#' Cross Validate
cv <- cross_validation(m, initial = 10, period = 3, horizon = 6, units = as.difftime(3, units = "hours"))
cv <- cross_validation(m, initial = 10, period = 3, horizon = 6, units = as.difftime(3, format="%H", units = "hours"))
cv <- cross_validation(m, initial = 10, period = 3, horizon = 6, units = as.difftime(3 * 12, format="%H", units = "hours"))
```

Edit 2: 
If the solution is simple in python, that would be useful too

Edit 3:
**Solved with example code below**. If your time series data is sampled every N hours, you can compute rolling cross validations for time series sampled every N hours, as long as period and horizon are multiples of N. If someone wants to expound in further detail. Feel free too

```
library(lubridate)
library(xts)
library(zoo)
library(dplyr)
library(prophet)

#' # Make data
tmp=zoo(rnorm(1000), as.POSIXct("2010-02-1")+(1:10020)*60)
#' # Resample to 3 hours time steps
tmp <- data.frame(tmp[endpoints(tmp, "hours", 3)]) %>%
  tibble::rownames_to_column("ds")
colnames(tmp) <- c("ds", "y")

#' # Transformations
#' Take out last row because it would change initial.dt in cross_validation
tmp <- tmp[-nrow(tmp),]
tmp[["ds"]] <- tmp[["ds"]] %>% ymd_hms() + minutes(1)

#' Run Prophet model
m <- prophet(tmp)

#' Observe that cutoffs initial takes in 30 hours which is 10 time steps for 3 hour time series data
#' If time series "ds" column ended offsetthe 3 hour time step, initial cutoff would be offset by the same amount
cv <- cross_validation(m, initial = 30, period = 3, horizon = 9, units = "hours")
cv[["horizon"]] <- cv[["ds"]] - cv[["cutoff"]]
View(cv)

#' Initial starts at "2010-02-01 13:00:00"
cv_2 <- cross_validation(m, initial = 10, period = 3, horizon = 9, units = "hours")
cv_2[["horizon"]] <- cv_2[["ds"]] - cv_2[["cutoff"]]
View(cv_2)
```

**Comment by bletham** [comment]
Internally the values passed as `horizon`, `period`, and `initial` are converted to difftime using `as.difftime`, like here:
https://github.com/facebook/prophet/blob/a2a0df904e2666bb126de99e5d68892edec91029/R/R/diagnostics.R#L77

So "units"  needs to be a valid units for `as.difftime`, not a difftime itself. Suppose I want to do a cross validation every 3 hours, starting from an initial 48 hours of data, each time forecasting out 12 hours. Then,
```
cv <- cross_validation(model = m, horizon = 12, initial = 48, period = 3, units = "hours")
```
would do it. (As noted in your edit).
