### ISSUE TITLE
Tuning regularization parameter changepoint prior scale

### ISSUE THREAD

**Issue by patelmohitj91** [facebook/prophet#1161]
I am new to FBProphet, is there any way to tune this parameter for best match mae or rmse? If we are trying to automate a forecast, how do we set this such that the result accuracy is improved by comparing between different changepoint prior scale values?

**Comment by sammourad** [comment]
You can try [this](https://medium.com/@jeanphilippemallette/prophet-auto-selection-with-cross-validation-7ba2c0a3beef)

**Comment by patelmohitj91** [comment]
Hi sammourad, I guess the question was a little unclear. I am already doing what you mentioned on the medium blog post. Let me re-phrase the question: How do I perform parameter tuning on FB prophet using parameters like changepoint prior scale and seasonality prior scale? Is there documentation on how to improve quality of forecast or reduce MAE?

**Comment by bletham** [comment]
On a practical note, I'd recommend tuning these parameter on a log scale, like described briefly here: https://github.com/facebook/prophet/issues/1009#issuecomment-502208570 . This can be done using random search, where you randomly generate values within the search range, and then use cross validation to evaluate how good a particular set of parameters is: https://facebook.github.io/prophet/docs/diagnostics.html

That would be the fully automated approach. I do also find that visual inspection is helpful for determining which aspects of the time series are being under/over-fit.

**Comment by TheXu** [comment]
Bayesian Hyperparameter Optimization for R Prophet Model Parameters is detailed here:
http://rpubs.com/tdneumann/351073

**Comment by nba2020** [comment]
How about create a loop and iterate with various values of  changepoint.prior.scale.
Then at the end of the lop pick the changepoint.prior.scale that has the minimum error and apply it to the final model
