### ISSUE TITLE
I am running Prophet on pyspark. But there are some errors regarding the datatype of the column 'ds' even though i changed it to Date datatype. Also there is a non-zero value being passed in forecaster.py (inbuilt for Prophet) because of which it is not able to convert it to boolean. Need advice on the same

### ISSUE THREAD

**Issue by baba-udit** [facebook/prophet#1164]
<img width="835" alt="Capture" src="https://user-images.githubusercontent.com/56115266/66123116-ed778e00-e5fe-11e9-819b-5ba9018e2a75.PNG">

**Comment by bletham** [comment]
The input to `Prophet` needs to be a pandas dataframe, not a spark DataFrame. I'd recommend looking here for some tips on getting Prophet to work on spark: #517
