### ISSUE TITLE
name 'm' is not defined

### ISSUE THREAD

**Issue by rezapci** [facebook/prophet#1167]
i still cant figure it out on my ubuntu!
every thing are up to date

`import pandas as pd`
`from fbprophet.plot import plot_plotly`
`import plotly.offline as py`
`py.init_notebook_mode()`

`fig = plot_plotly(m, forecast)
py.iplot(fig)`
`---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)`
`<ipython-input-10-692962f13113> in <module>`
     ` 4 py.init_notebook_mode()`
      `5 `
`----> 6 fig = plot_plotly(m, forecast)`
      `7 py.iplot(fig)`

`NameError: name 'm' is not defined`

**Comment by ruben-rosa** [comment]
I think you have not created and fit the model. Try this;
m = Prophet()
m.fit(dataset)

Good luck

**Comment by gremlin97** [comment]
m is the default name of the model in prophet. First create the model, fit it and then try to plot the interactive graph.
