### ISSUE TITLE
Understanding of "cross_validation" / "Predictive_samples" in combination with "cross_validation"

### ISSUE THREAD

**Issue by maxwell873** [facebook/prophet#1169]
Hi everyone,

please first read the EDIT of this post at the bottom, it would be really nice if i could first get an answer about the EDIT. :)
---------
i have a short question about the "predictive_samples" command. 

Can i somehow use the "predictive_samples" command, after I forecasted some future data with "cross_validation" ??

Usually the "predictive_samples" command is used this way:
predictive_samples(m, future)$yhat

It creates me by default 1000 sample values for each forecast value. 
But my problem here is, that i only forecast with cross_validation (because i want to forecast for many periods in the future, and i want to update the historical data periodically.)
And for cross_validation i do not have the "future" data frame (because it is not needed for cross_validation).

I use cross_validation this way:
cvforecast <- cross_validation(m, initial = 1822, period = 14, horizon = 14, units = 'days')
(So, i only have to fit the model m beforehand but i do not have to create the "future" data frame)

I would be happy if someone could help me with this problem! Thank you! :)

-------
EDIT: After i read some more information about cross_validation i am currently not quit sure if I understand the principle of it correctly. Some more information about what i am doing right now:

I have historical sales data for 5 years from 2012-2016 and based on this data i want to forecast the sales for the year 2017. (For which i of course already know the real sales data!) My aim is to evaluate the accuracy of prophets forecasts for the year 2017. So, i imported all my known data from 2012-2017 to R and i used cross_validation to simulate the forecasts for 2017. With my initial value i tell prophet that it has to use the daily data for the first 5 year and starts forecasting. 

The horizon / period value, in my case = 14, means that prophet should "update" the input data for the forecast every 14 days. So, for example for the forecast of weeks 1 and 2 of year 2017, prophet uses the input data from years 2012-2016 but than for forecast of weeks 3 and 4 of year 2017 it should in addition also take the sales data of weeks 1 and 2 of year 2017 for the model ("update" the input data). And so on, and then finally for the last 2 weeks of 2017 prophet should already know most of the sales values of 2017 and take all these values as input. (Doing so, forecasts should be more accurate, because historical data will periodically be updated)

--> This is how I understood cross_validation by now. I am not sure, if anyone could follow my thoughts about cross_validation, but if so, it would be great if you could tell me what i understood wrong about it :)

Best regards

**Comment by bletham** [comment]
Your description of cross validation is correct:
- Predictions for weeks 1 and 2 of 2017 will use data from 2012-2016
- Predictions for weeks 3 and 4 of 2017 will use data from 2012-2016 plus 2017 weeks 1-2
- Predictions for weeks 5 and 6 of 2017 will use data from 2012-2016 plus 2017 weeks 1-4
- etc.

So if I understand the original question, it is then how to get predictive samples in a similar way. There isn't a built-in functionality for this, but you can do it just by just filtering the history dataframe to include only data before a particular date (e.g. 2017), fit the model, make a future dataframe with the next two weeks, and call predictive_samples. For instance, for the CV steps above it would be
- filter history to dates < 2017, set future to weeks 1 and 2 of 2017
- filter history to dates < 2017 week 3, set future to weeks 3 and 4 of 2017
- etc.

Does that answer the question?

**Comment by maxwell873** [comment]
@bletham 

Hi Ben,

I am relieved that my comprehension of cross validation is correct :)

I can theoretically follow your steps for the predictive samples and it makes sense for me. What do you think, how many lines of code would be needed for this procedure? Since my programming skills are quit bad i am not sure if i could handle this. My only idea would be to use a for-loop somehow to not have that many lines of code.

What i did so far for predictive samples of cross_validation forecasts is the following: (I am definitely not sure if this makes sense but it runs and gives reasonable results)

cvforecast <- cross_validation(m, initial = 1822, period = 14, horizon = 14, units = 'days')
samples_daily <- predictive_samples(m,cvforecast)$yhat

This runs and it gives me reasonable sample values for yhat, but i am not sure if it can be done this way.

I would be very happy about some additional feedback for this points :)

Thank you in advance!

**Comment by bletham** [comment]
If you do
```
samples_daily <- predictive_samples(m,cvforecast)$yhat
```
then here `m` is a model fit to all of the training data, so it the samples you get will be in-sample predictions, not the out-of-sample predictions that cross validation is giving you. Essentially it's measuring training error and not test error.

I would do this with a for loop and it won't take much code. If you look in `cvforecast`, it has all of the cutoff dates used, and so you just need to (for each of them) trim the data down to that cutoff, and then make a two week forecast. It would look something like:

```
df$ds <- as.POSIXct(df$ds)
for (cutoff in unique(cvforecast$cutoff)) {
  df_c <- df[df$ds <= cutoff,]
  m_c <- prophet(df_c)  # include here whatever other parameters were used for m
  future <- make_future_dataframe(m_c, 14, include_history=FALSE)
  samples <- predictive_samples(m_c, future)$yhat
}
```
and then you would just have to store `samples` for each cutoff along with the corresponding dates in `future`.

**Comment by maxwell873** [comment]
Hi @blethem , thank you for the answer. Today, i finally managed to try out your lines of code to get the correct samples.

I simply copied and paste your lines above into my R skript and changed some small things (comments below):

`df$ds <- as.POSIXct(df$ds)
for (cutoff in unique(cvforecast$cutoff)) {
  df_c <- df[df$ds <= cutoff,]
  m_c <- prophet(df_c)  # I included my paramters here in the brackets instead of "df_c"
  m_c = fit.prophet(m_c, df_c) #I added this line because without it i get an error, is it correct?
  future <- make_future_dataframe(m_c, 364, include_history=FALSE) #Instead of 14 i used 364 here because in total i want to forecast a full year
  samples <- predictive_samples(m_c, future)$yhat
}`

The code works without an error but unfortunately results doesn't make sense for me, for some forecasted days, the sample values are for example much to high in comparison to the corresponding yhat value. 

The values that i got before when i used

`samples_daily <- predictive_samples(m,cvforecast)$yhat`

were much more realistic (although this procedure is not correct as you mentioned :) )

(I made some graphics and calculated quantiles to see if the sample values make sense or not.)

Do you maybe know what the mistake could be here?

Thank you again! :)

**Comment by bletham** [comment]
If you're looking at the y-hat from in-sample predictions (that is, a model fit with all the data) then it will certainly be much better because the true value will be part of the model training data. If the model has very high predictive uncertainty then it might have really good in-sample fits but very high variance when making predictions where the model doesn't have data (as in the loop above).

Try looking at the forecast just with m_c:
```
m_c <- prophet(df_c)  # include here whatever other parameters were used for m
future <- make_future_dataframe(m_c, 14, include_history=TRUE)  # TRUE for plotting
fcst_c <- predict(m_c, future)
plot(m_c, fcst_c)
```
Does it have very high uncertainty in the future?

**Comment by maxwell873** [comment]
Hi Ben,

yes my forecasts have rather high uncertainty in the future. 

Thank you so far, I will write again when it comes to my next question :)
