### ISSUE TITLE
Source code for Forecasting at Scale?

### ISSUE THREAD

**Issue by aisongzhang** [facebook/prophet#1179]
Where can I find the source code of Forecasting at Scale? I want to reproduce the experimental results.

**Comment by bletham** [comment]
All of the figures in the paper use a Facebook time series of actual product usage which unfortunately cannot be shared externally. So it will not be possible for you to reproduce the actual content of the figures.

If you want to do the same analysis on a similar time series, then Figs. 4-6 are just from fitting a model to a subset of the data (Fig. 4) or all data (Figs. 5-6) and predicting. The fitting and predicting is exactly as is done here:
https://facebook.github.io/prophet/docs/quick_start.html

Is there a specific analysis that is unclear?
