### ISSUE TITLE
Documentation: Missing development contribution guidelines

### ISSUE THREAD

**Issue by jdemonasterio** [facebook/prophet#1184]
This project does seem to have specific examples of how to contribute on the docs
https://github.com/facebook/prophet/blob/master/docs/CONTRIBUTING.md

but not on how to contribute at the code level. Some examples for this are the following:

- https://dev.pandas.io/docs/development/contributing.html#creating-a-development-environment
- https://scikit-learn.org/stable/developers/contributing.html#contributing-code
- https://scikit-learn.org/stable/developers/contributing.html#workflow-to-improve-test-coverage

As a basic start, maybe add a `requirements-dev.txt` file to indicate which testing packages ([`unittest`](https://github.com/facebook/prophet/blob/master/python/fbprophet/tests/test_prophet.py#L12) and any more? are needed).

What do you guys think?

**Comment by bletham** [comment]
Agreed! How to run the unit tests, and that this should be done when creating a PR, would be a great start.
