### ISSUE TITLE
Minimum version for plotly

### ISSUE THREAD

**Issue by bletham** [facebook/prophet#1186]
The plotly plot is reported to not work in Plotly 3.1.0 (#1181), so we should determine the latest version of plotly in which it does work and add that as a minimum version in requirements.txt.

**Comment by sammo** [comment]
It also works with the offline module.
```
from fbprophet.plot import plot_plotly
import plotly.offline as py

py.iplot(plot_plotly(pf.forecaster, forecast))
```

**Comment by bletham** [comment]
Yeah this all seems to be working afterall.
