### ISSUE TITLE
Installing Prophet on RHEL 7.5

### ISSUE THREAD

**Issue by datawookie** [facebook/prophet#1196]
Hi,

I've been hitting my head against this for a couple of days now: time to ask for help.

I'm trying to install Prophet on a RHEL 7.5 machine and I just can't get it to work. I've got it to install on a bunch of Ubuntu machines and it went flawlessly.

This is the error message that I'm getting:

```
> install.packages("prophet")
Installing package into ‘/home/andrew/R/x86_64-redhat-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/prophet_0.5.tar.gz'
Content type 'application/x-gzip' length 210535 bytes (205 KB)
==================================================
downloaded 205 KB

* installing *source* package ‘prophet’ ...
** package ‘prophet’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
installing via 'install.libs.R' to /home/andrew/R/x86_64-redhat-linux-gnu-library/3.6/00LOCK-prophet/00new/prophet
Compiling model (this will take a minute...)
Writing model to: /home/andrew/R/x86_64-redhat-linux-gnu-library/3.6/00LOCK-prophet/00new/prophet/libs
Compiling using binary: /usr/lib64/R/bin
DIAGNOSTIC(S) FROM PARSER:
Info: left-hand side variable (name=cp_idx) occurs on right-hand side of assignment, causing inefficient deep copy to avoid aliasing.
Info: left-hand side variable (name=m_pr) occurs on right-hand side of assignment, causing inefficient deep copy to avoid aliasing.

Error: Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.
* removing ‘/home/andrew/R/x86_64-redhat-linux-gnu-library/3.6/prophet’
Warning in install.packages :
  installation of package ‘prophet’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpVVJ2Oc/downloaded_packages’
Warning message:
In if (!is.character(x)) x <- as.character(x) :
  closing unused RODBC handle 1
```

My initial hypothesis was that my compiler was too old (the default on RHEL 7.5 is GCC 4.8.5). I've got that upgraded to 8.3.1.

```
g++ --version
g++ (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I also read that downgrading rstan and StanHeaders might work. So those are currently 2.18.1 and 2.18.0.

I've tried a lot of options, but feel like I'm just stumbling around in the dark looking for a solution. Any suggestions appreciated.

Thanks,
Andrew.

**Comment by bletham** [comment]
In the error message it mentions `check_build_tools` - did you by chance try that? In the rstan documentation that is their recommendation (https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started) and on that page they have some tips on what to do to get the build chain working depending on the output.

See also in https://github.com/stan-dev/rstan/wiki/Installing-RStan-on-Linux where it describes an extra step for CentOS which might be relevant here as a sibling distro.

Let me know if anything that they suggest there works!

**Comment by bletham** [comment]
And this is a handy code snippet for testing if rstan is working:
```
library(rstan)
model_code <- 'parameters {real y;} model {y ~ normal(0,1);}'
fit <- stan(model_code=model_code)  # this will take a minute
mean(extract(fit)$y)  # should be close to 0
```
Once that runs I'd expect the install to work.

**Comment by datawookie** [comment]
Hi @bletham,

Thanks for the feedback. I threw some more time at this and eventually figured it out. The process is written up (rather poorly!) here: https://datawookie.netlify.com/blog/2019/11/installing-prophet-on-centos/.

Thanks for the simple test for working `{rstan}`!

- Andrew.

**Comment by bletham** [comment]
Thanks for the writeup, that will be very helpful in the future! These gcc issues can be a bit hairy to work out, awesome you were able to get it working.
