### ISSUE TITLE
Prophet under forecasts Sundays consistently

### ISSUE THREAD

**Issue by jstephenj14** [facebook/prophet#1199]
Apologies if this is a simple issue but I'm finding that Prophet consistently under forecasts Sundays in my data. My actuals are higher than the forecasts. The actuals for the year before are far better proxies for this year's actuals than the forecasts. I can't upload a picture of the data since it's proprietary but I'd appreciate any help. I've tried the following to improve the situation but to no avail:

(1) added weekly seasonality = True
(2) added Sundays separately in the holidays data for the holidays input
(3) added a Sunday flag as an additional regressor (while turning off (2))

**Comment by benmwhite** [comment]
Instead of (2) and (3) I'd suggest trying out larger values for the weekly prior scale, maybe also increasing the Fourier order for that seasonality. The default priors perform regularization by default but you can tune them adjust how tightly you fit to the training data.

**Comment by jstephenj14** [comment]
> Instead of (2) and (3) I'd suggest trying out larger values for the weekly prior scale, maybe also increasing the Fourier order for that seasonality. The default priors perform regularization by default but you can tune them adjust how tightly you fit to the training data.

**Comment by bletham** [comment]
@jstephenj14 It sounds like you tried all of the things I'd first recommend (2 and 3 in particular make a lot of sense, though they are equivalent to eachother under the hood).

In particular as a binary extra regressor, model fitting tries to minimize squared error (plus some regularization terms) which typically does lead to the model fitting a holiday effect that is something like the average effect in the history. I do have a couple questions that might help to figure out what's happening.

* Does it under-forecast Sundays in just out-of-sample predictions (like, you fit using data through 2018 and then predict on 2019 and compare to actuals), or does it also under-predict on in-sample predictions? (meaning, you make predictions on the same data that were used in model fitting).

* Have you tried with multiplicative seasonality? I'm wondering if perhaps the size of the effect has been increasing over time, so maybe in early parts of the history it was smaller and so a smaller effect size is being fit as a result.
