### ISSUE TITLE
Modeling Holidays with Separate Day-Of-Week effects Without Data for Certain Days

### ISSUE THREAD

**Issue by trevor-pope** [facebook/prophet#1200]
For my dataset, the day of the week that Christmas falls on determines what the surrounding week will look like. As an example, let's say my dataset involves manufacturing data, where y is the number of units shipped. On weekends, we ship very little product, and during the weekdays we ship a lot.

For Christmas, last year it was on a Tuesday. We also close the day before Christmas, so Monday's y value is also low. But this year, Christmas is on Wednesday, and so we close on Tuesday, but we are open Monday, which will see a large spike due to Christmas demand.

I know I can specify a "Christmas_on_Tuesday" holiday, and a "Christmas_on_Wednesday" holiday to fit the separate effects, but I don't have data from the last time that Christmas was on Wednesday. I can probably create a regressor where I manually predict what Christmas week will look like, but I only want this regressor to be used for Christmas, and not fit anywhere else. Is this doable with regressors, or is there some other way to model this?

**Comment by xiaoyaoyang** [comment]
Maybe you can re-define your Christmas day. When Christmas_on_Tuesday, you could define last Friday as the holiday, whereas in the Christmas_on_Wednesday scenario , you could define Monday as your Christmas date. But you might need to set lower and upper window to 0..

**Comment by trevor-pope** [comment]
That doesn't really make sense to me, can you explain how that would help? No matter where I set my Christmas day to, the actual effects of Christmas will not change.

**Comment by trevor-pope** [comment]
Wait nevermind, I see what you mean. I will test this real quick, thanks!

**Comment by bletham** [comment]
Yeah, I was thinking something along those lines - have a binary regressor (or equivalently, holiday) for "last_workday_before_Christmas". Though if there are different effects depending on e.g. if that day is a Friday or a Monday, it might be hard to learn that without some manual intervention.
