### ISSUE TITLE
How to interpret params from FBProphet model which has external regressors. ?

### ISSUE THREAD

**Issue by himakiranalladi** [facebook/prophet#1201]
Firstly, great job with FBProphet! Using it in my project for cash flow forecasts. Is there a way to get the final equation of the FBProphet model after fitting it with training data? I looked into params function but, I was unable to interpret betas and deltas with K seasonality factors especially when I have external regressors. I would like to know how to get the betas of the external regressors ?

**Comment by himakiranalladi** [comment]
Thanks @benmwhite ! Looking into it. In one of the comments @bletham mentioned that I'd have to divide the value of the external regressor in the future dataframe with it's actual value to get standardized beta. But I was wondering if there was a simple equation that could define the complete model. Ill take a look at the paper as you suggested.

**Comment by bletham** [comment]
Probably the easiest place to see the equations is in the Stan code (which is meant to be readable like a probabilistic model):
https://github.com/facebook/prophet/blob/master/R/inst/stan/prophet.stan

Here `t` is time scaled to be between 0 and 1:
https://github.com/facebook/prophet/blob/83f66dadfd8f127687aa1d6e88cf153fff963fc7/R/R/prophet.R#L439-L440
https://github.com/facebook/prophet/blob/83f66dadfd8f127687aa1d6e88cf153fff963fc7/R/R/prophet.R#L402

and `y` is scaled by its maximum (absolute) value, so it will be between -1 and 1:
https://github.com/facebook/prophet/blob/83f66dadfd8f127687aa1d6e88cf153fff963fc7/R/R/prophet.R#L435
https://github.com/facebook/prophet/blob/83f66dadfd8f127687aa1d6e88cf153fff963fc7/R/R/prophet.R#L404

and `X` is the matrix of seasonality and extra regressors, constructed as defined in the paper and in code here:
https://github.com/facebook/prophet/blob/83f66dadfd8f127687aa1d6e88cf153fff963fc7/R/R/prophet.R#L855

Hope that helps!

**Comment by himakiranalladi** [comment]
@bletham Thank you for sharing! will look into this.
