### ISSUE TITLE
Non-linear growth

### ISSUE THREAD

**Issue by nba2020** [facebook/prophet#1208]
Thank you so much for contributing to this amazing package. I use it every week. Would it be possible to add non-linear option for growth with smoothing splines that optimize for the data modeled?

**Comment by bletham** [comment]
There is the logistic growth trend which provides a particular form of nonlinear growth (https://facebook.github.io/prophet/docs/saturating_forecasts.html#forecasting-growth) , but if you are looking for an entirely different type of trend model that's unfortunately something that is not easy to do right now. There is an issue for this in #705 , and it's on the roadmap to be done but it will still be some more time. If you're able to post a plot of your time series that would be helpful for knowing what type of trend might be appropriate in this case.

**Comment by alexsiormpas** [comment]
![Capture](https://user-images.githubusercontent.com/50983503/68480816-fda20f00-0235-11ea-93a6-e260221450e4.PNG)

**Comment by alexsiormpas** [comment]
A hypothetical example would be above. I don't have a specific use case in my current portfolio of forecasts, but I think could enhance the adaptability of trend lines.

**Comment by benmwhite** [comment]
For something like that you might be able to get a decent enough approximation with a finer grid of changepoints than the default.
