### ISSUE TITLE
Error while trying to import as a AWS Lambda layer

### ISSUE THREAD

**Issue by sree-kanth** [facebook/prophet#1209]
I have followed steps to package up FBProphet as a Layer, and created a Layer for FBProphet on AWS Lambda. I am able to add it as a Layer also, but when I run the Hello World Lambda function to test whether the Layer works, I get the following error: "Unable to import module 'lambda_function': No module named 'fbprophet'".

Has anyone experienced this issue? I have seen there is a way using Docker, I would prefer not to use the Docker solution as I prefer working with layers. Is there a fix?

**Comment by bletham** [comment]
I haven't used AWS Lambda myself so don't have any suggestions to give.

**Comment by ChiragSayaLife** [comment]
> I have followed steps to package up FBProphet as a Layer, and created a Layer for FBProphet on AWS Lambda. I am able to add it as a Layer also, but when I run the Hello World Lambda function to test whether the Layer works, I get the following error: "Unable to import module 'lambda_function': No module named 'fbprophet'".
> 
> Has anyone experienced this issue? I have seen there is a way using Docker, I would prefer not to use the Docker solution as I prefer working with layers. Is there a fix?

yes i am facing same issue looking for any solutions
![image](https://user-images.githubusercontent.com/93974916/226333047-a6b5006e-6a6c-4e7a-8b48-f9c64ba83074.png)
