### ISSUE TITLE
Negative predictions which doesn't make sense

### ISSUE THREAD

**Issue by maxwell873** [facebook/prophet#1214]
Hello,

I have daily historical sales data for one product (For 2 years, around 730 values in total). And i want to predict sales for the next 350 days. The historical values are always between 0 and 500 (on some days no units were sold) and on average around 50 per day.

After i created and fit the model and created the future dataframe for 350 days i made the predictions.

How can it be that some prediction values are negative although no single historical value is negative? (of course there can't be negative sales). Also many yhat_lower values are negative, especially the ones for which yhat is close to 0. Can i do anything do avoid this? Because negative sales doesn't make sense.

Thank you in advance!

**Comment by sammo** [comment]
@maxwell873 there is no way around negative predictions in prophet. If you use logistic growth you can prevent the trend component from falling below zero but that won't guarantee the seasonality components won't [push it down to negative](https://github.com/facebook/prophet/issues/337). This will need a Poisson regression which is not currently supported in Prophet. There is an [open issue](https://github.com/facebook/prophet/issues/337) for it but it's blocked by an RStan performance issue.

**Comment by bletham** [comment]
Just one more comment - as @sammo notes the logistic growth trend would be a good choice for a time series with a known floor at 0. In this case the seasonality can still push values below 0, but it would be totally appropriate to just clip those values to 0 after making the forecast.
