### ISSUE TITLE
Prophet will not run, but is not throwing errors

### ISSUE THREAD

**Issue by miamartin8** [facebook/prophet#1219]
I am trying to run a prophet script that runs fine on my coworkers machine (mac), but will not run on mine (pc).  All packages were installed in anaconda.  I had no issues importing the packages into my workbook.  When I try to run the script, the cell will not terminate, but it also does not throw any errors.  Any next steps to troubleshoot?

**Comment by djrscally** [comment]
We probably need to see the script itself. Is there any output reported to the console whilst it's running? 

My experience is that Prophet is slower on Windows than on Linux, so this could just be an extreme example of that.

**Comment by miamartin8** [comment]
The issue was that we were using multiprocessing to make the model run faster, and multiprocessing was not working on the PC.  No issues with Prophet.
