### ISSUE TITLE
Remove GPL dependency: Pystan

### ISSUE THREAD

**Issue by lcoulet** [facebook/prophet#1221]
Prophet is under MIT license but depends on a GPLv3 library: pystan.

Can pystan be replaced by an alernative ?

**Comment by benmwhite** [comment]
That's doubtful, literally everything runs through Stan AFAIK.

**Comment by sirpaddy** [comment]
Have a look here: [https://github.com/facebook/prophet/pull/1083](https://github.com/facebook/prophet/pull/1083)

**Comment by bletham** [comment]
As of v0.6 (now on PyPI), it is possible to use fbprophet with cmdstanpy (BSD licene) instead of PyStan; see #1045

**Comment by sirpaddy** [comment]
Thanks a lot for your **awesome** work!
