### ISSUE TITLE
Plot figsize not working for me

### ISSUE THREAD

**Issue by AndresJaramillo95** [facebook/prophet#1223]
Greetings,

I can't figure out how to change the figure size for my plots on prophet.  I have tried the method mentioned here #1182 Which is :

`from fbprophet.plot import plot
plot(m, fcst, figsize=(8, 4))`

How can I increase the figure size of this plot below?

fig = m.plot(forecast) 
ax1 = fig.add_subplot(111)
ax1.set_title(f"{ticker} Stock Price Forecast", fontsize=16)
ax1.set_xlabel("Date", fontsize=12)
ax1.set_ylabel("Close Price", fontsize=12)
plt.show()

Thank in advance

**Comment by bletham** [comment]
Calling `add_subplot(111)` on a figure that already has a subplot in the 111 position wouldn't be the standard way of doing this. There are basically two approaches for modifying axes properties of the plot. The first is to pass `m.plot` the axes to plot on:
```
fig = plt.figure(figsize=(8, 4))
ax = fig.add_subplot(111)
m.plot(forecast, ax=ax)  # Now it plots on the axes that we created
ax.set_title('Title here')
ax.set_xlabel('Change xlabel here')
```
The alternative would be to extract the axes that already exist on the figure:
```
fig = m.plot(forecast, figsize=(8, 4))
ax = fig.gca()  # instead of creating a new one, we get the existing one
ax.set_title('Title here')
ax.set_xlabel('Change xlabel here')
```

Either of those should allow you to adjust things in whatever way you'd like.
```

**Comment by AndresJaramillo95** [comment]
@bletham , thank you for your response. This helped solve my issue.
