### ISSUE TITLE
Add __version__ attribute

### ISSUE THREAD

**Issue by raybellwaves** [facebook/prophet#1225]
see https://github.com/dask/dask/blob/master/versioneer.py

**Comment by bletham** [comment]
There currently is a __version__ attribute that you can see in:
```
import fbprophet
print(fbprophet.__version__)
```
and comes from here: https://github.com/facebook/prophet/blob/0a270b4a19cafb084e5ed6ee0cf942198d4c913b/python/fbprophet/__init__.py#L10

This versioneer program for automatically updating that is intriguing but at the same time I think the burden of updating that for a version bump to be pretty low relatively to some of the other parts of pushing out a new version (like getting it through the CRAN build process), so this package probably isn't the target audience for that.
