### ISSUE TITLE
saving Prophet model in binary format

### ISSUE THREAD

**Issue by ostreech1997** [facebook/prophet#1228]
Hi, Can I save the model after fitting in binary format? I can't find the function. And How can I load the saved model when I want to predict by the model? I found only the way to use pickle package, but it doesn't suit me. Thank you!

**Comment by LVQAQ-cd** [comment]
Hi~
You can use these code to save you Porphet model
`
from sklearn.externals import joblib
joblib.dump(model,"model.pkl")
lr = joblib.load("model.pkl")
`
then you can use 'lr' to predict...
By the way,  I can't find the function in fbprophet too.

**Comment by bletham** [comment]
There's no built-in saving functionality, `pickle` (or equivalently `joblib`) is indeed the way to store a model. What makes pickle unsuitable? Do you need portability across platforms?
