### ISSUE TITLE
Formula to calculate trend and seasonality

### ISSUE THREAD

**Issue by ams1486** [facebook/prophet#1229]
Hi, I am trying to calculate the trend and seasonality components of the equation. 

1. For trend, I can calculate growth And offset using k values, gamma, changepoints and delta from the model parameters. However, summing up these doesn’t give me the trend value which I see in the forecast. What is the formula to calculate trend using growth and offset values?

2. Also, what is the formula to calculate the seasonality s(t). I see seasonality features using m.make_all_seasonality_features and there is also ‘beta’ in m.params. But I am not sure how and if we can use these values to calculate the seasonality component? What is the formula?

**Comment by trevor-pope** [comment]
The seasonality is fitted using a Fourier series, which is described on pages 11 and 12 of the [Prophet Paper](https://peerj.com/preprints/3190.pdf). The trend equation is also listed on page 10, but I'm sure @bletham can shine more light on this for you though.

**Comment by ams1486** [comment]
Thanks for the reply. Yes got it. Actually I was trying to derive the trend value that we see in the forecast using the params that we get from the model. I could calculate growth and offset using the k(initial growth), delta and changepoints but was not getting to the same trend value in forecast. I realized that we have to multiply (growth+offset) with y_scale to get to that. 
Thanks again.

**Comment by bletham** [comment]
Yes, as you discovered the model is fit after scaling both y and time. Y is scaled by `m.y_scale` as you note, and then time is mapped to be on [0, 1] (https://github.com/facebook/prophet/blob/0a270b4a19cafb084e5ed6ee0cf942198d4c913b/python/fbprophet/forecaster.py#L334-L335 and https://github.com/facebook/prophet/blob/0a270b4a19cafb084e5ed6ee0cf942198d4c913b/python/fbprophet/forecaster.py#L306).
