### ISSUE TITLE
I am getting the following error while doing : pip3 install Flask-MySQLdb

### ISSUE THREAD

**Issue by aashimagogia** [facebook/prophet#1231]

**Comment by aashimagogia** [comment]
pip install --upgrade setuptools
Requirement already up-to-date: setuptools in ./my_flask_app/venv/lib/python3.7/site-packages (42.0.1)
(venv) aashima@aashima-HP-348-G5:~$ pip3 install Flask-MySQLdb
Collecting Flask-MySQLdb
  Using cached https://files.pythonhosted.org/packages/62/e3/955c845efe1aacf30c8e2607470544ede36aa1044f6382c809f13e014104/Flask-MySQLdb-0.2.0.tar.gz
Requirement already satisfied: Flask>=0.10 in ./my_flask_app/venv/lib/python3.7/site-packages (from Flask-MySQLdb) (1.1.1)
Collecting mysqlclient
  Using cached https://files.pythonhosted.org/packages/d0/97/7326248ac8d5049968bf4ec708a5d3d4806e412a42e74160d7f266a3e03a/mysqlclient-1.4.6.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/aashima/my_flask_app/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-65u7nk_s/mysqlclient/setup.py'"'"'; __file__='"'"'/tmp/pip-install-65u7nk_s/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-65u7nk_s/mysqlclient/pip-egg-info
         cwd: /tmp/pip-install-65u7nk_s/mysqlclient/
    Complete output (12 lines):
    /bin/sh: 1: mysql_config: not found
    /bin/sh: 1: mariadb_config: not found
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-65u7nk_s/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-65u7nk_s/mysqlclient/setup_posix.py", line 61, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-65u7nk_s/mysqlclient/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by djrscally** [comment]
What does this have to do with prophet?

**Comment by Nitss10** [comment]
I am getting the same error? What do I do?
