### ISSUE TITLE
A confusing point when adjusting n_changepoints and using diagnostics together

### ISSUE THREAD

**Issue by yinanzhangepfl** [facebook/prophet#1232]
First, this is written in the tutorial:
"By default, Prophet specifies 25 potential changepoints which are uniformly placed in the first 80% of the time series."
In my project, I need to tune the parameter 'n_changepoints' and I also want to use the diagnostics part in Prophet to find a good set of parameters. It seems that when diagnostics is used, each time we fit time series of different lengths, but n_changepoints is specified to be the same value. Shouldn't this value be increased with the length of time series?
Hope someone can give me some hints. Many thanks.

**Comment by benmwhite** [comment]
You can override the defaults and specify your own set of changepoints manually instead. This should help if you need consistency across the models you're fitting and evaluating.

**Comment by yinanzhangepfl** [comment]
> You can override the defaults and specify your own set of changepoints manually instead. This should help if you need consistency across the models you're fitting and evaluating.

**Comment by yinanzhangepfl** [comment]
> You can override the defaults and specify your own set of changepoints manually instead. This should help if you need consistency across the models you're fitting and evaluating.

Hi benmwhite, Thank you very much for your answer. Do you mean that by default, fbprophet use the same number of changepoints for time series of different lengths? Think about cross validation for time series, every time we fit a longer training time series. To avoid this, we could revise the source code and specify our own set of changepoints.  Have I got it right?

**Comment by benmwhite** [comment]
>Think about cross validation for time series, every time we fit a longer training time series.

I'm not 100% sure how the changepoints are specified in the built-in cross validation tool, but I think they're the same locations as the ones used for the full training series. I'd love to be corrected if this interpretation is wrong however.

>revise the source code

You don't have to mess with any source code, it's available as an argument where you pass it a vector of dates/times to use as changepoint "locations". [See "Specifying the location of changepoints" here.](https://facebook.github.io/prophet/docs/trend_changepoints.html)

**Comment by yinanzhangepfl** [comment]
Hi benmwhite,

Thank you for editing your answer. I think you are right and I have understood this part. Thanks a lot.
