### ISSUE TITLE
Error when installing fbprophet on macOS catalina

### ISSUE THREAD

**Issue by BenWol** [facebook/prophet#1235]
I am trying to install fbprophet on my system, currently running macOS Catalina 10.15.1. I am installing `pip install fbprophet` on Python 3.7.5.
The following error occurs:

> 

Installing collected packages: fbprophet
    Running setup.py install for fbprophet ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/b.wolter/.pyenv/versions/3.7.5/envs/df_global/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/tf/zc10h6g9389csyzsp7nm2n_r0000gr/T/pip-install-7qdo2xnb/fbprophet/setup.py'"'"'; __file__='"'"'/private/var/folders/tf/zc10h6g9389csyzsp7nm2n_r0000gr/T/pip-install-7qdo2xnb/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/tf/zc10h6g9389csyzsp7nm2n_r0000gr/T/pip-record-jhk5qalf/install-record.txt --single-version-externally-managed --compile --install-headers /Users/b.wolter/.pyenv/versions/3.7.5/envs/df_global/include/site/python3.7/fbprophet
         cwd: /private/var/folders/tf/zc10h6g9389csyzsp7nm2n_r0000gr/T/pip-install-7qdo2xnb/fbprophet/
    Complete output (9 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/fbprophet
    creating build/lib/fbprophet/stan_model
    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_861b75c6337e237650a61ae58c4385ef NOW.
    error: command 'clang' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/b.wolter/.pyenv/versions/3.7.5/envs/df_global/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/tf/zc10h6g9389csyzsp7nm2n_r0000gr/T/pip-install-7qdo2xnb/fbprophet/setup.py'"'"'; __file__='"'"'/private/var/folders/tf/zc10h6g9389csyzsp7nm2n_r0000gr/T/pip-install-7qdo2xnb/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/tf/zc10h6g9389csyzsp7nm2n_r0000gr/T/pip-record-jhk5qalf/install-record.txt --single-version-externally-managed --compile --install-headers /Users/b.wolter/.pyenv/versions/3.7.5/envs/df_global/include/site/python3.7/fbprophet Check the logs for full command output.

I think I understand that the problem is related to the C compiler, therefore `error: command 'clang' failed with exit status 1`. When checking pystan with some example code, it is also not running. Cython seems to be installed just fine. Anyone? Can help with it?

**Comment by sammo** [comment]
The easiest way to install fbprophet is with conda through conda forge. You can install miniconda and use it.
`conda install -c conda-forge fbprophet`
Check documentation [here](https://facebook.github.io/prophet/docs/installation.html#python), last section.

**Comment by bletham** [comment]
Yeah, it definitely looks like pystan is not working. I know rstan had many issues with the Catalina release (https://twitter.com/mcmc_stan/status/1186923309662953472?lang=en) but I'm not aware of anything for pystan. Ultimately I don't think I can do better than to refer you to https://pystan.readthedocs.io/en/latest/installation_beginner.html or the pytsan repository. I agree with @sammo that the easiest way to avoid C++ compiler problems is to use Anaconda, though I do know that it can work without Anaconda in OSX if you want to keep fiddling with it.

**Comment by NicolaDonelli** [comment]
**System:** MacOS Catalina 10.15.6

I struggled a bit but I managed to install fbprophet using pip instead of conda.

As @bletham pointed out there is a problem with pystan: 

- it does not work with default Apple clang compiler (clang version 10.0.0, Target: x86_64-apple-darwin19.6.0, Thread model: posix). I didn't manage to exactly understand what actually goes wrong but it seems that there is some sort of incompatibility with C++14 standard used by PyStan.
- it does not work with gcc 10.2.0 (installed with `brew install gcc@10`) because of some changes in library libstdc++ shipped with this compiler wrt the one required for PyStan.
- **it works with gcc 7.5.0_2** (installed with `brew install gcc@7`)

So to install fbprophet you can run:
`CC=/usr/local/Cellar/gcc@7/7.5.0_2/bin/gcc-7 ; CXX=/usr/local/Cellar/gcc@7/7.5.0_2/bin/g++-7; pip install pystan; pip install fbprophet`

**Comment by maddy2u** [comment]
CC=/usr/local/Cellar/gcc@7/7.5.0_2/bin/gcc-7; CXX=/usr/local/Cellar/gcc@7/7.5.0_2/bin/g++-7; pip install pystan; pip install fbprophet

This failed for me with errors

```

Installing collected packages: fbprophet
  Running setup.py install for fbprophet ... error
    Complete output from command /Volumes/unix/workplace/Sentinel/venv/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/k5/fxywqn0n0s1_qcbwk61z8ymw8nvqvk/T/pip-install-xthv0lg9/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/k5/fxywqn0n0s1_qcbwk61z8ymw8nvqvk/T/pip-record-fwb3qqcb/install-record.txt --single-version-externally-managed --compile --install-headers /Volumes/unix/workplace/Sentinel/venv/include/site/python3.7/fbprophet:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/fbprophet
    creating build/lib/fbprophet/stan_model
    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_dfdaf2b8ece8a02eb11f050ec701c0ec NOW.
    error: command '/usr/local/Cellar/gcc@7/7.5.0_2/bin/gcc-7' failed with exit status 1
    
    ----------------------------------------
Command "/Volumes/unix/workplace/Sentinel/venv/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/k5/fxywqn0n0s1_qcbwk61z8ymw8nvqvk/T/pip-install-xthv0lg9/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/k5/fxywqn0n0s1_qcbwk61z8ymw8nvqvk/T/pip-record-fwb3qqcb/install-record.txt --single-version-externally-managed --compile --install-headers /Volumes/unix/workplace/Sentinel/venv/include/site/python3.7/fbprophet" failed with error code 1 in /private/var/folders/k5/fxywqn0n0s1_qcbwk61z8ymw8nvqvk/T/pip-install-xthv0lg9/fbprophet/

```

**Comment by Agudo07** [comment]
> Sorry for posting in a closed issue but I think I could add something interesting since I managed to install fbprophet using pip instead of conda.
> 
> As @bletham pointed out there is a problem with pystan:
> 
> * it does not work with default Apple clang compiler (clang version 10.0.0, Target: x86_64-apple-darwin19.6.0, Thread model: posix). I didn't manage to exactly understand what actually goes wrong but it seems that there is some sort of incompatibility with C++14 standard used by PyStan.
> * it does not work with gcc 10.2.0 (installed with `brew install gcc@10`) because of some changes in library libstdc++ shipped with this compiler wrt the one required for PyStan.
> * **it works with gcc 7.5.0_2** (installed with `brew install gcc@7`)
> 
> So to install fbprophet you can run:
> `CC=/usr/local/Cellar/gcc@7/7.5.0_2/bin/gcc-7; CXX=/usr/local/Cellar/gcc@7/7.5.0_2/bin/g++-7; pip install pystan; pip install fbprophet`


This worked for me even in 2020(macOS Catalina). First I used: brew install gcc@7, which took a long time to finish with an error output. Nevertheless, it stated what further lines should be written in the shell in order to install gcc@7 successfully. Thereafter, I could install gcc@7 and, after that, I could run: CC=/usr/local/Cellar/gcc@7/7.5.0_2/bin/gcc-7; CXX=/usr/local/Cellar/gcc@7/7.5.0_2/bin/g++-7; pip install pystan; pip install fbprophet

This installed fbprophet successfully. 

Thanks!

**Comment by skannan-maf** [comment]
Pystan issues can be solved by:
pip install pystan==2.19.1.1

This is because after 3.x version, stan has to be imported as "import stan"
Earlier, it was imported as "import pystan"
FBProphet uses "import pystan" and so we need to use only 2.x version of pystan.
2.19.1.1 is the last 2.x version of pystan.

HTH...
