### ISSUE TITLE
Is it possible to use frequency of 16 days?

### ISSUE THREAD

**Issue by jerubio** [facebook/prophet#1236]
I have time series form MODIS satellite images which are available every 16 days (yyyy001, yyyy017, yyyy033 and so on - julian dates)

How can I set the freq parameter?

Thnks a lot

**Comment by sammo** [comment]
@jerubio Prophet doesn't take a frequency parameter. What 'frequency parameter' are you trying to set?

**Comment by jerubio** [comment]
@sammo 
future_data = model.make_future_dataframe(periods=12, freq = 'm')
taken from 
https://pythondata.com/forecasting-time-series-data-with-prophet-part-2/

**Comment by sammo** [comment]
I see. You should be able to generate the future dataframe using "16D" as the frequency. The code would be:
`future_data = model.make_future_dataframe(periods=12, freq='16D')`

**Comment by jerubio** [comment]
Thanks a lot!
Cordially yours
