### ISSUE TITLE
Very wild prediction.

### ISSUE THREAD

**Issue by LeLocTai** [facebook/prophet#1237]
I'm getting this prediction, which seem inaccurate to me. I'm not sure what I'm doing wrong.
![image](https://user-images.githubusercontent.com/12182348/69950676-5a87a100-1526-11ea-84fe-f71a7d5a954f.png)

This is the relevant code:

```
winterSale = pd.DataFrame({
    'holiday': 'winterSale',
    'ds': pd.to_datetime(['2017-11', '2018-11', '2019-11', '2020-11']),
    'lower_window': 0,
    'upper_window': 31,
})

model = Prophet(
    holidays=winterSale,
    yearly_seasonality=True,
    weekly_seasonality=False,
    daily_seasonality=False)
model.fit(df)

future = model.make_future_dataframe(periods=6, freq='M')
future['cap'] = 2000
future['floor'] = 0

forecast = model.predict(future)

fig1 = model.plot(forecast)
a = add_changepoints_to_plot(fig1.gca(), model, forecast)
```

And this is the data:
```
	index	ds	y	cap	floor
0	0	2017-03-01	97.93	2000	0
1	1	2017-04-01	223.82	2000	0
2	2	2017-05-01	97.93	2000	0
3	3	2017-06-01	139.90	2000	0
4	4	2017-07-01	153.89	2000	0
5	5	2017-08-01	153.89	2000	0
6	6	2017-09-01	237.83	2000	0
7	7	2017-10-01	265.81	2000	0
8	8	2017-11-01	1117.41	2000	0
9	9	2017-12-01	461.61	2000	0
10	10	2018-01-01	293.79	2000	0
11	11	2018-02-01	209.85	2000	0
12	12	2018-03-01	341.33	2000	0
13	13	2018-04-01	349.72	2000	0
14	14	2018-05-01	262.99	2000	0
15	15	2018-06-01	221.02	2000	0
16	16	2018-07-01	243.40	2000	0
17	17	2018-08-01	327.35	2000	0
18	18	2018-09-01	232.22	2000	0
19	19	2018-10-01	260.19	2000	0
20	20	2018-11-01	234.98	2000	0
21	21	2018-12-01	230.76	2000	0
22	22	2019-01-01	181.85	2000	0
23	23	2019-02-01	232.21	2000	0
24	24	2019-03-01	332.98	2000	0
```

**Comment by LeLocTai** [comment]
If I try to use a higher period, this is what it look like:
![image](https://user-images.githubusercontent.com/12182348/69950892-c538dc80-1526-11ea-949c-99a9f552b82c.png)

**Comment by sammo** [comment]
@LeLocTai looks like you switched the floor and cap columns in the training data. cap should be 2000 and floor 97.93, ...

**Comment by LeLocTai** [comment]
It looked wrong here since it is misaligned, but the cap is 2000, floor is 0 and y is 97

**Comment by sammo** [comment]
I see. That's an interesting issue. Can you graph the components (trend, yearly, holidays) to see where the spikes are coming from?

**Comment by LeLocTai** [comment]
So the spike seem to come from holiday and year. But what fixed it is using seasonality_mode='multiplicative'. The prediction still overshoot floor and cap in both growth model, but not by a implausible amount, adjusting the scales will probably work for that.
