### ISSUE TITLE
Integration Error: Using Modin library in Prophet

### ISSUE THREAD

**Issue by s0301132** [facebook/prophet#1241]
Hi @dreiss !

**System information**

- Macos catalina 10.15.1
- Python version 3.7.3:

I'm trying to use the modin library to speed up the pandas workflow in prophet. But I got some error during the process, I raise the issue in modin repositories before:
modin-project/modin#884

So can I change some coding to integrate the modin inside the prophet library? Thanks!

**Comment by bletham** [comment]
I wasn't previously familiar with modin, but it looks like you would need to change the fbprophet pandas imports to instead import modin, e.g. here: https://github.com/facebook/prophet/blob/0a270b4a19cafb084e5ed6ee0cf942198d4c913b/python/fbprophet/forecaster.py#L14

Then things may or may not work, depending on whether or not we are using pandas API calls that are not yet covered in modin; they report about 80% coverage. We use a bunch of pandas datetime functionality which seems to be less commonly used so there's a definite chance of it not working.

**Comment by LizMcQuillan** [comment]
Was this functionality ever integrated? I'm assuming no, since I just attempted to use Modin and Prophet didn't like it.

**Comment by bletham** [comment]
I haven't heard of anyone testing Modin compatibility, so I expect not.
