### ISSUE TITLE
Suppressing `logger.error('Importing plotly failed. Interactive plots will not work.')`

### ISSUE THREAD

**Issue by DBCerigo** [facebook/prophet#1242]
I'm not using interactive plots, but the`fbprophet` logger logs the above error at the time `prophet` is imported. This creates unnecessary noise in application logging. 

Is there anyway I can suppress that error? (I still want to propagate other logs from `fbprophet`.)

Link to line for ref: https://github.com/facebook/prophet/blob/83f66dadfd8f127687aa1d6e88cf153fff963fc7/python/fbprophet/plot.py#L38

**Comment by Rockgecko** [comment]
I'd like to do this too.

**Comment by bletham** [comment]
I don't think there's any way to do this right now.

What we can do to make this possible is to change the logger for the plotting to be a different logging. That is, change
https://github.com/facebook/prophet/blob/0a270b4a19cafb084e5ed6ee0cf942198d4c913b/python/fbprophet/plot.py#L16
to be something like
```
logger = logging.getLogger('fbprophet.plot')
```

That would allow for setting different logging levels for the `fbprophet` logger (could stay at default) and the `fbprophet.plot` logger (could be set to critical).

**Comment by bletham** [comment]
This is now pushed to PyPI in v0.6. See the PR in #1332 for an example of how to disable logging for plotting but not other logging.

**Comment by mthmtc** [comment]
the following strange solution helped me

```
class suppress_stdout_stderr(object):
    def __init__(self):
        self.null_fds = [os.open(os.devnull, os.O_RDWR) for x in range(2)]
        self.save_fds = [os.dup(1), os.dup(2)]

    def __enter__(self):
        os.dup2(self.null_fds[0], 1)
        os.dup2(self.null_fds[1], 2)

    def __exit__(self, *_):
        os.dup2(self.save_fds[0], 1)
        os.dup2(self.save_fds[1], 2)
        for fd in self.null_fds + self.save_fds:
            os.close(fd)

with suppress_stdout_stderr(): 
    from fbprophet import Prophet

```
