### ISSUE TITLE
Suppress one-off peaks in seasonality

### ISSUE THREAD

**Issue by 99snowleopards** [facebook/prophet#1243]
Hello, I am fitting the Prophet model on 5 years of data for stores. The problem I'm having is that some stores have very high sales in one month of one year and that high sales value dominates the seasonality plot. 

For e.g., a store has higher sales in May for 4 of the past 5 years, but has very high sales in September of just one year. The yearly (monthly) seasonality plot peaks in September, wrongly indicating that sales for the store tends to peak in September.

How do I prevent high values of sales in just one month of one year from dominating the yearly seasonality plot? Please let me know if I can provide any further information that might help clarify the question. Thanks,

**Comment by benmwhite** [comment]
I think adjusting the monthly seasonal prior scale should help here.

**Comment by AnushaChan** [comment]
@benmwhite Thanks for your response. We did try changing seasonal prior scale but there was no change in yearly seasonality plot. We happen to observe that the one-off peaks were found for a couple of days, which had unusual spike in sales (i.e. more than twice the average sales in the month).

So, modelling these specific one-time peak dates as holidays (special events without repetition) produced a stable seasonality plot. Please let us know if you think any other approach would handle this scenario.

**Comment by bletham** [comment]
The model fitting minimizes a Gaussian log-likelihood which means that (subject to some regularization from the priors) it basically is finding a least-squares fit. So if you have a big peak in one year and no peak for 4 more years, the seasonality that minimizes squared error will be something like the average across years; so the peak will drag up the estimate, and every additional non-peak year will pull it down a little more. Is this consistent with what you're seeing? I'm guessing that this one September peak was large enough that even with four years of non-peak, the average is still pretty high.

In terms of how to fix it: reducing seasonal prior scale would suppress seasonality everywhere; in Sepetember, but also in May, so it wouldn't be the right solution here.

What I would recommend is what it sounds like you ended up doing, which is that if you believe that this one September was unusual in some way / different from what you expect future Septembers to be like, then you could define a holiday for that month and it would basically treat that event as a one-off thing and not effect future September seasonality.

**Comment by 99snowleopards** [comment]
Thanks so much for replying @bletham ! We'll try your suggestion and get back on this.
