### ISSUE TITLE
Update the model

### ISSUE THREAD

**Issue by johnnykahits** [facebook/prophet#1244]
I'm using Prophet to make a forecast but don't know if is possible to make an incremental update without training again the model? The reason is because I'm forecasting a lot of items and it takes too much time.

Thanks :)

**Comment by sammo** [comment]
@johnnykahits partial_fit has been under discussion as a potential new feature. Check out the discussion is [here 46](https://github.com/facebook/prophet/issues/46).

**Comment by johnnykahits** [comment]
Thanks Sam. Is it possible to build a forecast with the results of the model (trend lower, trend upper, additive terms, etc.) and using the equations of the paper? https://peerj.com/preprints/3190.pdf

**Comment by bletham** [comment]
@johnnykahits what exactly do you mean by trying to build a forecast from the components and from the equations from the paper? You can compute yhat just by summing the various components (e.g. https://github.com/facebook/prophet/blob/0a270b4a19cafb084e5ed6ee0cf942198d4c913b/python/fbprophet/forecaster.py#L1209-L1213 ).
