### ISSUE TITLE
Multiplicative_Terms does not equal the product of seasonal components

### ISSUE THREAD

**Issue by driskerr** [facebook/prophet#1245]
When working with a multiplicative model, I would think that  `yhat = trend*(1+weekly)*(1+yearly)`. 

Digging into the source code, I realize that `yhat = trend*(1+multiplicative_terms)`. However, I am uncertain of the calculation of `multiplicative_terms`. It seems that **_multiplicative_** terms is equal to the **_sum_** of the seasonal components, not the **_product_**.

For example, here are the first few lines of my `forecast` table:

ds | trend | ...  | multiplicative_terms | ...| weekly | ... | yearly | ... | yhat
-- | -- |  -- | -- | -- | -- |  --  | -- | -- | --
2017-01-01 | 0.173733768 | ... | 0.020518826 |...| 0.102948 | ... | -0.08243 | ... | 0.177299
2017-01-02 | 0.173652392 | ... | -0.150241624 |...|  -0.07322 |... | -0.07702 | ... | 0.147563
2017-01-03 | 0.173571017 | ... | -0.117270706 |...|  -0.04545 | ... | -0.07182 | ... | 0.153216

You'll notice that `multiplicative_terms` = `weekly` + `yearly`, which seem like a mismatch between description (multiplying) and function (adding). Wondering if this intentional/if there is some understanding that I am missing?

My code to generate the `forecast` table is pretty straight forward:
```
    # Fit the model with Prophet
    m = Prophet(seasonality_mode='multiplicative')
    m.fit(data)
    

    # Forecast x weeks ahead
    future = m.make_future_dataframe(periods=12*7, freq='D')
    forecast = m.predict(future)
```

**Comment by sammo** [comment]
@driskerr multiplicative_terms should be multiplied by the trend before they can be summed up with additive terms to make yhat.

`yhat = trend + additive_terms + trend * multiplicative_terms`

In the case of several multiplicative seasonalities, let's say weekly and yearly, multiplicative_terms would be the sum of the two.

**Comment by bletham** [comment]
That's right, what's happening here is that the total seasonal effect is multiplicative on the trend. This means that each seasonality will be multiplicative on the trend, but then all of these components add up. Like
```
yhat = trend + trend * weekly + trend * yearly + ...
```
so there aren't any interactions across seasonalities.

The actual code that does this is here:
https://github.com/facebook/prophet/blob/0a270b4a19cafb084e5ed6ee0cf942198d4c913b/python/fbprophet/forecaster.py#L1209-L1213
