### ISSUE TITLE
How do timezones interact with holidays?

### ISSUE THREAD

**Issue by Brideau** [facebook/prophet#1247]
I have time series data that is in UTC but that is impacted a lot by holidays, and I'm looking to predict at the hourly grain. Because this data is from a location that is many hours shifted from UTC, some of the data from the end of the day gets shifted into the next day from UTC's perspective. Do the holidays take this into account?

**Comment by bletham** [comment]
Prophet doesn't do any handling for timezones (and in fact will error out if the PD series has a timezone specified, https://github.com/facebook/prophet/blob/0a270b4a19cafb084e5ed6ee0cf942198d4c913b/python/fbprophet/forecaster.py#L249-L253 ).

The way holidays are handled is fairly simple for hourly data. Basically, every ds in the history/future that has the date of the holiday is given the holiday effect:
https://github.com/facebook/prophet/blob/0a270b4a19cafb084e5ed6ee0cf942198d4c913b/python/fbprophet/forecaster.py#L518

What this means is that there is a constant holiday effect that will be added to the daily seasonality. So if you have daily seasonality s(t) (with period 24 hrs), then on a holiday it will be s(t) + h where h is constant for the day.

The holiday offset is added to every row that has the holiday date in the dataframe, which means that if the dataframe is in UTC but the holiday effect is not, then the offset may not line up with the actual holiday effect.

The way to correct this would be to note use the holiday input to the model, but rather to model the holiday manually with a binary extra regressor. Then you would identify for each row in the df a 1 if that row should get the holiday effect and a 0 if not; so you could offset that to the proper timezone.

As a sidenote, I can imagine that in some situations with hourly data the _shape_ of the daily seasonality might be different on the holiday, and just fitting a constant offset is insufficient. If you want to capture that level of a holiday effect, then you can use the conditional seasonalities described here: https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#seasonalities-that-depend-on-other-factors . Basically you would add a new daily seasonality specifically for the holiday.

**Comment by strakehyr** [comment]
To be honest, this is just lazy. The model should account country holidays as per the timezone of the country they are in (selectable if there are several tzs in same country). This is not a specific case, it is a directly incorrect application of the intended functionality. And this is just another consequence of having prophet convert everything to UTC (also a mistake). Hourly patterns follow the timezone they are in, in almost everything related to human behaviour (most of the data these models are used for).
