### ISSUE TITLE
mute fbprophet training stacktrace

### ISSUE THREAD

**Issue by jaeniale-fd** [facebook/prophet#1248]
Is it possible to mute the training output, e.g.:

> Initial log joint probability = -22.9872
>     Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes 
>       94       627.764   0.000394725       83.4895   5.478e-06       0.001      157  LS failed, Hessian reset 
>       99       627.773   1.52474e-05       72.6313     0.09498     0.09498      163   
>     Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes 
>      155       627.822   0.000230212       100.026   2.599e-06       0.001      272  LS failed, Hessian reset 
>      198       627.869   3.37608e-06       73.4047   4.556e-08       0.001      362  LS failed, Hessian reset 
>      199       627.869   2.20748e-06       62.3663           1           1      363   
>     Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes 
>      235       627.869   2.02112e-06       81.5566   2.831e-08       0.001      449  LS failed, Hessian reset 
>      251       627.869   4.53416e-09       66.3179      0.1709      0.1709      470

**Comment by david-ml** [comment]
I use this class (found at the documented URL below) as a context manager to mute training output:

```
class suppress_stdout_stderr(object):
    """
    https://github.com/joblib/joblib/issues/868
    A context manager for doing a "deep suppression" of stdout and stderr in
    Python, i.e. will suppress all print, even if the print originates in a
    compiled C/Fortran sub-function.
       This will not suppress raised exceptions, since exceptions are printed
    to stderr just before a script exits, and after the context manager has
    exited (at least, I think that is why it lets exceptions through).
    """
    def __init__(self):
        # Open a pair of null files
        self.null_fds = [os.open(os.devnull, os.O_RDWR) for x in range(2)]
        # Save the actual stdout (1) and stderr (2) file descriptors.
        self.save_fds = [os.dup(1), os.dup(2)]

    def __enter__(self):
        # Assign the null pointers to stdout and stderr.
        os.dup2(self.null_fds[0], 1)
        os.dup2(self.null_fds[1], 2)

    def __exit__(self, *_):
        # Re-assign the real stdout/stderr back to (1) and (2)
        os.dup2(self.save_fds[0], 1)
        os.dup2(self.save_fds[1], 2)
        # Close the null files
        for fd in self.null_fds + self.save_fds:
            os.close(fd)
```

e.g.
```
with suppress_stdout_stderr():
    prophet_model.fit(ts)
```
