### ISSUE TITLE
how to make prediction more volatile

### ISSUE THREAD

**Issue by jaeniale-fd** [facebook/prophet#1249]
Hey,

first of all thank you for this nice framework and thanks to all the people that are contributing to that.
So i have a model that catches my pattern very good, but it would be much better if it actually is more volatile at all the spikes, is there a way to tune this?

Here is an example:
![export](https://user-images.githubusercontent.com/58504345/70784979-33349d80-1d8a-11ea-8edd-c10d3750f9da.png)

Thanks in advance,
Alex

**Comment by benmwhite** [comment]
Try increasing the [seasonality prior scales](https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#prior-scale-for-holidays-and-seasonality) and/or [seasonality Fourier orders](https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#fourier-order-for-seasonalities).  Sometimes it can also help to switch from the default additive effects to [multiplicative effects](https://facebook.github.io/prophet/docs/multiplicative_seasonality.html) depending on your time series.

**Comment by jaeniale-fd** [comment]
First of all thank you for your answers. I played a bit around with those numbers but it only resulted a very small difference, even if i changed the numbers by a lot. (Fourier order from 1 to 100, same with seasonality prior scale)

**Comment by benmwhite** [comment]
If the spikes are happening on known short intervals it might also help to specify those windows as holidays so they get a separate effect to be estimated.

**Comment by jaeniale-fd** [comment]
it is basically always not going high / low enough, so its not at specific intervals.

**Comment by bletham** [comment]
I think the most likely reason this would happen would be that the seasonality has changed over the course of the time series, and so it isn't able to fit it very precisely. To figure it out it would be very helpful if you could post the plot generated by `m.plot()` (you can wipe out the axis labels, but seeing the blue model fit with data dots for the entire time series would make it much more clear what is happening here).
