### ISSUE TITLE
Improve predict speed on small dataset

### ISSUE THREAD

**Issue by guyskk** [facebook/prophet#1252]
I found predict cost 1~2 seconds even if future has only one row.
Is it possible to make fit + predict finish in 100ms if history is small(<100) and only predict one future item?

```python
import pandas as pd
from fbprophet import Prophet

df = pd.read_csv('../examples/example_wp_log_peyton_manning.csv')
m = Prophet()
m.fit(df)  # about 200ms

future = m.make_future_dataframe(periods=365)
forecast = m.predict(future)  # about 5s

future = m.make_future_dataframe(periods=1, include_history=False)
forecast = m.predict(future)  # about 2s
```

**Comment by bletham** [comment]
Most of the cost for predict comes from computing the uncertainty intervals which is done with a Monte Carlo simulation that uses 1000 samples by default (the argument here: https://github.com/facebook/prophet/blob/0a270b4a19cafb084e5ed6ee0cf942198d4c913b/python/fbprophet/forecaster.py#L76-L78)

Reducing that parameter will speed things up alot. With `uncertainty_samples=100`, I get 160ms for when `include_history=False` in the future dataframe. With `uncertainty_samples=0`, I get 60ms. Reducing `uncertainty_samples` will increase the variance of the estimates of `yhat_lower` and `yhat_upper`. If you don't need those, then you can set it to 0 with no loss. If you do need uncertainty, you'd have to see what trade-off you're able to make between variance in those estimates and running time. I do think 1000 is pretty conservative, so you could reduce that quite a bit before the uncertainty estimates became too noisy.

**Comment by aliparsaa** [comment]
how you can forecast with only 2month series of price?
