### ISSUE TITLE
Hierarchical time series modeling

### ISSUE THREAD

**Issue by jroberayalas** [facebook/prophet#1254]
Is there a way to do hierarchical time series modeling with Prophet? I'm trying to come up with something similar to this [post](http://htmlpreview.github.io/?https://github.com/lauken13/Beginners_Bayes_Workshop/blob/master/stancon2019-intro.html) but taking advantage of Prophet's decomposition approach. Any help is greatly appreciated.

**Comment by bletham** [comment]
Not really. I have a comment here (https://github.com/facebook/prophet/issues/49#issuecomment-430383681) that describes how one could handle a hierarchical time series using extra regressors that may work in some situations, but it's really a case of YMMV.
