### ISSUE TITLE
I don't understand prophet cross_validation, some help here

### ISSUE THREAD

**Issue by jiwidi** [facebook/prophet#1257]
Hi! 

So I discovered the built in method [cross validation](https://facebook.github.io/prophet/docs/diagnostics.html) and I have a few questions on how does it really work.

I'm used to this use/defition of cross validation: 
![image](https://user-images.githubusercontent.com/10882086/71247011-267af100-2318-11ea-85e9-a8a3b598f1ea.png)

But this doesn't make have much sense to do in time series (because the time dimension and not wanting data leakage). 

What makes more sense to me and I think the prophet cross_validation method does is something like:
![image](https://user-images.githubusercontent.com/10882086/71247624-642c4980-2319-11ea-8271-8f080c35decd.png)

(Ignore the first row) Where you train on the red-doted data and evaluate on the blue cell, NOT using the black crossed data to train neither test (on the opposite to normal cross_validation).

Does the prophet method work like the second image? If so, what is exactly the parameter `horizon` mean?

I have used cross_validation to evaluate on 1 day predictions and I'm sure of what each parameter means. My code:
```python
from fbprophet.diagnostics import cross_validation
df_cv = cross_validation(m, initial='2189 days', period='1 days', horizon = '1 days')
df_cv.head()
```

Here I expect to evaluate on 1-day forecast from the 2189th row of the data to the end of it. So it should:

1 -  Create a model with 2189 datapoints as training data and evaluate on the 2190th datapoint
2 -  Create a model with 2190 datapoints as training data and evaluate on the 2191th datapoint
3 -  Create a model with 2191 datapoints as training data and evaluate on the 2192th datapoint
.
.
.
N - Create a model with N-1 datapoints as training data and evaluate on the Nth (last) datapoint.

Is this the correct behavior of the method?

**Comment by NikeNano** [comment]
I found this in the documentation and think it explains the answer to your questions quite well: https://facebook.github.io/prophet/docs/diagnostics.html

**Comment by bletham** [comment]
That is a correct description. I hope the documentation page that @NikeNano linked to explains this in an understandable way, but to directly answer your question - yes, the parameters you specified will give you the behavior described. When you look at the output `df_cv`, it will show in each row what the cutoff was and what the ds for the point being predicted was. The cutoff is the last day included in the training data, and ds is the point predicted with that training data. It should match the N points that you wrote out.

**Comment by rokazok** [comment]
Would this nested cross-validation overweight earlier timepoints? ex. In the modified visual below, the earliest data are used in all four folds (Performance 2-5) while the most recent data are only used in the last fold (Performance 5).

![crossvalidation](https://user-images.githubusercontent.com/16184194/115601669-ec668a00-a292-11eb-82bc-9a671131cb04.png)

Would a rolling block be more appropriate for more evenly weighting time periods? ex. Each fold trains on a fixed period (red dots) of past data.
![cv_roll](https://user-images.githubusercontent.com/16184194/115604522-55033600-a296-11eb-8932-4dcb3f182563.png)
