### ISSUE TITLE
PROPHET : Hierarchical and grouped forecasting

### ISSUE THREAD

**Issue by RJASROTIA** [facebook/prophet#1258]
is there a way to do hierarchical and grouped forecasting in prophet?

**Comment by trevor-pope** [comment]
You can create the forecasts in Prophet, then use the [hts package](https://pkg.earo.me/hts/) in R.

**Comment by bletham** [comment]
Yeah, there isn't any actual support for this in Prophet. The best you could do is try to use extra regressors for higher-level time series (like in https://github.com/facebook/prophet/issues/49#issuecomment-283330787) but it wouldn't be a true hierarchical forecast and YMMV.
