### ISSUE TITLE
Prophet Logistic Growth Predict issue in Python

### ISSUE THREAD

**Issue by Danielg18** [facebook/prophet#1259]
Hi,

I'm experiencing an issue with Prophet in Python when I try to predict some data with ```Logistic Growth```, for instance, I fit the model on a 3 year daily period and then try to forecast a month forward and it just gives ```NaN``` for all predictions.
The ```Linear Growth``` works, but the ```Logistic Growth``` does not.
This is a problem for me because I need the `Logistic` and not the `Linear`.

The ```fit``` function seems to work fine:
![2019-12-26 (1)](https://user-images.githubusercontent.com/36474085/71468992-7f430180-27d0-11ea-8d42-02aceaab7c7d.png)

But when I use the ```predict``` function, it just returns a ```NaN``` trend and yhat:
![2019-12-26](https://user-images.githubusercontent.com/36474085/71469053-ab5e8280-27d0-11ea-918e-233f26d9a277.png)

Here is a snippet of my code:
```
m = Prophet(growth="logistic",
                     holidays=df_holidays,
                     changepoints=[datetime.strptime('2018-12-14', '%Y-%m-%d'),
                                               datetime.strptime('2016-07-22', '%Y-%m-%d'),
                                               datetime.strptime('2017-01-27', '%Y-%m-%d'),
                                               datetime.strptime('2017-08-12', '%Y-%m-%d'),
                                               datetime.strptime('2018-09-09', '%Y-%m-%d')])
m.fit(df_with_cap)
future = m.make_future_dataframe(periods=31)
future['cap'] = 30000
forecast = m.predict(future)
```

I gave it a try in R (same system, same data) and it works there without any issues.
Therefore, I would like to know if this is a bug specifically in the Python package or something else? Maybe I'm doing something wrong here?
Looking forward to your replies!
Thank you!

**Comment by bletham** [comment]
That's a bit surprising to hear that it works in R but not Python. My initial guess is that the optimizer is having an issue (since that could be compiled differently in R or Py) but the printout of fit looks like things are working. Is there any chance you can post the data so I can try to reproduce this?
