### ISSUE TITLE
Increasing the predicting columns  at a time

### ISSUE THREAD

**Issue by hanu7674** [facebook/prophet#1260]
hello why should we predict different columns data a time using the same methods. you restricted to only one column at a time. Suppose we are predicting the different columns at a time then we need to go different files and then copy it to the desired file.its difficult at all time.

**Comment by bletham** [comment]
I'm don't fully understand the question; are you trying to predict multiple time series? In that case yes you need to do it separately for each, but you could do this programmatically in a `for` loop.

**Comment by hanu7674** [comment]
explain it with a simple example. is fbprophet supports predicton for minutes, if available explain it also

**Comment by bletham** [comment]
Yes, see https://facebook.github.io/prophet/docs/non-daily_data.html#sub-daily-data for an example.

**Comment by hanu7674** [comment]
Ok, Thanks for replying...it will be useful for us...
