### ISSUE TITLE
No online API docs

### ISSUE THREAD

**Issue by no-blockers** [facebook/prophet#1263]
I'm using the python version of Prophet. While I know I can view the documentation of each function by running help(mod), I can not find any detailed HTML API docs online.
Can anyone point me to if there is something there? If there isn't anything existing, wouldn't it be better if we create one? So that the docs can be well-formatted, anchored and linked.

**Comment by hardikudeshi** [comment]
You can refer to the documentation in the link below.
https://facebook.github.io/prophet/docs/quick_start.html

**Comment by sndrtj** [comment]
That is unfortunately not detailed API documentation.

**Comment by benmwhite** [comment]
@hardikudeshi They're looking for the Python equivalent for something like [the R package docs](https://cran.r-project.org/web/packages/prophet/prophet.pdf), with the details of all the functions/objects (like full lists of function arguments and descriptions of output for instance). The github.io docs are more like example vignettes.

**Comment by bletham** [comment]
Yes this would be nice. R automatically generates a nice API reference manual that @benmwhite links to. There are tools like sphinx that can generate a reference manual for Python code but it requires a lot of configuration. We have been careful to keep a consistent schema for the python docstrings with the intent of ultimately being able to automatically generate an API manual, but the tooling is just not nearly as nice as that with R. Last year I spent a morning unsuccessfully trying to get Sphinx to generate a pdf API manual for fbprophet like we have for R, and then moved on to other issues. If anyone has experience with setting up automatic API documentation, help would be great here :-)

**Comment by bletham** [comment]
There is an issue in #619 to have a Py reference manual, so I'm going to close this and redirect traffic there. Any help is appreciated :-)
