### ISSUE TITLE
Add method to store the dataframe from  plot_yearly (and other plot methods) 

### ISSUE THREAD

**Issue by angelotc** [facebook/prophet#1270]
![image](https://user-images.githubusercontent.com/26128248/71789189-f0638f80-2fee-11ea-82a8-68ac7e65a68f.png)

Currently, there is no method (that I know of) to pull the seasonal values of the dataframe that is used to plot the `plot_yearly` graph.  I was able to extract this dataframe by reverse engineering plot_yearly, but I'm not sure if there's a more elegant method of doing this. I would be happy to implement this, but I would need some sort of mentoring / guidance since I'm not really familiar with FB Prophet's development guidelines.

**Comment by angelotc** [comment]
Here's the code that I used to get the df that creates the seasonality plots.
```

def seasonality_df(m, yearly_start=0,  name='yearly'):
    from fbprophet.plot import seasonality_plot_df
    """Plot the yearly component of the forecast.
    Parameters
    ----------
    m: Prophet model.
    ax: Optional matplotlib Axes to plot on. One will be created if
        this is not provided.
    uncertainty: Optional boolean to plot uncertainty intervals, which will
        only be done if m.uncertainty_samples > 0.
    yearly_start: Optional int specifying the start day of the yearly
        seasonality plot. 0 (default) starts the year on Jan 1. 1 shifts
        by 1 day to Jan 2, and so on.
    figsize: Optional tuple width, height in inches.
    name: Name of seasonality component if previously changed from default 'yearly'.
    Returns
    -------
    a list of matplotlib artists
    """
    # Compute yearly seasonality for a Jan 1 - Dec 31 sequence of dates.
    days = (pd.date_range(start='2017-01-01', periods=365) +
            pd.Timedelta(days=yearly_start))
    df_y = seasonality_plot_df(m, days)
    seas = m.predict_seasonal_components(df_y)

    return seas

```

**Comment by bletham** [comment]
The yearly seasonality is part of the forecast dataframe that is returned by `m.predict`. For instance, if you call `m.predict()` without specifying future dates, it will just make a prediction on the history dataframe, and if you have more than a year of daily data then it will contain all of the yearly seasonality the same as its shown in the plot:
```
m = Prophet().fit(history)
fcst = m.predict()
fcst[['ds', 'yearly']].head()
```
If yearly seasonality is wanted for a different period, then you can just call predict on a different set of dates, like:
```
dates_df = pd.DataFrame({'ds': pd.date_range(start='2017-01-01', periods=365)})
fcst = m.predict(dates_df)
fcst[['ds', 'yearly']].head()
```
All of the other seasonal components are available in fcst as well. Does that provide what you're looking for?
