### ISSUE TITLE
OutOfBoundsDatetime for make_future_dataframe(periods=5000, freq='D')

### ISSUE THREAD

**Issue by BhushanKathar** [facebook/prophet#1271]
I am getting "OutOfBoundsDatetime: Cannot generate range with start=8852025600000000000 and periods=5001" exception when trying to generate future data frame. last date or max history date of my file is '7/6/2250'

**Comment by bhushan13** [comment]
after doing some research it seems that this is occurring because  Prophet : make_future_dataframe is using pandas date_range function which is unable to generate date range for given date ('7/6/2250') and period (5000 days) if it crosses Timestamp.max

**Comment by bletham** [comment]
Well that's good to know!
I don't expect many people will need to forecast past 2250 (not for another couple hundred years anyway!), so I'm inclined to leave this as-is. The workaround is to just manually construct the future dataframe instead of using `make_future_dataframe`.
