### ISSUE TITLE
How to save prophet model???

### ISSUE THREAD

**Issue by LVQAQ-cd** [facebook/prophet#1277]
I have many clients and i have to predict their sales in 7 days. How to save my prophet model for everyone? If it must to calculate model each times, it will be too troublesome.

**Comment by bletham** [comment]
In Python you can pickle the model object, and in R you can use RDS format. There are some code examples here: https://github.com/facebook/prophet/issues/521#issuecomment-389635684

**Comment by LVQAQ-cd** [comment]
@bletham thanks, that a good way.
