### ISSUE TITLE
Date of process in Prophet

### ISSUE THREAD

**Issue by johnnykahits** [facebook/prophet#1278]
Is it possible to get the date you are running the model in Prophet as an output?

**Comment by bletham** [comment]
This isn't stored anywhere. But I think you could find ways to store it depending on what you mean by wanting it as an output. You could save it as an attribute on the model object (if you're planning to save/reload the model object and want to be able to check when it was originally fit). Or you could add it as a column to the forecast dataframe, if that is what you will save/load and you want to see what date the predictions were originally made.
