### ISSUE TITLE
Parallel sampling

### ISSUE THREAD

**Issue by mthmtc** [facebook/prophet#1279]
hello
how can i disable pystan multoprocessing for sampling (and all multiprocssing/multithreading in fbprophet)?
i need it because i make forecasts for a lot of series in a lot of processes. now sampling falls with error:
`  File "//anaconda2/lib/python2.7/site-packages/fbprophet/forecaster.py", line 1116, in fit
    stan_fit = model.sampling(**args)
  File "//anaconda2/lib/python2.7/site-packages/pystan/model.py", line 778, in sampling
    ret_and_samples = _map_parallel(call_sampler_star, call_sampler_args, n_jobs)
  File "//anaconda2/lib/python2.7/site-packages/pystan/model.py", line 87, in _map_parallel
    pool.close()
UnboundLocalError: local variable 'pool' referenced before assignment`

**Comment by bletham** [comment]
For MCMC sampling, fbprophet will ultimately call `pystan.StanModel.sampling`:
https://github.com/facebook/prophet/blob/0a270b4a19cafb084e5ed6ee0cf942198d4c913b/python/fbprophet/forecaster.py#L1133

One of the arguments to this function is `n_jobs`, which if you look at the docstring for `pystan.StanModel.sampling` it says:

> n_jobs : int, optional
    Sample in parallel. If -1 all CPUs are used. If 1, no parallel
    computing code is used at all, which is useful for debugging.

Any additional kwargs to `m.fit()` are passed along directly to pystan, so you just need to do this:
```
m.fit(df, n_jobs=1)
```

**Comment by rajnish-garg** [comment]
Hi @bletham thanks for explaining this. I have tried passing `n_jobs` but it didn't work. 

In the Pystan Optimize function there is condition that checks the valids args: https://github.com/stan-dev/pystan/blob/readthedocs/pystan/model.py#L568

**Comment by rajnish-garg** [comment]
Hi @bletham, parameter n_jobs is throwing exception because it is not part of valid args for fit function https://github.com/stan-dev/pystan/blob/develop/pystan/model.py#L568

Is there any other recommended way to stop all the multiprocssing/multithreading in the execution. We are running it in pyspark shared yarn cluster and it is impacting other jobs.

@mthmtc did u able to solve this problem ?

**Comment by bletham** [comment]
I'm guessing that you didn't turn on MCMC if you're getting an error from pystan optimizing. This works:
```
from fbprophet import Prophet
import pandas as pd
import numpy as np

df = pd.DataFrame({'ds': pd.date_range(start='2017-01-01', freq='D', periods=100), 'y': np.arange(100)})

m = Prophet(mcmc_samples=500)

m.fit(df, chains=6, n_jobs=6)
```

**Comment by rajnish-garg** [comment]
Thanks @bletham, I missed this part earlier, that we don't need `Uncertainty in seasonality` so we are using it's default value `0`. 

From the other thread https://github.com/facebook/prophet/issues/1109 it looks like numpy's multithreading is causing cpu load. I will investigate that.
