### ISSUE TITLE
Extreme sensitivity to the changepoint_prior_scale parameter

### ISSUE THREAD

**Issue by FredericoCoelhoNunes** [facebook/prophet#1280]
Hello,

is it normal that the Prophet model is extremely sensitive to the changepoint_prior_scale parameter?
I have a situation where if I change this parameter from 0.01 to 0.009999999776482582 (this is a difference of around 2e-10, basically a rounding error), I get a decrease of around 2% accuracy.

I am wondering if by some bad luck I have hit some threshold at 0.01 where Prophet rounds the parameter down to zero? Otherwise I can't understand why the model should be so sensitive to this parameter.

Has anyone had a similar situation? Thanks.

**Comment by bletham** [comment]
This seems atypical to me. Is there any chance you could post the plot of the forecast (output of `m.plot`) with each of those parameter values? That might make it possible to figure out why this sharp change is happening.

**Comment by FredericoCoelhoNunes** [comment]
Hello,
thanks for the reply.

I have not been able to reproduce the 2% case, but I have simplified the problem (using my dataset and the simplest possible Prophet model) and for the same values of the parameter, I get a variation of 0.8% accuracy, which in my opinion is still significant for such a minute change.

I am not sure if the plots will help at all since they are virtually identical, but here they are:

For changepoint_prior_scale = 0.009999999776482582:
![image](https://user-images.githubusercontent.com/51457048/73734084-002cdb80-4735-11ea-8946-502db48bd23f.png)

For changepoint_prior_scale = 0.01:
![image](https://user-images.githubusercontent.com/51457048/73734174-205c9a80-4735-11ea-9d29-fe1c423e31eb.png)

What I could possibly do is upload an anonymized version of the data and the test notebook that I've used. Maybe that would be more useful? Unless this variation in accuracy is normal behavior and I'm just exaggerating.

**Comment by bletham** [comment]
There can certainly be some variation. With the okular test things look pretty reasonable here. One possibility is that in the earlier dataset the optimizer was running into issues with one of the changepoint prior scales; you might try the Newton optimizer which I have found to be a bit more robust than the default (but it's a bit slower):
```
m.fit(df, algorithm = 'Newton')
```
That might improve stability a bit but otherwise this seems inline with expectation to me.

**Comment by FredericoCoelhoNunes** [comment]
Thanks for the information Ben. Cheers
