### ISSUE TITLE
make_future_dataframe: Issue with Forward Monthly Dates

### ISSUE THREAD

**Issue by mayankgautam** [facebook/prophet#1281]
I have dataset with ds and y columns. The ds column has last day of each month as shown below:

2018-09-30
2018-10-31
2018-11-30
2018-12-31
2019-01-31
2019-02-28

When I use to extend the dataframe forward using make_future_dataframe function, I'm getting wrong dates as shown below:

2019-05-01
2019-05-31
2019-07-01
2019-07-31
2019-08-31
2019-10-01

**Comment by eromoe** [comment]
Why don't  you format ds to `2018-09` ?

**Comment by bletham** [comment]
Could you post the code that you use to get this? I'm not running into this issue with this code:
```
df = pd.DataFrame({
    'ds': ['2018-09-30', '2018-10-31', '2018-11-30', '2018-12-31', '2019-01-31', '2019-02-28'],
    'y': [1, 2, 3, 4, 5, 6],
})
m = Prophet().fit(df)
print(m.make_future_dataframe(periods=5, freq='M'))
```
This produces:
```
           ds
0  2018-09-30
1  2018-10-31
2  2018-11-30
3  2018-12-31
4  2019-01-31
5  2019-02-28
6  2019-03-31
7  2019-04-30
8  2019-05-31
9  2019-06-30
10 2019-07-31
```

**Comment by JBOE22175** [comment]
I got the same problem, but instead of using last day of month in the input dataframe I am using first day of month which seems to be the natural choice (same as in Prophet documentation for monthly data). 
```python
df1 = pd.DataFrame({
    'ds': ['2018-09-01', '2018-10-01', '2018-11-01', '2018-12-01', '2019-01-01', '2019-02-01'],
    'y': [1, 2, 3, 4, 5, 6],
})
m1 = Prophet().fit(df1)
future1 = m1.make_future_dataframe(periods=5, freq='M'))
print(future1)
```

This produces:

```
          ds
0  2018-09-01
1  2018-10-01
2  2018-11-01
3  2018-12-01
4  2019-01-01
5  2019-02-01
6  2019-02-28
7  2019-03-31
8  2019-04-30
9  2019-05-31
10 2019-06-30
```
As you can see the last historical month is 2019-02-01 and the first future month is 2019-02-28. I would expect 2019-03-01 instead. 
I created the future dataframe manually:
```
future2 = pd.DataFrame(pd.to_datetime(["2018-09","2018-10","2018-11","2018-12","2019-01","2019-02","2019-03","2019-04","2019-05","2019-06","2019-07"],format='%Y-%m'),columns=["ds"])
print(future2)
           ds
0  2018-09-01
1  2018-10-01
2  2018-11-01
3  2018-12-01
4  2019-01-01
5  2019-02-01
6  2019-03-01
7  2019-04-01
8  2019-05-01
9  2019-06-01
10 2019-07-01
```
The forecast for future1 and future 2 are different:
```
print(forecast1[['ds','yhat']].tail())
           ds       yhat
6  2019-02-28   6.870968
7  2019-03-31   7.870968
8  2019-04-30   8.838710
9  2019-05-31   9.838710
10 2019-06-30  10.806452

print(forecast2[['ds','yhat']].tail())
           ds       yhat
6  2019-03-01   6.903226
7  2019-04-01   7.903226
8  2019-05-01   8.870968
9  2019-06-01   9.870968
10 2019-07-01  10.838710
```

**Comment by bletham** [comment]
@JBOE22175 the issue you are seeing is because pandas by default does end-of-month for its monthly spacing. You use 'MS' to get start-of-month:
```
df1 = pd.DataFrame({
    'ds': ['2018-09-01', '2018-10-01', '2018-11-01', '2018-12-01', '2019-01-01', '2019-02-01'],
    'y': [1, 2, 3, 4, 5, 6],
})
m1 = Prophet().fit(df1)
future1 = m1.make_future_dataframe(periods=5, freq='MS')
print(future1)
```
gives
```
           ds
0  2018-09-01
1  2018-10-01
2  2018-11-01
3  2018-12-01
4  2019-01-01
5  2019-02-01
6  2019-03-01
7  2019-04-01
8  2019-05-01
9  2019-06-01
10 2019-07-01
```

**Comment by bletham** [comment]
These are all of the valid frequencies: https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#timeseries-offset-aliases

**Comment by evanputtosh** [comment]
12/15/2006
1/15/2007
2/15/2007
3/15/2007
4/15/2007
5/15/2007
6/15/2007
7/15/2007
8/15/2007
9/15/2007
My data is like this. I want date 15 date also. what should I do?
