### ISSUE TITLE
prophet_plot_components shows different seasonality when compared to count over weeknames('monday' to Sunday)

### ISSUE THREAD

**Issue by rajnishrajput12** [facebook/prophet#1282]
prophet_plot_components  shows seasonality high in Sunday and Saturday while when i did a group by count on my data it is showing more counts on Monday and Tuesday.

**Comment by bletham** [comment]
Do you possibly have missing data for some days? Or maybe there are holiday effects on some days that are increasing the Mon/Tue count but are not being attributed to weekly seasonality?

If you could post both the forecast plot (`m.plot()`) and the components plot (`m.plot_components()`) that would be really helpful for perhaps being able to give some idea of what is happening.

**Comment by rajnishrajput12** [comment]
Hey Bletham,

due to terrible Pystan dependency with c++ 14 compiler had to use R instead.
Yes i had some missing values in my continuous series, now the group count and the prophet_plot_components(m,forecast) looks similar after adjusting the missing values.
