### ISSUE TITLE
Parallel training of Prophet in Spark 

### ISSUE THREAD

**Issue by nigamv** [facebook/prophet#1283]
Is there a way to train multiple models of Prophet in Spark in parallel.My use case involves being able to train thousands of models in parallel.  I tried running the models inside a UDF using spark sql but it seems that during training only one executor is used. As a result of which it is taking a lot of time to run the training process. 

Has anyone been able to run the training part of Prophet in parallel ?

**Comment by elamm43** [comment]
Yes! I have done this. It involved grouping the data by each model and converting to an RDD (which can handle python objects such as the pandas data frames that prophet requires).

I modified the code from here:
https://github.com/asidlo/sparkprophet/blob/master/sparkprophet.py

**Comment by nigamv** [comment]
@elamm43 Yes, i have also picked the code from same source and used UDF to try to parallelize it. Can you share a sample code if possible for the modification you did to run it in parallel on cluster. For me, it is being able to utilize only one cluster.

**Comment by elamm43** [comment]
It sounds like you need to check your spark context or repartition your data. Put in the usual code/spark builder that you use to run on more than one executor.

**Comment by nescobar** [comment]
This article just came out yesterday [https://databricks.com/blog/2020/01/27/time-series-forecasting-prophet-spark.html](url)

**Comment by rajnish-garg** [comment]
@elamm43 we are running fbprophet on pyspark, but it exhausting cpu on the cluster. Have u seen similar issues when running pyspark job on shared env. 

Is there any multithreading being used in training and predicting (I am not doing mcmc sampling ) ?
