### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in C:\Users\insrik00\AppData\Local\Temp\pip-install-07w58xhm\fiona\

### ISSUE THREAD

**Issue by krishnakanth95** [facebook/prophet#1288]
HI I tried to install geopandas

I got the error
Command "python setup.py egg_info" failed with error code 1 in C:\Users\insrik00\AppData\Local\Temp\pip-install-07w58xhm\fiona\

I updated my setup tools but not worked
I tried to use sudo pip install geopandas but not worked

**Comment by bletham** [comment]
This repository is for a different package.
