### ISSUE TITLE
How to exclude weekends ( saturday & Sundays) from fb Prophet

### ISSUE THREAD

**Issue by obaidM** [facebook/prophet#1291]
Hello FB Prophet community, 

I am getting outrageous predictions on Saturday and Sunday.Mainly because they shouldn't be there. 
How can I remove weekends from the daily data to begin with. 

So that my input data never has a weekend and my predictions never have a weekend.

**Comment by bletham** [comment]
The model won't have any issues if you remove the weekend days prior to passing in the data, and you'll just want to be sure that the dataframe of future dates that you pass into `predict` also has weekend days stripped out. It's pretty easy to identify weekend days in a dataframe and just drop them; here is how you would do it in pandas, and similar commands exist in R:
```
df_no_weekdays = df[df['ds'].dt.dayofweek < 5]
```
Run that command on the history before passing it into `fit`, and on the future dates before passing it into `predict`.

**Comment by mat178** [comment]
@bletham
If I remove weekend days before fitting and predicting should I keep the default weekly seasonality or should I disable it and add a custom seasonality with period=5?
Thx for the advice.

**Comment by onlykimu** [comment]
what is the code for R

**Comment by asthaarora95** [comment]
> The model won't have any issues if you remove the weekend days prior to passing in the data, and you'll just want to be sure that the dataframe of future dates that you pass into `predict` also has weekend days stripped out. It's pretty easy to identify weekend days in a dataframe and just drop them; here is how you would do it in pandas, and similar commands exist in R:
> 
> ```
> df_no_weekdays = df[df['ds'].dt.dayofweek < 5]
> ```
> 
> Run that command on the history before passing it into `fit`, and on the future dates before passing it into `predict`.

Hi, I have tried to remove the weekends from future period dataframe, but in the seasonality graph I am still seeing very high values on weekends. I am trying to predict stock prices for a particular firm and the stock market is closed on weekends. Can you help me on that?
