### ISSUE TITLE
AttributeError: 'Prophet' object has no attribute 'plot_yearly'

### ISSUE THREAD

**Issue by Manolo1182** [facebook/prophet#1303]
Hi, I am trying to plot  using fbprophet and I keep gettiong this error when trying to peplicate WillKoehrsen/ Data-Analysis https://github.com/WillKoehrsen/DataAnalysis/tree/master/additive_models
'''
gm_prophet.plot_yearly(); plt.title('GM Yearly Component of Market Cap');
Traceback (most recent call last):

  File "<ipython-input-13-e9bc61cf285b>", line 1, in <module>
    gm_prophet.plot_yearly(); plt.title('GM Yearly Component of Market Cap');

AttributeError: 'Prophet' object has no attribute 'plot_yearly'
'''

Does anyone knows if the attribute was deprecated or replaced?

Thanks in advance!

**Comment by bletham** [comment]
Yes, that attribute was deprecated a couple versions again. It is now available in `fbprophet.plot`:
https://github.com/facebook/prophet/blob/6070b5a3092a6408a6130f3e74f589a6c3dc7460/python/fbprophet/plot.py#L308-L327

So you can do
```
from fbprophet.plot import plot_yearly
plot_yearly(gm_prophet)
```

**Comment by Manolo1182** [comment]
Thank you, It worked great!
