### ISSUE TITLE
Is Prophet some kind of Machine Learning algorithm?

### ISSUE THREAD

**Issue by maxwell873** [facebook/prophet#1307]
Hello everyone,

can anyone answer this question in the title? Is prophet some kind of Machine Learning algorithm? I am not an expert in modern forecasting algorithm and the field of Machine Learning but i would be really happy if anyone could answer this question or can give some opinions and reasons why Prophet is or is not a Machine Learning algorithm.

Thank you in advance!

**Comment by bletham** [comment]
In the generic sense of using data to fit a model and make predictions, then I'd say that Prophet is a type of machine learning algorithm. Especially if you consider regularized regression like elastic net to be machine learning. But I'm not sure ML has a very precise definition, see also #583.

**Comment by hershaw** [comment]
prophet is indeed machine learning. on its own it is an algorithm that generates no value. combine it with data and you have something that can predict the future.

I think it would pass all reasonable definitions of ML that you could come up with. Right alongside a linear regression.

Also: not sure if this is a relevant forum for the question. Probably something like the [stats stackexchange](https://stats.stackexchange.com/) would be a better place to ask.
