### ISSUE TITLE
explanation of seasonality calculation in prophet model

### ISSUE THREAD

**Issue by rajnishrajput12** [facebook/prophet#1313]
I was trying to see how the weekly seasonality graph is getting calculated in prophet_plot_components(m, forecast).

1. i saved the data to csv format. write.csv(forecast,'forecast.csv').
2. after reading the data and grouping the dayName column like .
forecast['dayName'] = forecast['ds'].map(lambda x:x.strftime('%B'))
forecast[forecast['year']=='2019'].groupby('dayName').agg('sum')['weekly']
the y axis value of day(monday-sunday) in group by is not matching to the y axis value of the prophet_plot_components(m, forecast).

**Comment by bletham** [comment]
The way it works is it makes a prediction on a 1 week period of dates (specifically, the 1 week starting from 2017-01-01) and then extracts the seasonality columns from that prediction. It happens here:
https://github.com/facebook/prophet/blob/496facb152ab2c4e59dfe4edb3df6390fdadaa6a/python/fbprophet/plot.py#L286-L290

This is different than the code you provided in that it's not a sum. It also might be different if the time series does not have exactly daily frequency (missing days or multiple observations per day would mess it up).

**Comment by rajnishrajput12** [comment]
hmmm. but if you see "forecast" dataframe(which facebook used to explain prophet).
we have values only till 2017-01-19 then does it make sense to show till 2017-12-31 in yearly plot.

**Comment by bletham** [comment]
I don't understand the issue. The yearly seasonality is the same for every year. For the components plot it evaluates the seasonality on 2017 for the purposes of plotting it, but it would be the same no matter what year you evaluated seasonality on, and does not matter whether or not you have data in the history for 2017. For instance if all of the data in your history is in 2019, then if you were to evaluate the yearly seasonality in 2019, it would be the same as if you were to do it in 2017, or any other year.

**Comment by rajnishrajput12** [comment]
Thanks Bletham.

i was confused because of this line from https://facebook.github.io/prophet/docs/quick_start.html
You can use the prophet_plot_components function to see the **"forecast "**broken down into trend, weekly seasonality, and yearly seasonality.
so i thought the it only gives me the trend of forecast..
