### ISSUE TITLE
Forecast multiple features in single model

### ISSUE THREAD

**Issue by ManikandanThangavelu** [facebook/prophet#1314]
I have a use case where I need to forecast multiple metrics of a server like, CPU, memory, disk usage, etc. for 100s of servers. I don't want to create a model for each server and metric. Is there a way to do any one of the below options.

1.  predict all the features of a server in a single model.
2.  Predict a metric for all the servers in a single model. In which case there might be duplicate entry for a particular time.

Thank you.

**Comment by bletham** [comment]
There isn't any functionality for jointly forecasting multiple time series. There's some discussion of this in #49.
