### ISSUE TITLE
Saving model vs Fit while predicting

### ISSUE THREAD

**Issue by ManikandanThangavelu** [facebook/prophet#1315]
I have a use case where i will have stream of data coming in for prediction. What is advised, 

1. Saving the trained model, load, predict and retrain after an interval
2. Fit the model every time a data comes and predict.

Thank you!

**Comment by bletham** [comment]
I suppose it depends on how much computation you're willing to spend re-fitting. Re-fitting will make the model more accurate, but possibly only a little (if there are already many data points, 1 more might not impact the forecast much) and it will obviously require a lot of computation if new data are coming in at high frequency. I would generally favor retraining after some interval as a useful way of adapting a batch training method (like Prophet) to an online setting.
