### ISSUE TITLE
python - Hourly Forecasting 

### ISSUE THREAD

**Issue by sachi-code** [facebook/prophet#1322]
we can do hourly forecasting using prophet library ?

**Comment by hmfaysal** [comment]
Yes, its possible.

`ds` field should be in `YYYY-MM-DD HH:00:00` format.

Then in future frame add hourly frequency  `m.make_future_dataframe(periods=300, freq='H')`

For 7 days worth of hourly forecast use
`m.make_future_dataframe(periods=168, freq='H')`

**Comment by bletham** [comment]
There's also an example in https://facebook.github.io/prophet/docs/non-daily_data.html#sub-daily-data
