### ISSUE TITLE
Weekly/Monthly data Yearly Seasonality=True

### ISSUE THREAD

**Issue by bhavinn** [facebook/prophet#1323]
Hi,

_**Question Type 1:**_
If I am having weekly data say, 01-01-2018 , 08-01-2018, 15-01-2018, 22-01-2018.... 29-10-2019 approx 96 weeks. Can we fix yearly.seasonality =True? (If I have yearly seasonality)
Similarly for monthly data say for 3.5 years, can we fix  yearly.seasonality =True?  (If I have yearly seasonality)
Similarly for sub daily data(hours,mins,secs) say for 3.5 years, can we fix  yearly.seasonality =True, daily.seasonality=True,weekly.seasonality=True? In case I have all  3 types of seasonality.

**_Question Type 2:_**
Lets say, for weekly data if ds column has dates 01-01-2018 , 08-01-2018, 15-01-2018, 22-01-2018.... 29-10-2019., and I fix yearly seasonality=True, How does prophet works? Does it look at date values and automatically identifies first 52 data points as 1st year, next 52 data points as 2nd year and so on?

Similarly lets say, for monthly data if ds column has dates 01-01-2018 , 01-02-2018, 01-03-2018... 01-12-2018, 01-01-2019... 01-11-2019 and I fix yearly seasonality=True, How does prophet works? Does it looks at date values and automatically identifies first 12 data points as 1st year, next 11 data points as 2nd year and so on?

**Comment by bletham** [comment]
1. Yes, there is an example here with monthly data that fits yearly seasonality: https://facebook.github.io/prophet/docs/non-daily_data.html#monthly-data . Yearly seasonality will be enabled by default for time series that have >=2 years of data.

2. The underlying model is continuous time. So the yearly cycle starting at 01-01-2018 will last for 365.25 days, and does not depend on how many data points there are. There is no requirement for the data points to be regularly spaced or occur at some fixed frequency.
