### ISSUE TITLE
MAP works but MCMC does not

### ISSUE THREAD

**Issue by ksvanhorn** [facebook/prophet#1325]
With the R API, when I call prophet to fit a model, everything works fine if mcmc.samples = 0 (MAP estimation), but if I set mcmc.samples = 1000 I get the following:

SAMPLING FOR MODEL 'prophet' NOW (CHAIN 1).
Chain 1: empty_nested() must be true before calling recover_memory()
[1] "Error in sampler$call_sampler(args_list[[i]]) : "             
[2] "  empty_nested() must be true before calling recover_memory()"
error occurred during calling the sampler; sampling not done
Stan model 'prophet' does not contain samples.
Error in matrix(m$params[[name]], nrow = n.iteration) : 
  'data' must be of a vector type, was 'NULL'

I'm running R version 3.4.3 on Mac OS Catalina (10.15.3). I have version 0.5 of Prophet installed.

**Comment by qwe79137** [comment]
It sames that you did not have enough data

**Comment by bletham** [comment]
@ksvanhorn this is unexpected and something seems to not be working right. Could you check if MCMC is generally working? I wonder if it could be an issue with rstan configuration (I know Catalina caused a bunch of trouble):
```
library(rstan)
model_code <- 'parameters {real y;} model {y ~ normal(0,1);}'
fit <- stan(model_code=model_code)  # this will take a minute
mean(extract(fit)$y)  # should be close to 0
```
This is the only thing I was really able to find about it: https://discourse.mc-stan.org/t/empty-nested-must-be-true-before-calling-recover-memory/7572

**Comment by CrHvG** [comment]
Not working for me
