### ISSUE TITLE
Range of changepoint prior scale

### ISSUE THREAD

**Issue by subhamkhemka** [facebook/prophet#1326]
Hi

What is the min and max limit for the changepoint prior scale parameter ?

**Comment by benmwhite** [comment]
It can be any positive number.

**Comment by ryankarlos** [comment]
Resonable/recommended ranges are discussed in this issue #1335 - will be in the docs soon

**Comment by subhamkhemka** [comment]
Thanks @benmwhite  and @ryankarlos
