### ISSUE TITLE
"Capacities must be specified" Error While Running Loop

### ISSUE THREAD

**Issue by aesler13** [facebook/prophet#1327]
Hi Everyone,

I am relatively new to coding and fbprophet. I am working on a model at work that will create forecast over different SKUs. After investigating the results of my first model, I realized that I need to add the logistic growth parameter to my model object. I have created a loop and I am receiving the following error: 

ValueError: Capacities must be supplied for logistic growth in column 'cap'

I added the 'cap' to my 'future_dates' df below in my loop, but I keep receiving this error. Can anyone help me fix my code below? I can't figure out if it is an issue in my function or loop (I'm new to coding). I would really appreciate the help!

`def get_prediction(df):
    prediction = {}
    df1= df.rename(columns={'Date': 'ds','qty_ordered': 'y', 'Final Item No': 'item', 'cap': 'cap'})
    list_items = df1.item.unique()

        for item in list_items:
            item_df = df1.loc[df1['item'] == item]
            # set the uncertainty interval to 95% (the Prophet default is 80%)
            my_model = Prophet(growth='logistic',
            daily_seasonality=False,
            weekly_seasonality=False,
            yearly_seasonality=False
            ).add_seasonality(
                name='weekly_in_season',
                period=7,
                fourier_order=3,
                condition_name='in_season'
            ).add_seasonality(
                name='weekly_off_season',
                period=7,
                fourier_order=3,
                condition_name='off_season'
            ).add_seasonality(
                name='yearly',
                period=7,
                fourier_order=20)
            my_model.fit(item_df)
            future_dates = my_model.make_future_dataframe(periods=12, freq='M')
            future_dates["in_season"] = future_dates['ds'].apply(is_season)
            future_dates["off_season"] = ~future_dates['ds'].apply(is_season)
            forecast = my_model.predict(future_dates)
            prediction[item] = forecast
        
    return prediction`

**Comment by IrinaFomina** [comment]
@aesler13 have you been able to detect what is wrong? I have the same issue

**Comment by GermanMay14** [comment]
have you been able to detect what is wrong? I have the same issue, Thank you very much in advance.
