### ISSUE TITLE
Mixed Additive and Multiplicative Model

### ISSUE THREAD

**Issue by jzicker** [facebook/prophet#1329]
I wanted to understand the model equations when you have multiplicative seasonality and additive additional regressors.  I found the base equations for additive and multiplicative.

additive: y(t) = trend(t) + seasonality(t) + beta * regressor(t)
multiplicative: y(t) = (1 + seasonality(t) + beta * regressor(t)) * trend(t)

would it be:
y(t) = (1 + seasonality(t)) * trend(t) + beta * regressor(t)

**Comment by bletham** [comment]
Yes, that is correct. The code is here:
https://github.com/facebook/prophet/blob/101dd50e3195c1875ee856cdf49ee9fcd6a87fa3/python/fbprophet/forecaster.py#L1191-L1194

Do you have a use case for this? I'd be curious to hear it. When implementing multiplicative seasonality it didn't require any additional work to make it possible to have both multiplicative and additive terms so we left that flexibility in, but I've always had a hard time imagining a scenario where one would expect a mix.

**Comment by quasistatic89** [comment]
I'm wondering if the equation should be y(t) = ( df2['trend'] + df2['additive_terms'] ) * (1 + df2['multiplicative_terms'])  ?  I'm trying to first add an additive regressor to the trend and then apply all the multiplicative terms (seasonality + regressors) to that baseline sum. Perhaps there is another way ?

**Comment by bletham** [comment]
There isn't any way right now to have multiplicative interactions between regressors like that, and I think to do so would require a bunch of changes (from the Stan code all the way up the stack).

**Comment by quasistatic89** [comment]
@bletham Is there a way to seed the model with the exact trend values for both history and future ? Or can I amplify the trend value in the forecast after a future date by say 5x ? My use case is something where the baseline demand is a step function and is kind of known.

**Comment by bletham** [comment]
@quasistatic89 not quite... you could get fairly close by doing this:
1. Remove the known trend from history data
1. Fit the model with `n_changepoints = 0`. This will make the fitted trend be purely linear. What you'd really want is a constant trend, but linear trend is the closest you can get for now (#614).
1. Add the known trend to the forecast y_hat.

This would be using the known trend, subject to whatever linear trend might still remain after step 1.

**Comment by quasistatic89** [comment]
Thats interesting. But I'd still want the multiplicative regressors to apply on the real known trend. So removing the known trend from history won't allow the model to fit properly, I guess.

**Comment by bletham** [comment]
Ahh, yes, with multiplicative seasonality that is true, this wouldn't work. That would require entirely replacing the trend in the Stan model, and there really isn't a clear way to do that unfortunately (#705 is related).
