### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 

### ISSUE THREAD

**Issue by ballerdre11** [facebook/prophet#1337]
Command "python setup.py egg_info" failed with error code 1 in C:\Users\DDW\AppData\Local\Temp\pip-inst
all-fbnhmzld\psycopg2\

I tried pip install --upgrade setuptools and still getting the same error.
using windows 10
python 3.8
pip v20

Thanks in advance for any suggestions

**Comment by bletham** [comment]
This issue tracker is for a different package, you might try https://github.com/psycopg/psycopg2
