### ISSUE TITLE
pip install fbprophet is not installing upto the latest commit

### ISSUE THREAD

**Issue by Archan1394** [facebook/prophet#1339]
Trying to install fbprophet for Python.
It is not installing upto the latest commit.
Any suggestions on how it should be done?

**Comment by sarikayamerts** [comment]
make sure your python version is >= 3.5, https://github.com/facebook/prophet/blob/master/python/setup.py#L30 is not valid for python 2
https://docs.python.org/3/library/typing.html

**Comment by Archan1394** [comment]
thanks!

**Comment by harupy** [comment]
Does this mean `fbprophet` no longer supports Python 2?
