### ISSUE TITLE
weekly cross validation with fbprophet

### ISSUE THREAD

**Issue by EfeOg** [facebook/prophet#1344]
Hi there, I have weekly data that i am trying to cross validate with fb prophet. I know usually the input into the cross validation function is supposed to be daily(or shorter) but i was wondering if i can do a weekly cross validation? 

cross_validation(prophet, horizon= pd.to_timedelta(2,unit="W"))

**Comment by bletham** [comment]
Yes, the horizon is converted to a pd.Timedelta under the hood:
https://github.com/facebook/prophet/blob/46e56119835f851714d22b285d2e4081853b9fb1/python/fbprophet/diagnostics.py#L85
so you just have to use a string that works for pd.Timedelta. This works: `horizon='2 W'`, which you can see by looking at `pd.Timedelta('2 W')`.

Of course, `'14 days'` is equivalent.
