### ISSUE TITLE
Allow specifying custom cutoff dates in cross validation

### ISSUE THREAD

**Issue by bletham** [facebook/prophet#1351]
Currently cutoff dates for cross validation are computed based on the `period`, `initial`, and `horizon` parameters here:
https://github.com/facebook/prophet/blob/master/python/fbprophet/diagnostics.py#L19
https://github.com/facebook/prophet/blob/master/R/R/diagnostics.R#L20

These parameters have to be valid Timedeltas (Py) or difftimes (R), which means they can't be things like "1 month" whose definition varies with time.

This can produce not-ideal cutoffs for cases like monthly data, where the spacing between data points varies (#586, #1253). In this case, it'd be great to be able to directly specify the cutoff dates as an alternative input to the `cross_validation` function.

**Comment by ryankarlos** [comment]
Can submit PR for this once #1356 is in

**Comment by MarcoFusi** [comment]
Hi @bletham, I agree on the issue but why would you want to be able to directly specify the cutoff dates? In case of multiple items to forecast it becames quite difficult for the user to specify custom cutoff dates for every item. Is possibile, in your opinion, to automatically adjust the cutoff dates to be somehow related to the samplig frequency of the data?

For example, if weekly data, the horizon on the performance matrix should be "1st week", "2nd week", ...; Again, if monthly data, the horizon in the performance matrix should be "1st month" "2nd month", ... 

Alternativly, could we simply adjust the cutoff dates as follows?
- if daily data compute the cutoff dates as-is
- if weekly data then adjust cutoff dates to be the Sunday of the week
- if monthly data then adjust cutoff dates to be the first day of the month
- ...

I think this is the line of code that I would like to edit.

https://github.com/facebook/prophet/blob/46e56119835f851714d22b285d2e4081853b9fb1/python/fbprophet/diagnostics.py#L251

**Comment by bletham** [comment]
This is done for Py in #1402, so that PR just needs to be translated into R
