### ISSUE TITLE
Period of monthly seasonality and the number of days in each month

### ISSUE THREAD

**Issue by GretaShi3084** [facebook/prophet#1372]
Hello-
Thanks a lot for developing Prophet! it is really promising.
Currently I am forecasting the number of calls for the call center of a bank. My data is organized by day. It has weekly seasonality as well as monthly seasonality - as more people will make the calls at the beginning and end of each month (especially the last day and the first day of a month) because they usually receive their bills at that time.
To deal with it, I add monthly seasonality to my model with period = 30.5, fourier_order = 3. The monthly seasonality chart from component plot looks good and is shown as below.
![image](https://user-images.githubusercontent.com/59681277/75659753-77f31500-5ca5-11ea-8dc4-7c195a25074b.png)
However, i find a problem: **since the numbers of days in each month aren't fixed, the monthly seasonality shifts from 1st to 3rd or 4th gradually in the dataset.** This situation is extremely serious in Feb. because Feb only has 28 or 29 days, the monthly seasonality of Mar moves forward - the spike doesn't show around 1st, but around 5th as the chart below.
![image](https://user-images.githubusercontent.com/59681277/75660490-d53b9600-5ca6-11ea-85d4-41a9ac5b4bde.png)
Any idea about how to solve it? I try to change the period of my monthly seasonality to 30 or 30.25, but the seasonality it finds become really weird.
Thank you in advance!

**Comment by benmwhite** [comment]
What does it look like if you add those last/first days of each month as [holiday effects instead of seasonal effects](https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#modeling-holidays-and-special-events)?

**Comment by GretaShi3084** [comment]
@benmwhite Thank you for your kind reply! I will give it a try and post the result later. Appreciate your help!!

**Comment by GretaShi3084** [comment]
Adding flags for these begin days and end days work well and it can achieve better performance than using monthly seasonality even for those normal months. It is like adding dummy variable seasonalities.
