### ISSUE TITLE
Raises an error for object creation

### ISSUE THREAD

**Issue by TejasBajania** [facebook/prophet#1374]
`from fbprophet import Prophet
import plotly
import pandas as pd

pro = Prophet() `
Raises an error
`AttributeError: 'Prophet' object has no attribute 'stan_backend'`

**Comment by CalinGheorghiu** [comment]
Hi! 
Was this solved? I have the same error.
Thank you!

**Comment by TejasBajania** [comment]
Yes. Here we actually need to check the executables path for your python environment. Changing that to current working environment will work.

**Comment by swang2016** [comment]
@TejasBajania Can you provide an example of how you did that? I'm getting the same error.

**Comment by CalinGheorghiu** [comment]
I'm interested in that as well. The only workaround I found was installing it on R, but would be really helpful if it'd work with Python as well

**Comment by jeanru** [comment]
I have the same issue when I use fbprophet.

**Comment by rashmikamath** [comment]
I am also facing the same issue.

**Comment by TejasBajania** [comment]
You need to check the python executable path if it is a windows machine by:
`import sys`
`sys.executables`
will return the executable path. If there is a change in the Anaconda environment, then there is the issue. You need to change the environment to present working environment. One solution can be:
`sys.path`
should return the paths for the site packages
`sys.path.append('path-to-site-packages-for-current-working-environment')`
- Also reinstalling prophet can also solve this issue. Because instead of setting the executable path I recommend re-installing prophet.

**Comment by TejasBajania** [comment]
You need to check the python executable path if it is a windows machine by:
`import sys`
`sys.executables`
will return the executable path. If there is a change in the Anaconda environment, then there is the issue. You need to change the environment to present working environment. One solution can be:
`sys.path`
should return the paths for the site packages
`sys.path.append('path-to-site-packages-for-current-working-environment')`
will append the required path to the systems path. 

- This is the temporary solution,reinstalling prophet can also solve this issue. Instead of setting the executable path I recommend re-installing prophet.

**Comment by jaydelatorred** [comment]
Still facing same issue, error "AttributeError: 'Prophet' object has no attribute 'stan_backend'", fbprophet 0.6 version, sys.path pointing to correct env on conda, any help?
