### ISSUE TITLE
Predicting seasonal data with truncated dataframe

### ISSUE THREAD

**Issue by NikkiDakota86** [facebook/prophet#1376]
As an academic exercise, say I have data that is collected on a daily basis say over 10 years and if I'm interested in a short term forecast (say a week). The data exhibits clear yearly seasonality. Wouldn't it make sense if one includes windows of historical data around the time of interest, say a couple of months prior, and get rid of the rest and train on this subset of data for predictions? Say I want to predict in June, one would include say from March till June of historical data. Especially since Prophet is a GAM, it looks more like a curve fitting where local support is all that should matter?

**Comment by benmwhite** [comment]
Off the top of my head you'd be missing potentially valuable trend estimates (like big shifts at changepoints for instance). Ex: we want to predict sales in the first week of March, and a noticeable and steady sales growth kicked in starting last October. If I was only using January and February data to make the prediction then I'm not incorporating the known trend information, and I might end up underestimating the true sales for the first week of March.
