### ISSUE TITLE
Call to prophet causes CNET pop up

### ISSUE THREAD

**Issue by sbaumbaugh** [facebook/prophet#1378]
I am quite new please forgive me, but after 0.6 prophet update from 0.5, R MacOS Catalina. A call to prophet returns 
this screenshot. Pop up type warning that I must install build tools.
I tick no and it returns error with no call to prophet.

Any help whatsoever would be immensely helpful as I finalize a presentation.

Thank you.
![F623F506-F69A-49A9-82BC-3DCBC6AA3614](https://user-images.githubusercontent.com/60758737/75991660-646dc700-5ebc-11ea-9287-ddc3dcc03073.jpeg)

**Comment by benmwhite** [comment]
If you're building the package from source then it will need the build tools though. Why wouldn't you click "yes" in this case?

**Comment by sbaumbaugh** [comment]
Thank you so much for the response Sir.
I have clicked Yes and it returns the CNET website page.

**Comment by bletham** [comment]
Like it says you'll need R build tools to install from source. I'm not sure how CNET got themselves involved here, but you can also download them from here: https://cran.r-project.org/bin/macosx/tools/

(and you'll need to install from source because OSX binaries on CRAN are stuck at an old version ... hopefully we can figure that one out soon, #977).

The only alternative that you could consider is installing directly from github using the devtools package:
```
devtools::install_github('facebook/prophet', subdir='R')
```

**Comment by sbaumbaugh** [comment]
I appreciate that, I’d be ok if clicking yes caused the tools to load, but the CNET thing seems odd. Do you recommend a complete uninstall and then install of R and Prophet?

**Comment by bletham** [comment]
I'm not really sure where CNET is coming from, I guess that's part of rstudio? I don't think re-installing R would be necessary, you just need to install the build tools. There are some directions here on what to install to get rstan working (at which prophet would install): https://discourse.mc-stan.org/t/rstan/11723

**Comment by sbaumbaugh** [comment]
I sent Sean a screen shot of the most current error messages, but it does look like the command line xcode-select —install into terminal of RStudio may deliver some results.

But I did uninstall R, so far so good, I’ll circle back when I have a positive result.

I really can’t thank you guys enough, I run a huge sales team here in Nashville and I wish I could learn all this well enough to navigate every issue but I probably should have started 20 years ago.

Stay tuned,

Shawn B

**Comment by sbaumbaugh** [comment]
Installed tools via the terminal window of Rstudio.
Xcode-select —install 

Problem solved and works perfectly on MacOS Catalina / Prophet, v0.5 and v0.6 

![47EC26A8-B66F-4361-933C-ACE847CF17CE](https://user-images.githubusercontent.com/60758737/76135289-24593200-5feb-11ea-9548-6346e5ebf3c2.jpeg)
![2F2B3DF4-3BDF-4435-B1EA-C6FD32B98CE2](https://user-images.githubusercontent.com/60758737/76135290-24f1c880-5feb-11ea-8261-25f4dbda6edd.jpeg)
