### ISSUE TITLE
Using 'Prophet' on binary data

### ISSUE THREAD

**Issue by yairbs** [facebook/prophet#1379]
Is it possible to use 'Prophet' on time series with binary values (0/1)? Will it be able to make accurate predictions? 

I've seen that the model makes some sort of 'growth' assumption  which we can limit by 'saturation' values, but there's no explicit information about the binary case.

**Comment by bletham** [comment]
No, unfortunately it will not work with binary data. The model uses a Gaussian link function, meaning it models
```
y ~ Normal( f, sigma^2)
```
where f is the model forecast. This happens here in the code:
https://github.com/facebook/prophet/blob/708ae20c04eaf33e51819034d0b2cf6df8caf1aa/python/stan/unix/prophet.stan#L117-L122

For binary data, you would want
```
y ~ Bernoulli(f)
```
This would require a pretty significant change; it is though fairly similar to #337 so you could see the steps that I outlined there in case you wanted to give it a shot.

**Comment by jordao4242** [comment]
@bletham I installed fbProphet both on Linux and Windows, and I was not able to find the file you mentioned (prophet.stan). Where should I find it

**Comment by bletham** [comment]
It's here: https://github.com/facebook/prophet/blob/master/python/stan/unix/prophet.stan
On your system, it will be in the package install folder.
