### ISSUE TITLE
Large pickle sizes with v0.6

### ISSUE THREAD

**Issue by bletham** [facebook/prophet#1384]
Starting in v0.6 the StanBackend object is attached to the model as `m.stan_backend`. This causes the pickled size of the model to be huge: with the model in the quickstart example, it is 44M.

Clearing that attribute reduces the pickled size to 189K:
```
m.stan_backend = None

with open('model.pckl', 'wb') as fout:
    pickle.dump(m, fout)
```

This is related to but distinct from the pickle issues in #1361.

We really don't need `stan_backend` to be attached to the model after fitting (which is when it makes sense to pickle the model), so one option is to just wipe that attribute as the last step in `fit`. But this interacts with #482, since right now the stan fit object is being stored on the backend. So that will need to be refactored if we want to take this approach to solving the issue.

**Comment by bletham** [comment]
It'd be great to have a unit test that verifies reasonable pickle size, to avoid regressions here in the future.

**Comment by bletham** [comment]
Note that clearing this attribute as above is a workaround for this issue. `m.stan_backend` is only used during fitting, so you can still make predictions after loading the model from pickle if the attribute has been wiped.

**Comment by CCadere** [comment]
Note that you can still make predictions if you wipe m.stan_backend or serialize the model (which also wipes the Stan objects), but will not be able to use the model for Cross Validation.

**Comment by bletham** [comment]
Built-in json serialization is now pushed out in v0.7 and should be used instead of pickle as described here: https://facebook.github.io/prophet/docs/additional_topics.html#saving-models
