### ISSUE TITLE
StanModel' object has no attribute 'fit_class' with fbprophet 0.6 installed in EMR

### ISSUE THREAD

**Issue by jyi0314** [facebook/prophet#1385]
Hello,

I tried to install fbprophet==0.6 in EMR, but got "StanModel' object has no attribute 'fit_class'" errors.

EMR: r5.xlarge
Python 3.6
Libraries installed:
sudo pip-3.6 install -U pip --upgrade
sudo pip-3.6 install -U pandas
sudo pip-3.6 install -U cython
sudo pip-3.6 install -U numpy
sudo pip-3.6 install -U ephem
sudo pip-3.6 install -U fbprophet  --no-cache --no-binary :all:
sudo pip-3.6 install -U pystan --upgrade

For pystan test.
import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this will take a minute
y = model.sampling(n_jobs=1).extract()['y']
y.mean()  # should be close to 0

Importing plotly failed. Interactive plots will not work.
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_5944b02c79788fa0db5b3a93728ca2bf NOW.

Gradient evaluation took 0 seconds
1000 transitions using 10 leapfrog steps per transition would take 0 seconds.
Adjust your expectations accordingly!

Iteration:    1 / 2000 [  0%]  (Warmup)
Iteration:  200 / 2000 [ 10%]  (Warmup)
Iteration:  400 / 2000 [ 20%]  (Warmup)
Iteration:  600 / 2000 [ 30%]  (Warmup)
Iteration:  800 / 2000 [ 40%]  (Warmup)
Iteration: 1000 / 2000 [ 50%]  (Warmup)
Iteration: 1001 / 2000 [ 50%]  (Sampling)
Iteration: 1200 / 2000 [ 60%]  (Sampling)
Iteration: 1400 / 2000 [ 70%]  (Sampling)
Iteration: 1600 / 2000 [ 80%]  (Sampling)
Iteration: 1800 / 2000 [ 90%]  (Sampling)
Iteration: 2000 / 2000 [100%]  (Sampling)

 Elapsed Time: 0 seconds (Warm-up)
               0.01 seconds (Sampling)
               0.01 seconds (Total)

Gradient evaluation took 0 seconds
1000 transitions using 10 leapfrog steps per transition would take 0 seconds.
Adjust your expectations accordingly!

Iteration:    1 / 2000 [  0%]  (Warmup)
Iteration:  200 / 2000 [ 10%]  (Warmup)
Iteration:  400 / 2000 [ 20%]  (Warmup)
Iteration:  600 / 2000 [ 30%]  (Warmup)
Iteration:  800 / 2000 [ 40%]  (Warmup)
Iteration: 1000 / 2000 [ 50%]  (Warmup)
Iteration: 1001 / 2000 [ 50%]  (Sampling)
Iteration: 1200 / 2000 [ 60%]  (Sampling)
Iteration: 1400 / 2000 [ 70%]  (Sampling)
Iteration: 1600 / 2000 [ 80%]  (Sampling)
Iteration: 1800 / 2000 [ 90%]  (Sampling)
Iteration: 2000 / 2000 [100%]  (Sampling)

 Elapsed Time: 0.01 seconds (Warm-up)
               0 seconds (Sampling)
               0.01 seconds (Total)

Gradient evaluation took 0 seconds
1000 transitions using 10 leapfrog steps per transition would take 0 seconds.
Adjust your expectations accordingly!

Iteration:    1 / 2000 [  0%]  (Warmup)
Iteration:  200 / 2000 [ 10%]  (Warmup)
Iteration:  400 / 2000 [ 20%]  (Warmup)
Iteration:  600 / 2000 [ 30%]  (Warmup)
Iteration:  800 / 2000 [ 40%]  (Warmup)
Iteration: 1000 / 2000 [ 50%]  (Warmup)
Iteration: 1001 / 2000 [ 50%]  (Sampling)
Iteration: 1200 / 2000 [ 60%]  (Sampling)
Iteration: 1400 / 2000 [ 70%]  (Sampling)
Iteration: 1600 / 2000 [ 80%]  (Sampling)
Iteration: 1800 / 2000 [ 90%]  (Sampling)
Iteration: 2000 / 2000 [100%]  (Sampling)

 Elapsed Time: 0.01 seconds (Warm-up)
               0.01 seconds (Sampling)
               0.02 seconds (Total)

Gradient evaluation took 0 seconds
1000 transitions using 10 leapfrog steps per transition would take 0 seconds.
Adjust your expectations accordingly!

Iteration:    1 / 2000 [  0%]  (Warmup)
Iteration:  200 / 2000 [ 10%]  (Warmup)
Iteration:  400 / 2000 [ 20%]  (Warmup)
Iteration:  600 / 2000 [ 30%]  (Warmup)
Iteration:  800 / 2000 [ 40%]  (Warmup)
Iteration: 1000 / 2000 [ 50%]  (Warmup)
Iteration: 1001 / 2000 [ 50%]  (Sampling)
Iteration: 1200 / 2000 [ 60%]  (Sampling)
Iteration: 1400 / 2000 [ 70%]  (Sampling)
Iteration: 1600 / 2000 [ 80%]  (Sampling)
Iteration: 1800 / 2000 [ 90%]  (Sampling)
Iteration: 2000 / 2000 [100%]  (Sampling)

 Elapsed Time: 0 seconds (Warm-up)
               0.01 seconds (Sampling)
               0.01 seconds (Total)

Error message:
WARNING:pystan:numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
WARNING:pystan:Something went wrong while unpickling the StanModel. Consider recompiling.
INFO:fbprophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
Traceback (most recent call last):
  File "/mnt/tmp/spark-75de3af3-53da-41ad-91b1-1a4ba2b933e9/prophet.py", line 52, in <module>
    m.fit(pd_aggregation)
  File "/usr/local/lib/python3.6/site-packages/fbprophet/forecaster.py", line 1141, in fit
    self.params = self.stan_backend.fit(stan_init, dat, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/fbprophet/models.py", line 242, in fit
    params = self.model.optimizing(**args)
  File "/usr/local/lib64/python3.6/site-packages/pystan/model.py", line 542, in optimizing
    fit = self.fit_class(data, seed)
AttributeError: 'StanModel' object has no attribute 'fit_class'

I saw similar issues with old version of fbprophet, but am not sure if this issue is an on-going issue with the most recent version of fbprophet or this is an issue with EMR environment.

**Comment by bletham** [comment]
hm, pytsan is definitely working. The thing that jumps out at me is the `WARNING:pystan:Something went wrong while unpickling the StanModel. Consider recompiling.`. Did this environment previously have an older version of fbprophet or pystan installed on it? I've run into this particular warning in the past where upgrading pystan broke fbprophet because the fbprophet model was pickled under the older version of pystan. The solution was to remove fbprophet (and make sure that the pickled model was removed) and re-install.

But if this is a totally clean environment then it'd have to be something else.

**Comment by jyi0314** [comment]
@bletham This is a totally clean environment since I launched a new EMR cluster in AWS and installed the packages on it. But, I can uninstall pystan, pandas, numpy and fbprophet before starting to install them. I'll add how it goes.

**Comment by jyi0314** [comment]
I've got the same result although I ran uninstallation commend lines before starting to install.


sudo pip-3.6 uninstall -y pandas
sudo pip-3.6 uninstall -y numpy
sudo pip-3.6 uninstall -y pystan
sudo pip-3.6 uninstall -y fbprophet

sudo pip-3.6 install -U pandas
sudo pip-3.6 install -U cython
sudo pip-3.6 install -U numpy
sudo pip-3.6 install -U ephem
sudo pip-3.6 install -U fbprophet --no-cache --no-binary :all:
sudo pip-3.6 install -U pystan --no-cache --no-binary :all:


`m.fit(pd_aggregation)
WARNING:pystan:numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
WARNING:pystan:Something went wrong while unpickling the StanModel. Consider recompiling.
INFO:fbprophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
Traceback (most recent call last):
  File "/mnt/tmp/spark-1f21e8e2-1dbc-4c10-a715-5625dd3dc0ed/metrics_collector.py", line 52, in <module>
    m.fit(pd_aggregation)
  File "/usr/local/lib/python3.6/site-packages/fbprophet/forecaster.py", line 1141, in fit
    self.params = self.stan_backend.fit(stan_init, dat, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/fbprophet/models.py", line 242, in fit
    params = self.model.optimizing(**args)
  File "/usr/local/lib64/python3.6/site-packages/pystan/model.py", line 542, in optimizing
    fit = self.fit_class(data, seed)
AttributeError: 'StanModel' object has no attribute 'fit_class'
`

Anything else I can try out?

**Comment by bletham** [comment]
I'm really unsure of what's happening here. Here is what you could try:

- Determine the install location that is being used
```
# In Python
import fbprophet
print(fbprophet.__file__)
# e.g., /usr/local/lib/python3.7/site-packages/fbprophet-0.6-py3.7.egg/fbprophet/
```
- Go to that directory, and then enter the `stan_model` subdirectory. E.g. for me it is `/usr/local/lib/python3.7/site-packages/fbprophet-0.6-py3.7.egg/fbprophet/stan_model/`

- You should see a file `prophet_model.pkl`. Is it there? If not that would be a problem.

- If it is, try to unpickle it and see what error it produces:
```
# In python
import pickle
with open('prophet_model.pkl', 'rb') as fin:
    model_binary = pickle.load(fin)
```

- Check what version of pystan the pickle was produced under
```
# In bash,
strings prophet_model.pkl | grep "Stan version"
# I get, // Code generated by Stan version 2.19.1
```
and make sure that matches that being used in python
```
# In Python
import pystan
print(pystan.__version__)
```

**Comment by mrietveld-leap** [comment]
So, what's going on here -- in my experience (march, 2020, emr 5.29) -- is that somehow, **after** the bootstrap, numpy 1.14.15 is being installed on the EMR ec2 instances. 

This is from my spark job log: 

```
[2020-03-24 19:24:59,956] [INFO] __main__: = numpy                         : 1.14.5      at [/usr/local/lib/python3.6/site-packages]
...
[2020-03-24 19:24:59,956] [INFO] __main__: = numpy                         : 1.18.1      at [/usr/local/lib64/python3.6/site-packages]
[2020-03-24 19:24:59,956] [INFO] __main__: = numpy                         : 1.14.5      at [/usr/local/lib64/python3.6/site-packages]
```

The above is generated by the following python code: 

```python
    distros = pkg_resources.AvailableDistributions()
    all_pkgs = {}
    job_log.info("\n")
    for key in distros:
        for dist in distros[key]:
            if dist.location not in all_pkgs:
                all_pkgs[dist.location] = []
            all_pkgs[dist.location].append(dist)
    for loc in sorted(all_pkgs):
        pkgs = all_pkgs[loc]
        for pkg in sorted(pkgs, key=lambda p: p.key):
            job_log.info(f"= {pkg.key:<30}: {pkg.version:<11} at [{loc}]")
    job_log.info("\n")
```

However, in my bootstrap script, I check to see which versions of numpy are installed, and only 1.18.1 is installed! 

At the moment, I'm going to write a UDF to fix this, which should theoretically work.

(Especially given that the UDF will be a separate process from the prophet UDF, allowing the prophet UDF to start a new python process that only includes the correct numpy version.)

**Comment by jyiatellation** [comment]
@bletham, the location of fbprophet and version of pystan looked correct, but when I tried to unpickle `prophet_model`, I got below warnings. 

```
import pickle
with open('prophet_model.pkl', 'rb') as fin:
    model_binary = pickle.load(fin)
WARNING:pystan:numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
WARNING:pystan:Something went wrong while unpickling the StanModel. Consider recompiling.
```

@mrietveld-leap Thanks for the script. I tried to remove `numpy==1.14.5` using your script but it wasn't removed although numpy==1.18.2 was installed after the numpy directories were deleted in the bash script.
```
= numpy                         : 1.18.2      at [/usr/local/lib64/python3.6/site-packages]
= numpy                         : 1.18.2      at [/usr/local/lib64/python3.6/site-packages]
= numpy                         : 1.14.5      at [/usr/local/lib64/python3.6/site-packages]
```

**Comment by bletham** [comment]
@mrietveld-leap thanks, that definitely seems like the issue based on the warning. Basically the model is being compiled and pickled under numpy 1.14.5, and then can't be unpickled in numpy 1.18.2.

Ideally you can get the install using 1.14.5, but I don't have enough experience with EMR to help with that.

If that ends up being difficult/impossible, as a workaround you could try re-compiling the model once you're set on numpy 1.18.2. This is the code that compiles and pickles the model:
https://github.com/facebook/prophet/blob/3c69ce3312fcf91d15fd7e56812aa28cabf6f9f2/python/fbprophet/models.py#L208-L215
where the model file is https://github.com/facebook/prophet/blob/master/python/stan/unix/prophet.stan , and the target_dir where the pickle is saved is that identified above.

**Comment by mrietveld-leap** [comment]
So, in the end, I had to write some fairly complicated code in order to do this automatically. The problem is the following: 

1. somehow, after the bootstrap, numpy 1.14.15 is being installed on the EMR ec2 instances.
2. Bootstrap scripts run on **all** nodes, but job flow scripts **only run on the driver/master node**. 
3. Because we're running this in an UDF, you need to fix **all** nodes. 

I resorted to a UDF to do this, which is crazy but it works. I also needed to reconfigure spark to so that the UDF would run on all of nodes (no dynamic allocation of executors, enough executors for 1 per core, etc). 

The fix, if you don't want to go this route, is to just use numpy==1.14.5, as @bletham mentions. Then the "secret" install by EMR of 1.14.5 won't get in your way.

**Comment by alfredolozano** [comment]
@nmedagoda I'm facing the same exact error, could you solve it?

**Comment by akashban812** [comment]
> @nmedagoda I'm facing the same exact error, were you able to solve it?

@alfredolozano @nmedagoda  Have you found a fix for this? I am the facing same error
