### ISSUE TITLE
cmdstanpy version 0.9.5 sampling arg name changes

### ISSUE THREAD

**Issue by mitzimorris** [facebook/prophet#1388]
Sampling argument names in CmdStanPy (and CmdStanR) which specify sampling and warmup iterations have been standardized across interfaces - https://github.com/stan-dev/cmdstanpy/issues/221.  Changes which affect fbprophet are:

- `sampling_iters` change to `iter_sampling`
- `warmup_iters` change to `iter_warmup`

**Comment by bletham** [comment]
@mitzimorris Thanks for the heads up!

This will impact us here: https://github.com/facebook/prophet/blob/d9bea6196981bfcedae40525e702d424d26e7cd0/python/fbprophet/models.py#L111

Right now on PyPI it is pinned to 0.4 (https://github.com/facebook/prophet/blob/d9bea6196981bfcedae40525e702d424d26e7cd0/python/requirements.txt#L2), so this won't break any pip installs, but we should fix to the new argument name and then advance the pin to 0.9.5.
