### ISSUE TITLE
Understanding cross validation

### ISSUE THREAD

**Issue by NikkiDakota86** [facebook/prophet#1394]
I have a very basic question. Can you please explain how cross validation or simulated historical forecasts work in Prophet? Specifically, how does it pick out-of-sample points when we already used the data and fit the model to find the parameters?

**Comment by benmwhite** [comment]
[The docs have a brief explanation and some simple examples](https://peerj.com/preprints/3190.pdf) and [section 4 of the paper (pdf](https://peerj.com/preprints/3190.pdf) has more details.
