### ISSUE TITLE
make_future_dataframe to take a date 'ds' for which you want to predict

### ISSUE THREAD

**Issue by ShwetaTurakhia** [facebook/prophet#1395]
Hi, I have a usecase where my dataframe looks like 

df = pd.DataFrame({
    'ds': ['2020-01-01','2020-01-02', '2020-01-05', '2020-01-07'],
    'y': [121, 342, 2343, 344, 235, 236],
})

todays date - 2020-01-10
m = Prophet().fit(df)
print(m.make_future_dataframe(periods=1))
Lets say I generate forecast daily, but I have some missing data for previous days and in this case it will only predict for 2020-01-08 as periods is set to 1. I can always set the periods to 7 or something but I will not know for sure which dates are missing. I was wondering if there should be a way to say

df = pd.DataFrame({
    'ds': ['2020-01-01','2020-01-02', '2020-01-05', '2020-01-07'],
    'y': [121, 342, 2343, 344, 235, 236],
})

//todays date - 2020-01-10
m = Prophet().fit(df)
print(m.make_future_dataframe(ds='2020-01-10'))

**Comment by bletham** [comment]
The `make_future_dataframe` method just creates a dataframe of dates that includes all of the history dates, and then extends out from the latest day in the history the specified number of periods. It's just a matter of convenience, you can actually specify the dates entirely manually if you'd like. For instance,
```
future = pd.DataFrame({'ds': ['2020-01-10']})
m.predict(future)
```
will work just fine. If you want to also get predictions on the history dates, you just prepend `df['ds']` to that.
