### ISSUE TITLE
One big model for multiple subjects

### ISSUE THREAD

**Issue by Hong-Revo** [facebook/prophet#1398]
Hi,

Possibly a basic question: when you have a dataset that consists of multiple subjects with one time series per subject, can you use prophet to fit one model to everything? That is, instead of fitting a separate model per subject, you fit one model with the subject label as an independent variable.

**Comment by bletham** [comment]
No, there currently isn't any functionality for multivariate time series like that, I think about the best that could be done with Prophet is fitting a separate model for each. There's some discussion of this in #49.
