### ISSUE TITLE
 pip install pyttsx3 not working .

### ISSUE THREAD

**Issue by DarkEquinox564** [facebook/prophet#1399]
` ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`
![image](https://user-images.githubusercontent.com/58512908/77032390-40d17300-69ca-11ea-83bd-ba543e4e9ea3.png)

Tried:
`pip install --upgrade setuptools`

Still not working pls help

**Comment by bletham** [comment]
This looks like it's for a different package, your best bet will be to find the github repo for that package and ask there.
