### ISSUE TITLE
R Version 0.6 kills multicore Sessions

### ISSUE THREAD

**Issue by Someone894** [facebook/prophet#1400]
Currently I'm using prophet to forecast several thousands of time series, in a `foreach dopar` fashion with underlying snow parallelisation, which in turn relays on sockets to run.

From version 0.5 to 0.6 the `compile_stan_model`-function was changed significantly. This leads to a problem with my Layout: Currently the `compile_stan_model`-function is called in every child, occupying another socket, and since there are only [125+3](https://github.com/HenrikBengtsson/Wishlist-for-R/issues/28) socket available (I use 120 Threads), my whole program collapses.

Now I'm calling  `prophet:::compile_stan_model` in my main thread, before establishing the children. But this feels rather "hacky". 

Is there a better way to deal with this issue?
Maybe create a new function like `prophet::initialize_prophet` that can be called by the user?

**Comment by bletham** [comment]
Yeah that sounds like a pain. That re-arrangement was made to satisfy some CRAN issues, but it also introduced some others, so we're working on yet another refactoring of the model building...

Previously the model was compiled during install. In v0.6, it is not. So when you call `fit`, it tries to load the compiled model, and if it isn't there, then it compiles it:
https://github.com/facebook/prophet/blob/d9bea6196981bfcedae40525e702d424d26e7cd0/R/R/prophet.R#L1231-L1235

So in this case where you are distributing the computation, you just want to make sure the model is compiled before doing so. What you are doing (calling `prophet:::compile_stan_model()` prior to spawning the child jobs) is exactly the right thing to do.

We're going to get this cleaned up better in the next version, so there will be some more changes and I apologize now for the thrash but we'll make sure this works then without requiring manually telling it to compile.

**Comment by bletham** [comment]
This was fixed in the 0.6.1 release.
