### ISSUE TITLE
Prophet leaves stderr redirected to file

### ISSUE THREAD

**Issue by ksvanhorn** [facebook/prophet#1404]
After running some R code that contained calls to `prophet`, I found that error messages were no longer printing; for example, I would enter an expression containing a nonexisting variable, and nothing would be printed. After some investigation I found that stderr was being redirected to the file

    /var/folders/rq/bwkpvgnn3_q5ylmpqwz_lr8c0000gn/T//RtmpSrj5cD/file3738587faad5

From what I can tell looking at this file, it appears that the redirection happened during the call to `prophet::prophet`, with `growth='linear'`, `uncertainty.samples` nonzero, `mcmc.samples` nonzero, `cores=4`, and `control=list(max_treedepth=15)`. There were also calls to `prophet::make_future_dataframe` and `prophet::predictive_samples`.

OS: MacOs Catalina (version 10.15.3)
R version: 3.6.2
RStudio version: 1.2.5033
Prophet version: 0.5

**Comment by ksvanhorn** [comment]
Also, I find that `sink.number()` returns 3, which is consistent with a redirect not being undone.

**Comment by ksvanhorn** [comment]
This may be a bug in rstan: see issue #751 in stan-dev/rstan.

**Comment by bletham** [comment]
Thanks, I'm glad you were able to track it down to something in rstan. I can't think of anything happen in R prophet that would change logging / message settings.
