### ISSUE TITLE
Add Regressor Weather Forecast Data

### ISSUE THREAD

**Issue by c3-VincentBrisse** [facebook/prophet#1410]
To help with forecasting water consumption, I would like to add a regressor with weather data. I have three years of data.
During cross validation, I first train on the first two years, then predict on the next two weeks, then train on the first two years plus one week, then predict on the next two weeks etc...
To avoid data leakage in validation, I should only use weather _forecast_ data, while to have a better training I should obviously use _actual_ weather data. Is there a way to implement this with prophet ?

**Comment by bletham** [comment]
This came up in a discussion a couple years ago. I made an issue for it in #442, but it isn't something that there's any real interface for. I think the best thing to do will be to write out the CV loop yourself.

Which fortunately I do not think is too difficult. This is all of the code for doing cross validation for a single cutoff:
https://github.com/facebook/prophet/blob/3c69ce3312fcf91d15fd7e56812aa28cabf6f9f2/python/fbprophet/diagnostics.py#L167-L197

Right now it is calling predict on `df[index_predicted][columns]`. And you would just need to change that to plug in the forecasted values for the regressor in the window [cutoff, cutoff + horizon].

That does CV for a single cutoff, and then you would just loop over cutoffs and concatenate all of the results.

**Comment by c3-VincentBrisse** [comment]
Thank you that answers my question !
