### ISSUE TITLE
How to get seasonally-adjusted data using prophet in R 

### ISSUE THREAD

**Issue by amurguiag** [facebook/prophet#1411]
I am aware that the package was not necessarily created to seasonally adjust data... But because it is an additive model and the predict function spits out the trend, seasonality, holiday values, etc. I was wondering if it is possible to extract all the seasonality out of the yhats. I've tired it a couple of time myself using make_all_seasonality_features to get the aggregate seasonality values but I don't seem to get the desired result.  Also related, is there a clear-cut way to extract the error term from the output dataframe of predict()? 

Any suggestions are appreciated!

**Comment by bletham** [comment]
For removing seasonality from yhat: when everything is additive, the model is
```
yhat = trend + seasonality + holidays + regressors + noise
```
where noise is mean 0. All of these components are returned in the forecast dataframe that is returned by `predict`. So if you want an estimate without any seasonality or holidays, you could do
```
fcst = m.predict(future)
yhat_deseas = fcst['trend'] + fcst['regressors']
```
Now getting uncertainty intervals for that is a bit more tricky; but if you don't do MCMC, then there is no uncertainty estimated for regressors anyway, so the uncertainty would just be that of trend plus the noise. You could also look at `m.predictive_samples`, which draws posterior samples for yhat and trend, to which you could then add whichever (not-random) components you wanted.

Which leads to your next question, of how to extract the noise from the output of predict. If you don't do MCMC, then all of the uncertainty on a past point comes from the noise. So you could look at the difference between yhat_lower and yhat_upper on a point that is in the history, and from that back out the variance of the normal whose 80% interval is that difference.

But the easier thing to do is just pull it directly from the fitted model parameters. The noise standard deviation is `m.params['sigma_obs'] * m.y_scale`.

This is where the noise is sampled in the code:
https://github.com/facebook/prophet/blob/3c69ce3312fcf91d15fd7e56812aa28cabf6f9f2/python/fbprophet/forecaster.py#L1421-L1422

**Comment by amurguiag** [comment]
Hi Ben, Thank you for your response. It was helpful but I still cannot arrive to my desired result. Basically, I am wondering if prophet has the capacity to give me a series that looks like the seasonally adjusted green line in the plot below, which is the official seasonally adjusted series for weekly initial claims from FRED.  
![fbp_compare](https://user-images.githubusercontent.com/62960637/78300959-5edcbe80-7506-11ea-89b1-1800d01dc088.png)

I followed your suggestion to generate a prophet estimate without seasonality and holidays, which is the black line in the figure above. Since I have no regressors in my prophet model, it was basically the trend from predict(). And it is not quite like the green line.  My hunch is that there is something else that should be added to the trend. Do you have an idea of what that could be? Thanks for all your help.

**Comment by bletham** [comment]
Ah, I see. The seasonality adjustment done by FRED is with an entirely different class of model (X12, according to https://www.dallasfed.org/research/basics/seasonally.aspx). X12 is an ARIMA model. I wouldn't expect it to provide similar results to Prophet in general, since it will incorporate a very different set of assumptions. So if you want to reproduce that result you'd have to use a package that includes the X12 model (there seem to be a few).

This particular time series seems a fine fit for the Prophet assumptions except for the fluctations in the magnitude of the yearly spike (Prophet assumes constant magnitude yearly seasonality). In any case the X12 de-seasonalization seems a bit wonky to me; why would it produce a large upswing in 2001-2004?...
