### ISSUE TITLE
Should "ds" be sorted (in order wrt time)?

### ISSUE THREAD

**Issue by aslanismailgit** [facebook/prophet#1412]
Hi there,
Regarding the data set: 
https://github.com/facebook/prophet/blob/master/examples/example_wp_log_R.csv
I see that the ds is not sorted wrt time. Does prophet handle this? I mean should be be in order?
Or am I missing something?
Thanks.
ismail

**Comment by bletham** [comment]
It doesn't matter since it is sorted internally prior to fitting:
https://github.com/facebook/prophet/blob/3c69ce3312fcf91d15fd7e56812aa28cabf6f9f2/python/fbprophet/forecaster.py#L298

**Comment by aslanismailgit** [comment]
Perfect!
Then, my problem is calling df.plot() before fit method. Right?
Thanks.

**Comment by bletham** [comment]
I don't see why that would necessarily be a problem, is there an error that you're getting?

**Comment by aslanismailgit** [comment]
I dont get an error. What I did is  as below. If I fit pophet model first or sort the data myself then there is no problem (of showing a later date's value before an earlier one on the plot.)  
I think it is solved for me.  Thanks. - and stay healthy- 
```
filename="/home/samsung-ub/PycharmProjects/TFDeneme/proph_data.csv"
df = pd.read_csv(filename)
dfFirstFive = df[:5].copy()
ax = plt.gca()
dfFirstFive.plot(kind='line', x='ds', y='y', ax=ax)
plt.title("Without sorting data")
plt.show()
```
![Without sorting data](https://user-images.githubusercontent.com/57701730/80467858-17035880-8947-11ea-955b-4f28bbf798d3.png)

```
ax = plt.gca()
dfFirstFiveSorted = dfFirstFive.sort_values('ds')
dfFirstFiveSorted.plot(kind='line',x='ds',y='y',ax=ax)
plt.title("After sorting data")
plt.show()
```
![After sorting data](https://user-images.githubusercontent.com/57701730/80467872-1f5b9380-8947-11ea-8d3e-ada7f1b8274e.png)

**Comment by bletham** [comment]
I'm still not exactly clear what's happening here since the output of `m.predict` will always be sorted. So if you do plotting directly from that there shouldn't be any issues with order. But if you do additional transformations then yes you may need to re-sort afterwards.
