### ISSUE TITLE
Serialize to/from json (Py)

### ISSUE THREAD

**Issue by bletham** [facebook/prophet#1415]
Right now the way to store a Prophet model in python is with pickle. This can occasionally produce issues (like #1361 and #1384), but even with workarounds for those, it's comes with other downsides like the fact that unpickling can execute arbitrary code.

The nicer approach would be to be able to serialize to and from json.

#1414 adds this, after which that would be the recommended approach for storing models, not pickle.

For convenience It is limited to fitted models; is there a scenario where one would want to store a model that hasn't yet been fit?

**Comment by bkolb249** [comment]
When will this feature be released?

**Comment by bletham** [comment]
In the next version release, which I'm aiming for the end of this month (so in 2-3 weeks).

**Comment by bletham** [comment]
This is now shipped in v0.7, and documented in https://facebook.github.io/prophet/docs/additional_topics.html#saving-models

**Comment by yfellous** [comment]
Hi Everyone ! I have this Error ? Help ?  

ModuleNotFoundError: No module named 'fbprophet.serialize'

**Comment by bletham** [comment]
@yfellous check your version of fbprophet and make sure it is 0.7.1
```
import fbprophet
print(fbprophet.__version__)
```
