### ISSUE TITLE
How does prophet process holiday effects when working with weekly data?

### ISSUE THREAD

**Issue by amurguiag** [facebook/prophet#1420]
Does prophet only assign holiday effects if the day the week ends falls on a holiday? Take Memorial Day, for instance, which is May 25 this year. If the y-value is the sum for all the days in the week from May 23-29, 2020 and the week is denoted by the end date (May 29, 2020), does prophet pick up that there was a holiday during that time frame? Or only if a holiday fell on May 29?

**Comment by bletham** [comment]
They would only be picked up if it fell on that particular date of the aggregation (in this case May 29). There is an extended discussion of this here, along with some tips of how to handle holidays with weekly data: #985

**Comment by amurguiag** [comment]
Thanks, Ben! That is good to know.
