### ISSUE TITLE
How to add second time series as feature? 

### ISSUE THREAD

**Issue by NikeNano** [facebook/prophet#1421]
Is it possible to add a second time series as a feature? For example to model electric consumption to add temperature as well? For the "future" these features will not be available so I can't include it as a regressor. 

Thanks for the help!

**Comment by benmwhite** [comment]
You can use a separate univariate time series model to predict the feature and supply those future feature values for your main prediction model.

**Comment by NikeNano** [comment]
Thanks for the advice @benmwhite!
