### ISSUE TITLE
How does automatic changepoint detection work?

### ISSUE THREAD

**Issue by rohan-gt** [facebook/prophet#1422]
So I'm aware that Prophet sets 25 equally spaced changepoints by default and detects the delta occuring at these changepoints. Out of this, only the changepoints having a delta > 0.01 (**threshold**) are selected. The piecewise linear trend model uses these selected changepoints as its breakpoints.

Couple of questions here:
1. The changepoints don't seem to lie exactly where huge deltas occur in the data. Instead their domain is limited to the 25 equally spaced points. So I'm guessing if there's a huge delta occuring between two changepoints it is not detected?
2. Does the `changepoint_prior_scale` parameter affect the number of changepoints (in which case is `n_changepoints` an optional parameter?) 
3. Does the `changepoint_prior_scale` affect the above mentioned changepoint delta **threshold**? (if not is there a way to control this threshold in order to decide on the trend component's breakpoints?)
4. If the `changepoint_prior_scale` affects the **threshold**), what is the relationship between `changepoint_prior_scale` and the threshold?

**Comment by benmwhite** [comment]
The changepoint locations are set before the model fitting, and the prior scale affects how large the estimated trend changes are at each point. If the prior scale is closer to zero then the model is more "skeptical" of estimated change and these values will be closer to zero, and if the prior scale is larger then the model will fit the training data more closely but at the risk of overfitting to noise terms. Delta is an absolute threshold applied after the fact here, so you'll end up "kicking out" more changepoints if your prior scale is closer to zero or if delta is larger (all else equal). It's recommended to tune these with time series cross validation like the implementation bundled with prophet.

See the [trend changepoint docs](https://facebook.github.io/prophet/docs/trend_changepoints.html ) for more details and examples.

**Comment by benmwhite** [comment]
>It's used for the trend model as well. I checked the source code

Oh I see what the miscommunication was. The deltas in the model code you mentioned are referring to the estimated changes in the trend slope at each changepoint, and are always fitted. You mentioned the delta threshold of 0.01 so I thought you were referring to the plotting threshold. The model never kicks out any estimated deltas/estimated slope changes as far as I know.

`n_changepoints` is used with `changepoint.range` to determine the grid of changepoint locations over which the delta values get estimated, but you can also override this by supplying your own list of changepoints manually. 

`changepoint_prior_scale` affects regularization when the deltas get estimated, with low values pushing the estimates to zero and high values allowing the closer fit to the training data. 

After the model fitting you'll have a list of changepoint times (determined by `n_changepoints` + `changepoint.range` OR by your manual list), and the estimated deltas/trend changes (affected by your prior scale), but the number of changepoints and the prior scale are independent.
