### ISSUE TITLE
AttributeError: 'DatetimeIndex' object has no attribute 'weekday_name'

### ISSUE THREAD

**Issue by tang6503659tang** [facebook/prophet#1426]
these are my code:
    m=Prophet()
    future=m.make_future_dataframe(periods=60)
    forecast=m.predict(future)
    m.plot_components(forecast) #I'd like to see the weekly effect 

but Error comes out:
    AttributeError: 'DatetimeIndex' object has no attribute 'weekday_name'
    # DatetimeIndex is pandas.DatetimeIndex

what should I do to fix this error?

**Comment by bletham** [comment]
This looks like #1304, which is an incompatability between fbprophet==0.5 and pandas>=1.0.
You can check the version of these with
```
import fbprophet
print(fbprophet.__version__)
import pandas
print(pandas.__version__)
```
The best thing to do would be to upgrade fbprophet to the latest version, which is 0.6. That will resolve this issue.

If for whatever reason that isn't possible, the only alternative would be to downgrade pandas to 0.25.3.
