### ISSUE TITLE
Ruby Library

### ISSUE THREAD

**Issue by ankane** [facebook/prophet#1430]
Hey, thanks for this awesome library! I wanted to let you know there's now a [Ruby port](https://github.com/ankane/prophet) of it. It's modeled after the Python API and supports the same functionality (besides plotly). The code was really clean and easy to follow.

If you have any feedback, let me know or feel free to create an issue on the project for it. Thanks!

**Comment by bletham** [comment]
Cool, thanks for sharing! I've never read Ruby code before, it's an interesting experience :-)

**Comment by ankane** [comment]
It was mostly:

- `self.attribute = value` to `@attribute = value`
- `def fit(self, df, **kwargs):` to `def fit(df, **kwargs)`
- `len(var)` to `var.size`
- `if condition: ...` to `if condition ... end`
- NumPy to Numo
- Pandas to Daru

It was great seeing how Prophet works - definitely impressed!
