### ISSUE TITLE
Getting the Simulated Values of 'yhat' and 'trend' which are used to calculate the Uncertainty Interval

### ISSUE THREAD

**Issue by Firrucane** [facebook/prophet#1439]
Is there any way to obtain the Simulated Trend and Yhat values ( the output of 'sample_posterior_predictive' function ) from the Prophet Model ?
I want to be able to calculate the uncertainty intervals for different 'interval_width' values in just a single run.

**Comment by ryankarlos** [comment]
You could just call the `predictive_samples` method after you have fitted the model object

m.fit(df)
## this just shows an example single date but for multiple dates just add them to the ds column
predict_date = pd.DataFrame({'ds': ['2019-10-01']})
samples = m.predictive_samples(predict_date)
`samples['trend'] `and `samples['yhat']` should contain the simulated trend and posterior predicted yhat values

By default 1000 samples are generated - to change this you would need to define it in the keyword to the Prophet constructor - 
`m = Prophet(uncertainty_samples=2000)`

**Comment by Firrucane** [comment]
Thanks Ryankarlos, that was really helpful ! 

Another doubt . Is there a better way to get the probability that a future forecast 'yhat' at time 'T' will be equal to a particular value 'X' . Right now I am checking the percentile value of 'X' in the list of uncertainty samples generated for the forecast 'yhat' at time 'T' and using that as an indicator as to how likely 'X' is to appear.

Thanks !

**Comment by ryankarlos** [comment]
@Firrucane i dont think it is possible to get a single probability for a point if it is a continuous random variable - technically the probability of yhat equalling any value is 0. However, you could compute a probability density distribution and compute the probability that yhat falls in a  finite range of values around the value you are interested in. The total probability under the density distribution  (i.e. the integral) should be 1 - so technically computing the area between two points will give you the probability of your variable falling between the range.  

Its slightly hacky but here is an example i computed from the quick start docs - for a random date in the forecast.  compute a smooth estimate of the pdf and integrate between a range - `scipy.stats` provides kernel density estimation to do this as well as integration method.

```
import scipy
m = Prophet()
m.fit(df)
future = m.make_future_dataframe(periods=365)
forecast = m.predictive_samples(future)
df_predict = pd.concat([future['ds'], pd.DataFrame(forecast['yhat'])], axis=1) 
ds = '2017-01-15'
samples_array = df_predict.set_index('ds').loc[ds, :].values
kde = scipy.stats.gaussian_kde(samples_array, bw_method=0.15)

# as a check - lets compute the total probability under the curve - this gives 1  (as expected)
np.round(kde.integrate_box_1d(min(samples_array),max(samples_array)), 2)

# compute probability that yhat is between 7.5 and 8  - this gives 0.25 
np.round(kde.integrate_box_1d(7.5,8), 2)
```
note that i've played around with the bandwith of the kernel fit by looking at how good the fit of pdf is in the plot below - the narrower it is the better fit but if you go too low then it starts fitting noise. (there are better ways of doing this if you wanted to get more technical - like `sklearn`  KernelDensity model where you can tune for bandwidth) 

```
import seaborn as sns
import matplotlib.pyplot as plt
ds = '2017-01-15'
plt.figure(figsize=(10,5))
sns.distplot(df_predict.set_index('ds').loc[ds, :], 
             norm_hist=True, color = 'darkblue', kde=False,
             hist_kws={'edgecolor':'black'})
sns.kdeplot(df_predict.set_index('ds').loc[ds, :], color="r", bw=.15) 
sns.kdeplot(df_predict.set_index('ds').loc[ds, :], color="b", bw=.25)
```
![image](https://user-images.githubusercontent.com/16509490/81758839-e0871b00-94ba-11ea-98ee-7b74e0cfae85.png)

@bletham may have better ideas though
