### ISSUE TITLE
Fbprophet Problem

### ISSUE THREAD

**Issue by Ram04420** [facebook/prophet#1443]
i was imported below library, as well as i installed all packages related to plot_plotly by using **"pip"**
i updated jupyter notebook version,  installed psuti1, and many more,
but problem is not clear.

**import plotly.graph_objs as go**

Example code:

from fbprophet.plot import plot_plotly as go
import plotly.offline as py
py.init_notebook_mode()

fig = plot_plotly(m, forecast) # This returns a plotly Figure
py.iplot(fig)

I am getting following error:

NameError Traceback (most recent call last)
in
3 py.init_notebook_mode()
4
----> 5 fig = plot_plotly(m, forecast) # This returns a plotly Figure
6 py.iplot(fig)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\fbprophet\plot.py in plot_plotly(m, fcst, uncertainty, plot_cap, trend, changepoints, changepoints_threshold, xlabel, ylabel, figsize)
560 data = []
561 # Add actual
--> 562 data.append(go.Scatter(
563 name='Actual',
564 x=m.history['ds'],

NameError: name 'go' is not defined

**Comment by bletham** [comment]
I'm not sure what's happening here. Can you try
```
import plotly.graph_objs as go
```
and see if it is successful?

One note though is that `from fbprophet.plot import plot_plotly as go` is probably a bad idea, you really just want `from fbprophet.plot import plot_plotly` , `go` comes from plotly, not fbprophet.

**Comment by Ram04420** [comment]
i got the output by below this code,
and one more thing is *m = Prophet(daily_seasonality=True)*
*Note: *While initializing  the* Prophet *class* in "m", *it was showing
Facebook prophet was disabled* daily_seasonality=True *error









*from fbprophet.plot import plot_plotly, goimport plotly.offline as
pypy.init_notebook_mode()import plotly.graph_objs as gofig = plot_plotly(m,
forecast)  # This returns a plotly Figurepy.iplot(fig)*

thanks for your responding to my *Error*



Regards
*Ramanjaneyulu*

**Comment by bletham** [comment]
Could you give the output just from
```
import plotly.graph_objs as go
```

As for the daily seasonality message: this is just a note (INFO) and not an error, you can ignore it (it just means that you have daily or higher data and so don't need to fit daily seasonality).
