### ISSUE TITLE
Can I adjust the output plot range?

### ISSUE THREAD

**Issue by HydonKim** [facebook/prophet#1444]
I predicted one month with five years of data, but the predicted area is too narrow to see. 
So I want to see only the last 1 year or the last 6 months, not 5 years. 

How Can I do so?
![plot](https://user-images.githubusercontent.com/33532542/79964186-4d635280-84c5-11ea-90bd-83d1305afbc9.png)

**Comment by bletham** [comment]
If you do
```
fig = m.plot(fcst)
```
then `fig` is a matplotlib fig object and matplotlib gives you complete control over making changes to it. For any change you want to make to a figure, just search for how to do that in matplotlib and you can almost certainly find a SO post about it. In this case, do `ax = fig.gca()` to get the matplotlib axis object, and then `ax.set_xlim([lower, upper])` to change the limit. `lower` and `upper` here would be python datetime objects with the dates you want for the lower and upper limits.
