### ISSUE TITLE
getting negative trend for icreasing time serie

### ISSUE THREAD

**Issue by romainMiralles** [facebook/prophet#1446]
Hi,

Thanks for this great tool. I have a question about the trend I am getting for my time series. For some reason it doesn't seem to make sense.(please see pictures below). I do know ow to fix it, I just need to start my time series later on when non of the uncertainty in the trend is below 0.  But I am still trying to understand why it is giving me this negative trend .

Thanks for any explanation

![Screen Shot 2020-04-23 at 10 02 39 AM](https://user-images.githubusercontent.com/54654998/80051028-b8ef0380-8549-11ea-9ff5-e46508741b00.png)
![Screen Shot 2020-04-23 at 10 02 56 AM](https://user-images.githubusercontent.com/54654998/80051034-bbe9f400-8549-11ea-8112-efc29a2eabfc.png)

**Comment by bletham** [comment]
I'm not really sure what's happening, could you post the entire components figure? And what is the time scale of this forecast? I'm wondering if there could be something messed up with yearly seasonality.

**Comment by romainMiralles** [comment]
THanks for your answer. I dig a little bit and I think I know the source (but not sure of the why)
here is a simplified version of the code after stripping out all the other parameter. It seems the issue come from the fourier order I used for added weekly seasonality. Guess I was playing with it and forgot to change back the value. Showing the plot below in case it can help others


m_prd=Prophet(growth ='linear', 
                                          seasonality_mode ='multiplicative').add_seasonality(
        name='weekly',
        period=7,
        fourier_order=50)


  
  #fit model
m_prd.fit(ds_pd.reset_index().rename(columns={'datetime':'ds', var_pred:'y'}))

  #create future dataframe
future = m_prd.make_future_dataframe(periods=10)
future['datetime']=future['ds']
  #run Prediction on future data
forecast_day = m_prd.predict(future)
forecast_day['datetime']=forecast_day['ds']


here are the plots when I use all the data
![Screen Shot 2020-04-24 at 9 30 39 AM](https://user-images.githubusercontent.com/54654998/80165665-75120200-860e-11ea-9865-0d83bf6618a0.png)
![Screen Shot 2020-04-24 at 9 30 20 AM](https://user-images.githubusercontent.com/54654998/80165668-75aa9880-860e-11ea-963e-a89c4b6105c7.png)


And now here are the plots when I only use a subset of data( basically removing early point when I get negative values for forecast)

![Screen Shot 2020-04-24 at 9 31 37 AM](https://user-images.githubusercontent.com/54654998/80165658-6deaf400-860e-11ea-8c19-2bff82047cda.png)
![Screen Shot 2020-04-24 at 9 31 28 AM](https://user-images.githubusercontent.com/54654998/80165662-73e0d500-860e-11ea-88fa-999a2249f548.png)


Now I rerun my code without my added weekly seasonnality. It seems fine


![Screen Shot 2020-04-24 at 9 35 39 AM](https://user-images.githubusercontent.com/54654998/80165850-097c6480-860f-11ea-8aee-e4ff7aceaa62.png)


![Screen Shot 2020-04-24 at 9 35 47 AM](https://user-images.githubusercontent.com/54654998/80165842-04b7b080-860f-11ea-9657-b3c040865675.png)


And finally after more testing, it seems if I decrease my fourrier order, I don't get the issue anymore

**Comment by bletham** [comment]
I see, a Fourier order of that high produces a very large amount of flexibility in the seasonality that will make it prone to overfitting, though I'm still not exactly sure what was happening here because I'd expect to see that as a bad weekly cycle. The components shown don't add up to the forecast so I'm thinking that the other parameter may be involved. In any case, glad to hear that things are more sane now!
