### ISSUE TITLE
Package ‘prophet’ was removed from the CRAN repository.

### ISSUE THREAD

**Issue by kirgush** [facebook/prophet#1448]
https://cran.r-project.org/web/packages/prophet/index.html

Package ‘prophet’ was removed from the CRAN repository.

Formerly available versions can be obtained from the archive.

Archived on 2020-04-23 as check problems were not corrected despite reminders.

Please use the canonical form https://CRAN.R-project.org/package=prophet to link to this page.

**Comment by ecs-hk** [comment]
Adding to this issue just to confirm what is reported here. Our Docker image builds (which are a custom Rserve container with the prophet package) suddenly began failing with:

> Warning message:
> package 'prophet' is not available (for R version 3.5.2)

Upon investigating I found exactly what @kirgush is describing. The CRAN repository URI states that the prophet package was removed.

**Comment by Aliceleeme** [comment]
I also want to report that when I try to install prophet with tar.gz file.
I got below error message. 

> ERROR: dependencies ‘dygraphs’, ‘extraDistr’, ‘rstan’, ‘xts’ are not available for package ‘prophet’
> * removing ‘/Users/alice/Library/R/3.6/library/prophet’

**Comment by dhisaxen** [comment]
I am unable to install propeht using the build script. I am seeing error "package ‘prophet’ is not available (for R version 3.6.0) "

**Comment by bletham** [comment]
We're working through some build issues and apparently did not get them fixed fast enough. The workaround for now is to install from github, which can be done in a single command once you install `devtools`:
```
devtools::install_github("facebook/prophet", subdir='R', ref="8306ae3")
```
and we're working to get this back on CRAN asap.

**Comment by seanjtaylor** [comment]
Here is the check result that was the cause of removal from CRAN:

```
The check problems on the Debian systems are caused by attempts to write
to the user library to which all packages get installed before checking
(and which now is remounted read-only for checking).

Having package code which is run as part of the checks and attempts to
write to the user library violates the CRAN Policy's

  Packages should not write in the user’s home filespace (including
  clipboards), nor anywhere else on the file system apart from the R
  session’s temporary directory (or during installation in the location
  pointed to by TMPDIR: and such usage should be cleaned up).
```

**Comment by bearloga** [comment]
I recently had to learn the {rstantools} method. Will try to find some time to make a PR if I can

**Comment by crhistian123** [comment]
@bletham,  When I try this command:

> > > devtools::install_github("facebook/prophet", subdir='R')
> Downloading GitHub repo facebook/prophet@master
> These packages have more recent versions available.
> It is recommended to update all of them.
> Which would you like to update?
> 
>  1: All                              
>  2: CRAN packages only               
>  3: None                             
>  4: rlang     (0.4.5 -> 0.4.6) [CRAN]
>  5: ggplot2   (3.2.1 -> 3.3.0) [CRAN]
>  6: lifecycle (0.1.0 -> 0.2.0) [CRAN]
>  7: vctrs     (0.2.3 -> 0.2.4) [CRAN]
>  8: purrr     (0.3.3 -> 0.3.4) [CRAN]
>  9: zoo       (1.8-7 -> 1.8-8) [CRAN]
> 10: withr     (2.1.2 -> 2.2.0) [CRAN]
> 11: pkgbuild  (1.0.6 -> 1.0.7) [CRAN]
> 12: backports (1.1.5 -> 1.1.6) [CRAN]
> 13: tibble    (2.1.3 -> 3.0.1) [CRAN]
> 
> Enter one or more numbers, or an empty line to skip updates:
> CRAN packages only
> Enter one or more numbers, or an empty line to skip updates:
> ggplot2   
> Enter one or more numbers, or an empty line to skip updates:

 1

> rlang     (0.4.5 -> 0.4.6) [CRAN]
> ggplot2   (3.2.1 -> 3.3.0) [CRAN]
> lifecycle (0.1.0 -> 0.2.0) [CRAN]
> vctrs     (0.2.3 -> 0.2.4) [CRAN]
> purrr     (0.3.3 -> 0.3.4) [CRAN]
> zoo       (1.8-7 -> 1.8-8) [CRAN]
> withr     (2.1.2 -> 2.2.0) [CRAN]
> pkgbuild  (1.0.6 -> 1.0.7) [CRAN]
> backports (1.1.5 -> 1.1.6) [CRAN]
> tibble    (2.1.3 -> 3.0.1) [CRAN]
> Skipping 1 packages ahead of CRAN: StanHeaders
> Installing 10 packages: rlang, ggplot2, lifecycle, vctrs, purrr, zoo, withr, pkgbuild, backports, tibble
> Installing packages into ‘C:/Users/crhis/Documents/R/win-library/3.6’
> (as ‘lib’ is unspecified)
> 
>   There are binary versions available but the source versions are later:
>       binary source needs_compilation
> rlang  0.4.5  0.4.6              TRUE
> zoo    1.8-7  1.8-8              TRUE
> 
> tentando a URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/ggplot2_3.3.0.zip'
> Content type 'application/zip' length 4021298 bytes (3.8 MB)
> downloaded 3.8 MB
> 
> tentando a URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/lifecycle_0.2.0.zip'
> Content type 'application/zip' length 101582 bytes (99 KB)
> downloaded 99 KB
> 
> tentando a URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/vctrs_0.2.4.zip'
> Content type 'application/zip' length 1027421 bytes (1003 KB)
> downloaded 1003 KB
> 
> tentando a URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/purrr_0.3.4.zip'
> Content type 'application/zip' length 430411 bytes (420 KB)
> downloaded 420 KB
> 
> tentando a URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/withr_2.2.0.zip'
> Content type 'application/zip' length 206792 bytes (201 KB)
> downloaded 201 KB
> 
> tentando a URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/pkgbuild_1.0.7.zip'
> Content type 'application/zip' length 136004 bytes (132 KB)
> downloaded 132 KB
> 
> tentando a URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/backports_1.1.6.zip'
> Content type 'application/zip' length 77492 bytes (75 KB)
> downloaded 75 KB
> 
> tentando a URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/tibble_3.0.1.zip'
> Content type 'application/zip' length 411838 bytes (402 KB)
> downloaded 402 KB
> 
> package ‘ggplot2’ successfully unpacked and MD5 sums checked
> package ‘lifecycle’ successfully unpacked and MD5 sums checked
> package ‘vctrs’ successfully unpacked and MD5 sums checked
> Erro: Failed to install 'prophet' from GitHub:
>   (convertido do aviso) cannot remove prior installation of package ‘vctrs’

What should I do? Thanks

**Comment by bletham** [comment]
Thanks to a quick fix by @bearloga, prophet is back in CRAN and so you can return to using `install.packages("prophet")`.
