### ISSUE TITLE
Flat weekly seasonality

### ISSUE THREAD

**Issue by shoaibkhanz** [facebook/prophet#1449]
I have time series data at a **weekly level** and each week starts on a sun.
The weird thing I notice is that after I have fit the model with weekly and yearly seasonality (additive or multiplicative), I get fair predictions. However, my weekly seasonality is just a flat line and I just don't understand why that would be ? At the same time, yearly seasonality is just fine.

**Comment by shoaibkhanz** [comment]
I cant share the data as its confidential, but here is what I have tried to do to understand this issue better.

**fitting a model with weekly seasonality `fourier order = 1`**
```
m3 = Prophet(daily_seasonality = False,weekly_seasonality = False,yearly_seasonality = False)
m3.add_seasonality(name = 'weekly',period =7,fourier_order = 1)
m3.fit(df)
future = m3.make_future_dataframe(periods=20,freq ='W')
forecast = m3.predict(future)

```
**manually calculating seasonality to better understand the issue**
```
t = np.array(
    (df['ds'] - datetime(1970,1,1)).dt.total_seconds().astype(np.float))/(3600*24.)

p = 7
x = (2 * np.pi * t)/p

sin_ = m3.params['beta'].ravel()[0]
cos_ = m3.params['beta'].ravel()[1]
weekly_seasonality = (np.cos(x) * cos_ + np.sin(x) *  sin_ )* df['y'].max() 

```
now when I print `weekly_seasonality` I get single number repeated for all dates and the result also matches the prophet output of weekly seasonality as well. So, thus I have calculated everything correctly. 

I am not sure, why weekly seasonality is behaving so ? There is no issue with yearly seasonality though.

**Comment by bletham** [comment]
The calculation does look correct to me. Weekly seasonality here means a seasonality with a period of 1 week. So it would capture e.g. changes in y due to it being Friday vs. Saturday. The period of 7 days means that every 7 days, the cycle repeats itself. So value of weekly seasonality on Sunday will be the same every Sunday. In this case the history only has data for Sunday, and so it will be the same for every day in the history. Does that make sense?

**Comment by shoaibkhanz** [comment]
yeah, it makes sense and perhaps my aha! moment says that my time series is fixed on Sunday.
i.e. the start date of my week is always a sunday thus I see just one value in my weekly seasonality. as you played (what it means for being weekly) it back to me, it helped! Thanks a lot!
