### ISSUE TITLE
Can't install prophet in R-4.0.0

### ISSUE THREAD

**Issue by davidjayjackson** [facebook/prophet#1450]
Prophet isn't listed in the package menu. 
So I tried to install using devtools, but no luck?

install_github("facebook/prophet")

**Comment by bletham** [comment]
This is related to #1448, which is that we got dropped from CRAN because we didn't fix our build issues quickly enough. You can install with devtools but need to specify the subdir:
```
devtools::install_github("facebook/prophet", subdir='R', ref="8306ae3")
```
(the `ref` here just points to the v0.6 release, removing that will install the latest from the `master` branch).

**Comment by davidjayjackson** [comment]
Ben,
Thanks for following up.

David

**Comment by bletham** [comment]
This should be resolved now, prophet is back in CRAN.
