### ISSUE TITLE
seasonality in add_aggressor's future values

### ISSUE THREAD

**Issue by swjoechen** [facebook/prophet#1451]
Hi fbprophet team,

Firstly wanted to say a huge thank you for providing such a great tool that helps with a lot of the problems that are otherwise very tricky to take on.

The issue, or rather just a straightforward question I have was regarding adding extra regressors.

I am trying to create future values for a model's extra regressor, which by itself has pretty strong weekly seasonality in the past, please see below, before vs after red dot line.

As we can see, it has pretty clear seasonality patterns up until the dip due to covid-19's hit, then we try to manually pace out the possible value in the future to help run the prophet model. My question is, would the extra regressor's current pacing affect the effectiveness of the model that fit with weekly seasonality in the past?

Thanks so much!

![image (44)](https://user-images.githubusercontent.com/48492821/80255521-17e87180-864b-11ea-8e85-a62e42db9d7d.png)

**Comment by bletham** [comment]
The extra regressor is added to the linear component of the model, so it is basically
```
y(t) = trend(t) + seasonality(t) + beta * regressor(t)
```
where `beta` is a coefficient that is fit to the data.

So, if your regressor has weekly seasonality and `beta` is not zero (that is, the regressor is actually being used by the model) then some of the seasonality in `y` will be explained by that. So the model seasonality term `seasonality(t)` will really be capturing the leftover seasonality in `y` after that which is explained by the regressor. When you flatten out the regressor, the seasonality in the forecast will thus be only that leftover seasonality. How much this will matter will depend on `beta` (how strong of a component the regressor is in the model). For the purposes of this pacing, the trend will be fine, but seasonality will likely be underestimated. If the seasonality is important, then I think you'd have to add the expected regressor seasonality into your future pacing.

**Comment by swjoechen** [comment]
@bletham thank you very much Ben, this makes sense and is super helpful! Just out of curiosity, would I be able to check the beta for a particular extra regressor in fbprophet built-in functions?

Thanks again!

**Comment by bletham** [comment]
The easiest way to get at that would just be to look at the component for the regressor in the forecast dataframe produced by `m.predict`. That gives the amount of `y` that is being attributed to the regressor, and so the relative magnitude between that and `y` is the weight being given to the regressor.
