### ISSUE TITLE
fbProphet Variable Selection and Independent Variable Interpretation/Impact Analysis

### ISSUE THREAD

**Issue by jpaulblue** [facebook/prophet#1459]
I'm relatively new to Prophet - and coding/GitHub for that matter - so if this isn't the place to ask this, please let me know. I'm just seeking some guidance on a part of FbProphet.

I'm aware of current discussions surrounding the addition of regressors and the different parameters associated with **.add_regressor()**. However, I have not seen many discussions oriented around the topic of feature selection and feature importances. 

I am aware of the ability to derive the beta variables from prophets output data frame (https://github.com/facebook/prophet/issues/928) - and maybe thats the best way we can do for interpretability, but I am curious as to what you all think about the addition of regressors.

I've found it very difficult to gauge the individual and global impact of added regressors on the dependent as well as their interactions with their fellow independent variables. It can be overwhelming trying to follow how everything added impacts everything else in Prophet and I don't know how to best think through and empirically find each variable's impact.

I believe more classical forecasting methods like VAR solutions this problem in the form of each variable having its own linear function of the lag values for all variables in the set (dependent and independent) - But i may be misunderstanding that as well.  :)

Maybe thats asking too much of Prophet - or any algorithm for that matter - but I thought I'd ask just to be sure.

Any Insight would be appreciated!

Best,
JB

**Comment by bletham** [comment]
On the question of feature importance: A pretty typical way of assessing feature importance is to, for each feature, fit the model both with and without that feature, and compare the performance. This would be pretty straightforward with Prophet - fit the model with and without the regressor, and each time measure performance using cross validation on the horizon of interest. The importance of the feature is then directly tied to its impact on the prediction of interest.

For selection, you could then leave out features that don't contribute enough to model prediction performance. (Though if there is correlation in the regressors, you may need to do this sequentially where you leave out the worst one (call it j), and then re-assess feature importance for all of the other features after dropping j, and then drop the new worst one, etc.)

**Comment by dharani-aws** [comment]
Hi @jpaulblue could you please advise me on below issue ? . Its quite urgent I am looking for a solution 

https://github.com/facebook/prophet/issues/1619

regards
Dharani
