### ISSUE TITLE
Missing argument in cross_validation

### ISSUE THREAD

**Issue by fbonaita** [facebook/prophet#1469]
Hi,
I use Python and I've tried to use the argument _parallel_ with `cross_validation()` but I got the error message:

> cross_validation() got an unexpected keyword argument 'parallel'.

I also checked with `inspect.getfullargspec()` and there's no trace of _parallel_.
I noticed it's been added only recently in #1434, is it possible that running `from fbprophet.diagnostics import cross_validation` doesn't provide the latest version yet?

**Comment by ryankarlos** [comment]
@fbonaita yes,  it hasn't been pushed to PyPI yet, so to use this immediately you'll need to download the code from github (master branch) and then install from that. 
Otherwise , it will be available in the next release (after 0.6)

**Comment by fbonaita** [comment]
Thank you for the clarification @ryankarlos.

**Comment by felipedram** [comment]
Hi!

Is it possible to install from git using `pip install git+https:// ...` in Windows/Anaconda?
And/or is there an idea of date for the next release?

**Comment by vishalmishra14** [comment]
how to pull master copy of fbprophet to use parallel parameter??
