### ISSUE TITLE
Add warning messages for missing days

### ISSUE THREAD

**Issue by Runze** [facebook/prophet#1477]
Hi! I was curious about what you think about adding warning messages when there are missing values or non-consecutive days in the dataset. I understand that Prophet handles missing values automatically, but I still think it's good to let users know about their presence in case they are not missing at random or they can be imputed with some institutional knowledge. What do you think?

**Comment by Runze** [comment]
Perhaps also relevant, when setting `seasonality_mode` to `multiplicative`, if the `y` variable contains 0, the logarithm of these 0s will be `Inf`, which will be treated as missing values by the model, is that correct? In that case, I think it's also useful to warn about them.

**Comment by svjack** [comment]
> Perhaps also relevant, when setting `seasonality_mode` to `multiplicative`, if the `y` variable contains 0, the logarithm of these 0s will be `Inf`, which will be treated as missing values by the model, is that correct? In that case, I think it's also useful to warn about them.

Have you try y contains 0 have errors ?
I think seasonality is only one component of the model, and this model is different with common seasonly decomposition model directly to y. Perhaps it may not yield errors.

**Comment by svjack** [comment]
> Hi! I was curious about what you think about adding warning messages when there are missing values or non-consecutive days in the dataset. I understand that Prophet handles missing values automatically, but I still think it's good to let users know about their presence in case they are not missing at random or they can be imputed with some institutional knowledge. What do you think?

With nan data, you can check MCMC intervals of the prediction to find nan and not fit best.

**Comment by bletham** [comment]
For multiplicative seasonality: It doesn't use a log transform, it actually directly models
```
y = trend(t) * (1 + seasonality(t))
```
so having 0s isn't actually an issue.

As for notifying of missing dates: Prophet doesn't assume any type of data regularity, either conceptually or in the software implementation. Forecasts for missing dates can be made directly with the model. So while I can see that it could be useful for some people to be made aware of the presence of missing data that they may not have known about, I feel that it's a bit outside the scope of this package. Someone who does want to impute their own values for missing data probably wouldn't find it too much effort to create this check themselves. That's my initial take on this anyway.

**Comment by Runze** [comment]
Thank you for clarifying the multiplicative seasonality and the design decision! Closing this issue now.
