### ISSUE TITLE
Setting positive values for additional regressor coefficients

### ISSUE THREAD

**Issue by ashwinpn** [facebook/prophet#1480]
Currently is there any support for defining positive values for additional regressor coefficients?   (in the context of priors, and the influence that this has on the forecasting)

**Comment by bletham** [comment]
This came up recently in #1405. There's some discussion of it there. There isn't really any way to do this right now. There's been a bit of work on adding this functionality but it got a bit complicated and stalled up, feel free to pitch in if you're able!

**Comment by ashwinpn** [comment]
Well, I checked out the log of issues, and this specific one seems to come up a lot! (Referenced in issue #1377 , issue #1349 too). Would definitely like to contribute.
