### ISSUE TITLE
from fbprophet.diagnostics import cross_validation

### ISSUE THREAD

**Issue by megakristiani** [facebook/prophet#1481]
fbprophet in d:\users\anaconda3\lib\site-packages (0.6)
'Prophet' object has no attribute 'stan_backend'

**Comment by bletham** [comment]
Could you post what code you ran to run into this error?

It's possible that it is failing to load the PyStan model. Could you run this code and let me know what messages are printed out?
```
from fbprophet import Prophet
import logging
logger = logging.getLogger('fbprophet')
logger.setLevel(logging.DEBUG)

m = Prophet()
print(m.stan_backend)
```

**Comment by eracle** [comment]
Once installed with conda, you can copy paste the stan_model folder into the fbprophet directory. So it would not be necessary to compile again with pystan. 
You can search for the stan_model folder inside the "External Libraries" folder you have on the left on the IDE. Hope it helps
