### ISSUE TITLE
Model taking forever to return the results when I am running using spark.

### ISSUE THREAD

**Issue by ankushreddy** [facebook/prophet#1482]
I am having a small dataset around 9k values. when I train the model it is taking around 4000 to 5000 iterations it is taking almost couple of hours to return the data.
Is there a way to set the limitations or to set time out.

These are the parameters that I am using 

`model = Prophet(growth = "linear", 
                        interval_width=0.95, 
                        yearly_seasonality=True, 
                        weekly_seasonality=False, 
                        daily_seasonality=False, 
                        holidays=holidays,
                        seasonality_mode = "additive")
        model.add_seasonality(name='yearly', period=365.25, fourier_order=10)
        model.add_country_holidays(country_name='US')`

`Iteration 3216. Log joint probability =    1057.52. Improved by 0.309114.
Iteration 3217. Log joint probability =    1057.81. Improved by 0.289322.
Iteration 3218. Log joint probability =    1057.92. Improved by 0.112497.
Iteration 3219. Log joint probability =    1058.14. Improved by 0.223203.
Iteration 3220. Log joint probability =    1058.29. Improved by 0.150475.
Iteration 3221. Log joint probability =    1058.42. Improved by 0.127985.
Iteration 3222. Log joint probability =    1058.45. Improved by 0.0276626.
Iteration 3223. Log joint probability =     1058.8. Improved by 0.349507.
Iteration 3224. Log joint probability =    1058.84. Improved by 0.0417333.
Iteration 3225. Log joint probability =    1059.42. Improved by 0.583481.
Iteration 3226. Log joint probability =    1059.65. Improved by 0.224732.
Iteration 3227. Log joint probability =    1059.96. Improved by 0.316668.
Iteration 3228. Log joint probability =    1061.31. Improved by 1.34647.
Iteration 3229. Log joint probability =    1061.76. Improved by 0.445363.
Iteration 3230. Log joint probability =    1062.03. Improved by 0.277961.
Iteration 3231. Log joint probability =    1062.87. Improved by 0.840931.
Iteration 3232. Log joint probability =    1063.14. Improved by 0.264146.
Iteration 3233. Log joint probability =    1063.31. Improved by 0.167159.
Iteration 3234. Log joint probability =    1063.37. Improved by 0.0648417.
Iteration 3235. Log joint probability =     1063.5. Improved by 0.13351.
Iteration 3236. Log joint probability =    1063.83. Improved by 0.328161.
Iteration 3237. Log joint probability =    1064.29. Improved by 0.460645.
Iteration 3238. Log joint probability =    1064.45. Improved by 0.152691.
Iteration 3239. Log joint probability =    1064.46. Improved by 0.0157281.
Iteration 3240. Log joint probability =    1065.34. Improved by 0.875037.
Iteration 3241. Log joint probability =    1065.54. Improved by 0.207478.
Iteration 3242. Log joint probability =     1065.6. Improved by 0.0602994.
Iteration 3243. Log joint probability =    1065.91. Improved by 0.310029.
Iteration 3244. Log joint probability =    1066.23. Improved by 0.314458.
Iteration 3245. Log joint probability =    1067.28. Improved by 1.05259.
Iteration 3246. Log joint probability =    1067.88. Improved by 0.598699.
Iteration 3247. Log joint probability =    1068.09. Improved by 0.206248.
Iteration 3248. Log joint probability =    1068.58. Improved by 0.490013.
Iteration 3249. Log joint probability =    1069.03. Improved by 0.452825.
Iteration 3250. Log joint probability =    1069.16. Improved by 0.13431.
Iteration 3251. Log joint probability =    1069.58. Improved by 0.411578.
Iteration 3252. Log joint probability =    1070.14. Improved by 0.565458.
Iteration 3253. Log joint probability =    1070.15. Improved by 0.00739314.
Iteration 3254. Log joint probability =    1070.87. Improved by 0.720909.
Iteration 3255. Log joint probability =    1071.08. Improved by 0.215632.
Iteration 3256. Log joint probability =    1071.32. Improved by 0.236172.
Iteration 3257. Log joint probability =     1071.8. Improved by 0.481558.
Iteration 3258. Log joint probability =    1071.86. Improved by 0.054658.
Iteration 3259. Log joint probability =    1071.97. Improved by 0.110042.
<string>:502: SettingWithCopyWarning:

A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

<string>:503: SettingWithCopyWarning:

A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

1210
5448
2065
XL
Iteration 3260. Log joint probability =    1072.16. Improved by 0.196655.
Iteration 3261. Log joint probability =     1072.7. Improved by 0.533853.
Iteration 3262. Log joint probability =     1073.1. Improved by 0.400175.
Iteration 3263. Log joint probability =    1073.31. Improved by 0.208219.
Initial log joint probability = -9
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes 
Iteration 3264. Log joint probability =    1073.99. Improved by 0.686541.
Iteration 3265. Log joint probability =    1074.68. Improved by 0.691669.
Iteration 3266. Log joint probability =    1074.87. Improved by 0.183165.
Iteration 3267. Log joint probability =    1075.37. Improved by 0.502154.
Iteration 3268. Log joint probability =    1075.45. Improved by 0.0788025.
Iteration 3269. Log joint probability =    1075.62. Improved by 0.169052.
      83        2620.7   0.000389527       124.489   2.655e-06       0.001      138  LS failed, Hessian reset 
Iteration 3270. Log joint probability =    1075.74. Improved by 0.125745.
      99       2620.92    0.00026726       82.0315      0.6895      0.6895      158   
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes 
Iteration 3271. Log joint probability =     1075.8. Improved by 0.0603919.
Iteration 3272. Log joint probability =    1076.11. Improved by 0.309295.
Iteration 3273. Log joint probability =    1076.32. Improved by 0.210414.
Iteration 3274. Log joint probability =    1076.52. Improved by 0.200225.
Iteration 3275. Log joint probability =    1076.97. Improved by 0.444049.
     163        2621.3   0.000466661       86.4034    5.48e-06       0.001      265  LS failed, Hessian reset 
Iteration 3276. Log joint probability =     1077.1. Improved by 0.134769.
Iteration 3277. Log joint probability =    1077.54. Improved by 0.436577.
Iteration 3278. Log joint probability =    1077.69. Improved by 0.146429.
     199       2621.34   0.000145679       93.3025           1           1      308   
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes 
Iteration 3279. Log joint probability =    1077.92. Improved by 0.237037.
Iteration 3280. Log joint probability =    1078.02. Improved by 0.0982676.
Iteration 3281. Log joint probability =    1078.02. Improved by 0.00289352.
Iteration 3282. Log joint probability =    1078.36. Improved by 0.338022.
Iteration 3283. Log joint probability =    1078.73. Improved by 0.370174.
     235       2621.35   4.07223e-05       93.3174   4.588e-07       0.001      397  LS failed, Hessian reset 
Iteration 3284. Log joint probability =    1078.92. Improved by 0.186653.
Iteration 3285. Log joint probability =    1079.17. Improved by 0.252585.
Iteration 3286. Log joint probability =    1079.72. Improved by 0.548383.
Iteration 3287. Log joint probability =    1079.73. Improved by 0.0123985.
     291       2621.36   1.15393e-07        75.883      0.2798           1      473   
Optimization terminated normally: 
  Convergence detected: relative gradient magnitude is below tolerance
Iteration 3288. Log joint probability =    1079.82. Improved by 0.084792.
Iteration 3289. Log joint probability =    1079.96. Improved by 0.139271.
Iteration 3290. Log joint probability =    1079.97. Improved by 0.0188282.
Iteration 3291. Log joint probability =       1080. Improved by 0.026679.
Iteration 3292. Log joint probability =    1080.28. Improved by 0.282309.
Iteration 3293. Log joint probability =    1080.72. Improved by 0.434755.
Iteration 3294. Log joint probability =     1080.9. Improved by 0.185696.
Iteration 3295. Log joint probability =    1080.97. Improved by 0.0694154.
Iteration 3296. Log joint probability =     1081.1. Improved by 0.129172.
Iteration 3297. Log joint probability =    1081.18. Improved by 0.0817105.
Iteration 3298. Log joint probability =    1081.32. Improved by 0.135554.
Iteration 3299. Log joint probability =    1081.61. Improved by 0.285313.
Iteration 3300. Log joint probability =    1081.89. Improved by 0.283696.
Iteration 3301. Log joint probability =    1082.09. Improved by 0.202657.
Iteration 3302. Log joint probability =    1082.16. Improved by 0.0654562.
Iteration 3303. Log joint probability =    1082.39. Improved by 0.237343.
Iteration 3304. Log joint probability =    1082.65. Improved by 0.253768.
Iteration 3305. Log joint probability =    1082.68. Improved by 0.0326266.
Iteration 3306. Log joint probability =    1082.99. Improved by 0.311547.
Iteration 3307. Log joint probability =    1083.19. Improved by 0.195663.
Iteration 3308. Log joint probability =    1083.41. Improved by 0.222634.
Iteration 3309. Log joint probability =    1083.48. Improved by 0.0682925.
Iteration 3310. Log joint probability =    1083.51. Improved by 0.0339284.
Iteration 3311. Log joint probability =    1083.64. Improved by 0.122462.
Iteration 3312. Log joint probability =    1083.87. Improved by 0.235477.
Iteration 3313. Log joint probability =     1083.9. Improved by 0.031806.
Iteration 3314. Log joint probability =    1083.91. Improved by 0.011834.
Iteration 3315. Log joint probability =       1084. Improved by 0.0890038.
Iteration 3316. Log joint probability =    1084.12. Improved by 0.116472.
Iteration 3317. Log joint probability =     1084.4. Improved by 0.276496.
Iteration 3318. Log joint probability =    1084.55. Improved by 0.156454.
Iteration 3319. Log joint probability =    1084.55. Improved by 0.00166974.
Iteration 3320. Log joint probability =     1084.6. Improved by 0.048554.
Iteration 3321. Log joint probability =    1084.82. Improved by 0.220555.
Iteration 3322. Log joint probability =    1084.95. Improved by`

Please let me know if there are any changes that I need to make.

**Comment by svjack** [comment]
Prophet fit method have kwargs option, that you can pass to PyStan, which is the internal bayes opt, there are two key methods for PyStan model.——  “sample” and “optimizing”
And you can see prophet truly call sample in its method,
For “optimizing” you can try to set valid args as follows:
valid_args = {"iter", "save_iterations", "refresh",
                      "init_alpha", "tol_obj", "tol_grad", "tol_param",
                      "tol_rel_obj", "tol_rel_grad", "history_size"}

For “sample” you can try to set valid args as follows:
valid_args = {"chain_id", "init_r", "test_grad", "append_samples", "refresh", "control"}

But I think you set some Params not suitable, in the model
Much time takes in fit the Fourier series for higher order, if you 
Can decrease this time consumption, may tackle it.

**Comment by bletham** [comment]
It looks like the optimization is converging very slow. My guess would be that the likelihood surface is very flat, because the model fit is poor / the model is misspecified. It also is using Newton, which means that L-BFGS failed, also suggestive model fit issues. Is there any chance you could post the figure produced by `m.plot(forecast)`? That might give some insight.

As far as what to do - increasing the regularization will add more curvature to the likelihood surface and will likely help the optimizer terminate faster. So try reducing the `holidays_prior_scale` and `seasonality_prior_scale`, maybe to something like 0.1.

**Comment by ankushreddy** [comment]
@bletham @svjack  thank you for the update.

I am running this in a pyspark environment it will be tough to generate the figures using m.plot.
and more over when I am running the same code for a single combination in my local machine is just taking 1 Min but when I scale it up to multiple combinations and run it in pyspark it is taking around 8 to 10 mins for single combination.

**Comment by stgoa** [comment]
I had the same problem. Since your dataset is too small, the stan optimizer being used is newton, which is slower than LBFGS. In the class [PyStanBackend](https://github.com/facebook/prophet/blob/main/python/prophet/models.py), we have:
`    def fit(self, stan_init, stan_data, **kwargs) -> dict:

        args = dict(
            data=stan_data,
            init=lambda: stan_init,
            algorithm='Newton' if stan_data['T'] < 100 else 'LBFGS',
            iter=1e4,
        )
        args.update(kwargs)` 

A way to force the use of one estimator is to pass to the .fit() method (of the class [Prophet](https://github.com/facebook/prophet/blob/main/python/prophet/forecaster.py)) the argument algorithm='LBFGS', which in my experience is faster in spark
