### ISSUE TITLE
Extra regressor coefficients

### ISSUE THREAD

**Issue by thomas-woodruff** [facebook/prophet#1487]
Hello there,

I'm trying to better understand how adding extra regressors affect the model specification and if it's possible to retrieve their model coefficients.

Adding extra regressors isn't discussed in detail in the original paper. My understanding from the docs is that adding a (single) extra regressor, `X(t)`, changes the General Additive Model from this:

`y(t) = g(t) + s(t) + h(t) + ε_t`

to:

`y(t) = g(t) + s(t) + h(t) + β*X(t) + ε_t`

Is my understanding correct? If so, is there a way of retrieving the regressor coefficients, `β`, from the model?

If not, it seems I can simply regress `yhat - g(t) - s(t) - h(t)` on `X(t)`. 

Thanks,
Tom

**Comment by shoaibkhanz** [comment]
Answering the first part of the question, yes you are right, its a simple matrix multiplication.
So the equation becomes  this `y(t) = g(t) + s(t) + h(t) + β*X(t) + ε_t`.

All the coefficients are stored here `model.params`, its an ordered dictionary in python.
here what the keys stand for in that dictionary.

`k` --> base growth
`m` --> offset
`delta` --> coefficients for changepoints
`sigma_bs`  --> noise's standard deviation
`beta`  --> coefficients for seasonality, holidays and extra regressors

e.g. beta coefficients are stored here: `model.params['beta']`

using the following you can get the coefficients for seasonality, extra regressors, bring everything together (*the mapping dataframe is this.. i.e. `train_component_cols`*)

 `model.train_component_cols.T.dot(np.array(model.params['beta'])[0])`

**Comment by thomas-woodruff** [comment]
Excellent - thanks for your explanation @shoaibkhanz ! I'll have a look into this.

**Comment by bletham** [comment]
I just wanted to add that both the time series and the regressor are normalized/standardized before model fitting, and the value that you read out of `m.params['beta']` will be in the transformed space and so not directly applicable to `y` and the regressor. Another way to see the effect of the regressor is in the forecast dataframe produced by `predict`, which will have a column that gives exactly the amount of `y` that is being attributed to the regressor. There's some more discussion of this in https://github.com/facebook/prophet/issues/1264#issuecomment-580400794.
