### ISSUE TITLE
Forecasting with a gap in series

### ISSUE THREAD

**Issue by nrchade** [facebook/prophet#1488]
Having an issue with some of my models which is now leading me to question some assumptions I may have made.  I have trained a model on 20,000 hours of data with extra regressors (i.e. weather forecasts).  The catch is, I have a lag in when I will get new Y's (i.e. 30 days).  

Is it appropriate to train a model, and then make the prediction 30 days out plus the horizon I'm interested in?  Or is this wrong for some reason?  Most of my model results look reasonable with this approach but some are giving nonsensical predictions (i.e. far outside logistic regression boundaries of cap and floor)  

Thx

**Comment by svjack** [comment]
The developer had answer the out boundary problem, that you can see the code in the predict function in prophet model.
The product function predict different components individually.
And combine them ( by add or multiply) in the final predict process.
The cap and floor affect on only one part. And the seasonality predictor and others may push the final prediction out of them,
You can clip the value by yourself.

**Comment by bletham** [comment]
@nrchade Sure, that's totally reasonable to predict for the whole period for which you don't have data; "future" can be relative to what data you have :-)

As for seeing data outside logistic bounds, as @svjack notes, those bounds apply only to the `trend` component, where
```
y(t) = trend(t) + seasonality(t) + beta * regressor(t)
```
So seasonality and especially the regressor can easily fluctuate `y` outside those bounds. If you have more concerns, feel free to post the figure produced by `m.plot(forecast)` and I could give more comments on if things are behaving as expected.

**Comment by nrchade** [comment]
Hi bletham,

Here are some plots I took of one of the models that is making me scratch my head.
![PlotComponents](https://user-images.githubusercontent.com/9909926/82145115-28d17080-980e-11ea-8877-44fc8cd0e6ec.png)

I also saved images of the forecast both pre and post "clipping"  This model is constrained between 0 and 220.
![ForecastPlotZoomed](https://user-images.githubusercontent.com/9909926/82145139-5b7b6900-980e-11ea-90ec-1bb66a590753.png)
![ForecastPlotZoomedpost clipping](https://user-images.githubusercontent.com/9909926/82145143-5fa78680-980e-11ea-9c56-90cd7493f2f7.png)

**Comment by bletham** [comment]
The model stores the scaling used during fitting, so if you're loading the model from a pickle and passing in un-scaled data to `predict`, it will do the right thing and scale it the same way it was scaled at fit time.

Could you also post the model prediction for the training data? This would do it:
```
fcst = m.predict()  # if you don't pass in anything, it will predict on the history
m.plot(fcst)
m.plot_components(fcst)
```

**Comment by nrchade** [comment]
m.plot(fcst):
![Figure_1](https://user-images.githubusercontent.com/9909926/82244675-3d456400-9907-11ea-9fb8-658951c8faa2.png)
m.plot_components(fcst):
![Figure_2](https://user-images.githubusercontent.com/9909926/82244739-4d5d4380-9907-11ea-9648-c7050afebfbe.png)

**Comment by bletham** [comment]
Thanks!
The in-sample fit here looks fairly reasonable. You'll notice that nearly all of Y is being explained by the extra regressors. The y-axis of `extra_regressors_additive` is the amount of `y` being attributed to the extra regressors. It goes up to ~150, while seasonalities are only being used to explain +/- 20 change in y.

Now if you look at the forecast, you'll see that the extra regressor takes on larger values than in the history. In the history, it has average of ~80, and only a few spikes above 200. In the future values, it has average of 200. That is why the forecast is so much higher than what is seen in the history.

Is it correct that the values for the extra regressor are higher in your future dataframe than in the history?

**Comment by nrchade** [comment]
Part of the difficulty in checking that is that m.history shows the scaled values and my dataframe for future is unscaled.  Is there a way to get unscaled data from a pickled model?  I don't think the period I'm considering has significantly higher values than the training set which was part of the reason I was confused by this particular model's output.

**Comment by bletham** [comment]
Ah, I had thought perhaps you still had the original values around. As you note in `m.history` they are scaled already.
The scaling happens here:
https://github.com/facebook/prophet/blob/16e632a6958bc1fbfcc67ed8628ba8c972df15db/python/fbprophet/forecaster.py#L324-L325

So you can un-scale it with
```
m.history['name'] * m.extra_regressors['name']['std'] + m.extra_regressors['name']['mu']
```

**Comment by nrchade** [comment]
I actually did more digging after my last post and ended up finding and doing this line:
`scaled_future = m.setup_dataframe(future)`

I then compared the averages for each column between past and future and have data that looks like this:


  | future | past
-- | -- | --
binary_regressor_1 | 0.0156 | 0.0536
binary_regressor_2 | 0.0234 | 0.0454
binary_regressor_3 | 0.013 | 0.0549
binary_regressor_4 | 0.0078 | 0.046
binary_regressor_5 | 0.0597 | 0.0746
binary_regressor_6 | 0.0312 | 0.0763
binary_regressor_7 | 0.0468 | 0.072
binary_regressor_8 | 0.0234 | 0.0748
binary_regressor_9 | 0.013 | 0.0326
binary_regressor_10 | 0.0026 | 0.0268
binary_regressor_11 | 0.0052 | 0.0343
binary_regressor_12 | 0.0208 | 0.0282
binary_regressor_13 | 0.039 | 0.0259
binary_regressor_14 | 0.0494 | 0.027
binary_regressor_15 | 0.0727 | 0.0296
binary_regressor_16 | 0.0727 | 0.0305
binary_regressor_17 | 0.0649 | 0.0403
binary_regressor_18 | 0.1013 | 0.0472
binary_regressor_19 | 0.0987 | 0.0416
binary_regressor_20 | 0.1117 | 0.0492
binary_regressor_21 | 0.0909 | 0.0263
binary_regressor_22 | 0.0571 | 0.0279
binary_regressor_23 | 0.0442 | 0.0274
binary_regressor_24 | 0.0571 | 0.0289
binary_regressor_25 | 0.039 | 0.034
binary_regressor_26 | 0.0649 | 0.0323
binary_regressor_27 | 0.0519 | 0.0343
binary_regressor_28 | 0.0416 | 0.0334
binary_regressor_29 | 0.0701 | 0.0552
binary_regressor_30 | 0.0649 | 0.0548
binary_regressor_31 | 0.0468 | 0.0517
binary_regressor_32 | 0.0468 | 0.0495
binary_regressor_33 | 0.0052 | 0.0258
binary_regressor_34 | 0.0026 | 0.0276
binary_regressor_35 | 0.0078 | 0.0261
binary_regressor_36 | 0.0026 | 0.0268
binary_regressor_37 | 0.013 | 0.0201
binary_regressor_38 | 0.0234 | 0.0188
binary_regressor_39 | 0.0078 | 0.0207
binary_regressor_40 | 0.0312 | 0.019
binary_regressor_41 | 0.0078 | 0.0184
binary_regressor_42 | 0 | 0.0189
binary_regressor_43 | 0.0182 | 0.0186
binary_regressor_44 | 0.0052 | 0.0185
binary_regressor_45 | 0.013 | 0.0337
binary_regressor_46 | 0.0104 | 0.0369
binary_regressor_47 | 0.013 | 0.0368
binary_regressor_48 | 0.0104 | 0.0426
binary_regressor_49 | 0.0338 | 0.0618
binary_regressor_50 | 0.0312 | 0.0652
binary_regressor_51 | 0.0416 | 0.0674
binary_regressor_52 | 0.0779 | 0.0709
binary_regressor_53 | 0.2545 | 0.2028
binary_regressor_54 | 0.2468 | 0.2018
binary_regressor_55 | 0.2494 | 0.1955
binary_regressor_56 | 0.2234 | 0.1923
binary_regressor_57 | 0.0727 | 0.128
binary_regressor_58 | 0.0831 | 0.1229
binary_regressor_59 | 0.0675 | 0.1168
binary_regressor_60 | 0.0675 | 0.1131
binary_regressor_61 | 0.2078 | 0.167
binary_regressor_62 | 0.2078 | 0.1703
binary_regressor_63 | 0.2156 | 0.1723
binary_regressor_64 | 0.2 | 0.1765
binary_regressor_65 | 0.0156 | 0.0555
binary_regressor_66 | 0.0234 | 0.0465
binary_regressor_67 | 0.0078 | 0.0577
binary_regressor_68 | 0.0078 | 0.0473
binary_regressor_69 | 0.0753 | 0.0772
binary_regressor_70 | 0.039 | 0.0795
binary_regressor_71 | 0.0597 | 0.0707
binary_regressor_72 | 0.0312 | 0.0764
binary_regressor_73 | 0.0026 | 0.0324
binary_regressor_74 | 0.0026 | 0.0266
binary_regressor_75 | 0.0052 | 0.0343
binary_regressor_76 | 0.0182 | 0.0278
binary_regressor_77 | 0.0364 | 0.0256
binary_regressor_78 | 0.0468 | 0.0259
binary_regressor_79 | 0.0701 | 0.0281
binary_regressor_80 | 0.0623 | 0.0287
binary_regressor_81 | 0.0545 | 0.0379
binary_regressor_82 | 0.0987 | 0.0465
binary_regressor_83 | 0.0909 | 0.0396
binary_regressor_84 | 0.1013 | 0.0462
binary_regressor_85 | 0.0909 | 0.0251
binary_regressor_86 | 0.0623 | 0.0268
binary_regressor_87 | 0.0494 | 0.026
binary_regressor_88 | 0.0727 | 0.0277
binary_regressor_89 | 0.0545 | 0.034
binary_regressor_90 | 0.0753 | 0.0333
binary_regressor_91 | 0.0545 | 0.0344
binary_regressor_92 | 0.0519 | 0.0329
binary_regressor_93 | 0.0519 | 0.0588
binary_regressor_94 | 0.0571 | 0.0559
binary_regressor_95 | 0.0416 | 0.0546
binary_regressor_96 | 0.0416 | 0.0521
binary_regressor_97 | 0.0052 | 0.0252
binary_regressor_98 | 0.0078 | 0.027
binary_regressor_99 | 0.0078 | 0.0248
binary_regressor_100 | 0.0026 | 0.0255
binary_regressor_101 | 0.0182 | 0.0207
binary_regressor_102 | 0.0234 | 0.0189
binary_regressor_103 | 0.0052 | 0.0201
binary_regressor_104 | 0.0156 | 0.0188
binary_regressor_105 | 0.0156 | 0.0192
binary_regressor_106 | 0 | 0.0202
binary_regressor_107 | 0.0182 | 0.0197
binary_regressor_108 | 0.0182 | 0.0187
binary_regressor_109 | 0.0052 | 0.0338
binary_regressor_110 | 0.0078 | 0.0366
binary_regressor_111 | 0.0156 | 0.036
binary_regressor_112 | 0.0156 | 0.0418
binary_regressor_113 | 0.0364 | 0.0566
binary_regressor_114 | 0.0234 | 0.0602
binary_regressor_115 | 0.0442 | 0.0638
binary_regressor_116 | 0.0701 | 0.0696
binary_regressor_117 | 0.2701 | 0.2081
binary_regressor_118 | 0.2753 | 0.2071
binary_regressor_119 | 0.2571 | 0.2029
binary_regressor_120 | 0.2312 | 0.1978
binary_regressor_121 | 0.0753 | 0.1325
binary_regressor_122 | 0.0727 | 0.1268
binary_regressor_123 | 0.0779 | 0.1211
binary_regressor_124 | 0.0675 | 0.1151
binary_regressor_125 | 0.1922 | 0.1573
binary_regressor_126 | 0.1844 | 0.1623
binary_regressor_127 | 0.1948 | 0.1662
binary_regressor_128 | 0.1922 | 0.1735
value_regressor_1 | 0.1711 | 0
value_regressor_2 | 0.1619 | 0
value_regressor_3 | 0.1316 | 0
value_regressor_4 | 0.1783 | 0
value_regressor_5 | 0.5034 | 0
value_regressor_6 | 0.5058 | 0
value_regressor_7 | 0.4133 | 0
value_regressor_8 | 0.4757 | 0
value_regressor_9 | -1.0767 | 0.0001
value_regressor_10 | -1.0953 | -0.0009
value_regressor_11 | -0.2847 | 0.0003
value_regressor_12 | -0.4262 | -0.0008
value_regressor_13 | 0.5639 | -0.0001
value_regressor_14 | 0.5933 | 0.0001
value_regressor_15 | 0.623 | 0
value_regressor_16 | 0.639 | -0.0001
cap | 220 | 220
cap_scaled | 1.0002 | 1.0002
floor | 0 | 0
t | 1.0682 | 0.4991

t is the variable that jumps out at me as being quite different. I'm going to try the reverse and do the un-scaling as you suggested above.

**Comment by bletham** [comment]
`t` is the model internal time; basically the history dates are all scaled to [0, 1] and that scaled time is `t`. It's >1 for future values.

I think the easiest way to get at this question will actually be to look at the forecast dataframe produced by `m.predict`. In it there will be a column for each extra regressor. that column will tell you the amount of `yhat` that comes from that regressor. Comparing the future ones to the past ones will help you indicate which regressors are the source of the increase, given that there are a very large number in this model. You can get the past ones by just making a prediction on the history, as I specified above.

**Comment by nrchade** [comment]
| past | future | Diff
-- | -- | -- | --
trend | 1.249 | 14.856 | 13.608
cap | 220.000 | 220.000 | 0.000
floor | 0.000 | 0.000 | 0.000
value_regressor_1 | 0.000 | -2.215 | -2.215
value_regressor_2 | 0.000 | -3.293 | -3.293
value_regressor_3 | 0.000 | 9.660 | 9.660
value_regressor_4 | 0.000 | -9.692 | -9.692
binary_regressor_1 | -0.448 | -0.239 | 0.209
binary_regressor_2 | 0.237 | 0.068 | -0.169
binary_regressor_3 | 1.425 | 0.808 | -0.616
binary_regressor_4 | 0.452 | 0.230 | -0.223
binary_regressor_5 | -0.099 | -0.138 | -0.039
binary_regressor_6 | -0.128 | -0.131 | -0.003
binary_regressor_7 | 2.171 | 2.664 | 0.493
binary_regressor_8 | 1.677 | 1.747 | 0.071
binary_regressor_9 | 0.002 | 0.001 | -0.001
binary_regressor_10 | 0.080 | 0.039 | -0.041
binary_regressor_11 | 0.363 | 0.165 | -0.198
binary_regressor_12 | 0.099 | 0.045 | -0.053
binary_regressor_13 | 0.150 | 0.390 | 0.241
binary_regressor_14 | 0.258 | 0.894 | 0.637
binary_regressor_15 | 0.695 | 1.281 | 0.586
binary_regressor_16 | 0.493 | 1.343 | 0.851
binary_regressor_17 | 0.204 | 0.619 | 0.415
binary_regressor_18 | -0.028 | -0.080 | -0.053
binary_regressor_19 | 1.048 | 2.553 | 1.505
binary_regressor_20 | 0.814 | 2.233 | 1.419
binary_regressor_21 | 0.123 | 0.376 | 0.253
binary_regressor_22 | 0.119 | 0.287 | 0.169
binary_regressor_23 | 0.594 | 1.746 | 1.152
binary_regressor_24 | 0.347 | 0.687 | 0.340
binary_regressor_25 | 0.522 | 0.637 | 0.115
binary_regressor_26 | 0.411 | 0.727 | 0.316
binary_regressor_27 | 0.478 | 0.687 | 0.209
binary_regressor_28 | 0.596 | 1.068 | 0.472
binary_regressor_29 | 0.961 | 1.312 | 0.351
binary_regressor_30 | 0.743 | 0.951 | 0.208
binary_regressor_31 | 0.364 | 0.603 | 0.239
binary_regressor_32 | 0.725 | 1.141 | 0.416
binary_regressor_33 | 0.331 | 0.033 | -0.298
binary_regressor_34 | 0.236 | 0.044 | -0.191
binary_regressor_35 | -0.060 | -0.006 | 0.054
binary_regressor_36 | -0.019 | -0.004 | 0.016
binary_regressor_37 | 0.268 | 0.104 | -0.164
binary_regressor_38 | -0.176 | -0.049 | 0.127
binary_regressor_39 | 0.263 | 0.132 | -0.131
binary_regressor_40 | 0.033 | 0.009 | -0.024
binary_regressor_41 | 0.336 | 0.000 | -0.336
binary_regressor_42 | -0.038 | -0.005 | 0.033
binary_regressor_43 | 0.217 | 0.091 | -0.126
binary_regressor_44 | 0.006 | 0.002 | -0.005
binary_regressor_45 | 0.808 | 0.187 | -0.621
binary_regressor_46 | 0.282 | 0.099 | -0.183
binary_regressor_47 | -0.277 | -0.020 | 0.258
binary_regressor_48 | 0.006 | 0.001 | -0.005
binary_regressor_49 | 0.988 | 0.208 | -0.780
binary_regressor_50 | 1.609 | 0.256 | -1.352
binary_regressor_51 | -0.681 | -0.131 | 0.550
binary_regressor_52 | 0.111 | 0.037 | -0.074
binary_regressor_53 | 2.329 | 2.178 | -0.152
binary_regressor_54 | 5.302 | 5.050 | -0.252
binary_regressor_55 | -0.873 | -0.811 | 0.061
binary_regressor_56 | 2.884 | 2.416 | -0.468
binary_regressor_57 | 1.445 | 1.172 | -0.272
binary_regressor_58 | 2.875 | 2.490 | -0.384
binary_regressor_59 | 0.219 | 0.175 | -0.044
binary_regressor_60 | 1.156 | 0.983 | -0.173
binary_regressor_61 | 1.202 | 1.047 | -0.155
binary_regressor_62 | 4.726 | 3.749 | -0.977
binary_regressor_63 | -1.178 | -1.243 | -0.065
binary_regressor_64 | 2.070 | 2.010 | -0.060
value_regressor_5 | 0.000 | 1.200 | 1.200
value_regressor_6 | 0.000 | -2.494 | -2.494
value_regressor_7 | 0.000 | 2.358 | 2.358
value_regressor_8 | 0.000 | -0.641 | -0.641
binary_regressor_65 | 0.622 | 0.378 | -0.244
binary_regressor_66 | 0.330 | 0.111 | -0.220
binary_regressor_67 | 0.333 | 0.210 | -0.123
binary_regressor_68 | 0.837 | 0.368 | -0.469
binary_regressor_69 | 0.214 | 0.338 | 0.124
binary_regressor_70 | 0.298 | 0.311 | 0.014
binary_regressor_71 | 0.203 | 0.275 | 0.073
binary_regressor_72 | 0.667 | 0.861 | 0.194
binary_regressor_73 | 0.403 | 0.129 | -0.274
binary_regressor_74 | 0.332 | 0.130 | -0.202
binary_regressor_75 | 0.480 | 0.218 | -0.262
binary_regressor_76 | 0.706 | 0.463 | -0.243
binary_regressor_77 | 0.174 | 0.406 | 0.232
binary_regressor_78 | 0.094 | 0.236 | 0.142
binary_regressor_79 | -0.004 | -0.007 | -0.003
binary_regressor_80 | 0.097 | 0.246 | 0.149
binary_regressor_81 | -0.023 | -0.068 | -0.045
binary_regressor_82 | 0.193 | 0.572 | 0.378
binary_regressor_83 | 0.045 | 0.116 | 0.071
binary_regressor_84 | 0.295 | 0.813 | 0.518
binary_regressor_85 | 0.079 | 0.246 | 0.167
binary_regressor_86 | 0.044 | 0.152 | 0.109
binary_regressor_87 | 0.015 | 0.041 | 0.026
binary_regressor_88 | 0.234 | 0.483 | 0.249
binary_regressor_89 | 0.345 | 0.474 | 0.129
binary_regressor_90 | 0.222 | 0.398 | 0.176
binary_regressor_91 | 0.101 | 0.153 | 0.052
binary_regressor_92 | -0.018 | -0.044 | -0.025
binary_regressor_93 | 0.681 | 0.901 | 0.221
binary_regressor_94 | 0.667 | 0.836 | 0.169
binary_regressor_95 | 0.807 | 1.189 | 0.382
binary_regressor_96 | 0.063 | 0.075 | 0.012
binary_regressor_97 | 0.408 | 0.084 | -0.324
binary_regressor_98 | 0.352 | 0.034 | -0.318
binary_regressor_99 | 0.346 | 0.109 | -0.237
binary_regressor_100 | 0.283 | 0.058 | -0.225
binary_regressor_101 | 0.187 | 0.070 | -0.116
binary_regressor_102 | 0.217 | 0.090 | -0.128
binary_regressor_103 | 0.119 | 0.062 | -0.057
binary_regressor_104 | 0.356 | 0.098 | -0.258
binary_regressor_105 | 0.141 | 0.000 | -0.141
binary_regressor_106 | 0.395 | 0.102 | -0.293
binary_regressor_107 | 0.108 | 0.028 | -0.079
binary_regressor_108 | 0.327 | 0.045 | -0.282
binary_regressor_109 | 0.187 | 0.014 | -0.173
binary_regressor_110 | 0.731 | 0.104 | -0.627
binary_regressor_111 | 0.528 | 0.038 | -0.490
binary_regressor_112 | 0.471 | 0.059 | -0.413
binary_regressor_113 | 0.489 | 0.090 | -0.400
binary_regressor_114 | 0.406 | 0.105 | -0.301
binary_regressor_115 | 1.232 | 0.251 | -0.981
binary_regressor_116 | 0.430 | 0.144 | -0.285
binary_regressor_117 | 3.622 | 3.436 | -0.186
binary_regressor_118 | 2.416 | 2.424 | 0.009
binary_regressor_119 | 3.308 | 3.262 | -0.047
binary_regressor_120 | 1.467 | 1.271 | -0.196
binary_regressor_121 | 1.769 | 1.386 | -0.382
binary_regressor_122 | 1.676 | 1.305 | -0.371
binary_regressor_123 | 2.056 | 1.676 | -0.380
binary_regressor_124 | 0.753 | 0.646 | -0.107
binary_regressor_125 | 2.831 | 2.384 | -0.447
binary_regressor_126 | 0.968 | 0.728 | -0.240
binary_regressor_127 | 3.070 | 2.831 | -0.239
binary_regressor_128 | 0.582 | 0.514 | -0.068
value_regressor_9 | 0.007 | -58.144 | -58.151
value_regressor_10 | 0.147 | 143.179 | 143.032
value_regressor_11 | 0.045 | -8.433 | -8.478
value_regressor_12 | 0.050 | 11.773 | 11.723
value_regressor_13 | -0.005 | 12.914 | 12.919
value_regressor_14 | -0.002 | -12.542 | -12.540
value_regressor_15 | 0.000 | 4.536 | 4.536
value_regressor_16 | 0.000 | 1.293 | 1.294
daily | 0.094 | -0.005 | -0.099
weekly | 0.003 | 0.060 | 0.057
yearly | 0.793 | -16.238 | -17.031
  |   |   |  
yhat | 85.991 | 167.511 | 81.520
Regressors + daily + weekly + yearly +   trend | 85.991 | 167.511 | 81.520

I think I have done the comparison as you suggested.  I took the average of the forecast for each column and compared it to m.predict() (which I'm calling "past") and averaged those columns as well. So in trying to interpret this, is it correct to say that in this case, "value_regressor9" and "value_regressor10" are having the largest impact?
