### ISSUE TITLE
Duplicated graphs when using add_regressor function and call plot_components 

### ISSUE THREAD

**Issue by makaishi2** [facebook/prophet#1490]
I got duplicated graphs when using add_register function and then called plot_components.
A Sample coding is as follow:
(x and df has columns ds, y, temp, weather)

```
m = Prophet(yearly_seasonality=5, weekly_seasonality=5, daily_seasonality=False)
m.add_regressor('temp')
m.add_regressor('weather')
m.fit(x)

future = m.make_future_dataframe(periods=61, freq='D')
f_add = df[['weather', 'temp']]
future2 = pd.concat([future, f_add], axis=1)

fcst = m.predict(future)
m2.plot_components(fcst)
```

**Comment by shoaibkhanz** [comment]
I can see an error in your code.
you are not using the same model object.
i.e. `m` and `m2`

`fcst = m.predict(future)` m object called
`m2.plot_components(fcst)` m2 object called

**Comment by makaishi2** [comment]
Sorry I mistook my sample code.
Right code is as follows:

```
m = Prophet(yearly_seasonality=5, weekly_seasonality=5, daily_seasonality=False)
m.add_regressor('temp')
m.add_regressor('weather')
m.fit(x)

future = m.make_future_dataframe(periods=61, freq='D')
f_add = df[['weather', 'temp']]
future2 = pd.concat([future, f_add], axis=1)

fcst = m.predict(future)
m.plot_components(fcst)
```

**Comment by shoaibkhanz** [comment]
so are you saying that when you run `m.plot_components(fcst)` you get the same plots twice.
if its so, please use this and see if it helps.

`fig = m.plot_components(fcst)`

**Comment by ryankarlos** [comment]
If you are running this in Jupyter then this happens because the return value of the plot is also generated in addition to the original plot generated from the plot method. So you could either assign it to a variable instead `fig=m.plot_components(fcst)` or have a semi colon after the call to `plot_components(fcst);` to suppress the return value.

**Comment by makaishi2** [comment]
It worked well!
Thanks a lot!
