### ISSUE TITLE
Use Sales-Target to adjust forecast

### ISSUE THREAD

**Issue by yuzuhikorunrun** [facebook/prophet#1493]
Hello great team who developed prophet,

I work at a farily traditional industry so in my case, unlike retailors, we don't have promotions, but instead, we have a sales-target value (annual, semi-anual, monthly).  Usually, our sales team rely on these numbers to check where they are in the year (e.g., rolling% of hitting the target) and adjust their performances, and for example, if they realize in Oct, they already achieved 99% of the goal, they'll slow it down in Nov and Dec and vice versa. 

I have tried adding (rolling% of target hit / actual sales-target) as extra regressors in my model, yet it appears not every helpful in terms of capturing the extreme (very high/low) months across the year. And weirdly, **monthly sales-target performed better compared to using the rolling% target hit ,** which in my mind does not make sense. 

My question is: **if I want the model to adjust its prediction refering to the sales target hit% am i doing it right? by adding this information as extra regressor?** 

thank you!

**Comment by bletham** [comment]
I'm not sure how well this will work as a regressor. The regressors are linear; the model is essentially
```
y(t) = trend(t) + seasonality(t) + beta * regressor(t)
```
Does it seem to you that the relationship here would be linear? That would be the key thing for it working.
