### ISSUE TITLE
Possible Regularization methods for Prophet

### ISSUE THREAD

**Issue by DivJ** [facebook/prophet#1494]
Is there a way to add a sort of regularization for prophet models? I believe my model is suffering from high variance and is sensitive to hyperparameters. I have a large number of time-series but with very less number of data points (~36). I am doing cross-validation as well but still, the outputs change rapidly in different iterations.

**Comment by svjack** [comment]
Disable components in the model, in construction of Prophet object. If must use some components decrease the Fourier order or the prior of it.
They can all exclude components other than linear or multi parts of the model.

**Comment by svjack** [comment]
But if you do like that, the model will Degenerate to general logistic or linear model, than you can see sklearn provide you Elastic net regularized regression model which have l1 reg and l2 reg in the weighted form.

**Comment by bletham** [comment]
Yeah, with that little data you're going to be a bit limited with what you can learn. You can crank down the changepoint_prior_scale to 0.01 and seasonality_prior_scale to something like 0.1 to add a lot of regularization. You can also set `n_changepoints=0`, which will produce a linear trend with no changes, which may be more robust for very short time series like this.

**Comment by DivJ** [comment]
I am using hyperparameter tuning using cross-validation to find changepoint prior scales as defined in #1320. Does that make sense or should I set these values as you said?

**Comment by bletham** [comment]
I guess you could try it both ways. The challenge with cross validation is that with only ~36 points the errors are being estimated based on an even smaller number of held-out samples, so I'd expect there to be very high variance in the cross validation errors, which could produce high variance in which hyperparameters are selected. Cranking them all to be relatively tight would reduce that variance and could thus possibly end up producing something that is overall better, but it really depends on what the bias/variance trade-off is for these particular time series.
