### ISSUE TITLE
How to change y_ticks on model.plot so it shows the exponential of y

### ISSUE THREAD

**Issue by viktivan19** [facebook/prophet#1495]
Before training the model I convert my target using np.log(y) and after getting the predictions I  convert them back with np.exp(yhat). How can I change the model.plot(forecast) plot in a way that the y ticks are the np.exp(y) rather than the values used for training the model?

**Comment by ryankarlos** [comment]
Hello @viktivan19  :)

So the history df gets stored in an attribute to model object  `m.history`
In the code this happens here 
https://github.com/facebook/prophet/blob/caaaee8d34f66fd4e8ad140b20c4d26b59a90e0a/python/fbprophet/forecaster.py#L1085-L1091

`yhat`, `yhat_lower` and `yhat_upper ` forecasts columns are stored in `forecast `df

which then gets used to generate the plots when calling `m.plot(forecast)`

https://github.com/facebook/prophet/blob/caaaee8d34f66fd4e8ad140b20c4d26b59a90e0a/python/fbprophet/plot.py#L69-L72

https://github.com/facebook/prophet/blob/caaaee8d34f66fd4e8ad140b20c4d26b59a90e0a/python/fbprophet/plot.py#L77-L79

So you would need to transform the columns in both these dfs before calling `m.plot(forecast)`

As an example from quick_start docs Manning dataset

**Plot with log scale**
```
import numpy as np
import pandas as pd
from fbprophet import Prophet
df['y'] = np.log(df['y'])
m = Prophet()
m.fit(df)
future = m.make_future_dataframe(periods=365)
forecast = m.predict(future)
m.plot(forecast);
```
![image](https://user-images.githubusercontent.com/16509490/81974954-388a6280-961e-11ea-93f8-f5c8ecb82042.png)


**Plot with original values before log transform**
```
m.history['y'] = np.exp(m.history['y'])
cols = ['yhat_lower', 'yhat_upper', 'yhat']
forecast[cols] = forecast[cols].transform(np.exp)
m.plot(forecast);
```
![image](https://user-images.githubusercontent.com/16509490/81975424-e7c73980-961e-11ea-87ff-abc31225e935.png)
