### ISSUE TITLE
tqdm warning in notebook

### ISSUE THREAD

**Issue by bletham** [facebook/prophet#1498]
#1338 added a progress bar to the cross validation using tqdm. Now, importing fbprophet in a jupyter notebook produces the warning
```
[...]/fbprophet/diagnostics.py:10: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm
```
This will need to be cleaned up since it could be confusing to users who won't know what tqdm is and might think it's an error.

**Comment by ryankarlos** [comment]
fixed via #1509
