### ISSUE TITLE
extract cross validation fits

### ISSUE THREAD

**Issue by shoaibkhanz** [facebook/prophet#1499]
Currently when we use the `cross_validation` the return object is a dataframe.
While when we use cross validation it fits multiple models and then predicts the horizon.
Now I am keen to **extract the fit results** from each fit that takes place during the cross validation process.

This will help me to view the coefficient values for my regressors and thus be able to know which regressors are important as the model is trained on different periods.

**Comment by bletham** [comment]
There isn't an especially clean way to do this. The cross validation code is fairly simple; basically it generates the list of cutoff dates using this:
https://github.com/facebook/prophet/blob/16e632a6958bc1fbfcc67ed8628ba8c972df15db/python/fbprophet/diagnostics.py#L20
and then for each date in that list, calls this function which fits the model using data up to that cutoff, and makes the prediction for `horizon` time:
https://github.com/facebook/prophet/blob/16e632a6958bc1fbfcc67ed8628ba8c972df15db/python/fbprophet/diagnostics.py#L196

`df` here is `model.history`:
https://github.com/facebook/prophet/blob/16e632a6958bc1fbfcc67ed8628ba8c972df15db/python/fbprophet/diagnostics.py#L117

You can look at the docstring for `single_cutoff_forecast` for a complete description of each of the parameters, but I think it's fairly self explanatory.

To do what you want, you'd have to copy the code for `single_cutoff_forecast` but then make a new version that also returns `m`. Then you can set up the loop yourself to run that for all of the cutoff dates that you want to evaluate. That should all be pretty simple to set up, with the only annoyance of having to edit that function.
