### ISSUE TITLE
Prophet for daily stock trading

### ISSUE THREAD

**Issue by erangil** [facebook/prophet#1502]
I've been working with Prophet for the last two weeks trying to understand all it's capabilities and features.

In your opinion is it suitable enough for daily stock trading? 
I'm trying to predict trends in stock prices at the resolution of minutes.

I'm also trying to work with some other RNN + LSTM models.

I must say that Prophet is fairly easy to use but I'm still finding it hard to fine tune the predictions thati I'm receiving and improve the results. I feel like it's trial and error as I'm trying various combinations of parameters but without much luck.

Any suggestions and support will be highly appreciated.

Thanks Eran.

**Comment by bletham** [comment]
Prophet is best-suited for time series with the sort of seasonal trends that are typical to business time series. I'm doubtful that stock price data has the sort of seasonal structure that would make Prophet a good choice. But people do periodically post about forecasting stock prices, so maybe someone else will be able to chime in with their experience.
