### ISSUE TITLE
[Win10, Python] How to work with the latest version on Github?

### ISSUE THREAD

**Issue by palexbg** [facebook/prophet#1507]
Apologies for posting this here as it is probably somewhat out of topic, but I am not sure where to start, I have been trying for many hours today.

In short - I am trying to run prophet from my fork of the latest master branch of Prophet on Github, **not** from the PyPi repository.
The reason for this is because I want to be able to experiment a bit with the code, as well as change e.g. the Stan file and play with it.

After numerous issues of installing the prophet package that is on PyPi on my windows 10 machine, I finally managed to do it, using a conda interpreter for my project, as suggested elsewhere.
However, I realized that the package that I had (v 0.6) is somewhat behind the one on the master branch and that e.g. the stan file is a pickle and not so easy to edit - hence I would like to use the one on Github, branch out, make changes etc.

But I am not sure how to proceed to do that... I would normally create a Project with Pycharm with its own venv, requirements etc. and copy over relevant folders of a Github Repo (or clone it using the terminal of Pycharm). 
When I do this here and try to run a test script, however I get the error :
```
Importing plotly failed. Interactive plots will not work.
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\pydevd.py", line 1415, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/GithubNew/poredno/test.py", line 7, in <module>
    m = Prophet()
  File "C:\GithubNew\poredno\fbprophet\forecaster.py", line 141, in __init__
    self._load_stan_backend(stan_backend)
  File "C:\GithubNew\poredno\fbprophet\forecaster.py", line 154, in _load_stan_backend
    logger.debug("Loaded stan backend: %s", self.stan_backend.get_type())
AttributeError: 'Prophet' object has no attribute 'stan_backend'
```

Here is how my project folder looks like:
![image](https://user-images.githubusercontent.com/56965360/82493001-818f5a80-9ae7-11ea-8b02-406748560780.png)

I would very much appreciate some help, I am not quite sure what the general steps are and how to proceed.

**Comment by bletham** [comment]
I haven't ever been successful in getting fbprophet to work in windows except via conda. The difficulty comes from getting the C++ compiler to work with pystan; conda ships with its own C++ toolchain. If you can get pystan working, then fbprophet will work. I expect that if you try running this code you will find that pystan is not working:
```
import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this will take a minute
y = model.sampling(n_jobs=1).extract()['y']
y.mean()  # should be close to 0
```
PyStan has some instructions for installing on windows, but they mostly assume conda too: https://pystan.readthedocs.io/en/latest/windows.html . It sounds like you have gotten pystan working in conda; I think you should be able to then install fbprophet from source (`python setup.py install`) inside the conda environment.

For the specific `AttributeError: 'Prophet' object has no attribute 'stan_backend'`, this means the pystan compilation of the model failed. If you can run this and let me know what it prints out, that would be helpful to see the debug logs.
```
from fbprophet import Prophet
import logging
logger = logging.getLogger('fbprophet')
logger.setLevel(logging.DEBUG)

m = Prophet()
print(m.stan_backend)
```

**Comment by eracle** [comment]
Once installed with conda, you can copy paste the stan_model folder into the fbprophet directory. So it would not be necessary to compile again with pystan. 
You can search for the stan_model folder inside the "External Libraries" folder you have on the left on the IDE. Hope it helps
