### ISSUE TITLE
Weekly Seasonality changes due to Coronavirus-19

### ISSUE THREAD

**Issue by GretaShi3084** [facebook/prophet#1508]
My time series data is the daily call volumes we receive from our customers. 
Recently I find the weekly pattern changes after the outbreak of COVID-19 as less people call us in weekends while the level of weekdays almost remains unchanged.
I want my model to capture the most recent pattern (or give it more weight), but based on my understanding it would just take the average of all my training data.
I search in Github and find this should be the same problem mentioned in #391 and #425. Just want to see do we have any solution?
if no, any suggestion that I can quickly take as of now to improve the forecast accuracy?
Many thanks!

**Comment by Olof-Hojvall** [comment]
The examples in https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#seasonalities-that-depend-on-other-factors could help.

In that example the default weekly seasonality is turned off, and is replaced by on_season and off_seasons components. In this case it's maybe possible keep the normal weekly seasonality and add the corona weekly pattern on top of it. Something like:
```
df['is_covid19'] = df['ds'] >= '2020-03-01'
m = Prophet(weekly_seasonality=True)
m.add_seasonality(name='weekly_covid19', period=7, fourier_order=3, condition_name='is_covid19')
```

**Comment by GretaShi3084** [comment]
Thank you so much @Olof-Hojvall ! Your method works well in my dataset. I really appreciate your kind help!
