### ISSUE TITLE
Windows 10 cannot import name 'prophet' from 'fbprophet' (unknown location)

### ISSUE THREAD

**Issue by zyc0416** [facebook/prophet#1514]
In Jupyter,the following can't run succcessfully with the error  "cannot import name 'prophet' from 'fbprophet' (unknown location)",so how to solve it?My version  is 0.6. I am a green hand and learn it by myself.Thanks for your help very much.
# Python
import pandas as pd
from fbprophet import prophet

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-19-965cfa44d43e> in <module>
      2 
      3 import pandas as pd
----> 4 from fbprophet import prophet
ImportError: cannot import name 'prophet' from 'fbprophet' (unknown location)

**Comment by bletham** [comment]
I think the issue here is that the name is case sensitive, so it needs to be
```
from fbprophet import Prophet
```
