### ISSUE TITLE
Does changepoints work?

### ISSUE THREAD

**Issue by FankLi** [facebook/prophet#1516]
`import pandas as pd
import numpy as np
from fbprophet import Prophet
import matplotlib.pyplot as plt

import warnings

warnings.filterwarnings('ignore')

import logging

logging.getLogger().setLevel(logging.ERROR)

prediction_size = 7

date_rng = pd.date_range(start='2020-05-04', end='2020-06-07', freq='D')
df = pd.DataFrame(date_rng, columns=['ds'])
df['y'] = list(range(10, 80, 10)) * int(df.shape[0] / 7)

''' set outlier '''
df.loc[1, 'y'] = 100

train_df = df[:-prediction_size]

m = Prophet(changepoints=['2020-05-05'])  ''' MAPE 33.78305710819468  MAE 8.977582829345316 '''
''' m = Prophet()  # MAPE 30.115773147342544 MAE 7.796704992161217 '''
m.fit(train_df)

future = m.make_future_dataframe(periods=prediction_size)

forecast = m.predict(future)

m.plot(forecast)

m.plot_components(forecast)

def make_comparison_dataframe(historical, forecast):
    return forecast.set_index('ds')[['yhat', 'yhat_lower', 'yhat_upper']]. \
        join(historical.set_index('ds'))

cmp_df = make_comparison_dataframe(df, forecast)

def calculate_forecast_errors(df, prediction_size):
    df = df.copy()
    df['e'] = df['y'] - df['yhat']
    df['p'] = 100 * df['e'] / df['y']
    prediction_part = df[-prediction_size:]
    error_mean = lambda error_name: np.mean(np.abs(prediction_part[error_name]))
    return {'MAPE': error_mean('p'), 'MAE': error_mean('e')}

for err_name, err_value in calculate_forecast_errors(cmp_df, prediction_size).items():
    print(err_name, err_value)

def show_forecast(cmp_df, num_predictions, num_values, title):
    plt.figure(figsize=(10, 4))
    plt.plot(cmp_df['y'][-num_values:], 'r', label='actual')
    plt.plot(cmp_df['yhat'][-num_predictions:], 'b', label='forecast')
    plt.plot(cmp_df['yhat_upper'][-num_predictions:], 'gray', alpha=0.6, linestyle='dashed', label='upper/lower bond')
    plt.plot(cmp_df['yhat_lower'][-num_predictions:], 'gray', alpha=0.6, linestyle='dashed')
    plt.legend(loc='upper left')
    plt.fill_between(x=cmp_df.index[-num_predictions:], y1=cmp_df['yhat_upper'][-num_predictions:],
                     y2=cmp_df['yhat_lower'][-num_predictions:], alpha=0.5, color='lightgrey')
    plt.title(title)
    plt.grid(True)

show_forecast(cmp_df, prediction_size, 100, 'New posts on Medium')

plt.show()

print('end')`

**m = Prophet(changepoints=['2020-05-05'])  
MAPE 33.78305710819468  
MAE8.977582829345316

 m = Prophet()  
 MAPE 30.115773147342544 
MAE 7.796704992161217**

**Comment by bletham** [comment]
Changepoints are for changes in a piecewise linear trend; see https://facebook.github.io/prophet/docs/trend_changepoints.html for examples. It is not for outliers, which are not part of the trend at all. As described in the documentation there, when you specify a list of changepoints, those will be the only points at which the trend is allowed to change. I think if you look at the plot produced by `m.plot` for each model it will be clear why the default changepoint selection is better than specifying just one.

**Comment by FankLi** [comment]
> Changepoints are for changes in a piecewise linear trend; see https://facebook.github.io/prophet/docs/trend_changepoints.html for examples. It is not for outliers, which are not part of the trend at all. As described in the documentation there, when you specify a list of changepoints, those will be the only points at which the trend is allowed to change. I think if you look at the plot produced by `m.plot` for each model it will be clear why the default changepoint selection is better than specifying just one.

1. m = Prophet(changepoints=['2020-05-05'])
2. m = Prophet()

I still don't understand，why 2 is better than 1 with MAPE ang MAE ?

**Comment by andrew-pollock** [comment]
> 1. m = Prophet(changepoints=['2020-05-05'])
> 2. m = Prophet()
> 
> I still don't understand，why 2 is better than 1 with MAPE ang MAE ?

In example 1 prophet will only (potentially) fit 1 changepoint (at 2020-05-05). In example 2 prophet will use the default behaviour which is (potentially) 25 evenly spaced changepoints. When you specify that you want a changepoint at 2020-05-05 you're actually reducing the number of changepoints that prophet attempts to fit from 25 down to 1. 

Bletham's link goes into more details but your first example is an example of specifying the locations of the changepoints and your second example is an example of automatic changepoint detection in Prophet.
