### ISSUE TITLE
make_future_dataframe series dates missing

### ISSUE THREAD

**Issue by sbaumbaugh** [facebook/prophet#1517]
Making monthly future data frame I've found prophet drops the dates between 
2020-04-01 and 2020-12-01.

thoughts?
![Screen Shot 2020-05-28 at 7 55 33 AM](https://user-images.githubusercontent.com/60758737/83144808-83de4f80-a0b9-11ea-974a-8f5b431bffdf.png)
![Screen Shot 2020-05-28 at 7 56 12 AM](https://user-images.githubusercontent.com/60758737/83144829-88a30380-a0b9-11ea-89d1-29589c14d7e1.png)

**Comment by bletham** [comment]
I'm not exactly sure what's happening here. Could you post some code that I can run to reproduce the issue? Could you post `m$history.dates`?

**Comment by sbaumbaugh** [comment]
Sure thing @bletham, be back Friday.
Thank you for the help Sir.
