### ISSUE TITLE
fbprophet AttributeError: 'DatetimeIndex' object has no attribute 'weekday_name'

### ISSUE THREAD

**Issue by 2043930** [facebook/prophet#1519]
AttributeError                            Traceback (most recent call last)
<ipython-input-179-2bf67437aea3> in <module>
----> 1 figure2 = m.plot_components(forecast)

~/opt/anaconda3/lib/python3.7/site-packages/fbprophet/forecaster.py in plot_components(self, fcst, uncertainty, plot_cap, weekly_start, yearly_start)
   1549 
   1550         Will plot whichever are available of: trend, holidays, weekly
-> 1551         seasonality, and yearly seasonality.
   1552 
   1553         Parameters

~/opt/anaconda3/lib/python3.7/site-packages/fbprophet/plot.py in plot_components(m, fcst, uncertainty, plot_cap, weekly_start, yearly_start, figsize)
    158             )
    159         elif plot_name in m.seasonalities:
--> 160             if plot_name == 'weekly' or m.seasonalities[plot_name]['period'] == 7:
    161                 plot_weekly(
    162                     m=m, name=plot_name, ax=ax, uncertainty=uncertainty, weekly_start=weekly_start

~/opt/anaconda3/lib/python3.7/site-packages/fbprophet/plot.py in plot_weekly(m, ax, uncertainty, weekly_start, figsize, name)
    286         ax = fig.add_subplot(111)
    287     # Compute weekly seasonality for a Sun-Sat sequence of dates.
--> 288     days = (pd.date_range(start='2017-01-01', periods=7) +
    289             pd.Timedelta(days=weekly_start))
    290     df_w = seasonality_plot_df(m, days)

AttributeError: 'DatetimeIndex' object has no attribute 'weekday_name'

I am getting this error. please help.

**Comment by bletham** [comment]
This looks like #1304, which is an incompatability between fbprophet==0.5 and pandas>=1.0.
You can check the version of these with
```
import fbprophet
print(fbprophet.__version__)
import pandas
print(pandas.__version__)
```
The best thing to do would be to upgrade fbprophet to the latest version, which is 0.6. That will resolve this issue.

If for whatever reason that isn't possible, the only alternative would be to downgrade pandas to 0.25.3.
