### ISSUE TITLE
built in holiday function in R

### ISSUE THREAD

**Issue by sarthakg94** [facebook/prophet#1520]
Code:
m <- prophet(yearly.seasonality = F,weekly.seasonality = F,
            daily.seasonality = F)
m<-add_seasonality(m,name = "Custom", period = 4,fourier.order =  15)
m<-add_seasonality(m,name = "Yearly", period = 48,fourier.order = 10)
m<-add_country_holidays(country_name = 'US')
m<-fit.prophet(m,df_prophet_Train)

Error:
Error in add_country_holidays(country_name = "US") : 
  argument "m" is missing, with no default

Also can i add custom frequency in the argument:
future <- make_future_dataframe(m, periods = 5, freq = "week")
so instead of week i need to provide a number

**Comment by benmwhite** [comment]
You're not specifying the model in your `add_country_holidays()` call, the error message is telling you you're missing a function argument.

**Comment by sarthakg94** [comment]
@benmwhite thanks i don't know how i missed it, i also resolved the frequency issue..
thanks
