### ISSUE TITLE
What is the reason that My Facebook Prophet model did not fit well?

### ISSUE THREAD

**Issue by aurumpierre** [facebook/prophet#1521]
Hello,

I have a 30 weekly average sales datas of 2015 and want to make prediction with the rest of 20 weeks of 2015 . My 30 weeks data like on below:

30 weeks df:
![prophet](https://user-images.githubusercontent.com/19674538/83429841-5852c080-a43d-11ea-9d26-2eefe5b3b8d3.png)

Actual data of the next 20 weeks df:
![ActualDataof20weeks](https://user-images.githubusercontent.com/19674538/83430483-6c4af200-a43e-11ea-82da-2ee4c8c41a44.png)

Code:
model=Prophet(interval_width=0.95,growth='logistic',weekly_seasonality=True)
model.fit(df_30Weeks) 
model=Prophet(interval_width=0.95,growth='logistic',weekly_seasonality=True)
model.fit(df_30Weeks)
future_dates = model.make_future_dataframe(periods = 20, freq='W')
future_dates['cap']=100
future_dates['floor']=0
forecast = model.predict(future_dates)
forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(7)

Here is the prediction prophet made:
![FORECAST](https://user-images.githubusercontent.com/19674538/83431149-8cc77c00-a43f-11ea-9e88-15a161cf330d.png)

And its plot:
![plot](https://user-images.githubusercontent.com/19674538/83431299-cef0bd80-a43f-11ea-89cd-5c29c7342882.png)

The RMSE is 43.669640768117475

What do you think this bad fits possible reasons? My assume is maybe it is not responds minumum data requirements if is there any?
Thanks.

**Comment by bletham** [comment]
I'd expect it to do better on this time series. A couple notes:
1. Weekly seasonality means seasonality within the week, like seasonal effects for Monday. vs. Tuesday etc. In this case where there is one datapoint per week, it won't be able to be fit and you should leave it disabled.
2. The trend is entirely failing to fit. Having the spurious seasonality could be making the fitting harder so disabling it might help, but I doubt it. Generally the logistic growth trend is harder to fit (from a numerical optimization point of view) so you might try just with the default piecewise linear trend instead. If you do that then it will predict negative values, but you can just clip them to 0 (replace negative forecast values with 0). The forecast yhat will be straight 0 on this time series, but you should see the upper uncertainty bound eventually become positive as you move further into the future.
