### ISSUE TITLE
daily seasonality has percentage below -100

### ISSUE THREAD

**Issue by divyanshu16** [facebook/prophet#1524]
Hi 

I am using prophet to forecast on my data and I found that daily seasonality goes below -100% for some time. I am using `weekly_seasonality`, `daily_seasonality`, `seasonality_mode` as multiplicative and `changepoint_prior_scale` as 0.05.

When I execute below code, I get negative numbers in some places too.
 ```
df_y = seasonality_plot_df(m, days)
seas = m.predict_seasonal_components(df_y)
``` 

What does below -100% in the daily seasonality graph mean?
Can I say something about my data seeing this?
Is there a way to keep the scale fixed or know the range of daily seasonality component?

<img width="459" alt="Screenshot 2020-06-03 at 12 02 29 PM" src="https://user-images.githubusercontent.com/11975046/83604719-45063900-a594-11ea-8668-c2bde64cb139.png">
<img width="457" alt="Screenshot 2020-06-03 at 12 02 18 PM" src="https://user-images.githubusercontent.com/11975046/83604741-49caed00-a594-11ea-844f-f0e5b28c215b.png">

**Comment by bletham** [comment]
A seasonality of -100% just means that the seasonal effect is the entire trend magnitude, so it is bringing the forecast down to 0. You can see this in the data from the first 3 weeks where it is spiking down to 0; that is the -100%. If it were 120% that would mean the seasonal effect is 1.2x the trend. For this particular time series, it's pretty clear that the magnitude of the seasonality is shrinking along with the trend, so multiplicative seasonality is appropriate here. Is that helpful?
