### ISSUE TITLE
Forecast within an unreasonable range - cap issue?

### ISSUE THREAD

**Issue by yanivbm88** [facebook/prophet#1530]
Hi,

I find Prophet very useful. However, I do have an issue of occasional predictions I get that exceed a reasonable range, as in the example I attach below. 

The first plot is the validation forecast, which seems fine. The forecast is within the same range of the training data. The second plot is the future forecast **of the same data, using the same hyper-parameters**, in which the predicted values range jumped from 400 to 1,750,000.

**Validation forecast**
![image](https://user-images.githubusercontent.com/19760109/84039014-4c20b300-a9a9-11ea-91ea-1b77ed1c07df.png)

**Future forecast**
![image](https://user-images.githubusercontent.com/19760109/84038926-314e3e80-a9a9-11ea-8a43-f0989f476c07.png)

**My questions are accordingly:**

1. I defined a high cap (around 317,000), but I don't want to get predictions within these range. My thought was just not to have the prediction range limited. Is that a wrong approach?
2. Does defining a cap that is relatively high in comparison to the existing values increases the chances of such an 'exploding' prediction to occur? 
3. Is there another parametric reason you can think of that can increase the chances of an 'exploding' prediction to occur?

Thank you in advance!

**Comment by bletham** [comment]
Could you post the components plot produced by `m.plot_components`? I'm wondering if this could be an issue with seasonality, like what just came up in #1522.
