### ISSUE TITLE
predictive_samples dimensions

### ISSUE THREAD

**Issue by bacross** [facebook/prophet#1531]
Hi, I've got a forecast with a trend, seasonality, holidays and one additional regressor.  When I use the predictive_samples function call, my yhat array has shape (3,1200) - the 1200 is a function of the number of chains and samples, but why 3 rows?

**Comment by bletham** [comment]
3 should be the number of rows in the dataframe you're passing into `predictive_samples`. Is that right? We should add that to the docstring.
