### ISSUE TITLE
plotly not working in Google Colab

### ISSUE THREAD

**Issue by shabutheenbasha** [facebook/prophet#1533]
Hi Team,

I have tried to do forecasting using fbprophet in Google Colab. All works fine except the Saturating Forecast and Plotly part and generates empty output

**Comment by bletham** [comment]
I haven't used Colab, but maybe try
```
fig = plot_plotly(m, forecast)
fig.show()
```
(based on https://stackoverflow.com/questions/47230817/plotly-notebook-mode-with-google-colaboratory)
