### ISSUE TITLE
Extra regressor contribution vs value

### ISSUE THREAD

**Issue by mathdvg** [facebook/prophet#1537]
Hello,

I have been using prophet in R to model my timeseries y and I have added an extra regressor "regressor" that is already standardized, as per the code below.

```
m <- prophet(weekly.seasonality = TRUE)
m <- add_regressor(m, regressor, standardize = FALSE, mode='additive')
m <- fit.prophet(m, df_train)
```

I am looking to understand the contribution of the regressor and I've obtained its parameter by calling `model$params$beta` and got the value -0.0129529. 

From my understanding of prophet, the contribution of the regressor to the timeseries on a given day should be the value of the regressor multiplied by its estimate parameter (since it is not standardized by prophet). I was very surprised to find this is not the case at all. 

I run 
`forecast <- predict(model, df_prophet$test)`
and find that if for example the value of the regressor on day 2 in df_prophet$test is 11.11 then the value of regressor in forecast is -10.87071 which is far from 11.11 * -0.0129529. 

Could you please explain the formula between the regressor and its contribution?

Many thanks

**Comment by bletham** [comment]
`y` is also normalized during model fitting:
https://github.com/facebook/prophet/blob/9a27386cccc01f1b7529bd613da64562bef92f34/R/R/prophet.R#L389
https://github.com/facebook/prophet/blob/9a27386cccc01f1b7529bd613da64562bef92f34/R/R/prophet.R#L358

which is the source of the difference here. If you undo the scaling with `m$y.scale` everything should match.

**Comment by mathdvg** [comment]
Thanks for your very prompt reply!

How can I remove y scaling? Should I set model$y.scale to 1?  Can I set this as a parameter when creating the model?

Thanks again

**Comment by bletham** [comment]
This isn't something that can be disabled, and I think if you were to try it would hurt model performance since hardcoded priors assume scaled data and could be really inappropriate for unscaled data.

`model$params$beta * m$y.scale` should give you what you're looking for.
