### ISSUE TITLE
Skipping MAPE because y close to 0

### ISSUE THREAD

**Issue by shabutheenbasha** [facebook/prophet#1539]
Hi Team,

I am trying to do forecast on the fbprophet in terms of an hourly basis from the historical data of 3 months and I am forecasting for the next 720 hours (30 days). The forecasting was as expected but when I do cross-validation, the MAPE data is not getting reflected and the prophet is showing as "Skipping MAPE because of y close to 0". Can anyone suggest me how to get the MAPE so that I can evaluate the model? Also, is there any ways of evaluating the fbprohet model.

**Comment by bletham** [comment]
MAPE is defined as the mean of |(y_true - y_hat) / y_true|:
https://github.com/facebook/prophet/blob/0d260699e4776c449703a957f08eca8013461a47/python/fbprophet/diagnostics.py#L561
This isn't defined for y_true=0, so if y_true is close to 0 it will be skipped:
https://github.com/facebook/prophet/blob/0d260699e4776c449703a957f08eca8013461a47/python/fbprophet/diagnostics.py#L360-L362

In this case, you should just use one of the other metrics, for instance RMSE and MAE are often both good options.
