### ISSUE TITLE
Release schedule?

### ISSUE THREAD

**Issue by hansukyang** [facebook/prophet#1540]
Hi - thanks for maintaining this tool, I find it extremely useful. I was wondering what the next release & update milestone is, or if there is a page where I can find this information?

**Comment by bletham** [comment]
There isn't a fixed release schedule, releases tend to happen when we have accumulated enough new features that it makes sense to push them all out (or when there is a breaking change in an upstream package that necessitates it).

I'm pretty confident we'll do a new push in July.

**Comment by hansukyang** [comment]
That's great to know - thanks for the info!
