### ISSUE TITLE
prophet install error on anaconda 3 - incompatibility error

### ISSUE THREAD

**Issue by ochenao** [facebook/prophet#1541]
Hi,

I am trying to install fbprophet on anaconda3 on a Win 7 but it is erroring out.
I already have  pystan and all the required dependencies.
_conda install -c conda-forge fbprophet_
I even tried _conda install fbprophet -c conda-forge -c defaults --override-channels_

Same error...

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible so
lve.
Solving environment: failed with repodata from current_repodata.json, will retry
 with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible so
lve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - fbprophet -> python[version='2.7.*|3.5.*|3.6.*']

Your python: python=3.7

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not change your python version to a different minor version unless you explicitly specify that.

**Comment by bletham** [comment]
I'm not sure what's happening here; conda forge has fbprophet for py37, you can see it as win-64/fbprophet-0.6-py37h6538335_0.tar.bz2 here: https://anaconda.org/conda-forge/fbprophet/files

This is related to #1227, though that is for py38 which has not been built.

**Comment by ochenao** [comment]
Still no joy, now i urgently need it to complete my research. Help please... how about the online jupyterlabs? Just a though...

Regards,

Ochen

**Comment by ochenao** [comment]
Hi,

I  was able to install fbprophet on anaconda3 python 3.7 on my Win7 albeit not the usual way.
What I did was:

1. Manually downloaded fbprophet_0.2.1_py2.7.tar.bz2 file, extracted the files.
2. Launched the anaconda console, cd to the condabin directory.
3. used pip to install the package.

Note, it failed to install certain calendar components like the Islamic Calendar and something on the Gregorian calendar but i was able to get on fine post that.

Just so, if someone is caught  out in the same situation that i was in.

Regards,

Ochen
