### ISSUE TITLE
issue with creating future_dataframe and getting results by id with prophet and pandas UDF on grouped df

### ISSUE THREAD

**Issue by petarzashev** [facebook/prophet#1550]
I am trying to implement solution suggested here : https://towardsdatascience.com/pyspark-forecasting-with-pandas-udf-and-fb-prophet-e9d70f86d802

In the very end he concatenates the prediction with the test column which has the item number. But predicting in the future requires to create a future_dataframe. I have tried many times without success.
Can you please help me understand how this works to get the predictions by item ?
Thanks in advance!

**Comment by bletham** [comment]
I'm not specifically familiar with that post, but generally the future dataframe that is passed to `m.predict()` just needs to be a pandas dataframe with a column `ds` that are the dates you want predictions for. Is the question how to construct that dataframe? It would just be whatever dates you're interested in predicting.
