### ISSUE TITLE
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

### ISSUE THREAD

**Issue by sparsh-99** [facebook/prophet#1553]
import statsmodels.regression.linear_model as lm

X=np.append(arr=np.ones((50,1)).astype(int), values=X, axis=1)
X_opt=X[:,[0, 1, 2, 3, 4, 5]]
regressor_x = lm.OLS(endog=y, exog=X_opt).fit()

After executing these commands, getting this error continuously!!!

**Comment by bletham** [comment]
This issue tracker is for a different package, you'll want to ask over at statsmodels.
