### ISSUE TITLE
Install Error in R

### ISSUE THREAD

**Issue by thorswapnil7** [facebook/prophet#1555]
I have installed RTools, tried installing 'Source' version of prophet, uninstalled rstan, reinstalled rstan 2.0.

Trying to do following:

> install.packages("prophet", type = "source")

*** arch - i386
Error in .shlib_internal(args) : 
  C++14 standard requested but CXX14 is not defined
* removing 'C:/Users/Swapnil/Documents/R/win-library/3.5/prophet'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘prophet’ had non-zero exit status

Can somebody help ?

**Comment by bletham** [comment]
Sorry for the slow reply!

It seems that the C++ toolchain has not been configured and so rstan isn't working. You can verify if it is the case that rstan isn't working by running this code:
```
library(rstan)
model_code <- 'parameters {real y;} model {y ~ normal(0,1);}'
fit <- stan(model_code=model_code)  # this will take a minute
mean(extract(fit)$y)  # should be close to 0
```
Beyond that I'm not certain what is happening. Prophet ships with some compiler flags that should work (https://github.com/facebook/prophet/tree/0d260699e4776c449703a957f08eca8013461a47/R/src) but maybe they're not right for your system. Rstan has instructions on how to configure the C++ toolchain here: https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started

This issue also seems very related and the solution given by bgoodri there could work: https://github.com/stan-dev/rstanarm/issues/325
