### ISSUE TITLE
Conda-forge 0.6 is not consistent with installed code version

### ISSUE THREAD

**Issue by claudia-so** [facebook/prophet#1558]
```
(work1) claudia@x86_64-apple-darwin13 ~ %  conda list | grep fbprophet
fbprophet                 0.6              py37h4a8c4bd_0    conda-forge

(work1) claudia@x86_64-apple-darwin13 ~ % python3
Python 3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import fbprophet
ERROR:fbprophet:Importing plotly failed. Interactive plots will not work.
>>> fbprophet.__version__
'0.5'
```
Started from a fresh environment.
What am I doing wrong?

Thanks a lot

**Comment by bletham** [comment]
hm I have no idea what's happening here. The conda forge recipe directly downloads the code from pypi:
https://github.com/conda-forge/fbprophet-feedstock/blob/2e6cffe6eeefb381a39753c863bba002c17c9348/recipe/meta.yaml#L1-L14

You can look at https://pypi.org/project/fbprophet/#files and see that the hash is correct for fbprophet-0.6.tar.gz .

If you download that tar.gz, you'll see that fbprophet/__init__.py gives the version as 0.6 as expected.

The only thing I can imagine is happening here is that there is some old version of fbprophet installed on the system somewhere that is being imported. I'm not sure how that could happen in a fresh environment, but could you try uninstalling fbprophet, make sure it's uninstalled by trying to import it and seeing that it fails, and then install it again? And just to be sure could you share the command you're using to install?

Thanks, and sorry for the slow reply.
