### ISSUE TITLE
Online-learning

### ISSUE THREAD

**Issue by gireeshkbogu** [facebook/prophet#1565]
Does this model work with online/real-time/incremental learning? If yes, could you please provide some examples? thank you.

**Comment by bletham** [comment]
Not really, you do have to re-fit the model every time you get new data. There's some discussion of this in #46.

It is possible to warm-start the fitting from a previous model, which can speed things up if the amount of incremental data is small; there's an example of how to do this (and some more discussion) in https://github.com/facebook/prophet/blob/master/notebooks/additional_topics.ipynb
