### ISSUE TITLE
Can't load the library in Windows - EXTPTR_PTR could not be located in the dynamic library

### ISSUE THREAD

**Issue by drjamil96** [facebook/prophet#1571]
I install "prophet" package and everything went well, I have rtools and rstan. when I load it shows this warning and never load the package (I am using rstudio on win 10)
![image](https://user-images.githubusercontent.com/64343533/87176825-535a1a00-c2e3-11ea-9d40-413fed8399aa.png)
it shows in the console this 
`>library(prophet)
>Loading required package: Rcpp
>Loading required package: rlang
Error: package or namespace load failed for ‘prophet’ in inDL(x, as.logical(local), as.logical(now), ...):
 unable to load shared object 'C:/Users/Bravo/Documents/R/win-library/4.0/prophet/libs/x64/prophet.dll':
  LoadLibrary failure:  The specified procedure could not be found.
In addition: Warning message:
package ‘prophet’ was built under R version 4.0.2 `

I tried removing rstan and prophet
`>remove.packages("prophet")
>remove.packages("rstan")
>if (file.exists(".RData")) file.remove(".RData")
>install.packages("rstan", repos = "https://cloud.r-project.org/", dependencies = TRUE)`

I have rtools
`> pkgbuild::has_build_tools(debug = TRUE)
>[1] TRUE`

I installed prophet package again, then I load it and I have the same problem.

**Comment by bletham** [comment]
I'm not really sure, it seems that something is messed up with the build toolchain but I haven't run into this particular problem before.
Could you check if rstan is working?
```R
library(rstan)
model_code <- 'parameters {real y;} model {y ~ normal(0,1);}'
fit <- stan(model_code=model_code)  # this will take a minute
mean(extract(fit)$y)  # should be close to 0
```

Otherwise the `package ‘prophet’ was built under R version 4.0.2 ` message is a bit suspicious, and it does seem that there can be dll issues from using packages that were built under a different version of R (https://github.com/r-lib/rlang/issues/416). What version of R are you using? Maybe upgrading R so that it matches the version under which the binary was built will work. Alternatively, if rstan is working per the test above you could try installing prophet from source, like `install.packages("prophet", type="source")`.

**Comment by RyanMAllen** [comment]
I am running into a similar problem I think. I installed RTools40 and changed my path like this [link ](https://cran.r-project.org/bin/windows/Rtools/) suggested. Now I get the EXTPTR_PTR could not be located in the dynamic library error. I know that it probably has something to do with R Versions, but I either don't know how to update all my packages. I tried `update.packages(checkBuilt = TRUE) `but I still get the error.

Here are some path outputs:
Output error message from RStudio:
```
library(odbc)
Error: package or namespace load failed for ‘odbc’ in inDL(x, as.logical(local), as.logical(now), ...):
unable to load shared object 'C:/Users/Ryan.M.Allen/Documents/R/R-4.0.0/library/Rcpp/libs/x64/Rcpp.dll':
LoadLibrary failure: The specified procedure could not be found.
In addition: Warning message:
package ‘odbc’ was built under R version 4.0.2

# Path
Sys.getenv("PATH")
[1] "C:\rtools40\usr\bin;C:\Users\Ryan.M.Allen\Documents\R\R-4.0.0\bin\x64;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Plantronics\Spokes3G\;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Users\Ryan.M.Allen\AppData\Local\Microsoft\WindowsApps;"

# Rcpp.dll
Sys.which("Rcpp.dll")
Rcpp.dll
""

# libPaths
.libPaths()
[1] "C:/Users/Ryan.M.Allen/Documents/R/R-4.0.0/library"
```

I got close with this closed question: [here](https://community.rstudio.com/t/unable-to-load-shared-object-on-startup-in-rstudio-only/33107) but I wasn't sure what to do with my Rcpp.dll file and my path.

Other necessary things:
RStudio version 1.3.1056
Windows
R version 4.0.0

I did also recently upgrade to R 4.0.0 and now I also get this message when I install packages:
"Do you want to install from sources the package which needs compilation?" And I have never gotten that before.

Thank you for the help!

**Comment by bletham** [comment]
Is it possible to upgrade R to 4.0.2 maybe? Did you try re-installing the package from source and seeing if the `built under R version 4.0.2` message goes away? That's about all I can think of here.

**Comment by superOmics** [comment]
I think it relates to Rcpp package, I have the same error message when I try to load Rcpp library in R 4.0.0. , but not happened in the previous version

**Comment by Johan-VM** [comment]
I managed to solve this issue by upgrading R to the latest build: 4.0.2. It was the only solution I found since the Rcpp package apparently needs this R build to work, as you can see by calling `library(Rcpp)`.

**Comment by Johan-VM** [comment]
I managed to solve this issue by upgrading R to the latest build: 4.0.2. It was the only solution I found since the Rcpp package apparently needs `R-4.0.2`, as you can see by calling library(Rcpp).

**Comment by Johan-VM** [comment]
I managed to solve this issue by upgrading R to the latest build: 4.0.2. It was the only solution I found since the Rcpp package apparently needs R-4.0.2 to work, as you can see by calling library(Rcpp).

**Comment by Johan-VM** [comment]
I managed to solve this issue by upgrading R to the latest build: 4.0.2. It was the only solution I found since the Rcpp package apparently needs `R-4.0.2` to work, as you can see by calling `library(Rcpp).`

**Comment by Johan-VM** [comment]
I managed to solve this issue by upgrading R to the latest build: 4.0.2. It was the only solution I found since the Rcpp package apparently needs `R-4.0.2` to work, as you can see by calling `library(Rcpp)`.

**Comment by ChuliangXiao** [comment]
Upgrade to R 4.0.2 as suggested by @eddelbuettel 
https://github.com/RcppCore/Rcpp/issues/1103#issuecomment-656688585

**Comment by eddelbuettel** [comment]
For completeness, it is actually not triggered by a change in Rcpp itself --- but rather by an accidental change in R 4.0.0 and R 4.0.1 that happens to upset Rcpp.  It was reverted in R 4.0.2 (and we also also some more defence against reoccurrence in Rcpp) and indeed upgrading to R 4.0.2 is the recommended fix, as written in several GitHub issues and StackOverflow answers. 

Sorry for the bother but Rcpp is mostly a bystander here.

**Comment by chamberlinc** [comment]
I had this issue with the shiny package. Updating worked for me as well!

**Comment by brewkeeper909** [comment]
What should you do if you are interested in purposely running an older version of R (v 3.6.3) in order to maintain compatibility with packages that are no longer the same in the latest version of R? I am trying to run a script that requires the mlogit package but this package changed significantly with the upgrade to R 4.0 - so for simplicity I want to rerun my script in an older version of R. However if I switch my Rversion from 4.0.2 to 3.6.3 and try to load other packages needed in the script (e.g. lme4) - then I get this error message. Anyway to make everything run on the older versions?

**Comment by eddelbuettel** [comment]
Docker is pretty ideal for 'isolating' such run-time environments, and we provide a few such containers as part of the [Rocker Project](https://www.rocker-project.org).

**Comment by brewkeeper909** [comment]
> Docker is pretty ideal for 'isolating' such run-time environments, and we provide a few such containers as part of the [Rocker Project](https://www.rocker-project.org).

Thanks - I tried using packrat which so far seems to be working, and I am also seeing that Rstudio offers Renv - is there an advantage to any of these options, including Docker, over the others?

**Comment by Joshuariver** [comment]
I had a same problem when I have just updated 4.0.0 to 4.0.2.  In case of me, it was "Rcpp" package.  What I have done is specify R version in the Rstudio from old 4.0.0 to 4.0.2 from Tools>Global Option>General menu.  Than the annoying windows just has gone.

**Comment by red-swan** [comment]
My solution:
Close RStudio and update and install packages running R from the command line.

Worked perfectly, no hiccups.
