### ISSUE TITLE
Forecast results are different between on Mac and on Windows

### ISSUE THREAD

**Issue by hideaki** [facebook/prophet#1573]
Thank you for creating and maintaining this great package.

I tried the following example on Mac and Windows, and the results were a little different.
I was expecting the same results since the same seed was set, but is this difference expected?

Test R script:
```
library(prophet)
set.seed(1)
history <- data.frame(ds = seq(as.Date('2015-01-01'), as.Date('2016-01-01'), by = 'd'),
                      y = sin(1:366/200) + rnorm(366)/10)
m <- prophet(history)
future <- make_future_dataframe(m, periods = 365)
forecast <- predict(m, future)
forecast$yhat[1:10]
```

Mac:
```
> forecast$yhat[1:10]
 [1] 0.05220835 0.04155861 0.07203398 0.04871457 0.09769864 0.06979336 0.07490799 0.08162730 0.07097756 0.10145293
```

Windows:
```
> forecast$yhat[1:10]
 [1] 0.05139311 0.04077045 0.07125999 0.04793571 0.09694998 0.06903741 0.07416074 0.08091637 0.07029371 0.10078325
```

**Comment by elsahxh** [comment]
It is answered [here](https://github.com/facebook/prophet/issues/1536)

**Comment by hideaki** [comment]
Thank you for the quick answer!
I'm closing this since it's already discussed at the issue you pointed out.
