### ISSUE TITLE
KeyError: 'metric_file'

### ISSUE THREAD

**Issue by leiru0806** [facebook/prophet#1576]
hi，everyone, I just started learning Prophet. I'm having some problems：
here is my code, it is simple:
df = pandas.read_csv('/Users/leiru/Downloads/prophet-master/examples/example_wp_log_peyton_manning.csv')
m = Prophet()
m.fit(df)
future = m.make_future_dataframe(periods=365)
future.tail()
forecast = m.predict(future)
forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()
fig = m.plot(forecast)

and my problem is：
### 
KeyError: 'metric_file'
Exception ignored in: 'stanfit4anon_model_861b75c6337e237650a61ae58c4385ef_2627248459119768848._set_stanargs_from_dict'
KeyError: metric_file
### 
thanks

**Comment by bletham** [comment]
Sorry for the slow reply. This message is coming from inside PyStan. `metric_file` is an optional arg for Stan fitting (https://mc-stan.org/cmdstanr/reference/model-method-sample.html) that we don't use. It looks like PyStan is looking for it. But it also looks like the exception is being ignored? (`Exception ignored in:`). Where are you seeing this message? Is the model still fitting? If so then I think this is benign.

**Comment by MOvations** [comment]
FYI, had the same issue. Corrected it by updating pystan from conda-forge

conda install -c conda-forge pystan

**Comment by SunixLiu** [comment]
> FYI, had the same issue. Corrected it by updating pystan from conda-forge
> 
> conda install -c conda-forge pystan

Thanks, got same issue, resolved as you suggested.
