### ISSUE TITLE
can you package use multivariate time series when some features are  categorical  and some some features are  continues

### ISSUE THREAD

**Issue by Sandy4321** [facebook/prophet#1583]
can you package use

1
with multivariate categorical time series 
2
multivariate time series when some features are  categorical  and some some features are  continues

**Comment by bletham** [comment]
Categorical features probably won't work very well. Prophet assumes a linear model for all of the regressors, like
```
y(t) = trend(t) + seasonality(t) + beta1 * regressor1(t) + beta2 * regressor2(t) + ...
```
and I wouldn't expect a linear model to work very well for categorical features.

**Comment by Sandy4321** [comment]
correct 
but also 
https://docs.aws.amazon.com/sagemaker/latest/dg/deepar.html
suggests the same approach
if this giants like amazon and facebook (they do have unlimited amount of money )
can not solve this problem then it is problem without solution ? 
or just they can not solve it  because bureaucracy

**Comment by bletham** [comment]
The DeepAR is a very different type of model, that probably is better suited for this type of problem (multivariate, categorical features) than Prophet is but I don't have personal experience with either it or this class of problems.

**Comment by Sandy4321** [comment]
any updates , did you managed to add categorical values to data ?
