### ISSUE TITLE
RuntimeError: Exception: normal_lpdf: Location parameter[1] is -nan(ind), but must be finite!

### ISSUE THREAD

**Issue by zerualem** [facebook/prophet#1584]
I am getting the following error when I tried to use the fit method with my monthly data. This error occurs when I try to use the logistic growth, but it runs okay without it. Here is my code snippet:

```python

...
tsize=6
data['cap']=1200
data['floor']=1

df_train, df_test = data.iloc[:-tsize,:], data.iloc[-tsize:,:]
m = Prophet(yearly_seasonality=True, weekly_seasonality=False,
                daily_seasonality=False, seasonality_mode = 'additive', growth='logistic')

m.fit(df_train)

...

```

<p style='color:blue;'>

**RuntimeError                              Traceback (most recent call last)**

~\Anaconda3\lib\site-packages\fbprophet\models.py in fit(self, stan_init, stan_data, **kwargs)
    241         try:
--> 242             params = self.model.optimizing(**args)
    243         except RuntimeError:

~\Anaconda3\lib\site-packages\pystan\model.py in optimizing(self, data, seed, init, sample_file, algorithm, verbose, as_vector, **kwargs)
    549 
--> 550         ret, sample = fit._call_sampler(stan_args)
    551         pars = pystan.misc._par_vector2dict(sample['par'], m_pars, p_dims)

stanfit4anon_model_ad32c37d592cdbc572cbc332ac6d2ee2_4431954053790800620.pyx in stanfit4anon_model_ad32c37d592cdbc572cbc332ac6d2ee2_4431954053790800620.StanFit4Model._call_sampler()

stanfit4anon_model_ad32c37d592cdbc572cbc332ac6d2ee2_4431954053790800620.pyx in stanfit4anon_model_ad32c37d592cdbc572cbc332ac6d2ee2_4431954053790800620._call_sampler()

**RuntimeError: Exception: normal_lpdf: Location parameter[1] is -nan(ind), but must be finite!  (in 'unknown file name' at line 161)`**

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
 in 
    
--> 136         m.fit(df_train)
    137 
   
~\Anaconda3_64\lib\site-packages\fbprophet\forecaster.py in fit(self, df, **kwargs)
   1139             self.params = self.stan_backend.sampling(stan_init, dat, self.mcmc_samples, **kwargs)
   1140         else:
-> 1141             self.params = self.stan_backend.fit(stan_init, dat, **kwargs)
   1142 
   1143         # If no changepoints were requested, replace delta with 0s

~\Anaconda3_64\lib\site-packages\fbprophet\models.py in fit(self, stan_init, stan_data, **kwargs)
    247             )
    248             args['algorithm'] = 'Newton'
--> 249             params = self.model.optimizing(**args)
    250 
    251         for par in params:

~\Anaconda3_64\lib\site-packages\pystan\model.py in optimizing(self, data, seed, init, sample_file, algorithm, verbose, as_vector, **kwargs)
    548         stan_args = pystan.misc._get_valid_stan_args(stan_args)
    549 
--> 550         ret, sample = fit._call_sampler(stan_args)
    551         pars = pystan.misc._par_vector2dict(sample['par'], m_pars, p_dims)
    552         if not as_vector:

stanfit4anon_model_ad32c37d592cdbc572cbc332ac6d2ee2_4431954053790800620.pyx in stanfit4anon_model_ad32c37d592cdbc572cbc332ac6d2ee2_4431954053790800620.StanFit4Model._call_sampler()

stanfit4anon_model_ad32c37d592cdbc572cbc332ac6d2ee2_4431954053790800620.pyx in stanfit4anon_model_ad32c37d592cdbc572cbc332ac6d2ee2_4431954053790800620._call_sampler()

**RuntimeError: Exception: normal_lpdf: Location parameter[1] is -nan(ind), but must be finite!  (in 'unknown file name' at line 161)**

</p>

Thanks!

**Comment by bletham** [comment]
How many rows does `df_train` have? This looks like numerical issues when trying to fit the logistic trend; there's some discussion of this in #1457, which I believe to be the same issue.

You can try the Newton optimizer, which can be more robust for some problems:
```
m.fit(df_train, algorithm='Newton')
```
