### ISSUE TITLE
The list of countries with holidays is small

### ISSUE THREAD

**Issue by vin2015-edem** [facebook/prophet#1587]
The Prophet package contains [holidays countries](https://github.com/facebook/prophet/blob/master/python/fbprophet/make_holidays.py), but unfortunately, there are only 56 countries. At the same time, there are several hundred countries on the planet. Are there any plans to expand the list of these holidays? And when?

**Comment by bletham** [comment]
Most country holidays are contributed by users. If you are interested in holidays for a particular country that is not available in the package, the best thing to do would be to add them to the `holidays` package here: https://github.com/dr-prodigy/python-holidays

**Comment by vin2015-edem** [comment]
I understood your answer. Thank you.
