### ISSUE TITLE
Why lower_window in the holidays dataframe can't be greater than 0?

### ISSUE THREAD

**Issue by vin2015-edem** [facebook/prophet#1588]
The result of the influence of some events may appear with a delay. The increased activity of people during the holidays can increase the number of cases of coronavirus, but this manifests itself after a while, for example after 7 days. Why can't I set lower_window = 7 in the holidays dataframe (Prophet only negative or zero is required)?

**Comment by bletham** [comment]
That's definitely a slightly different use case. The reason the code is strict on this is to avoid confusion where someone might think that "5" means 5 days prior to the holiday, and then completely miss the holiday. I think to have a delayed response to a holiday (like 7 days in this example), I'd recommend just adding 7 days to all of the holiday dates, which shouldn't be much effort and should work well.

**Comment by vin2015-edem** [comment]
Usually, the code is written with the account of those who understand the instructions. I wouldn't be wrong. But I understood your answer. Thanks for the advice.
