### ISSUE TITLE
How to plot original values and ( predicted_original+predicted_future) on same plot using plot_plotly after log transformation?

### ISSUE THREAD

**Issue by pratikchhapolika** [facebook/prophet#1589]
I have a monthly dataset of 54 data points. I want to plot the original values along with predicted value ( Past+
Future) in the  same plot. 

**Original Data: 54 points
Predicted (6 months in future): 60 data points**

My Code:

```
df['y'] = np.log(df['y']) # log_transformed
m = Prophet(holidays=holidays)
m.fit(df)
data_forecast = m.make_future_dataframe(periods=6, freq='M')
forecast = m.predict(data_forecast)

```
`forecast [`yhat`]=np.exp(forecast [`yhat`])`

**Question1:** How to use `from fbprophet.plot import plot_plotly` to plot original and predicted after conversion using `np.exp`.

**Issue**: The model `m` is trained on log values and when we pass it to `plot_plotly(m,forecast)` it takes log values. 

What I want in plot is values in original scale?

**Comment by bletham** [comment]
The historical data is pulled from `m.history`:
https://github.com/facebook/prophet/blob/0d260699e4776c449703a957f08eca8013461a47/python/fbprophet/plot.py#L568-L574
So you could actually just overwrite it there and the plot will work:
```
m.history['y'] = np.exp(m.history['y'])
```

**Comment by pratikchhapolika** [comment]
Great. Thank you. Working perfectly. Chhers!!
