### ISSUE TITLE
Visualising Bayesian/MCMC sampling results

### ISSUE THREAD

**Issue by MaxBirdChemEng** [facebook/prophet#1590]
Hi there,

Are there any in-built functions within Prophet to visualise the traceplots/posterior distributions for each chain when mcmc sampling is enabled? Something similar to the below example:

![image](https://user-images.githubusercontent.com/56254310/87957052-af712b00-caa7-11ea-8e54-b6a534deb066.png)

If not, do you know if I could somehow access the PyStan backend model itself and use something like the [ArviZ library](https://arviz-devs.github.io/arviz/) (used by PyMC3) to generate the plots I need?

**Comment by bletham** [comment]
There isn't anything. I think directly pulling out the model and using other libraries seems like a great approach. In the current version on pip there isn't any way to access the backend PyStan model where the samples are stored, but there is in the current code on github. So if you clone and install this repository, you'll be able to access the StanModel after fitting here:
```
m.stan_backend.stan_fit
```
which is created here:
https://github.com/facebook/prophet/blob/0d260699e4776c449703a957f08eca8013461a47/python/fbprophet/models.py#L111

**Comment by MaxBirdChemEng** [comment]
@bletham Thanks for the support so far. Could you help me understand how to install the current version from Github as you mentioned? I have tried looking this up online but the popular methods (using git) do not seem to work for me.

**Comment by bletham** [comment]
First make sure fbprophet isn't installed in your environment (just to be sure things don't get mixed up with different versions), and then you would do
```
git clone https://github.com/facebook/prophet.git
```
and then cd into the `python` directory, and run
```
python setup.py install
```
except `python` here needs to be your anacdona python. I don't use anaconda myself so I'm not exactly sure how to make sure you are using it and not system python, but I'm sure there are resources about this.

Once done, if you run
```
import fbprophet
print(fbprophet.__version__)
```
you'll see `0.6.1.dev0` which will mean it worked.

**Comment by bletham** [comment]
This has been pushed to pypi as v0.7 now.
