### ISSUE TITLE
Can we incorporate both positive effect and negative effect using same mode?

### ISSUE THREAD

**Issue by pratikchhapolika** [facebook/prophet#1591]
Here is my data-set and below are the codes and output:

year_month | units
-- | --
201601 | 30,370,494
201602 | 23,128,767
201603 | 25,410,253
201604 | 26,826,307
201605 | 21,825,270
201606 | 28,211,322
201607 | 21,895,438
201608 | 24,551,601
201609 | 27,205,830
201610 | 21,869,572
201611 | 29,485,238
201612 | 26,396,388
201701 | 22,511,512
201702 | 36,054,006
201703 | 28,325,218
201704 | 19,197,459
201705 | 27,070,847
201706 | 30,226,645
201707 | 23,984,626
201708 | 21,675,483
201709 | 28,480,071
201710 | 25,585,766
201711 | 26,228,244
201712 | 26,644,348
201801 | 29,486,910
201802 | 37,092,368
201803 | 31,358,425
201804 | 31,535,269
201805 | 25,271,860
201806 | 30,888,246
201807 | 31,031,229
201808 | 21,906,370
201809 | 30,088,270
201810 | 36,409,929
201811 | 27,322,991
201812 | 24,084,698
201901 | 31,096,087
201902 | 23,125,234
201903 | 27,096,293
201904 | 24,477,446
201905 | 22,178,141
201906 | 21,524,330
201907 | 24,833,720
201908 | 21,064,357
201909 | 21,113,914
201910 | 23,996,303
201911 | 29,519,374
201912 | 18,400,599
202001 | 26,652,358
202002 | 28,674,990
202003 | 27,250,892
202004 | 17,309,074
202005 | 19,180,332
202006 | 19,093,474

![newplot](https://user-images.githubusercontent.com/11159549/88171390-dd3ba880-cc3c-11ea-9f46-e95ffd52b035.png)

The graph is in `log(units)` .

Code below:

```
holidays = pd.DataFrame({
    "holiday":"New_Year",
    "ds": pd.to_datetime(["2015-11-30","2016-11-30","2017-11-30","2018-11-30","2019-11-30","2020-11-30"]),
    "lower_window":-10,
    "upper_window":90
})
```

I see peaks every Jan, Feb so I decalre it as New Year.

```
m = Prophet(holidays=holidays)
m.fit(df)
data_forecast = m.make_future_dataframe(periods=12, freq='M')
forecast1 = m.predict(data_forecast)
```

![newplot (1)](https://user-images.githubusercontent.com/11159549/88171714-74a0fb80-cc3d-11ea-80f8-300571293dd7.png)

I see that it capture positive impact nicely.

My question are:

**Question 1:** Can we include dates in holidays to include positive and negative impacts together? Like I want to include `Covid` impact which will have negative impact extending from say `April to October, 2020`? Obviously, covid will have huge impact on units sold. How to incorporate that in mode?

**Question2:**:  Now I am coverting my `y` in `log`.  When I add extra regressor should I convert that too in `log` along with `y`. ?

**Question3**: How to find the impact or coefficient value of each regressor on the model? For example can you help me with code to get the output like this:

extra_regressor  |coefficient
-- | --
A	|			0.6
B      |                        0.3
C       |                       0.2

**Comment by pratikchhapolika** [comment]
Please help.

**Comment by bletham** [comment]
The way extra regressors are handled in the model is as linear terms:
```
y(t) = trend(t) + seasonality(t) + holiday1(t) + holiday2(t) + beta1 * regressor1(t) + beta2 * regressor(t)
```
where of course you might have more than 2 regressors and holidays. beta1 and beta2 are parameters fit by the model.

Question 1: Yes, you can have multiple holidays and they will add as described above.
Question 2: the relationship between the `y` that you pass in and the regressor is modeled as linear. So you'll want to do whichever produces the strongest linear relationship with `log(y)`. You could look at the linear correlation between `log(y)` and `regressor` or `log(regressor)`.
Question 3: The best way to see the impact of a regressor on the forecast will be to look in the forecast dataframe returned by `m.predict`. There will be a column with the name of the regressor that will be exactly the amount of `y` attributed to the regressor.
Hope that helps!

**Comment by pratikchhapolika** [comment]
Thank you for your quick reply:

If I understand you correctly then I can do someting like this:


```
holidays1 = pd.DataFrame({
    "holiday":"New_Year",
    "ds": pd.to_datetime(["2015-11-30","2016-11-30","2017-11-30","2018-11-30","2019-11-30","2020-11-30"]),
    "lower_window":-10,
    "upper_window":90
})

holidays2 = pd.DataFrame({
    "holiday":"Covid",
    "ds": pd.to_datetime(["2020-04-30"]),
    "lower_window":-10,
    "upper_window"120
})

holiday= holidays1.append(holidays2, ignore_index=True)
```


For my **Qusetion 3:**

y(t) = trend(t) + seasonality(t) + holiday1(t) + holiday2(t) + beta1 * regressor1(t) + beta2 * regressor(t)

Here holiday1 will be **"New Year"** and holiday2 will be **"Covid"**? Is that correct??

I want to get the values of **<<  beta1, beta2>>** and finally will be able to see which beta corresponds to which parameter or Alternatively, Can I print the model exactly as you mentioned above

```
print(----)
Output: y(t) = trend(t) + seasonality(t) + holiday1(t) + holiday2(t) + beta1 * regressor1(t) + beta2 * regressor(t)
```

Or, the table I meantioned above. ? How to produce that code

**Comment by avinashmatani** [comment]
holidays1 = pd.DataFrame({
    "holiday":"New_Year",
    "ds": pd.to_datetime(["2015-11-30","2016-11-30","2017-11-30","2018-11-30","2019-11-30","2020-11-30"]),
    "lower_window":-10,
    "upper_window":90
})

If I am not wrong your data is monthly and if you give holiday days something like 30 or 31 as a new year. The model won't take this because those dates are not present.

**Comment by pratikchhapolika** [comment]
@bletham  Please help.

**Comment by avinashmatani** [comment]
@pratikchhapolika .I think the parameter value for the lower window and upper window makes sense here, which is why I am wrong. Can you comment? Thanks!!

**Comment by bletham** [comment]
@pratikchhapolika  if you'd like to extract the actual coefficient values, there is discussion of this on #1487, #1264, and #1011. Note you have to correctly adjust for standardization/scaling that is done internally for both `y` and the extra regressor.

The holiday specification you're using isn't going to work well, for two reasons.

First, the new year's holiday is specified to last 100 days; this is much too long. For repeated events like New Years, you'll usually want to think about holiday effects as being a short effect on a few days at most. Effects over a 3-month window will be fully captured by yearly seasonality and so don't need to be modeled with holiday effects. In fact, defining a 3-month period as holidays will make it harder for the model to estimate yearly seasonality so you'd be much better off without it.

Second, as @avinashmatani notes, with monthly data, the only effect that matters will be on the dates of each month that are actually in the input dataframe. See the discussion here about using holidays with monthly data: https://github.com/facebook/prophet/issues/927#issuecomment-484287758 . In this case, you will not need to include new years at all as a holiday because it's effect on Jan and Feb values will be totally captured by yearly seasonality. Similarly for the COVID effect, you will be better off defining it as an effect just for the one day of each month that you actually have data.

**Comment by pratikchhapolika** [comment]
@bletham  

**<< The holiday specification you're using isn't going to work well, for two reasons.>>** 


**The model doesn't capture  any of the spikes which occurs in Jan and Feb month if I don't pass holiday effect.** 
I think the model performs much better when I pass holiday parameters spread over 100 days. I guess when **days >30**  it will eventually consider the month, since my data is monthly.   If youwant to see the plot I can upload but it performs worse without holiday.

**Comment by bletham** [comment]
OK good that that's the day with data. Then with the window > 30 it's equivalent to adding a separate holiday on `"2015-12-30","2016-12-30","2017-12-30","2018-12-30","2019-12-30","2020-12-30"`.
