### ISSUE TITLE
How to consider impact on COVID - 19 on our forecasting problem using FB-Prophet?

### ISSUE THREAD

**Issue by avinashmatani** [facebook/prophet#1595]
I am trying to forecast international students arrival in a country and I want to consider the impact of COVID -19 post-March 2020 as this is when the majority of lockdown happened in the place. Is there any way using Facebook Prophet?

**Comment by bletham** [comment]
There is some discussion of this and some ideas in #1416. Overall I think it will mess up both seasonality and trend, and I think it will depend on the time series to what extent any data prior to March 2020 will be useful at all for forecasting the next few months.
