### ISSUE TITLE
Prediction boundary is inconsistent with training

### ISSUE THREAD

**Issue by hellobigbug** [facebook/prophet#1599]
As shown in the figure, my training set is not regular, but the prediction results are very cyclical. However, the curve trend of the prediction results is far from the training data

![1595845783(1)](https://user-images.githubusercontent.com/48911801/88532656-8ddbea80-d037-11ea-8823-6094c3654b09.png)

**Comment by hellobigbug** [comment]
My personal feeling is very poor fitting, is this normal, and how to repair it

**Comment by bletham** [comment]
I think if you include the model predictions in the history (by including the history dates in the dataframe you pass to `m.predict`) you might be able to get a clearer idea of what is happening.

The model is definitely underfitting the fluctuations in the history. You can fix this by allowing more trend flexibility, as described in https://facebook.github.io/prophet/docs/trend_changepoints.html#adjusting-trend-flexibility. Something like
```
m = Prophet(changepoint_prior_scale=0.5)
```
should give better fit there.

Ultimately though I don't think you're going to be able to get a great forecast from this time series. It is only 6 months of data, which is not enough to estimate yearly seasonality so the model will just be
```
y(t) = trend(t) + weekly_seasonality(t) + noise
```
Looking at the time series, I don't see a clear weekly seasonality, and the trend seems to be fluctuating all over the place. Maybe some of these large fluctuations are seasonal, but we won't know for sure til next year. But increasing the trend flexibility as above should at least give better uncertainty estimates.
