### ISSUE TITLE
NameError: name 'forecast' is not defined

### ISSUE THREAD

**Issue by ngrannum** [facebook/prophet#1600]
Hello, after running this code (see below), I am getting this error and not sure how to proceed. Do I have to import a library or defined forecast and if so how … pls help as I am a newbie in training in Python. Additionally, I seem to run into an error always at the inverting transformation step. Can someone explain plainly how to do this with code? I know conceptually what should be done but keeping running into a wall here. Thank you. 

# inverting transformation
def invert_transformation(df_tr_diff, pred):
    forecast = pred.copy()
columns = df_train.columns
for col in columns:
    forecast[str(col)+'_pred'] = df_train[col].iloc[-1] + forecast[str(col)+'_pred'].cumsum()
return forecast
output = invert_transformation(df_tr_diff, pred)
output.loc[:, ['unscript_sales_pred']]

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-62-7633663e48a0> in <module>()
      4 columns = df_train.columns
      5 for col in columns:
----> 6     forecast[str(col)+'_pred'] = df_train[col].iloc[-1] + forecast[str(col)+'_pred'].cumsum()
      7 return forecast
      8 output = invert_transformation(df_tr_diff, pred)

NameError: name 'forecast' is not defined

**Comment by bletham** [comment]
This seems to be a generic python issue and not something specifically for this package, but it looks like `forecast` is being defined in this line:
```
def invert_transformation(df_tr_diff, pred):
    forecast = pred.copy()  # <------------- forecast defined here
    columns = df_train.columns
    for col in columns:
        forecast[str(col)+'_pred'] = df_train[col].iloc[-1] + forecast[str(col)+'_pred'].cumsum()
```
so I'm guessing something is wrong in how this function is being used so that line isn't being run.
