### ISSUE TITLE
issues loading prophet in R 4.0.2

### ISSUE THREAD

**Issue by hlydecker** [facebook/prophet#1604]
When attempting to load prophet, I get these errors:
 
```
library(prophet)
Error: package or namespace load failed for ‘prophet’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/prophet/libs/prophet.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/prophet/libs/prophet.so, 6): Library not loaded: @rpath/libtbb.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/prophet/libs/prophet.so
  Reason: image not found
```

I've checked and prophet.so and libtbb.dylib are both in the correct locations. I'm using the most recent releases of R and Rstudio on macOS 10.15.5.

Other users are also reporting this issue: https://stackoverflow.com/questions/63155946/error-loading-prophet-library-in-r-how-can-i-fix-it

**Comment by bletham** [comment]
This just came up in #1601 too. My only thought there was to try re-installing from source? `install.packages("prophet", type="source")`. Does that do anything?

**Comment by hlydecker** [comment]
@bletham that worked; numerous warnings were generated, but they seem to all be from RcppEigen and StanHeaders rather than prophet. Thanks!
