### ISSUE TITLE
Similar to "Found NaN in column" for regressors #908

### ISSUE THREAD

**Issue by ahartman1988** [facebook/prophet#1609]
I am experiencing the same issue when adding regressors to my fbprophet model but when I use the method he discovered I still receive the error. To give a better idea how the data is structured I am pulling data from a pickle that contains nearly 3M rows of data covering roughly 3 years of one hour intervals. When I am accessing the data I am pulling based on ID and a date range. 

I used `df = load_df[load_df.isna().any(axis=1)]` to find all nan values and there were none. 

I am attempting to add a weekday regressor using `load_df['WEEKDAY'] = ((pd.DatetimeIndex(load_df.index).dayofweek) // 5 == 1).astype(float)`
and/or a temperature regressor based on the temperature data in the dataframe.

**Comment by bletham** [comment]
The check that is raising this happens here:
https://github.com/facebook/prophet/blob/5accde4fb58be87087a3cca7e944a1b73f4d9346/python/fbprophet/forecaster.py#L270-L280

so I'm guessing that something is going wrong when computing the regressor, though I'm not exactly sure what - maybe trouble parsing a date? In any case, the following should identify the issue:
```
load_df['WEEKDAY'] = pd.to_numeric(load_df['WEEKDAY'])
print(load_df['WEEKDAY'].isnull().any())  # will be True if the error is being raised.
```
For temperature data, if that is being joined in from a different table then if it isn't an inner join, a missing date could be a possible source of a NaN.
