### ISSUE TITLE
conditional seasonalily

### ISSUE THREAD

**Issue by asanka-fonseka** [facebook/prophet#1610]
I get following error when trying to run the conditional seasonality example provided in the documentation.

> m <- add_seasonality(m, name='weekly_off_season', period=7, fourier.order=3, condition.name='off_season')

Error in add_seasonality(m, name = "weekly_off_season", period = 7, fourier.order = 3,  : 
  unused argument (condition.name = "off_season")

Any suggestions to fix this ? Thanks

**Comment by bletham** [comment]
I think you may be using an old version of Prophet (before that feature was added). If you do
```
library(prophet)
sessionInfo()
```
it will show the version in `other attached packages` (latest is 0.6.1).
