### ISSUE TITLE
Unable to install fbprophet on Heroku pipenv. How do I fix this?(I have installed PyStan)

### ISSUE THREAD

**Issue by mittal1787** [facebook/prophet#1611]
After installing PyStan and Cython, I tried installing fbprophet on Heroku pipenv, but got these errors:

![image](https://user-images.githubusercontent.com/33040186/89439450-d66a6680-d70f-11ea-939d-be5292877d55.png)
![image](https://user-images.githubusercontent.com/33040186/89439490-e4b88280-d70f-11ea-8480-fe79f8ade397.png)
![image](https://user-images.githubusercontent.com/33040186/89439558-fd289d00-d70f-11ea-8975-94137ff8b71a.png)
![image](https://user-images.githubusercontent.com/33040186/89439754-42e56580-d710-11ea-8647-53b7c03aef1e.png)
![image](https://user-images.githubusercontent.com/33040186/89439876-71634080-d710-11ea-95ee-b440bd314371.png)
![image](https://user-images.githubusercontent.com/33040186/89439908-7f18c600-d710-11ea-9c6c-9167c2525acb.png)
![image](https://user-images.githubusercontent.com/33040186/89439976-9952a400-d710-11ea-8820-303827509dde.png)

How do I fix these errors?

**Comment by seanjtaylor** [comment]
Can you share more information about you environment? This looks like Windows (what version?), what version of Python, PyStan, etc? Can you capture the full error log in a file and create a paste?

**Comment by mittal1787** [comment]
@seanjtaylor Hi Sean, this is a Windows 10 version. I am using using the anaconda command prompt to access Heroku and download fbprophet on the Heroku server. I first used Pipenv install PyStan to install the latest version of PyStan, and it worked fine. When I used Pipenv install fbprophet after, it gave me the installation error. I even tried pip install fbprophet and also tried putting fbprophet in a requirements.txt, but I still got an installation error.

**Comment by mittal1787** [comment]
I even tried conda install, but the error result was that "'requests' is a dependency of conda and cannot be removed from conda's operating environment"

**Comment by bletham** [comment]
Pystan is installed, but isn't working properly. You can verify this by trying to run this code:
```
import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this will take a minute
y = model.sampling(n_jobs=1).extract()['y']
y.mean()  # should be close to 0
```
The key line in your output is: `pystan:MSVC compiler is not supported` . So, the C++ compiler it is using is not supported. You can follow the directions here on getting pystan to work: https://pystan.readthedocs.io/en/latest/windows.html . In particular, you'll need to install the mingw-64 compiler in conda as described there, and then make sure pystan is installed with conda python and not system python.

**Comment by mittal1787** [comment]
@bletham @seanjtaylor I did try to install the mingw-64 compiler with conda, however, I still get the error that says, "'requests' is a dependency of conda and cannot be removed from conda's operating environment"

**Comment by bletham** [comment]
I'm not entirely sure about that error, but it seems to be something with conda. It looks like updating conda might fix it: https://github.com/conda/conda/issues/8149

**Comment by ecomohitpande** [comment]
I am getting same issue using R application while deployment in heruko
