### ISSUE TITLE
Supressing output of the Prophet model

### ISSUE THREAD

**Issue by ApurvShah007** [facebook/prophet#1616]
Has any way to suppress the output of the model been implemented. I have been using this model and it gives a large amount of output that I do not necessarily need. 

![Screen Shot 2020-08-09 at 12 18 54 AM](https://user-images.githubusercontent.com/43690373/89719927-ea46ee80-d9d5-11ea-9917-c58c4a3c902a.png)

Please let me know if anything has been implemented and I missed it or if something is in the works.

**Comment by bletham** [comment]
The output here is coming from Stan, outside of even Python. Last I checked there still wasn't a totally simple way to suppress this (there is much discussion in #223). But #223 does show how you can suppress the output by basically putting a wrapper around your code.
