### ISSUE TITLE
Pls help - problem in add_regressor for multivariate prediction

### ISSUE THREAD

**Issue by dharani-aws** [facebook/prophet#1619]
Hi all
I have two data sets . One is  1) number of requests handled by a server and 2) CPU utilization of the server . I have been able to predict both the models seperately ( uni variate ?) using fbprophet and can plot the predicted vs actual values. However I am trying to influence the model 2 , which is CPU utilization , with model 1 which is volume (multi variate ?). Because we are very sure the volume of a server causes either increase or decrease of CPU utilization % . Here is the plots of both and the pattern of volume & CPU are perfectly matching 
**Server Volume** 
![image](https://user-images.githubusercontent.com/63944988/89782367-bb508a00-db47-11ea-830e-ae3a79f5affd.png)

**CPU %**
![image](https://user-images.githubusercontent.com/63944988/89782456-e63ade00-db47-11ea-9b50-56f04a885184.png)

The original data frames of Volume & CPU are below =>
![image](https://user-images.githubusercontent.com/63944988/89782634-4598ee00-db48-11ea-81de-3cec05c12b1e.png)

![image](https://user-images.githubusercontent.com/63944988/89782709-619c8f80-db48-11ea-93ee-a4c8764d8387.png)

As I understood that in order to make prediction of CPU with _volume as an aggressor_ I need to insert the volume of df_services[y] into df_cpu[] . So I prepared a new dataframe df_cpu_regression[] with new column "volume" at column =2. 
![image](https://user-images.githubusercontent.com/63944988/89782947-b9d39180-db48-11ea-855c-ad719cb84bcd.png)

After this ,I am trying to create a new cpu model . But it throw error . Please advise me what am I missing 
Below is my code snipper =>
![image](https://user-images.githubusercontent.com/63944988/89783256-39616080-db49-11ea-9cbb-52fbce50ebba.png)

Checked that future data frame has 24 extra rows ( original number of rows 24 x 7 days = 168. With 24 hours future predicted data frame total rows are 192 ...so far good )

![image](https://user-images.githubusercontent.com/63944988/89783533-ad036d80-db49-11ea-9b40-798e0c834a8a.png)
After adding the regressor and when I run "predict" it throws an error "Aggressor volume missing from the dataframe ". I could not understand because in the df_cpu_regression dataframe I can see 3 columns  ds|y ( which is cpu) | volume...I am not sure what am I missing here ..please help me

![image](https://user-images.githubusercontent.com/63944988/89783639-dd4b0c00-db49-11ea-87c3-0effd8f04b38.png)

Regards
Dharani

**Comment by dharani-aws** [comment]
Hi @bletham  is this the same problem as reported in https://github.com/facebook/prophet/issues/49 ?
Our results of univariate prediction by fbprophet are impressive , so will continue use the same. However for multivariate approach  , is there any example , outside of fbprophet , you can share with me ?. I am pretty new to ML . 
I have two prophet models . model1 and model2. In my case model2 is influenced by model1 , in other words the patterns are very much aligned . Someone mentioned we can regress on model2 with model1 ...Could you please advise further so that I can start implementing same ...
regards
Dharani

**Comment by bletham** [comment]
The particular issue causing the error is that the regressor must also be specified in the `future_hours_cpu` dataframe. This means you must also know future values of the regressor, or have some other forecast for them. As discussed in #49, including a forecast as an extra regressor can be useful in hierarchical settings where one time series may be easier to model than another, but that isn't really the case in this time series.

**Comment by dharani-aws** [comment]
Hi @bletham sorry for late response . I am able to fix the issue by adding the forecast data frame of aggressor in future_hours_cpu frame . In fact the comparision of previous and new model is very good because RMSE value has significantly come down and the forecast values of new model is more closer to actuals now .  Thanks. P.S : I am working on another feature for which I need some advise ( more a statistical problem than fbprophet one ... I will raise another ticket welcoming your insights ) .  I will close this ticket thanks for your support . See you in my next ticket ...Cheers Dharani
