### ISSUE TITLE
Uncertainty Interval

### ISSUE THREAD

**Issue by DivJ** [facebook/prophet#1626]
I am trying to understand what does interval width represents? Can we directly relate to confidence intervals?

Also, If I want a tighter lower and upper range, should we increase the interval width or decrease?

**Comment by bletham** [comment]
Yes, it's more or less a confidence interval. The framing here is Bayesian so it's really the Bayesian equivalent of a CI, which is a credible interval of the posterior predictive distribution.

The default of 0.8 would be like an 80% CI, setting it to 0.95 would be like a 95% CI and so would widen the interval. Small values will tighter ranges. There's some discussion of this in https://facebook.github.io/prophet/docs/uncertainty_intervals.html

**Comment by DivJ** [comment]
Thanks for clarifying. I have noticed another issue with ranges. I am using interval width .80 but the ranges are very wide. The upper and lower ranges are in the ratio of 1000-10000 times of the point forecast which seems quite wide. I am doing the parameter tuning as mentioned in other issues. Does this have to do something with this as higher changepoint scale values give more uncertainty? Is there a way to make them more realistic?

**Comment by bletham** [comment]
If you can post a plot of the forecast produced by `m.plot()` I might be able to give some suggestion as to why the uncertainty is so high.
