### ISSUE TITLE
Changes outside the changepoint range still reflected in trend

### ISSUE THREAD

**Issue by Runze** [facebook/prophet#1630]
Hi, I'm running into a problem where a sudden change outside the defined `changepoint_range` still ends up reflected in the fitted trend.

To illustrate, I created this notebook [gist](https://gist.github.com/Runze/0a45ed151c76ea8b3c7a4921c7041efc) in which I created a toy time series that is all 0 except one point towards the end of the period. After setting `changepoint_range` to exclude this one outlier, I can confirm that the automatically found changepoints indeed all predate the latter. However, as shown in the diagnostic plots, the fitted trend still increases towards the end, seemingly in response to the outlier. Hence my question: if the outlier in the end is indeed excluded in changepoint detection, wouldn't the trend stay flat throughout the period?

Thank you for taking a look!

**Comment by bletham** [comment]
This is expected. The `changepoint_range` is the range of dates where the trend will be able to change, but all data are still used for fitting. So in this case the last changepoint is being used to give some positive slope to improve fit in the presence of the outlier. There are some similar looking examples in the documentation on outliers here, along with discussion: https://facebook.github.io/prophet/docs/outliers.html

**Comment by Runze** [comment]
I see. Thanks for the clarification! I misunderstood the impact of `changepoint_range`.
