### ISSUE TITLE
Running setup.py install for fbprophet ... error

### ISSUE THREAD

**Issue by TahaSha** [facebook/prophet#1632]
I have tried installing fbprophet using `pip install fbprophet` and I keep getting this error below. I really would like to resolve this issue using pip (aka not resorting to conda)

C:\Users\tahas>pip install fbprophet
Collecting fbprophet
  Using cached fbprophet-0.6.tar.gz (54 kB)
Requirement already satisfied: Cython>=0.22 in c:\users\tahas\appdata\local\programs\python\python37\lib\site-packages (from fbprophet) (0.29.21)
Requirement already satisfied: cmdstanpy==0.4 in c:\users\tahas\appdata\local\programs\python\python37\lib\site-packages (from fbprophet) (0.4.0)
Requirement already satisfied: pystan>=2.14 in c:\users\tahas\appdata\local\programs\python\python37\lib\site-packages (from fbprophet) (2.19.1.1)
Requirement already satisfied: numpy>=1.10.0 in c:\users\tahas\appdata\local\programs\python\python37\lib\site-packages (from fbprophet) (1.17.2)
Requirement already satisfied: pandas>=0.23.4 in c:\users\tahas\appdata\local\programs\python\python37\lib\site-packages (from fbprophet) (0.25.1)
Requirement already satisfied: matplotlib>=2.0.0 in c:\users\tahas\appdata\local\programs\python\python37\lib\site-packages (from fbprophet) (3.1.1)
Requirement already satisfied: LunarCalendar>=0.0.9 in c:\users\tahas\appdata\local\programs\python\python37\lib\site-packages (from fbprophet) (0.0.9)
Requirement already satisfied: convertdate>=2.1.2 in c:\users\tahas\appdata\local\programs\python\python37\lib\site-packages (from fbprophet) (2.2.1)
Requirement already satisfied: holidays>=0.9.5 in c:\users\tahas\appdata\local\programs\python\python37\lib\site-packages (from fbprophet) (0.10.3)
Requirement already satisfied: setuptools-git>=1.2 in c:\users\tahas\appdata\local\programs\python\python37\lib\site-packages (from fbprophet) (1.2)
Requirement already satisfied: python-dateutil>=2.8.0 in c:\users\tahas\appdata\local\programs\python\python37\lib\site-packages (from fbprophet) (2.8.0)
Requirement already satisfied: pytz>=2017.2 in c:\users\tahas\appdata\local\programs\python\python37\lib\site-packages (from pandas>=0.23.4->fbprophet) (2019.2)
Requirement already satisfied: cycler>=0.10 in c:\users\tahas\appdata\local\programs\python\python37\lib\site-packages (from matplotlib>=2.0.0->fbprophet) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\tahas\appdata\local\programs\python\python37\lib\site-packages (from matplotlib>=2.0.0->fbprophet) (1.1.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\tahas\appdata\local\programs\python\python37\lib\site-packages (from matplotlib>=2.0.0->fbprophet) (2.4.2)
Requirement already satisfied: ephem>=3.7.5.3 in c:\users\tahas\appdata\local\programs\python\python37\lib\site-packages (from LunarCalendar>=0.0.9->fbprophet) (3.7.7.1)
Requirement already satisfied: pymeeus<=1,>=0.3.6 in c:\users\tahas\appdata\local\programs\python\python37\lib\site-packages (from convertdate>=2.1.2->fbprophet) (0.3.7)
Requirement already satisfied: six in c:\users\tahas\appdata\local\programs\python\python37\lib\site-packages (from holidays>=0.9.5->fbprophet) (1.12.0)
Requirement already satisfied: korean_lunar_calendar in c:\users\tahas\appdata\local\programs\python\python37\lib\site-packages (from holidays>=0.9.5->fbprophet) (0.2.1)
Requirement already satisfied: setuptools in c:\users\tahas\appdata\local\programs\python\python37\lib\site-packages (from kiwisolver>=1.0.1->matplotlib>=2.0.0->fbprophet) (47.1.0)
Using legacy 'setup.py install' for fbprophet, since package 'wheel' is not installed.
Installing collected packages: fbprophet
    Running setup.py install for fbprophet ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\tahas\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tahas\\AppData\\Local\\Temp\\pip-install-9h_5u_a0\\fbprophet\\setup.py'"'"'; __file__='"'"'C:\\Users\\tahas\\AppData\\Local\\Temp\\pip-install-9h_5u_a0\\fbprophet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\tahas\AppData\Local\Temp\pip-record-gsraen55\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\tahas\appdata\local\programs\python\python37\Include\fbprophet'
         cwd: C:\Users\tahas\AppData\Local\Temp\pip-install-9h_5u_a0\fbprophet\
    Complete output (44 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\fbprophet
    creating build\lib\fbprophet\stan_model
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\tahas\AppData\Local\Temp\pip-install-9h_5u_a0\fbprophet\setup.py", line 148, in <module>
        """
      File "c:\users\tahas\appdata\local\programs\python\python37\lib\site-packages\setuptools\__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\tahas\appdata\local\programs\python\python37\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\tahas\appdata\local\programs\python\python37\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\tahas\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\tahas\appdata\local\programs\python\python37\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\tahas\appdata\local\programs\python\python37\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\tahas\appdata\local\programs\python\python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\tahas\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\tahas\appdata\local\programs\python\python37\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\tahas\appdata\local\programs\python\python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\tahas\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\tahas\AppData\Local\Temp\pip-install-9h_5u_a0\fbprophet\setup.py", line 48, in run
        build_models(target_dir)
      File "C:\Users\tahas\AppData\Local\Temp\pip-install-9h_5u_a0\fbprophet\setup.py", line 38, in build_models
        StanBackendEnum.get_backend_class(backend).build_model(target_dir, MODEL_DIR)
      File "C:\Users\tahas\AppData\Local\Temp\pip-install-9h_5u_a0\fbprophet\fbprophet\models.py", line 206, in build_model
        import pystan
      File "c:\users\tahas\appdata\local\programs\python\python37\lib\site-packages\pystan\__init__.py", line 9, in <module>
        from pystan.api import stanc, stan
      File "c:\users\tahas\appdata\local\programs\python\python37\lib\site-packages\pystan\api.py", line 13, in <module>
        import pystan._api  # stanc wrapper
    ImportError: DLL load failed: The specified module could not be found.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\tahas\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tahas\\AppData\\Local\\Temp\\pip-install-9h_5u_a0\\fbprophet\\setup.py'"'"'; __file__='"'"'C:\\Users\\tahas\\AppData\\Local\\Temp\\pip-install-9h_5u_a0\\fbprophet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\tahas\AppData\Local\Temp\pip-record-gsraen55\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\tahas\appdata\local\programs\python\python37\Include\fbprophet' Check the logs for full command output.

**Comment by juniorspqr** [comment]
Same With Bletham answer, I havent succeed to solve this error on other bash. 

Normally , to solve this, you need to change your pip conpilateur default . Instead of VS,  you need to have gcc. But even if you will do this way, for me , it has not work ... 
So I have use anaconda and this error don't appear again... (but some other errors appear so keep pattience and progress)
Junior

**Comment by TahaSha** [comment]
> It looks like things are failing while compiling the stan model, which usually indicates the C++ toolchain is not configured as needed by Stan. You can run this code to verify if pystan is working:
> 
> ```python
> import pystan
> model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
> model = pystan.StanModel(model_code=model_code)  # this will take a minute
> y = model.sampling(n_jobs=1).extract()['y']
> y.mean()  # should be close to 0
> ```
> 
> Pystan has some directions on how to get it working in windows: https://pystan.readthedocs.io/en/latest/windows.html
> 
> I will note that I have never personally been successful in getting pystan to work outside of Anaconda (which ships with its own C++ toolchain), so I'd recommend following that route in the directions.

I appreciate your help. I've resorted to using google.colab instead of my local machine. Thank you again.
