### ISSUE TITLE
Prophet getting weekly component incorrect

### ISSUE THREAD

**Issue by raffg** [facebook/prophet#1633]
I created a very simple dataset consisting of a linear trendline with a small variation added for each day of the week and a sinusoidal variation for hour of day. When Facebook Prophet creates a component plot, it correctly gets the trend and daily variation, but incorrectly displays the weekly variation. It seems it is shifted a day, however the values still don't line up exactly. See these two images.

The first is the mock data I created:

![mock_data](https://user-images.githubusercontent.com/20135094/90920721-a83a8700-e39d-11ea-93fa-12fac1571464.png)

The second is the components plot from Prophet:

![prophet](https://user-images.githubusercontent.com/20135094/90920747-b38db280-e39d-11ea-8ea8-56b6cb83bbe7.png)

In the data I supplied, Saturday has the highest value but in Prophet's estimation, Sunday has the highest. Also, Monday and Tuesday should be the same. What is happening here? I'll also note that if I remove the sinusoidal daily component and set `freq='D'`, Prophet gets the weekly component correct.

Code to reproduce:

```
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from fbprophet import Prophet

week_variation = {'Monday': -5,
                  'Tuesday': -5,
                  'Wednesday': -4,
                  'Thursday': -3,
                  'Friday': 0,
                  'Saturday': 5,
                  'Sunday': 2}

x = pd.date_range('2000-01-01', '2001-01-01', freq='H')
y0 = [1000 + .025 * val for val in range(len(x))]  # create trend curve
y1 = [week_variation[date.day_name()] for date in x]  # add weekly variation
y2 = [10 * np.sin((idx - 6) * (360 / 24) * (np.pi / 180)) for idx in range(len(x))]  # add daily sinusoidal variation

fig, axis = plt.subplots(3, 1, figsize=(10, 10))
plt.subplots_adjust(hspace=.5)

axis[0].set_title('Trend Component')
axis[0].plot(x, y0)
axis[0].set_xlabel('Date')

axis[1].set_title('Weekly Component')
axis[1].plot(x.day_name()[24: 24 * 8], y1[24: 24 * 8])
axis[1].set_xlabel('Day')

axis[2].set_title('Daily Component')
axis[2].plot(x[:24].strftime('%#H'), y2[:24])
axis[2].set_xlabel('Hour')

plt.show()

df = pd.DataFrame({'ds': x, 'y': [y0[idx] + y1[idx] + y2[idx] for idx in range(len(x))]})

prophet = Prophet()
prophet.fit(df)
future = prophet.make_future_dataframe(periods=30 * 24, freq='H')
forecast = prophet.predict(future)
fig = prophet.plot_components(forecast)
plt.show()
```

**Comment by bletham** [comment]
The release will hopefully be today :-) Just trying to work out some R build issues.

And thanks for the offer for help. I've recently been trying to flag issues that I think are good first issues with that label (https://github.com/facebook/prophet/labels/good%20first%20issue) but the list is a bit short :-) We also just finished cleaning up most of the outstanding minor issues in preparation for the new release.

There is some work on the R side that needs to be done that I think could be straightforward for someone with enough R experience; #1557 and #1501 are the two main ones. On the Py side, #1405 is perhaps the main feature that would be nice to wrap up for the next version, but it got surprisingly hairy on the Stan side. So if you have any Stan experience and can see a better approach there that would be really helpful!

**Comment by raffg** [comment]
Unfortunately, my R and Stan experience is pretty limited. I'll keep an eye on the `good first issue` label though!
