### ISSUE TITLE
How to use more features on fbprophet?

### ISSUE THREAD

**Issue by fkhjoy** [facebook/prophet#1642]
I want to train my model with more features along Timestamp.
Is there any way to include other features too?
I searched a lot and failed to find out.

**Comment by benmwhite** [comment]
This is in the official documentation webpage [here.](https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#additional-regressors)

**Comment by fkhjoy** [comment]
I thought it's only for adding Holidays.
Is it forecasting all columns?

**Comment by fkhjoy** [comment]
> This is in the official documentation webpage [here.](https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#additional-regressors)

I thought it's only for adding Holidays.
So, I can just add and feed those columns?
So, is it forecasting all columns too?

**Comment by benmwhite** [comment]
>So, is it forecasting all columns too?

No, the model is only built for predicting a single time series. You'd need future values for separate projections for each additional feature you include.
