### ISSUE TITLE
Prophet plots data (black points) that don't exist

### ISSUE THREAD

**Issue by tani-a** [facebook/prophet#1644]
Dear all,

I'm using Prophet to analyse data and I find it really interesting but I'm getting a strange issue. When doing a plot the algorithm show you, by default, the actual data identified by black points and the blue line forecast. However, I noticed that it jumps some data of my dataframe (black points) and invent other ones that don't exist!!! Does someone know how is it possible?

Thanks

**Comment by tani-a** [comment]
It seems this happens with non-daily data.  I used the dataframe from:

https://finance.yahoo.com/quote/%5EGSPC/history?period1=1503532800&period2=1598227200&interval=1d&filter=history&frequency=1d&_guc_consent_skip=1599039570

how to solve it?

**Comment by bletham** [comment]
I'm not quite sure what might be happening here. Could you past the head of the the dataframe being passed in to `m.fit`?

For a fitted model `m`m, the points used for the plotting are `m.history['ds']` vs. `m.history['y']`. These should be exactly the same as the dataframe passed in to `m.fit`, except any points with NaN for y will be dropped. Are these the same?

**Comment by tani-a** [comment]
Thank you very much for your answer. I checked and the answer is NO! My dataframe (df) and the points passed to m.fit are completely different!

Here df.head()
	ds	                 y
0	24/08/2017	2438.969971
1	25/08/2017	2443.050049
2	28/08/2017	2444.239990
3	29/08/2017	2446.300049
4	30/08/2017	2457.590088

Here m.history[['ds', 'y']].head()
ds                y
2017-01-09 | 2476.550049
2017-01-11 | 2579.360107
2017-01-12 | 2642.219971
2017-02-10 | 2529.120117
2017-02-11 | 2579.850098

**Comment by bletham** [comment]
Here is basically how `m.history` is computed from `df`:
```
history = df.copy()
history['ds'] = pd.to_datetime(history['ds'])
history = history.sort_values('ds')
```

I think if you run those commands on `df`, you should see the result is the same as `m.history`. I'm guessing that some of the dates are not being parsed correctly by pandas. If you do
```
df['ds'] = pd.to_datetime(df['ds'])
```
are the dates correct? If not, then you'll want to convert them to correct datetimes before passing it into Prophet. The pandas documentation here shows how you can tell `pd.to_datetime` how to properly parse the dates: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html

That's about the only thing I can imagine is happening here, but if that's not the case then let me know what other differences you see between `history` as created above and `m.history`.

**Comment by tani-a** [comment]
Thanks a lot. I solved the problem by doing:

history['ds'] = pd.to_datetime(history['ds'], dayfirst = True).
