### ISSUE TITLE
Adding constraints to additional regressors

### ISSUE THREAD

**Issue by sld42** [facebook/prophet#1645]
I've got a few features I'm adding to my model that I know should be positively correlated with my forecast, but when I plot the feature and the additive component together, I see that there's a negative correlation. Is there anyway I can tell prophet "These features will me positively correlated with `y` and these features will be negatively correlated with `y`?"

**Comment by abelpd** [comment]
I'm new to TS and Prophet, but I think in general you would never want that for it to function properly (and to be able to diagnose issues with the inputs).

Sounds like there is an externality impacting it.
Maybe check for multicollinearity between all of your variables?

**Comment by sld42** [comment]
Maybe some more context would help: 
This is a marketing problem, where my additional regressors are 3 different types of marketing spend `[A, B, C]`, and my `y` is how many new customers I will acquire. 

I'm noticing that for some of the marketing regressors, there's a negative correlation between the amount I spend on marketing, and the number of customers I acquire. In other instances, I see there are some chunks of time where a marketing regressor will contribute a negative contribution to `yhat`. I know none of these relationships can occur in real life, which makes me doubt my model results, even though the model has decent accuracy. 

I agree that forcing correlation is weird, but is externality the only justification for this? I checked multicolinearity and prophet scales your feature data by default so it's not that. 

Also more generally, is there a way to add constraints to additional regressors? I feel like a nonnegative constraint like in nonnegative matrix factorization would be really helpful in this problem

**Comment by bletham** [comment]
There's a lot of discussion of this in #1405. As described there, you can do MCMC and hopefully the distribution covers 0, but otherwise there isn't really an easy way to force positivity for now. This is a feature that I think would be good to add, but doing it in the Stan model got a bit hairier than I expected in #1405 so there is still some effort to be done...
