### ISSUE TITLE
Is there way to tune prior scale of weekly and yearly seasonalities separately during cross validation?

### ISSUE THREAD

**Issue by bhargavreddy111** [facebook/prophet#1647]
Hi,
I would like to know if I can do Hyperparameter tuning for prior scale of weekly and yearly seasonalities separately? I am aware that I can specify custom seasonalities and give prior scale separately, but I would like to know if there is a way to tune them by cross validation.

at the moment, I can set different values for seasonality_prior _scale and perform cross validation to get the best value, but here the problem is the same value applies for both weekly seasonality and yearly seasonality prior scale. 

Pls let me know if there is way around for this issue.

**Comment by benmwhite** [comment]
You can [specify the seasonalities manually](https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#specifying-custom-seasonalities), this way you can use different prior scale parameters.

**Comment by bhargavreddy111** [comment]
Hi Ben,
My problem is bit different, its w.r.t tuning via cross validation. when I do grid search I am able to specify one seasonality prior scale like below which applies for both weekly and yearly seasonalities:
   param_grid = {'changepoint_prior_scale': [0.3,1, 3, 10],'seasonality_prior_scale': [0.1, 1, 5, 10.0]}
    
    #'changepoint_prior_scale': [0.05, 0.1, 0.3, 0.5, 0.7, 1, 3, 5,10]
    # Generate all combinations of parameters
    all_params = [dict(zip(param_grid.keys(), v)) for v in itertools.product(*param_grid.values())]
    rmses = []  # Store the RMSEs for each params here
    for params in all_params:
        model_try=Prophet(weekly_seasonality=True, yearly_seasonality=True, daily_seasonality=False,
                          changepoints=['2020-05-05'], **params)


What I would like to see is if there is a way to have tuning done for weekly seasonality and yearly seasonality prior scale separately from grid search.
