### ISSUE TITLE
get values from plot_component

### ISSUE THREAD

**Issue by akmalsabri** [facebook/prophet#1648]
Hi, how to get the values from plot component ?

For example yearly component.

**Comment by bletham** [comment]
These are all columns in the forecast dataframe returned by `m.predict()`.
```
forecast = m.predict(future)
print(forecast.head())
print(forecast['yearly'])  # This is the yearly component
```

**Comment by akmalsabri** [comment]
Thanks, actually I want to plot the yearly component but not using matplotlib. Now, I understand that yearly values are from forecast dataframe right? But not sure about the x-axis.
Maybe I need to create new function, try to understand the original code right?

https://github.com/facebook/prophet/blob/master/python/fbprophet/plot.py

**Comment by akmalsabri** [comment]
from this forum https://stackoverflow.com/questions/47946518/python-fbprophet-export-values-from-plot-components-for-yearly , is that correct the yearly plot are last year plot from forecast datafrmae?

**Comment by bletham** [comment]
The way this is done in the components plot is to generate a dataframe with 1-year daily sequence of dates and then predict the seasonal components on that:
https://github.com/facebook/prophet/blob/77da5b8c06d05d478af510198c685d454342db1f/python/fbprophet/plot.py#L339-L341
