### ISSUE TITLE
Update error message: Dataframe has no rows

### ISSUE THREAD

**Issue by Jakobhenningjensen** [facebook/prophet#1650]
I am trying to create a CV using leave-one-out i.e predicting the next rolling day in my test-data.

I have a train data `X_train` and test data `X_test`, and fitting a model using

```python

model.fit(pd.concat((X_train,X_test)))

from fbprophet.diagnostics import cross_validation
cutoffs = X_test["ds"].values
df_cv = cross_validation(model,cutoffs=cutoffs,horizon = '1 day')
```

the last part throws the error
```
----> 90 df_cv = cross_validation(model,cutoffs=cutoffs,horizon = '1 day')

~\AppData\Local\Programs\Python\Python37\lib\site-packages\fbprophet\diagnostics.py in cross_validation(model, horizon, period, initial, parallel, cutoffs)
    187         predicts = [
    188             single_cutoff_forecast(df, model, cutoff, horizon, predict_columns)
--> 189             for cutoff in tqdm(cutoffs)
    190         ]
    191 

~\AppData\Local\Programs\Python\Python37\lib\site-packages\fbprophet\diagnostics.py in (.0)
    187         predicts = [
    188             single_cutoff_forecast(df, model, cutoff, horizon, predict_columns)
--> 189             for cutoff in tqdm(cutoffs)
    190         ]
    191 

~\AppData\Local\Programs\Python\Python37\lib\site-packages\fbprophet\diagnostics.py in single_cutoff_forecast(df, model, cutoff, horizon, predict_columns)
    239         for props in m.seasonalities.values()
    240         if props['condition_name'] is not None])
--> 241     yhat = m.predict(df[index_predicted][columns])
    242     # Merge yhat(predicts), y(df, original data) and cutoff
    243 

~\AppData\Local\Programs\Python\Python37\lib\site-packages\fbprophet\forecaster.py in predict(self, df)
   1196         else:
   1197             if df.shape[0] == 0:
-> 1198                 raise ValueError('Dataframe has no rows.')
   1199             df = self.setup_dataframe(df.copy())
   1200 

ValueError: Dataframe has no rows.
```

The code of mine might be wrong for the CV part (I'm new to using fbprophet), but it is really difficult to debug anything with this error - which dataframe has no rows?

**Comment by bletham** [comment]
Thanks for raising this. The issue is that the last cutoff is the final point in the history, and so does not leave the required 1 day horizon left for cross validation. Here is some other code for replicating the issue:
```Python
from fbprophet import Prophet
from fbprophet.diagnostics import cross_validation

m = Prophet()
m.fit(df)
cutoffs = pd.to_datetime(df['ds'].tail(3).values)
df_cv = cross_validation(m,cutoffs=cutoffs,horizon = '1 day')
```

We should add validation of the cutoff to make sure that the min cutoff is strictly greater than the min date in the history, and the max value is <= (end date minus horizon). That validation should go inside this else clause here:
https://github.com/facebook/prophet/blob/77da5b8c06d05d478af510198c685d454342db1f/python/fbprophet/diagnostics.py#L141
and should raise an error with a meaningful message if the cutoffs are not as required.

In the meantime, the workaround on getting this error is to make sure the cutoffs satisfy those requirements (first is after the earliest date in the history, last leaves at least horizon time left). For instance, this adjustment to the code above works (just drop the last cutoff that didn't leave enough days left):
```Python
cutoffs = cutoffs[:-1]
df_cv = cross_validation(m,cutoffs=cutoffs,horizon = '1 day')
```

**Comment by bletham** [comment]
The R version has the same issue, and the fix would go in the equivalent place:
https://github.com/facebook/prophet/blob/77da5b8c06d05d478af510198c685d454342db1f/R/R/diagnostics.R#L107

**Comment by Jakobhenningjensen** [comment]
That is naturally true (I did not think of that) - but I agree, a more usefull error would be a good idea to raise.

**Comment by bletham** [comment]
This is done for R in  4e99ac6

**Comment by bletham** [comment]
This has been pushed to CRAN and pypi in the latest v1.0 release.

**Comment by godoyjulia** [comment]
> @bletham I'm having the same error as @Jakobhenningjensen but I already made sure that:
> 
> 1. min_cutoff > min_date
> 2. max_cutoff <= (max_date- horizon)
> 
> Could there be any other reason as to why this error keeps appearing?
> 
> For some context, I'm trying to run a cross-validation analysis for a model trained on monthly data. The time series the model was trained on is made up of 21 data points stored in a pandas data-frame called "data" with columns "ds" and "y". The "ds" column could be reproduced as:
> 
> `data["ds"] = pd.date_range(start='2020-01-31', end='2021-09-30', freq='M')`
> 
> The "y" column I figure is not so relevant, but just know that its composed of both positive and negative integer data (I can provided it though, if you consider it could be of any help). The cutoffs, meanwhile, are generated according to the following code:
> 
> ```
> cutoffs = pd.date_range(start=data.loc[10, 'ds'], end=data.loc[19, 'ds'], freq='M')
> ```
> 
> And the I've tried different settings for the cross-validation such as:
> 
> ```
> cv_df = cross_validation(model,  cutoffs=cutoffs, horizon ="20 days")
> ```
> 
> and
> 
> ```
> cv_df = cross_validation(model, cutoffs=cutoffs, horizon ="1 M")
> ```
> 
> But both of them give the same error:
> 
> ```
>    cv_df = cross_validation(model,
> 
>   File "C:\Users\andre\anaconda3\lib\site-packages\prophet\diagnostics.py", line 196, in cross_validation
>     predicts = [
> 
>   File "C:\Users\andre\anaconda3\lib\site-packages\prophet\diagnostics.py", line 197, in <listcomp>
>     single_cutoff_forecast(df, model, cutoff, horizon, predict_columns)
> 
>   File "C:\Users\andre\anaconda3\lib\site-packages\prophet\diagnostics.py", line 250, in single_cutoff_forecast
>     yhat = m.predict(df[index_predicted][columns])
> 
>   File "C:\Users\andre\anaconda3\lib\site-packages\prophet\forecaster.py", line 1204, in predict
>     raise ValueError('Dataframe has no rows.')
> 
> ValueError: Dataframe has no rows.
> ```
> 
> The only thing that works for the cross-validation process is:
> 
> ```
> cv_df = cross_validation(model, periods="1 M", horizon ="1 M")
> ```
> 
> But I would much rather be able to specify the cutoffs myself, specially since `periods="1 M"` will eventually be deprecated. (Actually, because of this same reason, I think that being able to also specify the horizon at each step would constitute a great add-on). But I'm lost and there doesn't seem to be many other info on this specific topic. Any help with very much be appreciated.

Were you @Mastercol01 able to fix this? I'm having the same trouble in R

**Comment by gabrieltomasin** [comment]
> > @bletham I'm having the same error as @Jakobhenningjensen but I already made sure that:
> > 
> > 1. min_cutoff > min_date
> > 2. max_cutoff <= (max_date- horizon)
> > 
> > Could there be any other reason as to why this error keeps appearing?
> > For some context, I'm trying to run a cross-validation analysis for a model trained on monthly data. The time series the model was trained on is made up of 21 data points stored in a pandas data-frame called "data" with columns "ds" and "y". The "ds" column could be reproduced as:
> > `data["ds"] = pd.date_range(start='2020-01-31', end='2021-09-30', freq='M')`
> > The "y" column I figure is not so relevant, but just know that its composed of both positive and negative integer data (I can provided it though, if you consider it could be of any help). The cutoffs, meanwhile, are generated according to the following code:
> > ```
> > cutoffs = pd.date_range(start=data.loc[10, 'ds'], end=data.loc[19, 'ds'], freq='M')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And the I've tried different settings for the cross-validation such as:
> > ```
> > cv_df = cross_validation(model,  cutoffs=cutoffs, horizon ="20 days")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and
> > ```
> > cv_df = cross_validation(model, cutoffs=cutoffs, horizon ="1 M")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But both of them give the same error:
> > ```
> >    cv_df = cross_validation(model,
> > 
> >   File "C:\Users\andre\anaconda3\lib\site-packages\prophet\diagnostics.py", line 196, in cross_validation
> >     predicts = [
> > 
> >   File "C:\Users\andre\anaconda3\lib\site-packages\prophet\diagnostics.py", line 197, in <listcomp>
> >     single_cutoff_forecast(df, model, cutoff, horizon, predict_columns)
> > 
> >   File "C:\Users\andre\anaconda3\lib\site-packages\prophet\diagnostics.py", line 250, in single_cutoff_forecast
> >     yhat = m.predict(df[index_predicted][columns])
> > 
> >   File "C:\Users\andre\anaconda3\lib\site-packages\prophet\forecaster.py", line 1204, in predict
> >     raise ValueError('Dataframe has no rows.')
> > 
> > ValueError: Dataframe has no rows.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The only thing that works for the cross-validation process is:
> > ```
> > cv_df = cross_validation(model, periods="1 M", horizon ="1 M")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But I would much rather be able to specify the cutoffs myself, specially since `periods="1 M"` will eventually be deprecated. (Actually, because of this same reason, I think that being able to also specify the horizon at each step would constitute a great add-on). But I'm lost and there doesn't seem to be many other info on this specific topic. Any help with very much be appreciated.
> 
> Were you @Mastercol01 able to fix this? I'm having the same trouble in R

I'm having the same issue in python, my DataFrame has some NaN values, but not at the tail, so I don't think this is causing the problem.

**Comment by godoyjulia** [comment]
> > @bletham I'm having the same error as @Jakobhenningjensen but I already made sure that:
> > 
> > 1. min_cutoff > min_date
> > 2. max_cutoff <= (max_date- horizon)
> > 
> > Could there be any other reason as to why this error keeps appearing?
> > For some context, I'm trying to run a cross-validation analysis for a model trained on monthly data. The time series the model was trained on is made up of 21 data points stored in a pandas data-frame called "data" with columns "ds" and "y". The "ds" column could be reproduced as:
> > `data["ds"] = pd.date_range(start='2020-01-31', end='2021-09-30', freq='M')`
> > The "y" column I figure is not so relevant, but just know that its composed of both positive and negative integer data (I can provided it though, if you consider it could be of any help). The cutoffs, meanwhile, are generated according to the following code:
> > ```
> > cutoffs = pd.date_range(start=data.loc[10, 'ds'], end=data.loc[19, 'ds'], freq='M')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And the I've tried different settings for the cross-validation such as:
> > ```
> > cv_df = cross_validation(model,  cutoffs=cutoffs, horizon ="20 days")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and
> > ```
> > cv_df = cross_validation(model, cutoffs=cutoffs, horizon ="1 M")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But both of them give the same error:
> > ```
> >    cv_df = cross_validation(model,
> > 
> >   File "C:\Users\andre\anaconda3\lib\site-packages\prophet\diagnostics.py", line 196, in cross_validation
> >     predicts = [
> > 
> >   File "C:\Users\andre\anaconda3\lib\site-packages\prophet\diagnostics.py", line 197, in <listcomp>
> >     single_cutoff_forecast(df, model, cutoff, horizon, predict_columns)
> > 
> >   File "C:\Users\andre\anaconda3\lib\site-packages\prophet\diagnostics.py", line 250, in single_cutoff_forecast
> >     yhat = m.predict(df[index_predicted][columns])
> > 
> >   File "C:\Users\andre\anaconda3\lib\site-packages\prophet\forecaster.py", line 1204, in predict
> >     raise ValueError('Dataframe has no rows.')
> > 
> > ValueError: Dataframe has no rows.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The only thing that works for the cross-validation process is:
> > ```
> > cv_df = cross_validation(model, periods="1 M", horizon ="1 M")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But I would much rather be able to specify the cutoffs myself, specially since `periods="1 M"` will eventually be deprecated. (Actually, because of this same reason, I think that being able to also specify the horizon at each step would constitute a great add-on). But I'm lost and there doesn't seem to be many other info on this specific topic. Any help with very much be appreciated.
> 
> Were you @Mastercol01 able to fix this? I'm having the same trouble in R

**Solution:**
The way i was creating cutoffs it was always the first day of the month. So cross validation was trying to find registers that started after day 01-january and ended before 01-january... therefore no rows
Cutoff has to be the last day of the month.
In R, simply subtract 1 day:
`cutoffs <-  seq(as.Date('2013-01-01'), as.Date('2022-07-01'), by="month") -1`
`df_cv <- cross_validation(m, cutoffs = c(as.Date("2020-01-01"))-1, horizon=1, units='months')`
