### ISSUE TITLE
Holiday vs regressor

### ISSUE THREAD

**Issue by JakobHenning** [facebook/prophet#1651]
Say I want to model the number of sales in a store and I want to include Black Friday as variable. 

Does it matter if I use it as holiday or as regressor or would the coefficients/benefit be the same?

**Comment by bletham** [comment]
Under the hood, specifying a holiday with a set of dates is equivalent to adding a binary regressor that is 1 on those dates and 0 otherwise. Is that what you wanted to know?

**Comment by JakobHenning** [comment]
That was my thoughts as well, but it makes a huge (!) difference if I add them as holidays or as a binary regressor

**Comment by bletham** [comment]
Could you post the components plot `m.plot_components(fcst)` under each model and perhaps the code you're using? I'm wondering if you're running into #1617 which was a bug where pandas 1.1.0 had a not-backwards-compatible change that broke holidays in fbprophet v0.6, and you need to upgrade fbprophet to v0.7.1 to get the fix.
