### ISSUE TITLE
refitting already fitted model

### ISSUE THREAD

**Issue by xalekx** [facebook/prophet#1652]
I have declared and fitted a model with the following code..

```
model = Prophet(weekly_seasonality=True,daily_seasonality=True,changepoint_prior_scale=0.06,
                holidays=df_holidays)
model.add_regressor('f1')
model.add_regressor('f2')
model.add_regressor('f3')

```

The use case i have to is try to refit the data every week. Fitting this model from start to end takes 10-15 minutes due to the size of the dataset. To speed up the fit process i have read the issues on github and also the https://facebook.github.io/prophet/docs/additional_topics.html#flat-trend-and-custom-trends documentation.

Only proposed  solution i have found is initializing a new model and refitting with the kwargs init and some sort of function like:

> def stan_init(m):
>     """Retrieve parameters from a trained model.
>     
>     Retrieve parameters from a trained model in the format
>     used to initialize a new Stan model.
>     
>     Parameters
>     ----------
>     m: A trained model of the Prophet class.
>     
>     Returns
>     -------
>     A Dictionary containing retrieved parameters of m.
>     
>     """
>     res = {}
>     for pname in ['k', 'm', 'sigma_obs']:
>         res[pname] = m.params[pname][0][0]
>     for pname in ['delta', 'beta']:
>         res[pname] = m.params[pname][0]
>     return res
> 

But whenever i try to use this function to refit a new model the following error pops up:

_**mismatch in dimension declared and found in context; processing stage=parameter initialization; variable name=beta; position=0; dims declared=(20); dims found=(40)**_

The delta parameter is passing through just fine and beta is 2x the size of the dimensions found. No matter what i change the same exact length of dims found(40) stays.

**Comment by bletham** [comment]
`beta` is the parameters used for seasonalities, holidays, and extra regressors. When you initialize the 2nd model (`m2` in the documentation example), are you using all of the same model kwargs? So like
```Python
m2 = Prophet(weekly_seasonality=True,daily_seasonality=True,changepoint_prior_scale=0.06,
                holidays=df_holidays)
m2.add_regressor('f1')
m2.add_regressor('f2')
m2.add_regressor('f3')
m2.fit(df, init=stan_init(m1))
```
It seems like the second model is missing some seasonalities/holidays/regressors that are found in the first.
