### ISSUE TITLE
How can I use prophet model for early warning or anomaly detection that may happen in future?

### ISSUE THREAD

**Issue by pratikchhapolika** [facebook/prophet#1657]
I have monthly data and converted my `y to log(y) `with some extra regressors to use prophet model.  I have `60` data points from `201601 till 202008`. 

Here is my mode:

```
holidays = pd.DataFrame({
        "holiday":"New_Year",
        "ds": pd.to_datetime(["2015-11-30","2016-11-30","2017-11-30","2018-11-30","2019-11-30","2020-11-30"]),
        "lower_window":-15,
        "upper_window":90
    })
m = Prophet(interval_width=0.95,holidays=holidays)

for c in cols:
        m.add_regressor(c)

m.fit(data)
train_forecast = m.predict(data)
```

**Question:** : I train and test on same data as I have just 60 points.  Is this a right way? Will there be any bias in my `MAPE `?

**Now coming to important question, I want to flag off any outlier/anaomaly as an early waring in future months ( 6 months of forecast let's say)**

**Current Approach**: I take `mean` and `standard deviation` of `yhat ` and then draw  `1std, 2std and 3std` lines on those 60 data points. And whatever falls beyond `3std`, I flag it as early warning.  Is this the right way?

**Question 2:**:  Since I have taken `interval_width=0.95`, so will my prediction for future data always fall inside `3 std.deviation` 
                         of predicted values?  In that case I will never get anomaly.

**Question3:**:  Any other suggestion to improve on Current approach?

**Comment by bletham** [comment]
Yes, evaluating MAPE on the training set will be biased down since it is measuring training error, but the thing you care about is probably test error.

I think you can use `yhat_upper` as a first-pass approach for anomaly detection, and as you note can set `interval_width` to correspond to whatever you think the appropriate definition of an anomaly is. At 0.95, approximately 5/100 points will be flagged as an anomaly even if they are consistent with the underlying model.

There is some discussion of anomaly detection in #595 and #1518 that I think will be helpful.

**Comment by pratikchhapolika** [comment]
> Yes, evaluating MAPE on the training set will be biased down since it is measuring training error, but the thing you care about is probably test error.
> 
> I think you can use `yhat_upper` as a first-pass approach for anomaly detection, and as you note can set `interval_width` to correspond to whatever you think the appropriate definition of an anomaly is. At 0.95, approximately 5/100 points will be flagged as an anomaly even if they are consistent with the underlying model.
> 
> There is some discussion of anomaly detection in #595 and #1518 that I think will be helpful.

I didn't understand your point << **I think you can use yhat_upper as a first-pass approach for anomaly detection**>>. In my prediction I get yhat_upper/yhat_lower for every month.  Now supposedly, I predict for next 6 months  how can I say it's an anomaly based on previous yhat_upper's. I don't have 1 yhat_upper but #yhat_upper=training samples?

**Comment by bletham** [comment]
I'd recommend taking a look at https://towardsdatascience.com/anomaly-detection-time-series-4c661f6f165f . I don't have any personal experience with anomaly detection so won't be able to give very concrete advice. Generally, I can imagine doing this either with in-sample y_hat (so, update the model once the point comes in and then flag it) or out-of-sample (predict for next month, and when next month's point comes in compare it to the prediction from last month). I think it depends a lot on what type of anomaly you're trying to flag.
