### ISSUE TITLE
How to remove weekends (Saturdays and Sundays) in the "weekly" component in "plot_components" method of prophet (in python).

### ISSUE THREAD

**Issue by yashveersinghsohi** [facebook/prophet#1658]
I am working on a project where I have S&P 500 stock data available for each business day (Monday to Friday) from 1994-2019.
[click here for the data](https://docs.google.com/spreadsheets/d/11zwL6W2XQOXyXbt_sUXp0YiHe-vaK6BjTiG-YJKm8ZU/edit#gid=452738143)

I have used ``` freq = "B" ``` parameter in ``` make_future_dataframe ``` method, to create the prediction dataframe containing dates for only business days in the ``` ds ``` column.
 
The forecasts thus generated are pretty accurate. However, when plotting the different components of the model using the ``` plot_components ``` method, the ``` weekly ``` component shows some value for weekends as well.

A sample code to reproduce the issue is as follows - 
```python
# Import Packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from fbprophet import Prophet

sns.set()


# Import Data
# "prices.csv" file is available in the following link
# https://docs.google.com/spreadsheets/d/11zwL6W2XQOXyXbt_sUXp0YiHe-vaK6BjTiG-YJKm8ZU/edit#gid=452738143
data = pd.read_csv("prices.csv")


# Prophet Model
prices_model = Prophet()
prices_model.fit(data)

# Predictions
future_df = prices_model.make_future_dataframe(periods = 30, freq = "B")
predictions_df = prices_model.predict(future_df)

# Plotting Components
prices_model.plot_components(predictions_df)
plt.show()
```
![prophet_plot_components_issue](https://user-images.githubusercontent.com/42487477/92738243-664ba200-f399-11ea-9219-e0cb287a8fe2.PNG)

Here is the plot in question. As you can see there is some seasonality estimated for weekends. This should not be the case as the data is only available for business days. Any help is appreciated in helping me remove the weekends from this plot, or in pointing me to the error in my code that may be causing this behavior.

![prophet_plot_components_issue_closeup](https://user-images.githubusercontent.com/42487477/92739171-3bae1900-f39a-11ea-917d-d2fe976f83c9.PNG)

Apologies if a similar issue has been raised previously. Thank you.

**Comment by bletham** [comment]
The issue here is along the lines of what is described in https://facebook.github.io/prophet/docs/non-daily_data.html#data-with-regular-gaps , where the seasonality is fitting poorly due to having no data for Sat and Sun. You have done the correct thing by limiting the future predictions to business days, but as you have discovered the components plot does not do that, and so you see wonky results there.

There is related discussion in #749 about having the components plots handle gaps in the data, but there isn't a great solution yet other than to produce the plot manually. You could do that like this by plotting the values as given in the forecast dataframe:
```Python
from matplotlib import pyplot as plt
import numpy as np

fig = plt.figure()
ax = fig.add_subplot(111)
days = predictions_df['ds'][0:5]  # Any sequence of dates starting on Monday
weekly_seas = predictions_df['weekly'][0:5]  # Weekly column for the same sequence of dates

ax.plot(np.arange(5), weekly_seas)
ax.set_xticks(np.arange(5))
ax.set_xticklabels(days.dt.day_name())
ax.set_xlabel('Day of week')
ax.grid(True, which='major', c='gray', ls='-', lw=1, alpha=0.2)
```

**Comment by yashveersinghsohi** [comment]
> The issue here is along the lines of what is described in https://facebook.github.io/prophet/docs/non-daily_data.html#data-with-regular-gaps , where the seasonality is fitting poorly due to having no data for Sat and Sun. You have done the correct thing by limiting the future predictions to business days, but as you have discovered the components plot does not do that, and so you see wonky results there.
> 
> There is related discussion in #749 about having the components plots handle gaps in the data, but there isn't a great solution yet other than to produce the plot manually. You could do that like this by plotting the values as given in the forecast dataframe:
> 
> ```python
> from matplotlib import pyplot as plt
> import numpy as np
> 
> fig = plt.figure()
> ax = fig.add_subplot(111)
> days = predictions_df['ds'][0:5]  # Any sequence of dates starting on Monday
> weekly_seas = predictions_df['weekly'][0:5]  # Weekly column for the same sequence of dates
> 
> ax.plot(np.arange(5), weekly_seas)
> ax.set_xticks(np.arange(5))
> ax.set_xticklabels(days.dt.day_name())
> ax.set_xlabel('Day of week')
> ax.grid(True, which='major', c='gray', ls='-', lw=1, alpha=0.2)
> ```

**Comment by yashveersinghsohi** [comment]
Thank you for your help. I will follow this procedure in the future as well for similar datasets.

**Comment by Emillybaek** [comment]
I see this thread is 2 years old - Has anything happened since then? I am running into the same issue, and was wondering if there is a better way of handling the weekends when they are not part of the dataset. I have already excluded them from the future predictions, but the components plots are acting up
