### ISSUE TITLE
Holiday Effects Not Captured

### ISSUE THREAD

**Issue by swjoechen** [facebook/prophet#1659]
Hi Prophet Team,

I recently got a new Mac machine and installed everything prophet related a couple of days ago. I have used the model in the past and it ran fine with all the basic component outputs/charts. Noticing in change log 0.6 you guys fixed something related to holidays and pandas, which happened to be what I've encountered an issue so just figured to share here.

I was just testing running some of the scripts with the Peyton M example you guys put in the documentation [link](https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#modeling-holidays-and-special-events) and looked like the holidays components no longer worked? Please see screenshot and any help with troubleshooting would be greatly appreciated!

PS reading through some posts I have downgraded / upgraded the holidays package from 0.10.3 to 0.9.1 to 0.10.1, with none of which working.

Love the prophet package. Keep up the great work!

Best,
Joe
<img width="1140" alt="Screen Shot 2020-09-10 at 11 38 30 AM" src="https://user-images.githubusercontent.com/48492821/92756547-eacb0000-f35a-11ea-964e-30d54d8a9bb5.png">

**Comment by bletham** [comment]
I believe this is the issue from #1617, which is that pandas 1.1.0 had a not-backwards-compatible change that broke holidays functionality. We just pushed the fix a few days ago in v0.7.1. So if you can check your fbprophet version and upgrade to 0.7.1, I think that should fix it!

**Comment by swjoechen** [comment]
hi @bletham , thank you very much for the quick response! My apologies for posting repeating issues without doing much research on the topic. Thanks and I will upgrade to 0.7!

**Comment by bletham** [comment]
No worries, glad the fix was already in place :-)
