### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Shyam1287** [facebook/prophet#1663]
Following was the error experienced while trying to install this using pip

Please note and check the following:
  
    * The Python version is: Python3.7 from "/anaconda3/bin/python3.7"
    * The NumPy version is: "1.19.1"
  
  and make sure that they are the versions you expect.
  Please carefully study the documentation linked above for further help.
  
  Original error was: /anaconda3/lib/python3.7/site-packages/numpy/core/../../../.././libgomp.so.1: version `GOMP_4.0' not found (required by /anaconda3/lib/python3.7/site-packages/numpy/core/../../../../libcblas.so.3)
  
  ----------------------------------------
  ERROR: Failed building wheel for fbprophet
  Running setup.py clean for fbprophet
Failed to build fbprophet
Installing collected packages: fbprophet
    Running setup.py install for fbprophet ... error

ImportError: /anaconda3/lib/python3.7/site-packages/numpy/core/../../../.././libgomp.so.1: version `GOMP_4.0' not found (required by /anaconda3/lib/python3.7/site-packages/numpy/core/../../../../libcblas.so.3)

**Comment by bletham** [comment]
I haven't seen this before, but it looks like something isn't working in numpy.
Does numpy work?
```Python
import numpy as np
np.linalg.svd(np.random.rand(4, 4))
```
Does pystan work?
```Python
import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this will take a minute
y = model.sampling(n_jobs=1).extract()['y']
y.mean()  # should be close to 0
```

There's various posts that seem related.. are you on an old version of Ubuntu? maybe https://forums.synfig.org/t/solved-gomp-4-0-not-found-ubuntu-14-04-derivated-distros-related/9137 will be helpful.

**Comment by Shyam1287** [comment]
Ya. You a recorrect. My numpy is not getting imported.
I get the following error:

```
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 
  * The NumPy version is: "1.18.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: /anaconda3/lib/python3.7/site-packages/numpy/core/../../../.././libgomp.so.1: version `GOMP_4.0' not found (required by /anaconda3/lib/python3.7/site-packages/numpy/core/../../../../libopenblas.so.0)

```

**Comment by bletham** [comment]
Interesting. I don't think I have any ideas on how to fix this besides what is recommended by numpy in their troubleshooting doc link that the error gives.

**Comment by Shyam1287** [comment]
Anyways thanks for your time. I resolved it myself yesterday. There was some uninstalls and reinstalls required.
