### ISSUE TITLE
Is Prophet good for data with period non-multiple of an Earth's year/month/week?

### ISSUE THREAD

**Issue by Nestak2** [facebook/prophet#1667]
I discovered Prophet recently and find it very useful. But on my latest project I encountered the problem of working with data, that is periodic, but the periods and main signals/fourier components of the data don't have the ratio of year/month/weak/day, but some other time ratio's.
For the sake of simplicity consider these neat signal, with components of yearly and weakly periodicity:

```
X = 0.05*np.sin(1./365*2*np.pi*np.linspace(0.00,3650,3650)) + 0.01*np.sin(1./7*2*np.pi*np.linspace(0.00,3650,3650)) + np.random.normal(0,0.002,3650)
df = pd.DataFrame({'ds':pd.date_range('2012-01-01', periods=365*10), 'y':X})
```
When I apply Prophet on these data I get some good model fits:

```
m4 = Prophet(weekly_seasonality=True, yearly_seasonality=True)
m4.add_seasonality(name='monthly', period=30.5, fourier_order=5)
m4.fit(df[:-1000])
future = m4.make_future_dataframe(periods=1000)
df_forecast = m4.predict(future)

fig = plt.figure(figsize=(10,4))
plt.plot(df.ds, df.y)
plt.plot(df.ds, df_forecast.yhat)
```

![github_prophet1](https://user-images.githubusercontent.com/16193553/93112999-4ed62700-f6c1-11ea-8db3-69151befb0b3.png)

But when I change the data to qualitatively equivalent but with non-integer periodicity for yearly/monthly/weakly/daily signal contributions, I get bad fits. For example, these data

`X = 0.05*np.sin(80*np.linspace(0.00,9.9,3650)) + 0.3*np.sin(4*np.linspace(0.00,9.9,3650)) + np.random.normal(0,0.005,3650) `

delivers with the same fitting as in the code above

![github_prophet2](https://user-images.githubusercontent.com/16193553/93113676-28fd5200-f6c2-11ea-835f-c359fee671a9.png)

I also tried to switch between early, monthly and daily seasonality with `weekly_seasonality=True` or `False` and so on, but with no improvement. **So is Prophet of use for signals of these kind?** Have I maybe missed some setting or additional parameter? Can you point me to another package that can deal with such periodic signal? Tnx

**Comment by bletham** [comment]
Yes, it should work fine with seasonalities that are not a multiple of 1 day, you'll just have to specify their frequencies manually.

The built-in seasonalities are yearly (365.25 days), weekly (7 days), and daily (1 day). You will want to disable all of these, like
```Python
m = Prophet(daily_seasonality=False, weekly_seasonality=False, yearly_seasonality=False)
```
Then, you would need to add new seasonalities with the appropriate frequencies. Like
```Python
m.add_seasonality(name='new_seasonality', period=3.14, fourier_order=5)
```
for 3.14 days period.

**Comment by Nestak2** [comment]
@bletham Thanks, but it still doesn't work out. I must be doing some silly period to-frequency mistake. At the example above with 

`X = 0.05*np.sin(80*np.linspace(0.00,9.9,3650)) + 0.3*np.sin(4*np.linspace(0.00,9.9,3650))`

we have 2 periodic signals with the relation P = 2*pi/f, where f is the frequency. Am I wrong? This means that for our 2 periodic contributions we should do
```

m3.add_seasonality(name='new_seasonality', period=2. * np.pi/80, fourier_order=5)
m3.add_seasonality(name='new_seasonality2', period=2. * np.pi/4, fourier_order=5)
```
Click [here](https://colab.research.google.com/drive/1KpWhpT88RgwgKmSP88ERazzc1OOGTca1?usp=sharing) to try it out in a colab notebook. But this still doesn't give a good fit. Do you see where I make the mistake?

**Comment by bletham** [comment]
The problem is that the periods needs to be defined in a unit of days. Your signal has a period of 2pi/80 on [0, 9.9], but [0, 9.9] isn't the unit of days. When creating the training data, [0, 9.9] is being mapped to 3000 days. So you have to account for that map also to compute period in days. This code works:
```Python
X = 0.05*np.sin(80*np.linspace(0.00,9.9,3000)) + 0.3*np.sin(4*np.linspace(0.00,9.9,3000)) + np.random.normal(0,0.005,3000)
df = pd.DataFrame({'ds':pd.date_range('2012-10-01', periods=3000), 'y':X})

m3 = Prophet(daily_seasonality=False, weekly_seasonality=False, yearly_seasonality=False)
m3.add_seasonality(name='new_seasonality', period=2*np.pi/80/(9.9/3000), fourier_order=5)
m3.add_seasonality(name='new_seasonality2', period=2*np.pi/4/(9.9/3000), fourier_order=5)
m3.fit(df[:-1000])
future = m3.make_future_dataframe(periods=1000)
df_forecast = m3.predict(future)
fig = m3.plot(df_forecast)
```
![prophet9](https://user-images.githubusercontent.com/6339760/93249432-26444080-f746-11ea-8b70-c9f1a0047acf.png)
