### ISSUE TITLE
Why was there a jupyter killed after the fit?

### ISSUE THREAD

**Issue by Slun12** [facebook/prophet#1669]
![image](https://user-images.githubusercontent.com/25979807/93177307-33245c80-f765-11ea-953f-2faef3dd3cfe.png)

**Comment by bletham** [comment]
That would be the first time that the Stan model is being used, and I'm wondering if something doesn't work with it. Would you mind checking if pystan works?
```Python
import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this will take a minute
y = model.sampling(n_jobs=1).extract()['y']
y.mean()  # should be close to 0
```

Otherwise, does you machine have >4gb of RAM?

**Comment by Slun12** [comment]
Thank you. Problem solved. I double-checked the Stan Model and reinstalled the pystan and fbprophet.

**Comment by Slun12** [comment]
> That would be the first time that the Stan model is being used, and I'm wondering if something doesn't work with it. Would you mind checking if pystan works?
> 
> ```python
> import pystan
> model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
> model = pystan.StanModel(model_code=model_code)  # this will take a minute
> y = model.sampling(n_jobs=1).extract()['y']
> y.mean()  # should be close to 0
> ```
> 
> Otherwise, does you machine have >4gb of RAM?

**Comment by Slun12** [comment]
Thank you. Problem solved. I double-checked the Stan Model and reinstalled the pystan and fbprophet.
