### ISSUE TITLE
'parallel' argument not recognized in the cross_validation function.

### ISSUE THREAD

**Issue by faouziamrouche** [facebook/prophet#1671]
I am using the 0.6 version of fbprophet with a python 3.6 environment, and I cannot use the parallelization function for the cross validation. I used this line of code : 
df_cv = cross_validation(m, initial='400 days', period='30 days', horizon = '90 days',parallel="processes")
And I received this error:
TypeError: cross_validation() got an unexpected keyword argument 'parallel'
Prophet works normally otherwise.

**Comment by bletham** [comment]
This functionality was added in v0.7.1, so if you upgrade to that it should work!

**Comment by faouziamrouche** [comment]
It worked after the update, thanks!
