### ISSUE TITLE
python stopped working when do fit()

### ISSUE THREAD

**Issue by lhoncorty** [facebook/prophet#1675]
When I use prophet to do fit, the python stopped working. Could you help to see this issue?

KeyError: 'metric_file'
Exception ignored in: 'stanfit4anon_model_f5236004a3fd5b8429270d00efcc0cf9_7332008770348935536._set_stanargs_from_dict'
KeyError: metric_file

Process finished with exit code -1073741819 (0xC0000005)

My os system is windows10 with conda installed.

**Comment by bletham** [comment]
This looks like the same error as #1670. There is some ongoing discussion there on how to resolve it.
