### ISSUE TITLE
while using Fbprophet: AttributeError

### ISSUE THREAD

**Issue by sudeshna-py** [facebook/prophet#1681]
Am getting AttributeError in this code and unable to fix it
![a](https://user-images.githubusercontent.com/71181547/93707584-8d4e6480-fb4d-11ea-94bf-e8be2a594b60.png)

**Comment by bletham** [comment]
What version of fbprophet are you using?
```Python
import fbprophet
print(fbprophet.__version__
```

This looks like an issue that was fixed a while back (#900) so upgrading to the latest version (0.7.1) should fix it. (I believe it was fixed prior to v0.6, so I suspect this is a pretty old version).

**Comment by sudeshna-py** [comment]
I'm using 0.2.1 version in anaconda, I had to downgrade it in order to
install fbprophet.

**Comment by bletham** [comment]
Yeah, that's a very old version and you'd have to downgrade pandas pretty far in order to get it to work (0.23 or so iirc). You should be able to install 0.7.1 from conda forge.
