### ISSUE TITLE
KeyError: 'metric_file' in Prophet using python

### ISSUE THREAD

**Issue by Erandi22** [facebook/prophet#1682]
I  want to use Prophet to forecast weekly data. I got a measurement every monday of every week. I got the next error: KeyError: 'metric_file'. I would appreciate any help.

It is not clear for me the reason of this, when I define my model I use the next parameters:

A glance of my dataframe:
df_tst.head(10)
Out[10]: 
          ds          y
0 2018-01-01  40.378101
1 2018-01-08  41.961418
2 2018-01-15  45.990971
3 2018-01-22  46.992864
4 2018-01-29  43.657005
5 2018-02-05  41.671037
6 2018-02-12  39.753788
7 2018-02-19  39.727373
8 2018-02-26  42.852055
9 2018-03-05  44.349185

model = Prophet(seasonality_mode='multiplicative',
                daily_seasonality = True,
                weekly_seasonality= True,
                yearly_seasonality = True,).fit(df_tst)

In [8]:df_tst.dtypes
Out[8]: 
ds    datetime64[ns]
y            float64
dtype: object

**Comment by bletham** [comment]
Did you install recently from conda forge? This looks like the same issue in #1670, there's ongoing discussion there about how to take care of it.

**Comment by Erandi22** [comment]
I will read the issue. Thanks @bletham for the tip

**Comment by Erandi22** [comment]
I have read the issue in #1670, I tried with:
pandas v1.0.4
pystan v2.19.1.1
I got the same result : KeyError: 'metric_file'

I also tried the pystan functionality using the code below, I have no problems to use pystan and the value of y is close to 0.

import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this will take a minute
y = model.sampling(n_jobs=1).extract()['y']
y.mean()  # should be close to 0

**Comment by Erandi22** [comment]
Ok, I created a new environment and install all again... now it is working with the next package versions:

fbprophet 0.7.1
pandas 1.0.4
pystan 2.19.1.1
numpy 1.19.1
python 3.8.5

**Comment by bletham** [comment]
@Erandi22 do you know what changed with the new environment? I'm still really confused as to what is causing this or the best way to fix it.

**Comment by albepelle** [comment]
> @Erandi22 do you know what changed with the new environment? I'm still really confused as to what is causing this or the best way to fix it.

I've been struggling with loading the model properly for a whole day and figuring out why it was causing the kernel meltdown. I've narrowed down the cause to a bug with Pystan loading. 

Easy fix (at least if you're using Anaconda): create new Conda env python >=3.8, and install directly fbphrophet on it, the installer will take automatically care of the right dependencies. works like a charm. Beware you need to create the environment manually via Conda terminal as the package manager doesn't automatically support new environments with  python >3.7

hope that helps
