### ISSUE TITLE
Final forecast less than previous forecast if adding continuous external regressors.

### ISSUE THREAD

**Issue by HimanshuKatyan** [facebook/prophet#1688]
Hello team, 
Let me excuse if somebody already asked this questions and I am also quite new to Prophet and Time Series problems. 
	
**My two continuous external regressors does not impact on the final forecasting.**  
what silly mistake or wrong I am doing in Add regressor prophet model? @bletham 

**Nature of dependent data – how it look likes?** 
![image](https://user-images.githubusercontent.com/71377752/94137269-13c0ba00-fe5e-11ea-9ebe-5021097ee197.png)

**Code for the dependent variable to build the prophet model** 
m = Prophet() #daily_seasonality = True, weekly_seasonality = False) # by putting daily_seasonality = True, weekly_seasonality = False provide much better results
m.fit(df1)
future_FTE1 = m.make_future_dataframe(periods=1500, include_history = True, freq= 'H' ) # write freq = 'H' will provide hourwise data
#future_FTE1
future_FTE11 = future_FTE1.copy()
future_FTE11 = future_FTE11[(future_FTE11['ds'].dt.hour > 8) & (future_FTE11['ds'].dt.hour < 18)] # Business Hours between 09 am to 05 pm
future_FTE11 = future_FTE11[future_FTE11['ds'].dt.dayofweek < 5] # Only week days not included Saturday and Sunday
forecast_FTE1 = m.predict(future_FTE11)

**Result Forecasted values** 
forecast_FTE1[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(15)
![image](https://user-images.githubusercontent.com/71377752/94137350-318e1f00-fe5e-11ea-88fe-40836ed97ecf.png)

**Nature of first regressor data – how it look likes?**
![image](https://user-images.githubusercontent.com/71377752/94137408-44085880-fe5e-11ea-9789-40e7363966fe.png)

**Code for the first Independent variable to build the prophet model** 

m = Prophet() # daily_seasonality = True, weekly_seasonality = True)
m.fit(df_Call1)
future_Call1 = m.make_future_dataframe(periods=1500, include_history = True , freq= 'H' ) # write freq = 'H' will provide hourwise data

future_Call11 = future_Call1.copy()
future_Call11 = future_Call11[(future_Call11['ds'].dt.hour > 8) & (future_Call11['ds'].dt.hour < 18)] # Business Hours between 09 am to 05 pm
future_Call11 = future_Call11[future_Call11['ds'].dt.dayofweek < 5] # Only week days not included Saturday and Sunday
future_Call11.count()
forecast_call1 = m.predict(future_Call11)

**Result Forecasted values** 
forecast_call1[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()
![image](https://user-images.githubusercontent.com/71377752/94137502-64d0ae00-fe5e-11ea-9fc4-531bf9dde2f2.png)
![image](https://user-images.githubusercontent.com/71377752/94137513-69956200-fe5e-11ea-8f22-a1a30b3ee37b.png)

**Code for the dependent variable to build the prophet model including the first regressor** 

# define the range 
future_range = pd.date_range(start='2020-01-06', end= '	2020-07-31', freq='H')
future_range = future_range[future_range.indexer_between_time('09:00:00','17:00:00')] # Business Hours between 09 am to 05 pm
future_range = future_range [future_range.dayofweek<5] # Only week days not included Saturday and Sunday
future_range.shape[0]  # gives number of row count

future_temp_df = pd.DataFrame({'future_date': future_range, 'Future_Call_Kal': forecast_call11['yhat'].tolist()})

future_temp_df['future_date'] = pd.to_datetime(future_temp_df['future_date'])#convert this dataframe into dattime 
future_temp_df=future_temp_df.set_index('future_date')
future_temp_df

def Kal_Call(ds):
    date = (pd.to_datetime(ds)).date()
    
    if df_Call_FTE12[date:].empty:
        return future_temp_df[date:]['Future_Call_Kal'].values[0]
    else:
        return (df_Call_FTE12[date:]['Kal_Imp_Call']).values[0]
    return 0

m = Prophet() #daily_seasonality = True, weekly_seasonality = False, seasonality_mode='multiplicative')
m.add_regressor('Kal_Imp_Call') 
m.fit(df_Call_FTE12)

FTE_future = m.make_future_dataframe(periods=1500, freq='H', include_history = True)

FTE_future1 = FTE_future.copy()
FTE_future1 = FTE_future1[(FTE_future1['ds'].dt.hour > 8) & (FTE_future1['ds'].dt.hour < 18)] # Business Hours between 09 am to 05 pm
FTE_future1 = FTE_future1[FTE_future1['ds'].dt.dayofweek < 5] # Only week days not included Saturday and Sunday

FTE_future1['Kal_Imp_Call'] = FTE_future1['ds'].apply(Kal_Call)

forecast3 = m.predict(FTE_future1)

**Result Forecasted values** 
forecast3[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(15)
![image](https://user-images.githubusercontent.com/71377752/94137583-86ca3080-fe5e-11ea-821a-6efc9efc48d1.png)

**Nature** 
![image](https://user-images.githubusercontent.com/71377752/94137604-8df13e80-fe5e-11ea-813a-fb0b25a9b139.png)

Even if i add more regressors the final forecasted model does not changed while all other regressors has same time series properties (trend and seasonal components). 

Please let me know if any other information need from my side.

**Comment by bletham** [comment]
Sorry for the slow response.

If you look at
```
m.plot_components(forecast3)
```
you will be able to see the contribution of the regressor in the forecast. I'm guessing that it will be basically 0. This is because the regressor does not look like it is correlated with the time series at all. In fact, the time series doesn't have any structure to it besides the weekly seasonality, so there really isn't anything for the regressor to add. I think the components plot will show that.
