### ISSUE TITLE
Is it possible to fit prophet with incomplete regressors?

### ISSUE THREAD

**Issue by faouziamrouche** [facebook/prophet#1689]
Use case : 
I want to forecast a variable with monthly historical values going back to let's say 2015, but the regressors are only available from 2017. When trying to feed the regressors directly with missing values, I get the following error message :
ValueError: Found NaN in column 'KPI1' 
Is there a way to bypass this and still fit the model with the available data?

**Comment by hansukyang** [comment]
In this case, I think you'd need to understand for yourself how important the external regressors are and how they affect the time-series. If it is significant but you don't have the data, an option would be to just use data from 2017 onwards.
