### ISSUE TITLE
ImportError: cannot import name '_png' from 'matplotlib'

### ISSUE THREAD

**Issue by jasonchia89** [facebook/prophet#1691]
Hi, while trying out the fbprophet tutorial, I encountered the following error log when attempting to execute in jupyter notebook the following code: fig1 = m.plot(forecast)

The error log is as follows:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~/opt/anaconda3/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    339                 pass
    340             else:
--> 341                 return printer(obj)
    342             # Finally look for special method names
    343             method = get_real_method(obj, self.print_method)

~/opt/anaconda3/lib/python3.7/site-packages/IPython/core/pylabtools.py in <lambda>(fig)
    246 
    247     if 'png' in formats:
--> 248         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    249     if 'retina' in formats or 'png2x' in formats:
    250         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))

~/opt/anaconda3/lib/python3.7/site-packages/IPython/core/pylabtools.py in print_figure(fig, fmt, bbox_inches, **kwargs)
    130         FigureCanvasBase(fig)
    131 
--> 132     fig.canvas.print_figure(bytes_io, **kw)
    133     data = bytes_io.getvalue()
    134     if fmt == 'svg':

~/opt/anaconda3/lib/python3.7/site-packages/matplotlib/backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, **kwargs)
   2092         hardcopy.
   2093 
-> 2094         Parameters
   2095         ----------
   2096         filename : str or path-like or file-like

~/opt/anaconda3/lib/python3.7/site-packages/matplotlib/backend_bases.py in _get_renderer(figure, print_method)
   1558             return renderer
   1559         else:
-> 1560             raise RuntimeError(f"{print_method} did not call Figure.draw, so "
   1561                                f"no renderer is available")
   1562         finally:

~/opt/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py in print_png(self, filename_or_obj, metadata, pil_kwargs, *args, **kwargs)
    503         pil_kwargs : dict, optional
    504             Keyword arguments passed to `PIL.Image.Image.save`.
--> 505 
    506             If the 'pnginfo' key is present, it completely overrides
    507             *metadata*, including the default 'Software' key.

ImportError: cannot import name '_png' from 'matplotlib' (/Users/jasonchia/opt/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py)

I tried updating matplotlib to 3.3.2 but the problem still persists. Please advise, am in need of urgent assistance...Thanks in advance.

**Comment by OsamaHamdyOsman** [comment]
I am experiencing the same issue when trying to plot a simple line plot:

```
[<matplotlib.lines.Line2D at 0x21c8e387748>]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\Anaconda3\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    339                 pass
    340             else:
--> 341                 return printer(obj)
    342             # Finally look for special method names
    343             method = get_real_method(obj, self.print_method)

~\Anaconda3\lib\site-packages\IPython\core\pylabtools.py in <lambda>(fig)
    246 
    247     if 'png' in formats:
--> 248         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    249     if 'retina' in formats or 'png2x' in formats:
    250         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))

~\Anaconda3\lib\site-packages\IPython\core\pylabtools.py in print_figure(fig, fmt, bbox_inches, **kwargs)
    130         FigureCanvasBase(fig)
    131 
--> 132     fig.canvas.print_figure(bytes_io, **kw)
    133     data = bytes_io.getvalue()
    134     if fmt == 'svg':

~\Anaconda3\lib\site-packages\matplotlib\backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, **kwargs)
   2092         hardcopy.
   2093 
-> 2094         Parameters
   2095         ----------
   2096         filename : str or path-like or file-like

~\Anaconda3\lib\site-packages\matplotlib\backend_bases.py in _get_renderer(figure, print_method)
   1558             return renderer
   1559         else:
-> 1560             raise RuntimeError(f"{print_method} did not call Figure.draw, so "
   1561                                f"no renderer is available")
   1562         finally:

~\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py in print_png(self, filename_or_obj, metadata, pil_kwargs, *args, **kwargs)
    503         pil_kwargs : dict, optional
    504             Keyword arguments passed to `PIL.Image.Image.save`.
--> 505 
    506             If the 'pnginfo' key is present, it completely overrides
    507             *metadata*, including the default 'Software' key.

ImportError: cannot import name '_png' from 'matplotlib' (C:\Users\Semseman\Anaconda3\lib\site-packages\matplotlib\__init__.py)

<Figure size 432x288 with 1 Axes>
```

**Comment by bletham** [comment]
@jasonchia89 it looks like something is messed up in the matplotlib install. I haven't seen this before and I'm not exactly sure what is going on, but poking around on stackoverflow a bit, it looks like it might be an issue with libpng. Otherwise, it looks like downgrading to matplotlib 3.1 might be worth a shot.

**Comment by aprilahijriyan** [comment]
try this `pip install matplotlib==3.1.3` work for me

**Comment by PuraCiensualidad** [comment]
> try this `pip install matplotlib==3.1.3` work for me

It worked for me too, thank you!!

**Comment by mschroen** [comment]
Why is this issue closed? There should be a solution which works for latest matplotlib versions. Downgrading for most people is not an option.

**Comment by tathi-martins** [comment]
> Why is this issue closed? There should be a solution which works for latest matplotlib versions. Downgrading for most people is not an option.

I agree.

**Comment by KrishnaRohit2110** [comment]
> Why is this issue closed? There should be a solution which works for latest matplotlib versions. Downgrading for most people is not an option.

Yes. I downgraded but still I'm facing the issue

**Comment by aegonwolf** [comment]
I reopened it, I think it's mad that someone would close the issue due to having a downgrade option
https://github.com/facebook/prophet/issues/2048

**Comment by davidshumway** [comment]
> > try this `pip install matplotlib==3.1.3` work for me
> 
> It worked for me too, thank you!!

This worked on Google Colab (downgrading from 3.5.1)

**Comment by gustavofelicidade** [comment]
I hope it can be useful in latest versions...

**Comment by gustavofelicidade** [comment]
I have downgraded to 3.2.2 and it works for me

**Comment by JacobHayes** [comment]
I was able to run all of the [python example](https://facebook.github.io/prophet/docs/quick_start.html#python-api) in a notebook using the latest prophet and matplotlib with no issues:
```
$ pip3 freeze | grep -E '(matplotlib|prophet)=='
matplotlib==3.6.3
prophet==1.1.1
```
I'm curious if folks still having issues may be using an old version of prophet?
