### ISSUE TITLE
Kernel keeps dying on macOS' jupyter notebook upon calling .fit() from fbprophet

### ISSUE THREAD

**Issue by jasonchia89** [facebook/prophet#1692]
The following are the warnings I suspect are related to the kernel crash each time I call .fit():

INFO:numexpr.utils:Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.

I could however run the same thing on Google Colab without a hitch...

Would any kind soul advise on this?

**Comment by jordanparker-me** [comment]
I am having the same issue running Prophet on SageMaker notebooks. 

The following warning is printed and then the kernel restarts. I installed Prophet using `%conda install -c conda-forge fbprophet`

```
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pystan/misc.py:399: FutureWarning:

Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
```

**Comment by bletham** [comment]
hm fbprophet doesn't use numexpr directly so I think the message may be unrelated. Crashing on fit makes me suspect a Stan issue, since that is the first time the Stan model is used. Could you check just if pystan is working or if that produces a crash? If that works then we'll have to dive deeper..
```Python
import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this will take a minute
y = model.sampling(n_jobs=1).extract()['y']
y.mean()  # should be close to 0
```

**Comment by bletham** [comment]
Actually it looks like pandas can use numexpr, so if pystan is working, then maybe it would be worth trying to disable or even uninstall numexpr just to see for sure if that is a source of the issue.

**Comment by jasonchia89** [comment]
Hi Ben,

Thanks for your reply.

I ran the specified code and I got a y mean value of -0.01751515193243853.

That is close to zero but is the negative sign of any concern?

Best Regards,
Jason

**Comment by bletham** [comment]
hm OK so pystan is working then, so it's not my first guess. Is it possible to execute the code just in the python console to see what error is happening? A segmentation fault I guess?

And then if you could try disabling numexpr that would also be great, to see if perhaps that is the issue.

**Comment by jasonchia89** [comment]
Will try executing the same code in the python interpreter soon. But how do I disable numexpr?

**Comment by jasonchia89** [comment]
Hi Ben,

I have run the same code on the python interpreter and the readout is as follows:

>>> y= model.sampling(n_jobs=1).extract()['y']

Gradient evaluation took 1.1e-05 seconds
1000 transitions using 10 leapfrog steps per transition would take 0.11 seconds.
Adjust your expectations accordingly!


Iteration:    1 / 2000 [  0%]  (Warmup)
Iteration:  200 / 2000 [ 10%]  (Warmup)
Iteration:  400 / 2000 [ 20%]  (Warmup)
Iteration:  600 / 2000 [ 30%]  (Warmup)
Iteration:  800 / 2000 [ 40%]  (Warmup)
Iteration: 1000 / 2000 [ 50%]  (Warmup)
Iteration: 1001 / 2000 [ 50%]  (Sampling)
Iteration: 1200 / 2000 [ 60%]  (Sampling)
Iteration: 1400 / 2000 [ 70%]  (Sampling)
Iteration: 1600 / 2000 [ 80%]  (Sampling)
Iteration: 1800 / 2000 [ 90%]  (Sampling)
Iteration: 2000 / 2000 [100%]  (Sampling)

 Elapsed Time: 0.010685 seconds (Warm-up)
               0.009244 seconds (Sampling)
               0.019929 seconds (Total)


Gradient evaluation took 2e-06 seconds
1000 transitions using 10 leapfrog steps per transition would take 0.02 seconds.
Adjust your expectations accordingly!


Iteration:    1 / 2000 [  0%]  (Warmup)
Iteration:  200 / 2000 [ 10%]  (Warmup)
Iteration:  400 / 2000 [ 20%]  (Warmup)
Iteration:  600 / 2000 [ 30%]  (Warmup)
Iteration:  800 / 2000 [ 40%]  (Warmup)
Iteration: 1000 / 2000 [ 50%]  (Warmup)
Iteration: 1001 / 2000 [ 50%]  (Sampling)
Iteration: 1200 / 2000 [ 60%]  (Sampling)
Iteration: 1400 / 2000 [ 70%]  (Sampling)
Iteration: 1600 / 2000 [ 80%]  (Sampling)
Iteration: 1800 / 2000 [ 90%]  (Sampling)
Iteration: 2000 / 2000 [100%]  (Sampling)

 Elapsed Time: 0.009191 seconds (Warm-up)
               0.007383 seconds (Sampling)
               0.016574 seconds (Total)


Gradient evaluation took 1e-06 seconds
1000 transitions using 10 leapfrog steps per transition would take 0.01 seconds.
Adjust your expectations accordingly!


Iteration:    1 / 2000 [  0%]  (Warmup)
Iteration:  200 / 2000 [ 10%]  (Warmup)
Iteration:  400 / 2000 [ 20%]  (Warmup)
Iteration:  600 / 2000 [ 30%]  (Warmup)
Iteration:  800 / 2000 [ 40%]  (Warmup)
Iteration: 1000 / 2000 [ 50%]  (Warmup)
Iteration: 1001 / 2000 [ 50%]  (Sampling)
Iteration: 1200 / 2000 [ 60%]  (Sampling)
Iteration: 1400 / 2000 [ 70%]  (Sampling)
Iteration: 1600 / 2000 [ 80%]  (Sampling)
Iteration: 1800 / 2000 [ 90%]  (Sampling)
Iteration: 2000 / 2000 [100%]  (Sampling)

 Elapsed Time: 0.008116 seconds (Warm-up)
               0.007858 seconds (Sampling)
               0.015974 seconds (Total)


Gradient evaluation took 3e-06 seconds
1000 transitions using 10 leapfrog steps per transition would take 0.03 seconds.
Adjust your expectations accordingly!


Iteration:    1 / 2000 [  0%]  (Warmup)
Iteration:  200 / 2000 [ 10%]  (Warmup)
Iteration:  400 / 2000 [ 20%]  (Warmup)
Iteration:  600 / 2000 [ 30%]  (Warmup)
Iteration:  800 / 2000 [ 40%]  (Warmup)
Iteration: 1000 / 2000 [ 50%]  (Warmup)
Iteration: 1001 / 2000 [ 50%]  (Sampling)
Iteration: 1200 / 2000 [ 60%]  (Sampling)
Iteration: 1400 / 2000 [ 70%]  (Sampling)
Iteration: 1600 / 2000 [ 80%]  (Sampling)
Iteration: 1800 / 2000 [ 90%]  (Sampling)
Iteration: 2000 / 2000 [100%]  (Sampling)

 Elapsed Time: 0.007848 seconds (Warm-up)
               0.006405 seconds (Sampling)
               0.014253 seconds (Total)

>>> print(y.mean())
0.018293536764459228
>>> 

Also, would disabling numexpr which is the numerical expression evaluator for numpy affect any critical operations when I use lumpy, as I use it very frequently…so if there are alternative ways around disabling numexpr, it would be greatly appreciated.

Thanks in advance!

Best Regards,
Jason

**Comment by bletham** [comment]
Sorry for the slow reply. I'm still a bit lost as to what's happening here. Is it possible to run the Prophet commands in the python terminal and see if it prints anything out when it crashes?

Is there something with the particular data or model producing the issue or does it crash even on the quickstart example: https://github.com/facebook/prophet/blob/master/notebooks/quick_start.ipynb

**Comment by dpoonam** [comment]
I had the same issue after installing the latest fbprophet with  "conda install -c conda-forge fbprophet"

Used following commands to downgrade fbprophet to 0.6.0 and that worked.

conda remove pystan fbprophet
conda install pystan=2.19.0.0
conda install -c conda-forge fbprophet=0.6.0

**Comment by guney1** [comment]
I am having the same issue with jupyter lab. Anaconda prompt throwing the following:

[I 15:14:06.747 LabApp] KernelRestarter: restarting kernel (1/5), keep random ports
kernel fd249a5d-2df8-4e09-bd52-bb5523a2ad7a restarted
[I 15:14:06.759 LabApp] Starting buffering for fd249a5d-2df8-4e09-bd52-bb5523a2ad7a:68787d0c-a63d-473c-8a6c-a2126ccf7b66
[I 15:14:06.768 LabApp] Restoring connection for fd249a5d-2df8-4e09-bd52-bb5523a2ad7a:68787d0c-a63d-473c-8a6c-a2126ccf7b66

**Comment by drush0** [comment]
@dpoonam That worked, thanks!

**Comment by srisha03** [comment]
I was trying to install the same in AWS Sagemaker. So, in addition to executing the commands that @dpoonam mentioned in the nb terminal, executing -> !conda install -c conda-forge fbprophet=0.6.0 -y
in the notebook itself worked for me.
