### ISSUE TITLE
x-axis scale on seasonalities > 1 year

### ISSUE THREAD

**Issue by raffg** [facebook/prophet#1693]
With custom seasonalities longer than 365 days, the component plot's x-axis scale is confusing. The x-ticks are month/day, but because of the cyclical nature of the year, it repeats back on itself.

For example, forecasting the 11-year cycle of sunspots results in this plot:
![image](https://user-images.githubusercontent.com/20135094/94347975-a5aafd00-ffed-11ea-9f89-0bd61a78b290.png)

It is not clear how to interpret the x-axis.

A change such as this could clarify what's going on:
![image](https://user-images.githubusercontent.com/20135094/94347982-ad6aa180-ffed-11ea-8a6d-4f90715530bb.png)

by adding:
```
    elif period > 730:
        fmt_str = '{dt:%m}/{dt:%d}/{dt:%y}'
```
after
https://github.com/facebook/prophet/blob/77da5b8c06d05d478af510198c685d454342db1f/python/fbprophet/plot.py#L407

It's not ideal to name a specific year for a repeating cycle though, nor to arbitrarily choose 2017 to start, so maybe change the year to increments of 01, 02, 03, ..., 11? That would match the convention of months and days starting at 01/01, but could also create confusion that the cycle begins on Jan 1, 2001, for instance.

**Comment by raffg** [comment]
Here's another idea. For seasonalities which don't neatly align with "human" time measurements of hours, days, years, etc., the x-axis could simply be stated in days, as that is how the period is specified in `add_seasonality`. That would produce this 11-year sunspot cycle:
![image](https://user-images.githubusercontent.com/20135094/94371310-6db5bf80-00aa-11eb-9c73-dd83b427b1bd.png)

**Comment by bletham** [comment]
Thanks for pointing this out, it is pretty confusing with cycles greater than a year or two. I like your suggestion of switching to "days" as the unit for such cycles. For cycles that aren't a multiple of 1 year there isn't a clear "starting point" for the seasonality, the way Jan 1 can be for a yearly seasonality or Sun/Mon for a weekly seasonality, but I'm not sure there is a great solution to that. So "days" is least a step in the right direction. Is this something you want to make a PR for?

**Comment by raffg** [comment]
Done for Python in https://github.com/facebook/prophet/pull/1707
