### ISSUE TITLE
Difference in results under the same dataset on python 

### ISSUE THREAD

**Issue by sfigueroa92** [facebook/prophet#1695]
First of all, awesome package, I encountered a small issue, I am using Prophet for anomaly detection on multiple variables under the same dataset. The basic setup was 

                   m = Prophet(daily_seasonality=False,
                                         yearly_seasonality=False,
                                         weekly_seasonality=False,
                                         seasonality_mode='multiplicative',
                                         interval_width=0.99,
                                         changepoint_range=0.8)

I am using python 3.7, one directly in python and the other one using Jupiter notebooks. Under the estimation in Jupiter I get around 13 points that are outside the confidence interval.   Under the estimation in python I get 130. I have tested them multiple times, both of them share the same class that is initializing Prophet (and silencing the logs). I also tested it to use the Newton algorithm but the difference remains consistent. I'm wondering if the issue is with the stan_backend. I don't know what else to try. I double checked the 13 values that I got on jupyter and they make sense, but the 130 from python seems too much for me. Is there anything I can do ? I am not sure where is the difference coming from

**Comment by fbonaita** [comment]
Hi,

is the data set imported exactly in the same way in both cases?
In my experience Prophet can sometimes be sensitive also to very small variations in the input (e.g. different rounding when pulling data via SQL vs importing via CSV).

**Comment by bletham** [comment]
@sfigueroa92 would it be possible to post the plots of the forecasts under each setting, from `m.plt(forecast)`? That would be helpful for seeing what might be happening.

As @fbonaita notes, differences in system configuration or small differences in the data (such as the linear algebra libraries or C++ compilers) can produce small differences in the optimizer behavior that lead to different forecasts. If you tried with the Newton optimizer and you're still seeing the difference then that sounds less likely (unless it is using the Newton optimizer anyway, either because it has less than 100 points or because the L-BFGS is failing and it is falling back on Newton).

You mentioned the logs are being suppressed by another class. Could you turn that off and actually post the optimization log under each setting?

**Comment by enesgur** [comment]
I have the same issue on mac os with python 3.8. I use prophet for anomaly detection too. Sometimes the result is different from previous result for same data set.

Example:

```python
periods = [[1600560000, 11], [1600563600, 44], [1600567200, 33]]
for i in range(0, len(periods)):
    date = datetime.datetime.fromtimestamp(periods[i][0])
    periods[i].append(date)

data_frames = pd.DataFrame(periods, columns=["ts", "y", "ds"])
m = Prophet(daily_seasonality=False, yearly_seasonality=False, weekly_seasonality=False,
            seasonality_mode='multiplicative',
            interval_width=0.99,
            changepoint_range=0.1)
m = m.fit(data_frames)
forecast = m.predict(data_frames)
```

First output:
```
python test.py
Importing plotly failed. Interactive plots will not work.
INFO:fbprophet:n_changepoints greater than number of observations. Using -1.

Initial log joint probability = -8.78696
Iteration  1. Log joint probability =    1.10979. Improved by 9.89675.
Iteration  2. Log joint probability =    2.00264. Improved by 0.892846.
Iteration  3. Log joint probability =    2.56319. Improved by 0.560558.
Iteration  4. Log joint probability =    2.65915. Improved by 0.095956.
Iteration  5. Log joint probability =    2.68374. Improved by 0.024592.
Iteration  6. Log joint probability =    2.68613. Improved by 0.00239084.
Iteration  7. Log joint probability =     2.6928. Improved by 0.00667053.
Iteration  8. Log joint probability =    2.71622. Improved by 0.0234147.
Iteration  9. Log joint probability =    2.71872. Improved by 0.00250422.
Iteration 10. Log joint probability =    2.71943. Improved by 0.000708012.
Iteration 11. Log joint probability =    2.71951. Improved by 7.95891e-05.
Iteration 12. Log joint probability =    2.71957. Improved by 5.5029e-05.
Iteration 13. Log joint probability =    2.71958. Improved by 1.17006e-05.
Iteration 14. Log joint probability =     2.7196. Improved by 2.1902e-05.
Iteration 15. Log joint probability =     2.7196. Improved by 2.62274e-06.
Iteration 16. Log joint probability =     2.7196. Improved by 1.5761e-06.
Iteration 17. Log joint probability =     2.7196. Improved by 5.07328e-07.
Iteration 18. Log joint probability =     2.7196. Improved by 5.42331e-07.
Iteration 19. Log joint probability =     2.7196. Improved by 2.23988e-07.
Iteration 20. Log joint probability =     2.7196. Improved by 1.46134e-08.
Iteration 21. Log joint probability =     2.7196. Improved by 2.36934e-10.
                   ds      trend  yhat_lower  yhat_upper  trend_lower  trend_upper  additive_terms  additive_terms_lower  additive_terms_upper  multiplicative_terms  multiplicative_terms_lower  multiplicative_terms_upper       yhat
0 2020-09-20 03:00:00  18.379794   -8.689891   42.267637    18.379794    18.379794             0.0                   0.0                   0.0                   0.0                         0.0                         0.0  18.379794
1 2020-09-20 04:00:00  29.356845    3.849727   55.552000    29.356845    29.356845             0.0                   0.0                   0.0                   0.0                         0.0                         0.0  29.356845
2 2020-09-20 05:00:00  40.333896   12.414757   65.390165    40.333896    40.333896             0.0                   0.0                   0.0                   0.0                         0.0                         0.0  40.333896
```

Second output
```
 python test.py
Importing plotly failed. Interactive plots will not work.
INFO:fbprophet:n_changepoints greater than number of observations. Using -1.

Initial log joint probability = -8.78696
Iteration  1. Log joint probability =    1.10979. Improved by 9.89675.
Iteration  2. Log joint probability =    2.00264. Improved by 0.892846.
Iteration  3. Log joint probability =    2.56319. Improved by 0.560558.
Iteration  4. Log joint probability =    2.65915. Improved by 0.095956.
Iteration  5. Log joint probability =    2.68374. Improved by 0.024592.
Iteration  6. Log joint probability =    2.68613. Improved by 0.00239084.
Iteration  7. Log joint probability =     2.6928. Improved by 0.00667053.
Iteration  8. Log joint probability =    2.71622. Improved by 0.0234147.
Iteration  9. Log joint probability =    2.71872. Improved by 0.00250422.
Iteration 10. Log joint probability =    2.71943. Improved by 0.000708012.
Iteration 11. Log joint probability =    2.71951. Improved by 7.95891e-05.
Iteration 12. Log joint probability =    2.71957. Improved by 5.5029e-05.
Iteration 13. Log joint probability =    2.71958. Improved by 1.17006e-05.
Iteration 14. Log joint probability =     2.7196. Improved by 2.1902e-05.
Iteration 15. Log joint probability =     2.7196. Improved by 2.62274e-06.
Iteration 16. Log joint probability =     2.7196. Improved by 1.5761e-06.
Iteration 17. Log joint probability =     2.7196. Improved by 5.07328e-07.
Iteration 18. Log joint probability =     2.7196. Improved by 5.42331e-07.
Iteration 19. Log joint probability =     2.7196. Improved by 2.23988e-07.
Iteration 20. Log joint probability =     2.7196. Improved by 1.46134e-08.
Iteration 21. Log joint probability =     2.7196. Improved by 2.36934e-10.
                   ds      trend  yhat_lower  yhat_upper  trend_lower  trend_upper  additive_terms  additive_terms_lower  additive_terms_upper  multiplicative_terms  multiplicative_terms_lower  multiplicative_terms_upper       yhat
0 2020-09-20 03:00:00  18.379794   -8.700378   44.633377    18.379794    18.379794             0.0                   0.0                   0.0                   0.0                         0.0                         0.0  18.379794
1 2020-09-20 04:00:00  29.356845    4.562566   54.304134    29.356845    29.356845             0.0                   0.0                   0.0                   0.0                         0.0                         0.0  29.356845
2 2020-09-20 05:00:00  40.333896   14.397123   64.589164    40.333896    40.333896             0.0                   0.0                   0.0                   0.0                         0.0                         0.0  40.333896
```

***yhat_lower*** fields are different.

**Comment by bletham** [comment]
@enesgur I see what's happening now. The `yhat` is essentially deterministic, subject to the differences in linear algebra libraries that I mentioned above. But the uncertainty intervals (`yhat_lower` and `yhat_upper`) are estimated using Monte Carlo sampling, and so they will be different on different calls to `predict`. This isn't about the model fitting at all; even if you take the same model and just call `predict` twice, you'll see differences in `yhat_lower` and `yhat_upper` just because of Monte Carlo variance. The reason Monte Carlo sampling is used is because of the future trend uncertainty, which can only be estimated via simulation.

You can reduce the variance of `yhat_lower` and `yhat_upper` across multiple calls to `predict` by increasing the number of MC samples used, like `m = Prophet(uncertainty_samples=10000)` to use 10,000 MC samples instead of the default 1000. This will reduce variance, though will also make prediction take longer. So you'd have to find for yourself the best trade-off between variance in the uncertainty estimates and predict speed.

**Comment by enesgur** [comment]
@bletham thank you so much for explanation. This behavior is not very important to me because results are similar. I just wondered :)

**Comment by yasirroni** [comment]
@bletham can the monte carlo result be ported into some markovian cluster, which include probability weights for each cluster? Or at least the raw result and user can further process it using many available clustering method?
