### ISSUE TITLE
Logistic growth

### ISSUE THREAD

**Issue by jlskrock** [facebook/prophet#1697]
Are there some hyperparameters for change the default behaviour of Logistic growth? I mean to try "squash" the forecast. 
Considering CAP=100 with just some lower historic  values the growth rate is huge. Will always the forecast try to touch the CAP value?
Congratulations for this fantastic package.  

![image](https://user-images.githubusercontent.com/72157270/94718478-2ccade80-0328-11eb-9e2c-9844155eead0.png)

**Comment by hansukyang** [comment]
I find setting `growth='flat'`tends to work well for my use case.

**Comment by bletham** [comment]
Yes, if there is increasing growth, then the logistic growth trend will grow (exponentially) until it reaches the saturation capacity. This is the underlying function: https://en.wikipedia.org/wiki/Logistic_function . If there isn't a particular level that you expect this time series to saturate at, then I think the default (piecewise linear) trend would probably be a better choice. If the intent of using the logistic trend was to keep it positive, then I'd recommend looking at the discussion and strategies in #1668.

**Comment by jlskrock** [comment]
I understood
Thanks for the tips.
