### ISSUE TITLE
Issue installating fbrophet - Help me to solve it.

### ISSUE THREAD

**Issue by shivapower1985** [facebook/prophet#1699]
I use jupyter notebook and to install fbprophet, 1st I installed 'pystan' using '! pip install pystan'. Then I did '! pip install fbprophet' to install 'fbprophet' I got an error shown below, 
---------------------------------------Error shown below------------------------------------
Collecting fbprophet
....
...
...
...
...
...
Building wheels for collected packages: fbprophet
  Building wheel for fbprophet (setup.py): started
  Building wheel for fbprophet (setup.py): finished with status 'error'
  Running setup.py clean for fbprophet
Failed to build fbprophet
Installing collected packages: fbprophet
  Running setup.py install for fbprophet: started
    Running setup.py install for fbprophet: finished with status 'error'

ERROR: Command errored out with exit status 1:
   command: 'C:\Users\IIT\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\IIT\\AppData\\Local\\Temp\\pip-install-r6qflgis\\fbprophet\\setup.py'"'"'; __file__='"'"'C:\\Users\\IIT\\AppData\\Local\\Temp\\pip-install-r6qflgis\\fbprophet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\IIT\AppData\Local\Temp\pip-wheel-shnp419f' --python-tag cp37
       cwd: C:\Users\IIT\AppData\Local\Temp\pip-install-r6qflgis\fbprophet\
  Complete output (11 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\fbprophet
  creating build\lib\fbprophet\stan_model
  Importing plotly failed. Interactive plots will not work.
  INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_f5236004a3fd5b8429270d00efcc0cf9 NOW.
  WARNING:pystan:MSVC compiler is not supported
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for fbprophet
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\IIT\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\IIT\\AppData\\Local\\Temp\\pip-install-r6qflgis\\fbprophet\\setup.py'"'"'; __file__='"'"'C:\\Users\\IIT\\AppData\\Local\\Temp\\pip-install-r6qflgis\\fbprophet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\IIT\AppData\Local\Temp\pip-record-ljhcuvfn\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\IIT\AppData\Local\Temp\pip-install-r6qflgis\fbprophet\
    Complete output (11 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\fbprophet
    creating build\lib\fbprophet\stan_model
    Importing plotly failed. Interactive plots will not work.
    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_f5236004a3fd5b8429270d00efcc0cf9 NOW.
    WARNING:pystan:MSVC compiler is not supported
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\IIT\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\IIT\\AppData\\Local\\Temp\\pip-install-r6qflgis\\fbprophet\\setup.py'"'"'; __file__='"'"'C:\\Users\\IIT\\AppData\\Local\\Temp\\pip-install-r6qflgis\\fbprophet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\IIT\AppData\Local\Temp\pip-record-ljhcuvfn\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by rquintino** [comment]
Hi there, this seems to be windows right? error seems to be related to compilation, "error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools":"

this may help

https://facebook.github.io/prophet/docs/installation.html

"On Windows, PyStan requires a compiler so you’ll need to follow the instructions. The easiest way to install Prophet in Windows is in Anaconda."

https://pystan.readthedocs.io/en/latest/windows.html
