### ISSUE TITLE
Prophet inoperable after Catalina update

### ISSUE THREAD

**Issue by sbaumbaugh** [facebook/prophet#1703]
Hello all,

after updating Catalina to 10.15.7 and updating R and R studio (1.3.1093) , Prophet continues to deliver this response.

Any help would be greatly appreciated as I prepare a corporate presentation.

![Screen Shot 2020-10-07 at 4 36 59 PM](https://user-images.githubusercontent.com/60758737/95390977-d3c8f080-08bb-11eb-8b9d-0b2f8261211d.png)

**Comment by bletham** [comment]
There was recently a spate of issues in OSX+R that I still haven't quite figured out; various people seem to have found different things that worked out. Here are some to try:
- #1628: import StanHeaders
- #1601: `devtools::clean_dll`, which you already tried, and someone also suggested downgrading tibble.
- #1604: Install from source: `install.packages("prophet", type="source")`
- #1608: Upgrade the dependencies (rstan, rstantools, rlang, and Rcpp are the ones I'd think most relevant).

If you have success with any of these please let me know, I'm not sure what the source of this error is or what the correct fix is.

**Comment by sbaumbaugh** [comment]
Hey Ben,

I appreciate all the info, what has worked is installing prophet, then #1604, close R, restart machine and open R.
it seems to be working fine.

Prophet has become my go to when forecasting monthly and quarterly sales and it is odd that every time I update my Mac, something affects prophet functionality.

I truly appreciate the help and apologize for the re-occuring issues.

Thank you Ben.

**Comment by mmparker** [comment]
I had similar problems on OSX, and after reading through many of the related issues here, I wanted to note that I _think_ what finally worked for me was `install.packages('prophet', type = 'source')` AND a restart. I'd thrown just about everything at it without luck until that restart.

**Comment by bletham** [comment]
We just pushed a new version 1.0 to CRAN in which we hope this issue is resolved.

**Comment by sbaumbaugh** [comment]
Use the install.packages("prophet", type = "source”) to obtain the current version?

**Comment by CharleyDublin** [comment]
That worked, thank you
