### ISSUE TITLE
The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by ssssnail** [facebook/prophet#1708]
Hi, I am new of Prophet , when i use 'model.fit()', then occur this error:

"The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()"

i don't know why .

these are code 

path = './monthly-car-sales.csv'
df = read_csv(path,header = 0)
df.columns = ['ds', 'y']
df['ds']= to_datetime(df['ds'])
# define the model
model = Prophet()
# fit the model
model.fit(df)

please help me

**Comment by bletham** [comment]
Sorry for the slow reply. This looks like the same issue as #1694. There one person reported that downgrading pandas to 1.1.2 fixed the issue for them, but I haven't been able to replicate the issue yet and don't know what's happening. What version of pandas and fbprophet are you using?
