### ISSUE TITLE
Rate change of change point inquiry

### ISSUE THREAD

**Issue by DSoot** [facebook/prophet#1712]
Don't want to sound stupid but if "rate" stands for slope then any absolute slope change (delta) value that is bigger than changepoint_prior_scale declares a change point?

**Comment by bletham** [comment]
Sorry for the really slow reply. Is there a particular use of the word "rate" that is confusing? I'm not sure that we've been especially precise about the use of that word and disambiguating between the slope of the trend and the magnitude of the changes to the slope of the trend.

In any case, for your particular question: the changepoint_prior_scale is just the variance of the prior distribution on delta. In particular, this is the prior on delta:
https://github.com/facebook/prophet/blob/master/python/stan/unix/prophet.stan#L131
and `tau` is the changepoint_prior_scale. So it wouldn't really be appropriate to use changepoint_prior_scale as a threshold for whether a particular delta is or is not a "changepoint". For instance, if I have a prior that large trend changes (large deltas) are possible, I might set changepoint_prior_scale to a large value, and there will be significant trend changes with delta less than that.
