### ISSUE TITLE
intuition for prior scales

### ISSUE THREAD

**Issue by jswan1000** [facebook/prophet#1714]
Is there an intuitive way to understand prior scale values for holidays, seasonalities, and changepoints? Can I say that the prior scale is a rough way to declare the expected order of magnitude of the effect, for instance? That is, a prior scale of 10 for yearly seasonality would attempt to make the maximum yearly seasonality effect to be around 10% of yhat. Or are these more like standardized values in that their absolute numbers are essentially meaningless?

**Comment by benmwhite** [comment]
>Can I say that the prior scale is a rough way to declare the expected order of magnitude of the effect, for instance?

No, my understanding is they're basically regularization hyperparameters (like with lasso regression for instance). Setting the prior scales closer to zero will make your regression parameter estimates closer to zero if you're trying to avoid overfitting or if you're using a large number of regressors and need a bit of automated feature selection baked into the model.

**Comment by robomotic** [comment]
Quick related question: if I know there are no changepoints, should I set n_changepoints to zero in the constructor?
