### ISSUE TITLE
Do additional regressors need to be stationary?

### ISSUE THREAD

**Issue by pydn** [facebook/prophet#1715]
I understand that prophet can be used to predict non-stationary timeseries, however, I'm curious if additional regressors may be non-stationary as well?

**Comment by bletham** [comment]
Sorry for the slow reply. The regressor itself does not need to be stationary but the relationship between `y` and the regressor is assumed by the model to be stationary. The model is basically
```
y = trend(t) + seasonalty(t) + beta * regressor(t)
```
where the coefficient `beta` will be fit to the data. `beta` will be constant as a function of time.

**Comment by pydn** [comment]
No problem at all. Thanks for the clarification!
