### ISSUE TITLE
[Bug] Incorrect no. of cross-validation cutoffs

### ISSUE THREAD

**Issue by rohan-gt** [facebook/prophet#1720]
When i run the following code, why are there 6 cutoffs being generated? There's 100 days of data out of which I'm setting initial=80, period=10 and horizon=10. Shouldn't there only be 2 cutoff dates, on the 80th and 90th days?

````python
import yfinance as yf
from fbprophet import Prophet
from fbprophet.diagnostics import cross_validation

symbol = 'MSFT'
period = '1d'
start = '1970-1-1'
end = '2020-1-25'
ticker = yf.Ticker(symbol)
df = ticker.history(period=period, start=start, end=end).head(100)
df = df['Close'].reset_index()

df.columns = ['ds', 'y']
model = Prophet().fit(df)
horizon = '10 days'
initial = '80 days'
period = '10 days'
df_cv = cross_validation(model, horizon=horizon, initial=initial, period=period)
````

**Comment by ojnas** [comment]
It's because initial, period and horizon are specified in calendar time (string with pd.Timedelta compatible style). The stock market is closed on weekends and holidays so 100 closing prices corresponds to more than 100 calendar days.

**Comment by robomotic** [comment]
Interesting could this be relate to my question here: https://github.com/facebook/prophet/issues/1731 ?
Is there a way to ignore the calendar days?

**Comment by bletham** [comment]
@robomotic I think the best alternative would be to just directly specify the cutoffs, with the `cutoffs=` kwarg. I don't think there's a reasonable way to use business days for those inputs instead of calendar days.
