### ISSUE TITLE
【R】Unable to load module "stan_fit4prophet_mod": 无法分配大小为14419.4 Gb的矢量

### ISSUE THREAD

**Issue by ctt123ctt** [facebook/prophet#1723]
library(prophet)
错误: package or namespace load failed for ‘prophet’ in .doLoadActions(where, attach):
 error in load action .__A__.1 for package prophet: Rcpp::loadModule(module = "stan_fit4prophet_mod", what = TRUE, : Unable to load module "stan_fit4prophet_mod": 无法分配大小为14419.4 Gb的矢量

I install successfully，but  can‘t load.

**Comment by bletham** [comment]
It sounds like something isn't working in the Stan toolchain. Could you check if rstan is working?
```R
library(rstan)
model_code <- 'parameters {real y;} model {y ~ normal(0,1);}'
fit <- stan(model_code=model_code)  # this will take a minute
mean(extract(fit)$y)  # should be close to 0
```

Otherwise I think the suggestions in #1703 might be some tips for trying to get things to work.
