### ISSUE TITLE
About the algorithm

### ISSUE THREAD

**Issue by feifei-python** [facebook/prophet#1724]
The paper did not mention the calculation method of the uncertainty interval of the predicted value, that is, the source of yhat_lower and yhat_upper, please answer.THANKS!!

**Comment by benmwhite** [comment]
https://facebook.github.io/prophet/docs/uncertainty_intervals.html

**Comment by feifei-python** [comment]
> https://facebook.github.io/prophet/docs/uncertainty_intervals.html
> 
> 我的理解是使用趋势估计值推断未来趋势变化，并将其与误差项估计值结合起来以获取未来预测值的分布，但是如果您使用的是MCMC，它还包括季节性估计值。




> https://facebook.github.io/prophet/docs/uncertainty_intervals.html
> 
> My understanding it extrapolates future trend changes using the trend estimates and combines that with the error term estimates to get the distribution of future predicted values, but it includes seasonality estimates as well if you're using MCMC.

Thanks for your reply, but I mean there is a _**formula**_ that can directly calculate the interval？like this
<img width="115" alt="a7d37ad230210e4e1ae8260bf1163c8" src="https://user-images.githubusercontent.com/44397443/97381943-23bc3580-1905-11eb-825f-eec68cbc33ce.png">

**Comment by benmwhite** [comment]
It generates a sample of predicted values and uses the sample's empirical quantiles to generate the uncertainty interval so I don't believe there's an actual closed form distribution. There's a function argument to adjust this sample size, defaults 1000.

**Comment by feifei-python** [comment]
> 它会生成一个预测值样本，并[使用样本的经验分位数来生成不确定性区间，](https://github.com/facebook/prophet/blob/e41ed25646f44f713c110c30c07c678e4a07728e/R/R/prophet.R#L1507)因此我认为没有实际的封闭式公式。主要拟合函数具有用于调整此样本大小的参数，默认为1000。

thanks!!! I got you

**Comment by bletham** [comment]
Besides the code (which is probably the most accurate description), there is a mathematical description of the trend uncertainty given in Section 3.1.4 of the paper: http://lethalletham.com/ForecastingAtScale.pdf
