### ISSUE TITLE
Part of the called plots not appearing

### ISSUE THREAD

**Issue by Bram-Java** [facebook/prophet#1725]
I have made program in Python, using PyCharm, which is used to plot a series of graphs. The first 5 or 6 are plotted without any problem, but from point 5.0 (see program), the M_n function is not executed and therefore, the graphs are not plotted. I can't find out why... Any help?
[pythonProject.zip](https://github.com/facebook/prophet/files/5451672/pythonProject.zip)

**Comment by bletham** [comment]
This issue tracker is for a different project.
