### ISSUE TITLE
Using make_future_dataframe with multiple regressors

### ISSUE THREAD

**Issue by LizMcQuillan** [facebook/prophet#1735]
make_future_dataframe seems to only produce a dataframe with values for ds, which in turn results in `ValueError: Regressor 'var' missing from dataframe` when attempting to generate forecasts. 

Looking through the python docs, there doesn't seem to be any mention of how to combat this issue using Prophet. Is my only option to write additional code to lag all regressors by the period for which I want to generate forecasts (ex. take var at t-30 to produce a 30 day forecast)?

**Comment by bletham** [comment]
The documentation here (https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#additional-regressors) has some discussion of the need to know the future values of each regressor. So yes, if you use `make_future_dataframe` to produce a dataframe of future dates, you'll need to add the regressor values to that dataframe. You can see how this is done in the documentation example there, but generally if you have a function for computing the lagged value in the history dataframe, you'll just have to run that same function to the future dataframe.
