### ISSUE TITLE
fbprophet web UI

### ISSUE THREAD

**Issue by robomotic** [facebook/prophet#1736]
Hi there,
I am looking either to contribute or to start on a fbprophet based web application (Flask or Django) that implements the human supervised approach described in the paper.
Are there any active projects I could contribute or something I could start?
I have some decent experience in Flask/Django  but don't want to replicate existing efforts.
Any pointers to existing projects would be great.
Cheers!

**Comment by bletham** [comment]
#898 and #686 could be useful to you!
