### ISSUE TITLE
I ran into an error while running the official example

### ISSUE THREAD

**Issue by a715471304** [facebook/prophet#1741]
Guys，please help me.I used this pack for the first time,and I ran into an error while running the official example.Here is my code and error report.If you can help me solve this problem, I will be very grateful.

import pandas as pd
from fbprophet import Prophet

df = pd.read_csv('example_wp_log_peyton_manning.csv')
m = Prophet()
m.fit(df)
KeyError: 'metric_file'
Exception ignored in: 'stanfit4anon_model_f5236004a3fd5b8429270d00efcc0cf9_7332008770348935536._set_stanargs_from_dict'
KeyError: metric_file

**Comment by Siddhant-K-code** [comment]
Please refer to #1670 
Summary:
> Upgrade pandas to ver 1.0.4 and pystan to ver 2.19.1.1

**Comment by a715471304** [comment]
Thank you very much.

**Comment by Siddhant-K-code** [comment]
Maintainers Can Close this issue now!
