### ISSUE TITLE
Skipping MAPE because y close to 0. How can I calculate MAPE if Christmas day sales are always zero?

### ISSUE THREAD

**Issue by soliverc** [facebook/prophet#1743]
I know why the error occurs during `performance_metrics`, as explained in issue 1539: https://github.com/facebook/prophet/issues/1539

However, I'd like to know how to get around it in my sales data.

There is always a zero in my data every year as the shop is closed on Christmas day. 

So because of this one day, during 3 years worth of data I have, I am unable to calculate MAPE? 

What's the best way to get around this? 

I thought of imputing, but wouldn't that affect the holidays I have loaded into the model? 

What about replacing the zero with €1 worth of sales?

**Comment by hansukyang** [comment]
There are alternative metrics to MAPE that may be suitable. I use [SMAPE](https://en.wikipedia.org/wiki/Symmetric_mean_absolute_percentage_error) for some of my work that might be an option, or [weighted-average - WAPE](https://en.wikipedia.org/wiki/Mean_absolute_percentage_error#Alternative_MAPE_definitions).

**Comment by bletham** [comment]
@soliverc Sorry for the slow reply. I think the best option here would be to just drop from the dataframe any dates where the store is closed; then it won't ry to predict for that date. Prophet doesn't have an issue with missing dates so no need to keep them in there.

**Comment by soliverc** [comment]
Thank you for the tip. Will try that.
