### ISSUE TITLE
define daily, weekly, yearly seasonality parameter in Prophet if i have dataset made per hour

### ISSUE THREAD

**Issue by rlaals7349** [facebook/prophet#1747]
hello, prophet is really good tool ! thanks. i made a model using some dataset made per hour

and i think fitted pretty well. but there are two things i wondering or maybe misunderstanding.

first, how can define daily, weekly, yearly seasonality in function Prophet if i have data made per hour.

for example, if one day is splitted 1 hour, i will get 24 data from 1 daily data.  and weekly is 24*7, which have seasonality daily and weekly

in this case, can i define daily_seasonality=24, weekly_seasonality=24*7 in function Prophet() ? 
i want to know this is correct way to define seasonalities

second one is about holiday. 
if i have some data as above, should i define hoilday as [ 2020-12-02 : 01:00:00, 2020-12-02 02:00:00, 2020-12-02 03:00:00 ... ] 
when i want to make 2020-12-02 to holiday

Thanks!!

**Comment by GinoWoz1** [comment]
Yearly seasonality, weekly seasonality and daily seasonality parameters are the # of fourier terms that will be used to make-up the 'wave-length' patterns in our data set. If you set all of those to true it will be default set yearly to 10, weekly to 3 and daily to 4. 
For some intuition on what the parameters mean please take a look at https://medium.com/@khairulomar/deconstructing-time-series-using-fourier-transform-e52dd535a44e. The argument is not the number of periods.

As for the holidays, I am pretty sure you pass in the holiday value per day and it fits regressors to the days and estimates the effect. I am unsure if you are setting a certain hour to a holiday, though.

**Comment by rlaals7349** [comment]
Thanks your answer. as you said, i was misunderstanding about Yearly, weekly, daily seasonality params. 👍
