### ISSUE TITLE
What could cause facebook's Prophet model to do so poorly on these procedurally generated datasets, where one is a continuation of the other

### ISSUE THREAD

**Issue by arid-mangoss** [facebook/prophet#1755]
Recently I've been looking into some easy out of the box modeling using Facebook's Prophet -- potentially to use in some projects at work. So far, I have been super impressed with everything that I've seen people use it online. Their first demo using the Peyton Manning Wikipedia page views is pretty impressive  [**see here**][1]

I started playing with it and I had a hard time getting the package `fbprophet` installed in python. I'm on windows and there's some CPP compiling going on which apparently can cause issues. So, anyway I switched over to R. I thought I would throw Prophet a softball, and see how it did on a dataset that I generated programmatically. Here is some R code that you can run so you can see what I mean:

``` R
install.packages('prophet')
library(prophet)

f = function(numDays){
  set.seed(10000)
  
  startDate = as.Date('2000-01-01')
  endDate = startDate + numDays - 1
  
  history <- data.frame(ds = seq(startDate, endDate, by='d'), y = sin(1:numDays/100 ) + rnorm(numDays)/4)
  m = prophet(history)
  future <- make_future_dataframe(m, periods = 365)
  forecast <- predict(m, future)
  plot(m, forecast)
}
```

Here are some results of this simple plotting function that I made. 

First with 6000 days of data:
``` R
f(6000)
```
[![enter image description here][2]][2]

Second with 1000 days of data:
``` R
f(1000)
```
[![1000 days][4]][4]

Some **comments** on the plots:
Clearly, something went wrong here!?
Note that the two datasets are the exact same for the first 1000 points. Yet the forecast with fewer points is more accurate. This is counterintuitive to what I would expect. 
Also, the data is clearly seasonal -- though the seasonality does not have a period of exactly 1 year. 

So, my **questions** are, what tweaks do I need to make to this model to get it to fit the data somewhat well? It does well fitting the data historically for the second model but does poorly on the forecast projection considering the 'obvious' sine curve. I mean, it seems like this is supposed to work well right out of the box (and it seems to have for everything I have seen online), but this is the first case that I've seen it do poorly -- and this seems like a much simpler dataset to fit than some of the other demos online. Or maybe it's the randomly generated data that threw it off?

I am looking for some insight from those with a bit more experience than me when it comes to time series modeling. 

  [1]: https://facebook.github.io/prophet/docs/quick_start.html#r-api
  [2]: https://i.stack.imgur.com/Tz7t1.png
  [3]: https://i.stack.imgur.com/KuOOW.png
  [4]: https://i.stack.imgur.com/2oITC.png

**Comment by benmwhite** [comment]
The default model only fits weekly and yearly seasonalities, but your synthetic time series has a 100 day periodic behavior. If you add a 100 day seasonal component you should see a much better fit.
