### ISSUE TITLE
Kernel Fails when fitting model in Datalore

### ISSUE THREAD

**Issue by goncaloperes** [facebook/prophet#1756]
I am using FBProphet (0.7.1) on a Notebook in Datalore (Basic Mahcine with IPython kernel).

Anytime I try to fit a model with FBProphet, such as

```
# fit model
model = Prophet()
model.fit(peyton)
```

It shows the info

> INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.

And the Kernel fails in less than 10s.

[This is the dataset ](https://raw.githubusercontent.com/PinkWink/DataScience/master/data/07.%20example_wp_peyton_manning.csv) that I am using.

**Comment by LukeScales1** [comment]
have you tried using `parse_dates=["ds"]` when reading the csv file? i.e. `pd.read_csv('route-to-file', parse_dates=["ds"], index_col=0)`

**Comment by goncaloperes** [comment]
It may be a problem related with Datalore as if one imports and fits the model within the same cell the Kernel doesn't die.

**Comment by goncaloperes** [comment]
Just added the Notebooks to a Workspace and changed the way the data was being read solved

  ```
from fbprophet import Prophet
!wget = 'https://raw.githubusercontent.com/PinkWink/DataScience/master/data/07.%20example_wp_peyton_manning.csv'
data = '07. example_wp_peyton_manning.csv'
peyton = pd.read_csv(data)
```

And then fitting the model
```
m = Prophet()
m.fit(peyton)
```
And the Kernel didn't fail.

It could have been a problem with Datalore.
