### ISSUE TITLE
Error in m.add_country_holidays(country_name='IL')

### ISSUE THREAD

**Issue by RazHadas** [facebook/prophet#1757]
Hi,
Python 3.7
windows 10
Jupyter notebook
I get this error:m.add_country_holidays(country_name='IL')
![image](https://user-images.githubusercontent.com/65238333/102201616-08b27e80-3ecf-11eb-9ddd-c8fadc4aad25.png)

Do you know this issue?

Thanks

**Comment by bletham** [comment]
It looks like this is coming from the `holidays` package, that it is failing to compute the date of Passover for some year.

I haven't been able to reproduce this issue yet. It looks like it is coming from this call:
```Python
from fbprophet.make_holidays import get_holiday_names
get_holiday_names('IL')
```
which runs for me. Does it error for you?
What versions of fbprophet and holidays are you running?

**Comment by talkthattalkjr** [comment]
#talkthattalkjr

**Comment by aletelecom** [comment]
I have a similar error when I try to add the holidays from Chile (CL), I get the error "TypeError: Invalid input types"
