### ISSUE TITLE
How to fit Prophet to a weekly aggregated data?

### ISSUE THREAD

**Issue by soumitra9** [facebook/prophet#1763]
I have data that is aggregated on a weekly level. It looks something like this

4     96
5     97
6     98

The first column is the week of the year. I am aware prophet requires the DateTime ds column for modeling. How do I tweak my data to use the prophet?

**Comment by benmwhite** [comment]
You'll have to create a column of weekly timestamps, for instance the dates for the corresponding Sundays or Mondays. If you're using R then the [lubridate](https://lubridate.tidyverse.org/) package should help.

**Comment by soumitra9** [comment]
Thanks. That's really helpful.
