### ISSUE TITLE
plot_cross_validation_metric in v0.7.1

### ISSUE THREAD

**Issue by ggrrll** [facebook/prophet#1771]
Hi, 

it seems that the function `plot_cross_validation_metric` does not exist anymore in v0.7.1 - is that correct?
If that's the case, maybe it would be better to update the docs here
https://facebook.github.io/prophet/docs/diagnostics.html

(I am using the python api)

Thanks for the package and happy new year :clinking_glasses:

**Comment by bletham** [comment]
It's still there - https://github.com/facebook/prophet/blob/20f590b7263b540eb5e7a116e03360066c58de4d/python/fbprophet/plot.py#L471
and this should work
```Python
from fbprophet.plot import plot_cross_validation_metric
```
Does that not work for you?

**Comment by ggrrll** [comment]
never mind -- my fault -.-
