### ISSUE TITLE
holidays setting not supported

### ISSUE THREAD

**Issue by JohnnyYuan93** [facebook/prophet#1774]
holidays setting not working with pandas 1.1.4, Please help to fix this.

**Comment by bletham** [comment]
I'm not seeing any issues with pandas 1.1.4, what issue are you running into? If it is #1617 be sure to ugprade fbprophet to 0.7.1.

**Comment by JohnnyYuan93** [comment]
> I'm not seeing any issues with pandas 1.1.4, what issue are you running into? If it is #1617 be sure to ugprade fbprophet to 0.7.1.

It is like 1617, Thanks for the help!
