### ISSUE TITLE
prophet_plot_compents error

### ISSUE THREAD

**Issue by soyeon-kang** [facebook/prophet#1781]
> plot(m, forecast)
Error in unit(unclass(x), attr(x, "unit"), attr(x, "data")) : 
  Invalid unit
> prophet_plot_components(m, forecast)
Error in unit(unclass(x), attr(x, "unit"), attr(x, "data")) : 
  Invalid unit

How can I solve this problem?

I tried dyplot.prophet instead of plot(m, forecast) it works well.

**Comment by arid-mangoss** [comment]
Could you please post a reproducible example that we can run? Thanks!
