### ISSUE TITLE
how do I extract growth model parameters?

### ISSUE THREAD

**Issue by j3ch** [facebook/prophet#1784]
I'd like to extract the parameters for the growth curves, so I can save it for later and do other processing. 
It's easy to get the slope/intercept for linear or exponential growths, but it's not as straight forward for logistics growth?

Not that I can't, but is there a way to get these parameters directly out of Prophet?

**Comment by bletham** [comment]
The parameters for the logistic growth curve are `k` and `m`, and are in `m.params`. But note the model is fit after scaling time to [0, 1], and normalizing `y` according to `m.y_scale`. So you would need to undo those transformations if you use the parameters to evaluate the model. See https://github.com/facebook/prophet/issues/1229#issuecomment-579550020.

**Comment by j3ch** [comment]
oh! thanks so much for the info! @bletham 

Wasn't sure how to interpret the values in `params`, considering it stores `k` and `m` by iterations.
Would the final model after the last change point be the first or the last iteration?

Would it be accurate to say the models are 
linear:  y = kx + m
logistic: y = cap / (1 + e^(-k*(x - m))


Could this information be added to the documentation somewhere? I think it'd be really helpful, instead of referencing github comments

**Comment by j3ch** [comment]
going to close anyway. thanks @bletham

**Comment by bletham** [comment]
@j3ch when you say it saves it per iteration, I'm guessing you are doing MCMC And seeing that it is stored per MCMC iteration?

The prediction will actually be made with the posterior mean of the parameters. That happens here:
https://github.com/facebook/prophet/blob/57230997baf04f44e6d1359e08ccbc84a01dda3d/python/fbprophet/forecaster.py#L1310-L1312
and then yes, those would be the correct formulae if there were no changepoints. The formulas for the piecewise versions are a little more complicated and are in the paper, or in the code here:
https://github.com/facebook/prophet/blob/57230997baf04f44e6d1359e08ccbc84a01dda3d/python/fbprophet/forecaster.py#L1223
https://github.com/facebook/prophet/blob/57230997baf04f44e6d1359e08ccbc84a01dda3d/python/fbprophet/forecaster.py#L1250
