### ISSUE TITLE
Missing time-point (date) handling - replacement with 0

### ISSUE THREAD

**Issue by aigym** [facebook/prophet#1788]
If a time period (in my case Date) is missing, currently my understanding is that prophet interpolates with piecewise regression (this is a kind of imputation). Often, missing dates could also mean 0 transactions. This would change the response and model completely? 

Is there a functionality or configuration within prophet to add missing time rows and replace NA with 0, rather than interpolation?

**Comment by HarisNaveed17** [comment]
Hello,
I'm not sure if what you want can be done in Prophet, but it is possible via Pandas. 
You can create a datetime Index and then re-index your time series using that. The reindex function allows you to fill missing values for a particular date with 0, np.nan or anything really. 
Hope this helps!

**Comment by bletham** [comment]
That is correct, missing data would be in essence imputed and would not be implied to have a zero value. If you do need it to be 0, you'd want to replace the missing data with 0s prior to passing it to Prophet. As @HarisNaveed17 notes, this is something that pandas has a lot of functionality around, and so I think it'd be better to do it in pandas before sending the data into fbprophet than to try to push the functionality into fbprophet.
