### ISSUE TITLE
Forecast peak values

### ISSUE THREAD

**Issue by philipandreadis** [facebook/prophet#1791]
Greetings, I am trying to forecast hourly energy consumption in Kwh. My model is able to capture the seasonality effects but it fails to forecast efficiently some extreme values (>1.25 Kwh) which cannot be considered outliers because they occur quite often. This problem affects negatively the model accuracy and I cant find a way to overcome it. 
![proph](https://user-images.githubusercontent.com/33031735/105541294-35448c00-5d00-11eb-948c-245e847033e9.png)

I use the following tuning on 9 months worth of hourly consumption.

m = Prophet(weekly_seasonality=True,daily_seasonality=False,yearly_seasonality=False,
            changepoint_prior_scale = 30,
            seasonality_prior_scale=30,
            seasonality_mode='multiplicative',
            growth='linear'
           ).add_seasonality(name='dailyc',period=1,fourier_order=15,prior_scale=50
           ).add_seasonality(name='half_dailyc',period=0.5,fourier_order=10,prior_scale=50
           ).add_country_holidays('UK')

I would like to know if there is a way to make the model more flexible in order to capture these values.
Thank you in advance.

**Comment by bletham** [comment]
I think the key here is that the model is going to fit a stationary seasonality, meaning the amplitude will be constant relative to the trend (which here is constant). So the afternoon spike will be assumed to be the same every day, and what you get is something like the average afternoon spike, which is of course missing a lot of variance. To do a better job here, you have to somehow be able to indicate to the model why the spike is high on some days but low on others. For instance, 3/2 had a very low afternoon spike, and 3/8 had a very high afternoon spike. The model doesn't have any way of knowing why 3/8 should be different than 3/2. So if you do have access to some external information about which days have the higher spikes, you'd need to get that into the model somehow. For instance, if it is a weekly seasonal effect (e.g. Mondays have higher spikes than Sundays) then you could capture this using conditional seasonalities, to specify separate daily seasonalities for Mondays vs. Sundays, so they can each capture the appropriate afternoon activity level (https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#seasonalities-that-depend-on-other-factors).
