### ISSUE TITLE
I want to install routersploit but

### ISSUE THREAD

**Issue by Danish391** [facebook/prophet#1793]
I want to install routersploit but 
python rsf.py 
shows error
![Screenshot_1611575089519](https://user-images.githubusercontent.com/77969619/105703772-8e463700-5f2f-11eb-8eed-859ad764980a.jpg)
plzz help me to fix it

_Originally posted by @Danish391 in https://github.com/facebook/prophet/issues/419#issuecomment-766770803_

**Comment by bletham** [comment]
This issue tracker is for a different package.

**Comment by Danish391** [comment]
Sir can you help me to install it with details
