### ISSUE TITLE
Code in CRAN for cross_validation doesn't have cutoffs= argument

### ISSUE THREAD

**Issue by adrianabp** [facebook/prophet#1797]
Hi,
I installed Prophet from CRAN (version 0.6.1). It's working fine. 
When trying to use cutoffs dates for cross_validation I got the following error:

Error in cross_validation(m, cutoffs = cutoffs2, horizon = 720, initial = 17616,  : 
  unused argument (cutoffs = cutoffs2)

I checked the source code in CRAN and it doesn't have the cutoffs argument (in diagnostics.R):
cross_validation <- function(
    model, horizon, units, period = NULL, initial = NULL) {
  df <- model$history
  horizon.dt <- as.difftime(horizon, units = units)
.....................

 But version in GitHub has the cutoffs argument:
cross_validation <- function(
    model, horizon, units, period = NULL, initial = NULL, cutoffs=NULL) {
  df <- model$history
  horizon.dt <- as.difftime(horizon, units = units)
........................

Is the CRAN version going to be updated soon, or should I clone the version from here?
Thanks,
Adriana

**Comment by bletham** [comment]
We had major issues trying to get the latest version in CRAN because of some windows building issues, but those should be fixed now so we do need to try again. But in the meantime it is easy to download from here:
```R
devtools::install_github('facebook/prophet', subdir='R')
```

**Comment by sflalek** [comment]
Hi @bletham - any update on the latest CRAN version? Would like to use the cutoffs functionality and my IT are reluctant to allow Github installation.

**Comment by bletham** [comment]
This finally made it! The CRAN submission process involves a manual review that can be a bit slow (we initially submitted it on Mar 24) but it's through and you can now install v1.0 from CRAN.
