### ISSUE TITLE
Unexpected spikes in the forecasts

### ISSUE THREAD

**Issue by lohraspco** [facebook/prophet#1801]
Hi,

I am using your awesome package to forecast time series data. However, I have some issues with the forecast that I don't know if I can resolve it with the FB Prophet package. There are some spikes in the prediction that do not follow the pattern in the historical data. Is there a way to fix this?

Here are some forecast examples: 
![image](https://user-images.githubusercontent.com/25494629/106165315-992be200-6150-11eb-9267-ed102b489f2d.png)

![image](https://user-images.githubusercontent.com/25494629/106165329-9f21c300-6150-11eb-8c4d-fbd4afb9ee36.png)
![image](https://user-images.githubusercontent.com/25494629/106165348-a517a400-6150-11eb-9286-b3acd0fdea95.png)

Best regards,

**Comment by bletham** [comment]
hm it looks like there is an overfit seasonality, maybe something along the lines of https://facebook.github.io/prophet/docs/non-daily_data.html#monthly-data . Let's focus on just one of these forecasts (perhaps the first one). What's the data frequency? Is it exactly monthly, and is it always on the first day of the month? What are the dates you are making predictions for in the plot? Are they also monthly and also consistent with the training data (e.g. first day of month)?

If you post the components plot from `m.plot_components(fcst)` that would also be helpful for identifying an overfit seasonality.
