### ISSUE TITLE
Cross validation understanding

### ISSUE THREAD

**Issue by pamparana34** [facebook/prophet#1811]
I have a small technical question and I hope it is ok to ask here.

Why does cross validation need a fitted model to be initialised. As I understand it, it will run multiple model fits with increasing history size and average the error across these runs and we can then use it to select the best hyper parameters.

However, why does it need the initial fitted model. All examples I see online, fit an initial model on all the data. Why is that?

**Comment by bletham** [comment]
Good question and definitely the right place to answer it. This came up recently in #1409, and I gave an answer there that I hope is satisfactory, but feel free to post follow-up questions and we can discuss further!
