### ISSUE TITLE
With cmdstanpy, warm-starting the fit from the model parameters is not possible

### ISSUE THREAD

**Issue by loulo1** [facebook/prophet#1814]
Hello,

I tried to do a warm-starting as it is written in the documentation:
m2 = Prophet().fit(df, init=my_paramater)

It worked with pystan but it does not work with cmdstanpy as stan_backend. 

I looked at the code to understand why I could not set an init parameter when the stan_backend is cmdstanpy.
And I found a difference of behavior between the backend stanpy and the backend cmdstanpy.

In the module https://github.com/facebook/prophet/blob/master/python/fbprophet/models.py
when I look at the class PyStanBackend(IStanBackend), 
I see in the method def fit(self, stan_init, stan_data, **kwargs) -> dict
And inside this method we see that the init in "Prophet().fit(df, init=my_paramater)" is take in account:

`def fit(self, stan_init, stan_data, **kwargs) -> dict:
        args = dict(
            data=stan_data,
            init=lambda: stan_init,
            algorithm='Newton' if stan_data['T'] < 100 else 'LBFGS',
            iter=1e4,
        )
        args.update(kwargs)  <-------------------------- here the init parameter is overriden with our paramater`

But in the class CmdStanPyBackend(IStanBackend), in the same method the init parameter is never overriden with our parameter.

`def fit(self, stan_init, stan_data, **kwargs):
        (stan_init, stan_data) = self.prepare_data(stan_init, stan_data)
        if 'algorithm' not in kwargs:
            kwargs['algorithm'] = 'Newton' if stan_data['T'] < 100 else 'LBFGS'
        iterations = int(1e4)
        try:
            self.stan_fit = self.model.optimize(data=stan_data,
                                                inits=stan_init,
                                                iter=iterations,
                                                **kwargs)`

Is there a solution to do a warm-starting with fbprophet when the stan_backend is CmdStanPyBackend please?
Thanks in advance

**Comment by tcuongd** [comment]
I think you're right, the `.update()` is missing from the CmdStanPyBackend code. There doesn't seem to be a clean way to cleanly pass in `inits` to the cmdstanpy functions unfortunately.

Would you be able to raise a PR to fix this bug? Happy to help as well.

**Comment by loulo1** [comment]
Hello,

Ok thank you for your answer.
I will do it
