### ISSUE TITLE
problem when trying to install cloudbox dependency

### ISSUE THREAD

**Issue by freedom1701** [facebook/prophet#1815]
Hello
I am a novice
I'm on ubuntu
when i try to install the cloodbox dependency it gives me this error message

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-tvla3mry/cryptography/

can you help me?
thank you

**Comment by bletham** [comment]
This issue tracker is for a different project, you'll want to find the one for cloudbox.
