### ISSUE TITLE
Importing dumped pickle generated model or JSON format model in browser

### ISSUE THREAD

**Issue by pradip-interra** [facebook/prophet#1819]
Hello Experts,

It's not an issue, rather more of a query. 

We are trying to save a Prophet learned model using both pickle and in JSON format. 

The purpose is that: we would like to import that model into a browser and do some inference based on the limited, realtime dataset available in the browser.  In browser we are using tensorflow JS layers to load the model (something like that):

model = await tf.loadLayersModel('models/model.json');

However what we are seeing that it's not getting loaded properly. The weights and the architectures are not exported. We are getting an error like "Architecture Details are missing." 

To investigate further, we did tried out the tensorflow converter as well to convert this Keras model to tensorflow JS model. That also did not helped us.

Please suggest if we are grossly missing anything or if you have some way around as a recourse.

Thanks,
Pradip

**Comment by bletham** [comment]
It looks like you're using Tensorflow to try to load the model, but Prophet isn't a Tensorflow model (or keras). To deserialize it you would use the built-in deserialization function, which will have to be done in python. There isn't going to be a way to evaluate the model in js. The closest thing I'm aware of is the NeuralProphet project which is implemented in pytorch: https://github.com/ourownstory/neural_prophet
