### ISSUE TITLE
make_future_dataframe(periods=7) generating 206 rows

### ISSUE THREAD

**Issue by akshitgupta29** [facebook/prophet#1822]
Team,

I am new to fb prophet and I want to do a forecast for the next 7 days using the model. I am trying to create the future data frame by using the 
`future = model.make_future_dataframe(periods=7) `

but if I see the shape of the future df, it is showing as 206 instead of just 7. Can anyone please help me with the problem, issue here.

`future.shape`

![image](https://user-images.githubusercontent.com/12370891/108243510-2ec8f900-7174-11eb-944b-1a1651746908.png)

**Comment by JeremyKeustersML6** [comment]
Can you maybe share (a part of) the DataFrame that you used to fit the model and also share (a part of) the `future` DataFrame that was generated? I suppose there's something wrong with the DataFrame that you use to fit your model.

**Comment by akshitgupta29** [comment]
Thanks for the help and confirmation. My bad, I have missed the part that the future data frame has a history as well.

**Comment by JeremyKeustersML6** [comment]
You're welcome, glad I could help!
