### ISSUE TITLE
Difference between add_holidays() and add_regressors()

### ISSUE THREAD

**Issue by muhlbach** [facebook/prophet#1828]
Hi there! First, thank you guys for a great library!

Second, I have a question regarding the two functionalities: `add_holidays()` and `add_regressors()`. I've built by own time-series cross-validation class, taking an instance of `Prophet()` as an input. Say I add some regressors via `add_regressors()` and that I try different values of `holidays_prior_scale`. Will these two play nicely together? I've read that `add_regressors` uses `holidays_prior_scale` as default, but I want to be sure.

Thanks in advance!

**Comment by tcuongd** [comment]
> I've read that add_regressors uses holidays_prior_scale as default

That's correct: https://github.com/facebook/prophet/blob/master/python/fbprophet/forecaster.py#L617

It'll also use `seasonality_mode` by default if you don't specify `mode='additive'|'multiplicative'`
