### ISSUE TITLE
Change noise estimation to vectorized calculation

### ISSUE THREAD

**Issue by gidutz** [facebook/prophet#1831]
The process of estimating the confidence intervals is currently done [iteratively](https://github.com/facebook/prophet/blob/20f590b7263b540eb5e7a116e03360066c58de4d/python/fbprophet/forecaster.py#L1387), and consumes a lot of time.
Since process is not dependent between iterations it should be done in a single run using vectorized programming.

```python 
        for i in range(n_iterations):
            for _j in range(samp_per_iter):
                sim = self.sample_model(
                    df=df,
                    seasonal_features=seasonal_features,
                    iteration=i,
                    s_a=component_cols['additive_terms'],
                    s_m=component_cols['multiplicative_terms'],
                )
                for key in sim_values:
                    sim_values[key].append(sim[key])
        for k, v in sim_values.items():
            sim_values[k] = np.column_stack(v)
        return sim_values
```

**Comment by bletham** [comment]
The challenge (and most computationally expensive part of `predict` I believe) is in sampling from the future trend distribution. That happens in this function that generates changepoints from the generative model:
https://github.com/facebook/prophet/blob/20f590b7263b540eb5e7a116e03360066c58de4d/python/fbprophet/forecaster.py#L1479

I suspect this function would be really challenging to vectorize, for instance the number of changepoints will be different in different samples.
