### ISSUE TITLE
Responsiveness of the graphs produced by forecasting

### ISSUE THREAD

**Issue by CalgaryBro** [facebook/prophet#1832]
Is there any way to make fbprophet python responsive to screen size?

**Comment by anshpujara14** [comment]
Would you like to have the graphs in full screen?

**Comment by CalgaryBro** [comment]
Full screen and on mobile phones as well. Right now they are a little restricted to a specific figure size.

**Comment by bletham** [comment]
Plot rendering is happening entirely within matplotlib (or plotly if you're using that plot method). I'm not sure if responsive plots are possible within matplotlib, but if they are, then you should be able to get them to work with fbprophet. Basically when you make an fbprophet plot you can pass in the matplotlib axes for it to plot on; the `ax` input here:
https://github.com/facebook/prophet/blob/fae1ac1f9a878879960722e8b3d72d45a0340b94/python/fbprophet/forecaster.py#L1573

You'd need to figure out how to get matplotlib to give you an axes object for a responsive figure.

In the plotly plotting the figure is made inside the function and there isn't a way to have it use a different one (i.e. one that has been setup to be responsive), so if you want to try to do this in plotly you'd probably be best off copying the code out of this function and then just editing it as needed to get responsiveness:

https://github.com/facebook/prophet/blob/fae1ac1f9a878879960722e8b3d72d45a0340b94/python/fbprophet/plot.py#L551

**Comment by CalgaryBro** [comment]
Thanks for your response. I was able to make it responsive by removing the figuresize argument from inside plot_plotly. That enabled the original plotly library to make fbprophet produced graphs responsive.
