### ISSUE TITLE
How can I identify which timesteps were considered important by fb prophet?

### ISSUE THREAD

**Issue by Subh1m** [facebook/prophet#1833]
I have a univariate time series dataset. But, its not able to forecast that great using fb prophet.

Is it possible to know/interpret which timesteps are considered important by the model.
You can compare this with feature importance in lime, just that I would like the same on time series data.

**Sample input:**
ds | y
----------|---------
1950-01-01  |  352  
1950-01-02  |  351
1950-01-03  |  350
1950-01-04  |  352
1950-01-05  |  353
1950-01-06  |  341  
1950-01-07  |  343
1950-01-08  |  348
1950-01-09  |  349
1950-01-10  |  358

**Forecast from Prophet:**
ds | y
----------|---------
1950-01-11  | 352
1950-01-12  | 346
1950-01-13  | 348
1950-01-14  | 355

**Output I require:**
ds | y | importance
----------|---------|-----------
1950-01-01  |  352  | 11%
1950-01-04  |  352  | 8%
1950-01-05  |  353  | 5%
1950-01-10  |  358  | 1%

Importance: How much contribution did that particular timestep have in the forecast by the model. Just like feature importance in multivariate but here the feature is timestep (since its a univariate dataset).

**NOTE: Please note that I am looking for fb prophet model optimization but a way to interpret the model & results in an MLI / explainable ai fashion.**

Also, can you please suggest any other machine learning explainable ai concepts which can be derived using fb prophet model?

**Comment by bletham** [comment]
I think the better parallel to feature importance would be the components plot (`m.plot_components(fcst)`) where it will show how much of y is being attributed to each component in the model (trend, weekly seasonality, yearly seasonality, etc.). Those are the features in the model that are being used to try to predict y.

What you have described is something like "example importance". In a regular ML model of predict Y from X, feature importance is the importance of each column of X, whereas what you have asked for is the importance of each row of X. You could estimate this by leaving out each row and then re-training the model and seeing how much the prediction changed, but it doesn't seem to be a very typical practice to evaluate something like that.

**Comment by Subh1m** [comment]
Thanks for the quick response. I understand the plot_components part and will try it.
The trouble I am having is, using supervised feature extraction, I can get the feature importance for the first forecast value but when  I try to get the importance for the 2nd/3rd/4th forecast, the results cannot be validated, as there is no data available to verify it against.

w.r.t. example, using the supervised method, I can get the importance (timesteps) for the first forecast value (1950-01-11), but if I want to obtain the importance for the next time step, I need to consider the 1st forecast as an input, which may/may not be correct. Thus, my goal is to get the importance for every forecast only w.r.t. the training data.

Attaching the URL for supervised feature importance: 
https://machinelearningmastery.com/feature-selection-time-series-forecasting-python/

**Comment by bletham** [comment]
The Prophet model has a very different structure than the models used in the URL there. There they are lagging variables to use as features in a model, so you can look at the importance of each lag. There is no lagging involved in the Prophet model. The features are things like the seasonalities and trend, which you can see the importance of via the components plot or via their columns in the forecast dataframe.
