### ISSUE TITLE
can't open file 'setup.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by sulastambunan** [facebook/prophet#1837]
![image](https://user-images.githubusercontent.com/66982223/110265473-3b5fa500-7fee-11eb-9844-55d5cecb7842.png)

![image](https://user-images.githubusercontent.com/66982223/110265511-4adeee00-7fee-11eb-8d9f-ed23c15c8a78.png)

![image](https://user-images.githubusercontent.com/66982223/110265533-57fbdd00-7fee-11eb-9b99-6ff4a3c2fbc4.png)

I'm trying to detekso objek faster from the following yt link: https://www.youtube.com/watch?v=89ADk0k1mEo and medium link: https://medium.com/analytics-vidhya/training-an-object-detection-model-with-tensorflow-api-using-google-colab-4f9a688d5e8b
 But there is an error like the description above. 
Looks like  PYTHONPATH that  did not work. But I am confused how to solve it.

**Comment by bletham** [comment]
This issue tracker is for a different package.
