### ISSUE TITLE
Troubles getting prophet to work in Python

### ISSUE THREAD

**Issue by CJax137** [facebook/prophet#1845]
I've installed using conda following the directions. I'm simply trying to run the example given at https://facebook.github.io/prophet/docs/quick_start.html#python-api to verify everything is working. As soon as I run the m.fit(df) command, I get the error

INFO:numexpr.utils:NumExpr defaulting to 4 threads.
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
KeyError: 'metric_file'

and the kernel blows up. Any guidance appreciated.

**Comment by CJax137** [comment]
Found a solution from https://github.com/alan-turing-institute/sktime/issues/666 ... thank you @aiwalter from that channel.

For anyone else banging their heads on getting fbprophet up and running, this worked for me:
Basically, take a deep breath and start from the beginning...

conda uninstall -y pystan fbprophet
conda install libpython m2w64-toolchain -c msys2
conda install -c conda-forge pystan
conda install -c conda-forge fbprophet


In precisely this order!
Cheers!

**Comment by bletham** [comment]
I'm glad you were able to find a solution, this came up in #1670 and I still hadn't quite figured out what was happening!
