### ISSUE TITLE
R CI with Github Actions

### ISSUE THREAD

**Issue by tcuongd** [facebook/prophet#1847]
It seems that Github Actions is now available for R. Some references:

- https://github.com/r-lib/actions
- https://www.jimhester.com/talk/2020-rsc-github-actions/

Should we look at getting the CI checks for R back?

**Comment by bletham** [comment]
Oh that's great to see, thanks for the heads up! When I had to switch things over to Github Actions I couldn't find any resources at that time on how to do CI for R, so I'll have to watch the video there and see what we can do.

**Comment by tcuongd** [comment]
Yeah just found this guide as well which seems quite comprehensive: https://ropenscilabs.github.io/actions_sandbox/index.html

If I get some free time I'm happy to help as well :)

**Comment by tcuongd** [comment]
https://github.com/facebook/prophet/pull/1891
