### ISSUE TITLE
Simulated Historical Forecast: Training Duration

### ISSUE THREAD

**Issue by thanatchon36** [facebook/prophet#1861]
According to A simulated historical forecast on the Peyton Manning dataset: [Here](https://facebook.github.io/prophet/docs/diagnostics.html)

"Here we do cross-validation to assess prediction performance on a horizon of 365 days, starting with 730 days of training data in the first cutoff and then making predictions every 180 days. On this 8 year time series, this corresponds to 11 total forecasts.":
Initial = 2 years
Horizon = 1 year
Period = 6 months

I was wondering that whether this setting could mean first experiment setup or the second:

First experiment setup:
1st forecast >>>    Train period: 2008-01 to 2010-01, Test: 2010-01 to 2011-01 (train duration 2 years)
2nd forecast >>>   Train period: 2008-06 to 2010-06, Test: 2010-06 to 2011-06 (train duration 2 years)
3rd forecast >>>    Train period: 2009-01 to 2011-01, Test: 2011-01 to 2012-01 (train duration 2 years)
....
....
....
11th forecast >>>  Train period:2013-01 to 2015-01, Test: 2015-01 to 2016-01 (train duration 2 years)

Second experiment setup:
1st forecast >>>    Train period: 2008-01 to 2010-01, Test: 2010-01 to 2011-01 (train duration 2 years)
2nd forecast >>>   Train period: 2008-01 to 2010-06, Test: 2010-06 to 2011-06 (train duration 2.5 years)
3rd forecast >>>    Train period: 2008-01 to 2011-01, Test: 2011-01 to 2012-01 (train duration 3 years)
....
....
....
11th forecast >>>  Train period:2008-01 to 2015-01, Test: 2015-01 to 2016-01 (train duration 7 years)

Could anyone please verify the correct experiment setup?

**Comment by bletham** [comment]
It's the 2nd: the training period always starts at the start of the history. There has recently been some confusion on this point, I think the documentation needs to be clarified.

**Comment by tachon36** [comment]
@bletham Thank you so much :D

**Comment by thanatchon36** [comment]
@bletham Thank you so much :D
