### ISSUE TITLE
Unable to install prophet from anaconda. pystan is OK!

### ISSUE THREAD

**Issue by wjcper2008** [facebook/prophet#1868]
The main issue is can not find prophet via **conda install -c conda-forge prophet**

Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - prophet

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

**How can I address this, thanks! The system is windows 10.**

**Comment by candalfigomoro** [comment]
The recipe PR is still unmerged: https://github.com/conda-forge/staged-recipes/pull/14408

**Comment by nviet** [comment]
On the Anaconda repository, the latest version of _prophet_ is v0.2.1 for Windows 32-bit and v0.7.1 for Windows 64-bit. As of v1.0, the package name on PyPI is _prophet_; prior to v1.0 it was _fbprophet_. Therefore you have to run the command with the old package name _fbprophet_ instead.

If you want to install the latest version of _prophet_ (v1.0 at the moment which is not available on the Anaconda repository yet), you have to download the code as ZIP file, extract the file and run the **setup.py** file from your Anaconda environment. You might need to install few more dependencies but the process is straight-forward and should only take a couple of minutes. I also successfully installed on my Windows 10 64-bit.

**Comment by bletham** [comment]
Like @candalfigomoro noted, there was some delay in getting the conda forge recipe reviewed and merged. It has now been merged so this should now work via conda forge.

**Comment by candalfigomoro** [comment]
@bletham Unfortunately, with the new "prophet" conda-forge package, I get the infamous `AttributeError: 'Prophet' object has no attribute 'stan_backend'` error (or a `pystan:Something went wrong while unpickling the StanModel. Consider recompiling.` error on another machine), while the old "fbprophet 0.7.1" package works fine. So it seems like the new package is broken.

**Comment by bletham** [comment]
hm I'm not sure what might be happening because the build is working in the conda forge continuous integration (https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=304002&view=results).

Just to be sure - do you happen to have the prophet code in the directory you are running python from? (i.e. is there a directory named "prophet" in your current working directory). If so then I've noticed that it will try to load the package from the current directory instead of from the install directory, which will produce the "no attribute stan_backend" error.

When you install the package, does it take a minute or two to compile the model? Are there any error messages or anything?

Can you follow the steps here (https://github.com/facebook/prophet/issues/1835#issuecomment-790812991) and see where it is looking for the model file, and then see if there is actually a model file there?

**Comment by candalfigomoro** [comment]
@bletham 
I have no "prophet" directory in my working directory.

**On my local Windows machine:**
I get no errors when I install the package.

Code output:
```
>>> from prophet import Prophet
Importing plotly failed. Interactive plots will not work.
>>> import logging
>>> logger = logging.getLogger('prophet')
>>> logger.setLevel(logging.DEBUG)
>>> m = Prophet()
WARNING:pystan:No module named 'stanfit4anon_model_dfdaf2b8ece8a02eb11f050ec701c0ec_4959769199373391054'
WARNING:pystan:Something went wrong while unpickling the StanModel. Consider recompiling.
DEBUG:prophet:Loaded stan backend: PYSTAN
>>> print(m.stan_backend)
<prophet.models.PyStanBackend object at 0x0000020F2D31AA00>
>>> import pkg_resources
>>> model_file = pkg_resources.resource_filename('prophet', 'stan_model/prophet_model.pkl')
>>> import pickle
>>> with open(model_file, 'rb') as f:
...     stan_model = pickle.load(f)
...
WARNING:pystan:No module named 'stanfit4anon_model_dfdaf2b8ece8a02eb11f050ec701c0ec_4959769199373391054'
WARNING:pystan:Something went wrong while unpickling the StanModel. Consider recompiling.
```

NOTE: if I install the package with `pip` it works fine, so it looks like a conda packaging issue.
Could it be related to the "noarch" and/or "binary_has_prefix_files" changes? Or the Cython dependency that has been removed? The old "fbprophet 0.7.1" conda-forge package works fine.

**On my Linux server:**

I get a different error here
```
  File "/build/conda/env/lib/python3.6/site-packages/prophet/forecaster.py", line 141, in __init__
    self._load_stan_backend(stan_backend)
  File "/build/conda/env/lib/python3.6/site-packages/prophet/forecaster.py", line 154, in _load_stan_backend
    logger.debug("Loaded stan backend: %s", self.stan_backend.get_type())
AttributeError: 'Prophet' object has no attribute 'stan_backend'
```
immediately after calling `m = Prophet()`

Also in this case, the old "fbprophet 0.7.1" package works fine.

So the new "prophet" conda package is basically broken on all my environments (with different errors), while the old "fbprophet" conda-forge package works fine on all my environments. On my local machine, prophet 1.0.1 installed through `pip` works fine, so it looks like a conda-forge packaging issue of the new "prophet" package.

**Comment by bletham** [comment]
Great thanks for helping to debug, so the pickle file exists but for some reason pystan is unable to unpickle it. Let's debug this over in the conda-forge/prophet-feedstock repo.

**Comment by bletham** [comment]
This should be fixed now with the package updated in conda forge.

**Comment by mertbozkir** [comment]
I have the same issue in my environment too.

I just tried. this command and it worked if you have problem, try this one
```
conda install -c conda-forge fbprophet
```


**My Steps:**
* Collected metadata package
* Failed frozen solve and tried flexible solve
* Failed repodata, then tried next repodata source
*  It collected metadata and solved environment
*  Proceed ([y]/n)? and I said Yeap download **Prompt Bro**

![image](https://user-images.githubusercontent.com/63906053/116377047-7d041380-a819-11eb-8d16-aa420f5f77a1.png)

**Comment by mertbozkir** [comment]
@bletham, is there any difference between prophet and fbprophet?
 
I installed fbprophet but don't know if mistake.

**Comment by bletham** [comment]
fbprophet is the old package name, as of the last release a few weeks ago in which the package name was changed to prophet. You will see that fbprophet is version 0.7.1, prophet is version 1.0.1. Future updates will all be in the prophet package.

**Comment by rakeshn1** [comment]
Is there an official docker image of fbprophet which can be pulled and used? 
I have installed fbprophet locally using conda and built a forecast model. However, I'm facing an issue when I'm trying to deploy it on cloud foundry using miniconda. I'm getting an error "Resolve package not found - fbprophet" and I was getting the same error even trying with "prophet". So, I thought of containerizing  it using docker to deploy on cloud. But still facing issues with installation of pystan and prophet in docker build. It would be really helpful if there is a offical docker image.

**Comment by mhadi813** [comment]
> @bletham
> I have no "prophet" directory in my working directory.
> 
> **On my local Windows machine:**
> I get no errors when I install the package.
> 
> Code output:
> 
> ```
> >>> from prophet import Prophet
> Importing plotly failed. Interactive plots will not work.
> >>> import logging
> >>> logger = logging.getLogger('prophet')
> >>> logger.setLevel(logging.DEBUG)
> >>> m = Prophet()
> WARNING:pystan:No module named 'stanfit4anon_model_dfdaf2b8ece8a02eb11f050ec701c0ec_4959769199373391054'
> WARNING:pystan:Something went wrong while unpickling the StanModel. Consider recompiling.
> DEBUG:prophet:Loaded stan backend: PYSTAN
> >>> print(m.stan_backend)
> <prophet.models.PyStanBackend object at 0x0000020F2D31AA00>
> >>> import pkg_resources
> >>> model_file = pkg_resources.resource_filename('prophet', 'stan_model/prophet_model.pkl')
> >>> import pickle
> >>> with open(model_file, 'rb') as f:
> ...     stan_model = pickle.load(f)
> ...
> WARNING:pystan:No module named 'stanfit4anon_model_dfdaf2b8ece8a02eb11f050ec701c0ec_4959769199373391054'
> WARNING:pystan:Something went wrong while unpickling the StanModel. Consider recompiling.
> ```
> 
> NOTE: if I install the package with `pip` it works fine, so it looks like a conda packaging issue.
> Could it be related to the "noarch" and/or "binary_has_prefix_files" changes? Or the Cython dependency that has been removed? The old "fbprophet 0.7.1" conda-forge package works fine.
> 
> **On my Linux server:**
> 
> I get a different error here
> 
> ```
>   File "/build/conda/env/lib/python3.6/site-packages/prophet/forecaster.py", line 141, in __init__
>     self._load_stan_backend(stan_backend)
>   File "/build/conda/env/lib/python3.6/site-packages/prophet/forecaster.py", line 154, in _load_stan_backend
>     logger.debug("Loaded stan backend: %s", self.stan_backend.get_type())
> AttributeError: 'Prophet' object has no attribute 'stan_backend'
> ```
> 
> immediately after calling `m = Prophet()`
> 
> Also in this case, the old "fbprophet 0.7.1" package works fine.
> 
> So the new "prophet" conda package is basically broken on all my environments (with different errors), while the old "fbprophet" conda-forge package works fine on all my environments. On my local machine, prophet 1.0.1 installed through `pip` works fine, so it looks like a conda-forge packaging issue of the new "prophet" package.

I was getting ``AttributeError: 'Prophet' object has no attribute 'stan_backend'`` with ``fbprophet==0.7.1``. I installed ``prophet==1.0`` and the code is working now. BTW, did package name change from fbprophet to prophet?

**Comment by ckaldemeyer** [comment]
I also had several issues installing `prophet` on my Windows 10 machine using `conda` and `Python 3.7`.

The following steps made it work:

1. Create a fresh `conda` environment
2. Install `pystan` and other dependencies using `conda install numpy cython matplotlib scipy pandas -c conda-forge` (see https://pystan2.readthedocs.io/en/latest/windows.html#steps)
3. Install `prophet` using `conda install prophet -c conda-forge`

In then still had a numpy error `Importing the numpy c-extensions failed...` as described here: https://numpy.org/devdocs/user/troubleshooting-importerror.html But this was due to my IDE which is VS Code as I could successfully run my `prohet` model using the command line with the activated `conda` environment.

So please also make sure to test the installation from the command line in order to rule out that the error stems from you IDE.

**Comment by ckaldemeyer** [comment]
I could provide a PR to add this to the docs, if needed as I found it really annoying to get this running :-)

**Comment by alsoulm** [comment]
> 

thank u ,  its working with me

**Comment by WardBrian** [comment]
Closing due to PyStan no longer being a dependency of `prophet`
