### ISSUE TITLE
ModuleNotFoundError: No module named 'fbprophet' on Miniconda

### ISSUE THREAD

**Issue by yoyoyo-yo** [facebook/prophet#1874]
I tried to install prophet package on miniconda. Install command is below.

```python
$ sudo conda install -c conda-forge prophet
```

The environment is python=3.9 virtual env of miniconda on macOS.

After installation, I tried 

```
from fbprophet import Prophet
```

and got error

```bash
----> 5 from fbprophet import Prophet

ModuleNotFoundError: No module named 'fbprophet'
```

I tried another way like

```bash
$ sudo pip install pystan==2.19.1.1 prophet
```

, but result is the same.

Install method is not correct?

Thanks

**Comment by bletham** [comment]
The package name changed to `prophet`, so if you do `from prophet import Prophet` that should work!

**Comment by yoyoyo-yo** [comment]
@bletham 
Thank you!

After installation like below

```bash
$ sudo pip install pystan==2.19.1.1 prophet
```

and I changed package name below

```python
from prophet import Prophet
```

worked.

**Comment by murodjon88** [comment]
thanks a lot

**Comment by mohigit** [comment]
Thank you...from prophet import Prophet....worked :)

**Comment by huB-ram** [comment]
thank u 🥹
