### ISSUE TITLE
[R] Compilation fails on Mac OS

### ISSUE THREAD

**Issue by tcuongd** [facebook/prophet#1877]
I just pulled from master and I'm getting compilation errors when building Prophet locally. 

* The error message (I can't tell the specific error it's failing on):

```
38 warnings and 3 errors generated.
make: *** [stanExports_prophet.o] Error 1
ERROR: compilation failed for package ‘prophet’
```
* My session info:

```r
R version 4.0.5 (2021-03-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

> packageVersion("rstan")
[1] ‘2.26.1’
> packageVersion("Rcpp")
[1] ‘1.0.6’
> packageVersion("RcppParallel")
[1] ‘5.1.2’
> packageVersion("rstantools")
[1] ‘2.0.0’
```

* Note that I'm using `remotes::install_local()` so the dependencies get downloaded as binaries from CRAN.

Wondering if anyone can reproduce this or if it's just me (e.g. an issue with my computer's C++ compiler).

**Comment by bletham** [comment]
It looks like the rstan is newer than the latest CRAN release, so it hasn't been tested against prophet. Could you just check if it is generally working to determine if the issue is in that or if it is specifically in compiling the prophet model?
```R
library(rstan)
model_code <- 'parameters {real y;} model {y ~ normal(0,1);}'
fit <- stan(model_code=model_code)  # this will take a minute
mean(extract(fit)$y)  # should be close to 0
```

**Comment by tcuongd** [comment]
Aha! Good pickup - it seems like I installed rstan from source instead of CRAN....

You're right, using rstan 2.21.1 works.

I was able to run the minimal example on rstan 2.26.1 on my machine as well, so it seems like there might be an issue compiling the Prophet model under 2.26.1
