### ISSUE TITLE
Get All Value Generated by Monte Carlo

### ISSUE THREAD

**Issue by yasirroni** [facebook/prophet#1878]
I want to implement clustering out of prophet result of monte carlo `yhat_upper` and `yhat_lower`, and giving the probability weights of each cluster. My question is, how to fetch the monte carlo predict?

**Comment by bletham** [comment]
If you do `m.predictive_samples` it will return the full set of posterior samples for `yhat`, from which you could do the clustering or whatever subsequent analysis you wanted:
https://github.com/facebook/prophet/blob/0616bfb5daa6888e9665bba1f95d9d67e91fed66/python/prophet/forecaster.py#L1407-L1425

**Comment by yasirroni** [comment]
THANKS!!!
