### ISSUE TITLE
Using FBProphet for Probabilities

### ISSUE THREAD

**Issue by jwoznicki** [facebook/prophet#1882]
Is FBProphet appropriate for estimating percentages or probabilities? I have a dataset of daily production, but I am really concerned with the daily production as a percent of the total month's production. Day-over-day we see a much larger proportion of our production coming on Monday or Friday, at the end of the month versus the beginning, and if we have a Friday as the last day of the month, etc. We also see some strong yearly seasonalities. I understand the trend will be essentially meaningless here, but I'm ok with that as we want to understand how our month will look based on goal amounts rather than actual forecasted production.

I was also interested in using it to look at what percent of our prospects will turn over into production on any given day, which again is very dependent on similar seasonalities above. This would be somewhat like estimating transition probabilities for markov chains.

Thanks!

**Comment by bletham** [comment]
You could use the "flat" trend and see if it does learn something useful for the seasonalities, but I think it would really depend on the time series how well this works. I guess the comparison would be to make the forecast at the daily level and then compute the % afterwards, and I think you'd just have to check empirically which works better.

**Comment by jwoznicki** [comment]
Thanks @bletham, I'll test both methods and see what works better!
