### ISSUE TITLE
Best approach to account for Covid-19 in a Forecast

### ISSUE THREAD

**Issue by Neptune444** [facebook/prophet#1887]
Hello,

I was just wondering how you would recommend accounting for Covid-19 in a Forecast. This may seem a broad question, but say my company has seen better than usual performance during Covid-19, which may not necessarily be repeated in the same way next year when things go "back to normal". 

I appreciate it's a trial and error approach, but would a custom holiday be a good tool? I could roughly map the UK lockdowns to time periods and go for that. 

Any tips welcome.

If this isn't the right place for this type of question, I'm sorry, and I'm still getting used to Github.

Thanks,

Neptune

**Comment by tcuongd** [comment]
Heya, have you read this thread: https://github.com/facebook/prophet/issues/1752 ? (I just searched COVID in the issues search box, it's been quite a common query I think 😅 ) It might provide some guidance.

**Comment by Neptune444** [comment]
Thank you! Much appreciated.
