### ISSUE TITLE
Change in plot_cross_validation_metric from fbprophet to prophet

### ISSUE THREAD

**Issue by raffg** [facebook/prophet#1894]
I noticed with the new Prophet version, `plot_cross_validation_metric` now plots the line and points as the same color, and also changes the alpha of the points from 0.5 to 0.1. I understand this was done to make comparing models easier by plotting the lines with different colors, but it has the drawback of making it difficult to see the line with a dense set of points. Compare these two plots:

from fbprophet:
![image](https://user-images.githubusercontent.com/20135094/116822586-7258bf80-ab34-11eb-99d8-51a028536706.png)

from prophet:
![image](https://user-images.githubusercontent.com/20135094/116822594-7a186400-ab34-11eb-9478-36aa0c531893.png)

I propose adding another argument to the function for the point colors. I'll make a PR with this change but feel free to disregard if this new behavior is desired.

**Comment by nuwan0327** [comment]
[DBN_TREND.xlsx](https://github.com/facebook/prophet/files/6920862/DBN_TREND.xlsx)

**Comment by nuwan0327** [comment]
CDR trend
