### ISSUE TITLE
Add PyStan 3 support

### ISSUE THREAD

**Issue by onacrame** [facebook/prophet#1896]
PyStan 3 benefits from an ISC license as opposed to the “viral” GPL license of PyStan 2.  That alone is worth the upgrade.  The current approach of allowing a cmdpystan option is not nearly as good as there are some differences between that package and PyStan.

**Comment by mahanh** [comment]
we run thousands of parallel prophet runs and noticed in some rare cases pystan 2.19 gets frozen after 2000~ iterations on Google cloud machines but works fine on Mac OS!
we really wanted to try pystan 3+ to check if the hanging bug is fixed or not.

**Comment by tcuongd** [comment]
I think the biggest issue with Pystan 2 -> Pystan 3 is the lack of support for MAP estimation. From https://pystan.readthedocs.io/en/latest/upgrading.html#notable-changes:

> The default, recommended HMC sampler is fully supported. Variational inference, maximization algorithms, and other sampling algorithms are not supported. Users who need these features should consider using different software (e.g., CmdStan, CmdStanPy, jax, PyTorch).

The default setting for Prophet fits is MAP estimation (i.e. `mcmc_samples = 0`) so this would be a pretty end-user change to enforce MCMC sampling. Could you also explain "cmdpystan option is not nearly as good" more? They have the same functionality from what I understand?

**Comment by ParthivNaresh** [comment]
@tcuongd `CmdStanPy` is built on top of `CmdStan`, and unfortunately the build time for `CmdStan` is excessive, in the range of 5-10 min depending on the system. Bringing that overhead downstream to the user is definitely something we'd like to avoid. Perhaps allowing installation of `PyStan 3` via flag with a limited functionality warning might be a better course of action?

**Comment by tmielika** [comment]
👍 for getting non-GPL PyStan as as in many entities software with GPLv3 dependencies (or being under GPLv3 themselves) cannot be used, except as standalone applications.

**Comment by tcuongd** [comment]
Thanks all for the feedback. I think we will try to re-consider what the "canonical backend" for the Python prophet package should be: pystan, cmdstanpy, or numpyro (see https://github.com/facebook/prophet/pull/1973). We'll need to consider things like ease of maintenance, keeping parity with R, performance, and ease of packing into a wheel (if we're able to publish a wheel / binary to PyPi, it should alleviate concerns about compile times).

**Comment by tcuongd** [comment]
With this release: https://github.com/facebook/prophet/releases/tag/v1.1 we have now removed the dependency on `pystan` altogether and now use `cmdstan` + `cmdstanpy` as the backend. The model binaries are pre-compiled and packaged into the wheel, so the end user won't require an existing `cmdstan` installation.

The wheels are now also on PyPI.
