### ISSUE TITLE
send STAN parameters to `fit.prophet`. 

### ISSUE THREAD

**Issue by nipnipj** [facebook/prophet#1900]
Hello! 

How do I pass STAN parameters like `chains = 3, parallel_chains = 2, adapt_delta = 0.9, iter_warmup = 1000,  iter_sampling = 2000` to `fit.prophet`?

**Comment by tcuongd** [comment]
Heya, `fit.prophet()` basically takes any additional arguments you provide and passes it to either the `rstan::optimizing` function when `mcmc.samples = 0`, or the `rstan::sampling` function when `mcmc.samples > 0`. I would check out the documentation for those functions ([here](https://mc-stan.org/rstan/reference/stanmodel-method-optimizing.html) and [here](https://mc-stan.org/rstan/reference/stanmodel-method-sampling.html)) to get a full list of the parameters they can take.

For your specific example, you would do something like this:

```
# data is your data frame
m <- prophet(mcmc.samples = 1000)
m <- fit.prophet(m = m, df = data, chains = 3, iter = 2000, warmup = 1000, control = list(adapt_delta = 0.9))
```

Note that `mcmc.samples = 1000` gets overridden when you provide the `iter` and `warmup` arguments, so it doesn't actually matter what number you put there as long as it's bigger than 0.
