### ISSUE TITLE
Future dates are being skipped

### ISSUE THREAD

**Issue by JordanRees1** [facebook/prophet#1901]
Hi, 

I am starting to get up to speed with prophet and currently have a very basic model.

I have data up to the 31st March 2021.

When I run make_future_dataframe the model starts filling the data in from December. Also when I plot the forecast, the model shows data points up to December. Please let me know if I need to add anything to the issue.

![future plot](https://user-images.githubusercontent.com/40856400/117639463-d5bd9f80-b17b-11eb-9976-1a1a02ad54a9.png)

**Comment by tcuongd** [comment]
The black dots are the historical data (in the dataframe you used to fit the model). From the chart it looks like you have some "historical" data points towards the end of 2021? It might be worth checking if there are some erroneous data points, or just doing a hard filter to 31st March 2021 in your code first.

**Comment by JordanRees1** [comment]
Thanks, yeah so I understand that the points represent historical data, however the data ends on 31st March 2021. This is a screenshot of running tail on the dataset.

![dataset](https://user-images.githubusercontent.com/40856400/117641145-bb84c100-b17d-11eb-8b2d-448e505153c8.png)

**Comment by tcuongd** [comment]
Yeah that is weird...can you post the code you're running? I'll see if I can reproduce.

**Comment by JordanRees1** [comment]
Sure here is the bare bones code (the dataset is S&P from 01/03/2011 to 31/03/2021:

`import pandas as pd
from prophet import Prophet
import numpy as np
import warnings


warnings.simplefilter('ignore')

df = pd.read_csv('data/s&p500_2011-21.csv', parse_dates=[0])
df.tail()

df = df[['Date', 'Adj Close']]
df_actual = df.copy()

# Must rename columns to these
df.columns = ['ds', 'y']

print(df.head)

# Adding US holidays (S&P500 is the US market), try adding: daily_seasonality=True, interval_width=0.95
m = Prophet()
m.add_country_holidays(country_name='US')
model = m.fit(df)

future = m.make_future_dataframe(freq='D', periods=180)

forecast = m.predict(future)

plot1 = m.plot(forecast)
`

**Comment by JordanRees1** [comment]
[s&p500_2011-21.csv](https://github.com/facebook/prophet/files/6451343/s.p500_2011-21.csv)

**Comment by tcuongd** [comment]
Ah yes, thanks for providing the csv as well. It seems like the date format is `dd/mm/yyyy` which `pandas` is parsing incorrectly (so there's no issue with Prophet itself). Here's a fix:

```python
from datetime import datetime
import pandas as pd

# Don't parse the dates on read, keep them as a string
df = pd.read_csv('/Users/cuongduong/Downloads/s.p500_2011-21.csv')
df['Date'] = df['Date'].apply(lambda x: datetime.strptime(x, '%d/%m/%Y'))

# Then the rest of your code follows here...
```

Let me know how that goes?

**Comment by JordanRees1** [comment]
Thanks, so that apply function didn't work for me. What is the desired format of the date? Is it %Y/%m%d' because that's how it appears in the prophet docs and as you can see in the above screenshot of the dataframe this is how it was parsed?

**Comment by JordanRees1** [comment]
Oh great, yeah that did it thank you! 

Think it was an issue with two different sources of data with different date formats, but using the apply function has solved it.
