### ISSUE TITLE
Pystan Windows install link is broken

### ISSUE THREAD

**Issue by dbur** [facebook/prophet#1903]
On the [Installation page](https://github.com/facebook/prophet/blob/master/docs/_docs/installation.md#windows-1), the link included in the text `PyStan requires a compiler so you’ll need to follow the instructions.` is broken: http://pystan.readthedocs.io/en/latest/windows.html

There are not many references to Windows in Pystan, so I am not sure what that should be updated to: https://pystan.readthedocs.io/en/latest/search.html?q=windows&check_keywords=yes&area=default

**Comment by bletham** [comment]
Thanks for pointing this out, it looks like the correct link is https://pystan2.readthedocs.io/en/latest/windows.html , since we're using pystan 2.x.
