### ISSUE TITLE
add_country_holidays(country_name='SE') generates no holidays

### ISSUE THREAD

**Issue by andersborgabiro** [facebook/prophet#1912]
There have been posted issues earlier (during 2020) regarding a change to Pandas causing issues with this, but those issues are closed (so fixed?), or does Pandas still need to be downgraded for this to work?

In any case train_holiday_names is empty and plot_components shows no holidays.

Code snippet:

        m.add_country_holidays(country_name='SE')
        print( m.train_holiday_names) # this shouldn't be empty

Thanks in advance for any clues.

I ran "conda update --all" just before.

**Comment by Kev1nZheng** [comment]
You need to do the m.fit(df) first, and then print the m.train_holiday_names.

**Comment by andersborgabiro** [comment]
That worked. plot_components still doesn't show it though.

I'll check whether that's due to holidays being deemed irrelevant.

Thanks for the help.
