### ISSUE TITLE
When to use MCMC vs. MAP

### ISSUE THREAD

**Issue by andrewsx** [facebook/prophet#1914]
Is there a set of guidelines for determining when to use the MCMC samples versus the MAP estimation default method?

thanks

**Comment by tcuongd** [comment]
Heya, you would use MCMC sampling when you want to produce uncertainty estimates for the seasonal, holidays, and extra regressor components.

In MAP estimation, we only produce uncertainties for the trend component.

This page from the docs might be useful: https://facebook.github.io/prophet/docs/uncertainty_intervals.html#uncertainty-in-the-trend
