### ISSUE TITLE
Getting error - No module named 'prophet'

### ISSUE THREAD

**Issue by aditya113141** [facebook/prophet#1922]
![Image](https://user-images.githubusercontent.com/56213335/118790402-5afb2f80-b8b3-11eb-8c22-8f0b44741a17.png)
I tried installing prophet using pip but still I am getting the error - No module named 'prophet'
I already have Pystan 2.19.1.1 installed.
What could be the possible errors ?

My OS is Ubuntu 20.04 LTS and i am using python 3.8.8

**Comment by tcuongd** [comment]
What happens if you run `python3 main.py` (instead of `streamlit run`?). I'm not sure how `streamlit` works but it could be using a Python version different to the one you installed Prophet into.

**Comment by aditya113141** [comment]
It works fine here
![Screenshot from 2021-05-19 17-00-35](https://user-images.githubusercontent.com/56213335/118805645-c9e08480-b8c3-11eb-8d00-26d6a177c91a.png)
I think there is some error with streamlit.

**Comment by tcuongd** [comment]
How did you go with this? It does seem like the `streamlit` command is running a different Python environment than the one you installed prophet into. Now if you try `python3 -m streamlit run main.py`, does that work?

**Comment by aditya113141** [comment]
![Screenshot from 2021-05-28 18-14-39](https://user-images.githubusercontent.com/56213335/119985692-9d71ea00-bfe0-11eb-900d-73de67199a2b.png)

This is what I get.

**Comment by tcuongd** [comment]
Nice I think at least it knows that Prophet exists now. The error you're getting is because you have a file called `copy.py` in your folder. Since this is the name of a built-in module, Python doesn't know which one to import. You'll need to rename that file or delete it.

**Comment by aditya113141** [comment]
Okay, I did not know about inbuilt copy.py in python. It works now and doesn't gives any error.
