### ISSUE TITLE
no suitable torch version for neuralprophet

### ISSUE THREAD

**Issue by RemKamal** [facebook/prophet#1928]
Hello all,
trying to install neuralprophet, I get the following error below. To fix that, also somehow cannot get torch 1.6.0, which I used to have some time ago on another machine.
Please let me know what I am missing.
Thanks,
Remkamal

[remkamal@a02 ~]$ pip install neuralprophet[live]
Collecting neuralprophet[live]
  Using cached neuralprophet-0.2.7-py3-none-any.whl (56 kB)
Requirement already satisfied: holidays>=0.10.2 in /opt/pyenv/versions/3.9.2/lib/python3.9/site-packages (from neuralprophet[live]) (0.11.1)
Requirement already satisfied: tqdm>=4.50.2 in /opt/pyenv/versions/3.9.2/lib/python3.9/site-packages (from neuralprophet[live]) (4.60.0)
Requirement already satisfied: numpy>=1.15.4 in /opt/pyenv/versions/3.9.2/lib/python3.9/site-packages (from neuralprophet[live]) (1.20.0)
  Using cached neuralprophet-0.2.6-py3-none-any.whl (55 kB)
  Using cached neuralprophet-0.2.5-py3-none-any.whl (54 kB)
ERROR: Cannot install neuralprophet[live]==0.2.5, neuralprophet[live]==0.2.6 and neuralprophet[live]==0.2.7 because these package versions have conflicting dependencies.

The conflict is caused by:
    neuralprophet[live] 0.2.7 depends on torch<1.7.0 and >=1.4.0
    neuralprophet[live] 0.2.6 depends on torch<1.7.0 and >=1.4.0
    neuralprophet[live] 0.2.5 depends on torch<1.7.0 and >=1.4.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
[remkamal@a02 ~]$ pip install torch==1.6.0
ERROR: Could not find a version that satisfies the requirement torch==1.6.0 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.7.1, 1.8.0, 1.8.1)
ERROR: No matching distribution found for torch==1.6.0

**Comment by tcuongd** [comment]
Hey! NeuralProphet is actually a different project, you'll get much better help on their GitHub page: https://github.com/ourownstory/neural_prophet/issues

Unfortunately I'm not super familiar with pytorch so I don't know a quick fix to that error.

**Comment by RemKamal** [comment]
@tcuongd  Thanks for the pointer, opened an issue there.
Have a great weekend!
