### ISSUE TITLE
Predicted Upper and lower values (yhat_upper & yhat_lower) are too far from Actual y values

### ISSUE THREAD

**Issue by SivarajaReddy** [facebook/prophet#1935]
Hi All,
I am using fbprophet to do time series forecasting of my app server's volume . My raw data is hourly aggregated volume served by each server and it’s in range of few 100s to few 1000s . But there is abnormal spike of 350000 recorded in one hour ( this could be anomalous data ..) . As far as I know fbprophet removes such abnormal spikes , i.e outliers , before it does forecasting right ? I may be wrong in this assumption , please correct me if so . 

We are actually forecasting hundreds of servers every day , so we ideally expect fbprophet to handle outliers removals also ( or that’s what we assumed ) . In the resultant forecast yhat is almost closer to the actual y – this is ok for me and as expected . But strangely  yhat_upper , yhat_lower are way off from the range . Forecast yhat_upper and lower are  in range of 14000 to 16000 / -14000 to -16000 . Could anyone please explain what’s going wrong here ?

![image](https://user-images.githubusercontent.com/26619230/120801164-661cb380-c573-11eb-8619-7cc63ecfe93e.png)

My actuals - y and yhat, yhat_upper , yhat_lower are here =>
![image](https://user-images.githubusercontent.com/26619230/120801285-8f3d4400-c573-11eb-83c9-cb2ff7d0f361.png)

I am using default parameters only here like below=>

service_model = Prophet(interval_width=0.95)
service_model.fit(df)
service_forecast = service_model.make_future_dataframe(periods=150, freq='H')
service_forecast = service_model.predict(service_forecast)

Please advise me how to fix this problem @bletham  your advise please also ….

**Comment by tcuongd** [comment]
Heya, Prophet does not remove outliers automatically. See https://facebook.github.io/prophet/docs/outliers.html

There is a bit of discussion on some strategies you could use to automate outlier removal here: https://github.com/facebook/prophet/issues/229

**Comment by SivarajaReddy** [comment]
Hi @tcuongd Thanks for the response. I am checking to implement auto detection of outliers before sending data to prophet model.
