### ISSUE TITLE
Extra regressors in Prophet model

### ISSUE THREAD

**Issue by Okroshiashvili** [facebook/prophet#1938]
**This could be widely discussed topic but unfortunately I did not find answers to my questions. Please help me to grab the intuition behind this.** 

I have daily sales time series data worth of one year. I want to have week ahead prediction of the sales.

If I use only `ds` and `y` then everything is quite OK and I have my week ahead forecast. However, when I want to use extra regressors then things getting complicated and makes lots of troubles.

During training I use lag and first order derivative of `y` along with some others as external regressors. When I want to make prediction I use model object to generate future dataframe and use `predict` method. The `predict` method requires to have future values of external values and that makes me trouble.

**My question**: if I cannot use model trained with external regressor to have forecast why do we need external regressors at all?

**Comment by imad24** [comment]
Since you dont have the future values of your extra regressors, is it relevant in your case to feed the model with the "forecasts" of each extra regressor before you fit the main model ? You can use Prophet to predict future values.

**Comment by Okroshiashvili** [comment]
These extra regressors help me to improve model performance. So, imagine a situation when instead of extra regressors have features derived from the target, such as lag and lead values, derivatives, and so on. How can I use predict method from the model object to have a prediction when I have these kinds of independent features?

I know that I can use Prophet, feed the only target in Prophet end then make predictions without any problem. But this is not my question

**Comment by Okroshiashvili** [comment]
I just realized that Prophet can be used only for nowcasting with extra regressors than forecasting. Despite the fact that I can derive extra regressors from the target it cannot be used for forecasting. Or, according to @imad24 answer, I can predict target, then derive extra regressors from it and then again make forecast.
I'm closing the issue.
