### ISSUE TITLE
AttributeError: 'Prophet' object has no attribute 'stan_backend'

### ISSUE THREAD

**Issue by wenouyang** [facebook/prophet#1943]
Hello, I am following the prophet tutorial, 

import pandas as pd
from prophet import Prophet
df = pd.read_csv('.\\examples\\example_wp_log_peyton_manning.csv')
df.head()
m = Prophet()
m.fit(df)

It got the following error message. I am using Anaconda on Windows  Are there any more information/test script that I need to provide for debugging the error? Thanks.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-2a37301e3f6e> in <module>
      7 
      8 # Python
----> 9 m = Prophet()
     10 m.fit(df)

```
~\Anaconda3\envs\tensorflow\lib\site-packages\prophet\forecaster.py in __init__(self, growth, changepoints, n_changepoints, changepoint_range, yearly_seasonality, weekly_seasonality, daily_seasonality, holidays, seasonality_mode, seasonality_prior_scale, holidays_prior_scale, changepoint_prior_scale, mcmc_samples, interval_width, uncertainty_samples, stan_backend)
    139         self.fit_kwargs = {}
    140         self.validate_inputs()
--> 141         self._load_stan_backend(stan_backend)
    142 
    143     def _load_stan_backend(self, stan_backend):

~\Anaconda3\envs\tensorflow\lib\site-packages\prophet\forecaster.py in _load_stan_backend(self, stan_backend)
    152             self.stan_backend = StanBackendEnum.get_backend_class(stan_backend)()
    153 
--> 154         logger.debug("Loaded stan backend: %s", self.stan_backend.get_type())
    155 
    156     def validate_inputs(self):

AttributeError: 'Prophet' object has no attribute 'stan_backend'

​

```

**Comment by tcuongd** [comment]
Hi! We've had a few issues pop up regarding Anaconda on Windows. Did you install prophet with conda forge? i.e. `conda install -c conda-forge prophet`; this comes from the installation instructions: https://github.com/facebook/prophet#anaconda

If that doesn't work then I'll try to do dig into this Windows issue.

**Comment by WardBrian** [comment]
Closing in favor of #2462
