### ISSUE TITLE
Data is not recorded on regularly spaced

### ISSUE THREAD

**Issue by Raj0569** [facebook/prophet#1945]
Hi,

How can I use Prophet for data recorded on non regular  spaced. I have data from 2001 to 2020, data was recorded 2 times (at 7:00, 15:00) in a day and randomly 10 days a month. How can I use Prophet for forecast in this case?

**Comment by tcuongd** [comment]
Hi! Prophet will still fit and predict with non-regularly spaced data. You can read this page for more info: https://facebook.github.io/prophet/docs/non-daily_data.html

For the prediction, you need to keep in mind that if Prophet has not seen any data for the days/times you want to predict, the predictions might look off.
