### ISSUE TITLE
Predict and plot facebook prophet model results in a dash/plotly app

### ISSUE THREAD

**Issue by Youtir** [facebook/prophet#1946]
Hope yall good,

I'm building a dash app that loads a trained Facebook prophet model and predicts an electricity load time series, in Colab notebook and locally I can predict and visualize prediction results but when I try this in a dash app all I get is the plot canvas with no data in plotted and keyerror : '_time' that raises after a while.

Thanks in advance !

**Comment by tcuongd** [comment]
Hey! We might need more details on this one to help you out. Could you post your notebook, maybe with some example data, so we can debug?

**Comment by Youtir** [comment]
Thanks for your response, I've found an alternative.

**Comment by FelipeMG** [comment]
Hi @Youtir could you please share the alternative you found? I am having the same issue

**Comment by AhmedThahir** [comment]
Same here. Kindly share the solution.
