### ISSUE TITLE
model.train_holiday_names is returning NoneType value for country_names='IN'

### ISSUE THREAD

**Issue by AnuragAnalog** [facebook/prophet#1947]
# Problem with holidays data

Hey Hii
I am new to FBProphet, and trying to fit the module for Indian time series data, which obviously requires holidays to make a good prediction. But when I am using any country code(not only India) to add the holiday's data.

The model is not taking it.

> I have tried finding a similar issue(both open and closed) but couldn't find it. If this is an existing issue, please redirect me to the solution.

## Version and System configs
System: Google Colab
Pystan version: 2.19.1.1
Prophet version: 1.0.1

## Code to reproduce the error

```python3
from prophet import Prophet

model = Prophet()
model.add_country_holidays(country_name='IN')
print(model.train_holiday_names)
```

### Expected Output
A DataFrame consisting of holidays

### Actual Output
None

**Comment by tcuongd** [comment]
Can you try to run `model.fit()` first, and then print `model.train_holiday_names`?

**Comment by AnuragAnalog** [comment]
@tcuongd Thanks man, it worked
