### ISSUE TITLE
Optimization terminated abnormally. Falling back to Newton.

### ISSUE THREAD

**Issue by mvtkurd** [facebook/prophet#1950]
hi guys, I got this error when I try to fit my model by prophet `WARNING:fbprophet.models:Optimization terminated abnormally. Falling back to Newton.` so would you please help me to overcome this error>
Also I tried 3 methods but no result.

![prophet err](https://user-images.githubusercontent.com/32674939/122690957-de020380-d22c-11eb-84eb-fa065757d31c.jpg)

**Comment by tcuongd** [comment]
When you do `.astype('<M8[D]')`, I believe you're converting everything to a date. This means you have multiple `y` values for the same `ds` value. I think you'll want to aggregate your data at the date level (e.g. `sum`, or `mean` with df.groupby('ds').agg()) before putting it into the it function.

**Comment by mvtkurd** [comment]
> When you do `.astype('<M8[D]')`, I believe you're converting everything to a date. This means you have multiple `y` values for the same `ds` value. I think you'll want to aggregate your data at the date level (e.g. `sum`, or `mean` with `df.groupby('ds').agg()`) before putting it into the it function.

I'm not professional in Prophet. I just followed the video tutorial which explains how we can connect influxdb to prophet and do some forecasting on incoming data from influx cloud. Now can you explain what should I do please?

**Comment by aabuabat** [comment]
I am facing the same issue; however, I am sure about my data structure overall. In fact, the code was working just fine with my Mac OS intel Chip. When I run the same code in the M1 chip I got this error. I do not know what is happening exactly.
![Screen Shot 2022-07-07 at 12 55 26](https://user-images.githubusercontent.com/87271203/177746490-0a3c5e8c-e04e-407e-b8eb-b93da9158ff0.png)

**Comment by aabuabat** [comment]
> 

what is your machine specifications?

**Comment by tulbureandreit** [comment]
@mvtkurd any solutions ?
