### ISSUE TITLE
pip install fails with pystan requirement

### ISSUE THREAD

**Issue by bholland** [facebook/prophet#1954]
Pystan 3 changed a lot of features and functionality and it appears like the pip package does not account for the correct pystan requirement. I assume that it requires a pystan 2 version but running pip install fbprophet results in 

Collecting pystan>=2.14
  Downloading pystan-3.2.0-py3-none-any.whl (13 kB)

The build fails with an import pystan error because as of pystan >= 3, the correct import is import stan. I am going to try and use the latest 2 branch but it would be great for the package maintainer to enforce whatever pystan requirement the package has on your end  or support pystan 3.

**Comment by tcuongd** [comment]
Hello! We actually have pinned the version, see here: https://github.com/facebook/prophet/blob/master/python/requirements.txt (and this has been released to PyPi). However:

1. You'll still want to install the pinned version of pystan before installing prophet: `pip install pystan==2.19.1.1`.
2. The package is called `prophet` now, so you'd do `pip install prophet` after that.

See the [installation instructions](https://github.com/facebook/prophet#installation-in-python)
