### ISSUE TITLE
Stan Code Example from original Paper

### ISSUE THREAD

**Issue by sarah2397** [facebook/prophet#1965]
Dear all,

I investigate togehther with my professor the propet package and we looked at the stan code from the original paper. Here you see the screenshot, which part I mean:

![stancode_prophet_paper](https://user-images.githubusercontent.com/68432546/125582312-205213b1-bc76-490b-b174-cafcf25fcf1e.PNG)

I understood, that we estimate with MAP **k**, **m**, **delta** and **beta**.

But the **epsilon** is a little bit confusing for me:
For the noise term of the completly model (which we use for calculating the uncertainty intervals), we estimate with MAP its variance.
![image](https://user-images.githubusercontent.com/68432546/125584285-50a28269-9475-41df-8b56-11fdf5737007.png)
... and the estimated variance is the, in the stan code mentioned, **epsilon**. Am I right?

So why we have within the **y~normal(..)** for the logistic likelihood the **epsilon** and for the linear likelihood the **sigma** as standard deviation for the normal distribution. Especially the sigma - it's not the same sigma like in the beta-prior, right?

Thanks for your reply. I'm really confused about the notation in this part. Hope you can help me.
Best regards,
Sarah Hadj Hassen

**Comment by tcuongd** [comment]
Hey Sarah, the actual implementation of the Stan code for the package can be found here: https://github.com/facebook/prophet/blob/b75844e07c3b09bf3bc383c9d43241c554dd251b/python/stan/unix/prophet.stan#L127-L142 - it's a bit different to the example given in the paper.

The variance parameter is the same for either trend function (logistic or linear), and has a `normal(0, 0.5)` prior.

**Comment by sarah2397** [comment]
So, it's a fault that we have in the paper 'sigma' instead of 'epsilon' - at least for the linear trend?

**Comment by tcuongd** [comment]
Yes I believe so. It says later in that paragraph:

> The parameters tau and sigma in Listing 1.1 are controls
for the amount of regularization on the model **changepoints** and
**seasonality**, respectively

so `sigma` is only meant to affect the seasonality & holiday parameters. Hence the `sigma` on the last line of the sample stan code in the paper is likely a typo.
