### ISSUE TITLE
add_changepoints_to_plot not showing changepoints

### ISSUE THREAD

**Issue by MSasta** [facebook/prophet#1977]
Hey! 

I was facing this issue when running prophet; basically if I use the function to add changepoints
`plot(m, castr) + add_changepoints_to_plot(m)` then instead of showing the changepoints it just shows a straight line running through the plot: 
![image](https://user-images.githubusercontent.com/87978045/127480545-2d23bddc-f534-4a84-987b-f08c8f95a8a3.png)

I have left the model to detect changepoints on its own and checking for change points then the model does have them: 
`m$changepoints` returns
` [1] "2018-11-24 GMT" "2018-12-11 GMT" "2018-12-27 GMT" "2019-01-22 GMT" "2019-02-24 GMT" "2019-04-06 GMT" "2019-06-21 GMT" "2019-07-16 GMT"
 [9] "2019-08-05 GMT" "2019-08-25 GMT" "2019-09-16 GMT" "2019-10-12 GMT" "2019-10-29 GMT" "2019-11-14 GMT" "2019-12-01 GMT" "2019-12-21 GMT"
[17] "2020-01-07 GMT" "2020-01-29 GMT" "2020-02-20 GMT" "2020-03-08 GMT" "2020-03-25 GMT" "2020-04-17 GMT" "2020-06-25 GMT" "2020-07-11 GMT"
[25] "2020-07-27 GMT" "2020-08-13 GMT" "2020-08-29 GMT" "2020-09-14 GMT" "2020-10-01 GMT" "2020-10-17 GMT" "2020-11-03 GMT" "2020-11-19 GMT"
[33] "2020-12-05 GMT" "2020-12-22 GMT" "2021-01-07 GMT"`

Sorry if this is a stupid question but any help would be much appreciated. Thank you!

**Comment by tcuongd** [comment]
There is a parameter in `add_changepoints_to_plot()`, `threshold` , that prevents changepoint lines from being added to the plot when their effect size (`delta`) is below a threshold. The default value is `0.01`, but the changepoints in this scenario could have a smaller effect than that (judging by the components plot, the model is mainly following the trend). Could you try a lower `threshold` value and see whether the lines get added? Setting `threshold = 0` should plot all the changepoint lines.

See here for reference: https://rdrr.io/cran/prophet/man/add_changepoints_to_plot.html

**Comment by MSasta** [comment]
> There is a parameter in `add_changepoints_to_plot()`, `threshold` , that prevents changepoint lines from being added to the plot when their effect size (`delta`) is below a threshold. The default value is `0.01`, but the changepoints in this scenario could have a smaller effect than that (judging by the components plot, the model is mainly following the trend). Could you try a lower `threshold` value and see whether the lines get added? Setting `threshold = 0` should plot all the changepoint lines.
> 
> See here for reference: https://rdrr.io/cran/prophet/man/add_changepoints_to_plot.html

Hey, this works! Thank you, I didn't know what the threshold parameter did so didn't adjust it, but I'm seeing the changepoints now.
