### ISSUE TITLE
doc: clicking on "follow the instruction" trigger a 404 error

### ISSUE THREAD

**Issue by defoishugo** [facebook/prophet#1991]
Hello,

On the website, the [Installation](https://facebook.github.io/prophet/docs/installation.html#python) page redirects to a `404: Not found` page when clicking on "follow the instruction" in the Windows section.

Regards,

Hugo Defois

**Comment by jorgelaranjo** [comment]
You can access the Google cached version in the meantime
[https://webcache.googleusercontent.com/search?q=cache:https://pystan.readthedocs.io/en/latest/getting_started.html](https://webcache.googleusercontent.com/search?q=cache:https://pystan.readthedocs.io/en/latest/getting_started.html)

**Comment by tcuongd** [comment]
Thanks Hugo, looks like this is the correct link: https://github.com/stan-dev/rstan/wiki/Configuring-C---Toolchain-for-Windows

**Comment by tcuongd** [comment]
Sorry I misread the issue initially, you're right that both the Windows installation links for pystan are broken. The updated links are:

* R: https://github.com/stan-dev/rstan/wiki/Configuring-C---Toolchain-for-Windows
* Python: https://pystan2.readthedocs.io/en/latest/windows.html

We'll need to also make it clear on the Python instructions that `pystan==2.19.1.1` needs to be installed.

**Comment by himanshu007-creator** [comment]
hi @tcuongd , i would like to work on this issue

**Comment by lokeswaran-aj** [comment]
@nelsoncardenas Yes, you can close this.

**Comment by nelsoncardenas** [comment]
@lokeswaran-aj I can't 🤔

**Comment by lokeswaran-aj** [comment]
@nelsoncardenas yes, even I cant close this issue. @defoishugo Can you close this issue?
