### ISSUE TITLE
Force prediction to be positive

### ISSUE THREAD

**Issue by Luffffffy** [facebook/prophet#2023]
Thank you for providing such a powerful tool ！！！

But i met a problem

The forecast is negative， so I can't use it

I've seen some of the same issues before,  is there any way to solve this problem now ?

**Comment by tcuongd** [comment]
Hey, Ben summarises the strategies for positive predictions here: https://github.com/facebook/prophet/issues/1668#issue-701631525

There is no functionality baked in to Prophet to do this, you'll want to either:
* Clip the predictions manually (`np.clip(preds, 0)`), or
* If the trend uncertainty is important and you want to show that it can become positive again, use the `ProphetPos` class that is written in that post.

**Comment by Luffffffy** [comment]
Thank you. It's very useful to me
