### ISSUE TITLE
How can I get the daily pattern data from model.plot_components()？

### ISSUE THREAD

**Issue by Yoshitama** [facebook/prophet#2028]
Hi everyone. When I running model.plot_components(), it will return some matplotlib plot figures(like 'trend-ds', 'weekly-ds', 'daily-ds'). I think it's useful but I need DataFrames instead of plot figures. How can I extract the data from the figure? thx :))

**Comment by tcuongd** [comment]
Hey there, can you see if this helps: https://github.com/facebook/prophet/issues/1920
