### ISSUE TITLE
External regressors impacting trend

### ISSUE THREAD

**Issue by Phildumoux** [facebook/prophet#2037]
Hi,

First of all, huge thanks for FBProphet which is an awesome tool.

I m using prophet to explain the influence of an external regressor on a time series. 
I know for sure that the increasing trend is 100% due to the value of that external regressor and that regressor can only have positive impact on the time series.

With crossvalidation and gridsearch, I m finding a trend that's below the observed point of the time series when the value of the regressor is very high. I m thinking that, the model is giving me, not the trend but the base index of the time series (the value of the time series that we would have without the impact of that regressor). 

The value of the extra regressor is the green curve. I m adding it to the model through intervals coded in dummy variables (because i think this regressor has a non linear relationship with y and I want to model it).

![image](https://user-images.githubusercontent.com/23377373/135429886-a2204c96-9464-48fa-8e6e-b805c21fb74e.png)

You can see that for 2012, the trend is below the observed time series which is unusual for a time series trend and I m unsecure about it. But having this type of trend is the only solution to have the extra regressor's coefficients matching our prior knowledge.

Any advice? Thank you !

**Comment by tcuongd** [comment]
You're right that external regressors can dampen the impact of the trend, and also vice versa. If your a-priori assumption is that the trend is the main driver of the series instead of the regressor, you can reduce the `prior_scale` value on the regressor. This will pull the regressor coefficients closer to 0. e.g.:

```python
m = Prophet()
m.add_regressor('regressor1', prior_scale=1.0)  # default is 10.0, the default for `holidays_prior_scale`
```
