### ISSUE TITLE
MIT License with PyStan (GPLv3 license) dependency?

### ISSUE THREAD

**Issue by benjaminsirb** [facebook/prophet#2053]
Hello,

I'm wondering on how this code can be provided with the MIT license when a dependency is PyStan, which is licensed under GPLv3. I'm fairly new to software licensing concepts so forgive me if this has an obvious answer; it's not immediately clear to me how that can work as I was under the impression that any software that depends on GPLv3 code must also then be provided with a GPLv3 license. Any help or guidance is appreciated!

**Comment by jhult** [comment]
FYI `pystan` appears to be disappearing in lieu of `cmdstanpy` (which is [BSD-3 licensed](https://github.com/stan-dev/cmdstanpy/blob/develop/LICENSE.md)). See #2041.

**Comment by WardBrian** [comment]
Closing due to PyStan no longer being a dependency of `prophet`
