### ISSUE TITLE
Setting appropriate value for changepoint_prior_scale

### ISSUE THREAD

**Issue by ascgou** [facebook/prophet#2061]
The trend component consists (a.o) of a base growth rate k and delta for the rate adjustments.

We can set a prior for delta, 
delta ∼ double_exponential(0, tau)

Tau can be set via changepoint_prior_scale in the code (if that is a correct interpretation)

Then my question evolves around determining the appropriate value for tau, whether it is dependent on the scale of my dependent variable y (e.g. whether the value for tau should be set differently in case my dependent variable is between 0-1 vs 0-1000) 
- I would think yes, as delta is an absolute growth rate (not relative) 
_As a reference (in the linear case), we have of course:
y ∼ normal((k + A * delta) .* t + (m + A * gamma) + X * beta, sigma);_
- The documentation seems to suggest not, as it has a fixed/absolute recommendation for the value of tau:
_" The default of 0.05 works for many time series"_ (https://facebook.github.io/prophet/docs/diagnostics.html)

Any explanation or advice is very welcome!

**Comment by tcuongd** [comment]
So under the hood, Prophet actually scales `y` to be between 0 and 1. We do this here: https://github.com/facebook/prophet/blob/ba9a5a2c6e2400206017a5ddfd71f5042da9f65b/python/prophet/forecaster.py#L349-L350
https://github.com/facebook/prophet/blob/ba9a5a2c6e2400206017a5ddfd71f5042da9f65b/python/prophet/forecaster.py#L327

Which I think is why Ben and Sean were able to pick a value that works for many time series.
That said I think it's still good to inspect this parameter for your time series, especially if the trend fit doesn't seem to match the history well. I would probably start with an order of magnitude (i.e. 0.005 for "flatter" trend, 0.5 for a more flexible trend), then go from there depending on how much the trend fit changes.

**Comment by ascgou** [comment]
Thanks, the crucial part was the scaling under the hood indeed. Thanks
