### ISSUE TITLE
Release a new version to pypi

### ISSUE THREAD

**Issue by akosfurton** [facebook/prophet#2064]
Hello @tcuongd or @bletham ,

I noticed that there has not been a release of prophet to PyPi in ~6 months.

In that time, https://github.com/facebook/prophet/pull/2010 has been merged to create Python Wheels for PyPi, which makes the installation experience significantly easier from a `pip install prophet` command.

Could you please upload these wheels to PyPi?

**Comment by tcuongd** [comment]
Yeah sorry we've dropped the ball on this one. Ben's been busy and I haven't had time to finish https://github.com/facebook/prophet/issues/2041

It's a bit hard to give an ETA since holiday season is coming up but I'll at least get the components of issue 2401 ready and let Ben know.

**Comment by ocardia** [comment]
Any news on this? 👋🏻

**Comment by tboddyspargo** [comment]
I was really excited to see #2041 and #2088 get completed, but I was hoping that there might be a forthcoming wheel released to PyPI soon that includes those changes. It would help my team considerably to be able to drop the `pystan` dependency.

@bletham, @tcuongd - Do you think a new wheel release on PyPI will be possible soon? Thanks for all your work on this!

**Comment by nlhkh** [comment]
I am also waiting for the new release. There are lots of good commits that have not been made available in the last year.

**Comment by akosfurton** [comment]
@winedarksea, can you reach out to @bletham on Meta internal chat about how to publish releases to Pypi?

cc: @orenmatar

**Comment by akosfurton** [comment]
https://github.com/facebook/prophet/pull/2202

**Comment by tcuongd** [comment]
Thanks everyone for your patience and help! With this release: https://github.com/facebook/prophet/releases/tag/v1.1
we now have wheels on PyPI (https://pypi.org/project/prophet/).
