### ISSUE TITLE
install Fbprophet issue : pystan shows installed as the log showed but after trying install fbprophet log shows pystan need to be installed 

### ISSUE THREAD

**Issue by Majeedraheem** [facebook/prophet#2066]
mac@Macs-MacBook-Pro ~ % pip install pystan 
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Requirement already satisfied: pystan in /usr/local/lib/python3.9/site-packages (3.3.0)
Requirement already satisfied: numpy<2.0,>=1.7 in /usr/local/lib/python3.9/site-packages (from pystan) (1.21.4)
Requirement already satisfied: pysimdjson<4.0,>=3.2 in /usr/local/lib/python3.9/site-packages (from pystan) (3.2.0)
Requirement already satisfied: clikit<0.7,>=0.6 in /usr/local/lib/python3.9/site-packages (from pystan) (0.6.2)
Requirement already satisfied: aiohttp<4.0,>=3.6 in /usr/local/lib/python3.9/site-packages (from pystan) (3.8.0)
Requirement already satisfied: httpstan<4.7,>=4.6 in /usr/local/lib/python3.9/site-packages (from pystan) (4.6.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.9/site-packages (from aiohttp<4.0,>=3.6->pystan) (21.2.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.9/site-packages (from aiohttp<4.0,>=3.6->pystan) (4.0.0)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /usr/local/lib/python3.9/site-packages (from aiohttp<4.0,>=3.6->pystan) (2.0.7)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.9/site-packages (from aiohttp<4.0,>=3.6->pystan) (1.7.2)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.9/site-packages (from aiohttp<4.0,>=3.6->pystan) (1.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.9/site-packages (from aiohttp<4.0,>=3.6->pystan) (5.2.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.9/site-packages (from aiohttp<4.0,>=3.6->pystan) (1.2.0)
Requirement already satisfied: pastel<0.3.0,>=0.2.0 in /usr/local/lib/python3.9/site-packages (from clikit<0.7,>=0.6->pystan) (0.2.1)
Requirement already satisfied: pylev<2.0,>=1.3 in /usr/local/lib/python3.9/site-packages (from clikit<0.7,>=0.6->pystan) (1.4.0)
Requirement already satisfied: crashtest<0.4.0,>=0.3.0 in /usr/local/lib/python3.9/site-packages (from clikit<0.7,>=0.6->pystan) (0.3.1)
Requirement already satisfied: appdirs<2.0,>=1.4 in /usr/local/lib/python3.9/site-packages (from httpstan<4.7,>=4.6->pystan) (1.4.4)
Requirement already satisfied: setuptools>=41.0 in /usr/local/lib/python3.9/site-packages (from httpstan<4.7,>=4.6->pystan) (57.4.0)
Requirement already satisfied: webargs<9.0,>=8.0 in /usr/local/lib/python3.9/site-packages (from httpstan<4.7,>=4.6->pystan) (8.0.1)
Requirement already satisfied: marshmallow<4.0,>=3.10 in /usr/local/lib/python3.9/site-packages (from httpstan<4.7,>=4.6->pystan) (3.14.0)
Requirement already satisfied: typing-extensions>=3.6.5 in /usr/local/lib/python3.9/site-packages (from async-timeout<5.0,>=4.0.0a3->aiohttp<4.0,>=3.6->pystan) (3.10.0.2)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.9/site-packages (from yarl<2.0,>=1.0->aiohttp<4.0,>=3.6->pystan) (3.3)
mac@Macs-MacBook-Pro ~ % 
mac@Macs-MacBook-Pro ~ % pip install fbprophet 
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Collecting fbprophet
  Using cached fbprophet-0.7.1.tar.gz (64 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: Cython>=0.22 in /usr/local/lib/python3.9/site-packages (from fbprophet) (0.29.24)
Requirement already satisfied: cmdstanpy==0.9.5 in /usr/local/lib/python3.9/site-packages (from fbprophet) (0.9.5)
Requirement already satisfied: pystan>=2.14 in /usr/local/lib/python3.9/site-packages (from fbprophet) (3.3.0)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.9/site-packages (from fbprophet) (1.21.4)
Requirement already satisfied: pandas>=1.0.4 in /usr/local/lib/python3.9/site-packages (from fbprophet) (1.3.4)
Requirement already satisfied: matplotlib>=2.0.0 in /usr/local/lib/python3.9/site-packages (from fbprophet) (3.4.3)
Requirement already satisfied: LunarCalendar>=0.0.9 in /usr/local/lib/python3.9/site-packages (from fbprophet) (0.0.9)
Requirement already satisfied: convertdate>=2.1.2 in /usr/local/lib/python3.9/site-packages (from fbprophet) (2.3.2)
Requirement already satisfied: holidays>=0.10.2 in /usr/local/lib/python3.9/site-packages (from fbprophet) (0.11.3.1)
Requirement already satisfied: setuptools-git>=1.2 in /usr/local/lib/python3.9/site-packages (from fbprophet) (1.2)
Requirement already satisfied: python-dateutil>=2.8.0 in /usr/local/lib/python3.9/site-packages (from fbprophet) (2.8.2)
Requirement already satisfied: tqdm>=4.36.1 in /usr/local/lib/python3.9/site-packages (from fbprophet) (4.62.3)
Requirement already satisfied: pytz>=2014.10 in /usr/local/lib/python3.9/site-packages (from convertdate>=2.1.2->fbprophet) (2021.3)
Requirement already satisfied: pymeeus<=1,>=0.3.13 in /usr/local/lib/python3.9/site-packages (from convertdate>=2.1.2->fbprophet) (0.5.11)
Requirement already satisfied: hijri-converter in /usr/local/lib/python3.9/site-packages (from holidays>=0.10.2->fbprophet) (2.2.2)
Requirement already satisfied: korean-lunar-calendar in /usr/local/lib/python3.9/site-packages (from holidays>=0.10.2->fbprophet) (0.2.1)
Requirement already satisfied: ephem>=3.7.5.3 in /usr/local/lib/python3.9/site-packages (from LunarCalendar>=0.0.9->fbprophet) (4.1)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/local/lib/python3.9/site-packages (from matplotlib>=2.0.0->fbprophet) (3.0.5)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.9/site-packages (from matplotlib>=2.0.0->fbprophet) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.9/site-packages (from matplotlib>=2.0.0->fbprophet) (0.11.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.9/site-packages (from matplotlib>=2.0.0->fbprophet) (8.4.0)
Requirement already satisfied: aiohttp<4.0,>=3.6 in /usr/local/lib/python3.9/site-packages (from pystan>=2.14->fbprophet) (3.8.0)
Requirement already satisfied: httpstan<4.7,>=4.6 in /usr/local/lib/python3.9/site-packages (from pystan>=2.14->fbprophet) (4.6.1)
Requirement already satisfied: clikit<0.7,>=0.6 in /usr/local/lib/python3.9/site-packages (from pystan>=2.14->fbprophet) (0.6.2)
Requirement already satisfied: pysimdjson<4.0,>=3.2 in /usr/local/lib/python3.9/site-packages (from pystan>=2.14->fbprophet) (3.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/site-packages (from python-dateutil>=2.8.0->fbprophet) (1.16.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.9/site-packages (from aiohttp<4.0,>=3.6->pystan>=2.14->fbprophet) (1.2.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.9/site-packages (from aiohttp<4.0,>=3.6->pystan>=2.14->fbprophet) (1.7.2)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.9/site-packages (from aiohttp<4.0,>=3.6->pystan>=2.14->fbprophet) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.9/site-packages (from aiohttp<4.0,>=3.6->pystan>=2.14->fbprophet) (21.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.9/site-packages (from aiohttp<4.0,>=3.6->pystan>=2.14->fbprophet) (5.2.0)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /usr/local/lib/python3.9/site-packages (from aiohttp<4.0,>=3.6->pystan>=2.14->fbprophet) (2.0.7)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.9/site-packages (from aiohttp<4.0,>=3.6->pystan>=2.14->fbprophet) (4.0.0)
Requirement already satisfied: crashtest<0.4.0,>=0.3.0 in /usr/local/lib/python3.9/site-packages (from clikit<0.7,>=0.6->pystan>=2.14->fbprophet) (0.3.1)
Requirement already satisfied: pastel<0.3.0,>=0.2.0 in /usr/local/lib/python3.9/site-packages (from clikit<0.7,>=0.6->pystan>=2.14->fbprophet) (0.2.1)
Requirement already satisfied: pylev<2.0,>=1.3 in /usr/local/lib/python3.9/site-packages (from clikit<0.7,>=0.6->pystan>=2.14->fbprophet) (1.4.0)
Requirement already satisfied: setuptools>=41.0 in /usr/local/lib/python3.9/site-packages (from httpstan<4.7,>=4.6->pystan>=2.14->fbprophet) (57.4.0)
Requirement already satisfied: appdirs<2.0,>=1.4 in /usr/local/lib/python3.9/site-packages (from httpstan<4.7,>=4.6->pystan>=2.14->fbprophet) (1.4.4)
Requirement already satisfied: marshmallow<4.0,>=3.10 in /usr/local/lib/python3.9/site-packages (from httpstan<4.7,>=4.6->pystan>=2.14->fbprophet) (3.14.0)
Requirement already satisfied: webargs<9.0,>=8.0 in /usr/local/lib/python3.9/site-packages (from httpstan<4.7,>=4.6->pystan>=2.14->fbprophet) (8.0.1)
Requirement already satisfied: typing-extensions>=3.6.5 in /usr/local/lib/python3.9/site-packages (from async-timeout<5.0,>=4.0.0a3->aiohttp<4.0,>=3.6->pystan>=2.14->fbprophet) (3.10.0.2)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.9/site-packages (from yarl<2.0,>=1.0->aiohttp<4.0,>=3.6->pystan>=2.14->fbprophet) (3.3)
Building wheels for collected packages: fbprophet
  Building wheel for fbprophet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/gk/537qy50d4ls5vppc09_8xb0r0000gn/T/pip-install-016rcptn/fbprophet_e3b4326b43f84c3a9f3e9800b94f4d45/setup.py'"'"'; __file__='"'"'/private/var/folders/gk/537qy50d4ls5vppc09_8xb0r0000gn/T/pip-install-016rcptn/fbprophet_e3b4326b43f84c3a9f3e9800b94f4d45/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/gk/537qy50d4ls5vppc09_8xb0r0000gn/T/pip-wheel-wegak9i3
       cwd: /private/var/folders/gk/537qy50d4ls5vppc09_8xb0r0000gn/T/pip-install-016rcptn/fbprophet_e3b4326b43f84c3a9f3e9800b94f4d45/
  Complete output (39 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/fbprophet
  creating build/lib/fbprophet/stan_model
  Importing plotly failed. Interactive plots will not work.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/gk/537qy50d4ls5vppc09_8xb0r0000gn/T/pip-install-016rcptn/fbprophet_e3b4326b43f84c3a9f3e9800b94f4d45/setup.py", line 122, in <module>
      setup(
    File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/gk/537qy50d4ls5vppc09_8xb0r0000gn/T/pip-install-016rcptn/fbprophet_e3b4326b43f84c3a9f3e9800b94f4d45/setup.py", line 48, in run
      build_models(target_dir)
    File "/private/var/folders/gk/537qy50d4ls5vppc09_8xb0r0000gn/T/pip-install-016rcptn/fbprophet_e3b4326b43f84c3a9f3e9800b94f4d45/setup.py", line 38, in build_models
      StanBackendEnum.get_backend_class(backend).build_model(target_dir, MODEL_DIR)
    File "/private/var/folders/gk/537qy50d4ls5vppc09_8xb0r0000gn/T/pip-install-016rcptn/fbprophet_e3b4326b43f84c3a9f3e9800b94f4d45/fbprophet/models.py", line 209, in build_model
      import pystan
  ModuleNotFoundError: No module named 'pystan'
  ----------------------------------------
  ERROR: Failed building wheel for fbprophet
  Running setup.py clean for fbprophet
Failed to build fbprophet
Installing collected packages: fbprophet
    Running setup.py install for fbprophet ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/gk/537qy50d4ls5vppc09_8xb0r0000gn/T/pip-install-016rcptn/fbprophet_e3b4326b43f84c3a9f3e9800b94f4d45/setup.py'"'"'; __file__='"'"'/private/var/folders/gk/537qy50d4ls5vppc09_8xb0r0000gn/T/pip-install-016rcptn/fbprophet_e3b4326b43f84c3a9f3e9800b94f4d45/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/gk/537qy50d4ls5vppc09_8xb0r0000gn/T/pip-record-f_o3z7vd/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/fbprophet
         cwd: /private/var/folders/gk/537qy50d4ls5vppc09_8xb0r0000gn/T/pip-install-016rcptn/fbprophet_e3b4326b43f84c3a9f3e9800b94f4d45/
    Complete output (41 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/fbprophet
    creating build/lib/fbprophet/stan_model
    Importing plotly failed. Interactive plots will not work.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/gk/537qy50d4ls5vppc09_8xb0r0000gn/T/pip-install-016rcptn/fbprophet_e3b4326b43f84c3a9f3e9800b94f4d45/setup.py", line 122, in <module>
        setup(
      File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.9/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/install.py", line 546, in run
        self.run_command('build')
      File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/gk/537qy50d4ls5vppc09_8xb0r0000gn/T/pip-install-016rcptn/fbprophet_e3b4326b43f84c3a9f3e9800b94f4d45/setup.py", line 48, in run
        build_models(target_dir)
      File "/private/var/folders/gk/537qy50d4ls5vppc09_8xb0r0000gn/T/pip-install-016rcptn/fbprophet_e3b4326b43f84c3a9f3e9800b94f4d45/setup.py", line 38, in build_models
        StanBackendEnum.get_backend_class(backend).build_model(target_dir, MODEL_DIR)
      File "/private/var/folders/gk/537qy50d4ls5vppc09_8xb0r0000gn/T/pip-install-016rcptn/fbprophet_e3b4326b43f84c3a9f3e9800b94f4d45/fbprophet/models.py", line 209, in build_model
        import pystan
    ModuleNotFoundError: No module named 'pystan'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/gk/537qy50d4ls5vppc09_8xb0r0000gn/T/pip-install-016rcptn/fbprophet_e3b4326b43f84c3a9f3e9800b94f4d45/setup.py'"'"'; __file__='"'"'/private/var/folders/gk/537qy50d4ls5vppc09_8xb0r0000gn/T/pip-install-016rcptn/fbprophet_e3b4326b43f84c3a9f3e9800b94f4d45/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/gk/537qy50d4ls5vppc09_8xb0r0000gn/T/pip-record-f_o3z7vd/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/fbprophet Check the logs for full command output.
mac@Macs-MacBook-Pro ~ %

**Comment by tcuongd** [comment]
Please follow these instructions: https://github.com/facebook/prophet#installation-in-python

You'll need to `pip install pystan==2.19.1.1` first, since pystan >=3.0 is not supported. We're working on removing the pystan dependency altogether but that's a few months away unfortunately.

**Comment by darshankachhadiya** [comment]
Thanks bro its working for me
