### ISSUE TITLE
add_regressor() got an unexpected keyword argument 'constraint'

### ISSUE THREAD

**Issue by ashishsoniece** [facebook/prophet#2069]
----> 1 model.add_regressor('sunday',constraint = 'positive') #mode = 'additive' ,prior_scale= 0.7,
      2 model.add_regressor('saturday',constraint = 'positive')# mode = 'additive' ,prior_scale= 0.7)
      3 model.add_regressor('monday',constraint = 'negative') #mode = 'additive' ,prior_scale= 0.2)
      4 model.add_regressor('tuesday',constraint = 'negative')#mode = 'additive' ,prior_scale= 0.2)
      5 model.add_regressor('days_3_lower',constraint = 'positive') #mode = 'additive' ,prior_scale= 0.7
add_regressor() got an unexpected keyword argument 'constraint'

showing me this error .... i used  from prophet import Prophet

**Comment by tcuongd** [comment]
We haven't implemented this feature, perhaps you intended to use a Prophet version from one of the branches in this thread: https://github.com/facebook/prophet/issues/1405 ?
