### ISSUE TITLE
Prophet library not installed on window 10

### ISSUE THREAD

**Issue by Kritika-11** [facebook/prophet#2073]
![image](https://user-images.githubusercontent.com/87233578/142616347-79cb35a5-da6f-4200-9628-d0ebe9d2244e.png)

I have followed all the steps from the below link but I am not able to install prophet library in windows10.

https://medium.com/data-folks-indonesia/installing-fbprophet-prophet-for-time-series-forecasting-in-jupyter-notebook-7de6db09f93e

**Comment by JuroMecir** [comment]
Hi. 

It seems like you have a typo in your import. Try this instead:

`from prophet import Prophet`

**Comment by Kritika-11** [comment]
> Hi.
> 
> It seems like you have a typo in your import. Try this instead:
> 
> `from prophet import Prophet`


![image](https://user-images.githubusercontent.com/87233578/142974086-8fb26ec7-59b6-43f4-99a2-c2c38d9255e1.png)

Tried this but still it's not working
