### ISSUE TITLE
Neptune + FBprophet integration

### ISSUE THREAD

**Issue by Blaizzy** [facebook/prophet#2079]
Hi,

Prince Canuma here, a Data Scientist at [Neptune.ai](https://www.neptune.ai)

I'm working on the FBprophet integration to help FBprophet users easily log their experiment's metadata to Neptune with a few lines of code.

I would like to connect with you (maintainers) and know more about your product roadmap (i.e. upcoming features and breaking changes).

**Comment by tcuongd** [comment]
Hey Blaizzy, that's super cool :) Feel free to email myself (cuong.duong242@gmail.com) and Ben (bletham@fb.com) with your plans and we can answer any questions. The roadmap for the package isn't set in stone yet, but once it is I'm hoping to have it somewhere on Github.

**Comment by Blaizzy** [comment]
Thanks a lot @tcuongd

Sending it right away!!

**Comment by Blaizzy** [comment]
Hi @tcuongd 

Happy new year!!

I just want to follow up on the email,

I have sent it but I haven't had a response till today.
