### ISSUE TITLE
Can you pass lower_ and upper_window when using m.add_country_holidays()?

### ISSUE THREAD

**Issue by psylabs** [facebook/prophet#2080]
Hi,
When using the add_country_holidays() method is it possible to include the upper and lower holiday windows? I see that this is possible when you create your own holiday_df but was wondering if it was possible without creating your own holiday_df. I ask because it looks like Prophet creates these features which show up in the forecast df when using the convenient provided add_country_holidays() method. But it looks like they don't get used? `forecast.columns` shows 

['ds', 'trend', 'yhat_lower', 'yhat_upper', 'trend_lower', 'trend_upper', 'Christmas Day', 'Christmas Day_lower', 'Christmas Day_upper',  'Christmas Day (Observed)', 'Christmas Day (Observed)_lower', 'Christmas Day (Observed)_upper', 'Columbus Day', 'Columbus Day_lower', ....]

Question 2:
If we create our own holiday_df do the names of the holidays matter? I see that `make_holiday_features()` creates a column for each holiday. I assume thus that you can't have the same holiday column name repeated as a feature, but yet the docs use the same holiday name 'playoff' and 'superbowl' so I'm a little confused. Assuming you provided a holiday df with US holidays, is `m = Prophet(holidays=holidays)` equivalent to `m.add_country_holidays(country_name='US')` ?

Thanks,

**Comment by tcuongd** [comment]
Hey there. 

1. There's no functionality to add lower/upper windows via `add_country_holidays()`.
2. The names of the holidays do matter; you would need one entry in the `holiday_df` for every date on which the holiday occurs, in the training dataset and in the future. So for example if you had

| ds | holiday |
| --- | ------ |
| 2021-01-01 | playoff |
| 2022-01-03 | playoff |

this gets turned into

| ds | playoff |
| --- | ------- |
| 2021-01-01 | 1 |
| 2021-01-02 | 0 |
| 2021-01-03 | 0 |
| ... | 0 |
| 2022-01-03 | 1 |

in the training dataframe. Specifying lower / upper windows will add extra 1s around the holiday date.
