### ISSUE TITLE
Found Conflicts during prophet install

### ISSUE THREAD

**Issue by Jillian2046** [facebook/prophet#2083]
I installed Pystan 2.19.1.1 onto my win10 (I have python 3.7), then I use anaconda command to install prophet:
conda install -c conda-forge prophet

But then it showed "Found conflicts! Looking for incompatible packages.", and keeping examining for conflicts (for >1 hour)?

Is it normal? shall I abort and re-install?

Thank you!

**Comment by maresb** [comment]
Conda is well-known to choke on all but the simplest environments. I'd recommend using `mamba` instead.

```bash
conda install -c conda-forge mamba
mamba install -c conda-forge prophet
```

In case of conflicts, `mamba` usually gives more coherent error messages.

If you want to install into a fresh environment, I'd recommend

```bash
conda create --name my-prophet-env -c conda-forge mamba python=3.9
conda activate my-prophet-env
mamba install prophet
```

**Comment by WardBrian** [comment]
Closing due to PyStan no longer being a dependency of `prophet`
