### ISSUE TITLE
Cannot install Prophet

### ISSUE THREAD

**Issue by yclui** [facebook/prophet#2085]
I am trying to set up my laptop ( Windows 10 ) for running Prophet but I am encountering some problems. I managed to install pystan and mingw-w64 C++ compiler in Anaconda and running the test codes provided in the pystan site (https://pystan2.readthedocs.io/en/latest/windows.html ) seems to have indicated that pystan is able to use the C++ compiler successfully.  However, when I tried to install Prophet in the Pip(3.9) terminal in Microsoft VS code,  I got the following error. The main error is “MSVC Compiler is not supported” which , according to the pystan site, is known and no fixes are known other than to change the compiler to GCC or clang-cl.  Is the use of these C++ compiler a must ?

![image](https://user-images.githubusercontent.com/96032354/145742144-e0cfb328-6aeb-437b-ba49-e362a80c0738.png)

Then I tried to install Prophet in Anaconda and I got errors of different kinds : 

![image](https://user-images.githubusercontent.com/96032354/145742118-9efaea59-e4cf-4be2-b074-00bb5d076275.png)

Can anyone let me know how Prophet can be installed successfully ?

**Comment by isabella-karabasz** [comment]
Hi, I was having the same issue with pip install and found the solution here: https://github.com/facebook/prophet#anaconda

> Use `conda install gcc` to set up gcc. The easiest way to install Prophet is through conda-forge: `conda install -c conda-forge prophet`.

Worked for me :)

**Comment by alfredaita** [comment]
conda install gcc does not work.
following pystan 2.19.1.1 instructions work fine.
prophet must be looking for a different compiler.
I did have prophet working in an earlier conda build.
had to rebuild the packages and now cant get prophet installea

**Comment by akosfurton** [comment]
This has been resolved in prophet 1.1. You can now `pip install prophet` directly from PyPI on Windows

**Comment by WardBrian** [comment]
Closing due to PyStan no longer being a dependency of `prophet`
