### ISSUE TITLE
Error on starting: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by birdynm** [facebook/prophet#2092]
Dear all,

I "successfully" installed seafile-server-8.0.7 on my rpi 4.
When trying to start seafile I get the error "cannot execute binary file: Exec format error".

I tried it with Raspberry Py Os bullseye and Raspbertry Py Os legacy (buster). But with both the same error.

Any idea?

Starting seafile server, please wait ...
./seafile.sh: Zeile 114: /opt/seafile/seafile-server-8.0.7/seafile/bin/seafile-controller: cannot execute binary file: Exec format error
Failed to start seafile server

**Comment by birdynm** [comment]
Somehow I thought I opened that issue at "haiwen/seafile-rpi"
I don't know either that topic got moved (what I don't see) or I just messed up....

**Comment by tcuongd** [comment]
Closing
