### ISSUE TITLE
forecasting values for each category using Prophet in python

### ISSUE THREAD

**Issue by analysismaster** [facebook/prophet#2095]
Can you please go over the code below? I try to get forecasting values for each category using Prophet in python.
I found some codes on the web. But they don't work. Please find the solution for this.

---------------------------------------------------------------------------------------------------------
import pandas as pd
from fbprophet import Prophet
df=pd.read_csv('data1.csv')

def get_prediction(df):
prediction={}
df2=df.rename(columns={'sales_date': 'ds', 'quantity': 'y', 'products': 'article'})
list_articles=df2.article.unique()

for article in list_articles:
article_df = df2.loc[df2['article'] == article]

my_model=Prophet(weekly_seasonality=False, daily_seasonality=True, seasonality_prior_scale=1.0)
my_model.fit(article_df)
future_dates=my_model.make_future_dataframe(periods=30, freq='D')
forecast=my_model.prediction(future)
predction[article]=forecast
return prediction
---------------------------------------------------------------------------------------------------------

**Comment by tcuongd** [comment]
Hey, could you confirm the error message? From first glance I don't think this is a Prophet issue, but there may be an issue in your Python code. For example:

* `my_model.prediction(future)` should be `my_model.predict()`
* `predction` is a typo on the second last line.
