### ISSUE TITLE
How many records (categories) are allowed to group when using Prophet?

### ISSUE THREAD

**Issue by analysismaster** [facebook/prophet#2096]
How many records (categories) are allowed to group when using Prophet?
I try to get forecasting values for each category by Prophet. How many records does Prophet work for?

**Comment by tcuongd** [comment]
This is not controlled by Prophet. If you are looping through a dataframe, you can create as many forecasts as you want. Keep in mind though that the accuracy may vary greatly, depending on how much data each category contains and the characteristics of each time series.
