### ISSUE TITLE
unable to install fbprophet in my virtual environment

### ISSUE THREAD

**Issue by zetag33** [facebook/prophet#2101]
If I try to pip install pystan it works fine, but then when it gets to pip install fbprophet it gives an error while building the wheel, basically it is unable to, and then crashes.

I've tried also to do it by anaconda with my virtual environment activated, conda install -c conda-forge fbprophet, and it gets stuck solving the environment and doesnt get through.

As I have read the problem with pip install fbprophet is a pystan problem that basically says pystan doesnt work, so I tried to install another compiler such as conda install -c conda-forge gcc, and then try to install the fbprophet again and it does not work.

I'm using ubuntu 20.04 in a virtualbox machine.

I've been the whole day researching how to do it and I've found no way.

**Comment by athulvis** [comment]
Did you try `pip3 install prophet` instead of `fbprophet` ?

**Comment by alfredaita** [comment]
when I was running python 3.7. * everything went as planned.
When I reinstalled conda  with python 3.9 .* I was able to install pystan 2.19.1.1
but not prophet.
when examining the project page my results seem consistent. That is it states windows 3.8 and not higher. This may only require opening the constraints or something more complicated.
2 workarounds 
1) create an environment using python 3.7 [ I use Anaconda navigator for this]
2) create a google colab notebook for this.
Personally, I'm gravitating toward the second option.

**Comment by alfredaita** [comment]
I did have prophet working in windows on on an older version of python. 3.7 I . 



Sent from Yahoo Mail for iPhone


On Thursday, February 10, 2022, 12:32 PM, Athul R T ***@***.***> wrote:




@alfredaita
   
   - From previous issues, it is clear that we can't use Prophet in Windows system. Here the reported issue is in Ubuntu 20.04. Prophet works well with Ubuntu and Python 3.9 for me.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zetag33** [comment]
Thanks anyway guys, I just solve it using conda, pip install prophet kept on failing to build the wheel, but conda did it without problems
