### ISSUE TITLE
pandas frame.appendis deprecated 

### ISSUE THREAD

**Issue by Conet1502** [facebook/prophet#2131]
fbprophet\forecaster.py:891: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

**Comment by jul-carras** [comment]
Looks like there is a [pull request](https://github.com/facebook/prophet/pull/2114) from [nlhkh](https://github.com/nlhkh) for this already. Should be merged in soon.

**Comment by nlhkh** [comment]
The maintainers disappeared. It has been 2 months and no response.

**Comment by jul-carras** [comment]
Could just be a busy time. I've looked at closed pull requests and sometimes it takes a few months to bring them in.

**Comment by Nil-Andreu** [comment]
I think is due to the pandas `append` method, that will be deprecated in the future.

So this method is basically to add in a given dataframe another dataframe. This can be done:

```python
# With append
df.append(df_other)

# With concat
pd.concat([df, df_other])
```

And basically the one that will be supported in the future is the second one.
