### ISSUE TITLE
Documentation suggests double-encoding Python models to JSON

### ISSUE THREAD

**Issue by tomsutch** [facebook/prophet#2133]
The [additional_topics page](https://facebook.github.io/prophet/docs/additional_topics.html#saving-models) suggests saving/reading a Prophet model in Python like so:

```python
import json
from prophet.serialize import model_to_json, model_from_json

with open('serialized_model.json', 'w') as fout:
    json.dump(model_to_json(m), fout)  # Save model

with open('serialized_model.json', 'r') as fin:
    m = model_from_json(json.load(fin))  # Load model
```

However, this encodes the model to JSON twice over:
*  `model_to_json` encodes the model to a string of JSON
* then `json.dump` encodes this string further when writing the file

This means that the `serialized_model.json` file contains one string only as the root node - everything within it is escaped with backslashes. So the beginning of my file is

```
"{\"growth\": \"linear\", \"n_changepoints\": 25, \"specified_changepoints\": false, \"changepoint_range\": 0.8, \"yearly_seasonality\": false, \"weekly_seasonality\": false, \"daily_seasonality\": false,
...
"
```

Obviously this is ok if we then read in the file using the example code, as it then double-decodes it. But for general use it would be better if the json file were more readable.

Surely instead it would be better to do:

```python
from prophet.serialize import model_to_json, model_from_json

with open('serialized_model.json', 'w') as fout:
    fout.write(model_to_json(m))  # Save model

with open('serialized_model.json', 'r') as fin:
    m = model_from_json(fin.read())  # Load model
```

Or is there a reason why you'd want to double-encode?

**Comment by tcuongd** [comment]
Great pickup :) I don't think there's any reason to double encode, I think your code makes more sense -- feel free to raise a PR to clarify those docs if you'd like (happy to help as well)
