### ISSUE TITLE
Error when passing STAN arguments.

### ISSUE THREAD

**Issue by nipnipj** [facebook/prophet#2139]
```
fit.prophet(m, data, chains = 3, iter = 1000, warmup = 500, control = list(adapt_delta = 0.9))
```
Results in 
```
Error: passing unknown arguments: chains, warmup, control.
```

**Comment by tcuongd** [comment]
Are you trying to run full MCMC sampling? You'll need to set a value for `mcmc.samples` that is greater than 0. Otherwise, the package runs the MAP estimation routine, which doesn't use chains / warmup / control.

**Comment by nipnipj** [comment]
Could you, please, share a quick example? I'm getting the following error:
```
Error: passing unknown arguments: mcmc.samples.
```
