### ISSUE TITLE
Unable to install fbprophet==0.7.1 in Sagemaker JupyterLab

### ISSUE THREAD

**Issue by rahul4tripathi2** [facebook/prophet#2144]
Hi,

Can you please share any link where I can get the wheel file of fbprophet==0.7.1 for linux (Sagemaker JupyterLab)

I tried creating the wheel file using give tar.gz file but it is failing during model.fit()

Error - attributeerror 'prophet' object has no attribute 'stan backend'

I tried every approaches present in Issues but none worked

Regards
Rahul

**Comment by jeremyallenjacobson** [comment]
Same issue here.

**Comment by rahul4tripathi2** [comment]
Installed prophet 1.0.1 using below url
https://test.pypi.org/project/prophet/#files
