### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Shmeeed** [facebook/prophet#2146]
I wa able to get pystan downloaded, but now when installing fbprophet i receive this error.

(base) Matthews-MBP-2:~ doyle$
(base) Matthews-MBP-2:~ doyle$ conda install -c conda-forge fbprophet
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes. Press CTRL-C to abort.
failed
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:
Specifications:
- fbprophet -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.5,<3.6.0a0']
Your python: python=3.9
If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

**Comment by tcuongd** [comment]
The package is now called `prophet`. You should be able to install that from conda forge directly without having to install pystan first.

**Comment by akosfurton** [comment]
This has been resolved in prophet 1.1. You can now `pip install prophet` directly from PyPI
