### ISSUE TITLE
Peer reviewed reference

### ISSUE THREAD

**Issue by BrendanMD** [facebook/prophet#2151]
Is there a peer reviewed reference for Prophet, published within a reputable journal? I would like to consider using Prophet in my research, but without a real publication reference, it would be pointless and irresponsible to do so.

**Comment by BrendanMD** [comment]
Ah. Found it. Insert foot in mouth. Tastes like... dirty socks.

**Comment by tcuongd** [comment]
http://lethalletham.com/ForecastingAtScale.pdf

**Comment by BrendanMD** [comment]
Thank-you.
