### ISSUE TITLE
Prophet' object has no attribute 'stan_backend

### ISSUE THREAD

**Issue by LoanSarazin** [facebook/prophet#2153]
Hello, I al running two different notebooks in the same conda env, and in one I get the error `['Prophet' object has no attribute 'stan_backend']()`, but not in the other.

It appends direcly after doing 
`from prophet import Prophet  
m = Prophet`

pystan has been installed in v2.19.1.1, and I am using python 3.8.

**Comment by rahul4tripathi2** [comment]
use CMDSTANPY is backend
m = Prophet(uncertainty_samples=100,stan_backend='CMDSTANPY', growth='logistic', seasonality_mode='multiplicative',changepoint_prior_scale=0.5, )
