### ISSUE TITLE
Cannot install on windows

### ISSUE THREAD

**Issue by VianneyMI** [facebook/prophet#2154]
It's really frustrating not being able to use the library in a real python project because it cannot be installed through pip on windows.

Please update the documentation to let us know how to install using pip

**Comment by xvlvzhu** [comment]
recommend use anaconda to install prophet
"conda install -c conda-forge fbprophet"

**Comment by rahul4tripathi2** [comment]
Install using below url
https://test.pypi.org/project/prophet/#files

**Comment by alexlach** [comment]
I encountered the same broken link in the documentation:
https://pystan.readthedocs.io/en/latest/windows.html

**Comment by VianneyMI** [comment]
@uniquegino  same here, I literally spend X months on this also. At the end, I decided to install Windows Subsystem for Linux and moved forward with my project using the WSL.

Now I am considering using another library like this one : https://github.com/Nixtla/statsforecast but the doc does not ease the transition neither.

Anyway good luck with your project !

**Comment by tcuongd** [comment]
See https://github.com/facebook/prophet/issues/2107#issuecomment-1133927696

**Comment by akosfurton** [comment]
This has been resolved in prophet 1.1. You can now `pip install prophet` directly from PyPI on Windows
