### ISSUE TITLE
Precompiled models

### ISSUE THREAD

**Issue by ankane** [facebook/prophet#2162]
Hi, I recently shipped precompiled Stan models with the [Ruby port](https://github.com/ankane/prophet-ruby), so wanted to share some of the resources in case it's useful (saw there's been some work done around this in #2010).

1. [Packaging code](https://github.com/ankane/strata)
2. CI runners - [Linux](https://github.com/ankane/ml-builds/blob/master/.github/workflows/prophet-linux.yml) and [Mac](https://github.com/ankane/ml-builds/blob/master/.github/workflows/prophet-mac.yml) (with cross-compilation)
3. [Precompiled models](https://github.com/ankane/ml-builds/releases/tag/prophet-1.0-1)

Also, thanks for this project!

**Comment by tcuongd** [comment]
Thanks heaps! We ended up settling on the wheels here: https://github.com/facebook/prophet/actions/runs/2275140778 built on the `master` branch, but I'll definitely take a look at your code to see if there's further improvements / simplifications we can make :)

**Comment by ankane** [comment]
Great, that should make installation much easier 🎉
