### ISSUE TITLE
AttributeError: 'StanModel' object has no attribute 'fit_class'

### ISSUE THREAD

**Issue by nicholas-miles-brex** [facebook/prophet#2167]
`pystan` version: 2.19.1.1
`prophet` version: 1.0.0

I'm running a notebook that ran successfully previously but is suddenly throwing the following error: `'StanModel' object has no attribute 'fit_class'`. Most of the issue reports that I've found related to using a different pystan version than 2.19.1.1, how can I fix the issue if I'm already running that version?

**Comment by tcuongd** [comment]
Hmm without more context, I think uninstalling and reinstalling is your best bet. That error is usually seen when the stan model hasn't compiled properly.

**Comment by rogerbock** [comment]
I am also getting this error. I have `prophet==1.0`, `pystan==2.19.1.1`, and `gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)`.
I am seeing the issue in a freshly created Docker image, so I don't think uninstalling and reinstalling would help.

**Comment by rogerbock** [comment]
I figured out my issue - I was pulling a prebuilt Prophet wheel from my company-internal host. When I ran the below command to rebuild it from scratch, things worked as expected:
`RUN source /opt/rh/devtoolset-7/enable && pip install prophet --no-cache-dir --no-binary :all:`
