### ISSUE TITLE
Feature Request: Expose Potential Changepoint 80% Threshold?

### ISSUE THREAD

**Issue by saefsky** [facebook/prophet#217]
I think it would make sense to expose a class variable to allow the user to change the 80% threshold for potential automatic changepoints. For long time series, the 20% runway may be longer than is necessary. 

Thanks,
Scott

**Comment by bletham** [comment]
This is a reasonable thing to expose. In the meanwhile, you can always generate the list of potential changepoints manually and pass them in with the `changepoints` argument.

**Comment by bletham** [comment]
If anyone would like to make a PR for this, it involves adding a new argument to `Prophet()` and then using it in the place of `.8` inside `set_changepoints`.

**Comment by bletham** [comment]
https://github.com/facebook/prophet/commit/ba1bac834e864ccf736397194847b3ac95cff8cf and https://github.com/facebook/prophet/commit/cb0b47994b1d2d6612f75eff4b9d4bec6f5ad846 add this feature.

**Comment by bletham** [comment]
This is now an input argument in v0.3, as described in the documentation here: https://facebook.github.io/prophet/docs/trend_changepoints.html
