### ISSUE TITLE
Can't install on python 3.10 - is python 3.10 supported?

### ISSUE THREAD

**Issue by andrew-at-alloy** [facebook/prophet#2170]
System: macOS Big Sur 11.6.5
Python version: 3.10.2

Does prophet support python 3.10? The official installation instructions say to install pystan 2.19.1.1, but pystan2 is [not maintained](https://github.com/stan-dev/pystan2#pystan-the-python-interface-to-stan) and I get compiler errors when trying to install it.

I follow the official [installation instructions](https://github.com/facebook/prophet#installation-in-python---pypi-release):
```
# Install pystan with pip before using pip to install prophet
# pystan>=3.0 is currently not supported
pip install pystan==2.19.1.1
pip install prophet
```

In a clean virtual environment, pystan 2.19.1.1 appears not to be able to install. It begins with:
```
❯ pip install pystan==2.19.1.1
Collecting pystan==2.19.1.1
  Using cached pystan-2.19.1.1.tar.gz (16.2 MB)
Requirement already satisfied: Cython!=0.25.1,>=0.22 in ./v3venv20220510/lib/python3.10/site-packages (from pystan==2.19.1.1) (0.29.28)
Requirement already satisfied: numpy>=1.7 in ./v3venv20220510/lib/python3.10/site-packages (from pystan==2.19.1.1) (1.22.3)
Building wheels for collected packages: pystan
  Building wheel for pystan (setup.py) ... -
```

This eventually results in a bunch of compilation errors:
```
INFO: compile options: '-DBOOST_DISABLE_ASSERTS -DBOOST_NO_DECLTYPE -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -DBOOST_RESULT_OF_USE_TR1 -DFUSION_MAX_VECTOR_SIZE=12 -Ipystan/stan/src -Ipystan/stan/lib/stan_math/ -Ipystan/stan/lib/stan_math/lib/eigen_3.3.3 -Ipystan/stan/lib/stan_math/lib/boost_1.69.0 -Ipystan/stan/lib/stan_math/lib/sundials_4.1.0/include -I/Users/andrew/v3venv20220510/include -I/Users/andrew/.pyenv/versions/3.10.2/include/python3.10 -c'
  extra options: '-Os -ftemplate-depth-256 -Wno-unused-function -Wno-uninitialized -std=c++1y'
  INFO: clang: pystan/_chains.cpp
  In file included from pystan/_chains.cpp:760:
  In file included from pystan/stan/lib/stan_math/stan/math/prim/mat/fun/autocovariance.hpp:4:
  In file included from pystan/stan/lib/stan_math/stan/math/prim/mat/fun/Eigen.hpp:4:
  In file included from pystan/stan/lib/stan_math/lib/eigen_3.3.3/Eigen/Dense:1:
  In file included from pystan/stan/lib/stan_math/lib/eigen_3.3.3/Eigen/Core:420:
  pystan/stan/lib/stan_math/lib/eigen_3.3.3/Eigen/src/Core/AssignEvaluator.h:86:63: warning: converting the enum constant to a boolean [-Wint-in-bool-context]
      MayLinearVectorize = bool(MightVectorize) && MayLinearize && DstHasDirectAccess
                                                                ^
  pystan/stan/lib/stan_math/lib/eigen_3.3.3/Eigen/src/Core/AssignEvaluator.h:607:20: note: in instantiation of template class 'Eigen::internal::copy_using_evaluator_traits<Eigen::internal::evaluator<Eigen::Matrix<double, -1, 1, 0>>, Eigen::internal::evaluator<Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, 1, 0>>>, Eigen::internal::assign_op<double, double>>' requested here
    typedef typename AssignmentTraits::PacketType PacketType;
                     ^
  pystan/stan/lib/stan_math/lib/eigen_3.3.3/Eigen/src/Core/AssignEvaluator.h:739:10: note: in instantiation of template class 'Eigen::internal::generic_dense_assignment_kernel<Eigen::internal::evaluator<Eigen::Matrix<double, -1, 1, 0>>, Eigen::internal::evaluator<Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, 1, 0>>>, Eigen::internal::assign_op<double, double>, 0>' requested here
    Kernel kernel(dstEvaluator, srcEvaluator, func, dst.const_cast_derived());
```

**Comment by antebandov** [comment]
+1

**Comment by Cedric-Garcia** [comment]
The version of prophet on pip uses a version of pystan that is no longer supported for python 3.10. I had success installing it straight from the git repository (development version, but seems to work fine) as it uses another backend. 

Instructions from the documentation:

```
git clone https://github.com/facebook/prophet.git
cd prophet/python
python -m install -r requirements.txt
python setup.py develop
```

**Comment by andrew-at-alloy** [comment]
@Cedric-Garcia - did you test actually running prophet after installing that way? I tried the same thing when initially debugging (ie cloning the current master branch from the prophet repo). It installed correctly, but when I tried running `Prophet()` in python I got an error along the lines of "pystan backend not found". Replicate (from the [official docs](https://facebook.github.io/prophet/docs/quick_start.html)) with:

```
import pandas as pd
from prophet import Prophet
df = pd.read_csv('../examples/example_wp_log_peyton_manning.csv')
m = Prophet()
m.fit(df)
```

**Comment by Cedric-Garcia** [comment]
I wonder if you have a broken install from trying to install it from pip? Try uninstalling that first?

I've been using Prophet for the last couple of days on Python 3.10 and it's working great. It should not be trying to use pystan but another backend which is why I think you may have a different version installed.

**Comment by andrew-at-alloy** [comment]
Confirmed that this works (tested with fresh virtual environment in python 3.10.2)! [Here](https://github.com/facebook/prophet#installation-in-python---development-version) is the link to the instructions that @Cedric-Garcia [posted](https://github.com/facebook/prophet/issues/2170#issuecomment-1129332272) (noting the typo with missing `pip` in `python -m pip install -r requirements.txt`)

Closing the issue
