### ISSUE TITLE
Build wheels for newer python  versions

### ISSUE THREAD

**Issue by jlopezpena** [facebook/prophet#2181]
https://github.com/facebook/prophet/blob/cc8c69a3ba148c5559596125c04f801f7238b651/.github/workflows/wheel.yml#L91

Shouldn't this line (and the corresponding one for the windows build) be updated so that the github action builds wheels for python 3.9 and 3.10 as well?

**Comment by tcuongd** [comment]
With this release: https://github.com/facebook/prophet/releases/tag/v1.1 we now have wheels for 3.7-3.10 on PyPI (https://pypi.org/project/prophet/).
