### ISSUE TITLE
no such file C:\Users\w00612942\Anaconda3\Lib\site-packages\prophet\stan_model\prophet_model.bin

### ISSUE THREAD

**Issue by WZFish** [facebook/prophet#2184]
When I use prophet to forcast, I new a prophet object by 

model=prophet.Prophet()
model.fit(train_df)

and There are error AttributeError: 'Prophet' object has no attribute 'stan_backend'
And the I see the issue that should change it to:

model=prophet.Prophet(stan_backend='CMDSTANPY')
model.fit(train_df)

but it have the problem :
no such file C:\Users\w00612942\Anaconda3\Lib\site-packages\prophet\stan_model\prophet_model.bin

How can I use it? Thank you!

**Comment by WardBrian** [comment]
How did you install prophet?

**Comment by akosfurton** [comment]
This has been resolved in prophet 1.1. You can now `pip install prophet` directly from PyPI
