### ISSUE TITLE
Milestone cleanup and 1.1 release schedule

### ISSUE THREAD

**Issue by abitrolly** [facebook/prophet#2191]
I've noticed that milestones were never completed https://github.com/facebook/prophet/milestones and that among them there no 1.x releases. It would be nice to get an idea when to expect wheel to be available (#664).

**Comment by akosfurton** [comment]
@abitrolly , 1.1 has been released on PyPI. You can now install Prophet with `pip install prophet`

**Comment by abitrolly** [comment]
@akosfurton thanks for the notice. I guess the main issue is fixed (1.1 is released), so milestone clean up can wait until the need to trace the next release emerges.
