### ISSUE TITLE
Build Apple M1 wheels

### ISSUE THREAD

**Issue by ShantanuKumar** [facebook/prophet#2209]
Currently there are no M1 wheels for prophet on pypi.
We have locally built it and can upload it, if that's something which might help other people.

**Comment by nlhkh** [comment]
> Currently there are no M1 wheels for prophet on pypi. We have locally built it and can upload it, if that's something which might help other people.

That would be very helpful.

**Comment by WardBrian** [comment]
Done in 1.1.5
