### ISSUE TITLE
Installation from source fails on docker container on M1 mac

### ISSUE THREAD

**Issue by jlopezpena** [facebook/prophet#2216]
Trying to build `prophet` inside a docker container running on an M1 mac (linux on arm64).
The installation script fails due to an error on the `install_cmdstan` command called from `install_cmdstan_dependencies` called from `build_cmdstan_model` (line 106 in the `setup.py` file).

I have traced this down to an issue in `install_cmdstan`: when the `overwrite` flag is set to true, the installation fails unless the folder already exists. I can reproduce this invoking `install_cmdstan` directly from the command line (using latest `cmdstanpy 1.0.3`).

Possible solutions would be to fix this on `cmdstanpy`, or to set the `overwrite` flag in the `setup` file to false (this model is written to a random temp folder anyway so it is definitely not going to have a previous `cmdstan` installation there).

For some reason I am only seeing this in the docker container inside a mac, in our production environment/CI it seems to work, but in our devcontainers is failing. @WardBrian do you have any idea on what might be the issue?

**Comment by WardBrian** [comment]
What happens if you pin cmdstanpy to 1.0.1? We had a bug reported earlier today:
https://github.com/stan-dev/cmdstanpy/issues/585

**Comment by WardBrian** [comment]
The part of your error that prints 

> Installed cmdstan-2.26.1

Implies to me that the error is occuring after the actual installation, which seems odd.

If you want an immediate workaround, if running `install_cmdstan` on your own works you can then set the environment variable `PROPHET_REPACKAGE_CMDSTAN` to `false` and setup.py should skip this.

**Comment by WardBrian** [comment]
Setting the build version to the branch from https://github.com/stan-dev/cmdstanpy/pull/586 also fixes, so cmdstanpy 1.0.4 will when it is released
