### ISSUE TITLE
Why is Cython included?

### ISSUE THREAD

**Issue by lucidfrontier45** [facebook/prophet#2232]
I found Cython is still included in the install dependencies. 
https://github.com/facebook/prophet/blob/95b1741d447c7283363475a63f1ceceaec2981c9/python/requirements.txt#L1

My understanding is that it is required for pystan2. As of Prophet 1.1 the backend is completely moved to cmdstanpy. Why is Cython still required?

**Comment by WardBrian** [comment]
I believe this was an oversight in #2148 and it should be removed

**Comment by WardBrian** [comment]
@tcuongd want to knock this one off as well? I think it’s causing some annoyances for the conda package. 

Also worth considering updating the “fbprophet” shim to not pin 1.0 any more
