### ISSUE TITLE
AttributeError: 'StanModel' object has no attribute 'fit_class'

### ISSUE THREAD

**Issue by tanercam** [facebook/prophet#2240]
AttributeError: 'StanModel' object has no attribute 'fit_class'

installing pystan's earlier version or installing wit no cache pystan and fbprophet are not working.

Has anyone a solution to fit model by using fbprophet?

Thanks in advance.

**Comment by Nil-Andreu** [comment]
Which are the versions that you are using of the packages?

```python
import pystan
import stan
print(pystan.__version__)
print(stan.__version__)
```

**Comment by tanercam** [comment]
Thank you for your message. I think you saw my message recently. I had sent
it a few months ago. I solved the problem by using prophet library instead
of fbprophet library. I had used fbprophet library without any problem in
the past; therefore I had asked you.

Best,
Taner

**Comment by Nil-Andreu** [comment]
Okay perfect then Taner!

Best,
Nil

**Comment by WardBrian** [comment]
Closing due to PyStan no longer being a dependency of `prophet`
