### ISSUE TITLE
How to retrain a fitted saved model in neural prophet with new additional datapoints? I read the documentation but nothing is there

### ISSUE THREAD

**Issue by Msaleh87** [facebook/prophet#2251]
I know how to do this in fbProphet, you get the parameters from the old model and update them using the new data points, instead of retraining the whole model from scratch. How to do the same with Neural Prophet? I tried the same function but it didn't work out.

**Comment by tcuongd** [comment]
This is the wrong repo, see https://github.com/ourownstory/neural_prophet
