### ISSUE TITLE
Installation of package not happening in mac

### ISSUE THREAD

**Issue by anuragreddygv323** [facebook/prophet#2264]
python3 -m pip install prophet==1.0.1
Defaulting to user installation because normal site-packages is not writeable
Collecting prophet==1.0.1
  Using cached prophet-1.0.1.tar.gz (65 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: Cython>=0.22 in ./Library/Python/3.6/lib/python/site-packages (from prophet==1.0.1) (0.29.30)
Requirement already satisfied: cmdstanpy==0.9.68 in ./Library/Python/3.6/lib/python/site-packages (from prophet==1.0.1) (0.9.68)
Requirement already satisfied: pystan~=2.19.1.1 in ./Library/Python/3.6/lib/python/site-packages (from prophet==1.0.1) (2.19.1.1)
Requirement already satisfied: numpy>=1.15.4 in ./Library/Python/3.6/lib/python/site-packages (from prophet==1.0.1) (1.19.5)
Requirement already satisfied: pandas>=1.0.4 in ./Library/Python/3.6/lib/python/site-packages (from prophet==1.0.1) (1.1.5)
Requirement already satisfied: matplotlib>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from prophet==1.0.1) (3.3.4)
Requirement already satisfied: LunarCalendar>=0.0.9 in ./Library/Python/3.6/lib/python/site-packages (from prophet==1.0.1) (0.0.9)
Requirement already satisfied: convertdate>=2.1.2 in ./Library/Python/3.6/lib/python/site-packages (from prophet==1.0.1) (2.3.2)
Requirement already satisfied: holidays>=0.10.2 in ./Library/Python/3.6/lib/python/site-packages (from prophet==1.0.1) (0.13)
Requirement already satisfied: setuptools-git>=1.2 in ./Library/Python/3.6/lib/python/site-packages (from prophet==1.0.1) (1.2)
Requirement already satisfied: python-dateutil>=2.8.0 in ./Library/Python/3.6/lib/python/site-packages (from prophet==1.0.1) (2.8.1)
Requirement already satisfied: tqdm>=4.36.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from prophet==1.0.1) (4.62.0)
Requirement already satisfied: ujson in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from cmdstanpy==0.9.68->prophet==1.0.1) (1.35)
Requirement already satisfied: pymeeus<=1,>=0.3.13 in ./Library/Python/3.6/lib/python/site-packages (from convertdate>=2.1.2->prophet==1.0.1) (0.5.11)
Requirement already satisfied: pytz>=2014.10 in ./Library/Python/3.6/lib/python/site-packages (from convertdate>=2.1.2->prophet==1.0.1) (2020.4)
Requirement already satisfied: hijri-converter in ./Library/Python/3.6/lib/python/site-packages (from holidays>=0.10.2->prophet==1.0.1) (2.2.4)
Requirement already satisfied: korean-lunar-calendar in ./Library/Python/3.6/lib/python/site-packages (from holidays>=0.10.2->prophet==1.0.1) (0.2.1)
Requirement already satisfied: ephem>=3.7.5.3 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from LunarCalendar>=0.0.9->prophet==1.0.1) (4.1.3)
Requirement already satisfied: pillow>=6.2.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from matplotlib>=2.0.0->prophet==1.0.1) (8.3.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from matplotlib>=2.0.0->prophet==1.0.1) (2.3.1)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from matplotlib>=2.0.0->prophet==1.0.1) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from matplotlib>=2.0.0->prophet==1.0.1) (1.0.1)
Requirement already satisfied: six>=1.5 in ./Library/Python/3.6/lib/python/site-packages (from python-dateutil>=2.8.0->prophet==1.0.1) (1.15.0)
Requirement already satisfied: setuptools in ./Library/Python/3.6/lib/python/site-packages (from kiwisolver>=1.0.1->matplotlib>=2.0.0->prophet==1.0.1) (59.6.0)
Building wheels for collected packages: prophet
  Building wheel for prophet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/l4/_ptjhj0j3h344l823z2ql6nrcj_v_6/T/pip-install-23wn44r9/prophet_d9b6b7bf46c440a49db553ce3fd32fa6/setup.py'"'"'; __file__='"'"'/private/var/folders/l4/_ptjhj0j3h344l823z2ql6nrcj_v_6/T/pip-install-23wn44r9/prophet_d9b6b7bf46c440a49db553ce3fd32fa6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/l4/_ptjhj0j3h344l823z2ql6nrcj_v_6/T/pip-wheel-_iett6ar
       cwd: /private/var/folders/l4/_ptjhj0j3h344l823z2ql6nrcj_v_6/T/pip-install-23wn44r9/prophet_d9b6b7bf46c440a49db553ce3fd32fa6/
  Complete output (10 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/prophet
  creating build/lib/prophet/stan_model
  Importing plotly failed. Interactive plots will not work.
  INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_dfdaf2b8ece8a02eb11f050ec701c0ec NOW.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for prophet
  Running setup.py clean for prophet
Failed to build prophet
Installing collected packages: prophet
    Running setup.py install for prophet ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/l4/_ptjhj0j3h344l823z2ql6nrcj_v_6/T/pip-install-23wn44r9/prophet_d9b6b7bf46c440a49db553ce3fd32fa6/setup.py'"'"'; __file__='"'"'/private/var/folders/l4/_ptjhj0j3h344l823z2ql6nrcj_v_6/T/pip-install-23wn44r9/prophet_d9b6b7bf46c440a49db553ce3fd32fa6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/l4/_ptjhj0j3h344l823z2ql6nrcj_v_6/T/pip-record-rdt3huq7/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/y971521/Library/Python/3.6/include/python3.6m/prophet
         cwd: /private/var/folders/l4/_ptjhj0j3h344l823z2ql6nrcj_v_6/T/pip-install-23wn44r9/prophet_d9b6b7bf46c440a49db553ce3fd32fa6/
    Complete output (12 lines):
    running install
    /Users/y971521/Library/Python/3.6/lib/python/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/prophet
    creating build/lib/prophet/stan_model
    Importing plotly failed. Interactive plots will not work.
    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_dfdaf2b8ece8a02eb11f050ec701c0ec NOW.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/l4/_ptjhj0j3h344l823z2ql6nrcj_v_6/T/pip-install-23wn44r9/prophet_d9b6b7bf46c440a49db553ce3fd32fa6/setup.py'"'"'; __file__='"'"'/private/var/folders/l4/_ptjhj0j3h344l823z2ql6nrcj_v_6/T/pip-install-23wn44r9/prophet_d9b6b7bf46c440a49db553ce3fd32fa6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/l4/_ptjhj0j3h344l823z2ql6nrcj_v_6/T/pip-record-rdt3huq7/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/y971521/Library/Python/3.6/include/python3.6m/prophet Check the logs for full command output.

**Comment by anuragreddygv323** [comment]
Mac OS Catalina version 10.15.7
Python 3.6.5

**Comment by anuragreddygv323** [comment]
can u guys help please....

**Comment by ShantanuKumar** [comment]
Try 1.1 version
