### ISSUE TITLE
`Prophet().fit()` method only works with date and not datetime?

### ISSUE THREAD

**Issue by bhattbhuwan13** [facebook/prophet#2274]
I am working on a project where the time axis is a timestamp. Two data points differ by a 5 minute interval.

|index|df|y|
|---|---|---|
|0|2022-01-01 00:00:00+00:00|5\.93|
|1|2022-01-01 00:05:00+00:00|5\.93|
|2|2022-01-01 00:10:00+00:00|5\.92|
|3|2022-01-01 00:15:00+00:00|5\.93|
|4|2022-01-01 00:20:00+00:00|5\.92|

When I run the prophet model, I get the following error:
```python
m = Prophet()
m.fit(train_df)
```

`ValueError: Dataframe must have columns "ds" and "y" with the dates and values respectively.`

**Comment by WeepingClown13** [comment]
The shown error is because your dataframe has a column df instead of ds

**Comment by bhattbhuwan13** [comment]
@WeepingClown13, Thank you. I made a silly mistake. Closing the issue.
