### ISSUE TITLE
Python version independent wheel

### ISSUE THREAD

**Issue by lucidfrontier45** [facebook/prophet#2289]
The current Prophet wheel is Python version specific. However CmdStanPy is Python version independent as it use stanc to compile the model as an executable binary and obtain the result from output file. Therefore we can also make Prophet wheel Python version independent. The merit is that we don't need to create binary included wheel for each Python version and we can immediately use Prophet even right after a release of new Python version without recompilation.

Is it possible to create a platform specific but Python version independent wheel?

----

By the way, in my forked https://github.com/lucidfrontier45/prophet-nogpl, I made Prophet download precompiled model file and runtime files on github release pages. By doing so we can also make wheel file platform independent. (But we need to put model and runtime files in the release page for each platform)

**Comment by tcuongd** [comment]
Thanks for your suggestion! Wheels are version agnostic as of 1.12
