### ISSUE TITLE
python setup.py egg_info did not run successfully.   exit code: 1

### ISSUE THREAD

**Issue by garyyliu** [facebook/prophet#2292]
Hi, everyone

I am very new to python and I want to install a pygame after I installed python on my computer. However, I have come across the above issue and I have searched numerous posts on internet on how to solve this, including everything to do with setup_tools, pip, ez_settings, etc, I have also tried pip3 instead of pip, however, none of those worked. I always get the same error.

Could anyone please help? I saw there was a previous thread on this but reading and trying everything suggested there didn't really help. As you can see, I am using all the most up to date version for all the modules required.

Please help!!!

>>>pip3 install --no-cache-dir pygame
Collecting pygame
  Downloading pygame-2.1.2.tar.gz (10.1 MB)
     ---------------------------------------- 10.1/10.1 MB 1.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [77 lines of output]

      WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
      Using WINDOWS configuration...

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\liuey\AppData\Local\Temp\pip-install-mgdoy35w\pygame_5f4a1501a54349bf8a36efa18e48b561\setup.py", line 359, in <module>
          buildconfig.config.main(AUTO_CONFIG)
        File "C:\Users\liuey\AppData\Local\Temp\pip-install-mgdoy35w\pygame_5f4a1501a54349bf8a36efa18e48b561\buildconfig\config.py", line 225, in main
          deps = CFG.main(**kwds)
                 ^^^^^^^^^^^^^^^^
        File "C:\Users\liuey\AppData\Local\Temp\pip-install-mgdoy35w\pygame_5f4a1501a54349bf8a36efa18e48b561\buildconfig\config_win.py", line 511, in main
          return setup_prebuilt_sdl2(prebuilt_dir)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\liuey\AppData\Local\Temp\pip-install-mgdoy35w\pygame_5f4a1501a54349bf8a36efa18e48b561\buildconfig\config_win.py", line 471, in setup_prebuilt_sdl2
          DEPS.configure()
        File "C:\Users\liuey\AppData\Local\Temp\pip-install-mgdoy35w\pygame_5f4a1501a54349bf8a36efa18e48b561\buildconfig\config_win.py", line 336, in configure
          from . import vstools
        File "C:\Users\liuey\AppData\Local\Temp\pip-install-mgdoy35w\pygame_5f4a1501a54349bf8a36efa18e48b561\buildconfig\vstools.py", line 11, in <module>
          compiler.initialize()
        File "C:\Program Files\Python311\Lib\site-packages\setuptools\_distutils\msvc9compiler.py", line 403, in initialize
          vc_env = query_vcvarsall(VERSION, plat_spec)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\Python311\Lib\site-packages\setuptools\_distutils\msvc9compiler.py", line 281, in query_vcvarsall
          raise DistutilsPlatformError("Unable to find vcvarsall.bat")
      distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
      Making dir :prebuilt_downloads:
      Downloading... https://www.libsdl.org/release/SDL2-devel-2.0.18-VC.zip ed561079ec622b0bab5a9e02976f5d540b0622da
      Unzipping :prebuilt_downloads\SDL2-devel-2.0.18-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-VC.zip 137f86474691f4e12e76e07d58d5920c8d844d5b
      Unzipping :prebuilt_downloads\SDL2_image-devel-2.0.5-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.15-VC.zip 1436df41ebc47ac36e02ec9bda5699e80ff9bd27
      Unzipping :prebuilt_downloads\SDL2_ttf-devel-2.0.15-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.4-VC.zip 9097148f4529cf19f805ccd007618dec280f0ecc
      Unzipping :prebuilt_downloads\SDL2_mixer-devel-2.0.4-VC.zip:
      Downloading... https://www.pygame.org/ftp/jpegsr9d.zip ed10aa2b5a0fcfe74f8a6f7611aeb346b06a1f99
      Unzipping :prebuilt_downloads\jpegsr9d.zip:
      Downloading... https://pygame.org/ftp/prebuilt-x64-pygame-1.9.2-20150922.zip 3a5af3427b3aa13a0aaf5c4cb08daaed341613ed
      Unzipping :prebuilt_downloads\prebuilt-x64-pygame-1.9.2-20150922.zip:
      copying into .\prebuilt-x64
      Path for SDL: prebuilt-x64\SDL2-2.0.18
      ...Library directory for SDL: prebuilt-x64/SDL2-2.0.18/lib/x64
      ...Include directory for SDL: prebuilt-x64/SDL2-2.0.18/include
      Path for FONT: prebuilt-x64\SDL2_ttf-2.0.15
      ...Library directory for FONT: prebuilt-x64/SDL2_ttf-2.0.15/lib/x64
      ...Include directory for FONT: prebuilt-x64/SDL2_ttf-2.0.15/include
      Path for IMAGE: prebuilt-x64\SDL2_image-2.0.5
      ...Library directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/lib/x64
      ...Include directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/include
      Path for MIXER: prebuilt-x64\SDL2_mixer-2.0.4
      ...Library directory for MIXER: prebuilt-x64/SDL2_mixer-2.0.4/lib/x64
      ...Include directory for MIXER: prebuilt-x64/SDL2_mixer-2.0.4/include
      Path for PORTMIDI: prebuilt-x64
      ...Library directory for PORTMIDI: prebuilt-x64/lib
      ...Include directory for PORTMIDI: prebuilt-x64/include
      DLL for SDL2: prebuilt-x64/SDL2-2.0.18/lib/x64/SDL2.dll
      DLL for SDL2_ttf: prebuilt-x64/SDL2_ttf-2.0.15/lib/x64/SDL2_ttf.dll
      DLL for SDL2_image: prebuilt-x64/SDL2_image-2.0.5/lib/x64/SDL2_image.dll
      DLL for SDL2_mixer: prebuilt-x64/SDL2_mixer-2.0.4/lib/x64/SDL2_mixer.dll
      DLL for portmidi: prebuilt-x64/lib/portmidi.dll
      Path for FREETYPE not found.
      ...Found include dir but no library dir in prebuilt-x64.
      Path for PNG not found.
      ...Found include dir but no library dir in prebuilt-x64.
      Path for JPEG not found.
      ...Found include dir but no library dir in prebuilt-x64.
      DLL for freetype: prebuilt-x64/SDL2_ttf-2.0.15/lib/x64/libfreetype-6.dll

      ---
      For help with compilation see:
          https://www.pygame.org/wiki/CompileWindows
      To contribute to pygame development see:
          https://www.pygame.org/contribute.html
      ---

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by accddd** [comment]
pip install pygame --pre

**Comment by scheniezel** [comment]
> pip install pygame --pre

ty so much sir <3 i've been trying to install pygame for 2 hours.

**Comment by ereptile-dysfunction** [comment]
> pip install pygame --pre

@accddd - You saved me hours. Thank you sir.

**Comment by ihsan-cu** [comment]
I'm having the same error while installing pcapy >> pip install pcapy, any recommendation for this?

**Comment by chharshavardhini** [comment]
TQ for giving this solution its been working.

**Comment by elharrak58** [comment]
thank you so much

**Comment by FahimOpenSource** [comment]
Can anyone please explain?

**Comment by tcuongd** [comment]
This is a pygame issue, please post here: https://github.com/pygame/pygame/issues

**Comment by RoseminSajiT** [comment]
> 

Thank you ;)

**Comment by rizwanuh09** [comment]
i have same issue for osmread. does anyone know the solution for that

**Comment by kodoman1234** [comment]
> pip install pygame --pre

thanks sir it worked

**Comment by rnezamivcc** [comment]
python -m pip install -U pygame==2.3.0 --user

**Comment by peace-for-all** [comment]
> Can anyone please explain?

`--pre` param allows installation of pre-releases, which can contain fixes, for example.
If you're interested, here's the [description of this param](https://pip.pypa.io/en/stable/cli/pip_install/#pre-release-versions).

**Comment by coolkarni987** [comment]
![Screenshot 2024-09-06 224213](https://github.com/user-attachments/assets/69c067bd-4c99-4d38-acb0-4f3f66513545)
what this error guy could u help me
