### ISSUE TITLE
I am getting error when i am creating Choropleth Maps!!!

### ISSUE THREAD

**Issue by s1a2u3r** [facebook/prophet#2294]
Here is my code:

data = dict(type = 'choropleth',
            locations =df ['Country'],
            colorscale= 'Portland',
            text= df['Text'],
            z=df['Power Consumption KWH'],
            colorbar = {'title':'2014_World_Power_Consumption'})

layout = dict(
    title = '2014_World_Power_Consumption',
    geo = dict(
        showframe = False,
        projection = {'type':'Mercator'}
    )
)

choromap = go.Figure(data = [data],layout = layout)
iplot(choromap,validate=False)

I am getting error after this.

This is what i have imported:

import plotly.graph_objs as go 
from plotly.offline import init_notebook_mode,iplot
init_notebook_mode(connected=True) 

import plotly.graph_objs as go 
from plotly.offline import init_notebook_mode,iplot
init_notebook_mode(connected=True) 
import pandas as pd

**Comment by tcuongd** [comment]
Please post this in Plotly's discussion board.
