### ISSUE TITLE
prophet add_seasonality() how to set period for minutely and hourly seasonality when we have data at minute level interval?

### ISSUE THREAD

**Issue by nivedangowda** [facebook/prophet#2303]
I am trying to add seasonality at 10 minutes interval and another at hourly interval and my data is at minute level aggregated.

What would be the period parameter considering the fact that period is "float number of days in one period".

**Comment by donggu-kang** [comment]
future = m.make_future_dataframe(periods="periods", freq="freq")

**future = m.make_future_dataframe(periods="144", freq="10min")**

**And check this**
https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases
