### ISSUE TITLE
Specify two months of the year (like Nov and Dec) as yearly seasonality

### ISSUE THREAD

**Issue by elaheshosseini** [facebook/prophet#2310]
Hi, I'm modeling the dynamics of the e-commerce data traffic of a huge online store. During November and December, we have huge spikes on sale data traffic. How can I define this seasonality in Prophet? Specifying yearly seasonality as having huge traffic on these two months of the year (every year).

**Comment by donggu-kang** [comment]
Does only November and December training data exist?
If so, your results may be inaccurate unless you are forecasting between November and December of next year.

As a rule of thumb, for this model to produce good results, not only the quantity of data is important, but also the actual duration of the data is important.

For example, if you want to see the weekly pattern for the next week, you need data with a period of at least 3 to 4 weeks, and if you want to predict the next month, you need more than 3 months.

Of course, it is possible to make predictions with less data without doing so.
However, in actual verification, a phenomenon in which the performance deteriorated was found.

Please note that it may be interpreted differently depending on the characteristics of the data, seasonality, etc.

**Comment by donggu-kang** [comment]
**for better results**
Please disclose the results of the experiments you have conducted so far and the parameter values you have set.


Smart people will answer here.
If the answer is resolved, please close the issue without deleting it.

**Comment by elaheshosseini** [comment]
Thank you @donggu-kang for your response. 

Do you recommend to use Prophet without any changes to parameter settings despite there are different sale's event and seasonalities in our data dynamics? 

Currently, I have three months data from September till now, regular data in Sep and Oct and also huge traffic in Nov and we will have huge traffic on Dec as well.  

The error rate of my prophet model is high (MAPE = 0.8175) and I wanted to increase the accuracy by adding sale's events and seasonality. 
Do you have any recommendation for me to increase my model accuracy?
