### ISSUE TITLE
plot error :  TypeError: ufunc 'isfinite' not supported for the input types

### ISSUE THREAD

**Issue by tanxiao1990** [facebook/prophet#2323]
errors when plot,  errors info :

TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

code :
![image](https://user-images.githubusercontent.com/38320121/209080589-2b6ba0e7-0794-41ac-8e13-2295a151145d.png)

data:
![image](https://user-images.githubusercontent.com/38320121/209080626-0830fcc7-a9a5-4a13-a252-a5dec1db7f5a.png)

version:
Name: prophet
Version: 1.1.1 
Name: matplotlib
Version: 3.6.2
Name: pandas
Version: 1.5.2

**Comment by soch2022** [comment]
i am also facing the same issue

**Comment by twolodzko** [comment]
Same here. Reproducible example that can be added to `TestProphet` class:

```python
    def test_make_forecast_plot(self):
        N = 468
        train = DATA.head(N // 2)
        forecaster = Prophet()
        forecaster.fit(train)
        future = forecaster.make_future_dataframe(periods=3, freq='D',
                                                  include_history=False)
        forecast = forecaster.predict(future)
        forecaster.plot(forecast)  # fails
```

**Comment by andriati-alex** [comment]
Also notice the same problem here

**Comment by kazuoteramoto** [comment]
One solution is to explicit pass the numpy array of  values instead of the Series

```
diff --git i/python/prophet/plot.py w/python/prophet/plot.py
index c531729..171bc95 100644
--- i/python/prophet/plot.py
+++ w/python/prophet/plot.py
@@ -77,7 +77,7 @@ def plot(
     if m.logistic_floor and 'floor' in fcst and plot_cap:
         ax.plot(fcst_t, fcst['floor'], ls='--', c='k', label='Minimum capacity')
     if uncertainty and m.uncertainty_samples:
-        ax.fill_between(fcst_t, fcst['yhat_lower'], fcst['yhat_upper'],
+        ax.fill_between(fcst_t, fcst['yhat_lower'].values, fcst['yhat_upper'].values,
                         color='#0072B2', alpha=0.2, label='Uncertainty interval')
     # Specify formatting to workaround matplotlib issue #12925
     locator = AutoDateLocator(interval_multiples=False)
```

This solves the problem for me, but I did not found what changed on numpy/prophet to make this necessary.

**Comment by tcuongd** [comment]
Hmm weird, I can't reproduce this (even with @twolodzko 's code). I've upgraded all the relevant packages to the latest versions (pandas 1.5.2, matplotlib 3.6.2, numpy 1.24.1), and the plots work for me.

**Comment by tanxiao1990** [comment]
Confirmed, after upgrading numpy from 1.24.0 to 1.24.1, the problem is solved
