### ISSUE TITLE
Something went wrong while unpickling the StanModel. Consider recompiling.

### ISSUE THREAD

**Issue by zayyan6** [facebook/prophet#2327]
Ive been using this code for decomposition but its showing error for pystan:
model_prophet = Prophet(seasonality_mode='multiplicative')
Error coming out is:
WARNING:pystan:No module named 'stanfit4anon_model_dfdaf2b8ece8a02eb11f050ec701c0ec_4959769199373391054'
WARNING:pystan:Something went wrong while unpickling the StanModel. Consider recompiling.

**Comment by tcuongd** [comment]
Please upgrade to the latest prophet version, pystan is no longer used.
