### ISSUE TITLE
Prophet 1.0

### ISSUE THREAD

**Issue by Leep2023** [facebook/prophet#2331]
Hi, I use Prophet 1.0. And I got the following message:

C:\Miniconda3\lib\site-packages\prophet\forecaster.py:896: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

Do you know why ? Or is there a solution for that ? I wonder if I update to Prophet 1.1, will the problem be solved ?

Best Regards,
Lee

**Comment by Leep2023** [comment]
It looks there is an ongoing task: https://github.com/facebook/prophet/issues/2131

**Comment by Nil-Andreu** [comment]
I think is due to the pandas `append` method, that will be deprecated in the future.

So this method is basically to add in a given dataframe another dataframe. This can be done:

```python
# With append
df.append(df_other)

# With concat
pd.concat([df, df_other])
```

And basically the one that will be supported in the future is the second one.

**Comment by tcuongd** [comment]
Please upgrade to the latest prophet version, this warning has been addressed.

**Comment by Leep2023** [comment]
I followed the advice from tcuongd to upgrade to the latest version, it works fine now. Many thanks !
