### ISSUE TITLE
No pandas version compatible with fbprophet which requires numpy<1.20.0

### ISSUE THREAD

**Issue by LucieSauvajon** [facebook/prophet#2353]
Hello, I use fbprophet from one year and an error recently occured since fbprophet requires numpy<1.20.0 (since fbprophet uses np.int and np.float types). 

Indeed, I use also pandas  library and I can't find a version of pandas compatible with numpy<1.20.0. Do you know which version of pandas I could use and is an update of numpy planned for fbprophet ? 

Best regards

**Comment by tcuongd** [comment]
fbprophet is the old package name, please install `prophet` instead, `pip Install prophet`.
