### ISSUE TITLE
Guidance on best approach to test many model variables

### ISSUE THREAD

**Issue by pcpp94** [facebook/prophet#2377]
Hi,

I have many models running using Prophet. I have been trying to use some new regressors (Which are a product of two weather variables) to try and input some "non-linearities" within prophet linear regressors.

1. First question: In terms of trying different models with different regressors, what is the best approach? I'm currently using hyperopt to tune the hyperparameters but this is adding/subtracting variables (regressors).

2. Second question: Is there an easy way to do the same with different seasonality? - See if adding/subtracting some make sense (better MAPE).

Hopefully someone can help with this? I'd like to take it to a next level in terms of including/excluding different variables!

Thank you!

**Comment by cgobat** [comment]
I would think you'd have better luck asking a question like this on [StackOverflow](https://stackoverflow.com/), since this doesn't really qualify as an "issue" with Prophet itself.
