### ISSUE TITLE
Importing plotly failed. Interactive plots will not work

### ISSUE THREAD

**Issue by cs3888** [facebook/prophet#2387]
from prophet import Prophet
from prophet.plot import plot_plotly
plot_plotly(model, prediction)

Has anyone encountered these messages recently? 

"Importing plotly failed. Interactive plots will not work"
 
and
--> 595 data.append(go.Scatter(
    596     name='Actual',
    597     x=m.history['ds'],
    598     y=m.history['y'],
    599     marker=dict(color=actual_color, size=marker_size),
    600     mode='markers'
    601 ))
    602 # Add lower bound
    603 if uncertainty and m.uncertainty_samples:

NameError: name 'go' is not defined

**Comment by cs3888** [comment]
resolved by...
pip install plotly

**Comment by joarobles** [comment]
Since we don't need plotly to use prophet "headlessly", is there a way to disable that warning?

**Comment by sisidra** [comment]
Solution - disable `prophet.plot` logger before importing anything from prophet:
```python
logging.getLogger("prophet.plot").disabled = True
from prophet import ...
```

Using python code is not ideal, as linters will complain about importing stuff after statements.
If possible, configure in your config file.
I wish there was a better solution, as polluting logs with not helpful messages is not great for ops.
