### ISSUE TITLE
how to install on Mac?

### ISSUE THREAD

**Issue by ravi160822** [facebook/prophet#2420]
neither conda nor pip worked, Stan also giving error

**Comment by donggu-kang** [comment]
Hi. Please provide all or part of the error message you are experiencing.
It works normally on the latest stable version of macOS.

**Comment by ale-dg** [comment]
Hi,

I am having the same issue... this is the error when using python -m pip install prophet:

RuntimeError: CmdStan failed to install in repackaged directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for prophet
Failed to build prophet
ERROR: Could not build wheels for prophet, which is required to install pyproject.toml-based projects

If I try to install with Conda, this is the error:

PackagesNotFoundError: The following packages are not available from current channels:

  - prophet

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

I have installed both CmdStan and CmdStanPy, and the error persists though.

Thanks

Best,

**Comment by ravi160822** [comment]
yes same error Stan error
and conda also not working
when I attempt to other repo like darts it also fail, because it has prophet has dependency

**Comment by AlexandroLuis** [comment]
Did you all try to install from it's source?

`git clone https://github.com/facebook/prophet.git`
`cd prophet`
`pip install .`

it should work

**Comment by ravi160822** [comment]
I have attempted installing from source also, but I get the same CmdStan error

**Comment by ale-dg** [comment]
> Did you all try to install from it's source?
> 
> `git clone https://github.com/facebook/prophet.git` `cd prophet` `pip install .`
> 
> or
> 
> `pip install git+https://github.com/facebook/prophet.git`
> 
> it should work

Yes, I've tried and the same error happens. There is another threat in #2402 where a similar issue happens in Windows. I have added the macOS issues there as well.

Best

**Comment by AlexandroLuis** [comment]
> CmdStan

try to run `pip install cmdstanpy` and then install the prophet

**Comment by ale-dg** [comment]
I have tried it... the error still happens...

**Comment by rasswanth-cogoport** [comment]
I get the same error too. Is it to do with MacOS version or Python3 Version?

**Comment by k-hui** [comment]
I found that this can help

Once upon a time I stumbled with this issue. If you're using macOS go to Macintosh HD > Applications > Python3.x folder (or whatever version of python you're using) > double click on "Install Certificates.command" file.

https://stackoverflow.com/a/53310545

**Comment by ale-dg** [comment]
> I found that this can help
> 
> 
> 
> Once upon a time I stumbled with this issue. If you're using macOS go to Macintosh HD > Applications > Python3.x folder (or whatever version of python you're using) > double click on "Install Certificates.command" file.
> 
> 
> 
> https://stackoverflow.com/a/53310545
> 
> 

Isn't it for issues when pulling repos?! The issue with Prophet is that it doesn't build the wheel correctly, not that it can't be reached online

**Comment by iamjazzar** [comment]
From https://github.com/facebook/prophet/issues/2438#issuecomment-1563558671
> I had the same issue and it appears that the new version of MacOS (13.4) specifically fails to install CmdStan `2.26.1`. I created a fork ([iamjazzar/prophet](https://github.com/iamjazzar/prophet)) where I changed the CmdStan version to `2.32.0` and the installation works. The only catch here is that I'm using my own repo to install the package:
> 
> ```
> -e "git+https://github.com/iamjazzar/prophet.git@0591532#egg=prophet&subdirectory=python"
> ```
> 
> I'm not sure how that would affect the behavior, but I'm happy to open a PR if deems fit.

**Comment by dadwin** [comment]
this https://github.com/facebook/prophet/issues/2002#issuecomment-1732070180 may help you on Apple M1, without rosetta

**Comment by WardBrian** [comment]
We believe 1.1.5 has resolved this, `pip install prophet` will now use M1/M2 wheels
