### ISSUE TITLE
Error importing Prophet

### ISSUE THREAD

**Issue by samarkinv1** [facebook/prophet#2434]
Hi!

I am trying to import Prophet, but there is an error. I've already discovered that there is a problem with `holidays` library and as a solution from problem [#2432](https://github.com/facebook/prophet/issues/2432) I've tried to install specific version of `holidays`, but still it didn't worked out.

`pip uninstall prophet -y`
`pip uninstall holidays -y`
`!pip install holidays==0.24`
`!pip install prophet==1.1.2`

`from prophet import Prophet`

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-39-a5f73520e9d5> in <module>
----> 1 from prophet import Prophet

D:\Anaconda\lib\site-packages\prophet\__init__.py in <module>
      5 # LICENSE file in the root directory of this source tree. An additional grant
      6 # of patent rights can be found in the PATENTS file in the same directory.
----> 7 from prophet.forecaster import Prophet
      8 
      9 from pathlib import Path

D:\Anaconda\lib\site-packages\prophet\forecaster.py in <module>
     17 from numpy.typing import NDArray
     18 
---> 19 from prophet.make_holidays import get_holiday_names, make_holidays_df
     20 from prophet.models import StanBackendEnum
     21 from prophet.plot import (plot, plot_components)

D:\Anaconda\lib\site-packages\prophet\make_holidays.py in <module>
     12 import pandas as pd
     13 
---> 14 import prophet.hdays as hdays_part2
     15 import holidays as hdays_part1
     16 

D:\Anaconda\lib\site-packages\prophet\hdays.py in <module>
    777 
    778 
--> 779 class TU(Turkey):
    780     pass
    781 

D:\Anaconda\lib\site-packages\holidays\registry.py in __init__(self, path, *args, **kwargs)

TypeError: object.__init__() takes exactly one argument (the instance to initialize)

Any ideas, please?

**Comment by vstarlino** [comment]
Try to restart and clear and repeat.

**Comment by samarkinv1** [comment]
> Try to restart and clear and repeat.

It's all good, restart helped. Thank you so much sir!
