### ISSUE TITLE
PIP Prophet installation on m1 does not work

### ISSUE THREAD

**Issue by anton164** [facebook/prophet#2438]
It is still not possible to run `pip install prophet` on M1 without using conda. I understand this is an open source project and your time is limited, but it would be good to at the very least provide guidance on your installation page for m1 users. Better yet -- if you have bandwidth it would be great if the team would prioritize fixing this, especially given the focus in 2023 and beyond: 
https://medium.com/@cuongduong_35162/facebook-prophet-in-2023-and-beyond-c5086151c138

The team claims that it's seamless to install, but that's clearly not the case for many users (I assume many more will switch to M1 this year). Related issues:
- #2209 
- #2002 
- #2420 

Hope this doesn't come off as expecting too much, I just wanted to bring this to your attention!

Stack trace for Python 3.9:
```
> pip install prophet
<...shortened for brevit...>
          cmd_obj.run()
        File "/private/var/folders/z1/tk8nhdf94639kldpqnysbpvh0000gq/T/pip-build-env-xfkuwmr7/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/private/var/folders/z1/tk8nhdf94639kldpqnysbpvh0000gq/T/pip-build-env-xfkuwmr7/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/z1/tk8nhdf94639kldpqnysbpvh0000gq/T/pip-build-env-xfkuwmr7/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/private/var/folders/z1/tk8nhdf94639kldpqnysbpvh0000gq/T/pip-build-env-xfkuwmr7/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 144, in run
        File "<string>", line 131, in build_models
        File "<string>", line 110, in build_cmdstan_model
        File "<string>", line 94, in install_cmdstan_deps
      RuntimeError: CmdStan failed to install in repackaged directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for prophet
Failed to build prophet
ERROR: Could not build wheels for prophet, which is required to install pyproject.toml-based projects
```

**Comment by iamjazzar** [comment]
I had the same issue and it appears that the new version of MacOS (13.4) specifically fails to install CmdStan `2.26.1`. I created a fork ([iamjazzar/prophet](https://github.com/iamjazzar/prophet)) where I changed the CmdStan version to `2.32.0` and the installation works. The only catch here is that I'm using my own repo to install the package:

```
-e "git+https://github.com/iamjazzar/prophet.git@0591532#egg=prophet&subdirectory=python"
```

I'm not sure how that would affect the behavior, but I'm happy to open a PR if deems fit.

**Comment by Lezcool** [comment]
> I had the same issue and it appears that the new version of MacOS (13.4) specifically fails to install CmdStan `2.26.1`. I created a fork ([iamjazzar/prophet](https://github.com/iamjazzar/prophet)) where I changed the CmdStan version to `2.32.0` and the installation works. The only catch here is that I'm using my own repo to install the package:
> 
> ```
> -e "git+https://github.com/iamjazzar/prophet.git@0591532#egg=prophet&subdirectory=python"
> ```
> 
> I'm not sure how that would affect the behavior, but I'm happy to open a PR if deems fit.

I changed version to `2.32.0` on file `setup.py` and `model.py`, still failed to install.

**Comment by iamjazzar** [comment]
@Lezcool You also need to change the `TBB_DIRS` to `["tbb", "tbb_2020.3"]`.

**Comment by Augustab** [comment]
Hi, the issue got solved on my m1 mac after reading [this thread](https://discourse.mc-stan.org/t/problems-with-migration-from-intel-to-m1-mac/29911) and then running `softwareupdate --install-rosetta` in the mac terminal! Hope it helps👍

"Rosetta 2 is a translation layer used on Apple's M1 chips that allows them to run applications compiled for Intel x86_64 architecture. Apple's M1 chips are based on the ARM64 architecture, so applications that have not been recompiled for ARM64 might need Rosetta 2 to run."  @Lezcool

**Comment by dadwin** [comment]
this https://github.com/facebook/prophet/issues/2002#issuecomment-1732070180 may help you on Apple M1, without rosetta

**Comment by WardBrian** [comment]
We believe 1.1.5 has resolved this, `pip install prophet` will now use M1/M2 wheels
