### ISSUE TITLE
How prophet handles weekly seazonalities between years

### ISSUE THREAD

**Issue by paulojunqueira** [facebook/prophet#2453]
Hi again, 

I am confused and would like to know more about how prophet handles the variation of seazonality among diferent years?
For instance, let's say that in 2018 we have a pattern x for weekly seazonality, but beacuase of the covid 19, or even some thing else that we couldn't measure, it changed in 2020. How it capture it? Because the parameters, weekly and yearly ramain the same between years

Appreciate, thanks in advance!

**Comment by imad24** [comment]
Hello, If you dont tell the model about the variation of seasonality, it will simply not handle it. It will calculate a seasonality component that fits the best the whole history.
Fortunately, Prophet natively supports [Seasonalities that depend on other factors ](https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#seasonalities-that-depend-on-other-factors) where you can set conditions based on specific periods. In your case you can have _weekly_ and _weekly_covid_ seasonalities for example.

**Comment by paulojunqueira** [comment]
Hi @imad24, Thanks for replaying!
Ok for cases like Covid, but is this the same for the effects of "weekly" and "yearly"?
