### ISSUE TITLE
incompatibility with Pandas 2.x / pd.DataFrame.iteritems

### ISSUE THREAD

**Issue by michael72** [facebook/prophet#2460]
Pandas 1.5 [deprecated](https://pandas.pydata.org/docs/whatsnew/v1.5.0.html#other-deprecations) and v2 removed `DataFrame.iteritems` completely since the `items` function has been [present all along](https://github.com/pandas-dev/pandas/blob/v1.0.0/pandas/core/frame.py#L891):

`iteritems` is still used - at least - in [`plot.py`](https://github.com/facebook/prophet/blob/v1.1.4/python/prophet/plot.py#L870) - therefore `get_forecast_component_plotly_props` won't work with Pandas 2.x

see also:
https://github.com/pandas-dev/pandas/pull/45321

**Comment by frbelotto** [comment]
Is this really solved? I am still facing it on prophet 1.1.4

**Comment by michael72** [comment]
@frbelotto 1.1.4 is from May and doesn't contain the fix yet
