### ISSUE TITLE
win 7 Failed to build fbprophet

### ISSUE THREAD

**Issue by liangzulin** [facebook/prophet#286]
## I want to install fbprophet. After successfully installed the pystan package, I run the following command and: 

>pip install fbprophet

Collecting fbprophet
  Using cached fbprophet-0.1.1.tar.gz
Requirement already satisfied: matplotlib in d:\program files\anaconda3\lib\site
-packages (from fbprophet)
Requirement already satisfied: numpy in d:\program files\anaconda3\lib\site-pack
ages (from fbprophet)
Requirement already satisfied: pandas>=0.18.1 in d:\program files\anaconda3\lib\
site-packages (from fbprophet)
Requirement already satisfied: pystan>=2.14 in d:\program files\anaconda3\lib\si
te-packages (from fbprophet)
Requirement already satisfied: python-dateutil in d:\program files\anaconda3\lib
\site-packages (from matplotlib->fbprophet)
Requirement already satisfied: pytz in d:\program files\anaconda3\lib\site-packa
ges (from matplotlib->fbprophet)
Requirement already satisfied: cycler in d:\program files\anaconda3\lib\site-pac
kages (from matplotlib->fbprophet)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,>=1.5.6 in d:\program fi
les\anaconda3\lib\site-packages (from matplotlib->fbprophet)
Requirement already satisfied: Cython!=0.25.1,>=0.22 in d:\program files\anacond
a3\lib\site-packages (from pystan>=2.14->fbprophet)
Requirement already satisfied: six>=1.5 in d:\program files\anaconda3\lib\site-p
ackages (from python-dateutil->matplotlib->fbprophet)
Building wheels for collected packages: fbprophet
  Running setup.py bdist_wheel for fbprophet ... \

# **After long time waiting ... ...**

ible<_Ty>' being compiled
  D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(705
): fatal error C1003: error count exceeds 100; stopping compilation
  error: command 'D:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin
\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for fbprophet
  Running setup.py clean for fbprophet
Failed to build fbprophet
Installing collected packages: fbprophet

…………………………………………………………………………………………
…………………………………………………………………………………………
I can not copy and paste all the output since the cmd cannot record that many lines.
…………………………………………………………………………………………

4): note: see declaration of 'std::false_type'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(260): note: see reference to class template instantiation 'std::_Is_member_object_pointer<_Ty,_Pmf>' being compiled
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(272): error C2146: syntax error: missing '>' before identifier 'remove_cv'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(274): note: see reference to class template instantiation 'std::is_member_object_pointer<_Ty>' being compiled
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(272): error C2947: expecting '>' to terminate template-argument-list, found '<'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(256): error C3083: '_Bool_type': the symbol to the left of a '::' must be a type
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(272): error C2065: 'value': undeclared identifier
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(272): error C2975: '_Pmf': invalid template argument for 'std::_Is_member_object_pointer', expected compile-time constant expression
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(256): note: see declaration of '_Pmf'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(272): error C2146: syntax error: missing ',' before identifier '_Ty'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(272): error C2143: syntax error: missing ',' before '>'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(279): error C2146: syntax error: missing '>' before identifier 'remove_cv'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(281): note: see reference to class template instantiation 'std::is_member_functio
n_pointer<_Ty>' being compiled
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(279): error C2947: expecting '>' to terminate template-argument-list, found '<'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(279): error C2146: syntax error: missing ',' before identifier '_Ty'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(279): error C2143: syntax error: missing ',' before '>'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(287): error C2516: 'std::false_type': is not a legal base class
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(54): note: see declaration of 'std::false_type'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(288): note: see reference to class template instantiation 'std::_Is_pointer<_Ty>'
 being compiled
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(292): error C2143: syntax error: missing ',' before '<'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(295): note: see reference to class template instantiation 'std::_Is_pointer<_Ty*>
' being compiled
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(299): error C2146: syntax error: missing '>' before identifier 'remove_cv'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(301): note: see reference to class template instantiation 'std::is_pointer<_Ty>'
being compiled
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(299): error C2947: expecting '>' to terminate template-argument-list, found '<'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(299): error C2146: syntax error: missing ',' before identifier '_Ty'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(299): error C2143: syntax error: missing ',' before '>'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(307): error C2143: syntax error: missing ',' before '<'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(309): note: see reference to class template instantiation 'std::is_null_pointer<_
Ty>' being compiled
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(307): error C2518: keyword 'typename' illegal in base class list; ignored
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(314): error C2143: syntax error: missing ',' before '<'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(316): note: see reference to class template instantiation 'std::is_union<_Ty>' be
ing compiled
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(321): error C2143: syntax error: missing ',' before '<'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(323): note: see reference to class template instantiation 'std::is_class<_Ty>' be
ing compiled
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(328): error C2143: syntax error: missing ',' before '<'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(332): note: see reference to class template instantiation 'std::is_fundamental<_T
y>' being compiled
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(337): error C2143: syntax error: missing ',' before '<'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(341): note: see reference to class template instantiation 'std::is_object<_Ty>' b
eing compiled
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(348): error C2143: syntax error: missing ',' before '<'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(350): note: see reference to class template instantiation 'std::is_convertible<_F
rom,_To>' being compiled
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(355): error C2143: syntax error: missing ',' before '<'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(357): note: see reference to class template instantiation 'std::is_enum<_Ty>' being compiled
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(362): error C2143: syntax error: missing ',' before '<'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(364): note: see reference to class template instantiation 'std::is_compound<_Ty>' being compiled
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(369): error C2143: syntax error: missing ',' before '<'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(372): note: see reference to class template instantiation 'std::is_member_pointer<_Ty>' being compiled
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(377): error C2143: syntax error: missing ',' before '<'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(383): note: see reference to class template instantiation 'std::is_scalar<_Ty>' being compiled
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(389): error C2516: 'std::false_type': is not a legal base class
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(54): note: see declaration of 'std::false_type'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(390): note: see reference to class template instantiation 'std::is_const<_Ty>' being compiled
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(402): error C2516: 'std::false_type': is not a legal base class
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(54): note: see declaration of 'std::false_type'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(403): note: see reference to class template instantiation 'std::is_volatile<_Ty>' being compiled
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(414): error C2143: syntax error: missing ',' before '<'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(416): note: see reference to class template instantiation 'std::is_pod<_Ty>' being compiled
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(421): error C2143: syntax error: missing ',' before '<'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(423): note: see reference to class template instantiation 'std::is_empty<_Ty>' being compiled
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(428): error C2143: syntax error: missing ',' before '<'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(430): note: see reference to class template instantiation 'std::is_polymorphic<_Ty>' being compiled
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(435): error C2143: syntax error: missing ',' before '<'
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(437): note: see reference to class template instantiation 'std::is_abstract<_Ty>'
 being compiled
   ……………………………………
   ……………………………………(Something like that again and again)

### Dose any one know how and why? Or other method to install fbprophet? THX

**Comment by bletham** [comment]
Sorry for the slow response here. Using Anaconda it seems to be best to install with conda forge:
```
conda install gcc
conda install -c conda-forge fbprophet
```

**Comment by liangzulin** [comment]
It seems that the gcc cannot be found in windows 64 bit environment. I got these message after trying enter "conda install gcc"

D:\>conda install gcc
Fetching package metadata .........
Solving package specifications: .
PackageNotFoundError: Package not found: '' Package missing in current win-64 channels:
  - gcc

You can search for packages on anaconda.org with

    anaconda search -t conda gcc



D:\>

**Comment by liangzulin** [comment]
OK, I succeed. Thanks to  @bletham . Directly skip gcc installation step and use "conda install -c conda-forge fbprophet" command, after long waiting, all the process done and I can use it in pycharm in windows 10 x64.

Actually I install 2 python version in my computer, one is anaconda2 with python2.7, another is anaconda3 with python 3.6.1 and in order to avoid conflict I install anaconda2 first and then install anaconda3. After that I use CMD and enter C:\Anaconda3\Scripts folder to make sure I run the anaconda3's conda command, not the anaconda2's.
