### ISSUE TITLE
QUESTION: Why changepoints only on first 80% of series?

### ISSUE THREAD

**Issue by DBCerigo** [facebook/prophet#288]
Hi,

I'm trying to understand why it would be desirable to have changepoints spread over the first 80% of the series only.

My naive thought would be that including the possibility of trend changes right up to the most recent data would be a good thing for capturing the future trajectory of the series. Disclaimer - I have very little understanding of how the trend changes at changepoints are actually calculated! First time "using" STAN etc...

Advice/help/directions to explanations appreciated.

**Comment by lukewarm** [comment]
It's definitely a parameter that can be "tuned". My guess is that 80% works well for many series that facebook encounters. Having a later threshold like 90% would definitely make the trend component more sensitive to tail trend. But you will have very bad forecast if you include change point up to the most recent data.

Prophet models currently make forecasts by extrapolating the latest trend component, so you'd want it to be robust and not to pick up every piece of noise.

**Comment by bletham** [comment]
Exactly what @lukewarm said, you want to have enough runway to have a decent trend to extrapolate forward, and 80% is just a seems-to-be-reasonable heuristic. If it isn't working you can create your own list of potential changepoints and pass it in with the `changepoints` parameter.
