### ISSUE TITLE
Season and holiday problem

### ISSUE THREAD

**Issue by Goffic** [facebook/prophet#289]
If I don't think the factor of season and holiday, what can I do?

**Comment by lukewarm** [comment]
If you don't think your time series data have seasonal or holiday patterns, you can turn them off by specifying

`yearly_seasonality=False` and `holidays=None` in Python and by using similar arguments in R.

reference: [doc string](https://github.com/facebookincubator/prophet/blob/master/python/fbprophet/forecaster.py#L53-L58)
