### ISSUE TITLE
ANNOUNCEMENT: v0.2 release

### ISSUE THREAD

**Issue by bletham** [facebook/prophet#298]
Hi everyone, today v0.2 was pushed to CRAN and pypi. This includes a bunch of bug fixes, as well as some exciting new features:
* Forecasting with sub-daily data
* Daily seasonality, and custom seasonalities
* Extra regressors
* Access to posterior predictive samples
* Cross-validation function
* Saturating minimums

And more. The new features are described in [the documentation](https://facebookincubator.github.io/prophet/docs/quick_start.html) If you are experiencing a bug and are on v0.1.1, please upgrade to v0.2 to be sure it wasn't fixed there.

[A lot of people](https://github.com/facebookincubator/prophet/graphs/contributors) made substantial contributions to this version. Thanks to all of you!

**Comment by hungphamvn** [comment]
i still can't use pip to install fbprophet  on windows 10 python 3.6.2. 
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2
any help?

**Comment by bletham** [comment]
@hungphamvn can you open a new issue for this?
In the meantime, it sounds like the C++ compiler is not properly configured. If you're using anaconda, follow the instructions at the bottom [here](https://facebookincubator.github.io/prophet/docs/installation.html). Follow these steps to check that pystan is working correctly: http://pystan.readthedocs.io/en/latest/windows.html

**Comment by pybokeh** [comment]
@hungphamvn I followed the steps at the bottom of this Github project called [bayesfit](https://github.com/SlugocM/bayesfit) which also relies on PyStan and it has worked for me.  But I was on Windows 7 here at work.

I ```conda install pystan``` first then performed the instructions per bayesfit project instructions for Windows.
