### ISSUE TITLE
R v0.2 Error in new_CppObject_xp + Error in matrix(m$params[[name]], nrow = n.iteration)

### ISSUE THREAD

**Issue by McCompexpert** [facebook/prophet#300]
R version 3.3.1 (2016-06-21) -- "Bug in Your Hair"
prophet v0.2
Windows

Runnings this:

```
library(prophet)
ds <- seq(as.Date('2005-04-01'), as.Date('2005-09-03'), by='day')
x <- (1:length(ds))/length(ds)
y <- rnorm(length(ds), x * (1 - x) + 0.5, 0.1)
m <- prophet(data.frame(ds = ds, y = y), daily.seasonality=TRUE)

```
produces still the same error as mentioned in other issues:

```
Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  no valid constructor available for the argument list
failed to create the optimizer; optimization not done
Error in matrix(m$params[[name]], nrow = n.iteration) : 
  'data' must be of a vector type, was 'NULL'
```

**Comment by McCompexpert** [comment]
Rtools is not istalled on my Windows - possibly that explains the issue

**Comment by bletham** [comment]
That would be an issue, and this does look like rstan isn't working. This page describes how you can check if Rtools is functioning correctly:
https://github.com/stan-dev/rstan/wiki/Installing-RStan-on-Windows

**Comment by grantog** [comment]
I was running into this error as well. Installing rstan and Rcpp on my mac machine fixed it:
install.packages("rstan", repos = "https://cloud.r-project.org/", dependencies=TRUE)
install.packages(c("Rcpp", "rstan"), type = "source")
