### ISSUE TITLE
Create more interesting example of cross_validation function

### ISSUE THREAD

**Issue by seanjtaylor** [facebook/prophet#302]
We need to do a more thorough job of explaining how to use this: https://facebookincubator.github.io/prophet/docs/diagnostics.html

**Comment by saadk408** [comment]
I definitely agree. I would love some examples on how to calculate the recommended MAPE and use it to modify parameters.

**Comment by bletham** [comment]
This area of documentation has been fleshed out substantially and includes functionality for computing MAPE. (https://facebook.github.io/prophet/docs/diagnostics.html)
