### ISSUE TITLE
Error in library(prophet) : there is no package called ‘prophet’

### ISSUE THREAD

**Issue by lmsanch** [facebook/prophet#303]
I am trying to run a tutorial for prophet, which uses R magic in a Jupyter notebook in an anaconda environment. The following code:

```
#%load_ext rpy2.ipython
%load_ext rpy2.ipython
%matplotlib inline
from fbprophet import Prophet
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import logging
logging.getLogger('fbprophet').setLevel(logging.ERROR)
import warnings
warnings.filterwarnings("ignore")
df = pd.read_csv('../examples/example_wp_peyton_manning.csv')
df['y'] = np.log(df['y'])
m = Prophet()
m.fit(df)
future = m.make_future_dataframe(periods=366)
```

This blocks loads fine, then this:

```
%%R
library(prophet)
df <- read.csv('../examples/example_wp_peyton_manning.csv')
df$y <- log(df$y)
m <- prophet(df)
future <- make_future_dataframe(m, periods=366)

```

Returns this:
`Error in library(prophet) : there is no package called ‘prophet’`

I can load prophet w/o problems in my Jupyter notebook, but it is this last section that uses R that is giving me problems.

In my RStudio, I have already installed prophet:
```
> install.packages("prophet")
Installing package into ‘/Users/luissanchez/Library/R/3.2/library’
(as ‘lib’ is unspecified)
also installing the dependencies ‘bindr’, ‘bindrcpp’, ‘glue’, ‘pkgconfig’, ‘rlang’, ‘Rcpp’, ‘tibble’, ‘BH’, ‘plogr’, ‘StanHeaders’, ‘inline’, ‘gridExtra’, ‘RcppEigen’, ‘purrr’, ‘tidyselect’, ‘dplyr’, ‘extraDistr’, ‘rstan’, ‘tidyr’
```
And I still can't run the example. Any idea about where the problem is?
Thanks

**Comment by bletham** [comment]
I wonder if there might be two R installations. Can you run this command in both RStudio and in the R block of jupyter?
```
.libPaths()
```
and see if it is looking in a different path than it was installed in RStudio.

**Comment by lmsanch** [comment]
Thank you very much for your help. The command you indicated:

```
%%R
.libPaths()
```
returns:

`[1] "/Users/user/anaconda/lib/R/library"`

While in RStudio, I get this:
```
[1] "/Users/user/Library/R/3.2/library"                      
[2] "/Library/Frameworks/R.framework/Versions/3.2/Resources/library"
```
So it looks like I have two versions of R. How can I set Jupyter notebook to use the same one as in RStudio, or RStudio to use the Anaconda version so I can install Prophet from RStudio?

Thanks

**Comment by bletham** [comment]
It looks like you'll have to install from source:
http://thomas-cokelaer.info/blog/2012/01/installing-rpy2-with-different-r-version-already-installed/

Your best source for help on this would probably be the rpy2 issue tracker:
https://bitbucket.org/rpy2/rpy2/issues

Alternatively you could just install prophet in the install that jupyter is using.

**Comment by bletham** [comment]
I'm going to close this since it seems to be external to Prophet, but if you're still having issues feel free to re-open.
