### ISSUE TITLE
Computing residuals

### ISSUE THREAD

**Issue by mkohram** [facebook/prophet#309]
I'm trying to get the residuals of the additive model. Just skimming through the paper It looks like something along the lines of:

```python
trend = m.predict_trend(df)
seasonality = m.predict_seasonal_components(df)['seasonal']

residual = df['y'] - trend - seasonality
```
I was just wondering if this is the right way to do this.

Thanks!

**Comment by bletham** [comment]
If you call `predict` with no input, it will evaluate the model on the history. You could do
```
m = Prophet()
m.fit(history)
forecast = m.predict()
df = pd.merge(history, forecast, on='ds')
residuals = df['yhat'] - df['y']
```

**Comment by mkohram** [comment]
Got it. Thanks a lot.
