### ISSUE TITLE
Version 0.2 not on Conda Forge

### ISSUE THREAD

**Issue by johnrussell9983** [facebook/prophet#312]
Trying to get newest version in Anaconda and doesn't seem like its in Conda Forge yet. Is this coming soon? Thanks!

conda search -c conda-forge fbprophet
Fetching package metadata ...........
fbprophet                    0.1.post1                py27_0  conda-forge
                             0.1.post1                py35_0  conda-forge
                             0.1.post1                py36_0  conda-forge
                             0.1.1               np111py27_0  conda-forge
                             0.1.1               np111py35_0  conda-forge
                             0.1.1               np111py36_0  conda-forge
                             0.1.1               np112py27_0  conda-forge
                             0.1.1               np112py35_0  conda-forge
                             0.1.1               np112py36_0  conda-forge

**Comment by bletham** [comment]
It looks like this is in progress here: https://github.com/conda-forge/fbprophet-feedstock/pull/4

**Comment by bletham** [comment]
This is done.
