### ISSUE TITLE
Version 0.2 install failing with Cython-0.27

### ISSUE THREAD

**Issue by johnrussell9983** [facebook/prophet#315]
Had to revert to Cython 26.1 for install to complete - install would not work with Cython 27 with error below:

Collecting Cython!=0.25.1,>=0.22 (from pystan>=2.14->fbprophet)
  Downloading Cython-0.27-cp36-cp36m-manylinux1_x86_64.whl (3.1MB)
    100% |████████████████████████████████| 3.1MB 316kB/s
Installing collected packages: pytz, six, python-dateutil, pyparsing, cycler, numpy, matplotlib, pandas, Cython, pystan, fbprophet
  Running setup.py install for fbprophet ... error
    Complete output from command /usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6ptvyczi/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-lhh_boyp-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/fbprophet
    creating build/lib/fbprophet/stan_models
    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_1fdd477dd8bcc50395c4e25c8741f1c1 NOW.
    error: command 'gcc' failed with exit status 4

**Comment by bletham** [comment]
I upgrade my cython to 0.27 and reinstalled fbprophet and did not run into this issue. Could you maybe try:
```
pip install --upgrade --force-reinstall --no-cache-dir fbprophet
```

Otherwise, what platform are you on?

**Comment by johnrussell9983** [comment]
Yeah I tried again on Centos7 and it worked with no issues this time with Cython27. Maybe some weirdness on my side. Thanks for the quick response and I will close issue!
