### ISSUE TITLE
prophet from python and R give different results

### ISSUE THREAD

**Issue by nswitanek** [facebook/prophet#316]
Haven't explored why, but prophet is returning different forecasts for the same data when used from Python and from R. 

See the results below from the Peyton Manning data, from docs/quick_start.html:

Python:

DS | YHAT | YHAT_LOWER | YHAT_UPPER
-- | -- | -- | --
2017-01-15 | 8.206753 | 7.485107 | 8.920149
2017-01-16 | 8.531766 | 7.779331 | 9.284859
2017-01-17 | 8.319156 | 7.610545 | 8.986889
2017-01-18 | 8.151772 | 7.415802 | 8.875191
2017-01-19 | 8.163690 | 7.427153 | 8.884826

R:
             ds     yhat yhat_lower yhat_upper
3265 2017-01-14 7.825609   7.183818   8.488012
3266 2017-01-15 8.207400   7.478778   8.951113
3267 2017-01-16 8.532394   7.826360   9.240482
3268 2017-01-17 8.319785   7.596815   9.042505
3269 2017-01-18 8.152424   7.440858   8.874581
3270 2017-01-19 8.164327   7.419148   8.882906

**Comment by bletham** [comment]
Differences in `yhat` come from differences across platforms in how the L-BFGS optimization terminates. This isn't necessarily an R vs Python thing, inasmuch as two different machines both using the Python version can give slightly different results depending on machine precision (see #253).

If the variance in those two sets of results is too high for your application, you can pass along `algorithm='Newton'` to `fit` and it will use the Newton optimizer instead of L-BFGS which seems to have a more consistent termination. It does, however, take significantly longer, which is why it isn't the default.

Some variance in `yhat_lower, yhat_upper` can be attributed to the same phenomenon, but a much more significant source of variance there is the fact that these are estimated using Monte Carlo sampling, and so are non-deterministic. By default we use 1000 MC samples for an 80% interval, which gives the variance shown. If this variance is too high then it can be reduced by increasing the `uncertainty_samples` input on Prophet initialization.

**Comment by nswitanek** [comment]
Thank you for the thorough reply, Ben! Very helpful

**Comment by robinsondaniel** [comment]
Hi @bletham , I'm facing a similar issue where the test set validation MAPE(Mean Absolute Percentage Error) in Python is much higher than the MAPE in R with the same data(Python model's MAPE was almost 50% more than R model's MAPE).

I tried using Newton optimizer and increasing the value of uncertainty samples but they were not helpful in reducing MAPE.

To give more context on the environment, R version 3.5 is run on my local environment and Python version 2.7 is run on the Cloudera workbench of my client's environment.

**Comment by bletham** [comment]
@robinsondaniel that's a bit surprising to me that the difference would be so large. I have personally not seen any significant changes in performance across different versions. Is there any chance you can post code and data that reproduces this issue so I can try to look more into it?

**Comment by GinoWoz1** [comment]
Issue seems to be with the backends. I have same data, same parameters and same optimizer and I am getting very different results. Using newton optimizer and L_BFGS explicitly doesnt seem to fix anything.

https://discourse.mc-stan.org/t/different-outputs-in-rstan-vs-pystan/211/27

**Comment by thebitanpaul** [comment]
> Differences in `yhat` come from differences across platforms in how the L-BFGS optimization terminates. This isn't necessarily an R vs Python thing, inasmuch as two different machines both using the Python version can give slightly different results depending on machine precision (see [#253](https://github.com/facebook/prophet/issues/253)).
> 
> If the variance in those two sets of results is too high for your application, you can pass along `algorithm='Newton'` to `fit` and it will use the Newton optimizer instead of L-BFGS which seems to have a more consistent termination. It does, however, take significantly longer, which is why it isn't the default.
> 
> Some variance in `yhat_lower, yhat_upper` can be attributed to the same phenomenon, but a much more significant source of variance there is the fact that these are estimated using Monte Carlo sampling, and so are non-deterministic. By default we use 1000 MC samples for an 80% interval, which gives the variance shown. If this variance is too high then it can be reduced by increasing the `uncertainty_samples` input on Prophet initialization.

How to pass this `algorithm='Newton'` argument in prophet, also in pycaret prophet? I have observed that differnt order of combination of independent variables, changes the output of pycaret prophet. This is the code I am using:

```Python
iv = ['holiday','tempAvg']
df_train1 = df_train1[['ds','y']+iv]
future_df= future_df[['ds']+iv]

# Step 1: Setup the PyCaret environment for time series modeling
        s = setup(
        data=df_train1, 
        target="y", 
        fold=3, 
        enforce_exogenous=True, 
        fh=future_df.shape[0], 
        session_id=124
        )


        # Create the model
        prophet_model = create_model('prophet',  algorithm='Newton')

        # Tune the model
        tuned_model = tune_model(prophet_model)

        # Finalize the model
        final_model = finalize_model(tuned_model)

        # Make predictions
        pycaret_pred = predict_model(final_model, fh=future_df.shape[0], X=future_df)
```
