### ISSUE TITLE
parallel prophet and GIL

### ISSUE THREAD

**Issue by rpanai** [facebook/prophet#317]
I'm having some performance issue trying to run prophet in parallel. Apparently everything lies on Gil not being released 
[https://stackoverflow.com/questions/46456438/dask-and-fbprophet/46471808#46471808](url)

Do you need to hold the GIL or are you eventually planning to release it?

**Comment by robertdknight** [comment]
That would be a feature of Python and not something Prophet would release.  To work around that use multiprocessing – run the work in distributed resources and architect a way to share the data (pipes, file-output, and so on).  Taskset can work <https://stackoverflow.com/questions/990102/python-global-interpreter-lock-gil-workaround-on-multi-core-systems-using-task>  for this – setting a task to work on a specific core.  You may not see a true performance gain if that core is used by other processes thanks to the operating system scheduler.  To account for that, you could boot Linux using the isolcpu <http://www.linuxtopia.org/online_books/linux_kernel/kernel_configuration/re46.html> s flag, and set aside specific cores so they were always “empty” at the time you initiated your computations – the basic OS will never use them for running applications.  Then, uses task set to specify which core the process works on, and combine the data from the two processes which run on the isolated cores.  If you don’t care to use the isolcpus flag, the principle still works, but the operating system might consume some percentage of the core/thread that your multiprocessor application is using.

**Comment by bletham** [comment]
Thanks @robertdknight for the thorough explanation.

**Comment by bletham** [comment]
I'm going to close this since there doesn't seem to be anything to be done about it here.
