### ISSUE TITLE
Using Dummy Variables for Daily Seasonality

### ISSUE THREAD

**Issue by apapiu** [facebook/prophet#319]
I've noticed that Prophet uses Fourier Series to model everything other than the Weekly Seasonality. This usually works well but for highly jagged hourly time-series I've noticed that the model underfits the trend even after adding extra Fourier terms. 

Has anyone considered adding an option to `add_seasonality` that to use dummy variables? I could probably try working on it if you think it makes sense both computationally and statistically.

Also thanks for adding support for sub-daily data!

**Comment by bletham** [comment]
The weekly seasonality actually is modeled with a Fourier series also. It uses an order of 3, which corresponds to 6 terms. With the offset term, this is equivalent to using dummy variables for weekly seasonality with daily data. 

This is an interesting idea, to have a way of adding dummy variable seasonalities. Computationally this is not an issue at all. Statistically, the Fourier components provides some extra regularization by imposing this smoothness constraint, which I would expect to be valid for most applications. So I'd be more worried about overfitting, but I can appreciate that there are situations where the current seasonality is too smooth and so it'd be good to have that as an option.

This can currently be done using the `add_regressor` method. You'd have to compute the dummy variable for each component and add them each separately as regressors. But maybe it would be good to start by trying out dummy variables that way, and if it works well and seems like it could be generally useful we can think about a nice interface for it. Maybe even just an interface for adding a matrix of regressors at a time might get us most the way there while being generally useful.

**Comment by apapiu** [comment]
Good pint on using `add_regressor` - thanks! Will run some test and report back if I see major improvements from using Fourier components.
