### ISSUE TITLE
Quality of model

### ISSUE THREAD

**Issue by beloteloff** [facebook/prophet#321]
Do you planing to add model's quality metrics like R^2 adjusted in ARIMA models? Metrics MAPE/MAE is not good evaluate model's accuracy

**Comment by teramonagi** [comment]
You can use `diagnostics` functionality to calculate the metrics like R^2.
https://facebook.github.io/prophet/docs/diagnostics.html

**Comment by beloteloff** [comment]
Of course, but I'm interesting for decision from "box".

**Comment by bletham** [comment]
I think it'd be nice to have a whole collection of various metrics. I for one do like MAPE, but it'd be good to have a bunch built-in. I'm not exactly sure what an adjusted R^2 would look like for this model, we'd have to give it a try. This is being tracked in #194.

**Comment by bletham** [comment]
I'm going to close this and leave the discussion on useful cross-validation metrics to #194.
