### ISSUE TITLE
Cross validation  parameters 

### ISSUE THREAD

**Issue by whitebread** [facebook/prophet#330]
Hi there. 
I'm not sure of how to set the parameters for the crossvalidation method. 
I have a TS with 5 minutes intervals 2 years long.
If I train my data like this:

```
m = Prophet(changepoint_prior_scale=0.01)
m.fit(df_training)
future = m.make_future_dataframe(periods=300, freq="5min")
df_cv = cross_validation(m, horizon='2 days')

```

The cross validation never ends. 
Ideally I would like to train my model on almost 2 years and measure the error on the last 2 days.
Any help?
Also, is there any group dedicated to fbprophet? Thanks.

**Comment by MuaazBin** [comment]
Try this approach without cross validation if you just want to train on everything and predict two more days:

``` python
m = Prophet(changepoint_prior_scale=0.01)
df_training2 = df_training[:-300] # remove last 300 from training
df_test = df_training[-300:] # last 300 for testing
m.fit(df_training2)
future_data = model.make_future_dataframe(periods=300, freq = '5min') 
forecast_data = model.predict(future_data)
```

Once you have forecast_data
lets say we want an MAPE error
``` python
def mean_absolute_percentage_error(y_true, y_pred): 
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100
```

Now just calculate MAPE 

```python
mean_absolute_percentage_error(df_test['y'],forecast_data['yhat'])
```

Hope it helps! 🗡

**Comment by bletham** [comment]
The reason `cross_validation` is taking forever is because it is re-fitting the model for each day of data, so ~730 model fits. The cross-validation function works by doing a model fit and forecast every `period` days, beginning from an initial history of `initial` days. If you look at the docstring `help(cross_validation)` it lists the default values for the `period` as 0.5 * horizon, and for `initial` as 3 * horizon. For you, that means it is starting from a history of 6 days, and then adding one day at a time. You can get more reasonable behavior from `cross_validate` with something like
```
cross_validate(m, horizon='2 days', period='20 days', initial='365 days')
```

**Comment by bletham** [comment]
This seems to be resolved but if you are having further issues with this please re-open.

**Comment by kevindavenport** [comment]
> Try this approach without cross validation if you just want to train on everything and predict two more days:
> 
> ```python
> m = Prophet(changepoint_prior_scale=0.01)
> df_training2 = df_training[:-300] # remove last 300 from training
> df_test = df_training[-300:] # last 300 for testing
> m.fit(df_training2)
> future_data = model.make_future_dataframe(periods=300, freq = '5min') 
> forecast_data = model.predict(future_data)
> ```
> 
> Once you have forecast_data
> lets say we want an MAPE error
> 
> ```python
> def mean_absolute_percentage_error(y_true, y_pred): 
>     y_true, y_pred = np.array(y_true), np.array(y_pred)
>     return np.mean(np.abs((y_true - y_pred) / y_true)) * 100
> ```
> 
> Now just calculate MAPE
> 
> ```python
> mean_absolute_percentage_error(df_test['y'],forecast_data['yhat'])
> ```
> 
> Hope it helps! 🗡
Be sure to include`
,include_history = False)`

in `make_future_dataframe` or else you'll end up with an array size mismatch
