### ISSUE TITLE
First of month projection seems off

### ISSUE THREAD

**Issue by bronsonelliott** [facebook/prophet#338]
I'm **VERY** new to Python and trying to make my way through Prophet to see how I might be able to use it in my work.  I am feeding Prophet with a file that contains about 3 years worth of history.  When I get the results and plug them into Excel and just do a side by side comparison to what actually happened, I'm getting some strange results when I look at the days of the month (1-30).

If you look at the image below, I've aggregated the data by the days of the month and immediately noticed that for some reason, Prophet doesn't seem to see the spike that occurs on the first of the month in it's projections.  The rest of the month looks pretty good overall and Prophet even accurately sees the drop off at the end of the month.

![image](https://user-images.githubusercontent.com/32395534/32017851-a309cb16-b98d-11e7-8ffa-301dcfe6f007.png)

Just looking for some guidance on how to improve the code and make the projections better fall in line with what actually happened.  Here is the code I'm currently using.

```python
import pandas as pd
import numpy as np
from fbprophet import Prophet
from holidays import holidays

data_file = "C:\path\to\file.csv"

df = pd.read_csv(data_file)
df.columns = ['ds', 'y']
df['ds'] = pd.to_datetime(df['ds'])
df['y'] = np.log(df['y']) # log-transform y

model = Prophet(holidays=holidays, yearly_seasonality=True, weekly_seasonality=True, holidays_prior_scale=0.05) #instantiate Prophet
model.add_seasonality(name='monthly', period=30.5, fourier_order=5, prior_scale=0.05) #add monthly seasonality
model.fit(df); #fit the model with your dataframe

future_data = model.make_future_dataframe(periods=7)
forecast = model.predict(future_data)

forecast['yhat'] = np.exp(forecast[['yhat']])

forecast.to_csv('PredictOutput.csv')
```

Thank you!

**Comment by bletham** [comment]
Sorry for the slow response on this. It looks like Prophet is requiring too much smoothness in the monthly seasonality.

From what you describe and from the figure, there is a big drop on day 30/31 followed immediately by a sharp uptick on day 1. Prophet's seasonality model assumes a degree of smoothness - it is grabbing the end of the month drop but then can't change quickly enough to also get the big uptick on the next day. Instead on the 1st it is still recovering from the end-of-month drop. You can also see this leading up to the end of the month, that the Prophet forecast starts to drop earlier than actuals. This is the fastest the seasonality model is allowing it to drop.

There are two things you could think about doing here. How quickly the seasonality is allowed to change is controlled by the `fourier_order` parameter. So increasing that for the monthly seasonality would allow it to get both the drop on the 30th/31st and the rise on the next day. However, adding all of this flexibility to the model could cause issues with overfitting the middle of the month. So I actually wouldn't recommend this approach.

What I would recommend would be to actually replace monthly seasonality with a holiday effect for the end/start of the month. This will allow for very sharp effects from one day to the next and does not assume the smoothness that seasonality does. So, you would make a dataframe like
```
holidays = pd.DataFrame({
  'holiday': 'month',
  'ds': pd.date_range('2012-01-01', '2019-01-01', freq='MS'),
  'lower_window': -2,
  'upper_window': 2,
})
```
where the date range would include all of the history and future dates. The `lower_window` and `upper_window` parameters tell it to include 2 days before the start of the month, and 2 days after the start of the month as having special effects. From the plot you give, it looks like this is the case.

**Comment by bronsonelliott** [comment]
Thank you @bletham. That absolutely did the trick!  Here's how the data looks now:


![image](https://user-images.githubusercontent.com/32395534/32381636-2d56ab46-c081-11e7-8fee-3c49d2a9a2fa.png)

**Comment by bletham** [comment]
Awesome, looks great!
