### ISSUE TITLE
Control predictive_samples variance

### ISSUE THREAD

**Issue by feriat** [facebook/prophet#345]
Hi everyone.

First I want to thank each and every person contributing to prophet: it made our predictions controllable and more precise compared to R `forecast` package! Hurray!

But what we want now is to control predictive_samples variance. The use-case is as follows: we first make a "mean" forecast of our priors using prophet, then generate multiple outcomes using predictive_samples to evaluate confidence intervals. We later combine multiple models together (not only prophet) to saturate our business specifics.

What we lack is the parameter to control predictive_samples variability. Say, mcmc says it will be between [55:57], but we are not sure about it and want to generate predictive_samples that are between [52:60] instead. 

Is there an option for that in prophet?

**Comment by bletham** [comment]
Glad to hear it's been useful to you!

The variance in `predictive_samples` is the posterior variance and contains the uncertainty in the model parameters and the future trend. It is inferred from the data and there aren't really any parameters to control it. What you are trying to do, however, is quite reasonable - the model is underestimating the uncertainty, and you want to incorporate your knowledge into the uncertainty estimates. 

The output of `predictive_samples` is a list with three items: `yhat`, `trend`, and `seasonal`. The prophet model is that `yhat = trend + seasonal + noise`, where `noise` is normally distributed with a variance that is inferred from the data. If a constant increase in variance would work for you, then you could adjust the variance of the posterior by computing `trend + seasonal + your_noise`, where you set the variance of `your_noise`.

Does that seem like what you're looking for?

**Comment by feriat** [comment]
Hi Ben!

Thank you for your suggestion! I was thinking of doing it already, but the problem is that `noise` would be IID, that would cause it to have zero mean. Shouldn't I add some sort of random walk to incorporate some trend error? I want to interpret it as one of possible scenarios, thus some simple one-period jiggle is not exactly what I expect. Also, this method wouldn't utilize my `cap` and `floor` settings that I have, but this thing I can cope with, I guess.

**Comment by bletham** [comment]
I see, you need to increase the trend uncertainty.

There isn't a very direct way to do this, but there are some things that would increase trend uncertainty. Generally allowing the trend to be more flexible will increase trend uncertainty, such as increasing `n.changepoints`. This does, however, make it more possible to overfit the trend, so you'd have to watch out for that. You could consider fitting the model twice, once as you currently are to get the mean estimate, but then a second time with higher `n.changepoints` to get the higher predictive variance.

The variance of the predictive trend is `lambda` here:
https://github.com/facebook/prophet/blob/master/R/R/prophet.R#L1346
but it's buried pretty deep and not easily alterable.

**Comment by bletham** [comment]
This is related to the issue in #293. I think the solution to both of these issues will end up being the same so I'm going to close this one and merge it over with #293.
