### ISSUE TITLE
update model using new data points?

### ISSUE THREAD

**Issue by p9anand** [facebook/prophet#347]
Thanks for great work and making it open source. Really enjoying the package.
how to apply prophet in new markets where things are changing rapidly?
Thanks.

**Comment by bletham** [comment]
If I understand correctly, you want to update the model to add in additional observations without having to fit from scratch.

This is along the same lines as #46 . There isn't any way currently to do that sort of on-line fitting for Prophet, you will just have to re-fit the model entirely.

**Comment by p9anand** [comment]
Yeah. Thanks for the response.
