### ISSUE TITLE
Error while calling predict() function

### ISSUE THREAD

**Issue by melzoghbi** [facebook/prophet#354]
I am using prophet to predict time series data i store in pandas dataframe. When i call predict() method i get the following error:

OverflowError: Python int too large to convert to C long

This is how my dataset looks look;
![image](https://user-images.githubusercontent.com/11993393/32803659-447f73c8-c952-11e7-9d71-5c7301b57ae2.png)

This is the output when i called make_future_dataframe():
![image](https://user-images.githubusercontent.com/11993393/32803726-77f61af4-c952-11e7-98bb-b0260179e1c3.png)

How to fix this?

Full error message:

---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
<ipython-input-120-9e13947d7f0b> in <module>()
----> 1 forecast = m.predict(future)
      2 forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()

~\AppData\Local\conda\conda\envs\fb\lib\site-packages\fbprophet\forecaster.py in predict(self, df)
    874         df['trend'] = self.predict_trend(df)
    875         seasonal_components = self.predict_seasonal_components(df)
--> 876         intervals = self.predict_uncertainty(df)
    877 
    878         # Drop columns except ds, cap, floor, and trend

~\AppData\Local\conda\conda\envs\fb\lib\site-packages\fbprophet\forecaster.py in predict_uncertainty(self, df)
   1102         Dataframe with uncertainty intervals.
   1103         """
-> 1104         sim_values = self.sample_posterior_predictive(df)
   1105 
   1106         lower_p = 100 * (1.0 - self.interval_width) / 2

~\AppData\Local\conda\conda\envs\fb\lib\site-packages\fbprophet\forecaster.py in sample_posterior_predictive(self, df)
   1066         for i in range(n_iterations):
   1067             for _j in range(samp_per_iter):
-> 1068                 sim = self.sample_model(df, seasonal_features, i)
   1069                 for key in sim_values:
   1070                     sim_values[key].append(sim[key])

~\AppData\Local\conda\conda\envs\fb\lib\site-packages\fbprophet\forecaster.py in sample_model(self, df, seasonal_features, iteration)
   1129         Dataframe with trend, seasonality, and yhat, each like df['t'].
   1130         """
-> 1131         trend = self.sample_predictive_trend(df, iteration)
   1132 
   1133         beta = self.params['beta'][iteration]

~\AppData\Local\conda\conda\envs\fb\lib\site-packages\fbprophet\forecaster.py in sample_predictive_trend(self, df, iteration)
   1171 
   1172             prob_change = min(1, (S * (T - 1)) / N)
-> 1173             n_changes = np.random.binomial(N, prob_change)
   1174 
   1175             # Sample ts

mtrand.pyx in mtrand.RandomState.binomial()

**OverflowError: Python int too large to convert to C long**

**Comment by bletham** [comment]
Thanks for reporting this.

I'm guessing that you have two data points that are very close to eachother which would cause a bug in how we estimate extrapolation uncertainty in the trend. Could you paste for me the output of this:
```
pd.to_datetime(df['ds']).diff().sort_values().head()
```
to see what the smallest difference between observations is?

On a side note, you have data with a frequency of every 1-2 seconds, but then in make_future_dataframe are getting just one observation per day. If you just care about predicting with a resolution of 1 day then it is really overkill to fit the model to second-level data. You would benefit from thinning out your data, perhaps to a few observations per day, or maybe even sum the data by day and forecast totals by day.
On the other hand if you want to model things with fine resolution, then you can use the `freq` input to make_future_dataframe to get a dataframe with second-level or minute-level resolution.

On a related note, if you have two many rows in the dataframe that you pass to `predict` you will run into issue #215, which basically will exit if you have too many rows. It looks like you have at least 150,000 rows in that dataframe, which would probably be too many. If you don't need a forecast for past dates then you can use `include_history=False` in make_future_dataframe and that will cut down the number of rows substantially. Alternatively you can break the dataframe into chunks and call `predict` on each chunk, and then concat the results all together afterwards.

**Comment by bletham** [comment]
I'm hoping this is resolved, if not then please re-open.
