### ISSUE TITLE
How to use Prophet Predict() for data that is daily seasonality

### ISSUE THREAD

**Issue by melzoghbi** [facebook/prophet#355]
Hi,

I am using data where we have sensor data every second, i would like to use prophet to predict() this feature data. I see that the sample program uses timestamp that is one record per day which is different in my case, i read multiple records per day since i read this sensor data every second.

Any suggestion how would we use Prophet() in this use case? if there is any sample would be great.

Thanks a lot.

**Comment by bronsonelliott** [comment]
Here's an example of using Prophet with sub-daily data. The sample data is every 5 minutes but you should be able to customize it for your purpose.  

[https://facebook.github.io/prophet/docs/non-daily_data.html](url)

**Comment by melzoghbi** [comment]
Thanks @bronsonelliott, will check this out.
