### ISSUE TITLE
plot_components() throws an error

### ISSUE THREAD

**Issue by melzoghbi** [facebook/prophet#356]
When i use plot_components() method after training and plotting my forecast as showing in the blog [post](https://facebook.github.io/prophet/docs/quick_start.html). I get this error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-128-10d98d6d0e49> in <module>()
----> 1 m.plot_components(forecast);

~\AppData\Local\conda\conda\envs\fb\lib\site-packages\fbprophet\forecaster.py in plot_components(self, fcst, uncertainty, plot_cap, weekly_start, yearly_start)
   1304                                  figsize=(9, 3 * npanel))
   1305 
-> 1306         for ax, plot in zip(axes, components):
   1307             if plot == 'trend':
   1308                 self.plot_forecast_component(

**TypeError: zip argument #1 must support iteration**

Any help how can i fix this?

Thanks.

**Comment by bletham** [comment]
The issue here seems to be that you have only 1 component to plot (the trend). It seems that all of the seasonalities have been disabled for this model. Is that the case? Could you post the output of 
```
print(m.seasonalities)
```

If this is the case, then the component plot won't really add anything to just `m.plot` since the only component is the trend, but anyway this error should be fixed.

**Comment by bletham** [comment]
(note: or
```
print m.seasonalities
```
in python2
)

**Comment by bletham** [comment]
Fixed in 4628bcd8017c3bf3558172afd3f6216a35770679

**Comment by melzoghbi** [comment]
Thanks.

**Comment by bletham** [comment]
Let's leave this open until the fix gets pushed to PyPI and CRAN.

**Comment by melzoghbi** [comment]
ok @bletham .

**Comment by PopatAD** [comment]
Hi Bletham,

I'm getting this error too

`print(m.seasonalities)` returns {'yearly': {'period': 365.25, 'fourier_order': 10, 'prior_scale': 10.0}, 'weekly': {'period': 7, 'fourier_order': 3, 'prior_scale': 10.0}, 'daily': {'period': 1, 'fourier_order': 4, 'prior_scale': 10.0}}

Fwiw, I'm modelling the S&P 500

**Comment by bletham** [comment]
@PopatAD  There must be something else going on here then. Can you post the traceback for the error you are getting?

**Comment by PopatAD** [comment]
@bletham It's all good now, thanks for replying anyway

**Comment by melzoghbi** [comment]
Thanks all.
