### ISSUE TITLE
R freeze during predict

### ISSUE THREAD

**Issue by vivshume** [facebook/prophet#366]
Hi , 
when I am running my Model for 15k+ prediction, My model suddenly stops in middle and it still shows processing. The model never moves forward. 
Can you Please let me know the Fix ?
Thanks 
Vivek

**Comment by TheGeoLawton** [comment]
I wonder if this might be an internal memory issue. R stores large objects in memory, and when the machine fills up, the processing stops. If that's the case, It is not specific to Prophet, it is an issue with R itself.

**Comment by bletham** [comment]
This is probably related to https://github.com/facebook/prophet/issues/215. Basically, in prediction we make a really big matrix that is (number of prediction points)x(uncertainty_samples), where `uncertainty_samples` here is an input to Prophet() for how many samples to use to estimate trend uncertainty. 15,000x1000 definitely sounds big enough to cause memory issues.

There are a few things you can do to get around this. If you don't care about uncertainty, then set `uncertainty_samples=1` when you create the Prophet object. Alternatively, just break your predict dates into chunks of maybe a 1000 and call predict separately on each chunk, and then concat the output dataframes from each call. Does that make sense?

**Comment by bletham** [comment]
I'm hoping these suggestions resolved the issue, otherwise feel free to re-open.
