### ISSUE TITLE
i cannot install pip install pyleargist 

### ISSUE THREAD

**Issue by pmathulan** [facebook/prophet#367]
i cannot install pip install pyleargist 
ERRoR:
Collecting pyleargist
  Using cached pyleargist-2.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/3d/cfmqwlqs6ljdnmj5357vpwsm0000gn/T/pip-build-eu4_knnk/pyleargist/setup.py", line 7, in <module>
        version = file('VERSION.txt').read().strip()
    NameError: name 'file' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/3d/cfmqwlqs6ljdnmj5357vpwsm0000gn/T/pip-build-eu4_knnk/pyleargist/

**Comment by bletham** [comment]
This isn't the pyleargist package, I think you have the wrong issue tracker.

**Comment by sidartastan** [comment]
Did you solve the problem? I have similar problem

(base) C:\Users\xxx>pip install pyleargist
Collecting pyleargist
  Using cached pyleargist-2.0.5.tar.gz (26 kB)
    ERROR: Command errored out with exit status 1:
     command: 'D:\programlar\anaconda\python.exe' -c 'import sys, setuptools, to
kenize; sys.argv[0] = '"'"'C:\\Users\\syks\\AppData\\Local\\Temp\\pip-install-hr
enhedf\\pyleargist\\setup.py'"'"'; __file__='"'"'C:\\Users\\syks\\AppData\\Local
\\Temp\\pip-install-hrenhedf\\pyleargist\\setup.py'"'"';f=getattr(tokenize, '"'"
'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');
f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:
\Users\syks\AppData\Local\Temp\pip-install-hrenhedf\pyleargist\pip-egg-info'
         cwd: C:\Users\syks\AppData\Local\Temp\pip-install-hrenhedf\pyleargist\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\syks\AppData\Local\Temp\pip-install-hrenhedf\pyleargist\set
up.py", line 7, in <module>
        version = file('VERSION.txt').read().strip()
    NameError: name 'file' is not defined
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check th
e logs for full command output.
