### ISSUE TITLE
Deploy Prophet models into production

### ISSUE THREAD

**Issue by melzoghbi** [facebook/prophet#368]
Hi,

What would be the steps to server and deploy Prophet models into production? Is there any recommendation or a walk through on how to do this?

Thanks a lot.

**Comment by bletham** [comment]
I don't think I have any recommendations to give for this since our own productionizing is pretty intimately tied to other internal systems. But I think generally the idea would be similar to doing this for any machine learning package, just a matter of I/O. Anyone else have any wisdom to share?

**Comment by sweb** [comment]
Hey,

we use Docker to bundle up the dependencies and the current state of data manipulation code (e.g. removal of outliers), the actual (Prophet) model configuration and the validation code. We schedule our forecasts using an ETL tool that fires up containers on a kubernetes cluster. During runtime, the container pulls the necessary data from hive using PyHive. Afterwards, forecast and validation results are written to hive as well.

**Comment by robertdknight** [comment]
I'm trying to get a job in software development or data analysis somewhere, so I just made [hundreds of thousands of charts](https://rdknight.org/viewer/) and put them on a webserver.

**Comment by melzoghbi** [comment]
@sweb do u have a docker image that you can point me to so i can use it as a starting point? Thanks.
