### ISSUE TITLE
r prophet freezes at data point

### ISSUE THREAD

**Issue by arbstat** [facebook/prophet#369]
I'm running 2952 prophet loops on a Windows server with r prophet 0.2.1.

After over 2000 loops the code freezes with the predict function.

It seems to be specific to a data point, as I can just run only 50 loops but prophet will freeze anyway at the same data point (just a few days ago the same code was running through the same data point with no issues).

If I run the code on that single point without a loop, the code works fine.

I tried many times, opening a new workspace or starting from a saved one.
I also tried the adapted_prophet in a previous thread without success.

For me a missed single point forecast is not such a big deal, but the problem is that try or tryCatch can't prevent the code from freezing and can't let it move on to the next data point.

**Comment by bletham** [comment]
Just to be sure I understand, you have 2952 datasets and you are fitting each with Prophet in a loop. There is one particular dataset that is freezing on predict, but only in a loop. (But it can be a smaller loop of only 50, not the full loop).

How many points are in the problem dataset and how many points are you making predictions at? I'm wondering if maybe there are memory issues like in https://github.com/facebook/prophet/issues/366 , which could be exacerbated in the loop by objects hanging around from past runs.

**Comment by arbstat** [comment]
I have a dataset of 82 rows and 12 columns.
I run a loop across rows and each column with 3 different windows, so the total loops are 82*12*3.
Using uncertainty.samples = 1 in the prophet function just makes the code run faster but it gets stuck anyway at the same point as before on the forecast fuction (third window value, 6th column and 78th row).
Since there is no way to let prophet skip a row, I really need to find out what is the issue.
I don't think it's memory because I can open a workspace with the dataset only and run the code only on the third window and sixth column (meaning only 82 loops) but it will still crash at the 78th row.
If I run the code outside a loop on the said critical point, it works fine.
Would attaching the file and the code help ?

**Comment by bletham** [comment]
I see, so each call to `predict` is passing in a dataframe with <=82 rows. That doesn't sound like a memory issue then. Is there any chance you can post the data so I can try to repro?
If not then I'm wondering if maybe something weird is happening during model fit. Could you print back the values of `m$params`?

**Comment by arbstat** [comment]
[results4.xlsx](https://github.com/facebook/prophet/files/1505000/results4.xlsx)

Sorry for the late answer.

Here is the code (data attached):

`library(prophet)
library(xts)

results4.xts <- read.csv("results4.csv") # convert .xlsx to .csv
results4.xts <- xts(results4.xts[,2:NCOL(results4.xts)], as.Date(results4.xts[,1]))
results4.xts_ <- results4.xts["2017-08-01::"]

fore <- mat.or.vec(nc=NROW(basket.names), nr=NROW(results4.xts_))
fores <- replicate(7,fore, simplify=FALSE)

for (win in 5:7){
for (j in 1:NROW(basket.names)){
for (i in win:NROW(results4.xts_)){
dat <- data.frame(index(results4.xts_[(i-win+1):i,j]),coredata(results4.xts_[(i-win+1):i,j]))
colnames(dat) <- c("ds","y")
m <- prophet(dat,uncertainty.samples = 1)
future <- make_future_dataframe(m, periods = 1, freq="day")
fores[[win]][i,j] <- predict(m, future)$yhat[(win+1)]
print(paste(i,j,win))
}}}
`

**Comment by bletham** [comment]
hm, I'm not able to replicate. The only change I had to make to the code was to replace NROW(basket.names) with 12 since basket.names wasn't defined:
```
library(prophet)
library(xts)

results4.xts <- read.csv("results4.csv") # convert .xlsx to .csv
results4.xts <- xts(results4.xts[,2:NCOL(results4.xts)], as.Date(results4.xts[,1], "%m/%d/%Y"))
results4.xts_ <- results4.xts["2017-08-01::"]

# NROW(basket.names) = 12?...
nrow.basket.names <- 12

fore <- mat.or.vec(nc=nrow.basket.names, nr=NROW(results4.xts_))
fores <- replicate(7,fore, simplify=FALSE)

for (win in 5:7){
for (j in 1:nrow.basket.names){
for (i in win:NROW(results4.xts_)){
dat <- data.frame(index(results4.xts_[(i-win+1):i,j]),coredata(results4.xts_[(i-win+1):i,j]))
colnames(dat) <- c("ds","y")
m <- prophet(dat,uncertainty.samples = 1)
future <- make_future_dataframe(m, periods = 1, freq="day")
fores[[win]][i,j] <- predict(m, future)$yhat[(win+1)]
print(paste(i,j,win))
}}}
```

What is m$params right before the predict that fails?

**Comment by bletham** [comment]
I'm going to close this as presumably resolved but if there is still an issue please reopen.
