### ISSUE TITLE
Historical data fiting problem: non-existing changepoints 

### ISSUE THREAD

**Issue by pocakka** [facebook/prophet#370]
I have a dataset with a high "top". 
When I see the historical data-fiting, the prophet shows non-exist high points. (The negative forecast values ​​are deliberately set to zero ).
Is it possible to do better historical data fiting? I made the red line with an image editor to the chart.
Chart: https://imgur.com/a/ItQFK

**Comment by bletham** [comment]
It's treating the spike at the end as yearly seasonality. You can avoid this by disabling yearly seasonality (`yearly_seasonality=False` input to Prophet()).

It looks like that very sharp set of trend change is near the very end of the time series. By default Prophet will only do automatic trend change detection in the first 80% of the time series. If you want to fit that spike with trend changes, you'll have to specify the changepoints manually as described here: https://facebook.github.io/prophet/docs/trend_changepoints.html

This looks like a hard time series to forecast. I don't see any seasonality to forecast forward, and it will be hard for Prophet to know what might happen in the future when such dramatic trend changes have been observed in the past.

**Comment by bletham** [comment]
If you have additional questions about this time series feel free to re-open this issue.
