### ISSUE TITLE
force silence

### ISSUE THREAD

**Issue by xinai57** [facebook/prophet#371]
how to remove the information of prophet? such as:

> Initial log joint probability = -18.6079
> Optimization terminated normally: 
>   Convergence detected: relative gradient magnitude is below tolerance

in lightGBM we can set verbose = -1 to silence, is there any similar parameter in prophet?

**Comment by robertdknight** [comment]
Redirect output to null when you launch the prophet script.

**Comment by robertdknight** [comment]
Redirect output to null when launching on [Linux](https://serverfault.com/questions/41964/how-to-hide-the-output-of-a-shell-application-in-linux), or [OSX](https://discussions.apple.com/thread/2742235?tstart=0), or [Windows](https://stackoverflow.com/questions/4507312/how-to-redirect-stderr-to-null-in-cmd-exe).

**Comment by bletham** [comment]
The output is coming from Stan and we don't have a good way to silence it. See #170, which also has links to the upstream issues. #223 provides a decorator that will suppress all of the output. Hopefully we'll be able to have a verbosity flag soon.

There are some info messages from prophet about setting seasonalities etc. that can be disabled by setting the logger level for fbprophet to logging.WARNING or higher.

**Comment by bletham** [comment]
I'm going to close this since it's covered by #170 and #223. Hopefully coming soon...
