### ISSUE TITLE
Give Negative weights to a particular holiday:

### ISSUE THREAD

**Issue by p9anand** [facebook/prophet#372]
Hi, 

I have a scenario in which a particular event has a negative impact. how can i provide this prior info to this particular event? This event does not present in the training data, you can assume it as rare event.

**Comment by bletham** [comment]
If it doesn't occur in the training data (so nothing to be fit) I think the best solution would be to make the adjustment outside of Prophet. The model is additive so you could just make a forecast, and then subtract your prior from that date in the forecast. Is that along the lines of what you mean?

**Comment by bletham** [comment]
I'm hoping that was helpful, if you have additional questions along these lines feel free to re-open.
