### ISSUE TITLE
Doubts in implementing Case of use : Asteroid impact forecasting 

### ISSUE THREAD

**Issue by SoyGema** [facebook/prophet#373]
Hello! 
Thanks for developing/contributing  this tool and put forecasting at scale in the hands of analysts and junior data science programmers. 
I am developing a case of use for this tool using NASA data-set of potential hazarous Asteroids and I have two questions 

**ANALYST IN THE LOOP**
- As I don´t have hourly data but different number of Asteroid E-moids observations, Should I normalize somehow into the same entries per day ? 
-Is the natural logarithm data-transformation applied to all forecasting methods ? Is it for ARIMA ? 

I am alredy with this results if you want to check . Please, if you see something wrong could you inform me? 
[https://github.com/SoyGema/Prophet_forecasting/blob/master/v2/Asteroid_Forecasting.ipynb](url)

Thanks so much for the time dedicated to solve this issue ! 👍

**Comment by bletham** [comment]
This looks like a challenging time series for Prophet. Prophet does really well with time series that have strong seasonalities and piecewise trends, neither of which I'd expect here. The model is also Gaussian additive noise, which doesn't look like the noise distribution here. I don't think I'd expect Prophet to perform better than some sort of rolling average.

For normalization, if the goal is to predict the number of observations each day then using daily observations should be the right thing to do.

We do not do a log transform of the data. Doing that could help with the noise distribution here.
