### ISSUE TITLE
Date mismatch in actual data and fbprophet fit data set

### ISSUE THREAD

**Issue by gourab4gd** [facebook/prophet#377]
Actual Train Data Starts with25-08-2012 00:00
![image](https://user-images.githubusercontent.com/25029404/33802873-f070c916-dda7-11e7-9112-b89d28e448b2.png)
But after using following code
![image](https://user-images.githubusercontent.com/25029404/33802916-e681ec2c-dda8-11e7-9e24-bd1525f96c57.png)

Date starts with  2012-01-09 00:00:00   in fbprophet fit dataset

![image](https://user-images.githubusercontent.com/25029404/33802898-7626a062-dda8-11e7-9c92-f4738b38d556.png)

why is it so?

Though I am using Hour as freq but there is a gap of 20 days in future_dates values

![image](https://user-images.githubusercontent.com/25029404/33802932-57cd3f26-dda9-11e7-91fa-742acd89e1ac.png)

I would be grateful if you solve my problem.

**Comment by bronsonelliott** [comment]
I just looks like it's not recognizing the timestamp properly when it flows through the model so maybe adding  **Train_Data['ds'] = pd.to_datetime(Train_Data['ds'])** after you rename the columns will help.

```
Train_Data = Train_Data.rename(columns = {'Datetime':'ds', 'Count':'y'})
Train_Data['ds'] = pd.to_datetime(Train_Data['ds'])
Train_Data.tail(5)
```

**Comment by gourab4gd** [comment]
Sir, 
Thank you very much for your reply. I would certainly  implement your advice.

**Comment by bletham** [comment]
Thanks @bronsonelliott!

pd.to_datetime also allows you to specify the format of your date, so you can be sure it is parsed correctly: https://pandas.pydata.org/pandas-docs/stable/generated/pandas.to_datetime.html
