### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 

### ISSUE THREAD

**Issue by sharmamoudgil87** [facebook/prophet#379]
Hi Githubers

hope everyone doing great !!
I have facing below issue while trying to installing a library on my machine.

Command "python setup.py egg_info" failed with error code 1 

Can you please help me out ?

Regards

**Comment by sidharthbolar** [comment]
Hello how are you installing it 
pip install  library_name?
Have you tried pip install --upgrade setuptools

Also check [this ](https://stackoverflow.com/questions/35991403/python-pip-install-gives-command-python-setup-py-egg-info-failed-with-error-c)

**Comment by sidharthbolar** [comment]
Also if  you have the option use conda
conda install -c conda-forge fbprophet worked for me

**Comment by sharmamoudgil87** [comment]
py -m pip install Basemap

**Comment by sharmamoudgil87** [comment]
none of them work .

**Comment by bletham** [comment]
It sounds like setuptools isn't working correctly. Try to `import setuptools` in python to see if it is there. You can also look here for how to get it set up: https://stackoverflow.com/questions/17886647/cant-install-via-pip-because-of-egg-info-error

**Comment by bletham** [comment]
I'm going to close this but if it is still an issue please re-open.
