### ISSUE TITLE
"Holidays" is too specific a name for events in time.

### ISSUE THREAD

**Issue by wjhrdy** [facebook/prophet#38]
> There are only two hard things in Computer Science: cache invalidation and naming things.

-- Phil Karlton

I made a package for creating regressors for forecasting using the forecasting package in R.
https://github.com/republicwireless-open/foregen

I use the word "events" instead of "holidays" so I am not prescriptive with how they are perceived.

**Comment by seanjtaylor** [comment]
@wjhrdy This is a good point.  It was definitely a result of our internal use-cases.  I'll add this name change to the 0.2 release milestone and we'll work on making it backward compatible by accepting both.

Nice job on your package!  If I had known about it we would have used it!

**Comment by bletham** [comment]
@seanjtaylor I'd favor leaving this as `holidays` in the code, and just updating the documentation to describe that this component is for 'holidays and other recurring events', or something along those lines. I certainly agree that `events` would have been a more appropriate choice, but maintaining support for both just seems like a pain. I'm guessing the typical usage for this feature is actual holidays, and people with non-holiday events would be able to tell from the documentation that this is the right interface. We also now have the `add_regressor` method which provides a more general interface, with a more general name.

**Comment by bletham** [comment]
I think with the `add_regressor` method there is now the more generally-termed interface for handling these types of things, and since it would be a pretty big disruption to remove/rename the holidays argument, I'm going to go ahead and not make this change unless anyone has any further objections.
