### ISSUE TITLE
Experience on using prophet (in a Kaggle comp)

### ISSUE THREAD

**Issue by DBCerigo** [facebook/prophet#383]
Hi, 

Just wanted to share a bit of my experience of using prophet, hopefully it's a tiny bit useful to its development at least. 

I used it for a Kaggle comp recently; forecasting 2 months of daily views for 145k wiki pages. My team came in the top 6% (62nd). 

Main feedback:
• API is incredibly usable
• Lack of being able to enforce lower bound (i.e. at 0) makes predictions unusable (in cases where possible outcomes are bounded as such). Due to Prophet linearly extrapolating downward trends, then it would overshoot. (Using the logistic growth model didn't seem to fix this.)

Brief explanation of how Prophet was used in our solution:
• Beating models which simply took the median of the most recent data were hard to beat. To the extend that even if Prophet got to see the data over which is was predicting, it would still lose badly compared to median over all 145k time series.
• We used Prophet to identify a specific subsets of the time series. Those which hard very strong seasonalities/autocorrelation. If Prophet could beat median models on average over all the train data, then this designated such a time series.
• If Prophet beat the median model over the test period (say Nov-Oct) in the previous year, then we used the data from that previous year as the prediction (shifted by a day or so to make the days of the week match up).
• We didn't actually use the output predictions of Prophet in the solution, due to the reasons above.

You can see a more detailed run through of exactly how Prophet was used in this comment on Kaggle https://www.kaggle.com/c/web-traffic-time-series-forecasting/discussion/39367#220948 (or search "Daniel Burkhardt Cerigo" in thread. 

Anyway - thanks for making this available and all the dev that went into it :) I'll be looking forward to using it again in the future hopefully.

**Comment by bletham** [comment]
Great, thanks! This issue with lower bound will definitely be addressed in the next version. This is awesome to hear that it was useful for the competition.
