### ISSUE TITLE
ModuleNotFoundError: No module named 'database'

### ISSUE THREAD

**Issue by sharmamoudgil87** [facebook/prophet#387]
Hi Github Guys,
I am just running a script and found an issue.Please check attached screen shot.
Regards
Anupam
![tasklist](https://user-images.githubusercontent.com/30086858/34171523-98d6286c-e514-11e7-8ad8-70d5ed8d54d5.PNG)

**Comment by teramonagi** [comment]
The screen shot said that you need to install database library.
I think you need to type the following commands on your console:
```
pip install database
```

I think that this is not prophet problem but the problem of your environment.

**Comment by lincoln1233** [comment]
Where did you even find that line from?  A quick search of PyPi, google, and Prophet shows no file called database...

I do not think this is a code issue.

**Comment by bletham** [comment]
Closing since not related to this package.

**Comment by darkhacknet** [comment]
> The screen shot said that you need to install database library. I think you need to type the following commands on your console:
> 
> ```
> pip install database
> ```
> 
> I think that this is not prophet problem but the problem of your environment.

this is not working, have you any other solution ? thanks in advance !
