### ISSUE TITLE
Produce daily forecast for specific period of time

### ISSUE THREAD

**Issue by bronsonelliott** [facebook/prophet#394]
I need to produce a daily forecast for a very specific portion of the year - **Dec 1 - July 31**.  The rest of the year is not needed as no sales are generated during that period.  I have 3 years of history for these sales.

How would I go about using Prophet to produce a daily forecast only for the required period of time?  Examples are always welcome.  

Thank you!

**Comment by bletham** [comment]
You can limit the forecast to the required period of time just by manually specifying the dates in the dataframe passed to `predict`. It would look like this:
```
future = pd.DataFrame({'ds': pd.date_range('2017-12-1', '2018-07-31')})
forecast = m.predict(future)
m.plot(forecast)
```

One thing to note is that with missing months the yearly seasonality curve is not well identified and sometimes can behave poorly. As long as you are only asking for predictions in 12-1 to 7-31 and you have data from 12-1 to 7-31 things might be OK.

If things look really bad, then you can try including data for the missing days, either with y=0 or linearly interpolated from the end of one period to the start of the next.

**Comment by bronsonelliott** [comment]
Thanks @bletham I'll give it a whirl and see how it goes.

**Comment by bletham** [comment]
If it didn't go well please re-open :-)
