### ISSUE TITLE
does it matter for uncontinuouse data??

### ISSUE THREAD

**Issue by amjiuzi** [facebook/prophet#403]
normally, my dataset should be 
```r
2014/12/31 10:00 | 8.761984
2014/12/31 11:00 | 5.677408
2014/12/31 12:00 | 7.197344
2014/12/31 13:00 | 5.677408
2014/12/31 14:00 | 6.169152
2014/12/31 15:00 | 5.677408
``` 
 but unfortunately, by sm reason, just left 
```r
2014/12/31 10:00 | 8.761984
2014/12/31 11:00 | 5.677408
2014/12/31 12:00 | 7.197344
 .
2014/12/31 14:00 | 6.169152
2014/12/31 15:00 | 5.677408
```
does it matter for my prediction?

**Comment by bletham** [comment]
No, Prophet is a continuous time model and missing data are not an issue. See https://facebook.github.io/prophet/docs/outliers.html for an example of fitting a time series after deleting some data.

**Comment by amjiuzi** [comment]
does it mean i should set my delete dates' y as NA ?

**Comment by bletham** [comment]
1. Either one would have the same effect, Prophet will just filter out rows with y NA: https://github.com/facebook/prophet/blob/master/R/R/prophet.R#L895
2. You can use `m <- prophet(df, weekly.seasonality=FALSE)` to disable weekly seasonality: https://github.com/facebook/prophet/blob/master/R/R/prophet.R#L34 . See here for a description of all of the available input arguments: https://cran.r-project.org/web/packages/prophet/prophet.pdf

**Comment by amjiuzi** [comment]
great!  thx

**Comment by amjiuzi** [comment]
i didn't see any param about quarters ,
Is it unnecessary to be set in prophet?

**Comment by rpanai** [comment]
@amjiuzi to add monthly seasonality you can check the firs example [here](https://facebook.github.io/prophet/docs/seasonality_and_holiday_effects.html)

@bletham about fillna 

> Either one would have the same effect, Prophet will just filter out rows with y NA: https://github.com/facebook/prophet/blob/master/R/R/prophet.R#L895
It's not the case when you are adding a regressor.

**Comment by Quantitative72** [comment]
What if my data is by year and quarter? Will Prophet still work?  Would I need to convert the year/quarter variable into a MM-DD-YYYY?

**Comment by bletham** [comment]
Date parsing is done by `pandas.to_datetime` in Python, which tries to guess what the right format is but won't always get it. In R it should be a date type in the column.

YYYY-MM-DD would be the best choice for the format. Besides that, Prophet should work fine for quarterly data, just see the caveat in the "Monthly Data" section here: https://facebook.github.io/prophet/docs/non-daily_data.html

**Comment by bletham** [comment]
This should be resolved but if not please re-open.
