### ISSUE TITLE
Predict multiple columns

### ISSUE THREAD

**Issue by Kalesberg** [facebook/prophet#404]
Is it possible to predict multiple columns in a CSV file?
I know prophet works well with `ds` and `y` in a CSV file.
In my case i have multiple `y`s to predict with same `ds`
How can i achieve my goal?

**Comment by bletham** [comment]
There isn't any true multi-output forecasting capability in Prophet. You could fit each one independently. You could also try fitting one, and then when you fit the next include the forecast for the previous as an extra regressor (see the bottom section at https://facebook.github.io/prophet/docs/seasonality_and_holiday_effects.html). This would be reasonable if you thought that the time series were linearly related, and if you felt you were able to more forecast the 1st more accurately than the 2nd. That's a pretty restrictive scenario but if it fits then give it a try.

True multi-output modeling is on the to-do list in #49, but will probably require some pretty substantial new development.

**Comment by Kalesberg** [comment]
thanks @bletham

**Comment by Saranya0721** [comment]
@bletham The link which is shared is not accessible. Can you please how to predict with multiple columns?

**Comment by bletham** [comment]
@Saranya0721 a documentation update moved the link to here: https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#additional-regressors

**Comment by cwilligv** [comment]
I know it's been years since this was posted but just for everyone's interest in this. Someone wrote a package around prophet called MultiProphet which I think aims at multi-output problems. Haven't tried it yet but it looks promising.
link here: [https://github.com/vonum/multi-prophet]
