### ISSUE TITLE
How to resolve "cannot find -lpthread" and -lc in Anaconda2 compiler_compat?

### ISSUE THREAD

**Issue by meammy** [facebook/prophet#408]
2.7 -o build/lib.linux-x86_64-2.7/common/sensors/compression.so
/home/aayush/anaconda2/compiler_compat/ld: cannot find -lpthread
/home/aayush/anaconda2/compiler_compat/ld: cannot find -lc
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1

**Comment by bletham** [comment]
Can you give some additional context for when this is happening? During fbprophet install?

**Comment by meammy** [comment]
Hi, Thanks for asking. Found answer at https://github.com/cocodataset/cocoapi/issues/94#issuecomment-350152998
