### ISSUE TITLE
Understanding fourier_order

### ISSUE THREAD

**Issue by Utsav2** [facebook/prophet#409]
Thanks for making the package!

As a beginner, i'm not sure what the fourier_order parameter can help with. Could someone shed some light on it in the docs?

**Comment by bletham** [comment]
We should put some examples of this in the documentation.

In short, a higher order means we have higher frequency terms and so will be able to fit more quickly-changing and complex seasonality patterns.

This figure from Wikipedia shows a Fourier series approximation to a square wave, with 1, 2, 3, and 4 components: https://en.wikipedia.org/wiki/Fourier_series#/media/File:Fourier_Series.svg . You can see that as the order is increased, the Fourier series is able to better represent the quick change of the square wave. The downside of using a very high order is just that it is more terms in the model and so overfitting becomes a risk.

The default of 10 typically is appropriate for seasonality on the scale of a year. If it looks like your seasonality effect changes very quickly and the Prophet seaosnality estimate is lagging and not able to capture it all, then try increasing the order.

**Comment by bletham** [comment]
Now described in documentation here: https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html
