### ISSUE TITLE
libstdc++.so.6: version `CXXABI_1.3.9' not found

### ISSUE THREAD

**Issue by dbur** [facebook/prophet#410]
On Ubuntu 16.04.3
Anaconda version 1.6.5
Python 3.6.3

https://facebook.github.io/prophet/docs/installation.html recommends running conda install gcc before installing Prophet. 

When running, from fbprophet import Prophet

Error message:
ImportError: /../.conda/envs/forecasting/lib/python3.6/site-packages/numexpr/../../../libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /../.conda/envs/forecasting/lib/python3.6/site-packages/matplotlib/_path.cpython-36m-x86_64-linux-gnu.so)

Resolved by conda uninstall gcc. Also fiddled with libgcc, not sure if installing/uninstalling/reinstalling that made a difference.

**Comment by bletham** [comment]
Thanks for the report. I haven't used Anaconda but multiple people had said that was necessary for getting pystan working on their setup so we added it to the docs. I wonder if it might be a matter of Anaconda version, here it looks like they had changes in gcc handling at version 5: https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html

**Comment by bletham** [comment]
I'm going to close this since I don't think there is anything to do here right now, but we can revisit the `conda install gcc` directive if more people start to experience this, and with later versions of Anaconda.
