### ISSUE TITLE
I get different forecast results for the same data sample in Python from R

### ISSUE THREAD

**Issue by omkay** [facebook/prophet#411]
I have the following dataframe which I want to apply forecasting on it

as displayed in Python

ds |  y
--- | ----
2017-11-05 00:00:00  | 1
2017-11-06 00:00:00  | 1
2017-11-09 00:00:00  | 1
2017-11-10 00:00:00  | 1
2017-11-20 00:00:00  | 1
2017-11-21 00:00:00  | 4
2017-11-24 00:00:00  | 1
2017-12-29 00:00:00  | 1

as displayed in R

ds |  y
--------- | -----
2017-11-05 | 1
2017-11-06 | 1
2017-11-09 | 1
2017-11-10 | 1
2017-11-20 | 1
2017-11-21 | 4
2017-11-24 | 1
2017-12-29 | 1

 I used python package to get the forecast dataframe but I got a weird results.
```python
  df['y'] = df['y'].apply(pd.to_numeric, errors='coerce', downcast='float')
  df['y'] = np.log(df.y)
  test_prophet = Prophet()
  test_prophet.fit(df)
  future = test_prophet.make_future_dataframe(periods = 30)
  forecast = test_prophet.predict(future)
  forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()
```
the output is

ds    |      yhat |  yhat_lower |  yhat_upper
------ | ---------- | --------------- | -----------------
2018-01-24  |   8.182315e+01  | 81.764908  | 81.880589
2018-01-25   |  1.532143e-10  | -0.061919   | 0.061369
2018-01-26   |  7.606360e-12  | -0.067280   | 0.065979
2018-01-27   |  5.145354e+01  | 51.381582 |  51.523097
2018-01-28   | -7.734343e-03   | -0.083440  |  0.065631

when I test the same data sample on R with the following code

```R
  df <- df %>%mutate(y = log(y))`
  test_prophet  <- prophet(df)`
  future <- make_future_dataframe(test_prophet, periods = 30)`
  forecast <- predict(test_prophet, future)`
  tail(forecast[c('ds', 'yhat', 'yhat_lower', 'yhat_upper')])`
```
I got the following results

ds    |     yhat   |   yhat_lower   |  yhat_upper
------ | ----------- | ----------------- | ----------------
2018-01-23 | 1.386296e+00 | 1.3857563516 | 1.3868219479
2018-01-24 | 1.153016e-01 | 0.1147678735 | 0.1158661610
2018-01-25 | 1.493997e-06 | -0.0005577810 | 0.0005245972
2018-01-26 | 1.244160e-06 | -0.0005267848 | 0.0005352099
2018-01-27 | 1.153017e-01 | 0.1147729043 | 0.1158397671
2018-01-28 | 1.910320e-06 | -0.0005024998 | 0.0005671054

when results from R makes more sense for my calculations I still don't understand why I get different results in python

**Comment by bletham** [comment]
The results can vary when the optimization doesn't terminate well. See #253 for a length discussion of this.
 On these really small somewhat pathological datasets the default L-BFGS optimizer can behave very poorly (see also #402). You will likely get more stable results by switching to the Newton algorithm, which is quite a bit slower on large datasets but you won't notice the difference here:
```
m.fit(df, algorithm='Newton')
```
```
m <- prophet(df, algorithm = 'Newton')
```

**Comment by bletham** [comment]
I hope that resolved the issue, but if not please re-open.

**Comment by yw2760** [comment]
Hi @bletham ,

Thanks for addressing this issue. I ran Prophet using python on both Mode and Databricks. Two results are different from each other. Setting algorithm to 'Newton' will solve part of the issue. However, there are still some discrepancies.

Also, I wonder when we should use 'Newton' or the default L-BFGS. Does Newton always work better?

Thanks so much.

**Comment by bletham** [comment]
I've only tried the Newton optimizer in cases where L-BFGS fails so I can't say for sure if it is generally more robust. It's definitely slower, which is why it isn't the default, but if you have found that it is providing better results then definitely use it.

You can know if it is providing better results by looking at the Stan output that is dumped to the console during model fitting. With the default optimizer, there is a column "log prob" that is the value that is being maximized. The final value is the best that it found. With the Newton optimizer, it will dump out to the screen "Log joint probability = ". Compare the final values of those numbers and that will tell you if one optimizer is finding better solutions than the other. (Most of the time they do not significantly differ).

**Comment by yw2760** [comment]
hi @bletham ,

Thanks so much for your response.
