### ISSUE TITLE
question on def logistic_growth_init(df):

### ISSUE THREAD

**Issue by gxperrin** [facebook/prophet#412]
A quick question on def logistic_growth_init(df)

Should we not write:
- Initialize the offset -
m = (L0 * df['t'].iloc[i1] - L1 * df['t'].iloc[i0]) / (L0 - L1)

instead of
- Initialize the offset -
m = L0 * T / (L0 - L1)

So that it can work without the assumption that df['t'].iloc[i0]==0, such as in def linear_growth_init(df)

Not a big deal however, great job to all the contributors.

Best,

Guillaume

**Comment by bletham** [comment]
Yeah, that'd be correct. We construct t so that t=0 at the min of df['ds'] so we're guaranteed that df['t'].iloc[i0]==0. But it could potentially avoid future bugs to not rely on that fact.

**Comment by bletham** [comment]
I'm going to close this since I don't see any immediate actions but we'll come back here if the way t is being defined ever needs to be adjusted.
