### ISSUE TITLE
Understanding of Trend

### ISSUE THREAD

**Issue by Kalesberg** [facebook/prophet#417]
I have been impressive so far with the capability of Prophet
During my current project, I have some ambiguous feeling about `trend` and `yhat`
After running `m.predict(future)` and printing out the future dataframe, I realised there are several columns.

I am concerned about `trend` and `yhat`.
- What is the difference between `trend` and `yhat`?
- In the trend graph below, what does each colour points represent? (`trend` or `yhat`) (black and blue)
![screen shot 2018-01-16 at 6 17 42 pm](https://user-images.githubusercontent.com/4900126/34993385-9d5e80f6-fae9-11e7-829e-1d3b4e4165be.png)
- In the trend graph below, my professor is asking about the `initial trend value` to adjust the trend graph. Is there any variable like that and if it is, will you explain briefly about it?
![screen shot 2018-01-16 at 6 21 53 pm](https://user-images.githubusercontent.com/4900126/34993571-32712c84-faea-11e7-9eaa-ddc5bf090b43.png)

Thank you for your help

**Comment by bletham** [comment]
`trend` would be useful if you wanted to understand where the different parts of the forecast are coming for, e.g. visually like with `m.plot_components(fcst)`. Like if `yhat` is increasing at a certain point because of seasonality or because of the underlying trend.

I'm not exactly sure what the initial trend value would be, but I think the first element of `yhat` would reasonably fit that description.

**Comment by Kalesberg** [comment]
@bletham 
- If we do not have enough history records that the future forecast is based on, i think we might need to have more control on the calculating the forecasts and give some initial values for the `yhat` of some future prediction data.
Is this possible?

- Also apart from other components like seasonality, holiday effects or regressions, can we add our own mathematical algorithm to change the forecast values?

**Comment by bletham** [comment]
* I'm not sure there is a good way to directly influence the forecast when you have little training data, other than to apply some function to the actual output.

* Those are the only types of components that are included in the model. You can apply whatever function you'd like to the forecast values to change them after fitting, but if you had some other algorithm that you wanted to incorporate along with these components in the fitting you'd have to edit the Stan code and implement it there.

**Comment by tetianakh** [comment]
Hi, I'm trying out prophet and I am really impressed with its capabilities. Where can I learn more about statistical algorithms it uses to compute components and make forecast?

**Comment by bletham** [comment]
@tetianakh the details are in the paper preprint here: https://peerj.com/preprints/3190v2.pdf

**Comment by bletham** [comment]
This question seems to be resolved but if there are more along this thread feel free to re-open.
