### ISSUE TITLE
python: can't open file 'setup.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by MaynulIslam** [facebook/prophet#419]
There it says,when im trying to install Django.What should i try, to fix it? My os is linux 

![ss](https://user-images.githubusercontent.com/25595362/35027703-5e8f98f4-fb7c-11e7-9c9f-dd4a50104da9.png)

**Comment by Sanjay-B** [comment]
This means that your setuptools are out of date.
You can fix this by doing: pip install --upgrade setuptools

**Comment by bletham** [comment]
Thanks @Sanjay-B and I hope that worked. I'm going to close the issue though since it isn't related to this package.

**Comment by MaynulIslam** [comment]
Thanks @Sanjay-B

**Comment by JanLechowskiTheFirst** [comment]
Update didnt help:
/usr/bin/python3.5: can't open file '/home/j/Desktop/PycharmProjects/untitled/DjangoEcommerce/src/setup.py': [Errno 2] No such file or directory

**Comment by fide1** [comment]
in terminal use the following commands:
<type pip>
if its hashed
<hash r>
then
<pip install --upgrade setuptools>

**Comment by shuttingdown** [comment]
Same problem appeared to me too, I tried this command:  sudo apt-get install python-setuptools ( installed ) on raspbian stretch, then -> sudo python setup.py build (previously I got error message, now didn't )  after that -> sudo python setup.py install ( installed without, that error message, that can't open file ). I hope it will help.

**Comment by organicnz** [comment]
1. I've installed that app.
```
Organic-2:~ organic$ brew install fail2ban
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core, homebrew/cask).
==> New Formulae
golang-migrate
==> Updated Formulae
citus                                              openrtsp

==> Downloading https://homebrew.bintray.com/bottles/fail2ban-0.10.3.1.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/91/91a2bf679c865a054a60cc9b980b1c5649649686d7e99a95b
######################################################################## 100.0%
==> Pouring fail2ban-0.10.3.1.mojave.bottle.tar.gz
==> Caveats
Before using Fail2Ban for the first time you should edit the jail
configuration and enable the jails that you want to use, for instance
ssh-ipfw. Also, make sure that they point to the correct configuration
path. I.e. on Mountain Lion the sshd logfile should point to
/var/log/system.log.

  * /usr/local/etc/fail2ban/jail.conf

The Fail2Ban wiki has two pages with instructions for macOS Server that
describes how to set up the Jails for the standard macOS Server
services for the respective releases.

  10.4: https://www.fail2ban.org/wiki/index.php/HOWTO_Mac_OS_X_Server_(10.4)
  10.5: https://www.fail2ban.org/wiki/index.php/HOWTO_Mac_OS_X_Server_(10.5)

Please do not forget to update your configuration files.
They are in /usr/local/etc/fail2ban.

To have launchd start fail2ban now and restart at startup:
  sudo brew services start fail2ban
==> Summary
🍺  /usr/local/Cellar/fail2ban/0.10.3.1: 497 files, 3.2MB
```
2. I could've run it and stop successfully. 
```
Organic-2:~ organic$ sudo brew services start fail2ban
Service `fail2ban` already started, use `brew services restart fail2ban` to restart.
```
```
Stopping `fail2ban`... (might take a while)
==> Successfully stopped `fail2ban` (label: homebrew.mxcl.fail2ban)
```
3.  Same error appeared.
```
Organic-2:~ organic$ sudo python setup.py build
Password:
python: can't open file 'setup.py': [Errno 2] No such file or directory
```
```
Organic-2:~ organic$ sudo python setup.py install
python: can't open file 'setup.py': [Errno 2] No such file or directory
```
4. Sorry I'm using Mac for developing. 

`/etc/fail2ban/jail.d this file is fully empty 
`
5. 
```
Best match: pyinotify 0.9.6
Processing pyinotify-0.9.6.tar.gz
Writing /tmp/easy_install-rt6zpgm0/pyinotify-0.9.6/setup.cfg
Running pyinotify-0.9.6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-rt6zpgm0/pyinotify-0.9.6/egg-dist-tmp-0c7ik4t7
inotify is not available on macosx-10.9-x86_64
error: Setup script exited with 
```

**Comment by shuttingdown** [comment]
I'm using linux, and unfortunatelly I know nothing about Mac systems, but I don't think that linux commands work on that system :-/.
I think the problem right now is that the Python Setuptools isn't installed, or did you installed previously? If I think well, then nowadays the " ez_setup.py " is: " easy_install.py " ( in position 4 ) or another method: https://pip.pypa.io/en/stable/installing/ ( get-pip.py also installs setuptools [2] and wheel if they are not already. setuptools is required to install source distributions. )

Quote from: Lingchao Cao
"1) Download ez_setup.py module from: https://pypi.python.org/pypi/setuptools
2) Open a Terminal
3) cd to the directory where you put the 'ez_setup.py'
4) type 'python ez_setup.py' and run it.
5) You should have it then."

**Comment by organicnz** [comment]
This command `apt-get` dosn't work on MacOS just in case.
What quoted from Lingchao Cao hasn't helped, but you can see that `pip install setuptools` has no issue with an instalation so far. Just couldn't be able to change the folder from `/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (40.2.0)` to `/anaconda3/lib/python3.7/site-packages`.

```
Organic-2:~ organic$ pip install setuptools
Requirement already satisfied: setuptools in /anaconda3/lib/python3.6/site-packages (39.1.0)
Organic-2:~ organic$ pip install setuptools --upgrade
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/66/e8/570bb5ca88a8bcd2a1db9c6246bb66615750663ffaaeada95b04ffe74e12/setuptools-40.2.0-py2.py3-none-any.whl
tensorflow 1.10.1 has requirement setuptools<=39.1.0, but you'll have setuptools 40.2.0 which is incompatible.
Installing collected packages: setuptools
  Found existing installation: setuptools 39.1.0
    Uninstalling setuptools-39.1.0:
      Successfully uninstalled setuptools-39.1.0
Successfully installed setuptools-40.2.0
Organic-2:~ organic$ pip3 install setuptools --upgrade
Requirement already up-to-date: setuptools in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (40.2.0)
```

**Comment by kavyaSri5** [comment]
Traceback (most recent call last):
  File "ifmgr_cisco_xr.py", line 3, in <module>
    from ydk.services import NetconfService, Datastore
  File "/usr/lib64/python2.7/site-packages/ydk/services/__init__.py", line 17, in <module>
    from .codec_service import CodecService
  File "/usr/lib64/python2.7/site-packages/ydk/services/codec_service.py", line 21, in <module>
    from ydk.entity_utils import get_data_node_from_entity as _get_data_node_from_entity
  File "/usr/lib64/python2.7/site-packages/ydk/entity_utils/__init__.py", line 17, in <module>
    from ydk.ext.entity_utils import get_data_node_from_entity
  File "/usr/lib64/python2.7/site-packages/ydk/exthook.py", line 87, in load_module
    raise ImportError('No module named %s' % fullname)
ImportError: No module named ydk.ext.entity_utils


getting this errorr while ia m trying to print system up time .can someone kindly help me for resolving this ??

**Comment by areejabbas1** [comment]
(venv) admin22@mediacore:~$ sudo python setup.py install
python: can't open file 'setup.py': [Errno 2] No such file or directory
(venv) admin22@mediacore:~$ sudo python setup.py install
python: can't open file 'setup.py': [Errno 2] No such file or directory
(venv) admin22@mediacore:~$ pip install --upgrade setuptools
Requirement already up-to-date: setuptools in ./venv/lib/python3.5/site-packages (41.0.1)
i doing upgrade to setuptool put cant install setup.py

**Comment by sarahab23** [comment]
> (venv) admin22@mediacore:~$ sudo python setup.py install python: can't open file 'setup.py': [Errno 2] No such file or directory (venv) admin22@mediacore:~$ sudo python setup.py install
> python: can't open file 'setup.py': [Errno 2] No such file or directory
> (venv) admin22@mediacore:~$ pip install --upgrade setuptools
> Requirement already up-to-date: setuptools in ./venv/lib/python3.5/site-packages (41.0.1)
> i doing upgrade to setuptool put cant install setup.py


Same for me :(

**Comment by areejabbas1** [comment]
so  how we can solve it?

**Comment by chaithanya121** [comment]
python: can't open file 'QRLJacker.py': [Errno 2] No such file or directory 

plz solve me

**Comment by Mumtaz22** [comment]
$ chmod +× hackinsta.py
chmod: hackinsta.py: No such file or directory

**Comment by Clarechioma** [comment]
i need help pls on this
C:\Users\CCUICT3\AppData\Local\Programs\Python\Python36\python.exe: can't open file './setup.py': [Errno 2] No such file or directory

**Comment by arnabtanu** [comment]
C:\Users\user\AppData\Local\Programs\Python\Python38\python.exe: can't open file 'setup.py': [Errno 2] No such file or directory
same error plz help

**Comment by Dhairyapbt** [comment]
> Tried different approaches to solve this issue but unsuccessfully.
> 
> ```
> Organic:/ organic$ sudo pip install --upgrade setuptools
> Password:***
> The directory '/Users/organic/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> The directory '/Users/organic/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> Requirement already up-to-date: setuptools in /Library/Python/2.7/site-packages (40.2.0)
> ```
> 
> ```
> Organic:~ organic$ sudo python setup.py
> (null): can't open file 'setup.py': [Errno 2] No such file or directory 
> `how did you get the solution?

**Comment by Danish391** [comment]
I want to install routersploit but 
python rsf.py 
shows error
![Screenshot_1611575089519](https://user-images.githubusercontent.com/77969619/105703772-8e463700-5f2f-11eb-8eed-859ad764980a.jpg)
plzz help me to fix it

**Comment by AndreyR62020** [comment]
Help how to fi
![2021-10-04_13-55-33](https://user-images.githubusercontent.com/88287240/135831417-e3a6fcee-e263-4d46-816f-fd59b1ec1c79.png)
x

**Comment by leibaogit** [comment]
Need to downgrade the pip version. I'm using python 2.7, initally installed the pip 20 version, it also encountered the same error. Then I downgrade the pip to version 9, it works.

```
$ pip --version
pip 20.3.4 from /home/vagrant/.local/lib/python2.7/site-packages/pip (python 2.7)


$ sudo -H pip install grpcio
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting grpcio
  Using cached grpcio-1.41.1.tar.gz (21.2 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ZF8rcN/grpcio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ZF8rcN/grpcio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-yyErzP
         cwd: /tmp/pip-install-ZF8rcN/grpcio/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ZF8rcN/grpcio/setup.py", line 256, in <module>
        if check_linker_need_libatomic():
      File "/tmp/pip-install-ZF8rcN/grpcio/setup.py", line 206, in check_linker_need_libatomic
        stderr=PIPE)
      File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
        errread, errwrite)
      File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
vagrant@lab1-qz1-sr1-rk01-s1:~$ python setup.py egg_info
python: can't open file 'setup.py': [Errno 2] No such file or directory
```

```
$ pip --version
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)

$ pip install grpcio
Collecting grpcio
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/bd/81/6c704c002a992b9d6466c739e3e7687e0bb2365d8cd63d7fc8e95d502cb6/grpcio-1.41.1.tar.gz (21.2MB)
    100% |████████████████████████████████| 21.2MB 78kB/s
Collecting six>=1.5.2 (from grpcio)
  Downloading https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl
Collecting enum34>=1.0.4 (from grpcio)
  Downloading https://files.pythonhosted.org/packages/6f/2c/a9386903ece2ea85e9807e0e062174dc26fdce8b05f216d00491be29fad5/enum34-1.1.10-py2-none-any.whl
Collecting futures>=2.2.0 (from grpcio)
  Downloading https://files.pythonhosted.org/packages/d8/a6/f46ae3f1da0cd4361c344888f59ec2f5785e69c872e175a748ef6071cdb5/futures-3.3.0-py2-none-any.whl
Building wheels for collected packages: grpcio
  Running setup.py bdist_wheel for grpcio ... |^|^done
  Stored in directory: /home/vagrant/.cache/pip/wheels/c4/93/65/a16057b837ece5b0b2a2a16253dfa7a649352db2e7370179e8
Successfully built grpcio
Installing collected packages: six, enum34, futures, grpcio
Successfully installed enum34-1.1.10 futures-3.3.0 grpcio-1.41.1 six-1.16.0
```

**Comment by Hudaka** [comment]
Same issue here I tried downgrading pip still did't help

![Screenshot 2022-05-18 at 17 40 33](https://user-images.githubusercontent.com/55352118/169084491-ec9d2fb1-d316-4e85-a52c-27e067c0e6b1.png)

**Comment by ashimmohamto1989** [comment]
python3: can't open file '/home/kali/infoga.py': [Errno 2] No such file or directory
E: Unable to locate package setup.py
E: Couldn't find any package by glob 'setup.py'

**Comment by nikunjsonule** [comment]
> i need help pls on this C:\Users\CCUICT3\AppData\Local\Programs\Python\Python36\python.exe: can't open file './setup.py': [Errno 2] No such file or directory

Did you resolve the issue ?

**Comment by fatita99** [comment]
> Thanks @Sanjay-B
hello plz can u tell me details of how to solve this problm

**Comment by jediApe** [comment]
Thank you!
I had to updated version I guess I had to do it again?

**Comment by CANTIKAKATIANDAGHO06** [comment]
<img width="471" alt="image" src="https://github.com/facebook/prophet/assets/103124539/c0c650f9-faff-47b6-82cc-230efde31e72">

please help how to solve this?

**Comment by soheil-jj** [comment]
Building compiled components in cryptography
[INFO]:    -> directory context /home/soheil/Desktop/App_encrypt/App/Buildozer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/cryptography/arm64-v8a__ndk_target_21/cryptography
[DEBUG]:   -> running python3 setup.py build_ext -v
[DEBUG]:   	/home/soheil/Desktop/App_encrypt/App/Buildozer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3: can't open file '/home/soheil/Desktop/App_encrypt/App/Buildozer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/cryptography/arm64-v8a__ndk_target_21/cryptography/setup.py': [Errno 2] No such file or directory
Exception in thread background thread for pid 76770:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/soheil/Desktop/App_encrypt/lib/python3.10/site-packages/sh.py", line 1641, in wrap
    fn(*rgs, **kwargs)
  File "/home/soheil/Desktop/App_encrypt/lib/python3.10/site-packages/sh.py", line 2569, in background_thread
    handle_exit_code(exit_code)
  File "/home/soheil/Desktop/App_encrypt/lib/python3.10/site-packages/sh.py", line 2269, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/soheil/Desktop/App_encrypt/lib/python3.10/site-packages/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2: 

  RAN: /home/soheil/Desktop/App_encrypt/App/Buildozer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3 setup.py build_ext -v

  STDOUT:
/home/soheil/Desktop/App_encrypt/App/Buildozer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3: can't open file '/home/soheil/Desktop/App_encrypt/App/Buildozer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/cryptography/arm64-v8a__ndk_target_21/cryptography/setup.py': [Errno 2] No such file or directory


  STDERR:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/soheil/Desktop/App_encrypt/App/Buildozer/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1256, in <module>
    main()
  File "/home/soheil/Desktop/App_encrypt/App/Buildozer/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/home/soheil/Desktop/App_encrypt/App/Buildozer/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 685, in __init__
    getattr(self, command)(args)
  File "/home/soheil/Desktop/App_encrypt/App/Buildozer/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 104, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/soheil/Desktop/App_encrypt/App/Buildozer/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 163, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx,
  File "/home/soheil/Desktop/App_encrypt/App/Buildozer/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 504, in build_recipes
    recipe.build_arch(arch)
  File "/home/soheil/Desktop/App_encrypt/App/Buildozer/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 983, in build_arch
    self.build_compiled_components(arch)
  File "/home/soheil/Desktop/App_encrypt/App/Buildozer/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 994, in build_compiled_components
    shprint(hostpython, 'setup.py', self.build_cmd, '-v',
  File "/home/soheil/Desktop/App_encrypt/App/Buildozer/.buildozer/android/platform/python-for-android/pythonforandroid/logger.py", line 167, in shprint
    for line in output:
  File "/home/soheil/Desktop/App_encrypt/lib/python3.10/site-packages/sh.py", line 915, in next
    self.wait()
  File "/home/soheil/Desktop/App_encrypt/lib/python3.10/site-packages/sh.py", line 845, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/soheil/Desktop/App_encrypt/lib/python3.10/site-packages/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2: 

  RAN: /home/soheil/Desktop/App_encrypt/App/Buildozer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3 setup.py build_ext -v

  STDOUT:
/home/soheil/Desktop/App_encrypt/App/Buildozer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3: can't open file '/home/soheil/Desktop/App_encrypt/App/Buildozer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/cryptography/arm64-v8a__ndk_target_21/cryptography/setup.py': [Errno 2] No such file or directory


  STDERR:

# Command failed: ['/home/soheil/Desktop/App_encrypt/bin/python3', '-m', 'pythonforandroid.toolchain', 'create', '--dist_name=com.AndroidDE', '--bootstrap=sdl2', '--requirements=python3,kivy==2.3.0,cryptography==44.0.0', '--arch=arm64-v8a', '--arch=armeabi-v7a', '--copy-libs', '--color=always', '--storage-dir=/home/soheil/Desktop/App_encrypt/App/Buildozer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a', '--ndk-api=21', '--ignore-setup-py', '--debug']
# ENVIRONMENT:
#     SHELL = '/bin/bash'
#     SESSION_MANAGER = 'local/soheil-UX310UQK:@/tmp/.ICE-unix/1481,unix/soheil-UX310UQK:/tmp/.ICE-unix/1481'
#     QT_ACCESSIBILITY = '1'
#     COLORTERM = 'truecolor'
#     XDG_CONFIG_DIRS = '/etc/xdg/xdg-ubuntu:/etc/xdg'
#     SSH_AGENT_LAUNCHER = 'gnome-keyring'
#     XDG_MENU_PREFIX = 'gnome-'
#     GNOME_DESKTOP_SESSION_ID = 'this-is-deprecated'
#     LC_ADDRESS = 'en_US.UTF-8'
#     GNOME_SHELL_SESSION_MODE = 'ubuntu'
#     LC_NAME = 'en_US.UTF-8'
#     SSH_AUTH_SOCK = '/run/user/1000/keyring/ssh'
#     XMODIFIERS = '@im=ibus'
#     DESKTOP_SESSION = 'ubuntu'
#     LC_MONETARY = 'en_US.UTF-8'
#     GTK_MODULES = 'gail:atk-bridge'
#     PWD = '/home/soheil/Desktop/App_encrypt/App/Buildozer'
#     LOGNAME = 'soheil'
#     XDG_SESSION_DESKTOP = 'ubuntu'
#     XDG_SESSION_TYPE = 'wayland'
#     SYSTEMD_EXEC_PID = '1514'
#     XAUTHORITY = '/run/user/1000/.mutter-Xwaylandauth.CE8FZ2'
#     HOME = '/home/soheil'
#     USERNAME = 'soheil'
#     IM_CONFIG_PHASE = '1'
#     LC_PAPER = 'en_US.UTF-8'
#     LANG = 'en_US.UTF-8'
#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
#     XDG_CURRENT_DESKTOP = 'ubuntu:GNOME'
#     VIRTUAL_ENV = '/home/soheil/Desktop/App_encrypt'
#     VTE_VERSION = '6800'
#     WAYLAND_DISPLAY = 'wayland-0'
#     GNOME_TERMINAL_SCREEN = '/org/gnome/Terminal/screen/ad3de639_16df_4929_a7b3_08c3d3491e6b'
#     GNOME_SETUP_DISPLAY = ':1'
#     LESSCLOSE = '/usr/bin/lesspipe %s %s'
#     XDG_SESSION_CLASS = 'user'
#     TERM = 'xterm-256color'
#     LC_IDENTIFICATION = 'en_US.UTF-8'
#     LESSOPEN = '| /usr/bin/lesspipe %s'
#     USER = 'soheil'
#     GNOME_TERMINAL_SERVICE = ':1.223'
#     DISPLAY = ':0'
#     SHLVL = '1'
#     LC_TELEPHONE = 'en_US.UTF-8'
#     QT_IM_MODULE = 'ibus'
#     LC_MEASUREMENT = 'en_US.UTF-8'
#     PAPERSIZE = 'letter'
#     VIRTUAL_ENV_PROMPT = '(App_encrypt) '
#     XDG_RUNTIME_DIR = '/run/user/1000'
#     PS1 = ('(App_encrypt) \\[\\e]0;\\u@\\h: '
 '\\w\\a\\]${debian_chroot:+($debian_chroot)}\\[\\033[01;32m\\]\\u@\\h\\[\\033[00m\\]:\\[\\033[01;34m\\]\\w\\[\\033[00m\\]\\$ ')
#     LC_TIME = 'en_US.UTF-8'
#     XDG_DATA_DIRS = '/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop'
#     PATH = '/home/soheil/.buildozer/android/platform/apache-ant-1.9.4/bin:/home/soheil/Desktop/App_encrypt/bin:/home/soheil/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin'
#     GDMSESSION = 'ubuntu'
#     DBUS_SESSION_BUS_ADDRESS = 'unix:path=/run/user/1000/bus'
#     LC_NUMERIC = 'en_US.UTF-8'
#     OLDPWD = '/home/soheil'
#     _ = '/home/soheil/Desktop/App_encrypt/bin/buildozer'
#     PACKAGES_PATH = '/home/soheil/.buildozer/android/packages'
#     ANDROIDSDK = '/home/soheil/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/home/soheil/.buildozer/android/platform/android-ndk-r25b'
#     ANDROIDAPI = '31'
#     ANDROIDMINAPI = '21'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

please help how to solve this?
