### ISSUE TITLE
Meaning of y-axis in component plot

### ISSUE THREAD

**Issue by Baschdl** [facebook/prophet#422]
I'm was wondering what the meaning of the y-axis in the component plot as in the example from the quick start is. Does it show the corresponding relative factor for each component or is it the absolute change in the value which was learned by the model?
![quick_start_14_0](https://user-images.githubusercontent.com/3034832/35184804-9a4ece84-fdfa-11e7-9d96-ccec5203a484.png)

**Comment by WGierke** [comment]
Apparently it's the unit of the data that was learned. This would also coincide with the known change rates detected by ADAC, RWI etc.

**Comment by bletham** [comment]
It's an additive model so it'd be the absolute change relative to just-trend.

So, the value of 0.3 on Monday means that "yhat" will be 0.3 larger on Monday just due to weekly effects. Does that answer your question?

**Comment by Baschdl** [comment]
Yes, thank you very much.
