### ISSUE TITLE
pystan issubdtype warning

### ISSUE THREAD

**Issue by likicv** [facebook/prophet#427]
Hi,
When running

>>> m = Prophet()
>>> m.fit(df)

I'm getting a warning from pystan:

/usr/local/lib/python3.6/site-packages/pystan/misc.py:399: FutureWarning: Conver
sion of the second argument of issubdtype from `float` to `np.floating` is depre
cated. In future, it will be treated as `np.float64 == np.dtype(float).type`.

(I believe all my packages are up to date).

Regards,
Vlad

**Comment by bletham** [comment]
Confirmed in pystan 2.17.1.0. We'll have to fix before it breaks.

**Comment by bletham** [comment]
I see, at first I had thought that pystan was throwing a deprecation warning for something that prophet was doing, but it  is actually numpy throwing the deprecation warning for something that pystan is doing. In particular,
https://github.com/stan-dev/pystan/blob/develop/pystan/misc.py#L399
was deprecated in numpy 1.14 (https://github.com/numpy/numpy/pull/9505).

This is an upstream issue so nothing to do here.
