### ISSUE TITLE
El Capitan release on CRAN is still 0.1.1

### ISSUE THREAD

**Issue by hideaki** [facebook/prophet#429]
Hi, thank you for this innovative algorithm!
I noticed that El Capitan release on CRAN is still 0.1.1 while other platforms has 0.2.1. Will it be updated to 0.2.1?
https://cran.r-project.org/web/packages/prophet/index.html

**Comment by bletham** [comment]
Oh I didn't realize that. I guess this is a consequence of #350, which I didn't realize had consequences.

If anybody has the ability to install 0.2.1 from source and see why the logistic_floor test is failing (https://www.r-project.org/nosvn/R.check/r-release-osx-x86_64/prophet-00check.html says it is but doesn't show any error message) that would be extremely helpful.

I'll find a mac I can borrow and can try to debug asap if noone gets to it before me.

**Comment by bletham** [comment]
This is resolved.
