### ISSUE TITLE
trend rate changepoint plot in documentation example

### ISSUE THREAD

**Issue by jzicker** [facebook/prophet#435]
I am using python implementation.  Really appreciate all the work that has been put into prophet.   In the documentation on changepoints do you have code examples to create the first two plots that you can share?

thanks

**Comment by bletham** [comment]
All of the documentation is generated from IPython notebooks, so it is available here:
https://github.com/facebook/prophet/blob/master/notebooks/trend_changepoints.ipynb

Those particular figures were generated only in Python but if you need them in R I hope the translation should be fairly straightforward. Actually in the v0.3 branch here, the R version has a tool for layering the locations of significant changepoints that may also be of interest if you need it in R: https://github.com/facebook/prophet/blob/v0.3/R/R/utils.R

**Comment by jzicker** [comment]
thanks for the speedy response
