### ISSUE TITLE
Error: could not determine PostgreSQL version from '10.1'

### ISSUE THREAD

**Issue by rahul6612** [facebook/prophet#441]
i wand to push my django app on heroku and i installed my all rquirements.txt file which given below
asgiref==1.1.2
asn1crypto==0.24.0
attrs==17.4.0
autobahn==17.10.1
Automat==0.6.0
beautifulsoup4==4.6.0
braintree==3.19.0
certifi==2017.11.5
cffi==1.11.2
chardet==3.0.4
chromedriver-installer==0.0.6
constantly==15.1.0
cryptography==2.1.4
defusedxml==0.5.0
dj-database-url==0.4.2
Django==1.11
django-allauth==0.33.0
django-amp-tools==0.1.1
django-crispy-forms==1.5.0
django-filter==0.11.0
django-registration-redux==1.2
djangorestframework==3.7.1
gTTS==1.2.2
gTTS-token==1.1.1
gunicorn==19.7.1
hyperlink==17.3.1
idna==2.6
incremental==17.5.0
numpy==1.13.3
oauthlib==2.0.4
opencv-python==3.3.0.10
Pillow==5.0.0
psycopg2==2.7.4
PyAudio==0.2.11
pycparser==2.18
PyJWT==1.5.3
pyOpenSSL==17.5.0
python-decouple==3.1
python-social-auth==0.3.6
python3-openid==3.1.0
pyttsx==1.1
pytz==2017.3
requests==2.7.0
requests-oauthlib==0.8.0
selenium==3.7.0
six==1.11.0
social-auth-app-django==1.2.0
social-auth-core==1.4.0
SpeechRecognition==3.7.1
txaio==2.8.2
urllib3==1.22
virtualenv==15.1.0
whitenoise==3.3.1
zope.interface==4.4.3

after this i run this command "git-push heroku maste"
i am getting
Error: could not determine PostgreSQL version from '10.1'
remote:
remote: ----------------------------------------
remote: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-07yg4mvk/psycopg2/
remote: ! Push rejected, failed to compile Python app.

i dont have to much idea about it so please tell me the solution

**Comment by bletham** [comment]
This isn't the right package.

**Comment by rahul6612** [comment]
then which version is right

**Comment by rahul6612** [comment]
tried lot but didn't get the solution
