### ISSUE TITLE
I am getting this error tell me how to solve it

### ISSUE THREAD

**Issue by ankit007im** [facebook/prophet#443]
$ py -3 -m pip install asciinema
Collecting asciinema
  Using cached asciinema-2.0.0.tar.gz
Installing collected packages: asciinema
  Running setup.py install for asciinema: started
    Running setup.py install for asciinema: finished with status 'error'
    Complete output from command "C:\Program Files\Python37\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\TECHCE~1\\AppData\\Local\\Temp\\pip-build-h379lfh4\\asciinema\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\TECHCE~1\AppData\Local\Temp\pip-aw0qx0qk-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\asciinema
    copying asciinema\api.py -> build\lib\asciinema
    copying asciinema\config.py -> build\lib\asciinema
    copying asciinema\http_adapter.py -> build\lib\asciinema
    copying asciinema\player.py -> build\lib\asciinema
    copying asciinema\pty_recorder.py -> build\lib\asciinema
    copying asciinema\term.py -> build\lib\asciinema
    copying asciinema\urllib_http_adapter.py -> build\lib\asciinema
    copying asciinema\__init__.py -> build\lib\asciinema
    copying asciinema\__main__.py -> build\lib\asciinema
    creating build\lib\asciinema\commands
    copying asciinema\commands\auth.py -> build\lib\asciinema\commands
    copying asciinema\commands\cat.py -> build\lib\asciinema\commands
    copying asciinema\commands\command.py -> build\lib\asciinema\commands
    copying asciinema\commands\play.py -> build\lib\asciinema\commands
    copying asciinema\commands\record.py -> build\lib\asciinema\commands
    copying asciinema\commands\upload.py -> build\lib\asciinema\commands
    copying asciinema\commands\__init__.py -> build\lib\asciinema\commands
    creating build\lib\asciinema\asciicast
    copying asciinema\asciicast\frames.py -> build\lib\asciinema\asciicast
    copying asciinema\asciicast\raw.py -> build\lib\asciinema\asciicast
    copying asciinema\asciicast\v1.py -> build\lib\asciinema\asciicast
    copying asciinema\asciicast\v2.py -> build\lib\asciinema\asciicast
    copying asciinema\asciicast\__init__.py -> build\lib\asciinema\asciicast
    running install_lib
    creating C:\Program Files\Python37\Lib\site-packages\asciinema
    error: could not create 'C:\Program Files\Python37\Lib\site-packages\asciinema': Access is denied

    ----------------------------------------
Command ""C:\Program Files\Python37\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\TECHCE~1\\AppData\\Local\\Temp\\pip-build-h379lfh4\\asciinema\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\TECHCE~1\AppData\Local\Temp\pip-aw0qx0qk-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\TECHCE~1\AppData\Local\Temp\pip-build-h379lfh4\asciinema\

**Comment by bletham** [comment]
This is for a different package.
