### ISSUE TITLE
Prophet hangs while plotting in AWS EMR with jupyter

### ISSUE THREAD

**Issue by AndrewKL** [facebook/prophet#451]
Hey Friends,

I recently installed jupyter on an AWS EMR cluster and discovered that while the core forecasting components of the library work successfully, prophet hangs when plotting the results.  I've attach the note book below. I suspect that this is due to the matplotlib backend not working because when I switch to the 'agg' backend the plot function completes but nothing is shown.  When i import prophet in the python cli i get.

```
>>> import pandas as pd
>>> import numpy as np
>>> from fbprophet import Prophet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/fbprophet/__init__.py", line 8, in <module>
    from fbprophet.forecaster import Prophet
  File "/usr/local/lib/python2.7/site-packages/fbprophet/forecaster.py", line 20, in <module>
    from matplotlib import pyplot as plt
  File "/usr/local/lib64/python2.7/site-packages/matplotlib/pyplot.py", line 116, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/lib64/python2.7/site-packages/matplotlib/backends/__init__.py", line 60, in pylab_setup
    [backend_name], 0)
  File "/usr/local/lib64/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from six.moves import tkinter as Tk
  File "/usr/local/lib/python2.7/site-packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/usr/local/lib/python2.7/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/local/lib/python2.7/site-packages/six.py", line 82, in _import_module
    __import__(name)
ImportError: No module named Tkinter
```

Which suggests that this may be due to the lack of certain libraries on the default AWS EMR master node instance.

Has anyone managed to get prophet to play nicely with AWS EMR yet?

jupyter+prophet was installed with this and the following 

https://aws.amazon.com/blogs/big-data/running-jupyter-notebook-and-jupyterhub-on-amazon-emr/

> sudo pip install fbprophet

**Comment by AndrewKL** [comment]
Jupyter output


```python
#import matplotlib
#matplotlib.use('agg',warn=True, force=True) # this will cause 
import pandas as pd
import numpy as np
from fbprophet import Prophet
df = pd.read_csv('/home/hadoop/example_wp_peyton_manning.csv')
df['y'] = np.log(df['y'])
df.head()
df.tail()
```




<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>ds</th>
      <th>y</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>2900</th>
      <td>2016-01-16</td>
      <td>7.817223</td>
    </tr>
    <tr>
      <th>2901</th>
      <td>2016-01-17</td>
      <td>9.273878</td>
    </tr>
    <tr>
      <th>2902</th>
      <td>2016-01-18</td>
      <td>10.333775</td>
    </tr>
    <tr>
      <th>2903</th>
      <td>2016-01-19</td>
      <td>9.125871</td>
    </tr>
    <tr>
      <th>2904</th>
      <td>2016-01-20</td>
      <td>8.891374</td>
    </tr>
  </tbody>
</table>
</div>




```python
m = Prophet(daily_seasonality=True)
m.fit(df);
```


```python
future = m.make_future_dataframe(periods=365)
future.tail()
```




<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>ds</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>3265</th>
      <td>2017-01-15</td>
    </tr>
    <tr>
      <th>3266</th>
      <td>2017-01-16</td>
    </tr>
    <tr>
      <th>3267</th>
      <td>2017-01-17</td>
    </tr>
    <tr>
      <th>3268</th>
      <td>2017-01-18</td>
    </tr>
    <tr>
      <th>3269</th>
      <td>2017-01-19</td>
    </tr>
  </tbody>
</table>
</div>




```python
forecast = m.predict(future)
forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()
```




<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>ds</th>
      <th>yhat</th>
      <th>yhat_lower</th>
      <th>yhat_upper</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>3265</th>
      <td>2017-01-15</td>
      <td>8.211682</td>
      <td>7.519712</td>
      <td>8.919276</td>
    </tr>
    <tr>
      <th>3266</th>
      <td>2017-01-16</td>
      <td>8.536762</td>
      <td>7.843319</td>
      <td>9.248431</td>
    </tr>
    <tr>
      <th>3267</th>
      <td>2017-01-17</td>
      <td>8.324179</td>
      <td>7.583607</td>
      <td>9.001573</td>
    </tr>
    <tr>
      <th>3268</th>
      <td>2017-01-18</td>
      <td>8.156803</td>
      <td>7.404435</td>
      <td>8.860569</td>
    </tr>
    <tr>
      <th>3269</th>
      <td>2017-01-19</td>
      <td>8.168738</td>
      <td>7.502191</td>
      <td>8.867415</td>
    </tr>
  </tbody>
</table>
</div>




```python
m.plot(forecast);#hangs
```


```python
m.plot_components(forecast);#also hangs
```

**Comment by bletham** [comment]
My understanding is that the `agg` backend creates the plot but will not show anything because it is non-interactive. You should, however, be able to do something like
```
fig = m.plot(forecast)
fig.savefig('figure.png')
```
with the `agg` backend. For interactivity I guess you'll have to install Tkinter or an alternative interactive backend.

**Comment by AndrewKL** [comment]
Quick update:  We found the bug.  It turns out we had a proxy in front of jupyter that was silently dropping websocket frames that were larger than 16KB.  Fixing this magically made the graphs reappear!
