### ISSUE TITLE
Understanding the parameters in the research paper

### ISSUE THREAD

**Issue by yusssk** [facebook/prophet#452]
Hello guys, i've been reading the research paper and under the saturating trend module (logistic growth) as a beginner, i am unable to understand what (m = offset parameter) represents and how (k= base growth rate) is calculated?

**Comment by bletham** [comment]
The wikipedia article here has a description of the parameters with an illustration: https://en.wikipedia.org/wiki/Logistic_function

The offset parameter `m` is in wikipedia the `x0`, the value of the midpoint, where the slope switches from increasing to decreasing.

The growth rate `k` is in wikipedia also `k` and determines how steep the curve is.

That is what the parameters mean - how they are actually estimated is just that we find the values that best fit the data. Does that answer your question?
