### ISSUE TITLE
Dealing with spikes

### ISSUE THREAD

**Issue by Yiyio** [facebook/prophet#455]
Many times there are spikes in times series data, that pretty much repeat every year/season/etc. This is very common when forecasting sales data (christmas periods, a certain sale the company does every year at around the same time, and so on).

So far I haven't been able to obtain good predictions for these spikes. I have 3 years of daily sales data, with yearly seasonality. I have added the spike periods as holidays and it improves it somewhat, but the spike is still about 5 times higher than the prediction. I've adjusted the holidays.prior.scale but it also didn't help much. Any tips, something I could look into, etc.? Or is prophet not a good option for this?

**Comment by vhpietil** [comment]
Hi,
could you share your data and/or plot your fit and predictions? It would be easier to comment on your problem.

Prophet can be very good predicting spikes if future spikes are about the same size as those in history. If the size of the spikes varies alot, the predictions can be inaccurate.

**Comment by Yiyio** [comment]
Hi @vhpietil,

I am attaching an example. as you can see it falls a bit short

These are the options I have used
```
m <- prophet(df, yearly.seasonality=TRUE, holidays = christmasperiod)

future <- make_future_dataframe(m, periods = 365)

forecast <- predict(m, future)

plot(m, forecast)
```
![image](https://user-images.githubusercontent.com/8472022/36539181-36047dac-17d6-11e8-8d7d-c6983a6d69f5.png)

**Comment by vhpietil** [comment]
Can you share the data (df and christmasperiod)? I can come up with anything without trying with the data. It seems weird that those spikes are not forecasted at all

**Comment by Yiyio** [comment]
Hi @vhpietil ,

I am attaching some sample data

This is the vector of 'holiday' dates: 

```
c('2015-03-06', '2015-03-11', '2015-03-12',
                 '2015-03-12', '2015-03-13', '2015-03-14',
                 '2015-03-15', '2015-03-16', '2015-03-17',
                 '2016-03-10', '2016-03-11', '2016-03-12',
                 '2016-03-13', '2016-03-14', '2016-03-15',
                 '2016-03-16', '2016-03-17', '2016-03-18',
                 '2016-03-19', '2017-03-20', '2017-03-10',
                 '2017-03-11', '2017-03-12', '2017-03-13',
                 '2017-03-14', '2017-03-15', '2017-03-16',
                 '2017-03-17', '2017-03-18', '2017-03-19',
                 '2017-03-20', '2018-03-20', '2018-03-10',
                 '2018-03-11', '2018-03-12', '2018-03-13',
                 '2018-03-14', '2018-03-15', '2018-03-16',
                 '2018-03-17', '2018-03-18', '2018-03-19',
                 '2018-03-20')
```
[testdata.txt](https://github.com/facebook/prophet/files/1751887/testdata.txt)

**Comment by bletham** [comment]
Is the spike you're referring to for instance that point way up at 20,000?
If so, there was no datapoint like that the year before, so there really isn't any way for Prophet to forecast it. That generally seems to be the way it is for those outliers - they are occurring on different days in the two years. Prophet will then give you something like the average of the two.

**Comment by vhpietil** [comment]
I think there might be something wrong with your holidays. The spikes are so large that you should see some effect in the forecast even if there is no similar spike the year before. 

Could you attach the full data and holiday dataframe (with holiday, ds, lower_window and upper_window) so that we can see if that is the problem. 

Also please see https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example. It is very difficult to comment on a problem without having full data and/or not knowing how one has approached the problem.
