### ISSUE TITLE
Duplication of plots in Jupyter notebook when %matplotlib inline is used

### ISSUE THREAD

**Issue by Mjboothaus** [facebook/prophet#456]
Hi - thanks for the cool library.

When I use

%matplotlib inline

as an option in my Jupyter notebook (Anaconda dist'n Win 7 / 64bit) I get the plots duplicated i.e. 2 copies of each plot displayed.

i.e. when calling the .plot( ) and .plot_components( )

Cheers Michael

**Comment by bronsonelliott** [comment]
Please #344
