### ISSUE TITLE
add weight

### ISSUE THREAD

**Issue by arita37** [facebook/prophet#459]
Can you add weighting MLE when optimizing with Pystan.
Idea is to use exponential smoothing weight for each value of time series,
so recent events impact more than past events.

This is especially true for change of regime period.

**Comment by bletham** [comment]
I can see how this would be useful. It would require a change to the model and can't be easily done right now, but this can be a future enhancement.

**Comment by arita37** [comment]
this is called weighted MLE,
and very useful for long dataset,
since only short term data is relevant for amplitude.... 




On Feb 28, 2018, at 0:55, Ben Letham <notifications@github.com> wrote:

I can see how this would be useful. It would require a change to the model and can't be easily done right now, but this can be a future enhancement.

―

**Comment by bletham** [comment]
There's actually an issue open for this in #282, so I'm going to close this and further discussion of this feature can happen there.
