### ISSUE TITLE
do not know how to convert 'time2' to class “POSIXct” (predict before fit)

### ISSUE THREAD

**Issue by chartsengrafs** [facebook/prophet#462]
Hi, we are having an issue that only occurs when we are trying to forecast using additional regressors. We have a data frame "future" that has the POSIXct date and the future values of the exogenous value. No matter what format we pass the date column ('ds') we get the same error below. It does not matter if the date is formatted as POSIXct, character, or mdy (using Lubridate) the error is the same.

If we switch to a univariate model, the problem goes away. 

`x <- predict(m2,future)`
`str(future)`

**Error in as.POSIXct.default(time2) : 
  do not know how to convert 'time2' to class “POSIXct”**
#Check structure of future dataset 

data.frame:	2192 obs. of  2 variables:
 $ ds                        : POSIXct, format: "2012-01-01" ...
 $ X: int  0 0 0 0 0 0 0 0 0 0 ...

**Comment by bletham** [comment]
I can't quite figure out where this is coming from, especially since we don't have any variables named `time2`.

Could you post the full traceback for the error? You can get this by running `traceback()` afterwards.

If you could also post an example data that produces this issue that'd be great so I can track down what's happening. The example in the documentation (https://github.com/facebook/prophet/blob/master/notebooks/seasonality_and_holiday_effects.ipynb) does work, so there must be something else going on.

**Comment by bletham** [comment]
I'm hoping this was resolved, but if it wasn't and you can post a traceback please reopen.

**Comment by gnjardim** [comment]
hahaha

**Comment by lissahyacinth** [comment]
**Basic fix** - They were probably passing an unfitted Prophet Model to the predict function, use the fitted model instead.

Adding in details here for anyone searching for this issue - time1 and time2 are variables within difftime in base R, and I made this mistake today and couldn't find answers anywhere else.

Trace for it is 
predict.prophet
Prophet::setup_dataframe

```R
# Line 40 in Version 0.4 of Prophet from CRAN, haven't checked a commit yet. 
df$t <- time_diff(df$ds, m$start, "secs")/m$t.scale
time_diff <- function (ds1, ds2, units = "days") {
  return(as.numeric(difftime(ds1, ds2, units = units)))
}
# So time_diff runs difftime, which has the variables we're interested in.
difftime <- function (time1, time2, tz, units = c("auto", "secs", "mins", 
    "hours", "days", "weeks")) 
```  
Difftime will return that error if ds2 is a NULL value. ds2 is m$start in setup_dataframe, m being the Prophet Model, and will have a NULL as m$start when the model has been built, but not fit.

m$start is provided to the Prophet Model either during initialisation in the function prophet within the function initialize_scales_fn, or the sam function within fit.prophet. 

The main issue is that a unfit model can be passed to predict without other errors.

**Comment by bletham** [comment]
@lissahyacinth thanks for tracking this down! We'll need to add validation there.

**Comment by bletham** [comment]
Fix pushed to PyPI
