### ISSUE TITLE
ValueError: Dataframe has less than 2 non-NaN rows.

### ISSUE THREAD

**Issue by VishnuPrashanthCVI** [facebook/prophet#466]
I am new to using prophet and trying to run the model in a "for loop". After few iterations I get a "ValueError: Dataframe has less than 2 non-NaN rows."

Below is my code:

`prediction = {}
df2 = df2.rename(columns={'Date of the document': 'ds','Quantity sold': 'y', 'Article bar code': 'article'})
list_articles = df2.article.unique()

for article in list_articles:
    article_df = df2.loc[df2['article'] == article]
    my_model = Prophet(weekly_seasonality= True, daily_seasonality=True,yearly_seasonality=True)
    my_model.fit(article_df)
    future_dates = my_model.make_future_dataframe(periods=12, freq='MS')
    forecast = my_model.predict(future_dates)
    prediction[article] = forecast
return prediction`

Below is the error that appears:

>  File "<ipython-input-101-a0f1073a32cb>", line 5, in <module>
    my_model.fit(article_df)

    File "C:\Anaconda\lib\site-packages\fbprophet\forecaster.py", line 775, in fit
    raise ValueError('Dataframe has less than 2 non-NaN rows.')

    ValueError: Dataframe has less than 2 non-NaN rows.

Attaching the screenshot of the error function:

![ef](https://user-images.githubusercontent.com/27816974/37331484-5e831b3a-26a4-11e8-8dc9-8a2ab7456688.PNG)

**Comment by hassheh** [comment]
I think the exception is pretty clear: Prophet object can only be fit once. Instantiate a new object. You are trying fit in a loop.

**Comment by VishnuPrashanthCVI** [comment]
Hi Hassheh,

Thanks for your response. I found the cause of the issue and resolved it. The model needs to have at least 2 values to do prediction. So, I filtered out the values that had less the 2 data values and then ran the model and got the results successfully.

will close the issue.

**Comment by hassheh** [comment]
Hi, I just realize that my comment was not relevant in any way. That wasn't even the error. But its good that you have fixed it.

**Comment by antoinecomp** [comment]
@VishnuPrashanthCVI Hi Vishnu ! I'm encountering the same issue. How did you filtered the values that had less the 2 data values ?

**Comment by Ganeshjadhav221b** [comment]
Prophet cannot be used when number of rows(that are not null) in your data (that you're passing) is less than 2. So you cannot do the prediction in that case!   
So you get an error when you're fitting the model!  
There's no other solution other than adding more (not null) data to the existing!

**Comment by sudhar09** [comment]
My dataframe doesnot contain nan values but still i am facing this issues
can anyone help me how to filter that

**Comment by stiti-bacem** [comment]
> My dataframe doesnot contain nan values but still i am facing this issues
> can anyone help me how to filter that

it's not about about nan values , you should have at least two points un your dataframe to make predictions , so if your are training serveral models into a for loop you can add this conditions:
    if df.shape[0] > 2:
            m.fit(df)

**Comment by stiti-bacem** [comment]
> > Hi Hassheh,
> > Thanks for your response. I found the cause of the issue and resolved it. The model needs to have at least 2 values to do prediction. So, I filtered out the values that had less the 2 data values and then ran the model and got the results successfully.
> > will close the issue.
> 
> i am getting same error...can you please help me

if your are training serveral models into a for loop you can add this condition:
if df.shape[0] > 2:
m.fit(df)

**Comment by tulbureandreit** [comment]
I had the same problem and solved it with @VishnuPrashanthCVI's answer

**Comment by elavankarthik84** [comment]
Hi I am facing similar issues, ValueError: Dataframe has less than 2 non-NaN rows. where exectly we would have to change the logic. please help us

**Comment by elavankarthik84** [comment]
> Hi Hassheh,
> 
> Thanks for your response. I found the cause of the issue and resolved it. The model needs to have at least 2 values to do prediction. So, I filtered out the values that had less the 2 data values and then ran the model and got the results successfully.
> 
> will close the issue.

Hi Hasshes,
Could you please help me, how do we resolve this issues. what kind of fix required. and I have raise similar help as below stackoverflow. kindly assist.

**Comment by elavankarthik84** [comment]
Hi All,
I am facing simialr issues and posted in stackoverflow, please some one help us where we have to change or fix the code.

**Comment by stiti-bacem** [comment]
> if your are training serveral models into a for loop you can add this condition:
> if df.shape[0] > 2:
>     m.fit(df)

**Comment by stiti-bacem** [comment]
> Hi All, I am facing simialr issues and posted in stackoverflow, please some one help us where we have to change or fix the code.

if your are training serveral models into a for loop you can add this condition:
if df.shape[0] > 2:
m.fit(df)

**Comment by elavankarthik84** [comment]
Hi,
Below my sample code, where exactly I have use this logic.

pd_apply_forecast File
"/databricks/python/lib/python3.8/site-packages/prophet/forecaster.py",
line 1113, in fit raise ValueError('Dataframe has less than 2 non-NaN
rows.') ValueError: Dataframe has less than 2 non-NaN rows.

My code :

import reimport pandas as pdimport pyspark.pandas as psfrom prophet
import Prophet
def run_row_outlier_check(df: DataFrame, min_date, start_date,
groupby_cols, job_id) -> DataFrame:
    """
    |    Generate dataframe containing prophet model forecasting of row counts
    """
    pd_schema = StructType([
        StructField(groupby_col, StringType(), True),
        StructField("ds", DateType(), True),
        StructField("y", IntegerType(), True),
        StructField("yhat", FloatType(), True),
        StructField("yhat_lower", FloatType(), True),
        StructField("yhat_upper", FloatType(), True),
        StructField("trend", FloatType(), True),
        StructField("trend_lower", FloatType(), True),
        StructField("trend_upper", FloatType(), True),
        StructField("additive_terms", FloatType(), True),
        StructField("additive_terms_lower", FloatType(), True),
        StructField("additive_terms_upper", FloatType(), True),
        StructField("weekly", FloatType(), True),
        StructField("weekly_lower", FloatType(), True),
        StructField("weekly_upper", FloatType(), True),
        StructField("yearly", FloatType(), True),
        StructField("yearly_lower", FloatType(), True),
        StructField("yearly_upper", FloatType(), True),
        StructField("multiplicative_terms", FloatType(), True),
        StructField("multiplicative_terms_lower", FloatType(), True),
        StructField("multiplicative_terms_upper", FloatType(), True)
        ])

    # dataframe of consecutive dates
    df_rundates = (ps.DataFrame({'date':pd.date_range(start=min_date,
end=(date.today() - timedelta(days=1)))})).to_spark()

    # combine + explode to create row for each date and grouped col
(e.g. business segment)
    df_bizlist = (
        df.filter(f"{date_col} >= coalesce(date_sub(date 'today',
{num_days_check}), '{start_date}')")
            .groupBy(groupby_col)
            .count()
            .orderBy(col("count").desc())
    )

    df_rundates_bus = (
        df_rundates
            .join(df_bizlist, how='full')
            .select(df_bizlist[groupby_col], df_rundates["date"].alias("ds"))
    )

    # create input dataframe for prophet forecast
    df_grouped_cnt = df.groupBy(groupby_cols).count()
    df_input = (
        df_rundates_bus.selectExpr(f"{groupby_col}", "to_date(ds) as ds")
            .join(df_grouped_cnt.selectExpr(f"{groupby_col}",
f"{date_col} as ds", "count as y"), on=['ds',f'{groupby_col}'],
how='left')
            .withColumn("y", coalesce("y", lit(0)))
            .repartition(sc.defaultParallelism, "ds")
    )
    # cache dataframe to improve performance
    # df_input.cache()
    #            .repartition(sc.defaultParallelism, "ds")

    # forecast
    df_forecast = (
        df_input
            .groupBy(groupby_col)
                .applyInPandas(pd_apply_forecast, schema=pd_schema)

    )
    # filter forecast with outlier scores
    df_rowoutliers = (
        df_forecast
            .filter("y > 0 AND (y > yhat_upper OR y <
array_max(array(yhat_lower,0)))")
            .withColumn("check_type", lit("row_count"))
            .withColumn("deduct_score", expr("round(sqrt(pow(y-yhat,
2) / pow(yhat_lower - yhat_upper,2)))").cast('int'))
            .select(
                col("check_type"),
                col("ds").alias("ref_date"),
                col(groupby_col).alias("ref_dimension"),
                col("y").cast('int').alias("actual"),
                col("deduct_score"),
                col("yhat").alias("forecast"),
                col("yhat_lower").alias("forecast_lower"),
                col("yhat_upper").alias("forecast_upper")
            )
    )

    return add_metadata_columns(df_forecast, job_id),
add_metadata_columns(df_rowoutliers, job_id)
def pd_apply_forecast(pd_history: pd.DataFrame) -> pd.DataFrame:
    # remove missing values and filter out null business segments
    pd_history = (pd_history[pd_history[groupby_col].notnull()]
                      .dropna())


    # instantiate the model, configure the parameters
    model = Prophet(
        growth='linear',
        yearly_seasonality='auto',  # default: auto
        weekly_seasonality='auto',  # default: auto
        daily_seasonality=False,    # default: auto
        seasonality_mode='additive'
    )

    # fit the model
    model.fit(pd_history)

    # configure predictions
    pd_future = model.make_future_dataframe(
        periods=365,
        freq='d',
        include_history=True
    )

    # make predictions
    pd_forecast = model.predict(pd_future)

    # ASSEMBLE EXPECTED RESULT SET
    # --------------------------------------
    # get relevant fields from forecast
    pd_f = pd_forecast[ ['ds', 'yhat', 'yhat_lower', 'yhat_upper',
'trend', 'trend_lower', 'trend_upper', 'additive_terms',
'additive_terms_lower', 'additive_terms_upper', 'weekly',
'weekly_lower', 'weekly_upper', 'yearly', 'yearly_lower',
'yearly_upper', 'multiplicative_terms', 'multiplicative_terms_lower',
'multiplicative_terms_upper'] ].set_index('ds')

    # get relevant fields from history
    pd_h = pd_history[ ['ds', groupby_col, 'y'] ].set_index('ds')

    # join history and forecast
    pd_results = pd_f.join(pd_h, how='left')
    pd_results.reset_index(level=0, inplace=True)


    # filter out null dimensions
    pd_results = pd_results[pd_results[groupby_col].notnull()]

    # return predictions
    return pd_results[ [groupby_col, 'ds', 'y', 'yhat', 'yhat_lower',
'yhat_upper', 'trend', 'trend_lower', 'trend_upper', 'additive_terms',
'additive_terms_lower', 'additive_terms_upper', 'weekly',
'weekly_lower', 'weekly_upper', 'yearly', 'yearly_lower',
'yearly_upper', 'multiplicative_terms', 'multiplicative_terms_lower',
'multiplicative_terms_upper'] ]

**Comment by elavankarthik84** [comment]
Please find below my code and issues in stackoverflow.com and help me where
exactly I have to change it.

https://stackoverflow.com/questions/74651378/prophet-forecasting-time-series-model-dataframe-2-non-nan-rows-issues
