### ISSUE TITLE
extra regressor as percentage

### ISSUE THREAD

**Issue by datalabel** [facebook/prophet#472]
Hey, 

I'm quite new in data science, but I hope I'll find a way to ask a question. I have data of a store's income with a 3-4 year history. My goal is to forecast next two months. I'm trying to achieve this with prophet, and so far it's going well. I have a regressor I want to use to improve my forecast but I'm not sure how to use it the best way I can. My regresor is different levels of impact on the stores income where 1 equals no impact, and 1,20 for example equals, 20 percent increase on that day. 0,8 would mean that there would be 20 percent decrease on income. How could I fit that kind of information in the best way to my model?

Thank you in advance.

**Comment by bletham** [comment]
What you are describing is a multiplicative factor, which is not currently supported (#254). In the meantime, you would have to try and somehow convert that to an additive factor.

**Comment by datalabel** [comment]
Thank you very much for your response. Do you have some ideas how to convert it to an additive factor? 

So far I had an idea, to take all my sales history, and count sales averages for all the weekdays. Then to count the differences of those weekdays and apply the same differences to my regressor. In that case I have a different impact for all weekdays. But it doesn't seem to improve my forecast alot. Is my thinking right? Can you direct me atleast where I could read about changing the multiplicative factor to additive?

Thank you in advance.

**Comment by bletham** [comment]
you would take the trend value and multiply it by this factor. But the difficulty is that you then need to have a forecast for the trend value, so there's a bit of a chicken-and-egg thing that keeps this from really being practical. You'll probably have to wait for multiplicative seasonality/regressors to be added.

**Comment by datalabel** [comment]
Thank you for taking your time to answer.

**Comment by bletham** [comment]
This has been added to the v0.3 branch. If you'd like to try it out I'd appreciate the feedback, see #254 for my comment on how to install from the v0.3 branch and enable multiplicative seasonality.

**Comment by bletham** [comment]
I'm going to close this issue now and we can merge the discussion over with #254, which is the main issue for multiplicative seasonality.
