### ISSUE TITLE
Can't load library after installing the package on Windows

### ISSUE THREAD

**Issue by anthonypiccolo** [facebook/prophet#473]
The following error is returned once I have installed the package and run library(prophet);

`> library(prophet)
Error: package or namespace load failed for ‘prophet’:
 .onLoad failed in loadNamespace() for 'prophet', details:
  call: fun(libname, pkgname)
  error: lazy-load database 'C:/Users/anthony/Documents/R/R-3.4.3/library/prophet/R/prophet.rdb' is corrupt
In addition: Warning messages:
1: package ‘prophet’ was built under R version 3.4.4 
2: In fun(libname, pkgname) : internal error -3 in R_decompress1`

Any help would be greatly appreciated!

**Comment by anthonypiccolo** [comment]
This error takes place first;

No C++ compiler found, so the following will probably not work.
See https://github.com/stan-dev/rstan/wiki/Installing-RStan-on-Windows#toolchain

**Comment by anthonypiccolo** [comment]
Resolved this issue now, needed to get rstan installed, it still doesn't work UNLESS I load rstan first. If I haven't loaded rstan it returns this when I try and run the prophet library;

`> library(prophet)
Loading required package: Rcpp
In file included from C:/Users/piccoloa/Documents/R/R-3.4.4/library/BH/include/boost/config.hpp:39:0,
                 from C:/Users/piccoloa/Documents/R/R-3.4.4/library/BH/include/boost/math/tools/config.hpp:13,
                 from C:/Users/piccoloa/Documents/R/R-3.4.4/library/StanHeaders/include/stan/math/rev/core/var.hpp:7,
                 from C:/Users/piccoloa/Documents/R/R-3.4.4/library/StanHeaders/include/stan/math/rev/core/gevv_vvv_vari.hpp:5,
                 from C:/Users/piccoloa/Documents/R/R-3.4.4/library/StanHeaders/include/stan/math/rev/core.hpp:12,
                 from C:/Users/piccoloa/Documents/R/R-3.4.4/library/StanHeaders/include/stan/math/rev/mat.hpp:4,
                 from C:/Users/piccoloa/Documents/R/R-3.4.4/library/StanHeaders/include/stan/math.hpp:4,
                 from C:/Users/piccoloa/Documents/R/R-3.4.4/library/StanHeaders/include/src/stan/model/model_header.hpp:4,
                 from file3b68878e128f6.cpp:8:
C:/Users/piccoloa/Documents/R/R-3.4.4/library/BH/include/boost/config/compiler/gcc.hpp:186:0: warning: "BOOST_NO_CXX11_RVALUE_REFERENCES" redefined
 #  define BOOST_NO_CXX11_RVALUE_REFERENCES
 ^
<command-line>:0:0: note: this is the location of the previous definition
In file included from C:/Users/piccoloa/Documents/R/R-3.4.4/library/StanHeaders/include/stan/math/rev/core.hpp:44:0,
                 from C:/Users/piccoloa/Documents/R/R-3.4.4/library/StanHeaders/include/stan/math/rev/mat.hpp:4,
                 from C:/Users/piccoloa/Documents/R/R-3.4.4/library/StanHeaders/include/stan/math.hpp:4,
                 from C:/Users/piccoloa/Documents/R/R-3.4.4/library/StanHeaders/include/src/stan/model/model_header.hpp:4,
                 from file3b68878e128f6.cpp:8:
C:/Users/piccoloa/Documents/R/R-3.4.4/library/StanHeaders/include/stan/math/rev/core/set_zero_all_adjoints.hpp:14:17: warning: 'void stan::math::set_zero_all_adjoints()' defined but not used [-Wunused-function]
     static void set_zero_all_adjoints() {
                 ^
In file included from C:/Users/piccoloa/Documents/R/R-3.4.4/library/BH/include/boost/config.hpp:39:0,
                 from C:/Users/piccoloa/Documents/R/R-3.4.4/library/BH/include/boost/math/tools/config.hpp:13,
                 from C:/Users/piccoloa/Documents/R/R-3.4.4/library/StanHeaders/include/stan/math/rev/core/var.hpp:7,
                 from C:/Users/piccoloa/Documents/R/R-3.4.4/library/StanHeaders/include/stan/math/rev/core/gevv_vvv_vari.hpp:5,
                 from C:/Users/piccoloa/Documents/R/R-3.4.4/library/StanHeaders/include/stan/math/rev/core.hpp:12,
                 from C:/Users/piccoloa/Documents/R/R-3.4.4/library/StanHeaders/include/stan/math/rev/mat.hpp:4,
                 from C:/Users/piccoloa/Documents/R/R-3.4.4/library/StanHeaders/include/stan/math.hpp:4,
                 from C:/Users/piccoloa/Documents/R/R-3.4.4/library/StanHeaders/include/src/stan/model/model_header.hpp:4,
                 from file3b6885f51400a.cpp:8:
C:/Users/piccoloa/Documents/R/R-3.4.4/library/BH/include/boost/config/compiler/gcc.hpp:186:0: warning: "BOOST_NO_CXX11_RVALUE_REFERENCES" redefined
 #  define BOOST_NO_CXX11_RVALUE_REFERENCES
 ^
<command-line>:0:0: note: this is the location of the previous definition
In file included from C:/Users/piccoloa/Documents/R/R-3.4.4/library/StanHeaders/include/stan/math/rev/core.hpp:44:0,
                 from C:/Users/piccoloa/Documents/R/R-3.4.4/library/StanHeaders/include/stan/math/rev/mat.hpp:4,
                 from C:/Users/piccoloa/Documents/R/R-3.4.4/library/StanHeaders/include/stan/math.hpp:4,
                 from C:/Users/piccoloa/Documents/R/R-3.4.4/library/StanHeaders/include/src/stan/model/model_header.hpp:4,
                 from file3b6885f51400a.cpp:8:
C:/Users/piccoloa/Documents/R/R-3.4.4/library/StanHeaders/include/stan/math/rev/core/set_zero_all_adjoints.hpp:14:17: warning: 'void stan::math::set_zero_all_adjoints()' defined but not used [-Wunused-function]
     static void set_zero_all_adjoints() {`

Interested to know why this would be occurring?

At least I can use prophet now!

**Comment by bletham** [comment]
Those messages there all looks like warnings, I'm wondering if it actually did load? could you post
```
library(prophet)
sessionInfo()
```

**Comment by divya074** [comment]
on google colab
!pip install -q python-midi
library is not installing
output i got is
Collecting python-midi
  Using cached https://files.pythonhosted.org/packages/8d/e1/fd34aa05508d907449fb2d66a679d4f98eeeacdb4b3c7e6af87d91c4fa21/python-midi-v0.2.4.tar.gz
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-2bqotnco/python-midi/

**Comment by bletham** [comment]
@divya074 that error is for a different package, I think you will have more success asking at https://github.com/vishnubob/python-midi
