### ISSUE TITLE
Support dataset in a streaming manner

### ISSUE THREAD

**Issue by turboT4** [facebook/prophet#476]
I was looking to integrate the project in a personal development, and I see that the data must be fixed and that it doesn't accept non-final sets. Is there any plans to support streaming regarding datasets? So that lets say, incoming monthly data is being compared to a whole already processed yearly dataset?

**Comment by bletham** [comment]
There's some discussion of this in #46. There isn't really any way at the moment to update a model fit, in this case you would have to re-fit the model from scratch when given the new monthly data.

Usually the fitting time is pretty small so there isn't a whole lot of benefit to be had from trying to do an online update, but this is something that we've been thinking about, especially with sub-daily data.
