### ISSUE TITLE
Trend that include changepoints in the last 20%

### ISSUE THREAD

**Issue by csumaria** [facebook/prophet#477]
I was trying to fit data that increases in value at the end. By default, Prophet only considers the first 80% of data points while determining changepoints for trend. While I understand that this isn't a standard way to model, I wanted to fit a trend line across all points. Thanks.

**Comment by zelkhama** [comment]
- This parameter is hardcoded in the source code. 

- You can change it by accessing the script forecaster.py and replace this line of the set_changepoints method : 

`hist_size = np.floor(self.history.shape[0] * 0.8)`

by something like that: 

`hist_size = np.floor(self.history.shape[0] * 0.95)`

**Comment by bletham** [comment]
This will be exposed as a parameter in the next version (see #217).

**Comment by bletham** [comment]
I'm going to close this and leave #217 as the main issue for this feature.
