### ISSUE TITLE
How does Prophet calculate uncertainty (blue region)

### ISSUE THREAD

**Issue by camontanezp** [facebook/prophet#478]
Dear all, 

Can someone share with me how Prophet generates simulations of the forecast in order to calculate the uncertainty intervals? For example, is it done by sampling errors with respect to the adjusted curve and calculating percentiles? 

In the paper it explains something and also in the documentation. But there is not much detail. For example in the documentation it says that there are various assumptions made. Which ones?

Also. I'd like to know what's the generative process. Does it depends only on the change points scale? I did notice that when this value is high, the uncertainty grows into the future. But when it is not, the uncertainty is kind of constant. 

Many thanks!

**Comment by bletham** [comment]
The paper (https://peerj.com/preprints/3190v2.pdf) attempts to describe this in Section 3.1.4. The code is here (in R): https://github.com/facebook/prophet/blob/master/R/R/prophet.R#L1312

Basically the procedure is:
* Use the fitted trend change magnitudes to estimate the Laplace rate scale parameter, with the equation in the paper.
* Calculate the average rate of changepoints in the history according to the time discretization of the history.
* Sample the number of future changepoints from a binomial distribution whose rate is that average rate of changepoints from the previous point.
* For each of these changepoints, sample a trend change magnitude from the Laplace distribution from the first point.

That is now a simulated trend. That is done many (by default 1000) times and then quantiles can be computed.

The role of the changepoints prior scale: As you can see in the generative process outlined above, it does not appear directly. However, shrinking the changepoints prior scale will shrink the fitted trend change magnitudes. This will in turn shrink the magnitudes of the simulated future trend changes and so leads to narrower uncertainty bands.

Does that clarify things?

**Comment by camontanezp** [comment]
That is very clear @bletham, thanks a lot! 

I think the source of doubt was that in the paper the changepoints prior scale is not (directly) mentioned. 

Will I find, in the code provided, the (mathematical) relation between lambda and this rate?

Many thanks again!
