### ISSUE TITLE
Can prophet be applied to time series with sequential time index instead of calender date-ds

### ISSUE THREAD

**Issue by Jen2018** [facebook/prophet#481]
Can prophet be applied to time series with sequential time index instead of calender date-ds?
It seems that it uses calendar dates. However, my time series is in sequential with like 15 or 20 data points within one cycle(year).The cycle is not calendar year. Can prophet accommodate this like R package forecast does using start =1, freq=15?
data example:
  ds  y
  1   34
  2    45
.......  
  15  89
   1   47
   2  67
 .......
  15 108
   1  54
.......

**Comment by bletham** [comment]
The R version uses the POSIXct type for `ds`, and the assumption of datetime type is all throughout the code so I don't think there's going to be a straightforward way to have `ds` not be datetime. I think the best option in this case would be to convert the indexes to dates. The Prophet model is continuous-time, so you could just convert them to sequential days, and then add a custom 15-day seasonality to capture cycles on that time-scale (and disable the built-in yearly and weekly seasonalities). So the data would look like:
```
ds y
2018-01-01 34
2018-01-02 45
.......
2018-01-15 89
2018-01-16 47
....
```
and then
```
m <- prophet(
  weekly.seasonality = FALSE,
  yearly.seasonality = FALSE,
)
m <- add_seasonality(m, name = 'cycle', period = 15, fourier.order = 7)
m <- fit.prophet(m, df)
```
