### ISSUE TITLE
Extract stan fit from 'm' object in prophet()

### ISSUE THREAD

**Issue by leungi** [facebook/prophet#482]
Hi,

First off, thank you for sharing this convenient and valuable tool.

I noticed in prophet() that the return object 'm' has a parameter stan.fit that's default to NULL.

Will it be possible to allow a boolean argument so user can choose to retrieve fitted stan 'fit' (if TRUE)?

Thank you.
Ivan

**Comment by bletham** [comment]
Thanks for pointing that out, you found a vestigial property that has been there since the beginning but isn't being used for anything. You want to have the stanfit object stored there? Is there something specific you want to use it for?

**Comment by leungi** [comment]
Thanks for reply @bletham.

I'm using prophet() with regressors to model injection/production responses, and am getting mixed results, even after adjusting the prior.scales; hence, I hope to do MCMC diagnostics on stan.fit to see why it returns acceptable results in some cases, and not in others.

**Comment by leungi** [comment]
I may be missing something, but for R, can we assign `.prophet.stan.models` to `stan.fit` in `m`?

For Python, this is how we pickle for reuse, and seems to work fine:
```
# function to handle cached or non cached stan models
def stan_cache(stan_model, model_name, **kwargs):
 cached_model = 'some_path/' + model_name + '.pkl'
 try:
  # check for existing model
  stan.fit = pickle.load(open(cached_model, 'rb'))
 except:
  # else compile
  stan.fit = pystan.StanModel(file = stan_model, verbose = True)
  with open(cached_model, 'wb') as f:
   # save stan.fit
   pickle.dump(stan.fit, f)
  return stan.fit.sampling(**kwargs)

# sampling_dict is `dat` list to stan()
fit = stan_cache(stan_model='foo.stan', model_name='foo', **sampling_dict)
```

Look forward to your feedback.

**Comment by bletham** [comment]
In R we'd want to store the `stan.fit` variable, that's where the actual samples are stored.

We're looking into moving the prediction code to happen inside Stan, in which case we'd certainly want to be keeping the stan fit object around. I can get behind storing it and we could add pickling functionality as needed.

**Comment by leungi** [comment]
Awesome. Thanks again for all your work @bletham!

**Comment by Igevorse** [comment]
Seems like this is resolved since https://github.com/facebook/prophet/pull/1156 is merged.

**Comment by leungi** [comment]
Thanks for the PR @Igevorse; hope to see a CRAN release soon!

**Comment by bletham** [comment]
This is done for R, but for Py it was un-done by the refactoring to allow for a cmdstanpy backend. The fit object is now generated in the backend and so will need to be passed back from here
https://github.com/facebook/prophet/blob/46e56119835f851714d22b285d2e4081853b9fb1/python/fbprophet/models.py#L71
and here
https://github.com/facebook/prophet/blob/46e56119835f851714d22b285d2e4081853b9fb1/python/fbprophet/models.py#L232

**Comment by ryankarlos** [comment]
Hopefully #1353  closes this now

**Comment by bletham** [comment]
I'll leave this open until it gets pushed

**Comment by bletham** [comment]
In v0.7 this is now stored as `m.stan_backend.stan_fit`.
