### ISSUE TITLE
Exclude holiday effect

### ISSUE THREAD

**Issue by karunakarantk** [facebook/prophet#485]
Is it possible to factor in the absence of a holiday (or an event that influences what is being forecast) in a certain year? Just omitting the dates from the holiday dataframe does not seem to work. 
Ideally I want to define when the holiday will or will not happen

In other words:

- I have time series (sales data) where every year an event happens and there is increased sales during this event
- That event does not happen in some years so I need to factor in that in the forecast

TIA

**Comment by bletham** [comment]
I would expect that simply leaving the holiday out in the years that you expect no effect would work...
The holidays are fit as a binary regressor that is 0 on all days except the holiday, where it has some fixed additive effect. So, for instance, it might learn an effect of -3, and then would apply that effect to all of the dates specified for that holiday, and would have no effect on other dates.

If you are seeing drops on holiday dates that have been omitted, then I wonder if perhaps the drop is being caught by yearly seasonality. If it happens on the same day every year and especially if the effect is broader than just the 1 day then maybe yearly seasonality is being used to capture the effects outside that one day.

Could you post the components plot? That would be really helpful for seeing what is going on here.

**Comment by bletham** [comment]
I'm hoping this was resolved but if there are further questions feel free to reopen.
