### ISSUE TITLE
Submit latest version to PyPI

### ISSUE THREAD

**Issue by mcastillon** [facebook/prophet#486]
Right now, I'm trying to leverage the `dependency_links` parameter in `setup.py` to install `fbprophet`, but would much rather just leverage PyPI. Is there a plan to release the development version to PyPI? In particular, the `cross_validation` functionality is out of date on PyPI (https://github.com/facebook/prophet/issues/380).

**Comment by bletham** [comment]
Coming very soon, I wanted to get multiplicative seasonality finished for the next version and it's now ready to go, so it's just cleaning up a some other minor issues and then documentation update.
