### ISSUE TITLE
how to make weekly effect disappear when it meet the holiday effect

### ISSUE THREAD

**Issue by sevenseablue** [facebook/prophet#493]
example.  
my data, monday to friday is about 200, saturday and sunday is about 100, holiday is 100
2016-12-31, 2017-01-01, 2017-01-02 is new year holiday,  the number of these days must be similar , like 70, 
I make a prophet(holidays), predict, but get 
2016-12-31 100
2017-01-01 100
2017-01-02 140
2017-01-03 180

how can I make 2017-01-02 to be 100?
how can I make the  weekly effect disappear when it meet the holiday effect

**Comment by bletham** [comment]
The model treats the holiday and weekday effects as independent additive effects. In this case where there are interactions between being a holiday and being a weekday, there are basically two things you could do. One is to create a "holiday_on_weekend" holiday and put just the dates that are holidays on the weekend, and then a separate "holiday_on_weekday" with the dates that are on a weekday. This would learn a separate effect depending on if it is weekday or weekend for the holiday. 
If you don't have much data you might not be able to reliably estimate these effects, for instance if you only have one year where the holiday was on a weekday or weekend.

If you believe the holiday effect is the same on weekday/weekend and it's just a matter of the day-of-week effect disappearing, then you could remove weekly seasonality for just that day by manually adding day-of-week indicators as extra regressors. This is a bit of effort, but see the second comment (mine) in #425 for how to manually model weekly seasonality with extra regressors. You would then just set them all to 0 on holidays.

**Comment by bletham** [comment]
I'm going to go ahead and close this but if there are additional questions about this feel free to re-open.
