### ISSUE TITLE
Different Daily seasonalities based on day of the week

### ISSUE THREAD

**Issue by glil** [facebook/prophet#497]
For a lot of patterns the difference in diurnal profile is significantly different for weekdays from weekends. Prophet does a good job at merging the two but being able to have different daily profiles for different days of the week would be very useful when modelling customer demand, or at the least being able to separate weekdays from weekends.

**Comment by bletham** [comment]
This seems to be a similar issue as in #434. This can be handled by manually creating extra regressors to handle the seasonality but it's quite a pain (see #434 for how). Making this easier to do is on the to-do list.

**Comment by bletham** [comment]
I'm going to go ahead and close this and leave #434 as the issue to track this.
