### ISSUE TITLE
Displaying weekly components on a forecast plot

### ISSUE THREAD

**Issue by pfmoore** [facebook/prophet#498]
I have a plot [image here](https://imgur.com/a/HNfqD) (Sorry, I can't work out how to post it inline) that shows a clear trend in my data. The component analysis shows a distinct peak on Sundays, and I'd like to highlight that data on the plot (I'm assuming that the dots at the top will be for Sundays).

I haven't been able to find an obvious way to do this - is there a way I can say to highlight the actual data points by day of the week?

Edit: I should have said, I'm working in Python.

**Comment by bletham** [comment]
The output of the `plot` method is a matplotlib figure, which you can then edit/add stuff to as desired using normal matplotlib commands. If you're not familiar with matplotlib there is a bit of a learning curve, but it is very powerful and you can do pretty much whatever you'd want. Here is how you would do what you are describing:
```
# Plot the full forecast as usual
fig = m.plot(fcst)
# filter the forecast to just Sundays
sunday_fcst = fcst[fcst['ds'].dt.dayofweek == 6]
# Extract the axis from the figure
ax = fig.gca()
# Plot the sunday values on top of the figure, here the 'r.' means with red dots.
ax.plot(sunday_fcst['ds'], sunday_fcst['yhat'], 'r.')
```

**Comment by pfmoore** [comment]
Thanks - so just take what's there and then overwrite the dots I want to be in a different colour? Yes, that would work for changing colour which is all I wanted to do. (Might be more awkward if I wanted to change the style, say to a cross, though - but I can worry about that later if I need to).

**Comment by bletham** [comment]
Yes this just overwrites with the other color. Removing the points to replace with another marker would be quite a bit more annoying, and I think what I'd probably do in that situation is have the `fcst` being input to `m.plot` exclude Sundays, and then you could add in the Sunday forecast as above but with different markers.

**Comment by pfmoore** [comment]
Thanks, yes that might be an option. I actually looked at the source of the `plot()` method, and it's not as complex as I'd feared - another option would probably be to simply use that method as a template, and build my own graphs based on the code in there.

So I think I have some good options to use in future. Thanks for your help.
