### ISSUE TITLE
Excluding daily time periors

### ISSUE THREAD

**Issue by sasasavic82** [facebook/prophet#500]
I have sub-daily observations (1-hour intervals) of building floor occupancy.

I am only interested in observations between the hours of 6am and 6pm

Data goes back in history 1.5 years.

Q1: Do I have to df['y'] = np.log(df['y']) for non-daily data too? (the non-daily example didn't do that)

Q2: Is there possibility to exclude data from 6pm to 6am, as I'm not interested in after hours observations

The reason why I ask, my forecast would produce high numbers of occupancy for after hours or weekends, when in-fact hardly anybody is around.

What is the best approach in this case? Open to all suggestions including "you're doing it wrong, you should include all observation" to "this is how you exclude ..." 

It almost seems like my seasonality IS infact 6am-6pm observations? 

Thank you so much. Awesome project.

**Comment by vhpietil** [comment]
I think you can remove the 6pm-6am rows from the future dataframe before predicting or you can remove those from the forecast if you are not interested in them.

I don’t know if you should include those observations or not. Check which approach gives better results.

Prophet will provide crazy forecasts for some hours if there are no observations in the history during those hours.

**Comment by bletham** [comment]
+1 on what @vhpietil says about limiting the dataframe of future datetimes that you pass to `m.predict()` to include only datetimes from 6a-6p.

For the first question, the log transform on that example in the documentation was just because the y in that particular time series took on a very extreme range of values (effects spanned orders of magnitudes). Typically you wouldn't need this, and I'd imagine for the the time series you describe you would not. Using or not using a log transform is unrelated to the time resolution of the data, it's just about the scale of y.

**Comment by sasasavic82** [comment]
Thank you. Will give it a try and let you know here.

**Comment by sasasavic82** [comment]
Hey gents - one last "issue" I have is that, whilst I got rid of the unwanted times, how would you go about removing weekends? Would you use a regressor to mark the weekends?

**Comment by vhpietil** [comment]
If you are not predicting on weekends, I would probably remove them from the training data. If the observations on weekends are not similar to those on weekdays, they will probably decrease the accuracy of your predictions on weekdays. If you need to include those weekend observations, you should use regressors.

**Comment by bletham** [comment]
Adding weekend days as an extra regressor would not give you anything that the weekly seasonality isn't already given you. I'm guessing that the daily seasonality looks very different on weekends and weekdays, which is related to the issue in #434. You can handle this by manually creating extra regressors that contain the fourier features used for daily seasonality; this is described in #434, but it is a bit of a pain. Alternatively like @vhpietil suggests you could just remove the weekend days and forecast them separately (not as good as the other option, but a lot simpler).
