### ISSUE TITLE
duplicate plotting

### ISSUE THREAD

**Issue by shinsonwu** [facebook/prophet#503]
environment：py3.5,win10, Anaconda,jupyter notebook:
After  import maplotlib.pyplot and set  %matplotlib inline,
then following the officals Doc,used plot API to see the forecast and components,but return duplicate figures in jupyter notebook
1 m.plot(forecast)
2 m.plot_components(forecast)
If i used m.plot(forecast).show() and m.plot_components(forecast).show(),it will return the right  num of maplotlib figures

Hoping you can understand me after see the attachment

[duplicate plot.zip](https://github.com/facebook/prophet/files/1948288/duplicate.plot.zip)

**Comment by bronsonelliott** [comment]
Just add a semicolon to the end of the plot line.  For example:

- m.plot(forecast)**;**
- m.plot_components(forecast)**;**

**Comment by bronsonelliott** [comment]
Please refer to #344
