### ISSUE TITLE
Additional influential factors

### ISSUE THREAD

**Issue by bgruenefeld** [facebook/prophet#512]
I just found your forecast lib and experimented with it for a while - it looks realy good!

Sometimes it makes sense to include influencing factors in a forecast, e.g. the temperature often has an influence on a forecast.
so my question is:
Is there the possibility in prophet to add such influencing factors get involved in the forecast?

**Comment by adodell** [comment]
you may be looking for Additional Regressors

https://facebook.github.io/prophet/docs/seasonality_and_holiday_effects.html

check out the "Additional Regressors" section near the bottom of the page.
