### ISSUE TITLE
Prophet Prediction Fails When given a Static Data Set

### ISSUE THREAD

**Issue by GregorMcC** [facebook/prophet#518]
Hey,

I've run into an issue where it appears that Prophet fails to predict when passed a static dataset while using the logistic regression technique.

This works fine in v0.1.1, however since upgrading to v0.2.1 this seems to occur.

See below for attached screenshots:

Forecast Output
![forecast output](https://user-images.githubusercontent.com/5014180/40064462-7d84d8c2-5857-11e8-9607-8de1d0a11b43.png)

Trend Components
![trend components](https://user-images.githubusercontent.com/5014180/40064664-ef20d436-5857-11e8-87c2-6e32d864cb22.png)

I can bypass this issue by changing one of the dataset points to be one higher than the rest and then the result is as below:

![screen shot 2018-05-15 at 15 54 23](https://user-images.githubusercontent.com/5014180/40064856-4e126bee-5858-11e8-8e26-26528a6ee1e5.png)
![screen shot 2018-05-15 at 15 54 29](https://user-images.githubusercontent.com/5014180/40064860-50508134-5858-11e8-99ee-abe5de4c234f.png)

If you need a dataset put together then let me know and I can get one hosted somewhere.

Cheers,
Gregor

**Comment by bletham** [comment]
This was fixed in v0.3, which has now been pushed out.
