### ISSUE TITLE
Export a model and import it back

### ISSUE THREAD

**Issue by petr-k** [facebook/prophet#521]
Hi,
once a model has been fit, is there a way to serialize it to a file and import it back at a later time?

**Comment by bletham** [comment]
In Python, you should find that the model pickle's nicely:
```
import pickle
with open('model.pckl', 'wb') as fout:
    pickle.dump(m, fout)

with open('model.pckl', 'rb') as fin:
    m2 = pickle.load(fin)
```

In R, `saveRDS` and `readRDS` work:
```
saveRDS(m, file="model.RDS")
m2 <- readRDS(file="model.RDS")
```

**Comment by petr-k** [comment]
Thanks! ;)

**Comment by bletham** [comment]
We should add this to the documentation, I'll leave this open until then.

**Comment by bletham** [comment]
Actually there isn't a very natural place to put this in the documentation without adding a section for miscellanea, of which this would be the only one, so I'll hold off on adding this unless it comes up again.
