### ISSUE TITLE
fbprophet causing python to stop working

### ISSUE THREAD

**Issue by jkelley7** [facebook/prophet#525]
I've been using batch files to automate my prophet forecasts and have not had any issues until a couple days ago.  I've been getting messages that says, "Python has stopped working". After using the pdb i've found the issue has been coming from importing fbprophet. I'm using Anaconda version 4.5.4 running python 3.5.0 on a windows 7 64 bit. 

The strange thing, when I use a jupyter notebook i have no issues importing and using fbprophet. I've been trying to troubleshoot on my own but am at a dead end. Any ideas?

Here's an error message i'm getting:
<?xml version="1.0" encoding="UTF-16"?>

<WERReportMetadata><OSVersionInformation><WindowsNTVersion>6.1</WindowsNTVersion><Build>7601 Service Pack 1</Build><Product>(0x4): Windows 7 Enterprise</Product><Edition>Enterprise</Edition><BuildString>7601.23915.amd64fre.win7sp1_ldr.170913-0600</BuildString><Revision>1130</Revision><Flavor>Multiprocessor Free</Flavor><Architecture>X64</Architecture><LCID>1033</LCID></OSVersionInformation><ParentProcessInformation><ParentProcessId>12540</ParentProcessId> <ParentProcessPath>C:\Windows\System32\cmd.exe</ParentProcessPath> <ParentProcessCmdLine>"C:\WINDOWS\system32\cmd.exe" </ParentProcessCmdLine> </ParentProcessInformation><ProblemSignatures><EventType>APPCRASH</EventType><Parameter0>python.exe</Parameter0><Parameter1>3.5.150.1013</Parameter1><Parameter2>565ddd01</Parameter2><Parameter3>python35.dll</Parameter3><Parameter4>3.5.150.1013</Parameter4><Parameter5>565ddd00</Parameter5><Parameter6>c0000005</Parameter6><Parameter7>0000000000125c80</Parameter7></ProblemSignatures><DynamicSignatures><Parameter1>6.1.7601.2.1.0.256.4</Parameter1><Parameter2>1033</Parameter2><Parameter22>0adf</Parameter22><Parameter23>0adf588e850205a04234933694bb0327</Parameter23><Parameter24>c2aa</Parameter24><Parameter25>c2aa57c5ceb195df61ce0906600ef6d0</Parameter25>

<EXE NAME="python35.dll" FILTER="CMI_FILTER_THISFILEONLY">

    <MATCHING_FILE NAME="python35.dll" SIZE="3918336" CHECKSUM="0xCE4CE823" BIN_FILE_VERSION="3.5.150.1013" BIN_PRODUCT_VERSION="3.5.150.1013" PRODUCT_VERSION="3.5.0" FILE_DESCRIPTION="Python Core" COMPANY_NAME="Python Software Foundation" PRODUCT_NAME="Python" FILE_VERSION="3.5.0" ORIGINAL_FILENAME="python35.dll" INTERNAL_NAME="Python DLL" LEGAL_COPYRIGHT="Copyright © 2001-2015 Python Software Foundation. Copyright © 2000 BeOpen.com. Copyright © 1995-2001 CNRI. Copyright © 1991-1995 SMC." VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x4" VERFILETYPE="0x2" MODULE_TYPE="WIN32" PE_CHECKSUM="0x0" LINKER_VERSION="0x0" UPTO_BIN_FILE_VERSION="3.5.150.1013" UPTO_BIN_PRODUCT_VERSION="3.5.150.1013" LINK_DATE="12/01/2015 17:46:40" UPTO_LINK_DATE="12/01/2015 17:46:40" EXPORT_NAME="python35.dll" VER_LANGUAGE="Language Neutral [0x0]" EXE_WRAPPER="0x0" />

</EXE>

**Comment by jkelley7** [comment]
Thanks. I re-installed it. All is working now.

**Comment by bletham** [comment]
Did you just do the force re-install, or was there something else involved? (For others that have the same issue in the future).

**Comment by jkelley7** [comment]
I uninstalled everything then re-installed everything. I had previously installed altair and after the installation of that package it gave me the above error. I'm not sure why. As such, I have learned an important lesson, use virtual environments.
