### ISSUE TITLE
Any way to change the image features that prophet generates?

### ISSUE THREAD

**Issue by andymancodes** [facebook/prophet#526]
Hi,

Thanks for the great library.

While using m.plot(forecast) the figure that appears has black dots as data points.

Is there any way to customize how the figure looks. I know I can use forecast and plot using other libraries, but I guess there must be a way somewhere to customize frophet's figures as well.

Cheers!

**Comment by bletham** [comment]
The method returns a matplotlib figure, and you could extract the axis object and then use matplotlib commands to modify it:
```
fig = m.plot(forecast)
ax = fig.gca()
```
However, for something like changing the markers that sounds pretty painful - I'd personally in that case just reproduce the figure from scratch. It's actually very little code (20 lines): https://github.com/facebook/prophet/blob/master/python/fbprophet/forecaster.py#L1232

Just do `from matplotlib import pyplot as plt`, replace `self` with `m`,  and it will work. Then you can edit at will (for instance here https://github.com/facebook/prophet/blob/master/python/fbprophet/forecaster.py#L1256 to change the data marker type).

**Comment by bletham** [comment]
This should be resolved but please reopen if there are further questions about this.
