### ISSUE TITLE
Using Multiplicative Models

### ISSUE THREAD

**Issue by deniznoah** [facebook/prophet#527]
Hello,

I am pretty sure that multiplicative models would work better for at least a few of my variables.

Is there a way to use multiplicative models instead of additive? I have tried using log transformation but not `all` variables should be multiplicative.

Can you please help me with this?

Thank you,
Deniz

**Comment by bletham** [comment]
Multiplicative seasonality will be in the next version, to be released soon. If you're like to try it out now it has actually been added to the development branch already, and you can see in #254 my comment on how to install the development branch.

**Comment by bletham** [comment]
Now pushed in v0.3.
