### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in C:\Users\LCY\AppD ata\Local\Temp\pip-install-c465o9dr\django-quiz-app\

### ISSUE THREAD

**Issue by anitahkimanzi** [facebook/prophet#528]
This is the error yet i cant find that directory in my laptop

![djangoerr](https://user-images.githubusercontent.com/25051454/40421573-0c262cc8-5e95-11e8-8c89-2a785c1b2def.PNG)

**Comment by bletham** [comment]
This seems to be unrelated to this package, I'd recommend finding the developers of that package to try and find the solution.
