### ISSUE TITLE
Negative sales forecasts

### ISSUE THREAD

**Issue by deniznoah** [facebook/prophet#532]
Hi,

My forecasts are occasionally going negative. What is the best way to remove "negativity" from the model?

Sales or demand can never be negative so I need to make sure my forecasts never go negative. If your recommendation would be to use logistic growth, then my problem is how do I set a "higher cap" for the model?

I have absolutely no idea what the cap would be. Is there a way to only have a lower cap?

Please help!!

Deniz

**Comment by bletham** [comment]
Related to #307

**Comment by bletham** [comment]
Discussed in #554
