### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in C:\Users\LCY\AppD ata\Local\Temp\pip-install-g9u9yist\django-quiz-app\ 

### ISSUE THREAD

**Issue by anitahkimanzi** [facebook/prophet#534]
Im trying to set up a cloned project to window 7.
This happens when I try to pip install -r requirement\local.txt.
Setuptools are up to date.
I don't know whats the problem.
please help me.

![capture](https://user-images.githubusercontent.com/25051454/40469715-1e12da4e-5f3a-11e8-91e4-e02263c19433.PNG)

**Comment by bletham** [comment]
#528
