### ISSUE TITLE
Details on the Model and Training

### ISSUE THREAD

**Issue by andymancodes** [facebook/prophet#539]
Hi,

Thanks for the great library.

However, I am having trouble getting into the nuts and bolts of the training process.

I can see that log joint probability is maximized but rest of the parameters like alpha, grad of x I am not getting.

Is there any link or post that I could refer to?

Does the associated paper of Prophet have enough details, on scanning it I saw mostly high level ideas and not too much details on what model is constructed by the APIs (it gives components though) and how the training proceeds, what algorithms are used?

**Comment by bletham** [comment]
I hope that answered the question, feel free to re-open if not.
