### ISSUE TITLE
Mechanics with regards to "cap"

### ISSUE THREAD

**Issue by deniznoah** [facebook/prophet#544]
Hello,

I am working on the v0.2.1dev version's "logistic" growth. I have trouble understanding what exactly the "cap" does. Is it used in linear model if you define it? Or is it only for logistic model?

Does it cap only the trend?

Thank you for your help,
Deniz

**Comment by bletham** [comment]
It is only used for logistic growth, and will be ignored if the growth is set to linear. It only affects the trend. It is the dashed line in the first figure in (https://facebook.github.io/prophet/docs/saturating_forecasts.html), the point that the trend will saturate at. For more detail you could look at the Wikipedia page for the logistic function - cap is the "L" in that function (https://en.wikipedia.org/wiki/Logistic_function).
