### ISSUE TITLE
Extract Fourier terms?

### ISSUE THREAD

**Issue by simon19891101** [facebook/prophet#553]
Hi there, just wondering if it is possible to extract the Fourier terms of the Prophet model (python)? Many thanks!

**Comment by bletham** [comment]
The `fourier_series` method will do that. You can do `help(Prophet.fourier_series)` to see the documentation for it, but basically for yearly seasonality it would be:
```
X = Prophet.fourier_series(dates=pd.to_datetime(df['ds']), period=365, series_order=10)
```
For weekly seasonality `period=7` and `series_order=3`, for daily it is 1 and 4.

**Comment by simon19891101** [comment]
Cool. Thanks a lot!
