### ISSUE TITLE
Fully multiplicative model going negative

### ISSUE THREAD

**Issue by deniznoah** [facebook/prophet#554]
Hi,

I am trying to avoid "negative" values in my forecast since a sales/demand forecast can never get lower than zero.

For this reason I have tried setting below to multiplicative:
- Seasonality
- Promotional Impact
- Easter Sunday
- Christmas Sunday

Can you please help me understand how my model achieves negativity :(

![image](https://user-images.githubusercontent.com/35758436/40817477-f244e04e-6595-11e8-93bb-a3acd79c6871.png)

![image](https://user-images.githubusercontent.com/35758436/40817484-f5ab3788-6595-11e8-9418-4338f430c0c9.png)

**Comment by WouterTromp** [comment]
It the last graphs where the impact of the regressors are shown you see some specific negative dips (around 2016-12 & 2018-12), coupled with the negative yearly trend around the same time. Multiply that, and your predicted values become negative.

Did you log-transform the data first before fitting? That might help in some cases to prevent these huge spikes.

**Comment by deniznoah** [comment]
I actually did not. I do not know exactly when I should be applying the log transformation. For some sets we do use it and for some we do not.

Is there a way to compare the log transformed model with the regular one? How can I do it using tools on python?

**Comment by bletham** [comment]
If the seasonal effect or extra regressor is >100% then it can result in negative forecasts, which is what is happening here. I'm not sure there is much to be done about it besides clipping the yhat at 0 before you use it.

**Comment by bletham** [comment]
This seems to be resolved but please reopen if there is more to discuss.

**Comment by bsnithin44** [comment]
Hi Bletham, I do not have an extra regressor. So how can i understand if seasonal effect is gonna give negative forecasts or not? will the plot_components chart tell me if the seasonality >100% or is there any metric i can get from prophet regarding the seasonality?

**Comment by bletham** [comment]
@bsnithin44 Yes, in the components plot you can see if the seasonal effect is >100% (as it is in the first post of this issue).
