### ISSUE TITLE
Using multiplicative seasonality together with log transformation

### ISSUE THREAD

**Issue by deniznoah** [facebook/prophet#559]
Hi,

I am using specifying "additive" regressors while using log transformation because it makes everything 'multiplicative' from what I understand.

Even if I specify additive, because of log property model would become multiplicative, right?

In this case if I use multiplicative seasonality, or multiplicative regressors that would not make sense, right? I would be applying multiplicative effects twice?? Can you please clarify the reasonable uses here?

Deniz

**Comment by bletham** [comment]
That is correct, the additive model is `y(t) = trend(t) + seasonality(t)`, so if you fit log(y(t)), then
```
log(y(t)) = trend(t) + seasonality(t)
y(t) = exp(trend(t) + seasonality(t)) = exp(trend(t)) * exp(seasonality(t))
```
so it is multiplicative after the inverse transform.

If you have multiplicative seasonality on a log, then you have
```
log(y(t)) = trend(t) * seasonality(t)
y(t) = exp(trend(t) * seasonality(t))
```
which doesn't have a clear interpretation.

I think if you do a log transform to get normal noise and seasonal effects seem to be multiplicative in the log space, then it would be the right model, but I have a hard time imagining a generative model for that so I think it unlikely that you would want to use multiplicative seasonality on a log-transformed time series.

**Comment by deniznoah** [comment]
Thank you very much for the clarification Bletham!

In case of both multiplicative and additive regressors/seasonality, what does the tool do?

Does it first get added to ( trend(t) + regressor1(t) ) * multi_seasonality(t) ) ? Or  does it use multi_seasonality * trend (t) + regressor1(t) ?
