### ISSUE TITLE
Which model is being used during forecasting

### ISSUE THREAD

**Issue by deniznoah** [facebook/prophet#561]
Hi!

For me to do better forecast using this tool I believe I need to understand better what is going on under the hood. Right now I feel like I do not understand well enough the mechanics.

How does the prophet engine work? Does it apply SARIMAX? Holt-Winters? Does it try few methods?

How could we write the regression equation for multiplicative/additive models? It would be great if you can help!

Thank you!
Deniz

**Comment by WouterTromp** [comment]
Indeed read the paper. The underlying model is GAM (General Additive Model; https://en.wikipedia.org/wiki/Generalized_additive_model)

**Comment by deniznoah** [comment]
Hey guys I did read all sections of the tutorial. I still do not understand what the regression equation is ?

**Comment by WouterTromp** [comment]
See here for win-lineair growth:

https://github.com/facebook/prophet/blob/1722e99554f217d72cf82ef7b35e57888fc3c67f/python/stan/win/prophet_linear_growth.stan#L30

**Comment by ryantsullivan** [comment]
@deniznoah not the tutorial their academic preprint https://peerj.com/preprints/3190/
