### ISSUE TITLE
Plot Settings in Prophet Model

### ISSUE THREAD

**Issue by wushengzhong** [facebook/prophet#567]
How can I change default FB color in plotting for model result and components?

**Comment by bletham** [comment]
In Python, the output of the plotting functions is a matplotlib figure. You can then use matplotlib functionality to edit it in any way that you'd like. For instance, this post explains how to change the line color in an existing matplotlib figure: https://stackoverflow.com/questions/41709257/how-to-change-the-plot-line-color-in-python-from-blue-to-black

It's a bit of a pain though, and so if I were in your position I would consider just producing new figures from scratch with the colors that you desire. The entire plot function is only 20 lines of code here:
https://github.com/facebook/prophet/blob/master/python/fbprophet/plot.py#L32
and you could take that code and edit it to replace the color with whatever you'd like.

Same for R, I'd just copy out the plotting function and make edits: 
https://github.com/facebook/prophet/blob/master/R/R/plot.R#L43

**Comment by wushengzhong** [comment]
This is very helpful. Thanks, Ben! @bletham
