### ISSUE TITLE
add time series duration into the models

### ISSUE THREAD

**Issue by bgstn** [facebook/prophet#568]
Hello,

I am wondering if anything tunable for a time series with known duration?

I work on a project with time series that dooms to end in a known date. But based on the historical data,
the model wouldn't know that especially for a long term forecasting. 

like the following (just for illustration).

![image](https://user-images.githubusercontent.com/24259330/41198389-43ee2ea6-6cac-11e8-87c8-560e64b52627.png)

I know the duration and corresponding value of the time series, which is 0. 

One way I can think of is to add another new feature to simulate the dash line.

Is there any other way for prophet, like specify trend changing point for the future or add a constrain for the loss function? Or any other thing?

Thanks,
Frank

**Comment by bletham** [comment]
If you use the logistic growth function, you can specify a capacity, and that capacity can change with time. So setting a capacity that decreases to 0 in the dataframe of future dates for prediction should give you the behavior you're looking for.

**Comment by bgstn** [comment]
Hi, setting the capacity works just sweet! Really appreciate the help! @bletham

**Comment by bletham** [comment]
Great, glad to hear it!
