### ISSUE TITLE
On Multiplicative Modeling

### ISSUE THREAD

**Issue by deniznoah** [facebook/prophet#573]
Hello,

I have two options while modeling the sum of demand forecast coming from over a thousand stores.

a) Total Demand = Trend(t) x Seasonality(t) x Christmas (t) x Easter (t) + Promotional Score(t)
b) Average Demand per Store = Trend(t) x Seasonality (t) x Christmas (t) x Easter (t)  + Average Promotional Score per Store (t)

*** Promotional Score = Sum ( 1 - 1 / Discount ) over stores

Considering prophet's internal mechanics, would you think the second one would make sense? Is it OK to swap forecast variables to averages using variables I have on hand? I have an array of # of stores at hand which I could use to calculate average demand per store.

Is what I am doing with the second option, different than adding another multiplicative regressor? Which would you recommend?

Thank you for your help,
Deniz

**Comment by bletham** [comment]
Forecasting a total or an average would be identical in Prophet. The only difference is a constant scaling (number of stores), and Prophet normalizes the data prior to fitting anyway so there would actually be no difference.

One important thing to note though is that the model in Prophet would be
Demand = Trend(t) * (1 + Seasonality(t) + Christmas (t) + Easter (t)) + Promotional Score(t)

**Comment by deniznoah** [comment]
Hi it is not a constant but an array over time. Different number of stores per week. Would that change above?
Thanks!

**Comment by deniznoah** [comment]
For example: Store ranging is a variable ranging from 200 to 1500. So by dividing "Total Demand` by the active stores that week, I feel like creating a (Trend  * Store Ranging) effect by making this division on the left side of the equation, prior to fitting the model.

Would you agree this is a sound choice?

**Comment by deniznoah** [comment]
I plan to convert my forecast on "Average Demand Per Store" to Total Demand afterwards by multiplying with # of projected stores. Does this look right?

**Comment by bletham** [comment]
I see, if the number of active stores is varying in time then it seems that the average would be the better thing to forecast.
