### ISSUE TITLE
Floor on seasonalities

### ISSUE THREAD

**Issue by shaidams64** [facebook/prophet#575]
Hi, I'm trying to forecast daily transactions and was wondering if there's a way to put minimum threshold for seasonalities or if that makes sense at all. I fit the model on two years of data using logistic growth with floor= 0 and predicting for the next year. I'm getting positive trend , however, because of negative seasonalities I'm still getting negative forecasts for transactions:
![1](https://user-images.githubusercontent.com/13664507/41436180-ae8af286-6fd5-11e8-88cb-d926a9136f3a.png)
![2](https://user-images.githubusercontent.com/13664507/41436182-b206de0c-6fd5-11e8-9361-684bcde40eae.png)
Thanks a lot for your help in advance!
P.S. is it possible/sensible to put floor on confidence bands?

**Comment by bletham** [comment]
I don't think there's anything more that can be done for this at the moment besides just trimming the forecast outputs at 0, like
```
forecast.loc[forecast['yhat'] < 0, 'yhat'] = 0
```
The same could be done for yhat_lower and yhat_upper.

The more correct solution would be to support non-Gaussian link functions (in this case a Poisson link function), there's an issue for that in #337 and I hope we can get that in in the future.
