### ISSUE TITLE
Negative R2 values (for Trend Fit without Seasonality)

### ISSUE THREAD

**Issue by csumaria** [facebook/prophet#576]
I have been using fbprophet to fit lines on historical data without any seasonality. I generate lots of plots to pick the best fit to optimize my fit with respect to the no_changepoints, linear/logistic growth and upper/lower caps. I notice that a big chunk of these plots have negative R^2 value. Why would prophet even return a model-line if the R^2 value is negative in the first place?

**Comment by bletham** [comment]
There are a couple things I can imagine might be going on here. The first is that the optimization may just be failing in some way, and so we're not actually getting the best fit. The second is that we do have priors on the parameters so it's not just a least squares problem (there's some regularization), and it's possible that is leading to the negative R^2. (Although I don't think it's that likely). I would be very interested in seeing an example dataset of this so I could actually figure out what is happening.

**Comment by seanjtaylor** [comment]
I don't think it's likely you could get a negative R^2 in-sample, but out-of-sample that's perfectly reasonable if the time series is difficult to predict.
