### ISSUE TITLE
hyper-parameter for confidence interval

### ISSUE THREAD

**Issue by luofanghao** [facebook/prophet#578]
Hi I am using Prophet on my data, and now I am getting this:

<img width="720" alt="screen shot 2018-06-18 at 5 17 37 pm" src="https://user-images.githubusercontent.com/7426314/41562836-cf11dbf2-731b-11e8-990a-fd0702d5d6f1.png">

In future I want to use this model to do anomaly detection: which means the data points that fall outside of the "band" will be labeled as "anomaly", and right now I want my model to be conservative so I want a larger "band". Is there such parameter that I can tune to achieve this?

Thanks!

**Comment by bletham** [comment]
The `interval_width` parameter can set the percentile for the uncertainty interval. It defaults to 0.8 but can be increased, e.g. to 0.95 for a 95% range. See
```
from fbprophet import Prophet
help(Prophet)
```
to see the detailed description of that (and other) arguments.

**Comment by luofanghao** [comment]
It works. Thanks @bletham !
