### ISSUE TITLE
Issues when multi-processing

### ISSUE THREAD

**Issue by drcrook1** [facebook/prophet#581]
Hey Folks,

For each projection I am building 3 models and merging the projections together to get a good balance of long term and short term impact.  I've noticed that for longer term projections shorter term trends in a varying trend environment can be off.  So I'm building a series of projections for target business objectives.

Anyways; as you can imagine when you have tens of thousands of assets and need to train upwards of 10 models and merge them together in interesting ways leads me to wanting to do this in parallel.

Do you have examples of multi-processing and returning the results into a dictionary?  Below is a simple code sample of what I'm attempting to achieve on a very small subset.  

`from multiprocessing import Process, Pool, Manager

def calc_projections(thing):
    print("Attempting forecast on thing: {}".format(thing))
    forecast, model_10, model_5, model_2 = year_projection(thing)
    return {"forecast" : forecast, "model_10" : model_10, "model_5" : model_5, "model_2" : model_2}
    
manager = Manager()
projections = manager.dict()
params = []
for thing in things[:3]:
    params.append((projections, thing))
with Pool(processes=2) as pool:
    results = pool.starmap(calc_projections, params)`

This just cranks forever.  Very well could be a coding mistake on my side of the house though; but I don't think it is currently.  If I run similar problem sequentially it solves everything in about 5 minutes.

An option I've come up with is to break the workload up across hundreds of docker containers where each container gets a shared portion of the processing time across a cluster of machines and drop results into a database and just bypass the starmap stuff; but Id rather figure out starmap and use the combination of both techniques.

**Comment by saefsky** [comment]
I am seeing the same issue. I was able to track it down to the "predict" step. I tried reducing the number of uncertainty samples and saw no effect. Each individual forecast takes ~8 seconds  when running in series; I've waited up to 20 minutes when running in parallel and the prediction step is still hung. I am using joblib Parallel rather than multiprocessing, but I imagine it is the same underlying issue.

**Comment by saefsky** [comment]
I recently spent some more time looking into this, and was able to track this a step further. I also put together a sample script that allows the devs to recreate the issue, included below. The parallelization only hangs in the predict step when holidays are included (it's possible that this would happen with any additional regressor, but we only tested with holidays). There are two lines where a Prophet object is instantiated: the line that is currently commented will allow the code to run, while the line that is active will cause it to hang.

```
from joblib import Parallel, delayed
import pandas as pd
import numpy as np
from fbprophet import Prophet
import holidays

def proph(df, idx, holidays_df):
    #m = Prophet(**{'yearly_seasonality': True})
    m = Prophet(**{'yearly_seasonality': True, 'holidays': holidays_df})

    m.fit(df)
    future = m.make_future_dataframe(**{'periods': 365, 'freq': 'D'})
    forecast = m.predict(future)

    return {'idx': idx, 'm': m, 'forecast': forecast}


holidays_df = pd.DataFrame()
a = holidays.US(years=[2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]).items()
for i, h in enumerate(a):
    name = ''.join(e for e in h[1] if e.isalnum())
    this_holiday = {'holiday': name, 'ds': h[0], 'lower_window': -1, 'upper_window': 1}
    for key in this_holiday.keys():
        holidays_df.loc[i, key] = this_holiday[key]

tmp = pd.DatetimeIndex(start=pd.datetime(2017,1,1), freq='d', end=pd.datetime(2018,10,1), name='ds')

tmp2 = pd.DataFrame(index=tmp)

tmp2['y'] = np.random.randint(0, 100, len(tmp2))

tmp2 = tmp2.reset_index()

results = Parallel(-1)(
    delayed(proph)(tmp2, x, holidays_df) for x in range(80)
)

```
