### ISSUE TITLE
Is this a statical modelling library or a machine learning library

### ISSUE THREAD

**Issue by umar-siddiqui** [facebook/prophet#583]
I am trying to understand in what category the component which we have built using this amazing library can be labelled under and having a hard time identifying it.

The below link has made me belief that it's statical modelling
https://www.infogix.com/blog/machine-learning-vs-statistical-modeling-the-real-difference/

Any kind input will help tremendously

**Comment by bletham** [comment]
I don't personally see such a clear distinction between the two (a conference like ICML is full of statistical modeling), but would say that this is on the statistics side of that intersection.
