### ISSUE TITLE
Why don't historical yhat in forecast values match input dataframe historical y values and y in model$history ?

### ISSUE THREAD

**Issue by tmuman** [facebook/prophet#584]
Hi,

Maybe I am using the package incorrectly, but when I inspect the historical values in the yhat column of a forecast object produced using prophet, or the values in model$history$y,  I am finding they don't match the input data for the same dates. 

Is this to be expected, does it reflect Prophet's handling of outliers, or does it indicate something is wrong in my model params?

**Comment by bletham** [comment]
This is to be expected. Prophet is a regression model, and specifically assumes
```
y = (trend + seasonal_stuff) + noise
```
The `yhat` is the estimate for `(trend + seasonal_stuff)`, not including noise. So (if the model were correct) we expect there to be a difference between `yhat` and `y`, and it should be whatever the noise variance in the time series is.

This is the same as in a typical linear regression, where the predicted value will not perfectly match the observed values when there is noise (see https://en.wikipedia.org/wiki/Regression_analysis#/media/File:Linear_regression.svg for instance).
