### ISSUE TITLE
Regressor Influence

### ISSUE THREAD

**Issue by rossvoorheesintuit** [facebook/prophet#585]
If I add multiple regressors is it possible to identify the influence of each regressor on the forecast?

**Comment by bletham** [comment]
The forecast dataframe that is returned by `predict` will have a column for every component of the model that gives that component's contribution to the overall foecast `yhat`. There will be a column for each of the regressors and by looking at them you can see how that regressor is being used.

If you're interested in something closer to feature importance, there's a discussion of that in #361.

**Comment by Steviey** [comment]
+1
