### ISSUE TITLE
Prophet's outlier detection method

### ISSUE THREAD

**Issue by tmuman** [facebook/prophet#587]
Hi,

Is there any way to change the sensitivity with which Prophet will remove outliers? 
I'm finding it excludes too much data.

Thanks!

**Comment by bletham** [comment]
Prophet does not have any outlier removal (it relies on outliers that mess up the forecast to be removed manually, see https://facebook.github.io/prophet/docs/outliers.html). Are you just finding that the historical fit does not match all of your past data? Could you post the forecast plot?
