### ISSUE TITLE
Iterations shouldn't be hardcoded

### ISSUE THREAD

**Issue by vruvora** [facebook/prophet#589]
Would it be possible for us to not hardcode the iterations here: https://github.com/facebook/prophet/blob/8d804fce0cf6301c6ee6cdbdde3bcb6d377e7e19/python/fbprophet/forecaster.py#L1003? 

Recommended but would like the possibility of doing early stopping or code in few numbers of iterations if I am only doing it for testing purposes.

**Comment by bletham** [comment]
The default value is a smaller number and not always enough, hence a large value is supplied here. Probably the best thing to do would be to check if iter is supplied in kwargs and add iter=1e4 to kwargs if not.

**Comment by bletham** [comment]
This is done in https://github.com/facebook/prophet/commit/1d398c679d40007ade0dcf81ae0022cceaa1ce8b

**Comment by bletham** [comment]
Pushed to PyPI.
