### ISSUE TITLE
How to set a weekend as a working day?

### ISSUE THREAD

**Issue by wwguo** [facebook/prophet#590]
When a holiday is in the middle of a week, e.g. Tuesday, the government will make an adjustment, e.g. making the next Friday also a holiday and the next Sunday a working day, to create a three days holiday (including Saturday). 

Is it possible to customize the adjustment of setting a weekend as working day?

**Comment by bletham** [comment]
I think the best approach here would be to define a holiday like "Sunday_as_workday" that you would specify the dates of any Sundays that are actually workdays. It should then be able to learn the effect of being a workday on Sunday.

**Comment by wwguo** [comment]
Thanks. The result seems good.

**Comment by bletham** [comment]
Great, glad to hear it!
