### ISSUE TITLE
when install distribute I got error"Command "python setup.py egg_info" failed with error code 1 "

### ISSUE THREAD

**Issue by reneelin2017** [facebook/prophet#594]
I am reading <learn python the hard way> and i try to install pip, distribute, nose and virtualenv. 
I have installed pip, nose and virtualenv, but when i install distribute this error pop up.
I tried "pip3 install --upgrade setuptools" but it still doesn't work, what should I do?

 ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/wj/vyd1fs2j6wscz17r3qnqkw5h0000gn/T/pip-install-31f6e2wb/distribute/

**Comment by bletham** [comment]
I'm going to cloe this since it isn't related to this package.
