### ISSUE TITLE
How to add 120 days and weekly seasonality in PROPHET?

### ISSUE THREAD

**Issue by NEHASHARMA1234** [facebook/prophet#597]
Hi,I am using prophet for seasonailty of 120 days and weekly seasonailty,what parameters i should use?

**Comment by bletham** [comment]
You can use `add_seasonality` to add a seasonality with period 120 (described partway through https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html). You have to specify the fourier order - the default for yearly seasonality is 10, and that would probably be appropriate for 120 day seasonality too.

It sounds like you also want to disable yearly seasonality, which you can do with `Prophet(yearly_seasonality=False)`.
