### ISSUE TITLE
Python3.7.0 - 'StanModel' object has no attribute 'fit_class'.

### ISSUE THREAD

**Issue by elka0711** [facebook/prophet#599]
OS: Win10
Installing  fbprophet  in virtualenv with Python3.6.5 no error. Run's 100%
Installing  fbprophet  in virtualenv with Python3.7.0 gives an error - 'StanModel' object has no attribute 'fit_class'.

**Comment by bletham** [comment]
Could you post the full stacktrace for the error?

In the past this has come up when fbprophet was built with a different version of the dependency packages than it is being used (#249). Maybe try re-installing numpy and pystan?

Can you verify that pystan is working correctly by running this code?
```
import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this will take a minute
y = model.sampling(n_jobs=1).extract()['y']
y.mean()  # should be close to 0
```

**Comment by elka0711** [comment]
The result with your code snipset is:
Generating code
Finished generating code

Gradient evaluation took 0 seconds
1000 transitions using 10 leapfrog steps per transition would take 0 seconds.
Adjust your expectations accordingly!


Iteration:    1 / 2000 [  0%]  (Warmup)
Iteration:  200 / 2000 [ 10%]  (Warmup)
Iteration:  400 / 2000 [ 20%]  (Warmup)
Iteration:  600 / 2000 [ 30%]  (Warmup)
Iteration:  800 / 2000 [ 40%]  (Warmup)
Iteration: 1000 / 2000 [ 50%]  (Warmup)
Iteration: 1001 / 2000 [ 50%]  (Sampling)
Iteration: 1200 / 2000 [ 60%]  (Sampling)
Iteration: 1400 / 2000 [ 70%]  (Sampling)
Iteration: 1600 / 2000 [ 80%]  (Sampling)
Iteration: 1800 / 2000 [ 90%]  (Sampling)
Iteration: 2000 / 2000 [100%]  (Sampling)

 Elapsed Time: 0.026 seconds (Warm-up)
               0.022 seconds (Sampling)
               0.048 seconds (Total)


Gradient evaluation took 0 seconds
1000 transitions using 10 leapfrog steps per transition would take 0 seconds.
Adjust your expectations accordingly!


Iteration:    1 / 2000 [  0%]  (Warmup)
Iteration:  200 / 2000 [ 10%]  (Warmup)
Iteration:  400 / 2000 [ 20%]  (Warmup)
Iteration:  600 / 2000 [ 30%]  (Warmup)
Iteration:  800 / 2000 [ 40%]  (Warmup)
Iteration: 1000 / 2000 [ 50%]  (Warmup)
Iteration: 1001 / 2000 [ 50%]  (Sampling)
Iteration: 1200 / 2000 [ 60%]  (Sampling)
Iteration: 1400 / 2000 [ 70%]  (Sampling)
Iteration: 1600 / 2000 [ 80%]  (Sampling)
Iteration: 1800 / 2000 [ 90%]  (Sampling)
Iteration: 2000 / 2000 [100%]  (Sampling)

 Elapsed Time: 0.035 seconds (Warm-up)
               0.027 seconds (Sampling)
               0.062 seconds (Total)


Gradient evaluation took 0 seconds
1000 transitions using 10 leapfrog steps per transition would take 0 seconds.
Adjust your expectations accordingly!


Iteration:    1 / 2000 [  0%]  (Warmup)
Iteration:  200 / 2000 [ 10%]  (Warmup)
Iteration:  400 / 2000 [ 20%]  (Warmup)
Iteration:  600 / 2000 [ 30%]  (Warmup)
Iteration:  800 / 2000 [ 40%]  (Warmup)
Iteration: 1000 / 2000 [ 50%]  (Warmup)
Iteration: 1001 / 2000 [ 50%]  (Sampling)
Iteration: 1200 / 2000 [ 60%]  (Sampling)
Iteration: 1400 / 2000 [ 70%]  (Sampling)
Iteration: 1600 / 2000 [ 80%]  (Sampling)
Iteration: 1800 / 2000 [ 90%]  (Sampling)
Iteration: 2000 / 2000 [100%]  (Sampling)

 Elapsed Time: 0.027 seconds (Warm-up)
               0.024 seconds (Sampling)
               0.051 seconds (Total)


Gradient evaluation took 0 seconds
1000 transitions using 10 leapfrog steps per transition would take 0 seconds.
Adjust your expectations accordingly!


Iteration:    1 / 2000 [  0%]  (Warmup)
Iteration:  200 / 2000 [ 10%]  (Warmup)
Iteration:  400 / 2000 [ 20%]  (Warmup)
Iteration:  600 / 2000 [ 30%]  (Warmup)
Iteration:  800 / 2000 [ 40%]  (Warmup)
Iteration: 1000 / 2000 [ 50%]  (Warmup)
Iteration: 1001 / 2000 [ 50%]  (Sampling)
Iteration: 1200 / 2000 [ 60%]  (Sampling)
Iteration: 1400 / 2000 [ 70%]  (Sampling)
Iteration: 1600 / 2000 [ 80%]  (Sampling)
Iteration: 1800 / 2000 [ 90%]  (Sampling)
Iteration: 2000 / 2000 [100%]  (Sampling)

 Elapsed Time: 0.027 seconds (Warm-up)
               0.021 seconds (Sampling)
               0.048 seconds (Total)

**Comment by elka0711** [comment]
If I let run my code inside of the same venv37 it throws the following error:

File "C:\Users\...\test_prophet\venv37\lib\site-packages\pystan\model.py", line 472, in optimizing
    fit = self.fit_class(data, seed)
AttributeError: 'StanModel' object has no attribute 'fit_class'

**Comment by elka0711** [comment]
My used packages:
pip list ...
Package         Version
--------------- ---------
cycler          0.10.0
Cython          0.28.3
fbprophet       0.3.post2
kiwisolver      1.0.1
matplotlib      2.2.2
numpy           1.14.5
pandas          0.23.1
pendulum        2.0.2
pip             10.0.1
pyparsing       2.2.0
pystan          2.17.1.0
python-dateutil 2.7.3
pytz            2018.5
pytzdata        2018.5
setuptools      39.2.0
six             1.11.0
wheel           0.31.1

**Comment by bletham** [comment]
Well Pystan is definitely working. It just seems that maybe the Prophet model didn't compile correctly. Could you try re-installing first pystan and then fbprophet both with a --no-cache? What output do you see when installing fbprophet?

**Comment by elka0711** [comment]
Ok, at first re-installing pystan:
pip install pystan --no-cache
Collecting pystan
Downloading https://files.pythonhosted.org/packages/.../pystan-2.17.1.0.tar.gz (13.9MB)
    100% |████████████████████████████████| 13.9MB 12.8MB/s
Requirement already satisfied: Cython!=0.25.1,>=0.22 in c:\users\...\desktop\test_prophet\venv37\lib\site-packages (from pystan) (0.28.3)
Requirement already satisfied: numpy>=1.7 in c:\users\...\desktop\test_prophet\venv37\lib\site-packages (from pystan) (1.14.5)
Installing collected packages: pystan
  Running setup.py install for pystan ... \

Running setup.py install for pystan ... done
Successfully installed pystan-2.17.1.0

**Comment by elka0711** [comment]
That's cracy... now it is run 100%

Initial log joint probability = -2.01779
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes
      99       155.894   0.000457806       4067.72      0.6917      0.6917      147
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes
     199       166.411     0.0108109       50966.9      0.8686      0.8686      256
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes
     299       169.339   0.000430451       2418.03           1           1      372
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes
     399       171.611      0.025327       52861.4           1           1      484
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes
     499       174.523   0.000276406       6483.58           1           1      594
....
Optimization terminated normally:
  Convergence detected: absolute parameter change was below tolerance
  
---------------- ds ------------------------------
numpy.datetime64('2018-12-31T07:00:00.000000000')
---------------- trend ---------------------------
1807.3504797067549
---------------- yhat ----------------------------
1807.3504796062318
---------------- Next24h (Day) -----------
numpy.datetime64('2018-07-13T07:00:00.000000000')
1638.113369698606
1638.1133696951456
---------------- EndOfWeek ---------------
numpy.datetime64('2018-07-15T07:00:00.000000000')
1640.09275110221
1640.092751118008
---------------- EndOfMonth --------------
numpy.datetime64('2018-07-31T07:00:00.000000000')
1655.9278023310428
1655.9278022705557
---------------- EndOfYear ---------------
numpy.datetime64('2018-12-31T07:00:00.000000000')
1807.3504797067549
1807.3504796062318
###################### FINISH ####################

**Comment by elka0711** [comment]
SOLVED
Thanks for the support !!!
I will close the issue

**Comment by bletham** [comment]
@elka0711 Great, glad that did it!

**Comment by jiapei100** [comment]
``` https://github.com/facebook/prophet/issues/599 ``` still goes one...

**Comment by louisguitton** [comment]
@jiapei100 here is an answer that fixes this:
https://github.com/facebook/prophet/issues/775#issuecomment-449139135

**Comment by ivonnics** [comment]
Please, notice that @bletham Just reopened #775 ...

**Comment by tanercam** [comment]
AttributeError: 'StanModel' object has no attribute 'fit_class'

installing pystan's earlier version or installing wit no cache pystan and fbprophet are not working. 

Has anyone a solution to fit model by using fbprophet?

Thanks in advance.
