### ISSUE TITLE
Difference between Python and R packages

### ISSUE THREAD

**Issue by dsizzler** [facebook/prophet#600]
Hi there,

I've noticed that there's quite a big difference when running the same data through the Python package and the R package. In my test, it gave a mean difference of between 8% and 62%.

Please see attached for the input data I used for this test as well as the results.

[FBProphet R Results.zip](https://github.com/facebook/prophet/files/2171118/FBProphet.R.Results.zip)

**Python script:**
`import pandas as pd
from fbprophet import Prophet

df = pd.read_csv('FBProphet Test Data.csv')

m = Prophet(changepoint_prior_scale=0.01, yearly_seasonality=True, weekly_seasonality=True)
m.fit(df)
future = m.make_future_dataframe(periods=(30))
forecast = m.predict(future)

results = forecast[['ds','yhat','yhat_lower','yhat_upper']]

results.to_csv('FBProphet Py Results.csv')`

**R script:**
`library(prophet)

df<-read_csv("FBProphet Test Data.csv")

m<-prophet(df, yearly.seasonality = TRUE, weekly.seasonality = TRUE, changepoint.prior.scale = 0.1)
future <-make_future_dataframe(m, periods = 30)
forecast <- predict(m, future)

results <- forecast[c('ds', 'yhat', 'yhat_lower', 'yhat_upper')]

write.csv(results, "FBProphet R Results.csv")
`

**Python details:**
Python Version: 3.6.5
FBProphet Version: 0.3.post2
OS: Ubuntu 18.04 in VMware

**R details:**
R version: 3.5.0
FBProphet Version: 0.3.0.1 
OS: Windows 10

**Comment by bletham** [comment]
Thanks for the really clear repro setup. I think the issue here is just that the model is being given different settings in each of the versions, probably a typo. In the Py script `changepoint_prior_scale=0.01`, in the R script `changepoint.prior.scale = 0.1`. When I change the Py to be 0.1 the results become very similar to those produced by R.

The results from the two versions can differ in situations where the optimizer terminates badly, but this is not one of those situations so here the R and Py versions should be practically speaking identical.

**Comment by dsizzler** [comment]
Hi @bletham,

Thanks for the response and apologies about the typo. When I correct the script, I do get far more similar results, but still have a mean difference of 13.9% in the yhat_lower and 1.5% in the yhat_upper forecasts. 

Any ideas about what could be causing this?

**Comment by bletham** [comment]
There is stochasticity in how the upper and lower values are computed (it is done with a Monte Carlo sampling procedure). With 100 changepoints I would expect this to have more variability than usual, and that is probably what is causing the difference in those values. This is unrelated to Py or R - if you just run the same code twice in Py for instance, you will see variability in the lower and upper values, and I'd expect here it would be this same amount of variability.

This variability can be decreased by using more Monte Carlo samples in estimating the confidence bands. You can do this with the `uncertainty_samples` argument to `Prophet()` (or `uncertainty.samples` in R), which defaults to 1000. Increasing that to 10000 would significantly reduce variance (but take 10x as long in the `predict` phase and use 10x as much RAM).

**Comment by bletham** [comment]
Sorry, there aren't 100 changepoints here, I was getting mixed up with another issue. Anyway, do check if the variance is replicated across repeated runs within a platform, and if it is reduced by increasing uncertainty_samples.
