### ISSUE TITLE
Can prophet deal with minutely data?

### ISSUE THREAD

**Issue by gongshaojie12** [facebook/prophet#602]
Prophet is a good tool.

But it only support daily data, do not support minute timeseries data.

I hope make_future_dataframe(freq=**) cat support minutely data
How can I solve this problem?

**Comment by WouterTromp** [comment]
Look here: https://facebook.github.io/prophet/docs/non-daily_data.html

**Comment by gongshaojie12** [comment]
@WouterTromp thanks,but this url can't solve my problem.
my data is like this:
ds,y
2018/6/14 14:25,21.68
2018/6/14 14:26,21.65
2018/6/14 14:27,21.72
2018/6/14 14:28,21.78
2018/6/14 14:29,21.71
2018/6/14 14:30,21.67
2018/6/14 14:31,21.65
2018/6/14 14:32,21.64
result is 
![default](https://user-images.githubusercontent.com/6407116/42438523-dab2d4fc-8392-11e8-804e-711bac28ca0c.png)
The result I expected was:
ds,y
2018/6/14 14:25,21.68
2018/6/14 14:26,21.65
2018/6/14 14:27,21.72
2018/6/14 14:28,21.78
2018/6/14 14:29,21.71
2018/6/14 14:30,21.67
2018/6/14 14:31,21.65
2018/6/14 14:32,21.64
2018/6/14 14:33,xx.xx
2018/6/14 14:34,xx.xx
2018/6/14 14:35,xx.xx
2018/6/14 14:36,xx.xx

**Comment by gongshaojie12** [comment]
@WouterTromp Does the value of the 'freq' parameter represent minutes?

**Comment by gongshaojie12** [comment]
@WouterTromp thank you very much！This solved my problem.

**Comment by RSwarnkar** [comment]
> periods=300, freq='min

Hi there, I am using an Hourly sampled data, what should be the `periods` and `freq` argument values?

Data is like: 
```
ds,y
2020-01-20 00:00:00,10940.00
2020-01-20 01:00:00,7078.00
2020-01-20 02:00:00,17649.00
2020-01-20 03:00:00,13070.00
2020-01-20 04:00:00,12391.00
2020-01-20 05:00:00,7810.00
2020-01-20 06:00:00,7465.00
2020-01-20 07:00:00,7882.00
2020-01-20 08:00:00,10762.00
2020-01-20 09:00:00,20626.00
2020-01-20 10:00:00,46015.00
2020-01-20 11:00:00,65593.00
2020-01-20 12:00:00,90323.00
2020-01-20 13:00:00,146207.00
2020-01-20 14:00:00,162514.00
2020-01-20 15:00:00,178279.00
2020-01-20 16:00:00,118995.00
2020-01-20 17:00:00,108726.00
2020-01-20 18:00:00,163868.00
2020-01-20 19:00:00,168032.00
2020-01-20 20:00:00,158714.00
2020-01-20 21:00:00,126804.00
2020-01-20 22:00:00,62207.00
2020-01-20 23:00:00,22746.00
2020-01-21 00:00:00,17147.00
2020-01-21 01:00:00,15217.00
2020-01-21 02:00:00,14600.00
```

**Comment by abhimanyu3** [comment]
Is it worth investing time for minute by minute forecast as on teh home page its mentioned its best suitable for :- 
hourly, daily, or weekly observations with at least a few months (preferably a year) of history

They havent mentioned minute data.

**Comment by RSwarnkar** [comment]
Depends on nature of data.
Mostly data don't show seasonality over minutes. Try aggregation by hourly and check seasonality.

**Comment by abhimanyu3** [comment]
@RSwarnkar I am working on creating a real time alarm system and in which I have to identify anomaly in the incoming data point. So, I don't have that privilege to aggregate the data by hourly as I am already aggregating it to every minute.

**Comment by donggu-kang** [comment]
https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#timeseries-offset-aliases

https://facebook.github.io/prophet/docs/non-daily_data.html#sub-daily-data

**Comment by Ebin04** [comment]
If it's 15 minutes, give parameter as freq='15 min'
