### ISSUE TITLE
Bug using a single change point and mcmc sampling

### ISSUE THREAD

**Issue by blimasouza** [facebook/prophet#608]
Hi guys,

When I try to build a model using a single change point and mcmc sampling:
```python
model_opts = {'changepoints': ['2016-01-01'], 'mcmc_samples': 50}
m = Prophet(**model_opts)
m.fit(sample_ts)
future = m.make_future_dataframe(periods=365)
forecast = m.predict(future)
```
I get the following error:
<img width="734" alt="screenshot 2018-07-11 16 59 40" src="https://user-images.githubusercontent.com/7920501/42596386-d4880968-852b-11e8-954d-ebdf8a7ce1b6.png">

I do not see this issue when I am not using mcmc sampling or when I have more than one change point.

Regards,
Bruno

**Comment by bletham** [comment]
Pushed to PyPI.
