### ISSUE TITLE
Why is the difference between the forecast and the actual？

### ISSUE THREAD

**Issue by gongshaojie12** [facebook/prophet#609]
![default](https://user-images.githubusercontent.com/6407116/42610154-c11c3b28-85c2-11e8-84d8-eab762e9e259.png)
The A,B,C  The predicted and actual differences are very large，How can I eliminate this error?I tried changing the parameter ‘changepoint_prior_scale‘，But not quite satisfactory.Is there any other way?Please help me, thank you

**Comment by vhpietil** [comment]
You have a huge spike there in 2015. That is affecting the yearly seasonality. Try excludin that anomalia from 2015 or explaining it away with regressors/holidays.

Actually all the observations before that spike do not seem very helpful. Maybe you could drop all the history before that spike.

**Comment by gongshaojie12** [comment]
@vhpietil Thank you, I will give it a try.
