### ISSUE TITLE
What is the time interval of trend calculation?

### ISSUE THREAD

**Issue by haru29** [facebook/prophet#610]
Hi,

I tried python prophet model with daily data to obtain smoothed time-series, like:

from fbprophet import Prophet
m=Prophet(); m.fit(data); future=m.make_future_dataframe(periods=365); forecast=m.predict(future)
forecast.head()
Out[489]:
          ds     trend  trend_lower  trend_upper  yhat_lower    ...     weekly_upper    yearly  yearly_lower  yearly_upper      yhat
0 2008-02-01  8.066339     8.066339     8.066339    7.353009    ...        -0.012982 -0.160753     -0.160753     -0.160753  7.892604
1 2008-02-02  8.067649     8.067649     8.067649    7.353227    ...         0.001792 -0.176454     -0.176454     -0.176454  7.892986
2 2008-02-03  8.068958     8.068958     8.068958    7.333478    ...        -0.037184 -0.190390     -0.190390     -0.190390  7.841384
3 2008-02-04  8.070268     8.070268     8.070268    7.346262    ...        -0.004285 -0.202228     -0.202228     -0.202228  7.863756
4 2008-02-05  8.071578     8.071578     8.071578    7.314857    ...         0.002430 -0.211700     -0.211700     -0.211700  7.862308

When I checked initial slope value in model parameters, it was k=0.32214629.
m.params['k']
Out[491]: array([[0.32214629]])

In my understanding, it should be same as the slope of the first few trends. However, according to the above forecast result, the trend slope on the first day is (8.067649-8.066339)/1day = 0.00131, which is obviously different from k.
I guess the time interval for the trend calculation is not 1day, but if so, how long is it?

**Comment by bletham** [comment]
The model is fit on a standardized and scaled version of the data. To be specific, `y` is standardized (subtract mean, divide by standard deviation) and `ds` is mapped to [0, 1]. `m.params['k']` is the initial slope on these transformed variables.

Computing the slope using the `trend` column of the forecast dataframe like you did is probably easier than trying to reverse the standardization and normalization transforms in `m.params['k']`.

**Comment by bletham** [comment]
Correction: `y` is not standardized, rather it is just scaled by the standard deviation (unless you specify a floor): https://github.com/facebook/prophet/blob/master/python/fbprophet/forecaster.py#L273

`ds` is mapped to [0, 1]: https://github.com/facebook/prophet/blob/master/python/fbprophet/forecaster.py#L271
