### ISSUE TITLE
Can prophet deal with hourly data?

### ISSUE THREAD

**Issue by ZED711** [facebook/prophet#611]
Hello. 
I'm trying to forecast data with a frequency of 1 hour during 30 days (720 samples) because the data that I have is during 1 month with a sample rate of 1 sample per hour. 
Is it possible? What are the arguments that I should input in the following line of code:
future_dates = my_model.make_future_dataframe**(periods=36, freq='MS')** ?

**Comment by luofanghao** [comment]
`future_dates = my_model.make_future_dataframe(periods=30*24, freq="1h")`

**Comment by ZED711** [comment]
My ds is something like this: 
112      19-05-2018 01:00 DST
187      19-05-2018 02:00 DST
277      19-05-2018 03:00 DST
376      19-05-2018 04:00 DST
456      19-05-2018 05:00 DST
558      19-05-2018 06:00 DST
634      19-05-2018 07:00 DST
716      19-05-2018 08:00 DST
824      19-05-2018 09:00 DST
903      19-05-2018 10:00 DST
1004     19-05-2018 11:00 DST
1069     19-05-2018 12:00 DST
1180     19-05-2018 13:00 DST
1249     19-05-2018 14:00 DST
1361     19-05-2018 15:00 DST
1431     19-05-2018 16:00 DST
1538     19-05-2018 17:00 DST
1610     19-05-2018 18:00 DST
1697     19-05-2018 19:00 DST
1787     19-05-2018 20:00 DST
1892     19-05-2018 21:00 DST
1961     19-05-2018 22:00 DST
2053     19-05-2018 23:00 DST
2161     20-05-2018 00:00 DST
2241     20-05-2018 01:00 DST
2338     20-05-2018 02:00 DST
2415     20-05-2018 03:00 DST
2515     20-05-2018 04:00 DST
2588     20-05-2018 05:00 DST
                 ...         
62673    17-06-2018 08:00 DST
62763    17-06-2018 09:00 DST
62843    17-06-2018 10:00 DST
62931    17-06-2018 11:00 DST
63027    17-06-2018 12:00 DST
63106    17-06-2018 13:00 DST
63215    17-06-2018 14:00 DST
63294    17-06-2018 15:00 DST
63385    17-06-2018 16:00 DST
63468    17-06-2018 17:00 DST
63551    17-06-2018 18:00 DST
63639    17-06-2018 19:00 DST
63737    17-06-2018 20:00 DST
63839    17-06-2018 21:00 DST
63903    17-06-2018 22:00 DST
64013    17-06-2018 23:00 DST
64096    18-06-2018 00:00 DST
64195    18-06-2018 01:00 DST
64265    18-06-2018 02:00 DST
64351    18-06-2018 03:00 DST
64438    18-06-2018 04:00 DST
64537    18-06-2018 05:00 DST
64625    18-06-2018 06:00 DST
64713    18-06-2018 07:00 DST
64805    18-06-2018 08:00 DST
64905    18-06-2018 09:00 DST
64987    18-06-2018 10:00 DST
65075    18-06-2018 11:00 DST
65169    18-06-2018 12:00 DST
65237    18-06-2018 13:00 DST

When I plot the forecast, there are samples (in black) outside of this interval. Why? 
![d1](https://user-images.githubusercontent.com/41108785/42643605-70c83a58-85f1-11e8-9ca1-ceccec556d08.PNG)

**Comment by ZED711** [comment]
@luofanghao I don't see where that issue can help my problem. I'll reformulate my issue again: 
The data has values between 19-05-2018 01:00 DST until 18-06-2018 13:00 DST, with sample rate of 1 sample per hour. If you see this plot: 
![capturar](https://user-images.githubusercontent.com/41108785/42692114-6f4a2e32-86a2-11e8-8f1d-c3cd8e25fbd3.PNG)
I don't understand how can be plotted samples (points in black) that are out of range of input. Btw, the code 
> future_dates = my_model.make_future_dataframe(periods=30*24, freq="1h")  
seems to be working fine!

**Comment by vhpietil** [comment]
Does you future_dates look reasonable? Are there dates outside you region of interest? I guess you can eliminate those before making predictions. 

I have no idea why there would be datetimes that should not be there. Maybe the datetimes are in such a format that they are read incorrectly.

**Comment by ZED711** [comment]
@vhpietil your comment helped me to remember that my time column was not in datetime type, and the time column is expected to be of the datetime type. Plus, I rectified the input data column that was in "18-06-2018 04:00 DST" form to "18-06-2018 04:00". I deleted "DST" from all the strings basically.
I have an idea of what the problem might be, and I'll explain in next, but I'm struggling a bit in figuring out a solution. 
My dataframe has the following shape. 
> print(df_forecast.shape)  
>(734, 2)

It has 734 dates (ds) and 734 values of data(y). I printed and plotted the graph without forecast and the result was the following: 
![ss](https://user-images.githubusercontent.com/41108785/42695991-d8bd0054-86ae-11e8-8dd3-feb5d5818083.PNG)
![ssss](https://user-images.githubusercontent.com/41108785/42695995-dde9415a-86ae-11e8-81e6-f8612bfc42e7.PNG)
![s](https://user-images.githubusercontent.com/41108785/42696000-e02819be-86ae-11e8-9b3b-1ea2acf9c977.PNG)

As you can see, there are values outside of the range that have non-zero values. I think that's why when I plot the forecast the time axis is between january 2018 until december 2019. Since the input of the forecast period time is:
> future_dates = my_model.make_future_dataframe(periods=30*24, freq="1h") 

It makes sense that the next plot shows values until january 2019:
![lol](https://user-images.githubusercontent.com/41108785/42696543-5d287264-86b0-11e8-8012-66ea37f98532.PNG)

**Comment by vhpietil** [comment]
I am not familiar with python so I can’t help getting rid of those extra days in you training data :(

**Comment by ZED711** [comment]
I've solved the problem. The data input as in dd--mm-yyyy format and the prophet works with yyyy-mm-dd.

**Comment by bletham** [comment]
Yeah, under-the-hood Prophet is using `pd.to_datetime()` to convert the dates and it unfortunately does a lot of guessing at what the right format is, and can guess wrong sometimes without warning (the case here).
