### ISSUE TITLE
Allow constant trend

### ISSUE THREAD

**Issue by luofanghao** [facebook/prophet#614]
Hi,

Is there a way to force the trend to be flat? My data has strong daily and weekly seasonality, rather than a strong trend change pattern. Is there a way to make a flat trend on model?

example:
<img width="728" alt="screen shot 2018-07-16 at 11 34 02 am" src="https://user-images.githubusercontent.com/7426314/42767982-5165baac-88ec-11e8-9d4f-56f1f70d01b0.png">

right now the trend change is too strong, so if I use the current model to predict, prediction will go down (because of the trend). I want to avoid this by making the trend flat. What really matters in my data should only be the seasonalities.

**Comment by mcaviel** [comment]
Have you looked at `changepoint_prior_scale` this should help you adjust the trend flexibility 
[https://facebook.github.io/prophet/docs/trend_changepoints.html](url)

**Comment by luofanghao** [comment]
@mcaviel thank you.

I have tried but turn down `changepoint_prior_scale` does not really help. And the acceptable smallest value for `n_changepoint` is 1. So the trend still not be flat.

**Comment by luofanghao** [comment]
I am thinking about taking the mean value of predicted `trend` values, and manually re-calculated the `yhat` value. This might work. But I haven't figure out the formula yet. Does anyone know it?

```py
fcst["yhat_upper"] = fcst["trend_upper"]*fcst["multiplicative_terms_upper"]*( fcst["daily_upper"] + fcst["weekly_upper"])
```

**Comment by luofanghao** [comment]
@bletham thank you so much for the concrete information.

And you are right, I realized that my data does not conform very well to the model, especially if I want to make a constant trend. However, it is okay that the "constant-trend model" does not fit the data very well. Because what I am doing is an anomaly detection project, and actually the middle week should be considered to be anomaly. That is what I mean, even seems like there is a trend, but it actually is not.

**Comment by bletham** [comment]
That's reasonable, and a flat trend seems like a good thing to support in the future. In the meantime, the only way this could be done would be by modifying the Stan code to put a very tight prior on `k` that forces it to be close to zero. (Currently there is no prior on `k`).

**Comment by luofanghao** [comment]
@bletham Thank you. Hope we can have this new feature in the future.

**Comment by kaleming** [comment]
Now with #501, is there a easy way (changing k) to make this possible ?

Could you give some hint how to do that ?

**Comment by sammo** [comment]
I believe Ben means we need to set the prior scale for `k` to something much smaller than 5, what it currently is set to here
https://github.com/facebook/prophet/blob/a3ae4715bbc0a18cde35f7b199a671f53df80168/python/stan/unix/prophet.stan#L109

Please correct me if I'm wrong @bletham . 
I tried doing that and it sure does help set a flat trend. I'm facing a few questions though. It seems like it it works better for a logistic growth? It also seems like a very low scale for the trend would throw the optimizer in a limbo. In multiple cases it's starting with a negative log join probability! That was the case for 0.001. Higher scales are resulting in a significantly positive to negative growth coefficient... Any insight on what should this number be to get a flat linear trend, @bletham ?

**Comment by bletham** [comment]
@sammo Yes, k is the initial slope and so a very tight prior will force it to be very close to 0. And then if n_changepoints=0, it will stay flat at 0. There is another parameter m that sets the y intercept and that will still be fit.

I'd expect that to work well for the linear trend. For the logistic I have less intuition - there isn't a y-intercept term in the logistic growth function rather there is an x offset, so I think taking k close to 0 would force the trend to be 0.5 * cap? If this is a bad fit then that would definitely mess up the optimizer.

If you're anyway modifying Stan code, then there's a cleaner way of doing this by just directly editing the trend function here:
https://github.com/facebook/prophet/blob/a3ae4715bbc0a18cde35f7b199a671f53df80168/python/stan/unix/prophet.stan#L74

If you replace that with
```
return m;
```
then it will fit a flat trend with y-intercept m (which is fit). The same modification has to be made in the Py/R definition of the trend, which is used at predict time:
https://github.com/facebook/prophet/blob/a3ae4715bbc0a18cde35f7b199a671f53df80168/python/fbprophet/forecaster.py#L1199
That entire function would be replaced by 
```
return m * np.ones_like(t)
```
to match the modified Stan.

That requries 2 edits but doesn't make you have to worry about super tight priors or inference issues that may come as a result.

**Comment by sammo** [comment]
@bletham thanks for the thorough explanation. That makes sense. There might be a few cases where this would be helpful for some of the time series I'm working with so I may use it...

**Comment by MrBordeaux** [comment]
I am not sure how elegant it is, but you can get prophet to force a constant trend by setting growth='logistic', cap = last * (1 + epsilon), floor = last * (1 - epsilon), where last is the latest y-value you have, and epsilon is a very small number

**Comment by Rosina9700** [comment]
Just adding a +1 that being able to manually configure the growth curve would be great. I'm also attempting to use Prophet for anomaly detection and find that often, the anomalous behavior leads to unwanted growth trends. I appreciate that this is great functionality for forecasting but not so great for anomaly detection (which is not the intended case for Prophet). But if I could fix the trend to be zero, then the anomalous period would be easier to identify and Prophet would very applicable to anomaly detection too.

**Comment by ryankarlos** [comment]
@Rosina9700 Ive just submitted a PR for this - although my working solution sets a flat growth rather than allowing tightening of the growth prior.

**Comment by Rosina9700** [comment]
@ryankarlos and @bletham thanks for tackling this and getting it merged! Looking forwards to trying it out!

**Comment by bletham** [comment]
@Rosina9700 if you do try this out and have a nice example that you can share the data for, please do post it so we could potentially use it in the documentation!

**Comment by bletham** [comment]
I'm leaving this open until it gets ported to R too.

**Comment by bletham** [comment]
This feature is now in R and in CRAN in the latest v1.0 release.
