### ISSUE TITLE
Python FBprophet how to let other columns be used as weight in forecasting

### ISSUE THREAD

**Issue by JafferWilson** [facebook/prophet#615]
I am trying to forecast the close prices from the data available. I have started using the framework FbPropet to forecast the values. See the following I tried:
from fbprophet import Prophet

```
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['figure.figsize']=(20,10)
plt.style.use('ggplot')
df = pd.read_csv("EURUSD_M1.csv",sep='\t',encoding="utf-16",usecols = [0,1,2,3,4])
df.head(5)
```
The output:

```
Time    open    high    low close
2018.05.31 23:59:00 1.16928 1.16935 1.16906 1.16906
2018.06.01 00:00:00 1.16879 1.16906 1.16852 1.16855
2018.06.01 00:01:00 1.16871 1.16884 1.16871 1.16879
2018.06.01 00:02:00 1.16879 1.16900 1.16872 1.16895
2018.06.01 00:03:00 1.16895 1.16895 1.16883 1.16890
```
Next I tried:

```
df.rename(columns={'Time':'ds'}, inplace=True)
df['y'] = np.log(df.close)
df.head(5)
```
output:

```
ds  open    high    low close   y
2018.05.31 23:59:00 1.16928 1.16935 1.16906 1.16906 0.156200
2018.06.01 00:00:00 1.16879 1.16906 1.16852 1.16855 0.155764
2018.06.01 00:01:00 1.16871 1.16884 1.16871 1.16879 0.155969
2018.06.01 00:02:00 1.16879 1.16900 1.16872 1.16895 0.156106
2018.06.01 00:03:00 1.16895 1.16895 1.16883 1.16890 0.156063
```
I know that ds and y are the input variable for the model training in the fbprophet. Hence, got it placed in the dataframe itself.

But as one can see that I am only using the close price in the column y. And that is how the weights will get generated in the framework.

I wanted to put the weight of open high low on the prediction. But I am not getting any idea how I can put the complete data as input to predict the output using the fbprophet.

Kindly, suggest me a way if there is any.

Edited

I have already tried using the add_regressor but had came across issues using it while plotting and predicting:
```

future_Time_frame = model.make_future_dataframe(periods=4000, freq='T')
display(future_Time_frame.tail(10))
```
Output:

```
ds
2018-07-02 18:30:00
2018-07-02 18:31:00
2018-07-02 18:32:00
2018-07-02 18:33:00
2018-07-02 18:34:00
2018-07-02 18:35:00
2018-07-02 18:36:00
2018-07-02 18:37:00
2018-07-02 18:38:00
2018-07-02 18:39:00
```
Next:

`forecast = model.predict(future_Time_frame.tail(4000))`
The error:
```

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-85-a7ed34b7336a> in <module>()
----> 1 forecast = model.predict(future_Time_frame.tail(4000))

/usr/local/lib/python3.5/dist-packages/fbprophet/forecaster.py in predict(self, df)
   1036             if df.shape[0] == 0:
   1037                 raise ValueError('Dataframe has no rows.')
-> 1038             df = self.setup_dataframe(df.copy())
   1039 
   1040         df['trend'] = self.predict_trend(df)

/usr/local/lib/python3.5/dist-packages/fbprophet/forecaster.py in setup_dataframe(self, df, initialize_scales)
    249             if name not in df:
    250                 raise ValueError(
--> 251                     'Regressor "{}" missing from dataframe'.format(name))
    252 
    253         df = df.sort_values('ds')

ValueError: Regressor "high" missing from dataframe
```

**Comment by JafferWilson** [comment]
@bletham Thank you for your suggestion and clarification. Now let me clear my point.
By the word weights, I mean that the model decision must use the multiple inputs to predict the possibility of the forecast that I mean to happen. In my case, I want that fbprophet should not only be using the ds and y values but the open, high, and low values must also be used, as helpful variables in deciding what must be the outcome. 
I hope that my point is clearer this time sir.

**Comment by bletham** [comment]
Thanks for the clarification. If you know the other variables in the future then this would be a good place for an extra regressor, but since you don't it means you would have to forecast all of them jointly. This is not currently possible, and is being tracked in #49. I don't think there is anything better you can do with Prophet here than to make independent forecasts.

**Comment by JafferWilson** [comment]
Thanks for your reply. I hope that this feature comes soon.

**Comment by RSwarnkar** [comment]
@bletham Can you please indicate some resource for using the added regressors (_exogenous_ variables) in `fbprophet`?

**Comment by benmwhite** [comment]
@RSwarnkar [Here are the examples from the doc page.](https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#additional-regressors), and some implementation details with code location links in [another related thread,](https://github.com/facebook/prophet/issues/1201#issuecomment-551300482) hope that helps.
