### ISSUE TITLE
How to improve accuracy of daily forecast

### ISSUE THREAD

**Issue by ZED711** [facebook/prophet#616]
Hello everyone. 
I have 1 month of data with a sample rate of one rate per hour. To test the accuracy, I used 3 week of input data and forecasted the 4th. Then, I compared each sample of the 4th week with the sample that was forecasted. 
The plots look like this: 
Plot of data **without** forecast:

![withoutforec](https://user-images.githubusercontent.com/41108785/42814583-911fd026-89bc-11e8-8df9-cc6d35e78fc2.PNG)

Plot of data **with** forecast:

![withforecast](https://user-images.githubusercontent.com/41108785/42814586-94099380-89bc-11e8-8ea7-4f013bde4019.PNG)

I calculated the error between the samples (the 4th week samples that I had of real data and the ones which were forecasted [yhat]) and got an average error of 43%. **I tried to put weekly_seasonality and daily_seasonality to TRUE but there were no major variations**. Plus, I **even tried to change changepoint_prior_scale:** to higher values like 0.45, 0.55, 0.65 but **the error was near 70-75%** and as I dropped changepoint_prior_scale drops the error decreases. **The best that I've measured was with 0.05 and got an error of 43%.** 
Is there anything else I can do?

**Comment by ZED711** [comment]
They look a bit diferent, I compared each sample of the 4th week data with each sample of the yhat and got an average error of 43%. 
What is the idea behind the code? I don't know R, is there any topic with a similar code in python?

**Comment by ZED711** [comment]
@bletham Ok! I'm starting to implement it in Python, but I'm having some difficulties because I don't know R. Do you have any similar script with this code but in Python?

**Comment by luofanghao** [comment]
@ZED711 there is another way to do is separate weekends' data out. @bletham mentioned this in: #524 

However @bletham the plotting function seems does not work when merge the forecasts. I obtained wired result when I plot it.
<img width="1005" alt="screen shot 2018-07-20 at 4 20 39 pm" src="https://user-images.githubusercontent.com/7426314/43023431-def3bc12-8c38-11e8-899c-0bc4706744a6.png">

code is like:

```py
fcst2 = fcst2.append(fcst1)
fig = m2.plot(fcst2)
```

**Comment by ZED711** [comment]
![ff](https://user-images.githubusercontent.com/41108785/43065297-5149a96c-8e59-11e8-81b1-4a7f0a0300f2.PNG)
The plot is a bit weird. I'll try to implement the other solution that @bletham said (the code in R).

**Comment by ZED711** [comment]
> series.order <- 3
**> regressors <- fourier_series(df$ds, 1, series.order) %>% 
>   as_data_frame %>% 
>   cbind(ds = df$ds) %>% 
>   filter((lubridate::wday(df$ds) %in% c(1,7)))**
> 
> # Initialize prohet
> m <- prophet(weekly.seasonality = TRUE)
> 
> # Add regressors to the model one by one
> for (i in 1:(length(regressors)-1)) {
>   m <- add_regressor(m, paste0("V", i))
> }
> # Join regressors to the data, replace NAs with zeros and fit
> m <- fit.prophet(m, df = df %>% left_join(regressors) %>% replace(is.na(.), 0))
> 
> # Create future dataframe and extra regressors for those datetimes
> future = make_future_dataframe(m, 24*7, freq = 3600)
> 
> series.order <- 3
> future_regressors <- fourier_series(future$ds, 1, series.order) %>% 
>   as_data_frame %>% 
>   cbind(ds = future$ds) %>% 
>   filter((lubridate::wday(future$ds) %in% c(1,7)))
> 
> # Profit
> forecast <- predict(m, future %>% left_join(future_regressors) %>% replace(is.na(.), 0)) 
> 
> plot(m, forecast)
> 

I don't understand very well the code in bold. Could someone explain, please?

**Comment by vhpietil** [comment]
You make fourier series with df$ds timestamps. Function returns matrix without timestamps, so you add those timestamps to the series matrix. Then you filter out all but weekends because you want to apply extra regressors on weekends only.

**Comment by ZED711** [comment]
I've implemented it in python. With period = 2 and series_order = 3 I get a 40% error .... it dropped a bit but not that much. Tomorrow I'll try to use other values and get a lower error. What values do you think are best for period and series_order?

**Comment by OlgaLyudchik** [comment]
Hello! I am currently facing the same issue and the solution of @vhpietil seems very promising! However, I am quite new in Python and unfortunately don't know R. Can I ask @ZED711 to share his Python version? That would save my life!

**Comment by ZED711** [comment]
`def weekend_regressors (series_order, dates, period):
    regressors = Prophet.fourier_series (dates, 2, series_order)
    regressors_df = pd.DataFrame(data=regressors)
    dates_no_index = dates
    regressors_df_ds = pd.DataFrame(data=dates_no_index.tolist()) 
    regressors_df['ds'] = regressors_df_ds # adicionar coluna ds ao dataframe
    regressors_df.ds = pd.to_datetime(regressors_df.ds)
    regressors_df.set_index('ds',inplace = True)
    regressors_df = regressors_df[regressors_df.index.dayofweek >=5] 
    return regressors_df

def merge_forecast_regressors(df_f, df_r):
    df_f.set_index('ds',inplace = True)
    df_final = df_f.merge(df_r,how = 'left', left_index=True, right_index=True)
    df_final = df_final.fillna(0)
    df_final = df_final.reset_index()
    df_final.rename(index=str, columns={0: "V0", 1: "V1",2:"V2",3:"V3",4:"V4",5:"V5"}, inplace = True)
    return df_final`

`
series_order = 3
period = 2
regressors_df = weekend_regressors(series_order,df_forecast['ds'],period)

my_model = Prophet(interval_width=0.8, weekly_seasonality = True,changepoint_prior_scale = 0.8)

for i in range(0,len(regressors_df.columns)):
    my_model.add_regressor("V" + str(i))

df_final = merge_forecast_regressors(df_forecast,regressors_df)
my_model.fit(df_final)

df_future = my_model.make_future_dataframe(periods=9*24+14, freq="1h")

series_order = 3
period = 2
future_regressors_df = weekend_regressors(series_order,df_future['ds'],period)
df_future_final = merge_forecast_regressors(df_future,future_regressors_df)

forecast = my_model.predict(df_future_final)
my_model.plot(forecast)`

The variable "df_forecast" is the dataframe where you have your data stored. 
Check the argument of the this line of code and apply how many days you want to forecast (I wanted 9 days and 14 hours):

> df_future = my_model.make_future_dataframe(periods=9*24+14, freq="1h")

"df_future" is the dataframe which already has the space for the information you want to forecast (yhat).

**Comment by OlgaLyudchik** [comment]
@ZED711 Thank you very much! For my data the error is rather high, model almost does not capture weekend extreme values. I will also try to tune series_order and period parameters.
![image](https://user-images.githubusercontent.com/15955658/43273251-4345b806-90fc-11e8-9f9a-0c33558b90d9.png)

**Comment by ZED711** [comment]
@OlgaLyudchik  if you know a good combination of both, please share. I'm trying to figure out one to optimize it.

**Comment by ZED711** [comment]
Thanks for help. The Mean Absolute Error is good, the MAPE is not that good because of the values that are close to 0.
