### ISSUE TITLE
Extra Regressors and Missing Data

### ISSUE THREAD

**Issue by rossvoorheesintuit** [facebook/prophet#621]
I have multiple extra regressors I want to add to add. Some of these regressors have missing values over time. I noticed that if I build a forecast with just one regressor and the regressor has missing values then it fits and predicts just fine. However, if I add multiple regressors and one of the regressors is has missing values then it doesn't fit well at all  and the forecast is completely off. Any suggestions on how to get around this?

**Comment by APramov** [comment]
Could you post some reproducible example?
