### ISSUE TITLE
Forecast with Regressors and Multiplicative Seasonality

### ISSUE THREAD

**Issue by rossvoorheesintuit** [facebook/prophet#622]
I am trying to understand the output of the forecast and how you get to yhat.
What is the formula that is used to get yhat?
The variables I have are:
trend, regressor1, regressor2, extra_regressors_multiplicative, multiplicative terms, yearly.

**Comment by APramov** [comment]
If we start from the example in the guide by using the `example_retail_sales.csv` data, we would have something like:
```
  df <- read.csv("C:/Github/prophet/examples/example_retail_sales.csv")
  m <- prophet(df, seasonality.mode = 'multiplicative')  
  future <- make_future_dataframe(m, periods = 120, freq = 'month')
  fcst <- predict(m, future)
  
# Reconstruct following the model structure described [here](https://github.com/facebook/prophet/issues/563):
# where a = additive and m = multiplicative
`y(t) = trend(t) * (1 + X_m(t) beta_m) + X_a(t) beta_a`

 reconstructed <-  fcst$trend * (1 + fcst$multiplicative_terms) + fcst$additive_terms + fcst$yearly
 mean(reconstructed - fcst$yhat )
# 
```
There is some residual difference (small) that I am not sure where it comes from...
Following this logic, the y_hat for you would be the same but including the multiplicative regressors inside the brackets and adding the regressor1 and regressor2 outside.

**Comment by rossvoorheesintuit** [comment]
Thanks for responding. Is this what you are suggesting ?

reconstructed <-fcst$trend * (1 + fcst$multiplicative_terms + fcst$extra_regressors_multiplicative) + fcst$regressor1 + fcst$regressor2 + fcst$additive_terms + fcst$yearly
