### ISSUE TITLE
slope/equation of trend line

### ISSUE THREAD

**Issue by rds99** [facebook/prophet#623]
does the output contain slope / equation for the trend line?

**Comment by APramov** [comment]
From what I understood, what you can get are the posterior distributions for the whole trend-line (not the individual components), e.g. by doing `predictive_samples(myfit, future)$trend`.

But yes, it would be also nice to know something about the growth rate, rate adjustment etc. at each t from e.g. formula (4) on page 10 from the prophet paper. I haven't done Bayesian Inference in a long, long time (and have never worked with GAM), but I assume that the model puts calculates posteriors for all the parameters that are in the trend function and then "aggregates" them to have one final posterior for the whole trend equation (that is accessible via `predictive_samples`, is this correct?)

**Comment by bletham** [comment]
Yes that is best way to grab the posterior for the model parameters. One thing to note however is that the parameters are fit on a transformed data, and so they would not correspond directly to the slope that you see in the plot. See #610 for a recent discussion about the transformations.
