### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-wfumbo/MySQL-python/

### ISSUE THREAD

**Issue by aliaa37** [facebook/prophet#624]
When I run pip install MySQL-python  on Python 2.7.15 , UBUNTU OS 17.10 I get the following error 
Collecting MySQL-python
  Using cached https://files.pythonhosted.org/packages/a5/e9/51b544da85a36a68debe7a7091f068d802fc515a3a202652828c73453cad/MySQL-python-1.2.5.zip
    Complete output from command python setup.py egg_info:
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-CN81Ff/MySQL-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-CN81Ff/MySQL-python/

**Comment by bletham** [comment]
This is for a different package so I'll close it.
