### ISSUE TITLE
how prophet train the model in parallel?

### ISSUE THREAD

**Issue by gongshaojie12** [facebook/prophet#625]
I have 1 million models to train. How to complete in a short time？For example, training 1 million models in one day. Is there any way to achieve this? Thanks!

**Comment by APramov** [comment]
I don't think it has a built-in functionality for this like e.g. `caret` package does, but you could check out the `foreach` package, it might be helpful (see section 5 of its vignette [here](https://cran.r-project.org/web/packages/foreach/vignettes/foreach.pdf))

**Comment by gongshaojie12** [comment]
Ok, I will give it a try, thank you very much. @APramov

**Comment by APramov** [comment]
No prob, let us know the results - I am also curious to test it out. :)

**Comment by IronistM** [comment]
You can also use the pattern of fitting many models that Hadley lays out in R for Data Science's chapter [Many Models](http://r4ds.had.co.nz/many-models.html). In order to use it on parallel you can resolve to [`furrr`](https://github.com/DavisVaughan/furrr), eg like the snippet below.

```R
library(furrr)
future::plan(multiprocess)

data %>% # A dataframe with dimensions and nested the `ds, y` in `data.tbl`
      mutate(
        m = furrr::future_map(
          data.tbl,
          prophet::prophet,
          daily.seasonality = TRUE,
          holidays = holidays,
          ...
        )
     )
```
