### ISSUE TITLE
Backwards forecasting

### ISSUE THREAD

**Issue by Finecoh** [facebook/prophet#626]
I'm trying to use prophet R version to forecast retail sales. I have data from Jul'17 to Jul'18 and would like to predict the period Jan'17 to Jun'17, so I would like to predict the past. I'm not being able to point make_future_dataframe into past periods, is it possible to do that? Thanks.

**Comment by APramov** [comment]
I think an easy way would be to can create an artificial time-series from the data you have (the values would have to be in reverse order) and then forecast 6 months ahead. I haven't seen an option to back-cast directly from the `prophet `function itself.

**Comment by vhpietil** [comment]
I don't think you have to use make_future_dataframe -function. Check how the future dataframe should look like and construct one by using e.g. data_frame and seq -functions to make dates in the history that you want to "forecast" (backcast?)

Or maybe construct future dataframe with long enough horizon and use dplyrs mutate to replace ds=ds-180. This should give you a dataframe with start date 180 days before your data.

May I ask why are you trying to forecast the time before you data?

**Comment by Finecoh** [comment]
Thanks @vhpietil, I'll try that. 

My company started collecting this data only in July 2017, but we have clients who need to see the whole fiscal year for comparison purposes. I'm looking at the options we have to do that.

**Comment by Finecoh** [comment]
In case someone stumbles upon this, @vhpietil suggestion worked. You can manually define a data frame with a named column "ds" for the period you want to forecast, for example Jan'17 - Dez'17, and then use the predict function providing only Jul'17 - Dez'17 data. It will predict the series values for the Jan'17 - Jun'17.

Thanks
