### ISSUE TITLE
C++ 

### ISSUE THREAD

**Issue by rds99** [facebook/prophet#628]
Hi, 
is it possible to make a C++ binary so that I can embed prophet into C++ code and dont need to run R or Python?

**Comment by bletham** [comment]
You could use Stan directly to compile the model into a binary but all of the code to turn your dataframe into the data that Stan expects, and to convert the outputs into actual model predictions, is all in R and Python so you'd have to re-write all of it in C++ if you wanted to have that functionality in C++.
