### ISSUE TITLE
Campaigns in Prophet

### ISSUE THREAD

**Issue by schroedingerkat26783** [facebook/prophet#631]
I´m having a  hard time predicting a campaign because I´m a newbie in Time Series and R programming.

![image](https://user-images.githubusercontent.com/41993243/43517215-334864fe-9588-11e8-9f33-fff45ffb2aac.png)

![captura](https://user-images.githubusercontent.com/41993243/43517019-a054b80a-9587-11e8-8b05-229c425ee583.PNG)
As you can see in the image, Prophet catches a change of trend but in our case the first day of the campaign is a peak point and decreases later.  Prophet says that the first day the trend begins to grow and draws the peak in the middle of the campaign while our real data has a valley.

How can I correct this or, at least, improve my model?

Thank you in advance

**Comment by vhpietil** [comment]
Please include component plot (prophet_plot_components) so that we can see what goes in which component. 

You can use holidays to include regressors on your campaings. Components of prophet cannot capture that rapid change in you campaing. Because of the spikes in the beginning and the end of you campaing, you might want to include start and end as separate (or additional) holidays.

**Comment by vhpietil** [comment]
Please include the component plot with campaing holidays too

**Comment by schroedingerkat26783** [comment]
![image](https://user-images.githubusercontent.com/41993243/43520111-1994eef6-9592-11e8-9981-117572c2c621.png)
![image](https://user-images.githubusercontent.com/41993243/43520140-3137f7ec-9592-11e8-9dc4-6308cac32283.png)

**Comment by vhpietil** [comment]
You have included only the first days of campaing. Therefore prophet fit the rest of the campaing with other components. Make your holidays last as long as the campaing to make it fit better

**Comment by schroedingerkat26783** [comment]
![image](https://user-images.githubusercontent.com/41993243/43521806-9b411952-9597-11e8-83c0-e32c7428f20c.png)
![image](https://user-images.githubusercontent.com/41993243/43521821-a9d83eaa-9597-11e8-849e-d339378b0782.png)
 When a specify the duration of the entire campaign the model adjusts way better but the forecast is even worse.

**Comment by bletham** [comment]
It looks like the discussion here has wrapped up so I'm closing the issue, but please re-open if there is more to address.
