### ISSUE TITLE
how to forecast the ‘yhat_upper’ and ‘yhat_lower’ in Prophet?

### ISSUE THREAD

**Issue by AhaEdgar** [facebook/prophet#637]
hi,
      I’ve read the paper and a part of the source code， but I still don‘t understand how to  forecast the ‘yhat_upper’ and ‘yhat_lower’？ anyone willing to share their own opinions？

**Comment by AhaEdgar** [comment]
@bletham   thanks for your answer ^_^ ~

Another question： `y_lower'` and `y_upper'` calculated by  TP`lower_p` and TP`y_upper`   in the `uncertainty_samples (by default 1000)`. 

` lower_p = 100 * (1.0 - self.interval_width) / 2`
`upper_p = 100 * (1.0 + self.interval_width) / 2`
in code :
[](https://github.com/facebook/prophet/blob/master/python/fbprophet/forecaster.py#L1233)

however,  how to calculate  1000 parameters in the `uncertainty_samples` ？
why does `Prophet ` get the uncertainty interval in this way?

**Comment by bletham** [comment]
The `uncertainty_samples` is needed because Prophet uses Monte Carlo sampling to simulate future trend changes. The trend uncertainty thus relies on having a large-ish number of these simulations from which we can compute the lower_p and upper_p quantiles.

**Comment by pginand** [comment]
just wanted to comment that @bletham  has done an excellent job answering questions and prophet has been the best forecasting tool I have come across. I use it as my baseline for forecasting and have yet found another method that beats it.

**Comment by Sreedhanya-K** [comment]
I am using fbprophet for anomaly detection, and **for the same data sets, the anomalies it pick are different for different runs in my laptop**. The number of anomalies and the anomalies which the code pick up are different for 1st, 2nd third.. runs. I am confused, how can I use this , though it is giving good results many a times. The false positives are too many in a few runs.
Can someone please help me to fix this.

**Comment by yasirroni** [comment]
To be clear, than we can say that with `interval_width=0.8` (default), we have [confidence interval](https://en.wikipedia.org/wiki/Confidence_interval) (0.8) that the forecasted value lies in the range of `yhat_upper` and `yhat_lower`? @bletham

**Comment by yasirroni** [comment]
> To be clear, than we can say that with `interval_width=0.8` (default), we have [confidence interval](https://en.wikipedia.org/wiki/Confidence_interval) (0.8) that the forecasted value lies in the range of `yhat_upper` and `yhat_lower`? @bletham

Finally found the answer [here](https://github.com/facebook/prophet/issues/1626#issuecomment-674292968). Yes, `interval_width` is like CI on bayesian. Thank you @bletham. You really did well.

But to be honest, the [docs](https://facebook.github.io/prophet/docs/uncertainty_intervals.html) did not clearly state that.

**Comment by ngae-nage** [comment]
I have a question : why my yhat is not the center of the interval (yhat_lower yhat_upper) ?
