### ISSUE TITLE
Excluding a specific day from historic and predicted data

### ISSUE THREAD

**Issue by nthang1** [facebook/prophet#638]
Hi all,

I'm aware this has been addressed by non daily data, however as a relative newcomer to Python, I am struggling to find a way to exclude only Monday from my dataset. My data set has y values for only Tuesday-Sunday throughout the year. Is there an example of how this can be done? 

TIA

**Comment by vhpietil** [comment]
Just remove all mondays from your training and future datasets

**Comment by nthang1** [comment]
Thanks vhpietil,

I guess I should have been a little clearer, 

Do you mean that I should just drop Mondays from my dataset and then fit against this? Or is there a way, much like the example of using only data from 12am to 6am in the prophet documentation that I can get my model to ignore the Monday values?

**Comment by vhpietil** [comment]
Yeah, just drop mondays from your dataset at fit against that. I am pretty sure it works :)

**Comment by nthang1** [comment]
Thanks for your help Yuliyan,

The future data frame was my issue as you have explained above. I wasn't originally very clear! Thanks again.
