### ISSUE TITLE
Multiplicative seasonality mode is not works 

### ISSUE THREAD

**Issue by beloteloff** [facebook/prophet#639]
Hello!
I installed the latest version of the library and here is my code,which works fine , but without mode of seasonality.

`Prophet(seasonality_mode='multiplicative').add_regressor('days_happy',prior_scale=1,standardize=False).fit(df)`

But I have this error in this line:
`TypeError: __init__() got an unexpected keyword argument 'seasonality_mode'`

P.S. OS - Debian Jessie, python version - 3.4.

**Comment by bletham** [comment]
Yeah I'm a bit surprised here since you do have the latest version installed. Could you copy the output of
```
help(Prophet)
```
up to the point where it says "Methods defined here:"

I want to see that it is coming from the right module, and what arguments are specified there.

**Comment by bletham** [comment]
Ok `seasonality_mode` is not there so this is not the latest version. I'm wondering if maybe you have multiple versions installed and they are getting mixed up. Try running
```
sudo pip3 uninstall fbprophet
```
a few times until it tells you that there is no package fbprophet, and then reinstall with
```
sudo pip3 install fbprophet
```

**Comment by beloteloff** [comment]
Thanks, it was a problem only coz I use virtual env.
