### ISSUE TITLE
' .predict' method takes too much time to run

### ISSUE THREAD

**Issue by ZED711** [facebook/prophet#641]
Hello everyone. 
I'm currently doing a forecast with 3 months of data and trying to make a forecast of 1 month. However, my program takes too much time to run. 

> my_model = Prophet(interval_width=0.8,changepoint_prior_scale = 0.1)
> df_future = my_model.make_future_dataframe(periods=31, freq="D")

**The program takes too much time on this line of code:**

> forecast = my_model.predict(df_future_final)

I've implemented Fourier regressors to model the weekends and removed outliers, not sure if that might be a problem in terms of optimization, but I don't think so.
Btw, the data is weekly periodic, should I put weekly_seasonility = True?

**Comment by ispmarin** [comment]
How much is "too much time to run"?

**Comment by ZED711** [comment]
I let it for hours and it didn't run

**Comment by ispmarin** [comment]
Can you provide a data sample and the code?

**Comment by ZED711** [comment]
Nevermind, I have solved the problem.

**Comment by markrazmandi** [comment]
What was your issue? I have experienced the same with specific parameter combinations.
