### ISSUE TITLE
Loaded pickle model cannot properly predict new 'future' dataframe

### ISSUE THREAD

**Issue by tianchuliang** [facebook/prophet#643]
I fitted a prophet model (with additional regressors), pickled it, and re-loaded it to predict a future dataframe. However, I am seeing this error: 
A bug occurred in constructing regressors

As I traced the function calls (self.predict -> self.predict_seasonalities -> .. -> self.regressor_column_matrix), the problem is rooted at the final few lines in the "self. regressor_column_matrix" function: 
if self.train_component_cols is not None:
    component_cols = component_cols[self.train_component_cols.columns]
    if not component_cols.equals(self.train_component_cols):
        raise Exception('A bug occurred in constructing regressors.')

I discovered that only a few additional reggressor columns are not equal. Could these additional reggressors cause the problem? 

Thanks,

**Comment by ispmarin** [comment]
I haven't seem any problems on pickling and unpickling using sklearn joblib. Does this only happens with additional regressors?

**Comment by tianchuliang** [comment]
hi @ispmarin , as far as I can tell, it ONLY happens with additional regressors. If I do a simple fbprophet model, no extra aggressors, the pickling wouldn't be a problem.

**Comment by ispmarin** [comment]
Got it. May you try to use joblib and see if the same problem happens? http://scikit-learn.org/stable/modules/model_persistence.html

**Comment by Gedevan-Aleksizde** [comment]
I found similar problem. I didn't encounter this error when I ran the above @bletham 's code. But when I ran the following code, the error was raised (I tried it with Python 3.5). I need to change the regressor names.

```
from fbprophet import Prophet  # 0.3
import pandas as pd  # 0.23.4
from sklearn.externals import joblib  # 0.11
import numpy as np  # 1.15.1

df = pd.DataFrame({
    'ds': pd.date_range('2010-01-01', '2011-01-01'),
    'y': range(366)
})
np.random.seed(42)
extra_variables = [
        'lag_y', 'reg_1', 'reg_2',
        'dummy_00', 'dummy_01', 'dummy_02', 'dummy_03', 'dummy_04',
        'dummy_05', 'dummy_06', 'dummy_07', 'dummy_08', 'dummy_09',
        'dummy_10', 'dummy_11', 'dummy_12', 'dummy_13', 'dummy_14',
        'dummy_15', 'dummy_16', 'dummy_17', 'dummy_18', 'dummy_19',
        'dummy_20', 'dummy_21'
        ]
for v in extra_variables:
    df[v] = np.random.uniform(size=df.shape[0])

# create model
m = Prophet(weekly_seasonality=False)
for v in extra_variables:
    m.add_regressor(v)

m.fit(df)

future = m.make_future_dataframe(10, include_history=False)
for v in extra_variables:
    future[v] = np.random.uniform(size=future.shape[0])
fcst = m.predict(future)

joblib.dump(m, 'test.pkl')
m2 = joblib.load('test.pkl')

fcst2 = m2.predict(future)  # failed
```
Also I tried to use `pickle` instead of `joblib`, I encountered the same error.

In this case, the order of the keys of `extra_regressors` changed by pickle-unpickling process.

```
order1 = [k for k in m.extra_regressors.keys()]
order2 = [k for k in m2.extra_regressors.keys()]
print(order1 == order2)  # False
```
Although I don't know the implementation of Python dictionary in detail, `Prophet.regressor_column_matrix()` seems to depends on the order of `extra_regressors.items()`. Maybe this is the cause of the error.

So, I think out some of the simplest way to fix:
1. use `OrderedDict` insteadly (like this: https://github.com/Gedevan-Aleksizde/prophet/commit/adedafe259326611317c6f4c5f23d24956f3a39f), or simply overwrite `extra_regressors`  with `OrderedDict` object before pickling
2. use Python > 3.7

**Comment by bletham** [comment]
@Gedevan-Aleksizde thanks for the great repro. What an interesting behavior - pickle/unpickle changes the iteration order of the dictionary, but also in a non-deterministic way. This is a really simple example, if you run it then every now and then every now and then they will actually equal!
```
import pickle

a1 = {'a_{}'.format(i): i for i in range(5)}
order1 = [n for n in a1]

with open('a.pckl', 'wb') as fout:
    pickle.dump(a1, fout)

with open('a.pckl', 'rb') as fin:
    a2 = pickle.load(fin)

order2 = [n for n in a2]

print(order1)
print(order2)
print(order1 == order2)
```

Anyway, I agree with you that the solution is to use OrderedDict. Do you want to make a PR with your commit?

**Comment by bletham** [comment]
Fix in the new version pushed to PyPI.

**Comment by chomchomtron** [comment]
Hello,

I found a similar bug while using version 0.4, but this time due to `self.seasonalities` not being ordered. My guess is everyone is already using Python3.6+ so it went unnoticed, but I wonder if it's worth turning `self.seasonalities` into an OrderedDict for the occasional Python3.5 users.

**Comment by winnie333** [comment]
hi, @bletham :  
   I also encountered the same problem as chomchomtron, this bug will still appear on fbprophet 0.4 post2, python 3.5.0，As chomchomtron said, I hope to change self.seasonalities to OrderedDict.
thanks！

**Comment by chomchomtron** [comment]
@bletham Thanks for the reply and sorry I haven't been able to produce a test case. If no one has done it by end of this week, I'll try and do it.

**Comment by bletham** [comment]
Pushed to PyPI
