### ISSUE TITLE
Massive MAPE/fit variation if training window shifts by just one week

### ISSUE THREAD

**Issue by raginikr** [facebook/prophet#648]
Hi,

I am trying to forecast sales at weekly level (week ending on Sat). I am currently considering only 2 years worth data. Passing holiday values to capture spikes for Easter and Xmas and using default model values. I noticed that overall fit changes dramatically when the training period window is shifted even by one week. For e.g.

Training period: 2015-12-26 to 2017-12-30 (both inclusive)
Training MAPE: 7.4%
![image](https://user-images.githubusercontent.com/7434310/44177115-53beeb80-a0a1-11e8-9151-a88cc2a508bb.png)
  
Now, if I shift starting date of training period by just one week: 
Training period: 1/2/2016 – 12/30/2017 (both inclusive)
Training MAPE: 23.2%

![image](https://user-images.githubusercontent.com/7434310/44177247-e65f8a80-a0a1-11e8-92e7-d9149be79c81.png)

Can anyone please help me understand why this is happening?

**Comment by vhpietil** [comment]
In second case you have less than two years of data and yearly seasonality is turned off by default

**Comment by raginikr** [comment]
Oh- I didn't even realise that! I have now kept the yearly seasonality flag on and it did help. Thanks much!
