### ISSUE TITLE
Parallelization of list with dataframes

### ISSUE THREAD

**Issue by beloteloff** [facebook/prophet#656]
Hi,
Does anybody used Pool.map from multiprocessing library on list of pandas dataframes?
For example, I have the same data (listok object):

```
[ ds   Id   y
2017-05-31 18:00:00   Big Boss   122
2017-05-31 18:00:00   Big Boss  123
...
...

 [9407 rows x 3 columns],
ds   Id   y
2017-05-31 18:00:00   Mini Pig    432
2018-05-31 18:00:00   Mini Pig   322
...
...
 [23278 rows x 3 columns]]
```

This is a list type of object, which includes a lot of pandas dataframes.

I have a function,where initial data is processed and Prophet is used.
After that I use a simple solution:

```
from multiprocessing import Pool
pool = Pool(5)
df = pd.concat(pool.map(calculation, listok))
pool.close()
pool.join()
```
What do you think about this method to speed-up of calculation?

**Comment by ispmarin** [comment]
Are all dataframes on the list the same dataframe split up or there are different dataframes?

**Comment by beloteloff** [comment]
@ispmarin  Each dataframe from list have a standart format for input to fbprophet: ds column and y column. And it works for me on Unix and windows

**Comment by bletham** [comment]
Related to #625 and #581
