### ISSUE TITLE
Cross-Validation with Monthly data

### ISSUE THREAD

**Issue by joaocunha1991** [facebook/prophet#658]
When I run cross_validation with 'months' as units it gives the error:

Error in as.difftime(horizon, units = units) : invalid units specified

The documentation of as.difftime doesn't seem to refer to units = 'months' as an option. 
Is there a way of using prophet::cross_validation() function with monthly data?

Many thanks, 
Joao

**Comment by bletham** [comment]
There's some more discussion of this in #650. The short answer is no, we use R's `as.difftime` and it does not support month because it isn't a precise unit of time (https://stat.ethz.ch/R-manual/R-devel/library/base/html/difftime.html).

**Comment by bletham** [comment]
I'm going to close this and leave #586 as the open issue for monthly cross-validation.
