### ISSUE TITLE
Daily forecast of model trained with hourly data

### ISSUE THREAD

**Issue by ispmarin** [facebook/prophet#659]
I'm trying to understand if it would be possible to generate a forecast with daily frequency from a model trained with hourly data. For example, a synthetic sine signal with daily oscillation:

```
import pandas
idx = pd.date_range('2016-01-01','2016-02-04', freq='H')
len_idx = len(idx)
points = np.arange(0, len_idx)
df_day = pd.DataFrame({'y':np.sin(points*2*np.pi/24)}, index=idx)
df_day['ds'] = df_day.index

mdl_day = Prophet()
mdl_day.fit(df_day)

future = mdl_day.make_future_dataframe(periods=300, freq='H')
forecast_day = mdl_day.predict(future)
forecast_day.index = pd.to_datetime(forecast_day.ds)
df_day.y.plot_components(forecast_date)
```
![image](https://user-images.githubusercontent.com/12247/44586533-5f3ba200-a786-11e8-9463-eda502641608.png)

as expected. So now I try to generate a forecast with daily freq:

```
future_week = mdl_day.make_future_dataframe(periods=10, freq='D')
forecast_week = mdl_day.predict(future_week)
forecast_week.index = pd.to_datetime(forecast_week.ds)
forecast_week.yhat.plot()
```
![image](https://user-images.githubusercontent.com/12247/44586555-77132600-a786-11e8-857c-0ad8f4d45ea5.png)

So the forecast is the value of the hourly freq forecast at midnight.

![image](https://user-images.githubusercontent.com/12247/44586565-85f9d880-a786-11e8-9b37-70a2cde31946.png)

Now, if I shift the phase of the sine by pi/2, the forecast that I get is the max value, the value of the forecast at midnight:

![image](https://user-images.githubusercontent.com/12247/44586892-9b233700-a787-11e8-858c-1b218dcf1c43.png)

So the function make_future_dataframe generates the time stamps for days only, with midnight as the time, and the model will output the prediction value for that specific time. The same thing happens if I add a constant trend:

![image](https://user-images.githubusercontent.com/12247/44586980-ed645800-a787-11e8-997b-24f5498f0712.png)

With that understanding, is there an approach where it would be reasonable to generate a daily freq forecast with a model trained with hourly freq data? So far, it seems that it would be more sensible to first resample the data to the new frequency (hour -> day) and then generate a forecast.

**Comment by bletham** [comment]
Thanks for the clear example!

`make_future_dataframe` uses `pd.date_range` to generate the sequence of timestamps. If you look at 
```
>>> future.tail()
                      ds
1112 2016-02-16 08:00:00
1113 2016-02-16 09:00:00
1114 2016-02-16 10:00:00
1115 2016-02-16 11:00:00
1116 2016-02-16 12:00:00
```
you see that it is giving points separated by 1 hour, as requested. If you do
```
>>> future_week.tail()
            ds
822 2016-02-10
823 2016-02-11
824 2016-02-12
825 2016-02-13
826 2016-02-14
```
they are separated by 1 day. Note that pd.date_range with 1-day frequency returns just a date with no time component, but the time component is implicitly set to 00:00:00; hence you see that you get predictions for whatever the time was at midnight.

The main thing to understand here is that the Prophet model is continuous time, so when you ask for a prediction you do have to also tell it the time that you want the prediction for. So, the right thing to do here depends on what you mean by a daily frequency forecast - do you want a forecast for each day at midnight? (what was done). Noon? (use something like `future = pd.DataFrame({'ds': pd.date_range(start='2016-01-01 12:00:00', periods=10, freq='d')})`). Or maybe a daily total? (Make an hourly forecast and then sum by day).

Does that make sense?

**Comment by ispmarin** [comment]
Hi @bletham, thank you for your answer. It makes total sense, and matches on what I was thinking. My next question would be: is it better to first aggregate the data into daily frequency and then generating a model, or generate a forecast with hourly frequency and aggregate the prediction by day?

**Comment by bletham** [comment]
If ultimately the task is to forecast the aggregate, I don't think there would be any benefit to fitting hourly data and then aggregating the predictions; it should be just as good to fit the aggregates, and quite a bit faster too.

That said, if you have a chance to try both I'd love to hear how they compare.

**Comment by eromoe** [comment]
@bletham 

The smallest level in Prophet seems to be day as I saw below code 
```
    @staticmethod
    def fourier_series(dates, period, series_order):
        """Provides Fourier series components with the specified frequency
        and order.

        Parameters
        ----------
        dates: pd.Series containing timestamps.
        period: Number of days of the period.
        series_order: Number of components.

        Returns
        -------
        Matrix with seasonality features.
        """
        # convert to days since epoch
        t = np.array(
            (dates - pd.datetime(1970, 1, 1))
                .dt.total_seconds()
                .astype(np.float)
        ) / (3600 * 24.)
        return np.column_stack([
            fun((2.0 * (i + 1) * np.pi * t / period))
            for i in range(series_order)
            for fun in (np.sin, np.cos)
        ])

    @classmethod
    def make_seasonality_features(cls, dates, period, series_order, prefix):
        """Data frame with seasonality features.

        Parameters
        ----------
        cls: Prophet class.
        dates: pd.Series containing timestamps.
        period: Number of days of the period.
        series_order: Number of components.
        prefix: Column name prefix.

        Returns
        -------
        pd.DataFrame with seasonality features.
        """
        features = cls.fourier_series(dates, period, series_order)
        columns = [
            '{}_delim_{}'.format(prefix, i + 1)
            for i in range(features.shape[1])
        ]
        return pd.DataFrame(features, columns=columns)
```

But it is confusing that `plot_component` has a plot in day. 

Would you mind to explain this ?

**Comment by bletham** [comment]
@eromoe yes, there is no problem with using hourly data. There is an example in the documentation here that uses data with 5-minute frequency:
https://facebook.github.io/prophet/docs/non-daily_data.html#sub-daily-data

The seasonality period is the length of the seasonal cycle. For instance a seasonality period of 1 day means a pattern that repeats itself every day, which is what the 'daily' seasonality in the plot is. The seasonal pattern itself is a continuous function, with a period of 1 day.

It may be worth noting also that while the seasonality period is specified in days, it does not need to be an integer. The fastest default seasonality is a period of 1-day, since that is the shortest seasonality seen in typical business time series. But if you had a time series with seasonal patterns that repeated every hour, you could put the seasonality period to 1/24.

**Comment by eromoe** [comment]
Thank you for clarification
