### ISSUE TITLE
Document reasonable ranges for prior scales

### ISSUE THREAD

**Issue by ruksarsultana** [facebook/prophet#660]

**Comment by bletham** [comment]
It would really depend on the data, but I generally think about it as spanning a few orders of magnitude. My rule of thumb for a starting range for a search would probably be [0.001, 1]. Depending on how many changepoints were specified, 1 would likely be effectively unregularized.

**Comment by zzlotoff** [comment]
@bletham - I'm not sure if you're the documenation expert on the website (I've seen you a lot around the tickets), but I have this type of question for each of the different parameters. It's confusing, for example, on https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html where, when walking through prior scale, it says that the default is 10, but you can decrease it a little bit - but then the example decreases it to 0.05, which seems very drastic. So I've taken a lot of time to play around with different parameter values, but it's probably not the best use of time when I'm sure experts such as yourself could better guide users.

Anyway, maybe it's off-topic or not a great suggestion. But I do think the rest of the documentation is very well done!

**Comment by bletham** [comment]
This is a good point, it isn't really stated anywhere what the reasonable range to look over is. I'll make sure that gets into the documentation somewhere before the next release.

**Comment by kenny1901** [comment]
Hi @bletham one of the challenges i am having with the fb prophet is how to choose the right Fourier order for the different seasonalities, currently I am iteratively choosing the Fourier orders and choosing the one with the lowest mape, I fear that i may be over fitting, is this possible in my method.
