### ISSUE TITLE
Difference in forecast values on R and Python

### ISSUE THREAD

**Issue by kumarvrsec** [facebook/prophet#668]
There is difference in forecast values on R and Python, when tried using Prophet for different data sets.
Can anyone help in clarifying this difference?

**Comment by vhpietil** [comment]
Is the difference significant? There might be a difference because of different seeds for some random numbers

**Comment by kumarvrsec** [comment]
It differs by 1 to 2.Can you explain at what case,random numbers are used

**Comment by bletham** [comment]
See also #600 and #316 for sources of stochasticity and discussion of differences between R and Python.
