### ISSUE TITLE
Editing the uncertainty of the plot of the forecast

### ISSUE THREAD

**Issue by ZED711** [facebook/prophet#672]
Hello everyone. 
I'd like to edit the uncertainty of the plot of the forecast. In other words, I'd like to edit the color of the uncertainty to red (light red if possible). 
![dd](https://user-images.githubusercontent.com/41108785/44855121-476e8d00-ac62-11e8-9dc0-590225c3b899.jpg)
**The code of the plot attribute is written here:** 
![1](https://user-images.githubusercontent.com/41108785/44854908-bd262900-ac61-11e8-8b96-ec730c9ffccd.PNG)
![2](https://user-images.githubusercontent.com/41108785/44854914-bf888300-ac61-11e8-9ee5-fc9f28b91847.PNG)

I'm having some difficulties since the plot is done like this by default. Can anyone help?

**Comment by IronistM** [comment]
What you need to edit is in `fill_between` section :

```python
if uncertainty:
   ax.fill_between(..., color = '#0072b2')
```

**Comment by ZED711** [comment]
How can I edit it? I only call for the attribute .plot.

**Comment by IronistM** [comment]
You can create a new function , eg `my_plot()` and pass to it the prophet model and forecast

```python
def my_plot(
    m, fcst, ax=None, uncertainty=True, plot_cap=True, xlabel='ds', ylabel='y',
):
    """Plot the Prophet forecast.
    Parameters
    ----------
    m: Prophet model.
    fcst: pd.DataFrame output of m.predict.
    ax: Optional matplotlib axes on which to plot.
    uncertainty: Optional boolean to plot uncertainty intervals.
    plot_cap: Optional boolean indicating if the capacity should be shown
        in the figure, if available.
    xlabel: Optional label name on X-axis
    ylabel: Optional label name on Y-axis
    Returns
    -------
    A matplotlib figure.
    """
    if ax is None:
        fig = plt.figure(facecolor='w', figsize=(10, 6))
        ax = fig.add_subplot(111)
    else:
        fig = ax.get_figure()
    fcst_t = fcst['ds'].dt.to_pydatetime()
    ax.plot(m.history['ds'].dt.to_pydatetime(), m.history['y'], 'k.')
    ax.plot(fcst_t, fcst['yhat'], ls='-', c='#0072B2')
    if 'cap' in fcst and plot_cap:
        ax.plot(fcst_t, fcst['cap'], ls='--', c='k')
    if m.logistic_floor and 'floor' in fcst and plot_cap:
        ax.plot(fcst_t, fcst['floor'], ls='--', c='k')
    if uncertainty:
        ax.fill_between(fcst_t, fcst['yhat_lower'], fcst['yhat_upper'],
                        color='#FCB44C', alpha=0.2)
    ax.grid(True, which='major', c='gray', ls='-', lw=1, alpha=0.2)
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    fig.tight_layout()
    return fig
```

An example run
```python
m = Prophet()
m.fit(df)
future = m.make_future_dataframe(periods=365)
forecast = m.predict(future)
fig = my_plot(m = m, fcst = forecast, ax=None, uncertainty=True)
```

**Comment by ZED711** [comment]
Well this works. However the code has rights reserved in copyright so I don't if I can copy it to a new function...

**Comment by IronistM** [comment]
Well don't get me into legal stuff.... 🎣

**Comment by bletham** [comment]
You can copy and modify code with the conditions in the license: https://github.com/facebook/prophet/blob/master/LICENSE

Just making a new plot function like that one above with the color you want is probably what I'd recommend. You could also use matplotlib functions to edit the figure created with the builtin plot, you just have to find the right artist element from `ax.get_children()` to modify. This code does what you want:

```
fig = m.plot(fcst)
ax = fig.gca()
ax.get_children()[0].set_color('r')
```
