### ISSUE TITLE
Weird samples appearing in the plot 

### ISSUE THREAD

**Issue by ZED711** [facebook/prophet#676]
Hello everyone.
I have some weird points in my prophet plot, but don't know where are they coming from, since the 'y' column of the data frame which has the input values doesn't have any sample with a value near zero. 
![wcs](https://user-images.githubusercontent.com/41108785/44993077-2c1cbe00-af91-11e8-99d2-21e4836d9fc5.PNG)
![plottt](https://user-images.githubusercontent.com/41108785/44993153-7736d100-af91-11e8-9606-377f89ac6ef1.PNG)
Ideas ???

**Comment by pankaj-kvhld** [comment]
Were these values missing in y and get imputed as 0? Just a wild guess

**Comment by bletham** [comment]
This is a bit strange, can you check `min(m.history['y'])` and `min(pd.to_numeric(df_forecast['y']))`?

missing values (NA) are filtered and so shouldn't show up at all here.

**Comment by bletham** [comment]
I'm hoping this was resolved but if not please re-open and we can figure out what happening here. (Presumably something in how the dataframe is being handled.)
