### ISSUE TITLE
Import error : cannot import name 'performance_metrics' from fbprophet.diagnostics

### ISSUE THREAD

**Issue by sriramkraju** [facebook/prophet#684]
https://facebook.github.io/prophet/docs/diagnostics.html
### Getting an error: ImportError: cannot import name 'performance_metrics'
```
# Python
from fbprophet.diagnostics import performance_metrics
df_p = performance_metrics(df_cv)
df_p.head()
ImportError Traceback (most recent call last)
```
in ()
----> 1 from fbprophet.diagnostics import performance_metrics
2 df_p = diagnostics.performance_metrics(df_cv)
3 df_p.head()

> ImportError: cannot import name 'performance_metrics'

**Comment by bletham** [comment]
Resolved in #194.

**Comment by ivonnics** [comment]
Hi!
I just installed Prophet, however, when I type:
`import fbprophet`
I get this error:
`ImportError: cannot import name 'MONDAY'`
I ran: `pip install fbprophet --upgrade` before asking the question, and even with that I got the same error.
Any suggestion on how to overcome this error, would be extremelly welcome...

**Comment by savagedata** [comment]
It seems like a new release of holidays (0.9.9) earlier today is causing errors with Prophet.

`>>> from fbprophet import Prophet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/fbprophet/__init__.py", line 8, in <module>
    from fbprophet.forecaster import Prophet
  File "/usr/local/lib/python3.6/site-packages/fbprophet/forecaster.py", line 23, in <module>
    from fbprophet.make_holidays import get_holiday_names, make_holidays_df
  File "/usr/local/lib/python3.6/site-packages/fbprophet/make_holidays.py", line 17, in <module>
    import fbprophet.hdays as hdays_part2
  File "/usr/local/lib/python3.6/site-packages/fbprophet/hdays.py", line 13, in <module>
    from holidays import HolidayBase, MONDAY, WEEKEND, rd, easter
ImportError: cannot import name 'MONDAY'
`

I rolled back to holidays 0.9.8 and am now able to import Prophet. 
`pip uninstall holidays
pip install holidays==0.9.8`
