### ISSUE TITLE
Submit example of implementation as a web service

### ISSUE THREAD

**Issue by Draichi** [facebook/prophet#686]
Hello, fist of all, Prophet is really nice, thank you very much.

I made a implementation using cryptocurrency data, maybe would be useful as a example for people who want to get started, see here: https://github.com/Bud-Fox/API and here: https://bud-fox.github.io/live/

If you guys want me to give the credits in a specific way i can update the readme, or linik the project, or i can issue a PR with the example code, idk, i want to people see how useful Prophet can be

Thanks guys :heart:

**Comment by bletham** [comment]
This is really neat. We've seen a few pretty cool applications recently and are thinking about having a section in the documentation that could link to them, as a way of diving deeper after reading the documentation. This is a good example of Prohet-as-a-service. I'll leave this issue open and with the next version we'll figure out what we want to do for external examples.
