### ISSUE TITLE
Prophet hangs on our data

### ISSUE THREAD

**Issue by kdubovikov** [facebook/prophet#692]
Hi. We've noticed a strange bug when prophet optimisation algorithm hangs on our data when using holidays. I've attached a fully reproducible example to the issue.

[prophet_problems.zip](https://github.com/facebook/prophet/files/2441583/prophet_problems.zip)

**Comment by bletham** [comment]
I'm actually not able to replicate the issue (it successfully fits for me both times). What version of fbprophet do you have installed? There was an issue in an older version where very small datasets would sometimes cause the optimizer to hang.
```
import fbprophet
fbprophet.__version__
```

**Comment by JohnnyChingas** [comment]
I'm seeing a similar issue.  I'm running fbprophet version 0.3.  Is there a different version I can use?

**Comment by bletham** [comment]
That is the latest, could you post the data so I can try and investigate? It is hanging during fitting I assume?

**Comment by JohnnyChingas** [comment]
I found this:

https://github.com/facebook/prophet/issues/402

It's no longer hanging.  Thanks!
