### ISSUE TITLE
BNN package install

### ISSUE THREAD

**Issue by Urjitmodhia** [facebook/prophet#694]
hiiiii
i am trying to install BNN package in my PYNQ board but getting this eroor from so long the error is:-

command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-4u3yynr8/

pleeeeeeeeeeeeeeseeeeeee help me if someone have the solution

**Comment by bletham** [comment]
This issue tracker is for a different project, I'd recommend asking at https://github.com/Xilinx/BNN-PYNQ
