### ISSUE TITLE
error term not implemented in program now?

### ISSUE THREAD

**Issue by sparo-jack** [facebook/prophet#696]
The description "The error term εt represents any idiosyncratic changes which are not
accommodated by the model; later we will make the parametric assumption that εt is
normally distributed" in paper [Forecasting at scale. https://peerj.com/preprints/3190.pdf], "later" denote error term not implemented in program now?

**Comment by bletham** [comment]
"later" there meant later in the paper. At that point in the paper, we just assume there is an error term, we have not yet made any assumptions about it. Later in the paper (in Listing 1) we explicitly model the errors as being i.i.d. normal. This assumption shows up in the code here:

https://github.com/facebook/prophet/blob/master/R/inst/stan/prophet.stan#L112

**Comment by sparo-jack** [comment]
thanks
