### ISSUE TITLE
The predict line is so much different in 2 days

### ISSUE THREAD

**Issue by TaurusYin** [facebook/prophet#701]
Dear developers,

I find a weird result produced by prophet.

the data is 8 day ago till now or more than 8 days ago:

![image](https://user-images.githubusercontent.com/5126301/46721772-6e2ed300-cca6-11e8-8348-3aaea8136d87.png)

The data is 7 day ago till now.
![image](https://user-images.githubusercontent.com/5126301/46721819-9585a000-cca6-11e8-9315-4abe9394c2b2.png)

If I use sarimax, the result looks like more reasonable.
![image](https://user-images.githubusercontent.com/5126301/46722072-36745b00-cca7-11e8-9f16-31ad6b88d7c6.png)

Here you can find the result is much different if I get one week data. I tried to change the changepoint and prior_scale parameter, but it failed.
Anything further can be done in terms of this case?

**Comment by bletham** [comment]
The Prophet forecasts can be sensitive to trend changes at the very end of the forecast. For this reason, by default Prophet does not place changepoints in the last 20% of the time series (e.g., the figure in https://facebook.github.io/prophet/docs/trend_changepoints.html) . In this case where it is being allowed to change at the end of the time series, the little bit of extra data makes the model more confident that the trend will continue to stay flat, and so it is adjusted.

In this case, the model uncertainty actually is quite high even in the first case, and the 2nd trend seems to be consistent with the uncertainty interval in the first forecast. So I don't think I can fault the model too badly in this case. One thing that might be helpful when you have a relatively small amount of data and want to fully understand the model sensitivity is to do MCMC. Try setting `mcmc_samples=500` when you instantiate the model and then look at the trend uncertainty in the components plot. MCMC will be able to estimate the uncertainty in that final trend value and should make it more clear in the first forecast that staying flat is a possibility.

**Comment by ensalty** [comment]
> The Prophet forecasts can be sensitive to trend changes at the very end of the forecast. For this reason, by default Prophet does not place changepoints in the last 20% of the time series (e.g., the figure in https://facebook.github.io/prophet/docs/trend_changepoints.html) . In this case where it is being allowed to change at the end of the time series, the little bit of extra data makes the model more confident that the trend will continue to stay flat, and so it is adjusted.
> 
> In this case, the model uncertainty actually is quite high even in the first case, and the 2nd trend seems to be consistent with the uncertainty interval in the first forecast. So I don't think I can fault the model too badly in this case. One thing that might be helpful when you have a relatively small amount of data and want to fully understand the model sensitivity is to do MCMC. Try setting `mcmc_samples=500` when you instantiate the model and then look at the trend uncertainty in the components plot. MCMC will be able to estimate the uncertainty in that final trend value and should make it more clear in the first forecast that staying flat is a possibility.

Thanks, I tried to use MCMC but it exited without send any error when it run this mdl.fit(dataframe)
Could you please provide more documents in terms of MCMC and I would like to investigate further in terms of this. It looks like it use another set of algorithm to run it which takes a little longer time to sample the data

BTW, I just crack it by enhance the n_changepoints to assgin 50 to it. 
![image](https://user-images.githubusercontent.com/5126301/47074246-98473e80-d22c-11e8-8a65-81ed2fd8bdb9.png)

**Comment by bletham** [comment]
The MCMC is described here: https://facebook.github.io/prophet/docs/uncertainty_intervals.html 
Indeed it does take much longer than the default fitting.

**Comment by ensalty** [comment]
Thanks for the information, I tried to run by mcmc sampling with multiple processes, it looks like always exit without any error message. When I tried to run it by single process, it work fine. 
![image](https://user-images.githubusercontent.com/5126301/47279641-03b25700-d605-11e8-8892-6f9c0e9314a0.png)

`mdl = Prophet(seasonality_mode='multiplicative',mcmc_samples=50, changepoint_prior_scale=0.01,changepoint_range=1.0)
            mdl.fit(dataframe)`

I just use multiprocessing package to run the forecast jobs in paralleled jobs. It looks like all the jobs exited
Is there any multiple process sample for mcmc sample?

![image](https://user-images.githubusercontent.com/5126301/47279628-f006f080-d604-11e8-895f-c6e4e4c647c7.png)

**Comment by bletham** [comment]
MCMC will definitely take a lot longer. I'm not sure there are any simple steps that will significantly increase the speed. Reducing the number of potential changepoints would likely help (for instance, by looking at you data and determining where likely changepoints are and using only those). Reducing the size of the history would also speed things up. But both of these also potentially impact forecast quality so you'd have to see what works for you.
