### ISSUE TITLE
ValueError: Expected column 'floor'. fbprophet 0.3.post2

### ISSUE THREAD

**Issue by macher07** [facebook/prophet#702]
Dear developers,
I have a problem with Saturating Forecasts. ValueError: Expected column 'floor'.
Latest version prophet installed. I do not know why. Сode in image

Sorry for my English)
Thanks.

![1](https://user-images.githubusercontent.com/44036088/46757158-042c2300-ccd2-11e8-99e0-9b6d2867037c.JPG)

**Comment by bletham** [comment]
I think the problem here is that you are adding the floor to `future`, but then are aftewards re-creating `future`, with `future = m.make_fjuture_dataframe(periods=11,freq='M')`. Make sure you add floor to `future` after that. Does that do it?
