### ISSUE TITLE
Posterior predictions diverge from predict() when including a regressor variable

### ISSUE THREAD

**Issue by nickpetri** [facebook/prophet#704]
I am using Prophet in R, and I'm having trouble producing monthly confidence intervals using the `predictive_samples` method. Specifically, the mean yhat produced by the predictive samples is way off the yhat generated by `predict()`, and empirically, it seems the latter is better calibrated. 

This issue only seems to come up when a regressor is included in the model. Here is illustrative code:

```
require(prophet)
require(plotly)
require(data.table)

# use data set of Larry Bird wikipedia searches
# http://tools.wmflabs.org/pageviews/?project=en.wikipedia.org&platform=all-access&agent=user&range=all-time&pages=Larry_Bird#
df <- data.table(read.csv('~/downloads/bird.csv'))

# spoof a regressor, make sure it is important
df[, important_variable := runif(.N, 0, 1000)]
df[, new_y := Larry.Bird + runif(.N) * important_variable]

# format columns for prophet
setnames(df, c('Date', 'new_y'), c('ds', 'y'))
df[, cap := 20000]
df[, floor := 0]

# function to graphically compare yhat generated by predict() vs. mean of posterior samples
compare_yhat <- function(model, prediction) {

  future_yhat_sample <- predictive_samples(model, prediction) # matrix of 1k predictions for each date in "prediction" dt
  prediction_dates <- as.Date(prediction$ds)
  
  yhat_dt <- data.table(future_yhat_sample$yhat)
  yhat_dt[, date := prediction_dates] # add dates
  # melt into long format
  melted_samples <- melt(yhat_dt, id.vars = 'date')
  setnames(melted_samples, 'variable', 'sample')
  
  intervals <- melted_samples[, j = list(
    mean_yhat = mean(value)
    , yhat_50 = quantile(value, probs = 0.5)
    , yhat_5 = quantile(value, probs = 0.05)
    , yhat_95 = quantile(value, probs = 0.95)
    , pct_negative = sum(ifelse(value < 0, 1, 0))
    ), by = date
    ]
  
  daily_yhat <- prediction[, j = list(date = as.Date(ds), yhat)]
  comparison <- merge(x = intervals, y = daily_yhat, by = 'date')
  
  message('sum of yhat:')
  message(sum(comparison$yhat))
  message('sum of mean of yhat samples:')
  message(sum(comparison$mean_yhat))
  
  plot_ly(data = comparison) %>%
    add_trace(name = 'yhat', x = ~date, y = ~yhat, mode = 'lines') %>%
    add_trace(x = ~date, name = 'mean_yhat', y = ~mean_yhat, mode = 'lines')
}

# compare yhat in predictive_samples vs. predict()
prediction_date <- as.Date('2017-01-01')
m <- prophet(seasonality.mode = 'multiplicative', interval.width = 0.90, changepoint.prior.scale = 0.05, growth = 'logistic') %>%
  # bias appears when this regressor is un-commented:
  #add_regressor('important_variable', mode='additive') %>%  
  fit.prophet(df[prediction_date > ds,])
future <- df[ds >= prediction_date,]
future_prediction <- data.table(predict(m, future))
compare_yhat(m, future_prediction)

```

when fitting the model, `yhat` is roughly the same in `predict()` and `predictive_samples` when the regressor is commented out, but diverge by ~10% when it is included. in fact, `predict()`'s yhat is outside the 95% confidence interval of the posterior samples.

i have experimented with different combinations of prophet features (logistic growth, different seasonalities, etc.) and i'm fairly certain the regressor is the problem. i would love to include regressors, but until i can make sense of the confidence intervals i don't think i can.

any ideas? do the posterior samples not include the regressor variable?

**Comment by bletham** [comment]
Thanks for raising this issue and for the really clean repro. It took me a while to figure out what was going on here but I was finally able to get to the bottom of it!

The issue here is that the posterior samples are being drawn with
```
future_yhat_sample <- predictive_samples(model, prediction)
```
Note that here `prediction` is the forecast dataframe returned by `predict(m, future)`. The correct input to `predictive_samples` would be the future dataframe, like
```
future_yhat_sample <- predictive_samples(model, future)
```
If you make that substitution (like this) then you will see that there is no discrepancy:
```
compare3 <- function(model, prediction, future) {
  future_yhat_sample <- predictive_samples(model, future) # matrix of 1k predictions for each date in "prediction" dt
  prediction_dates <- as.Date(prediction$ds)
  
  yhat_dt <- data.table(future_yhat_sample$yhat)
  yhat_dt[, date := prediction_dates] # add dates
  # melt into long format
  melted_samples <- melt(yhat_dt, id.vars = 'date')
  setnames(melted_samples, 'variable', 'sample')
  
  intervals <- melted_samples[, j = list(
    mean_yhat = mean(value)
    , yhat_50 = quantile(value, probs = 0.5)
    , yhat_5 = quantile(value, probs = 0.05)
    , yhat_95 = quantile(value, probs = 0.95)
    , pct_negative = sum(ifelse(value < 0, 1, 0))
    ), by = date
    ]
  
  daily_yhat <- prediction[, j = list(date = as.Date(ds), yhat)]
  comparison <- merge(x = intervals, y = daily_yhat, by = 'date')
  
  message('sum of yhat:')
  message(sum(comparison$yhat))
  message('sum of mean of yhat samples:')
  message(sum(comparison$mean_yhat))


  gg <- ggplot(comparison, aes(date)) + 
    geom_line(aes(y = yhat, colour = "yhat")) + 
    geom_line(aes(y = mean_yhat, colour = "mean_yhat"))
  print(gg)
}
```

The source of the issue is that both the future dates dataframe (`future`) and the forecast dataframe (`prediction`) have a column named `important_variable`. In `future`, this column is the value of `important_variable` at that date. In `prediction`, the column is the amount of `yhat` explained with `important_variable` (in particular, it is `beta * important_variable` with the fitted coefficient beta). When we pass `prediction` into `predictive_samples` instead of `future`, then it's using the wrong values for `important_variable` hence the discrepancy.

I'm not sure if there is a reasonable way to avoid this mistake for others in the future, besides perhaps updating the docstring for `predictive_samples` to explicitly state to not do this. Note that `predict` has the same behavior.

**Comment by nickpetri** [comment]
beautiful, thanks so much for your help! 

i suppose `predict` and `predictive_samples` could issue a warning if you pass it what "looks like" the output of a prediction, but since they're just `data.frame`s there's no foolproof way to assert that.

closing the issue, thanks again for all the hard work on this
