### ISSUE TITLE
NameError: name 'logger' is not defined

### ISSUE THREAD

**Issue by SlinkoIgor** [facebook/prophet#707]
~/miniconda/lib/python3.6/site-packages/fbprophet/forecaster.py in <module>()
     21     import pystan  # noqa F401
     22 except ImportError:
---> 23     logger.exception('You cannot run fbprophet without pystan installed')
     24 
     25 from fbprophet.diagnostics import prophet_copy

NameError: name 'logger' is not defined

Solution: Move logger definition upper like this:

logging.basicConfig()
logger = logging.getLogger(__name__)
warnings.filterwarnings("default", category=DeprecationWarning)

import numpy as np
import pandas as pd
try:
    import pystan  # noqa F401
except ImportError:
    logger.exception('You cannot run fbprophet without pystan installed')

**Comment by seanjtaylor** [comment]
I'm not quite sure I understand what you've done to generate this error message.  Can you explain how to reproduce this?

**Comment by bletham** [comment]
This issue was actually recently fixed in 817f0306a45c7c5014b804877e87d32c22435f58 , so it will show up locally once we push the next version to pip.
