### ISSUE TITLE
Function add_changepoints_to_plot not found (R)

### ISSUE THREAD

**Issue by 14mprb** [facebook/prophet#710]
Hi,

I am just starting using prophet trying to produce a simple forecast. Therefore, I am following the steps given on the website (https://facebook.github.io/prophet/docs/trend_changepoints.html).

So basically, this works and generates a graph with my history and forecast:
plot(m, forecast)

But this generates an error message:
plot(m, forecast) + add_changepoints_to_plot(m)

Error message: 
Error in add_changepoints_to_plot(m): could not find function "add_changepoints_to_plot"
Traceback:

and that's it.

Do you have any idea of what is causing this?

Thank you!

**Comment by bletham** [comment]
I wonder if your version of Prophet may be old. Could you check that you have v0.3.0.1 installed with
```
packageVersion("prophet")
```

**Comment by 14mprb** [comment]
packageVersion("prophet")
[1] '0.1.1'

How do I install the most recent version? (I am using R in jupyter notebook - anaconda, switching to python is also an option)

Thank you

**Comment by bletham** [comment]
`install.packages("prophet")` should get the latest version.
