### ISSUE TITLE
Cross validation for hourly data

### ISSUE THREAD

**Issue by aradhanachaturvedi** [facebook/prophet#712]
I have a data which is recorded every 15 minutes.I have sampled it on hourly basis and built a model using Prophet.

However I want to do cross validation on hourly data.Can you suggest what parameter I can put it in for horizon ,initial and others.

I have total rows =35064 which has hourly data recorded

 	                yhat 	        yhat_lower 	yhat_upper 	 y
ds 				
2014-12-31 21:00:00 	580.991010 	201.445953 	1035.706288 	359.3775
2014-12-31 22:00:00 	526.637199 	144.599515 	971.679750 	361.3325
2014-12-31 23:00:00 	432.940257 	61.687435 	868.879605 	351.5650

**Comment by Gynii** [comment]
Hi , i have the data recorded on the same interval (15 min ) do you know if there is any possibility to make prediction on interval 15 minutes also ? 

If i make freq = min it does it for every minute like :
2018-10-21 00:01:00
2018-10-21 00:02:00
2018-10-21 00:03:00
Etc.
And i want something like 

2018-10-21 00:15:00
2018-10-21 00:30:00
2018-10-21 00:45:00

**Comment by bletham** [comment]
The horizon will really depend on what range of forecasts you would like to make. If you intend to make 1 day forecasts then a horizon of 1 day would be appropriate; if you intend to make 1 year forecasts, then it should be 1 year.

An appropriate value for the initial would be whatever you think the minimum amount of data needed to make a forecast of length `horizon` would be. E.g., if you have yearly seasonality that you think is important for your problem, then you should probably have initial be at least a year. The default is to use 3x horizon as the initial.

Finally, there is the period, which is the amount of time between each cutoff. I think this would depend on how many estimates of the error you want. It seems that you have 4 years of hourly data. If you set initial to 1 year, horizon to 1 year, and period to 1 day, then this would make a forecast for every day starting with initial and ending when horizon reaches the end of the dataset. That is, it would make a prediction for every day in the 2nd and 3rd years of the time series. This means ~730 days, so it would have to fit the model 730 times. This would take forever, and you probably don't really need that many estimates. Setting the period to 30 days would mean a forecast per month for those two years, which would be much more reasonable and still give you a large number of estimates.

Does that make sense?
