### ISSUE TITLE
Is it possible to make frequency 15 minute for Timestamp ?

### ISSUE THREAD

**Issue by Gynii** [facebook/prophet#713]
Hi Everyone ,
Is it possible to change the frequency to interval of 15 minutes ? So the date should look like this : 

2018-10-21 00:15:00
2018-10-21 00:30:00
2018-10-21 00:45:00

Thank you in advance

**Comment by ensalty** [comment]
sure, it support non-daily data forecast.

**Comment by Gynii** [comment]
Could u tell me how to do it then @ensalty ?

**Comment by Gynii** [comment]
I found the solution , it was easy . We just make freq=‚15min‘
