### ISSUE TITLE
Are there any ways to implement the incremental update for the forecasting job?

### ISSUE THREAD

**Issue by TaurusYin** [facebook/prophet#716]
Input data is so huge that it take much time to do the forecast calculation.
Is there any guides about how to merge the incremental data with the previous forecast calculation result ?
In this way, every time it can just load the new produced data and merge the data into the previous calculated data structure instead of query the full data for every forecast job.

**Comment by bletham** [comment]
This is not currently possible, there is an open issue for this in #46.

This is a little tricky to do the way that Prophet is implemented (and in particular to handle trend changepoints well), but my comment at the end of that issue gives some description of what I think could be done there.
