### ISSUE TITLE
In last line of doc , its given that '5m min resolution'  and in code freq is given as ' freq='H' '  is it right ?

### ISSUE THREAD

**Issue by multinucliated** [facebook/prophet#717]
https://facebook.github.io/prophet/docs/non-daily_data.html

Prophet can make forecasts for time series with sub-daily observations by passing in a dataframe with timestamps in the ds column. The format of the timestamps should be YYYY-MM-DD HH:MM:SS - see the example csv here. When sub-daily data are used, daily seasonality will automatically be fit. Here we fit Prophet to data with 5-minute resolution (daily temperatures at Yosemite):

`# Python
df = pd.read_csv('../examples/example_yosemite_temps.csv')
m = Prophet(changepoint_prior_scale=0.01).fit(df)
future = m.make_future_dataframe(periods=300, freq='H')
fcst = m.predict(future)
fig = m.plot(fcst)`

**Comment by Gynii** [comment]
Yes i saw this also , they did it in hourly frequency but you still can do it in interval of 5 min

**Comment by multinucliated** [comment]
Thanks @Gynii ,I solved it like this 
`    future = model.make_future_dataframe(periods=20, freq='15min')    `

for 15min interval and 20 more counts.
