### ISSUE TITLE
Is there any ways to cover the points for 1 min/15 mins level data ?

### ISSUE THREAD

**Issue by TaurusYin** [facebook/prophet#724]
I just add the seasonality with the name of hourly but no 1 min level label which can be selected.

`mdl = Prophet(seasonality_mode='multiplicative',interval_width=0.80, mcmc_samples=30,uncertainty_samples=30, changepoint_prior_scale=0.01, changepoint_range=1.0,)
            mdl.add_seasonality(
                name='hourly', period=24, fourier_order=30, prior_scale=0.1)
            mdl.fit(dataframe)`

![image](https://user-images.githubusercontent.com/5126301/47844670-eef07300-ddfd-11e8-9ea5-4e996e8ef0f5.png)

Here the upper bounds cannot cover the several much more higher points. May I know how to cover this?

The data looks like this below. It ways get 2 points much more higher at around the same time every day
![image](https://user-images.githubusercontent.com/5126301/47844963-aab1a280-ddfe-11e8-9cff-bd23a3a75c77.png)

**Comment by bletham** [comment]
I actually just commented on #714 about this, the specification of the hourly seasonality is actually specifying a period of 24 days. I'm going to close this issue since we are already discussing it on #714 and can continue there.
