### ISSUE TITLE
Implement piecewise linear functions in python prophet

### ISSUE THREAD

**Issue by AntonioBlago** [facebook/prophet#726]
Hello, i have been trying out with the basic linear function und logistic function. But i wanted to improve the model a bit by using more sophisticated models like piecewise models. I researched for documentation but there is no real documentation about it despite which variables do you put in (from r documentation: https://www.rdocumentation.org/packages/prophet/versions/0.3.0.1/topics/piecewise_linear )

Usage
piecewise_linear(t, deltas, k, m, changepoint.ts)
Arguments
t
Vector of times on which the function is evaluated.

deltas
Vector of rate changes at each changepoint.

k
Float initial rate.

m
Float initial offset.

changepoint.ts
Vector of changepoint times.

The question is how do i implement those variables into the m = Prophet() function and where do i get "deltas". 

Has somebody experience with that model? Looking forward to discussion

**Comment by bletham** [comment]
The equivalent python function is here: https://github.com/facebook/prophet/blob/master/python/fbprophet/forecaster.py#L1106

`t` is the times at which we are evaluating the trend function, and `changepoint_ts` are the times of the changepoints with which the model was fit. The other things (`deltas`, `k`, and `m`) are parameters that are fit to the data. They show up in the Stan model here, which implements the same piecewise linear trend function: https://github.com/facebook/prophet/blob/master/python/stan/unix/prophet.stan#L69

So `deltas` will be fit in Stan. On a fitted model, it is accessible as `self.params['delta']`.

**Comment by AntonioBlago** [comment]
Thanks @bletham 
so i found out that the linear model is the piecewise linear model 

 `if self.growth == 'linear':`
            `trend = self.piecewise_linear(t, deltas, k, m, `self.changepoints_t)`

but i don't get access to the parameters: 
https://github.com/facebook/prophet/blob/9928dc39aeac310d143396595f07b254744ce0bf/python/stan/unix/prophet.stan#L69

**Comment by bletham** [comment]
I'm not sure what you mean by not having access to the parameters. The fitted parameters are stored on `m.params`, is that what you mean?

**Comment by AntonioBlago** [comment]
@bletham, I could not call these parameters via the console with `self.params` but `model.params` gives me them! Thanks!
