### ISSUE TITLE
How is yhat uncertainty estimated in the historical period

### ISSUE THREAD

**Issue by tommylees112** [facebook/prophet#727]
Data:
[evi_mean.txt](https://github.com/facebook/prophet/files/2549584/evi_mean.txt)
Code:
```
df = pd.read_table("evi_mean.txt",delimiter=" ")

m = Prophet.Prophet(yearly_seasonality=4, 
                    daily_seasonality=False, 
                    weekly_seasonality=False,
                    seasonality_mode="multiplicative",
                    changepoint_prior_scale=5e-2)

m.fit(df)

future = m.make_future_dataframe(periods=365*3)
forecast = m.predict(future)
fig1 = m.plot(forecast);
fig2 = m.plot_components(forecast);
```
![evi_prophet1](https://user-images.githubusercontent.com/21049064/48012234-7b11db80-e119-11e8-9b2f-2394a93c1524.png)

![evi_prophet2](https://user-images.githubusercontent.com/21049064/48012276-9250c900-e119-11e8-974b-8da48d639ece.png)

I understand that the parameters have been fit using the Stan optimisation and so there are no parameter uncertainties estimated. But I have been looking through the code and I don't understand how `yhat_upper` and `yhat_lower` are estimated in the `forecast` dataframe above. All of the component parts (trend_upper, trend_lower, yearly_upper ...) are constant throughout, so where does this uncertainty come from? 

Could you let me know how it is calculated and also point me to the function in which it is calculated? 

Thanks very much 

Tommy

**Comment by tommylees112** [comment]
I understand the uncertainties for FUTURE are based on the following process:
i) trend has a constant rate (the solid line)
ii) there are S changepoints in the history (T timesteps)
iii) therefore, a rate of S/T changepoints with an average magnitude of $\delta$
iv) given the historical average we simulate this many changes to the trend into the future 

How is this done for the data that already exists? for the data that we have fit our model to?

Thanks for your help guys!

**Comment by xiaoyaoyang** [comment]
Well, I don't quite understand the process yet but if one is able to predict it for the future, he will always be able to do it for the past since you can simply treat parts of your past data as "future"

**Comment by bletham** [comment]
@tommylees112 There are three types of uncertainty in the model. The first is future trend uncertainty, which you correctly described. The second is parameter uncertainty, which you also correctly observed is not present because MCMC was not done. The third type, and the source of the uncertainty in the past here, is that there is a noise term in the model. Specifically, the model is
```
y(t) = trend(t) + seasonality(t) + regressors(t) + noise
```
where `noise ~ Normal(0, sigma)` and the noise variance `sigma` is fit to the data. `yhat_lower` and `yhat_upper` are in the history just the quantiles of that noise distribution.
