### ISSUE TITLE
Outlier consideration when fitting a model

### ISSUE THREAD

**Issue by ispmarin** [facebook/prophet#728]
Hi all,

I'm fitting a model with large seasonal variation (daily and weekly) and prophet is capturing these patterns well. The problem is that it is considering the highest daily values as outliers and the total amplitude of the forecast is well below the data. How does prophet considers values as outliers on the forecast process?

**Comment by vhpietil** [comment]
It may be that the fourier order of the daily seasonality is not high enough to allow the daily seasonality to change rapid enough to fit those largest values. 

As far as I can tell Prophet does not consider any data as outlier. The fourier series based seasonality just can’t always fit the data if the data has too rapid changes

Including a plot would demostrate your problem better ;)
