### ISSUE TITLE
fbprophet 0.3.post2 installed but cannot import to Jupyter Notebook (no module named fbprophet)

### ISSUE THREAD

**Issue by gblack686** [facebook/prophet#729]
I have the following packages installed in my virtual environment, but when I go to import fbprophet, it says no module found. Do I have to be in a certain directory in order to import the package? I'm running my Jupyter Notebook within the same virtual environment. 

Please advise... I have a technical exam due Sunday in which I was hoping to use fbprophet

gblac@LAPTOP-8S12FEEB MINGW32 ~
$ pip list
Package              Version
-------------------- ----------
arrow                0.12.1
asn1crypto           0.24.0
beautifulsoup4       4.6.3
bokeh                1.0.0
branca               0.3.0
bs4                  0.0.1
certifi              2018.10.15
cffi                 1.11.5
chardet              3.0.4
click                6.7
compass              0.1.4
cryptography         2.3.1
cycler               0.10.0
Cython               0.29
dash                 0.28.1
dash-core-components 0.30.2
dash-html-components 0.13.2
dash-renderer        0.14.1
decorator            4.3.0
docx                 0.2.4
fbprophet            0.3.post2
Flask                1.0.2
Flask-Compress       1.4.0
Flask-PyMongo        2.1.0
Flask-SQLAlchemy     2.3.2
folium               0.6.0
gmplot               1.2.0
idna                 2.7
ipython-genutils     0.2.0
itsdangerous         0.24
Jinja2               2.10
jsonschema           2.6.0
jupyter-core         4.4.0
kiwisolver           1.0.1
lxml                 4.2.5
MarkupSafe           1.1.0
matplotlib           3.0.1
mimesis              0.0.5
mkl-fft              1.0.6
mkl-random           1.0.2
msgpack              0.5.6
mysql                0.0.2
mysql-connector      2.1.6
mysqlclient          1.3.13
nbformat             4.4.0
numpy                1.15.4
olefile              0.46
packaging            18.0
pandas               0.23.4
Pillow               5.2.0
pip                  18.1
plotly               3.3.0
proj                 0.1.0
pscript              0.6.1
pycparser            2.19
pymongo              3.7.1
PyMySQL              0.8.1
pyOpenSSL            18.0.0
pyparsing            2.3.0
PyPDF2               1.26.0
PySocks              1.6.8
pystan               2.18.0.0
python-dateutil      2.7.5
python-docx          0.8.7
pytz                 2018.7
PyYAML               3.13
requests             2.19.1
retrying             1.3.3
scikit-learn         0.20.0
scipy                1.1.0
selenium             3.14.1
Send2Trash           1.5.0
setuptools           40.5.0
six                  1.11.0
splinter             0.9.0
SQLAlchemy           1.2.13
tornado              5.1.1
traitlets            4.3.2
urllib3              1.24.1
Werkzeug             0.14.1
wheel                0.32.2
win-inet-pton        1.0.1
wincertstore         0.2
(pythondata)

**Comment by bletham** [comment]
Well sorry for the slow response and not making it by Sunday.
I'm not exactly sure what is happening here but my guess would be that Jupyter is using a different version of Python than the system python. I wonder if it might be a py2 vs py3 thing? Could you check
```
pip --version
```
and see if it is python2 or python3, and then check if your Jupyter kernel is on the same version?
