### ISSUE TITLE
How do you interpret the "yearly" column of the forecast data frame when using multiplicative seasonality?

### ISSUE THREAD

**Issue by sfhansen** [facebook/prophet#730]
I'm using prophet to model a times series of data represented as monthly counts of a variable over several years. There's evidence of multiplicative seasonality, so I am using that parameter along with yearly seasonality to fit the model. 

After I obtain the `forecast` data frame, there are columns for the `trend` and `yearly` values. Can you explain how we interpret the `yearly` values, and how they interact with the `trend` column when we're using multiplicative seasonality? 

For instance, let's say the first row of the `forecast` data frame has:

`trend`: "50000"
`yearly`: "0.01"

What exactly do these terms mean, and how do they interact?

**Comment by vhpietil** [comment]
If I remember correctly, the final forecast is trend * (1+yearly (+weekly+daily etc)). So in your example on the current point of the year the forecasted value is a bit higher than the trend (1%). 

Sum of yearly seasonality over a year is zero. Thus yearly seasonality tells where the forecast goes up and where it goes down compared to the trend
