### ISSUE TITLE
How to improve accuracy of records with lowest accuracy levels?

### ISSUE THREAD

**Issue by dhanashreearole** [facebook/prophet#735]
Hello Ben and Development Team,

I use error (= absolute value of difference between actual and forecast), error ratio (= error/actual) and accuracy level (1- (error ratio)) to determine how good the predictions are at daily level. If the data values are too small, I roll it up to monthly level which helps improve the accuracy levels.

Although is it possible to focus on the months with lowest accuracy levels and run the predictions in iterative manner so that the second or third iteration shows better accuracy % ?

![image](https://user-images.githubusercontent.com/43793310/48414948-07279280-e71a-11e8-8e0c-be15c2954caf.png)

The image shows that Jan 2018 has lowest accuracy level. Any suggestions on how it can be improved so that it reaches at least 80%? Ideally the goal is to have 90% accuracy level at record level.

Thanks,
Dhanashree

**Comment by bletham** [comment]
To be clear, the accuracy here is a predictive accuracy, where you have fit the model with data only through 2016 and then are making forecasts for 2017 and 2018?

I'd recommend plotting the forecast and seeing for the months with low accuracy if there are any features of the time series in those months that are being missed. Maybe holidays that could be modeled?
