### ISSUE TITLE
Is it possible to use prophet in a R script and Run it on AWS ?

### ISSUE THREAD

**Issue by SaswatMahapatra** [facebook/prophet#736]
Hi Ben,

I am planning to implement porphet forecasting model for a particular forecasting model.
Can I use it in a R script where I am fetching and writing data from mongo using mongolite package in R , and run this script on AWS as a daily scheduler on daily basis ?

And one more query,
is it possible to add another external regressor into prophet like xreg, in ARIMA ?

**Comment by bletham** [comment]
Yes, running this as an R script on AWS shouldn't be an issue as long as the instance has the necessary packages installed.

As for extra regressors, yes, they can be added as described here: https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#additional-regressors

**Comment by SaswatMahapatra** [comment]
Thanks for the reply ,
Can I use it on production level , as I’m trying to integrate it on my
product.
Is there any issue regarding that ?

**Comment by bletham** [comment]
I can't think of any special considerations, are there any issues you're particularly worried about?

**Comment by SaswatMahapatra** [comment]
Like is there any copyright issues or something I should be aware of ?

**Comment by bletham** [comment]
I don't have any expertise on legal issues, but the license and patent grants are pretty short and readable here:
https://github.com/facebook/prophet/blob/master/LICENSE
https://github.com/facebook/prophet/blob/master/PATENTS

**Comment by bletham** [comment]
Note that it is a standard 3-clause BSD license, which you can find many resources for understanding, e.g. https://opensource.org/licenses/BSD-3-Clause

**Comment by SaswatMahapatra** [comment]
Sure thanks for your time Ben.

**Comment by SaswatMahapatra** [comment]
Hi Ben,
Im trying to install prophet on CentOS 7  
Im getting these error.


* installing *source* package ‘rstan’ ...

** package ‘rstan’ successfully unpacked and MD5 sums checked

** libs

Error in .shlib_internal(args) :
 C++14 standard requested but CXX14 is not defined

* removing ‘/usr/local/lib64/R/library/rstan’

ERROR: dependency ‘rstan’ is not available for package ‘prophet’

* removing ‘/usr/local/lib64/R/library/prophet’


The downloaded source packages are in
    ‘/tmp/RtmpNoczSf/downloaded_packages’



Can you help me here.

**Comment by bletham** [comment]
It looks like you need to set the C++ toolchain to use C++14, in order to install rstan. See the "C++ toolchain configuration" section here: https://github.com/stan-dev/rstan/wiki/Installing-RStan-on-Linux

This is a new requirement as one of the recent rstan releases. I expect we will also need to make this change in the Prophet Makevars (in R/src/), so I'm going to flag this as a bug until we have a chance to update those and make sure it's working with the latest rstan.

**Comment by bletham** [comment]
Actually I'll open a new issue for it.
