### ISSUE TITLE
Changing uncertainty intervals

### ISSUE THREAD

**Issue by JdHondt** [facebook/prophet#737]
Dear developers,

First of all, I would like to thank you for this amazing algorithm.
It has helped me with numerous projects.

One question; how come that my uncertainty interval, and particularly the values of my yhat_lower and yhat_upper can change from one run to the other?
I am trying to calculate the percentage that the actual date of reaching a value falls outside of the uncertainty interval.

Thanks in advance,

Jens

**Comment by IronistM** [comment]
Maybe this issue sheds some light to what is going on the calculations https://github.com/facebook/prophet/issues/478 .

**Comment by bletham** [comment]
+1 for what @IronistM says.

The fitting is deterministic and I wouldn't expect much variance in the parameters across different fits (you can look at `m.params['delta']` to see the fitted change magnitudes and see if they are varying across fits).

Most of the variance will come from the Monte Carlo sampling used to estimate the quantiles. You can decrease the variance of that by increasing the `uncertainty_samples` argument, which defaults to 1000. For example, `m = Prophet(uncertainty_samples=10000)`.
