### ISSUE TITLE
Error with cross validation: Error in bind_rows_(x, .id) : Argument 1 must have names

### ISSUE THREAD

**Issue by EnricowithR** [facebook/prophet#742]
When running the cross validation with the following code:
df.cv <- cross_validation(m, initial = 360, horizon = 30, units = 'days')

The output is the following with the error below. Why is that happening?

Initial log joint probability = -10.8463
Optimization terminated normally: 
  Convergence detected: relative change in objective function was below tolerance
Initial log joint probability = -14.16
Optimization terminated normally: 
  Convergence detected: relative gradient magnitude is below tolerance
 Show Traceback
Error in bind_rows_(x, .id) : Argument 1 must have names

**Comment by EnricowithR** [comment]
I found already the issue, the dataframe for the training should contain only the variables used for training

**Comment by adrfantini** [comment]
This also happens if the passed dataframe is, for example, a `tsibble`. Even if it only has two columns (`ds` and `y`). I would personally consider this a bug and reopen this issue.
