### ISSUE TITLE
Is there a way to incorporate weather data into Prophet?

### ISSUE THREAD

**Issue by oren0e** [facebook/prophet#743]
Hi,

I want to be able to incorporate weather data, beyond seasonality. For instance, if there were 2 days of a bad storm on particular dates - this will affect my metrics. Does including these days in the changepoints vector of dates is a proper way to deal with this?
Thanks in advance for any help :)

**Comment by vhpietil** [comment]
It is hard to say without seeing the data, but I would guess that using holidays or external regressors would give better results

**Comment by oren0e** [comment]
@vhpietil: I'm talking about a general solution which doesn't depend on a particular dataset.
I'm not sure but isn't the holiday list is something that repeats each year? A particularly bad storm is something that doesn't repeat itself each year necessarily

**Comment by IronistM** [comment]
Personally, I use a calendar for this kind of events (which is in a way like using external  dummy encoded regressors).

**Comment by oren0e** [comment]
@IronistM: yes but that's my question - how can you incorporate external dummies or other regressors with the prophet package?

**Comment by vhpietil** [comment]
See https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html

**Comment by eromoe** [comment]
@vhpietil I add regressors but got error https://github.com/facebook/prophet/issues/741

**Comment by oren0e** [comment]
> See https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html

Thank you! That was what I've been looking for, I totally missed the add_regressor() part.
