### ISSUE TITLE
Error: package or namespace load failed for ‘prophet’ in SAP HANA DB

### ISSUE THREAD

**Issue by Jchen1628** [facebook/prophet#745]
Hi guys,

I have installed prophet on a R Server (version 3.4.0) running on Linux Enterprise Server 12 SP3.
It is set up for HANA access so that any R procedures can be executed in the HANA data base via R integration. So far it works with any library properly except with prophet.
Whenever I try to load the library in the SAP HANA DB via R integration I get the following Error message:

 Could not execute 'call ...' in 662 ms 101 µs . 
SAP DBTech JDBC: [2048]: column store error: search table error:  [34082] Execution of R script failed;Error: package or namespace load failed for ‘prophet’:
 .onLoad failed in loadNamespace() for 'prophet', details:
  call: base::file(tf, open = "wt")
  error: cannot open the connection
stack trace: 
6: stop(msg, call. = FALSE, domain = NA)
5: value[[3L]](cond)
4: tryCatchOne(expr, names, parentenv, handlers[[1L]])
3: tryCatchList(expr, classes, parentenv, handlers)
2: tryCatch({
       attr(package, "LibPath") <- which.lib.loc
       ns <- loadNamespace(package, lib.loc)
       env <- attachNamespace(ns, pos = pos, deps)
   }, error = function(e) {
       P <- if (!is.null(cc <- conditionCall(e))) 
           paste(" in", deparse(cc)[1L])
       else ""
       msg <- gettextf("package or namespace load failed for %s%s:\n %s", 
           sQuote(package), P, conditionMessage(e))
       if (logical.return) 
           message(paste("Error:", msg), domain = NA)
       else stop(msg, call. = FALSE, domain = NA)
   })
1: library(prophet) 

Any suggestions on how to solve this are much appreciated!

**Comment by bletham** [comment]
I don't have any experience with SAP HANA and so don't know that I'll be able to be very helpful. The dependencies for prophet are a bit more complex than for most packages (Stan), and I wonder if maybe something is going wrong there. Could you see if you can load rstan in SAP HANA?
