### ISSUE TITLE
 How to judge a product has seasonality.

### ISSUE THREAD

**Issue by jiayouanan** [facebook/prophet#748]
Hi, I use prophet to fit the sales of beef in the past 2 and a half years。I got the following result：

![11](https://user-images.githubusercontent.com/42060610/48903988-fb656a00-ee97-11e8-99bd-043940d7ddc9.png)

![22](https://user-images.githubusercontent.com/42060610/48904105-5303d580-ee98-11e8-9851-0bccd442dee4.png)

We can see that the result is not bad. **My purpose is to prove that beef is a seasonal product.** But I don't know how to prove my purpose from the yearly_seasonality component chart. Can someone tell me a way to judge that the product is a seasonal product?

Thank you for your great help!

**Comment by bletham** [comment]
I have two suggestions.

The first is to turn on MCMC (https://facebook.github.io/prophet/docs/uncertainty_intervals.html#uncertainty-in-seasonality), which will give you uncertainty bands for seasonality. If those uncertainty bands are far from 0%, then that provides evidence that there are significant seasonal effects.

A second possibility would be to do cross-validation (https://facebook.github.io/prophet/docs/diagnostics.html) both with yearly seasonality on and off, and compare if you have better predictive accuracy with seasonality on than off. That would also provide evidence that there is a seasonal effect that the model is able to capture and use to improve predictions.

**Comment by jiayouanan** [comment]
> I have two suggestions.
> 
> The first is to turn on MCMC (https://facebook.github.io/prophet/docs/uncertainty_intervals.html#uncertainty-in-seasonality), which will give you uncertainty bands for seasonality. If those uncertainty bands are far from 0%, then that provides evidence that there are significant seasonal effects.
> 
> A second possibility would be to do cross-validation (https://facebook.github.io/prophet/docs/diagnostics.html) both with yearly seasonality on and off, and compare if you have better predictive accuracy with seasonality on than off. That would also provide evidence that there is a seasonal effect that the model is able to capture and use to improve predictions.

ok, I get it. Thank you very much.
