### ISSUE TITLE
ufunc 'true_divide' not supported for the input types

### ISSUE THREAD

**Issue by DanyangSu** [facebook/prophet#750]
![screen shot 2018-11-23 at 12 42 29 am](https://user-images.githubusercontent.com/32192334/48929645-b30a7400-eeb8-11e8-855e-7c6f01e350fa.png)
Hi I am trying to use the fb model, and I run into this error. After some diagnosis, it seems the issue is with pandas version. when I use 0.20.1, everything seems fine, but when I use 0.23.4, I got the error. Since I am trying to use newer version of pandas to accommodate other packages, is it possible to have Prophet accommodate to it as well?

**Comment by DanyangSu** [comment]
A quick update, it has nothing to do with pandas version. Changing the version caused another issue that occurred before invoking Prophet.

**Comment by bletham** [comment]
@DanyangSu sorry for the slow response, I somehow missed this issue. 

I haven't run into this issue myself and am not entirely sure what is happening. Could you paste the the code you ran that produced it? And ideally attach the data csv too?

My one guess is that the date column might be getting parsed badly (pandas does this automagically, and sometimes gives wonky results). Can you verify that that ds column is of the format `YYYY-MM-DD` for daily data, or `YYYY-MM-DD HH:MM:SS` for timestamps?

**Comment by DanyangSu** [comment]
Hi,

I was able to fogure out the issue, I was passing ‘14’ as a string instead
of a number. So I think an easy fix would be to check input type.

Danyang

**Comment by bletham** [comment]
Was this in the `y` column  or `ds`? `y` is converted with pd.to_numeric so there shouldn't be an issue there. Unless it was in an extra regressor, in which case those were not being converted but that bug was recently fixed.

**Comment by DanyangSu** [comment]
It’s for ds. I was using docopt to parse days and I forgot to convert them
before feeding them to fbprophet, so I ended up having option ds=‘30’ not
ds=30, which caused the problem. But if you have already implement some
guardrails, then that’s fine you can close this issue.
