### ISSUE TITLE
Undeterministic order of dictionary items with serializing/deserializing Prophet model

### ISSUE THREAD

**Issue by bjlkeng** [facebook/prophet#752]
I'm trying to use Prophet with `joblib` (where I implicitly will serialize and deserialize a Prophet model).  I get the following error when trying to `predict()`:

```
A bug occurred in constructing regressors.
```
(Here: https://github.com/facebook/prophet/blob/v0.3/python/fbprophet/forecaster.py#L721)

I traced it down and I think the error is caused by the fact the serialize/deserialization process causes the order of keys in some dictionaries (e.g. `self.extra_regressors` and `self.seasonalities`) to change.  This causes problems in `make_all_seasonality_features()` on lines:

* https://github.com/facebook/prophet/blob/v0.3/python/fbprophet/forecaster.py#L616
* https://github.com/facebook/prophet/blob/v0.3/python/fbprophet/forecaster.py#L638

I believe you just need to wrap the iteration of `items()` in a `sorted()`, it seems to work out when I modified my local copy.  Unfortunately, it's kind of hard for me to put a use-case together but I think the logic makes sense.  Let me know if you have any questions.

**Comment by bletham** [comment]
Thanks for raising this bug. There's some discussion of it in #643, and it was fixed in #688. So if you install the current github version it will have the fix, but we are also going to push a new version with the fix to pip in the next few days.

**Comment by bjlkeng** [comment]
Great!  Thanks for responding so quickly.  I'll close the ticket since it's fixed.
