### ISSUE TITLE
prophet limits 

### ISSUE THREAD

**Issue by bthornhill417** [facebook/prophet#754]
I am attempting to use prophet to create a forecast of a date of when a project will end based on a decreasing number of test cases. While using prophet I can get the prediction and lower limit to converge to 0, like the photo below, but sometimes my upper limit is really extreme and won't converge. Is there anyway to fix/manipulate this? 

![prophet limit](https://user-images.githubusercontent.com/45239786/49101220-489c5f80-f23b-11e8-8972-ba6f505484ff.png)

**Comment by bletham** [comment]
discussion in #747
