### ISSUE TITLE
Description of the estimates

### ISSUE THREAD

**Issue by 14mprb** [facebook/prophet#755]
Once I fitted my model (with regressor), I would like to have a view on the value of the estimates, their significance level, etc. I cannot find such command. Can you tell me what to use and where should have I be able to find that because it is absent from the doc?

What makes me want to see that is because my predictions are the same whether or not I include my dummie as regressor and I find it puzzling.

**Comment by bletham** [comment]
The fitted coefficients are in `m.params['beta']` (Py, or `m$params$beta` in R). This will be an array of the coefficient values. To see what coefficient corresponds to which component, you can look at `m.train_component_cols` in Py or `m$train.component.cols` in R. I give a description of what this is in #361.

That said, probably the easiest way to see what is happening with your extra regressor would be to just make the components plot, like at the bottom of https://facebook.github.io/prophet/docs/quick_start.html#python-api . This plot will include the contribution of the extra regressors to the `yhat` estimate. If it is very small, it means it is not being used.

**Comment by 14mprb** [comment]
Is there a documentation where I could have found such info?

**Comment by bletham** [comment]
Not a ton... the docstring `help(Prophet.fit)` says where the fitted parameters are stored, but it isn't in the online documentation.

One complication (which is the reason we haven't exposed these parameters more openly) is that Prophet scales the data prior to fitting (see the `setup_dataframe` method/function), and these parameters are for the model in the scaled space. So the absolute value of any beta parameter is not directly meaningful, but their values relative to eachother are.

**Comment by nrchade** [comment]
So I poked around in m.params and have array of betas.  I understand that I can really only compare these to each other, but should be able to determine relative importance of my regressors.  For a model I'm testing I had 221 "betas" with 183 being regressors. "len(m.params['beta'][0])"  How can i easily match the beta values with the labels i.e. regressor names?  Not sure what the remaining 38 betas are from (i'm suspect some seasonal related betas)
