### ISSUE TITLE
ImportError: No module named expressions

### ISSUE THREAD

**Issue by galfaroi** [facebook/prophet#756]
Hi
When I (on linux python 2.7) do: 
`m.fit(df)`
It was working fine now I have the following error:

/home/german/miniconda2/lib/python2.7/site-packages/fbprophet/forecaster.pyc in fit(self, df, **kwargs)
    936         self.history_dates = pd.to_datetime(df['ds']).sort_values()
    937 
--> 938         history = self.setup_dataframe(history, initialize_scales=True)
    939         self.history = history
    940         self.set_auto_seasonalities()

/home/german/miniconda2/lib/python2.7/site-packages/fbprophet/forecaster.pyc in setup_dataframe(self, df, initialize_scales)
    254         df.reset_index(inplace=True, drop=True)
    255 
--> 256         self.initialize_scales(initialize_scales, df)
    257 
    258         if self.logistic_floor:

/home/german/miniconda2/lib/python2.7/site-packages/fbprophet/forecaster.pyc in initialize_scales(self, initialize_scales, df)
    297         else:
    298             floor = 0.
--> 299         self.y_scale = (df['y'] - floor).abs().max()
    300         if self.y_scale == 0:
    301             self.y_scale = 1

/home/german/miniconda2/lib/python2.7/site-packages/pandas/core/ops.pyc in wrapper(left, right)
   1067                 casted = pd.Series(other, index=self.index)
   1068             else:
-> 1069                 # casted = self._constructor_sliced(other, index=self.columns)
   1070                 casted = pd.Series(other, index=self.columns)
   1071             return self._combine_series(casted, na_op, fill_value, axis, level)

/home/german/miniconda2/lib/python2.7/site-packages/pandas/core/ops.pyc in safe_na_op(lvalues, rvalues)
   1031         ----------
   1032         other : Series, DataFrame, or constant
-> 1033         axis : {0, 1, 'index', 'columns'}
   1034             For Series input, axis to match Series index on
   1035         fill_value : None or float value, default None

/home/german/miniconda2/lib/python2.7/site-packages/pandas/core/ops.pyc in na_op(x, y)
   1007                                     op=name, x=type(x), y=type(y)))
   1008 
-> 1009             result, changed = com._maybe_upcast_putmask(result, ~mask, np.nan)
   1010             result = result.reshape(x.shape)
   1011 

ImportError: No module named expressions

**Comment by bletham** [comment]
This is happening inside Pandas and I wonder if something has become misconfigured there. What version of pandas do you have installed?
```
import pandas
pandas.__version__
```
Could you try re-installing it?

**Comment by galfaroi** [comment]
yes, you're right, using my python3 env for now, will be back later to solve the Pandas issue,

Thanks!
