### ISSUE TITLE
AttributeError: 'Prophet' object has no attribute 'regressor_column_matrix'

### ISSUE THREAD

**Issue by ahbon123** [facebook/prophet#757]
When I try to run following code: 
`model = Prophet(seasonality_mode='multiplicative', mcmc_samples=300).fit(df)
fcst = model.predict(future)
fig = model.plot_components(fcst)`

the traceback points to an AttributeError as follows:

"Traceback (most recent call last):
  File "<ipython-input-223-4860aefdc2d6>", line 1, in <module>
    model = Prophet(seasonality_mode='multiplicative', mcmc_samples=300).fit(df)
  File "C:\Users\User\Anaconda3\lib\site-packages\fbprophet\forecaster.py", line 942, in fit
    self.make_all_seasonality_features(history))
  File "C:\Users\User\Anaconda3\lib\site-packages\fbprophet\forecaster.py", line 650, in make_all_seasonality_features
    component_cols, modes = self.regressor_column_matrix(
AttributeError: 'Prophet' object has no attribute 'regressor_column_matrix'"

**Comment by bletham** [comment]
You can now install v0.4 with
```
devtools::install_github('facebookincubator/prophet', subdir='R')
```
I' expect a reinstall to resolve this.
