### ISSUE TITLE
Changed variance throughout the year

### ISSUE THREAD

**Issue by steeks91** [facebook/prophet#758]
Hi,

Thanks for a great package. How can I handle data that has changed variance throughout the year. For example:
![image](https://user-images.githubusercontent.com/22839730/49148349-6afbaf00-f307-11e8-8fc9-dbd2c000ba5a.png)

When I try to model this with Prophet, it seems to estimate constant variance. Even though the variance is clearly lower during Winter and Summer
![image](https://user-images.githubusercontent.com/22839730/49148480-c7f76500-f307-11e8-9ee6-71bea7073808.png)

**Comment by steeks91** [comment]
Thank you for your answer! 
I tried that but it makes no difference in the model. The predictions are exactly the same (which surprised me). I thought I did something wrong but when I look at the component plots, all of the components are describes as % of the trend. Precisely as it should according to the document...

**Comment by steeks91** [comment]
![image](https://user-images.githubusercontent.com/22839730/49360820-96511600-f6da-11e8-9a00-803a77b76db0.png)
![image](https://user-images.githubusercontent.com/22839730/49360880-c8fb0e80-f6da-11e8-9466-dbcb08a537bd.png)

**Comment by bletham** [comment]
I see, I had thought those two big dips were trend changes but now see that they're yearly seasonality. Like I said above, this is seasonality-depending-on-another-seasonal-factor which isn't really well supported yet.

You could try defining custom extra regressors to learn those effects on weekend days during July and Dec, but I think the simplest thing that I would probably try would be just to forecast the weekend days separately from the weekdays. If you fit a model to weekday days only and make a forecast for only weekdays, it seems like it would be pretty good. You could then merge that with a another model that is fit to weekend days only.

**Comment by steeks91** [comment]
Thank you very much Ben! That is a very good suggestion, I will try that! 
Much appreciated feedback, thanks spending time helping out! 🥇
