### ISSUE TITLE
C++14 standard requested but CXX14 is not defined

### ISSUE THREAD

**Issue by bletham** [facebook/prophet#760]
From #736, an install issue
```
installing source package ‘rstan’ ...
** package ‘rstan’ successfully unpacked and MD5 sums checked

** libs

Error in .shlib_internal(args) :
C++14 standard requested but CXX14 is not defined

removing ‘/usr/local/lib64/R/library/rstan’
ERROR: dependency ‘rstan’ is not available for package ‘prophet’

removing ‘/usr/local/lib64/R/library/prophet’
The downloaded source packages are in
‘/tmp/RtmpNoczSf/downloaded_packages’
```

is due to not setting C++14 in the C++ toolchain (https://github.com/stan-dev/rstan/wiki/Installing-RStan-on-Linux). This probably needs to be updated in Prophet Makevars also.

**Comment by bletham** [comment]
This is a new thing with Stan 2.18. From what I can tell, this issue only comes up: (1) when installing rstan from source in Windows, or (2) in packages that ship compiled models (https://discourse.mc-stan.org/t/how-to-update-a-package-that-has-stanheaders-and-rstan-in-its-linkingto/6041). Since we're compiling the model locally on install, I haven't found anything that indicates we need to change anything. I am able to successfully install Prophet in R with rstan 2.18.1, so I think we should be OK and am closing this.

**Comment by statwonk** [comment]
Just ran into this on Ubuntu,

```
* installing *source* package ‘rstan’ ...
** package ‘rstan’ successfully unpacked and MD5 sums checked
** libs
Error in .shlib_internal(args) :
  C++14 standard requested but CXX14 is not defined
* removing ‘/home/ubuntu/R_library/rstan’
ERROR: dependency ‘rstan’ is not available for package ‘prophet’
* removing ‘/home/ubuntu/R_library/prophet’
```

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

I've run into this before. I'll report back if I find a solution. 👍

**Comment by bgoodri** [comment]
It is the same issue. On Linux, you need to have

CXX14FLAGS += -fPIC

https://github.com/stan-dev/rstan/wiki/Installing-RStan-on-Linux

**Comment by Steviey** [comment]
+1

**Comment by thistleknot** [comment]
`
cat ~/.R/Makevars
CXX14 = g++
CXX14FLAGS = -O3
CXX14FLAGS += -fPIC
#LIBS += -lm
`
