### ISSUE TITLE
FB Prophet failed building wheels

### ISSUE THREAD

**Issue by sarapython** [facebook/prophet#763]
HI I have spent a couple hours trying install fbprophet,  but I keep getting this. I downloaded microsoft build tools and this error starts....please help
C:\Users\T910571>pip install fbprophet
Collecting fbprophet
  Using cached https://files.pythonhosted.org/packages/83/a1/a39be1675a62597e4c0d4fdaeb65b14752b8aa8afc92e90edd91614353ab/fbprophet-0.3.post2.tar.gz
Requirement already satisfied: Cython>=0.22 in c:\programdata\anaconda3\lib\site-packages (from fbprophet) (0.28.2)
Requirement already satisfied: pystan>=2.14 in c:\programdata\anaconda3\lib\site-packages (from fbprophet) (2.18.0.0)
Requirement already satisfied: numpy>=1.10.0 in c:\programdata\anaconda3\lib\site-packages (from fbprophet) (1.14.3)
Requirement already satisfied: pandas>=0.20.1 in c:\programdata\anaconda3\lib\site-packages (from fbprophet) (0.23.0)
Requirement already satisfied: matplotlib>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from fbprophet) (2.2.2)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.20.1->fbprophet) (2.7.3)
Requirement already satisfied: pytz>=2011k in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.20.1->fbprophet) (2018.4)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=2.0.0->fbprophet) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=2.0.0->fbprophet) (2.2.0)
Requirement already satisfied: six>=1.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=2.0.0->fbprophet) (1.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=2.0.0->fbprophet) (1.0.1)
Requirement already satisfied: setuptools in c:\programdata\anaconda3\lib\site-packages (from kiwisolver>=1.0.1->matplotlib>=2.0.0->fbprophet) (39.1.0)
Building wheels for collected packages: fbprophet
  Running setup.py bdist_wheel for fbprophet ... error
  Complete output from command C:\ProgramData\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\T910571\\AppData\\Local\\Temp\\pip-install-udpoo5tj\\fbprophet\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\T910571\AppData\Local\Temp\pip-wheel-un_kth4s --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\fbprophet
  creating build\lib\fbprophet\stan_model
  DIAGNOSTIC(S) FROM PARSER:
  Warning: left-hand side variable (name=cp_idx) occurs on right-hand side of assignment, causing inefficient deep copy to avoid aliasing.
  Warning: left-hand side variable (name=k_s) occurs on right-hand side of assignment, causing inefficient deep copy to avoid aliasing.
  Warning: left-hand side variable (name=m_pr) occurs on right-hand side of assignment, causing inefficient deep copy to avoid aliasing.

  INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_db8febf10f23d7fa27a62fbcfd7f17b2 NOW.
  WARNING:pystan:MSVC compiler is not supported
  error: command 'cl.exe' failed: No such file or directory

  ----------------------------------------
  Failed building wheel for fbprophet
  Running setup.py clean for fbprophet
Failed to build fbprophet
Installing collected packages: fbprophet
  Running setup.py install for fbprophet ... error
    Complete output from command C:\ProgramData\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\T910571\\AppData\\Local\\Temp\\pip-install-udpoo5tj\\fbprophet\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\T910571\AppData\Local\Temp\pip-record-kyt7h3ta\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\fbprophet
    creating build\lib\fbprophet\stan_model
    DIAGNOSTIC(S) FROM PARSER:
    Warning: left-hand side variable (name=cp_idx) occurs on right-hand side of assignment, causing inefficient deep copy to avoid aliasing.
    Warning: left-hand side variable (name=k_s) occurs on right-hand side of assignment, causing inefficient deep copy to avoid aliasing.
    Warning: left-hand side variable (name=m_pr) occurs on right-hand side of assignment, causing inefficient deep copy to avoid aliasing.

    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_db8febf10f23d7fa27a62fbcfd7f17b2 NOW.
    WARNING:pystan:MSVC compiler is not supported
    error: command 'cl.exe' failed: No such file or directory

    ----------------------------------------
Command "C:\ProgramData\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\T910571\\AppData\\Local\\Temp\\pip-install-udpoo5tj\\fbprophet\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\T910571\AppData\Local\Temp\pip-record-kyt7h3ta\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\T910571\AppData\Local\Temp\pip-install-udpoo5tj\fbprophet\

**Comment by ammarasmro** [comment]
Have you tried installing `pystan` before `fbprophet`

```python
pip install pystan
# Then install fbprophet
pip install fbprophet
```

**Comment by sarapython** [comment]
@ammarasmro Thanks for your response. I did install that 
pip install pystan
I don;t know of it's working properly or not
Requirement already satisfied: pystan in c:\programdata\anaconda3\lib\site-packages (2.18.0.0)
Requirement already satisfied: numpy>=1.7 in c:\programdata\anaconda3\lib\site-packages (from pystan) (1.14.3)
Requirement already satisfied: Cython!=0.25.1,>=0.22 in c:\programdata\anaconda3\lib\site-packages (from pystan) (0.28.2

**Comment by bletham** [comment]
The failure to build the wheel is because of #401 and isn't really breaking anything.

It does seem that pystan is not installing correctly due to the compiler not being configured. This is the part of the logs that sticks out to me:
```
WARNING:pystan:MSVC compiler is not supported
error: command 'cl.exe' failed: No such file or directory
```

You can tell if pystan is working by running this code:
```
import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this will take a minute
y = model.sampling(n_jobs=1).extract()['y']
y.mean()  # should be close to 0
```

I have personally found it to be very difficult to get pystan working in Windows other than in Anaconda. So I'd recommend installing pystan in Anaconda, and then you can install fbprophet in Anaconda as described here: https://facebook.github.io/prophet/docs/installation.html
