### ISSUE TITLE
Missed Seasonal Pattern

### ISSUE THREAD

**Issue by pkmurthy** [facebook/prophet#767]
I am using Prophet in Python.  I have daily and weekly seasonalities. I am also using holidays.
The data (parking lot occupancy) has a pattern whereby for a few hours every day the occupancy is basically 0.  The model fit is pretty good, except that for Saturdays on the low hours.  The actual is around 0, but the model estimate is around 10.  Saturday happens to be the peak day in terms of occupancy.

I have tried using 'multiplicative' and 'additive' seasonality and also logistic growth.
I have also tried calling out saturdays as a special type of holiday.
Nothing fixes the issue.

The Prophet code is below:

marLotOccupancy_model= Prophet( holidays=holidays, weekly_seasonality = 10, daily_seasonality=6,seasonality_mode='additive')
marLotOccupancy_model.fit(notH_historyData[useData])
notH_futureData=marLotOccupancy_model.make_future_dataframe(periods=720, freq='H')
notH_futureData['cap']=84.0
notH_futureData['floor']=0.0
notH_futureData.loc[selDates,'cap']=81.0
notH_forecast=marLotOccupancy_model.predict(notH_futureData)

The comparison between actuals and model estimates are below:
![image](https://user-images.githubusercontent.com/45676966/49629135-b6aff780-f99c-11e8-813b-8e09cf905d9b.png)

Note the gap between the blue (actual) and the orange (model) lines at the low points for
Aug-4, Aug-11 and Aug-18.

Any suggestions?

**Comment by bletham** [comment]
In this case the daily seasonality depends on the day-of-week. This phenomenon isn't very well supported yet - see #538, which is the open issue for this and has some other examples of daily seasonality depending on day-of-week.

What you would really want is to create a separate daily seasonality for Saturday. #434 does this for weekends vs. weekdays, but it's a bit complicated. The simpler option is to just forecast Saturday separately from the other days: Fit a model to just Saturday and use it to forecast for just Saturday dates, and then fit a model for other days and use it to forecast for the other days. That is simple and could work depending on the time series.

A better solution for this will be in the next version.

**Comment by bletham** [comment]
This feature has now been implemented in #538, and if anyone is able to give it a spin and report in that issue how it went that'd be really helpful.
