### ISSUE TITLE
No of changepoints in the plot and prophet object "m" don't match

### ISSUE THREAD

**Issue by sid0972** [facebook/prophet#770]
When i plot the changepoints i get different results than what i see in m$changepoints (in my case there is only one changepoint that is added to the plot, but m$changepoint gives 25 changepoints).

Why is there a discrepency between the two? How can i be sure which result is the correct one?

**Comment by vhpietil** [comment]
There are 25 changepoints but most of those have very small value. In you case I guess that only one has significant value.

**Comment by sid0972** [comment]
Ok so the most significant ones are plotted in the graph. Thank you.
