### ISSUE TITLE
relation between changepoint prior scale and number of changepoints

### ISSUE THREAD

**Issue by kumarvrsec** [facebook/prophet#780]
Is there any relation between changepoint prior scale and number of changepoints..like to know number of changepoints used..if changepoint prior scale is 0.01

**Comment by bletham** [comment]
In the generative model, we assume that trend change magnitudes at each changepoint are drawn from a distribution with scale changepoint.prior.scale (e.g., 0.01).

If we keep changepoint.prior.scale fixed and increase the number of changepoints, the average magnitude of the trend change at each point will stay more or less the same, but with more changepoints there will be room for more total change (i.e., more trend flexibility).

If we keep number of changepoints fixed but increase changepoint.prior.scale, then at each changepoint the trend is now allowed to change by a larger amount. Hence again more total change and more trend flexibility, but concentrated on the same number of changepoints.

Practically, in general I think you should find that you only need to turn one of these knobs, and it should be changepoint.prior.scale. If your time series has really frequent trend changes you may need to increase the number of changepoints to capture them all, but the default number (30) is likely already more than you will actually use. The key then becomes making sure that changepoint.prior.scale is such that it uses them in the right way. Like any regularization parameter, if it is too large then you may over-fit the trend changes, if it is too small then you may under-fit.
