### ISSUE TITLE
Error in filter_impl(.data, quo) : Evaluation error: as_dictionary()is defunct as of rlang 0.3.0

### ISSUE THREAD

**Issue by pavelenko** [facebook/prophet#781]
Hey
RSdutio (Windows) cant see any new version of prophet. After reinstall I still see v0.3.0.1
Thanks!

**Comment by fdrennan** [comment]
Yea, that would be nice. I'm finding prophet terribly impossible to install - on three separate computers.

**Comment by pavelenko** [comment]
Hi,again
After update manually I see this message from console window

```
>  m <- prophet(df,changepoint.prior.scale=scale,changepoint.range = range)
Disabling yearly seasonality. Run prophet with yearly.seasonality=TRUE to override this.
Disabling weekly seasonality. Run prophet with weekly.seasonality=TRUE to override this.
Warning messages:
1: `list_len()` is soft-deprecated as of rlang 0.2.0.
Please use `new_list()` instead
This warning is displayed once per session. 
2: The `printer` argument is soft-deprecated as of rlang 0.3.0.
This warning is displayed once per session. 
3: `lang()` is soft-deprecated as of rlang 0.2.0.
Please use `call2()` instead
This warning is displayed once per session. 
4: `new_overscope()` is soft-deprecated as of rlang 0.2.0.
Please use `new_data_mask()` instead
This warning is displayed once per session. 
5: `overscope_eval_next()` is soft-deprecated as of rlang 0.2.0.
Please use `eval_tidy()` with a data mask instead
This warning is displayed once per session. 
```

**Comment by donskerclass** [comment]
After updating to Prophet 0.4 (in RStudio on Mac with R version 3.50), after ignoring the warning messages, I am also seeing problems with rlang, related to the update to rlang 0.3.0.1 The error I get is 

`m <- prophet(df)
Error in filter_impl(.data, quo) : 
  Evaluation error: `as_dictionary()` is defunct as of rlang 0.3.0.
Please use `as_data_pronoun()` instead.`

Downgrading to rlang 0.2.0, I obtain

`library(prophet)
Error: package ‘rlang’ 0.2.0 was found, but >= 0.3.0.1 is required by ‘prophet’`

Reinstalling rlang 0.3.0.1, I get the same error again.

**Comment by yutannihilation** [comment]
@donskerclass Maybe your dplyr is too old to use with rlang 0.3.0? https://github.com/tidyverse/dplyr/issues/3941

**Comment by donskerclass** [comment]
Thanks, updating dplyr (to 0.7.8) solves the error. I get the same warnings as pavelenko, but no functionality seems to be affected.

**Comment by bletham** [comment]
The CRAN release took a bit extra long this time since we had some build issues on the CRAN testing machines that we had to figure out, but as you've noticed it has finally made it up.

@donskerclass thanks for pointing out the issue with dplyr. It looks like we'll have to raise our dplyr requirement to 0.7.7 then to be compatible with the rlang requirement (which was required to fix a bug in #592).

**Comment by lppier** [comment]
It would be great if 0.4 is in conda forge as well. Many thanks!

**Comment by bletham** [comment]
@lppier we're about to push a post release that will fix a few build issues and then we'll get it there too!

**Comment by bletham** [comment]
Pushed to CRAN
