### ISSUE TITLE
Minimum number of data points in time series

### ISSUE THREAD

**Issue by sophia-wright-blue** [facebook/prophet#783]
I hope this question makes sense:

I have time series usage data for about 1000 users. I'm able to run prophet on the entire dataset, and get very good results.

 But I'm also interested in individual user analysis. The problem I'm facing is that some of the users are very light users, and I only have a few data points for them. Hence, the question - Is there a minimum number of data points required to be able to accurately fit a Prophet model?

 I hope my query is clear. Please let me know if I can add any information that'd help with understanding the problem better.

 Any guidance on this or even links to related articles/posts would be very helpful.

Thanks,

**Comment by dhanashreearole** [comment]
Hi,
That is good question.
In my experience of monthly predictions, I have seen that prophet needs atleast 18 months to predict for 12 months, else it complains of not having enough datapoints. You will have to play with the input dataset and future dataframe parameters to conclude the minimum size of input dataset for how much in future you can predict. Hope that addresses your question!
Thanks,
Dhanashree

**Comment by sophia-wright-blue** [comment]
thanks for replying @dhanashreearole , i'm mostly interested in week ahead forecasts, and i have sparse data for the last few months, i'll experiment with fitting Prophet models. thanks again,

**Comment by bletham** [comment]
+1 for @dhanashreearole's comment, it really depends on the sort of structure that you need to capture, and how far you want to forecast. If you want to capture yearly seasonality, then you need at least a year of data, if you only care about weekly seasonality then a couple weeks would suffice. How far you can forecast out based on the size of your history also depends on how stable the time series is, but you could try using the cross validation on some of the longer ones to see what the forecast horizon looks like (that is, how far out can you get reasonable prediction error).

If you have some users that have more data that you think are examplars of typical usage, you could consider including their timeseries/forecast as an extra regressor for an individual user with less data. That user's forecast would then be biased towards the forecast for the user with more data, which could be useful shrinkage and reduce variance.

**Comment by sophia-wright-blue** [comment]
thanks for the clarification @bletham ; i'm clear about the duration of the data required for forecasting out;

my problem is that I need to be able to capture the usage patterns of sparse usage with a fair amount of confidence; i'll try your idea of add heavy user data as an extra regressor;

greatly appreciate your response and all of the work you put in to help the users of this amazing library! looking forward to more features in 2019!

**Comment by sushmit86** [comment]
@sophia-wright-blue were you able to do the user level analysis. I am trying to do a similar thing

**Comment by dhanashreearole** [comment]
I am not sure what you mean by user level analysis?
