### ISSUE TITLE
Docker Official fbprophet container?

### ISSUE THREAD

**Issue by lppier** [facebook/prophet#784]
Hi, 

Thank you for Prophet, it has helped me tremendously. 
Just wondering, are there any plans to maintain an official fbprophet container in docker hub? IMO, Prophet has landed and its time!

**Comment by bletham** [comment]
Since I personally have not used Docker I don't think I'm well suited to do this, but if someone else wants to own it (like for the conda-forge package, https://github.com/conda-forge/fbprophet-feedstock) I would certainly be supportive of that.

**Comment by lppier** [comment]
Hi @bletham , it's something I may be interested in doing. 
Is there any way I can automatically get news of major version updates to prophet?

**Comment by bletham** [comment]
Great!

I guess this is related to #465 and having a communication channel other than github issues. We're still a bit unsure on what the best solution there is. In the meantime I expect I can remember to comment on this issue when there is a release.

**Comment by bletham** [comment]
I don't have enough knowledge of docker to provide useful feedback, but I'm glad to hear that it works and it certainly seems to be fairly clean.
