### ISSUE TITLE
Large variation during holidays

### ISSUE THREAD

**Issue by pj0409** [facebook/prophet#785]
I am super new to R and using Prophet to forecast for month of Dec 2018 and January 2019. I have daily revenue data from Jan 2016 to Nov 2018. After comparing Dec forecast data with actual,  I noticed that my model  is not taking in holiday effects so well. I have yearly, weekly and monthly seasonality in my data and looks like weekly seasonality is hampering holiday effects.  My model prioritizes weekly seasonality over holiday effects

For example- Christmas eve and Christmas were on Monday and Tuesday and  it showed much higher revenue  on these two  days than I would expect and the difference between forecast and actual >100%

Varinace in trend and code below:

![forecast](https://user-images.githubusercontent.com/46168385/50502784-f1530000-0a2f-11e9-8a26-c4f5c51794fa.JPG)
 [](url)

#capture holidays
impholidays <- data.frame(
 holiday = 'impholidays',
   ds = c('2016-07-04','2016-11-24','2016-12-25','2017-07-04','2017-11-23','2017-12-25','2018-07-04','2018-11-22','2018-12-25','2019-07-04','2019-11-28','2019-12-25'),
lower_window=-1,
 upper_window=1,
prior_scale=100)

#capture holidays 
lw <-data.frame(
  holiday = 'lw',
  ds = c('2016-09-05','2017-05-29','2017-09-04','2018-05-28','2018-09-03','2019-05-27','2019-09-02'),
  lower_window=0,
  upper_window=1,
  prior_scale=100
)

#capture holidays
w <- data.frame(
  holiday='w',
  ds=c('2016-01-18','2016-02-15','2016-10-10','2016-11-11','2017-01-16','2017-02-20','2017-10-09','2017-11-11','2018-01-15','2018-02-19','2018-10-08','2018-11-12','2019-01-21','2019-02-18','2019-10-14','2019-11-11'),
  lower_window=-0,
  upper_window=0,
  prior_scale=10)

#capture monthly effect
firstday <-data.frame(
  holiday='firstmonth',
                    ds=c('2016-01-01','2016-02-01','2016-03-01','2016-04-01','2016-05-01','2016-06-01','2016-07-01','2016-08-01','2016-09-01','2016-10-01','2016-11-01','2016-12-01',
                      '2017-01-01','2017-02-01','2017-03-01','2017-04-01','2017-05-01','2017-06-01','2017-07-01','2017-08-01','2017-09-01','2017-10-01','2017-11-01','2017-12-01',
                      '2018-01-01','2018-02-01','2018-03-01','2018-04-01','2018-05-01','2018-06-01','2018-07-01','2018-08-01','2018-09-01','2018-10-01','2018-11-01','2018-12-01',
                      '2019-01-01','2019-02-01'),
                    lower_window=-2,
                    upper_window=1,
                    prior_scale=100)

#creating model
m <- prophet(holidays=holidays, seasonality.mode = 'multiplicative', changepoint_range=0.8, changepoint_prior_scale=.55,interval.width = 0.95)

#adding seasonality
m <- add_seasonality(m, name='weekly', period=7, fourier.order=5, prior.scale=10)
m <- add_seasonality(m, name='yearly', period=365, fourier.order=10, prior.scale=10)
m <- add_seasonality(m, name='daily', period=1,fourier.order=3, prior.scale=10)
m <- add_seasonality(m, name='monthly', period=30, fourier.order=1,prior.scale=1,mode='additive')
m <- fit.prophet(m, df)

future <- make_future_dataframe(m, periods = 90)
forecast <- predict(m,future)

Thanks for the help!

**Comment by bletham** [comment]
With the multiplicative seasonality as you have it, the model will be
`y(t) = trend(t) * (1 + weekly(t) + holiday(t))`.
So there isn't necessarily a priority given to weekly over holiday, but there isn't any consideration of the interaction between the two either.

Thanks for giving all of your code. The way holidays are handled here is to put them all (Jul 4, Thanksgiving, and Christmas) into a single holiday called "impholidays". What this means is that all of these holidays are given the same effect: Specifically, the effect on revenue of Jul 4 is assumed to be the same as Christmas. If these have a smaller effect on revenue than Christmas, then it may be the case that this is what is diluting some of your predicted effect for Christmas. I would definitely recommend separating those out into three separate holidays. As a side note, this also assumes that each day-before and day-after has the same effect, so Christmas Eve is given the same effect as the day before Thanksgiving, and Black Friday is given the same effect as Jul 5; probably not what we want.

I would hope that separating those out improves things a lot. There could still be, as you mentioned, some interaction between Christmas and day-of-the-week. That is, the multiplicative effect of Christmas is different when it is on a Sunday (2017) vs. a weekday (2017 and 2018). In this case, you would again want to put them into the model as separate holidays ("christmas-on-weekend" and "christmas-on-weekday"). You only have 1 of each in the data so you'll really be relying on them having repeatable effects though.

As a final note, the latest version of Prophet (v0.4) that just got pushed to CRAN has built-in country-level holidays as a new feature. You may find it useful, you can read about it here: https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#built-in-country-holidays . (But it does include a few more than what you have here, so you also might just want to stick to your list if those are really the only ones that have impact on your time series).

**Comment by pj0409** [comment]
Than you so much! I will try with that. Just to make sure that I understand this right. I will create separate indicators for Christmas, Thanksgiving and July 4th but I would still use this code
holidays <- bind_rows(impholidays,lw,w,firstday) to bind all the holiday indicators together, right?  


Thanks,
Purti

**Comment by bletham** [comment]
That's right, you'd combine them all into a single dataframe at the end but they'd have different names. So the final dataframe would look something like
```
df <- data.frame(
  holiday=c('July 4', 'July 4', 'Christmas', 'Christmas'),
  ds=as.Date(c('2016-07-04', '2017-07-04', '2016-12-25', '2017-12-25')),
  lower_window=-1,
  upper_window=1
)
```
