### ISSUE TITLE
Accuracy of Prophet

### ISSUE THREAD

**Issue by dhanashreearole** [facebook/prophet#786]
Hello All,

Does the accuracy of prophet reduce if the input dataset has values lower than 100? Does it work more efficiently for values that are in thousands?

Thanks,
Dhanashree

**Comment by abhisranj** [comment]
IMHO, values being in hundreds or thousands should not affect the accuracy as such.

**Comment by dhanashreearole** [comment]
@abhisranj Thanks, I saw that the sub-daily example on prophet webpage used lower numbers, so I was contemplating anyways.
Any idea on what one should look while examining the input dataset on being confident if the prophet prediction will be 90% accurate or above?
Wish you all happy new year!

**Comment by vhpietil** [comment]
Do some cross validation to see how accurate the predictions are :)
