### ISSUE TITLE
AttributeError: 'Prophet' object has no attribute 'add_country_holidays'

### ISSUE THREAD

**Issue by abhisranj** [facebook/prophet#787]
Trying to add in built country holidays as mentioned in the doc (https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#modeling-holidays-and-special-events)

Executing this code -->

```
optimal_model = Prophet(n_changepoints=25, changepoint_prior_scale=0.1, changepoint_range=0.7, seasonality_mode='multiplicative', weekly_seasonality=4)
optimal_model.add_country_holidays(country_name = 'IN')
forecast = optimal_model.fit(df)
```

results in attribute error -->
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-48-8aa3bc6f54a3> in <module>()
      2      seasonality_mode='multiplicative', weekly_seasonality=4
      3 )
----> 4 optimal_model.add_country_holidays(country_name = 'US')
      5 forecast = optimal_model.fit(df)

AttributeError: 'Prophet' object has no attribute 'add_country_holidays'
```

Used conda forge for Prophet installation.
I am using fbrophet0.3.post2 (since conda took forever to solve env for fbprophet0.4)
Python3.6
Anaconda3-5.2.0-Windows-x86_64

**Comment by abhisranj** [comment]
@rmax pls see

**Comment by uncleDC** [comment]
I used ''conda update fbprophet'',but the version is still 0.3,how to update fbprophet to 0.4 on anaconda?

**Comment by uncleDC** [comment]
> 
> 
> I used ''conda update fbprophet'',but the version is still 0.3,how to update fbprophet to 0.4 on anaconda?

python 3.6.5

**Comment by thunfischtoast** [comment]
> 
> 
> I used ''conda update fbprophet'',but the version is still 0.3,how to update fbprophet to 0.4 on anaconda?

The default channel does not contain fbprophet. The conda-forge version is managed via https://github.com/conda-forge/fbprophet-feedstock. Someone has to test and merge the newest version into that repository, then conda-forge will be able to distribute it.

**Comment by bletham** [comment]
We're about to push out a post release that will fix some build issues and then will work to get it into conda-forge.

**Comment by bletham** [comment]
The PR to get the new version into conda-forge is here: https://github.com/conda-forge/fbprophet-feedstock/pull/18
It requires some new packages to be added to conda-forge, for which PRs have also been made and are awaiting merge as described in the PR above.

**Comment by bletham** [comment]
This is in conda forge now.
