### ISSUE TITLE
Holidays Not Being Included in Prediction

### ISSUE THREAD

**Issue by connorphill** [facebook/prophet#789]
I am running into an issue with running predictions with the holidays included in the days being predicted. I have followed the documentation and see that my holidays are attached to the Prophet() object, but in the actual prediction I don't see the boolean columns related to the holidays marked with a "1" value. The forecasts as a result are much higher than expected and impacts my ability to use the results for forecasting.

Here is my setup:

```
import pandas as pd
import numpy as np

# Facebook Prophet
from fbprophet import Prophet

...

## set a dataframe for each holiday

# thanksgiving
thanksgiving = pd.DataFrame({
  'holiday': 'thanksgiving',
  'ds': pd.to_datetime(['2017-11-22', '2018-11-22', '2019-11-22']),
  'lower_window': 0,
  'upper_window': 1,
})

christmas = pd.DataFrame({
  'holiday': 'christmas',
  'ds': pd.to_datetime(['2017-12-25', '2018-12-25', '2019-12-25']),
  'lower_window': -1,
  'upper_window': 1,
})

holidays = pd.concat((thanksgiving, christmas))
print(holidays)

       holiday         ds  lower_window  upper_window
0  thanksgiving 2017-11-22             0             1
1  thanksgiving 2018-11-22             0             1
2  thanksgiving 2019-11-22             0             1
0     christmas 2017-12-25            -1             1
1     christmas 2018-12-25            -1             1
2     christmas 2019-12-25            -1             1

...

def forecast_data(data_set, y, forecast_period):
    # copy data_set with only the date (ds) and the depedent variable (y) being forecasted
    forecast_data_set = data_set[[sheet_date, y]].copy()
    forecast_data_set.columns = ['ds', 'y']
    
    print(type(forecast_data_set['ds']))
    
    # instantiate Prophet and call "fit" method on forecast_data_set
    m = Prophet(holidays=holidays, daily_seasonality=True, weekly_seasonality=True, yearly_seasonality=True)
    m.fit(forecast_data_set)
    
    print(vars(m))
    
    
    # set future periods to Prophet.fit()
    future = m.make_future_dataframe(periods=forecast_period)
    
    # forecast future periods
    forecast = m.predict(future)
    
    # plot forecast
    fig1 = m.plot(forecast)
    fig2 = m.plot_components(forecast)
    
    # return forecasted values
    return forecast


...
```

Here is a portion of the Prophet object that shows that the holidays are attached:

```
# print(vars(m)) yields
...
name: ds, dtype: datetime64[ns], 'n_changepoints': 25, 'specified_changepoints': False, 'changepoint_range': 0.8, 'yearly_seasonality': True, 'weekly_seasonality': True, 'daily_seasonality': True, 'holidays':         holiday         ds  lower_window  upper_window
0  thanksgiving 2017-11-22             0             1
1  thanksgiving 2018-11-22             0             1
2  thanksgiving 2019-11-22             0             1
0     christmas 2017-12-25            -1             1
1     christmas 2018-12-25            -1             1
2     christmas 2019-12-25            -1             1, 'seasonality_mode': 'additive', 'seasonality_prior_scale': 
...

```

However, when I run, ```m.predict(future)``` it outputs results that doe not include these holidays as a factor in the analysis:

```
ds	holidays	holidays_lower	holidays_upper	thanksgiving	thanksgiving_lower	thanksgiving_upper
2018-11-21 00:00:00	0	0	0	0	0	0
2018-11-22 00:00:00	0	0	0	0	0	0
2018-11-23 00:00:00	0	0	0	0	0	0
```

Should my output have a 1 marked for the rows that are identified as a holiday?

**Comment by connorphill** [comment]
It looks like the problem is unrelated to the library, but potentially how I am using the Prophet object. I have the object set and modified within a function that is being called multiple times. Due to this process it looks like the holidays aren't set for each time the function is called, but on the last call the holiday is included correctly. I am closing this issue as it seems like something related to my code and not the library itself.

**Comment by pg1912** [comment]
Hello @connorphill I am facing the same issue where the future holidays are not being included in the forecast results. I confirmed this using the plot compliments and it shows a straight line in holidays. Could you please elaborate how you resolved this issue ? Thanks

**Comment by tgjc** [comment]
> 
> 
> Hello @connorphill I am facing the same issue where the future holidays are not being included in the forecast results. I confirmed this using the plot compliments and it shows a straight line in holidays. Could you please elaborate how you resolved this issue ? Thanks

@pg1912 could be the version you are using. Upgrading to v0.7 worked for me! (see https://github.com/facebook/prophet/issues/1617 for details)
