### ISSUE TITLE
How to  use the prophet?In this codes,which one py do I run?And where is the result in?I run the python/plot.py,but don't see the result where is ?Thank you! 

### ISSUE THREAD

**Issue by qhwscream** [facebook/prophet#809]

**Comment by LakshmikanthanSrikanthan** [comment]
@qhwscream  You can have a look at the [Quick Start](https://facebook.github.io/prophet/docs/quick_start.html#python-api) Page.

**Comment by qhwscream** [comment]
The Quick Start only tells us the simple usage,but not the hole,I want to ask how to run the codes in the github,Do you understand me,Thank you!

**Comment by qhwscream** [comment]
> 
> 
> @qhwscream You can have a look at the [Quick Start](https://facebook.github.io/prophet/docs/quick_start.html#python-api) Page.
