### ISSUE TITLE
Conversion to PMML

### ISSUE THREAD

**Issue by hancelpv** [facebook/prophet#811]
Hello, 

I'm looking to train Prophet models in Python and use the trained PMML to produce predictions in Java.
Is there a way to write/save prophet models to PMML format, using some library ?

For instance, sklearn models can be converted to PMML using sklearn2pmml, I'm looking for something similar.
https://github.com/jpmml/sklearn2pmml

Thanks in Advance.

**Comment by bletham** [comment]
The main estimate `yhat` is a fairly straightforward regression which I imagine could be implemented in PMML. But the challenge is in getting the uncertainty intervals - in Prophet these are computed at predict time (not fit) using Monte Carlo sampling (to simulate future trend changes). I'm not familiar enough with PMML to know if it has that sort of capability.
