### ISSUE TITLE
Can't find function 'add_country_holidays'

### ISSUE THREAD

**Issue by xluo-ds** [facebook/prophet#812]
I am on 0.4 version of Prophet in RStudio, trying to add the country specific holiday, and get the error saying "Error in add_country_holidays(m, country_name = "de"): could not find function "add_country_holidays". The code I used are:

```
m2 <- prophet(predict_dat, 
             yearly.seasonality = TRUE, 
             weekly.seasonality = TRUE,
             daily.seasonality = FALSE 
)
add_country_holidays(m2, country_name = "de")
```

Anyone know how to fix this?

**Comment by LakshmikanthanSrikanthan** [comment]
I Suppose that there isn't a class for holidays in Germany. Please do cross check once and correct me if I am wrong.

**Comment by xluo-ds** [comment]
> I Suppose that there isn't a class for holidays in Germany. Please do cross check once and correct me if I am wrong.

I have tried "US", "United States", "us" (the one used in [tutorial](https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html), and it now gave me this error. I am not sure what's going on. 

> Error in add_country_holidays(m, country_name = "us") : 
>   Country holidays must be added prior to model fitting.

**Comment by xluo-ds** [comment]
Got it, thank you!
