### ISSUE TITLE
using prophet in a map function with seasonality and holiday

### ISSUE THREAD

**Issue by queenvi** [facebook/prophet#813]
Hi everyone. I would like to add seaonality and holidays for multiple items, i tried in the line below but it does not allow this number of attributes. Is the a way I can apply this?

m_list <- map(ts_list,prophet)

**Comment by IronistM** [comment]
You can create a nested data frame and apply prophet into the nested time series (`ds`, `y`). You can checkout my approach [here](https://github.com/IronistM/googleAnalyticsProphetR#get-predictions).

```R
## Apply the prophet prediction to each group
data %>%
  group_by_if(is.character) %>% # group by all dimensions present to `data`
  arrange(date) %>% # order by date explicitly!
  nest() %>%
  mutate(prophet_range = map_chr(data, ~ suppressWarnings(
    get_prophet_prediction(.x[["totalEvents"]], start_date = start,  daily.seasonality = TRUE)
  ))) 
```

**Comment by queenvi** [comment]
> You can create a nested data frame and apply prophet into the nested time series (`ds`, `y`). You can checkout my approach [here](https://github.com/IronistM/googleAnalyticsProphetR#get-predictions). Note that `get_prophet_prediction()` is a custom function that returns the prediction only.
> 
> ```r
> ## Apply the prophet prediction to each group
> data %>%
>   group_by_if(is.character) %>% # group by all dimensions present to `data`
>   arrange(date) %>% # order by date explicitly!
>   nest() %>%
>   mutate(prophet_range = map_chr(data, ~ suppressWarnings(
>     get_prophet_prediction(.x[["totalEvents"]], start_date = start,  daily.seasonality = TRUE)
>   ))) 
> ```

Thanks so much. Let me try it.

**Comment by queenvi** [comment]
Please can you expand more on the  get_prophet_prediction() function.

**Comment by IronistM** [comment]
You can find the function [here](https://github.com/IronistM/googleAnalyticsProphetR/blob/a2456b4073af6972d82dbc51c3452c4a59a12dce/Functions/functions.R#L83).

**Comment by queenvi** [comment]
Thanks!!!

**Comment by queenvi** [comment]
Hi @IronistM. The model seems to start executing then stops and give me the error. Please see the code and error. What could I be doing wrong:

_Results <-  df %>%
+ group_by_if(is_character) %>%
+ arrange(ds) %>%
+ nest() %>%
+ mutate(map_chr(df,~suppressWarnings(get_prophet_prediction(df$type[["y"]],ds = ds))))_


**ERROR:  Column `map_chr(...)` must be length 1 (the number of rows), not 3**

**Comment by IronistM** [comment]
Can you provide a reproducible example, say using [reprex](https://github.com/tidyverse/reprex). Are you sure that all dimensions that you want to group are grouped and not passed on the nested tibble?

**Comment by queenvi** [comment]
Hi @IronistM I have included the get_prediction function code as well. Its both the get prophet as I made some changes to it.

**Comment by queenvi** [comment]
``` r
get_prophet_prediction <- 
  function(series = NULL,ds = NULL,...)
  {
    holidays <- data_frame(holiday = 'newyear',ds = as.Date(c('2016-12-31','2017-12-31','2018-12-31')), lower_window = -7,upper_window = 0) 
    (history <- data_frame(ds = seq(from = as.Date("2016-01-31"),to = as.Date("2018-12-31"),by = "month"),y = sample(1:5000,36))) 
    (m <- prophet(history, holidays = holidays,seasonality.mode = 'multiplicative') ) 
    (future <- make_future_dataframe(m,periods = 12)) 
    (forecast <- predict(m,future) )
    (str_c(c(forecast$yhat_lower,forecast$yhat,forecast$yhat_upper),collapse = ",")) }


Results <-  df %>%
  group_by_if(is_character) %>%
  arrange(ds) %>%
  nest() %>%
  mutate(group_map(df,~suppressWarnings(get_prophet_prediction(df$type[["y"]],ds = ds))))
#> Error in df %>% group_by_if(is_character) %>% arrange(ds) %>% nest() %>% : could not find function "%>%"
```

<sup>Created on 2019-01-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by bletham** [comment]
That particular error is that the `dplyr` package needs to be loaded.
