### ISSUE TITLE
Question: Impact of changepoint prior scale on choosing models

### ISSUE THREAD

**Issue by lppier** [facebook/prophet#814]
I read this about the parameter changepoint_prior_scale. 
https://facebook.github.io/prophet/docs/trend_changepoints.html

This question may not exactly be a prophet question, but for data analytics in general. 
For two models, one with changepoint_prior_scale 0.005 (less flexible) and another with changepoint_prior_scale 0.12 (more flexible) which produce the cross-validated MAPE results 8.37% and 8.17% respectively, is it correct to consider choosing the 1st model because it is less prone to over-fitting? The improvement of MAPE of model 2 over model 1 is neligible here IMO. 

It is cross-validated, but I fear that future data points may suffer due to the more flexible model 2 (more prone to over-fitting). 

What are your thoughts?

**Comment by bletham** [comment]
I for one agree with the general idea that it is better to err on the side of more regularization than less. Underfitting can be an issue too, but in models with as many parameters as this I would also be more wary of overfitting. In this case you are also able to visualize the model fit and I would definitely recommend doing that in addition to the cross validation, as a safety check against really bad underfitting.

**Comment by lppier** [comment]
Thanks @bletham for confirming my suspicions regarding this.
