### ISSUE TITLE
Suggestions on tightening lower and upper forecast range

### ISSUE THREAD

**Issue by dhanashreearole** [facebook/prophet#816]
Hello All,

I am interested in ways to tighten the forecast range:

![image](https://user-images.githubusercontent.com/43793310/51410887-e4f42b80-1b33-11e9-96ce-47eeff61cd35.png)

As you can see the accuracy level is pretty good. Although the sway in the forecast is large. I am using change points value of 250 and scale of 0.05. Will picking appropriate transformation in Tukey Ladder of Powers be the solution? Or there are other ways / config params to control the sway?

Thanks,
Dhanashree

**Comment by bletham** [comment]
By tighten the range, do you mean tighten the interval between yhat_lower and yhat_upper?

If so, then there are two things you can do. The first is to use the parameter "interval_width" to reduce the width of the uncertainty interval, as described here: https://facebook.github.io/prophet/docs/uncertainty_intervals.html 
By default it is 80%, which means if there were no model misspecification you'd expect the actual values to lie within the region 80% of the time. You can reduce that, and it will give tighter intervals.

You can also reduce the number of past change points and/or the changepoint prior scale. This allows less flexibility in the past, and so the uncertainty intervals will reflect less flexibility in the future (i.e., will be narrower). (Assuming you don't significantly reduce the model fit error). 250 seems like a rather large number, and I'd expect it could be reduced without impacting predictive performance.

**Comment by dhanashreearole** [comment]
Yes, thanks for all the advice, that is exactly what I was looking for Ben. Have a nice day!
