### ISSUE TITLE
Day of Week Seasonality not Fully getting picked up

### ISSUE THREAD

**Issue by scottNewsela** [facebook/prophet#817]
We have a data set that's very sensitive to time of year but also the day of the week. Specifically for a few defined and known period of times, weekend data is 1/10th of weekday data. For the bulk of the year, weekend data is 1/25th-weekday data. Even when using multiplicative seasonal factors the model is constantly over predicting weekends values. We've resolved on our end by adjusting the weekend data to be 10 or 25 times larger depending on the season but there has to be a better way to account for this within the framework. 

In our case the seasonal factor is basically are kinds in school or not and it's not the weekends that get larger but rather the weekdays that get smaller

**Comment by bletham** [comment]
What is the frequency of your data? 1 data point per day or hourly or something else?

**Comment by scottNewsela** [comment]
1 data point per day

**Comment by scottNewsela** [comment]
We’ve tried adding in extra regressors for the weekend. Sundays, Saturday, Weekend as well as trying to just highlight the weekend that are less impacted. We’ve also tried highlighting just the weekdays that are less impacted and it helps some but its not applying a high enough impacts. Our fix was to modify the values (say multiply by 10 or 20) depending on which seasons trend we were in. Model this and then adjust back.

Applying a binary indicator for when we wanted 10 or 20 should have accomplished the same basic effect but for some reason it doesn't

**Comment by bletham** [comment]
That is very odd to me, it does seem like if you put a binary indicator on those same days in which you are multiplying the effect it should do the same thing. Just to be sure, did you set `mode='multiplicative'` with the extra regressor?
