### ISSUE TITLE
Question: how to disable the Sat. and Sun.s (remine working days only) in terms of the weekly Seasonality

### ISSUE THREAD

**Issue by plok1221** [facebook/prophet#818]
Question: how to disable the Sat. and Sun.s (remine working days only) in terms of the weekly Seasonality

**Comment by bletham** [comment]
There isn't a way to do this right now. If you fit data that has no Sat and Sun values, then you will end up with arbitrary values for the weekly seasonality on those days. The important thing is that when you make predictions, you should be sure to remove Sat and Sun from your prediction dataframe. Besides that, the fact that they were included in the model should have no effect. (You just have to also ignore them on the components plot). See this bit in the documentation about data with regular gaps (in this case the gap is the weekend): https://facebook.github.io/prophet/docs/non-daily_data.html#data-with-regular-gaps

**Comment by needsomehelp4** [comment]
> There isn't a way to do this right now. If you fit data that has no Sat and Sun values, then you will end up with arbitrary values for the weekly seasonality on those days. The important thing is that when you make predictions, you should be sure to remove Sat and Sun from your prediction dataframe. Besides that, the fact that they were included in the model should have no effect. (You just have to also ignore them on the components plot). See this bit in the documentation about data with regular gaps (in this case the gap is the weekend): https://facebook.github.io/prophet/docs/non-daily_data.html#data-with-regular-gaps

When I try to remove a set of dates from the 'future' dataframe and then forecast, it does not have any effect:
https://github.com/facebook/prophet/issues/844

Any thoughts on this or can you share a working model using this concept?

**Comment by domarcon** [comment]
any notes on how to do this on cross_validation method?

**Comment by bletham** [comment]
@domarcon cross_validation will make model predictions for dates where you have actual data, and then compare them to the actual values. If you only have data on weekdays, then it will only be making predictions for those dates and you shouldn't have any issues.
