### ISSUE TITLE
Non-Daily Data， Weekly data

### ISSUE THREAD

**Issue by NemoCpp** [facebook/prophet#819]
Dear developers,
I'd like to use prophet to do a cell-phone sales analysis, but the the daily sales of a cell-phone shop is very small (around 0-5, most of time is less than 3 per day) . 
It seems that I cannot do a daily time series analysis, so I want to do a weekly time series.
In the prophet  tutorials, there is an example about Monthly data (https://facebook.github.io/prophet/docs/non-daily_data.html), so my question is that "is there an example about weekly data" ?

Thank you!

**Comment by bletham** [comment]
Yes, the underlying model is in continuous time, so the data can take on any frequency (or even be irregularly spaced).

The same considerations for monthly data described in (https://facebook.github.io/prophet/docs/non-daily_data.html#monthly-data) will apply to weekly data: Just make sure that you make predictions on a dataframe with the same weekly frequency.

**Comment by uomodellamansarda** [comment]
Sorry for my reply, for me, it's not so clear. 
Like Nemo I want to forecast weekly data, I understood that the underlying model is continuous-time. 
But I didn't get how to forecast on weekly basis, and how to avoid strange output. 
What should I do? Forecasting the data, getting the daily one, and then aggregating by week? 
Moreover in the next example in "Non-daily_data/ Monthly Section" what does it mean
mcmc_samples=300 ?
Thank you Bletham! 
Prophet is amazing in my opinion

**Comment by bletham** [comment]
@uomodellamansarda if you have data that is weekly with a data point every Sunday, then just fit a Prophet model as usual, and when you generate the dates for making a prediction, just generate future dates only on Sundays and you'll have weekly predictions.

If you have daily data and want to predict a weekly aggregate, then use a you could either compute the weekly aggregate first and then make a weekly prediction as above, or you could fit daily data, make daily predictions, and aggregate your predictions.

**Comment by adasiitm** [comment]
Sorry, but can you please give an example on how to use weekly data?
future = m.make_future_dataframe(periods=120, freq='MS')
How do I modify this line above? Thanks!

**Comment by bletham** [comment]
@adasiitm see https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#timeseries-offset-aliases for a list of all of the time frequencies used by pandas (which can be used for freq). You probably want W.

**Comment by adasiitm** [comment]
Thanks @bletham ! My data has peak before holiday & there is a lead & lag effect, e.g., Hol-3, Hol-2, Hol-1, Hol-0,Hol+1,Hol+2 are weeks surrounding the holiday. Data could show peak at Hol-3 & starts gradually dropping, max dip at Hol_0, then rise slowly back to normal by Hol+2. Can Prophet handle these impacts of holidays, both peak & dip? Thanks!

**Comment by bletham** [comment]
I think #985 will have the answer to your question.

**Comment by adasiitm** [comment]
Thanks @bletham for the link! If I pass external regressor like ...0,0,0,1,2,3,4,5,4,3,2,1,0,0,0,0... to show the rising & falling effects, will it also work even if I don't pass dates in holiday list?

**Comment by bletham** [comment]
Under the hood holidays are just converted into binary regressors that are 1 on the date of the holiday and 0 otherwise. So if you specify the effects via an external regressor then it will be all covered and you don't need to worry about adding any holidays.
