### ISSUE TITLE
UnicodeDecodeError with pystan install susfully

### ISSUE THREAD

**Issue by Xialichong** [facebook/prophet#822]
Hi 

Thanks for helping me.
I install pystan successfully and run the code successfully.

However when I import fbprophet, I got below error

`import fbprophet
Traceback (most recent call last):

  File "<ipython-input-8-4f89f47c1bda>", line 1, in <module>
    import fbprophet

  File "C:\Anaconda3\lib\site-packages\fbprophet\__init__.py", line 8, in <module>
    from fbprophet.forecaster import Prophet

  File "C:\Anaconda3\lib\site-packages\fbprophet\forecaster.py", line 26, in <module>
    from fbprophet.models import prophet_stan_model

  File "C:\Anaconda3\lib\site-packages\fbprophet\models.py", line 27, in <module>
    prophet_stan_model = get_prophet_stan_model()

  File "C:\Anaconda3\lib\site-packages\fbprophet\models.py", line 24, in get_prophet_stan_model
    return pickle.load(f)

UnicodeDecodeError: 'ascii' codec can't decode byte 0x90 in position 2: ordinal not in range(128)`

I pip install fbprophet, becasue condo forge is not workable, keeping alert me to clean the packages...

**Comment by bletham** [comment]
I recently updated fbprophet in conda forge, is there still an issue there? Installing it via conda forge is the only way I've ever gotten it to work in python in windows.

I'm not exactly sure what is going on here. It is happening when trying to load the model that was compiled at install-time, which makes me wonder if it was installed in a different environment than it is now being loaded.

When you did pip install, was that in Anaconda? And are you importing it in the same environment?

**Comment by Xialichong** [comment]
Hi Bletham

Thanks for reply.
However, when I re-conda the prophet, there is still same error

Executing transaction: failed
ERROR conda.core.link:_execute(507): An error occurred while installing package 'conda-forge::automat-0.7.0-py_1'.
CondaError: Cannot link a source that does not exist. C:\Anaconda3\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.
Attempting to roll back.

**Comment by bletham** [comment]
@Xialichong that's not something that I'm familiar with, but it looks like it's happening while trying to install the `automat` package. Maybe run `conda clean --packages` like it suggests and then try to install `automat` directly?

**Comment by Xialichong** [comment]
Thanks Bletham so much, and happy new year.

Seems not workable.
I found there is access denied error.
It may because it is a corporate computer and IT has some higher access.

> C:\Anaconda3\Scripts\conda.exe.c~.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash - Access is denied.

**Comment by bletham** [comment]
Very strange, seems like something is messed up with the Conda install, I'd maybe ask over there.

**Comment by Kingflyinger** [comment]
> Hi Bletham
> Thanks for reply.
> However, when I re-conda the prophet, there is still same error
> Executing transaction: failed
> ERROR conda.core.link:_execute(507): An error occurred while installing package 'conda-forge::automat-0.7.0-py_1'.
> CondaError: Cannot link a source that does not exist. C:\Anaconda3\Scripts\conda.exe
> Running conda clean --packages may resolve your problem.
> Attempting to roll back.

hi bro，I met the same problem these days.And install automat frontly makes no sense.
it seems like something is wrong with new version cond

`Downloading and Extracting Packages
boto3-1.9.100        | 62 KB     | ############################################################################ | 100%
isort-4.3.4          | 76 KB     | ############################################################################ | 100%
xlsxwriter-1.1.4     | 104 KB    | ############################################################################ | 100%
dask-core-1.1.1      | 523 KB    | ############################################################################ | 100%
markupsafe-1.1.0     | 27 KB     | ############################################################################ | 100%
requests-oauthlib-1. | 17 KB     | ############################################################################ | 100%
jedi-0.13.2          | 229 KB    | ############################################################################ | 100%
python-3.6.6         | 21.4 MB   | ############################################################################ | 100%
pyodbc-4.0.25        | 65 KB     | ############################################################################ | 100%
distributed-1.25.3   | 858 KB    | ############################################################################ | 100%
dask-1.1.1           | 4 KB      | ############################################################################ | 100%
botocore-1.12.100    | 3.2 MB    | ############################################################################ | 100%
cloudpickle-0.7.0    | 17 KB     | ############################################################################ | 100%
astropy-3.1.1        | 6.9 MB    | ############################################################################ | 100%
xlwings-0.15.2       | 823 KB    | ############################################################################ | 100%
pluggy-0.8.1         | 17 KB     | ############################################################################ | 100%
jsonschema-3.0.0a3   | 98 KB     | ############################################################################ | 100%
pyzmq-18.0.0         | 452 KB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(543): An error occurred while installing package 'conda-forge::automat-0.7.0-py_1'.
CondaError: Cannot link a source that does not exist. D:\Anaconda3\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.
Attempting to roll back.

Rolling back transaction: done

CondaError: Cannot link a source that does not exist. D:\Anaconda3\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.`
