### ISSUE TITLE
Yearly seasonality values on monthly data

### ISSUE THREAD

**Issue by alexHeu** [facebook/prophet#823]
Hi,

I have a question regarding forecasts on monthly data. I have about 12 years of monthly data and trained the Prophet Model with yearly seasonality and otherwise default parameters on it.

From my understanding, the yearly saisonality has a fixed value for each month in the year (as the components plot would suggest). However, looking at the predictions my output dataframe looks as follows:
![image](https://user-images.githubusercontent.com/8157458/51602208-b0eb8280-1f06-11e9-9ab3-97f2279ca542.png)

The yearly values vary significantly between e.g. 2006-01-01 and 2007-01-01. Is this expected behaviour or did I do something wrong?

If i wanted to produce a custom component plot, do I have to aggregate the yearly values per month?

Thank

**Comment by bletham** [comment]
I think https://facebook.github.io/prophet/docs/non-daily_data.html#monthly-data might provide some help here.

The underlying model is continuous time. When you provide monthly data, in the model it is not "Jan 2006" rather it is specifically the day that you specify (Jan 1 2006).

The yearly seasonality is a continuous function with a period of 365.25 days. That extra .25 is why it isn't the same on Jan 1 every year. (But it should be the same after a full cycle that includes a leap year. Does that make sense? You could get it to line up perfectly by either changing the frequency of your data or the frequency of the yearly seasonality to match each other, but you'd need to be careful about leap years.

**Comment by alexHeu** [comment]
Thanks for your answer. This makes sense, yes.

So to make it line up I have to specify a custom seasonality with period 365 when I have monthly data or would a seasonality with period 12 also work?

**Comment by bletham** [comment]
The period is always in days, so a period of 12 would not be what you want.

If you set the period to 365, it will line up until you have a leap year, and then it will be off by 1 day.

**Comment by bletham** [comment]
An alternative would be to disable yearly seasonality and just learn a separate per-month effect using extra regressors.
Create a binary extra regressor named "is_jan" that has value 1 on your Jan data points and value 0 otherwise. Same thing for all of the other months. The model will then learn the effect for each month and you won't have to worry about leap years.

The difference in this relative to the built-in seasonality is that it will treat Jan and Feb entirely independently of eachother, where the yearly seasonality would have induced some smoothness between the two. But if you have a few years of data I'd expect it to work just as well.

**Comment by vavlopes** [comment]
@bletham, in the same direction but using less data points, if i have weekly data, is it correct to set yearly.seasonality = TRUE for cases in which i don't have a entire year of data ?
Is there a minimum period of months that prophet considers to interpolate seasonality ?

**Comment by bletham** [comment]
If you have less than a year of data, the yearly seasonality will be totally unconstrained for whatever months are not observed. One downside of the way seasonality is modeled is that it won't have a value of 0 if there is no data for that month - it can take on very extreme values. You can see some of this in the components plot in this section : https://facebook.github.io/prophet/docs/non-daily_data.html#monthly-data . You can see that there is large uncertainty in yearly seasonality in the middle of the month (where there is no data). Now just imagine if you had several months in a row with no data what the range of values could be! I would not recommend using yearly seasonality unless you have a full year, or else you will not get good predictions for months that you do not have in your history.
