### ISSUE TITLE
running in google cloud function

### ISSUE THREAD

**Issue by mikeyoungbhep** [facebook/prophet#825]
First off, thanks for the library - very useful. 

I am running into an issue trying to use this in a google cloud function (haven't tried similar with AWS yet though). When the function is deploying the build fails with 
`{"error": {"canonicalCode": "INVALID_ARGUMENT", "errorMessage": "pip_download_wheels had stderr output:\n  Failed building wheel for fbprophet\nERROR: Failed to build one or more wheels\n\nerror: `pip_download_wheels` returned code: 1", "errorType": "InternalError", "errorId": "433B238B"}}`

I'm pretty certain this is a gcp execution environment issue, but just curious if anyone had successfully used this in a serverless function successfully 

## Update

I tried testing with pystan like mentioned [here](https://github.com/facebook/prophet/issues/800l) and I get the following:
`Error: function crashed. Details:
command 'x86_64-linux-gnu-gcc' failed with exit status 1`

So it does look like it's due to the runtime I think... gcp functions run in Ubuntu 18.04

**Comment by IronistM** [comment]
I don't know if this will be helpful to you : [fb-prophet transformation for aws lambda](https://gist.github.com/CarstVaartjes/77dbe8249d171e592bd17847f7009272).

**Comment by mikeyoungbhep** [comment]
@IronistM thanks a lot for this. I'll see if I can replicate something similar in GCP

**Comment by hugopalmer** [comment]
Hello @mikeyoungbhep  ! 
I am getting through this error. Did you succeed in making this work with GCP?

**Comment by mikeyoungbhep** [comment]
No dice. The google folks advised it would be better to use the new cloud run (containers) instead of a cloud function. Haven’t really worked at it since that advice though.


Michael Young

Birch Hill Equity Partners

D: 416.775.3803 | M: 647.629.8174 | E: mailto:myoung@birchhillequity.com

On Mar 13, 2019, at 5:45 AM, Hugo Palmer <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @mikeyoungbhep<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmikeyoungbhep&data=01%7C01%7Cmyoung%40birchhillequity.com%7C10d43ba5c13f41dbef6308d6a798948e%7Cac67a2a70165451eb6cbe600d751d7ff%7C0&sdata=s9%2FL2ckkyQCohKbRXoukrqoysnIBHuoK0ouqphT9naQ%3D&reserved=0> !
I am getting through this error. Did you succeed in making this work with GCP?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffacebook%2Fprophet%2Fissues%2F825%23issuecomment-472350316&data=01%7C01%7Cmyoung%40birchhillequity.com%7C10d43ba5c13f41dbef6308d6a798948e%7Cac67a2a70165451eb6cbe600d751d7ff%7C0&sdata=tWg1KOb5VrZ7wxkl8bE28AUIOMr2AmmnZI%2F6474Hj8c%3D&reserved=0>, or mute the thread<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAe_NsrolYhepynuztdR8aBVM-mFLoCF9ks5vWMijgaJpZM4aPpj_&data=01%7C01%7Cmyoung%40birchhillequity.com%7C10d43ba5c13f41dbef6308d6a798948e%7Cac67a2a70165451eb6cbe600d751d7ff%7C0&sdata=8nm%2FvAfWxBmreHWA87QberrvKCsJcG6P6kmRCCxNjDw%3D&reserved=0>.

********************************
NOTICE OF CONFIDENTIALITY
This communication including any information transmitted with it is intended only for the use of the addressees and is confidential. If you are not an intended recipient or responsible for delivering the message to an intended recipient, any review, disclosure, conversion to hard copy, dissemination, reproduction or other use of any part of this communication is strictly prohibited, as is the taking or omitting of any action in reliance upon this communication. If you receive this communication in error or without authorization please notify us immediately by return e-mail or otherwise and permanently delete the entire communication from any computer, disk drive, or other storage medium.

AVIS DE CONFIDENTIALITÉ
Ce message, ainsi que tout renseignement inclus, est à l'intention exclusive des destinataires mentionnés, et est confidentiel. Si vous n'êtes pas le destinataire désigné ou un agent responsable de la livraison de ce message à son (ou ses) destinataire(s), tout examen, divulgation, copie, impression, reproduction, distribution, ou autre utilisation de toute partie de ce message est strictement interdit, de même que toute intervention ou omission à cet égard. Si vous avez reçu ce message par erreur ou sans autorisation, veuillez nous en aviser immédiatement par retour de courriel ou par un autre moyen et supprimer définitivement et entièrement ce message de tout ordinateur ou système de sauvegarde.
