### ISSUE TITLE
Issues when forecasting with Multiplicative seasonality 

### ISSUE THREAD

**Issue by SaswatMahapatra** [facebook/prophet#826]
Hi @bletham ,
This is my code. I expect the forecasts to go on increasing but when trained with 2 years data and predicting next 3 months , the value keeps on decreasing , and i want the trend to be multiplicative.

How to achieve it ?

m <- prophet(data,yearly.seasonality = TRUE,seasonality.mode = 'multiplicative',growth = 'linear')
changepoint prior scale value is [0.75]

**Comment by SaswatMahapatra** [comment]
![components plot](https://user-images.githubusercontent.com/44432711/51670535-dbb00680-1fec-11e9-8e90-ce27564d9389.png)
![decreasing trend](https://user-images.githubusercontent.com/44432711/51670537-dbb00680-1fec-11e9-9a11-1f1af7c009c4.png)

**Comment by SaswatMahapatra** [comment]
Can you help me out on this ??

**Comment by SaswatMahapatra** [comment]
@bletham ,
One more issue , the model predicted value , if you see in the graph is negative , its dropping to -623 for December end ,.
Is there something can be done for the predicted negative values in model fit ?

**Comment by bletham** [comment]
For the trend: From what I can see it looks like the trend has been decreasing in the history, and I don't see much of an upturn at the end (certainly not enough for the model to forecast an increasing trend). Now, you may know that in reality something has changed and there should be an increasing trend. There isn't a way to have much control over the actual values of the trend though. I think the best you could do to put in this external knowledge would be to take what you know the future trend should be and add it to yhat.

It is a similar situation for the negative values. You can force the trend to saturate at 0 (https://facebook.github.io/prophet/docs/saturating_forecasts.html#saturating-minimum), but then seasonal fluctuations will still be able to push the overall value negative as is happening here. We are working on implementing a Poisson link function which will keep the values always positive, but in the meantime the best that can be done is to take the yhat predictions and set any negative values to 0.
