### ISSUE TITLE
ERROR:fbprophet.plot:Importing matplotlib failed. Plotting will not work

### ISSUE THREAD

**Issue by shanks0739** [facebook/prophet#832]
import fbprophet faild in env(python2.7.5, centos7). 
import fbprophet  
ERROR:fbprophet.plot:Importing matplotlib failed. Plotting will not work

solution:  
check Tkinter
yum install python-tools

**Comment by bletham** [comment]
This indicates that there was an ImportError on one of the following:
```
from matplotlib import pyplot as plt
from matplotlib.dates import MonthLocator, num2date
from matplotlib.ticker import FuncFormatter
```
(https://github.com/facebook/prophet/blob/master/python/fbprophet/plot.py#L21)

I would guess that matplotlib is not installed.

**Comment by pkulics** [comment]
Even the matplotli is installed, the problem is still there.

**Comment by bletham** [comment]
Can you try each of these commands and see if one of them raises an ImportError?
```
from matplotlib import pyplot as plt
from matplotlib.dates import MonthLocator, num2date
from matplotlib.ticker import FuncFormatter
```

**Comment by liu044100** [comment]
I had the same error, and fixed it by refer [this question](https://stackoverflow.com/questions/21784641/installation-issue-with-matplotlib-python)

**Comment by M-Younus** [comment]
simple run this command `pip install --upgrade plotly`.
From [SOF](https://stackoverflow.com/a/31387885/5398403)

**Comment by ChatsHD** [comment]
upgrading plotly worked for this problem !

**Comment by akira1005** [comment]
I was able to do pip install --upgrade plotly and it said requiremnt already met. But, I still see the error ERROR - Importing matplotlib failed. Plotting will not work. Aany thoughts/ideas ? Mine is a linux machine and already have C++ compiler equivalent.

**Comment by bletham** [comment]
@akira1005 what this means is actually just that matplotlib plotting won't work; plotly plotting should still work fine. We need to clarify the message there.

**Comment by shivang-ts** [comment]
> simple run this command `pip install --upgrade plotly`.
> From [SOF](https://stackoverflow.com/a/31387885/5398403)

Thanks a lot. Worked for me

**Comment by Arunakiri** [comment]
> simple run this command `pip install --upgrade plotly`.
> From [SOF](https://stackoverflow.com/a/31387885/5398403)

Worked for me too

**Comment by reissaavedra** [comment]
> simple run this command `pip install --upgrade plotly`.
> From [SOF](https://stackoverflow.com/a/31387885/5398403)

Worked for me too. Thanks

**Comment by davetpj** [comment]
> simple run this command `pip install --upgrade plotly`.
> From [SOF](https://stackoverflow.com/a/31387885/5398403)

Worked for me too. Thanks a lot!

**Comment by Masiptech** [comment]
> simple run this command `pip install --upgrade plotly`.
> From [SOF](https://stackoverflow.com/a/31387885/5398403)

Worked for me too. Thanks a lot

**Comment by Werikcyano** [comment]
> simple run this command `pip install --upgrade plotly`. From [SOF](https://stackoverflow.com/a/31387885/5398403)

Worked for me too. Thaaanks!
