### ISSUE TITLE
Discontinuity in Prophet Forecasts

### ISSUE THREAD

**Issue by ruksarsultana** [facebook/prophet#853]
I'm facing issues in continuity of historical data & prophet forecasts while plotting using ggplot2 (Please find attached snapshot of the plot). I'm forecasting quarterly data using prophet using two regressors (Historical data available from 2003 Q1 to 2018 Q1, Forecast period - 2018 Q2 to 2027 Q4). After forecasting quarterly data, I'm aggregating (by taking average) quarterly forecasts to yearly numbers and visualizing actuals vs forecasts where I'm seeing discontinuity between actuals & forecasts in borderline year (2018). Could you please provide suggestions to tackle this issue.
![prophet_forecast_discontinuity_issue](https://user-images.githubusercontent.com/42566423/53081413-d3ca8000-3520-11e9-9cd0-e53861ad138c.PNG)

**Comment by bletham** [comment]
It's hard for me to know why the forecast is too high at the end of 2918 based on this plot. Maybe could you provide the non-aggregated forecast (directly the result of `m.plot(fcst)`) as well as the component plot (`m.plot_components(fcst)`)? That might give some insight into what features the model is fitting, and what features are present in the actual data that the model is missing.
