### ISSUE TITLE
what is the best minimum number of observations for facebook prophet forecasting?

### ISSUE THREAD

**Issue by ChaymaeHarfoush** [facebook/prophet#855]
What is the best minimum number of observations for fprophet forecasting.
I know that it's necessary to have more observations than parameters but I couldn't know the number of all parameters included in fprophet package.

**Comment by bletham** [comment]
The answer depends on what types of features you need to capture in the model, and how far you want to forecast.

If your time series has yearly seasonality, you will need 2 years of data to be able to reliably capture that. Similarly, weekly seasonality will require at least 2 weeks of data.

A few months of data is probably reasonable for forecasting out a week, but not for forecasting out a year. What's reasonable in terms of forecast horizon will depend on how stable the dynamics of the time series are, but I'd be hesitant to forecast out more than about a third of the history length.

As far as the number of parameters: There is a parameter for every changepoint (`n_changepoints` of them, default 25), and an initial slope and offset (2 parameters). There are by default 6 parameters used for weekly seasonality and 20 used for yearly. That said, there is a lot of regularization on the parameters so I think it can be OK to have fewer data points than model parameters in this case.
