### ISSUE TITLE
Changing yhat (Forecasts)

### ISSUE THREAD

**Issue by ruksarsultana** [facebook/prophet#858]
I see that the values of yhat for the same change_point_parameter (For instance 0.05) change from one run to the other? Could you please help me understand what could be the reason for this. 

I understand that uncertainty interval (values of yhat_lower and yhat_upper) can change from one run to the other due to deterministic fitting & Monte Carlo sampling, however not sure why the values of yhat could also change as it would then be difficult to recreate the numbers.

Please note - I'm running prophet model twice for the same changepoint parameter (0.05) in one run. Please note the comparison in attached excel. Please note yhat & yhat_0.05 correspond to forecasts for the same change_point_parameter (0.05) & changepoint.range set to 1 in both the cases with seasonality excluded.

[Prophet_Forecast_Issue.xlsx](https://github.com/facebook/prophet/files/2888464/Prophet_Forecast_Issue.xlsx)
 

Thanks in advance,

**Comment by bletham** [comment]
Just to be clear, you are running the exact same code twice and that is producing the differences in the spreadsheet? I tried to reproduce this by running this code:
```
import pandas as pd
from fbprophet import Prophet

ds = pd.date_range(start='2003-01-01', freq='AS', periods=15)
y = [
    86.5221075317564,
    98.3952878868141,
    110.342622578159,
    129.627365793375,
    154.636471572466,
    180.178320887186,
    208.254757402791,
    238.120783197448,
    268.481614797235,
    287.510237101886,
    309.991354514461,
    348.020337899458,
    377.261368006243,
    404.673011675899,
    437.520290180677,
]
df = pd.DataFrame({'ds': ds, 'y': y})

m = Prophet(
    changepoint_prior_scale=0.05,
    changepoint_range=1.0,
    yearly_seasonality=False,
    weekly_seasonality=False,
    daily_seasonality=False,
)
m.fit(df)
future = m.make_future_dataframe(freq='AS', periods=10)
fcst = m.predict(future)
print(fcst['yhat'])
```
I get really stable results in the forecast when I run this repeated times. Could you post code that produces the issue for you so I can try to figure out what is happening?
