### ISSUE TITLE
how to use prophet to handle drastic changes

### ISSUE THREAD

**Issue by xxddsummer** [facebook/prophet#867]
Dear prophet team and everyone, I want to forecast the service invocation times using prophet. The history datum is showed as below. The day of 19th February is the Chinese Lantern Festival. There are drastic changes between 12:00 of 02-18-2019 and 00:00 of 02-21-2019.
I am wondering how to use prophet to handle such a case, or any other techniques can be adopted in the process of anomaly detection of such kind. Thanks for suggestions.

![tracetotalcount2019022501_line](https://user-images.githubusercontent.com/39851759/53392884-bb9da980-39d5-11e9-81fa-82d8f50cc27c.png)

**Comment by jbanik85** [comment]
xxddsummer,

do you want to predict these abrupt changes during the Chinese new year? If that's the case, you should be able to train your model using the holidays parameters. I haven't exactly played around with that option yet, but I did read about it in the documentation. Prophet has rigorous support for accommodating impacts of Holidays.
