### ISSUE TITLE
Recovering s parameter

### ISSUE THREAD

**Issue by DataGems** [facebook/prophet#868]
In your paper, s(t) seems to measure the overall seasonality of the data set. Is this the correct interpretation? If so, is there a way to recover it from prophet's output?

Thanks very much for contributing your package to the community.

**Comment by bletham** [comment]
If you make a forecast with `predict`, the resulting dataframe will have a column with the forecasted value (`yhat`), as well as columns for all of the components. There will be one for each seasonality separately, as well as the columns `additive_terms` and `multiplicative_terms` for the combined total (depending on whether it is additive or multiplicative seasonality). Do note however that that value also includes holiday effects and extra regressors.
