### ISSUE TITLE
Prophet Equation

### ISSUE THREAD

**Issue by ruksarsultana** [facebook/prophet#869]
How can we extract the underlying equation while fitting a prophet model in R. I need this for later extending forecasts forward (during future refresh) by re-using the model equation (instead of having to re-run the model again).

**Comment by bletham** [comment]
You just need to keep around the model object. You make a forecast with
```
forecast <- predict(m, future)
```
where `future` holds the future dates. If you want to change the dates to `future2`, then you can just do
```
forecast <- predict(m, future2)
```
with the same `m` and do not need to re-fit the model.

Is that what you mean?

**Comment by ruksarsultana** [comment]
What I mean is If I want to use the same model coefficients after 3 months (for instance) for forecasting additional future dates for periodic refresh. Is there a way to extract the model equation/ coefficients to do the same instead of fitting the model again. Or would you suggest to store the model object (m) for future refresh

**Comment by bletham** [comment]
I see now. In our usage, we usually forecast on a long range of dates and store the forecast to the database and don't keep around the model. When we do want to refresh the forecasts, we usually have new data by then anyway and so it makes sense to re-fit the model.

If you wanted to be able to forecast on a set of dates, and then later on forecast on a different set of dates without having to re-fit the model, then I think just storing the entire model object would be easiest. It does pickle cleanly in Python, and in R objects are easy to save/reload. We haven't really added an interface for re-instantiating a model from data that has been serialized in some way.

**Comment by ruksarsultana** [comment]
@bletham Thanks for the comment. Is this option to save prophet coefficients and equation part of future releases?

**Comment by bletham** [comment]
No, there is currently no plan to store models other than via pickle.

**Comment by KushalRunthala** [comment]
Hi @bletham. 
I want to extract the equation for my prophet model and use it to forecast for future values. I need this equation to simulate for multiple regressor values. Is there a way we can do this

**Comment by Afibagh** [comment]
I'm using the facebook prophet model to forecast postnatal attendance, but I'm struggling to extract the mathematical equation from the model
