### ISSUE TITLE
Prophet hangs on fitting with add_country_holidays

### ISSUE THREAD

**Issue by zijie0** [facebook/prophet#870]
```
import fbprophet
fbprophet.__version__
```

output: `'0.4'`

Reproduce steps:

```
from fbprophet import Prophet
import pandas as pd

df = pd.DataFrame({'ds': ['2017-05-01', '2017-12-01', '2018-03-01', '2018-11-01'], 
                   'y': [4.356, 3.96, 0.0, 0.0]})

m = Prophet()
m.add_country_holidays('CN')  # if we comment out this line, everything works fine

m.fit(df)  # hanging forever...
```

I checked other issues and tried to upgrade pystan to the latest version: pystan-2.18.1.0, the problem remains.

Could anyone please take a look? Thanks.

**Comment by bletham** [comment]
Thanks for the really clean repro.

With very small datasets, the Prophet model is underspecified and this can cause Stan's built-in L-BFGS optimizer to run into issues when optimizing the likelihood function. Adding in the country holidays increases the number of parameters which exacerbates the poor specification.

A few instances of this have popped up in v0.4, another example is in #842. In all of these cases, switching from Stan's L-BFGS optimizer to Stan's Newton optimizer fixes the issue:
```
m.fit(df, algorithm='Newton')
```
The Newton algorithm is slower than L-BFGS on large datasets (hence it is the default), but seems to be much more robust for these very flat likelihood surfaces. In the next version we'll make a change to use Newton by default on small datasets.

**Comment by zijie0** [comment]
Hi bletham,

Thank you for your detailed explanation. Problem solved!

**Comment by bletham** [comment]
I'm going to go ahead and leave this open until it is fixed.

**Comment by eromoe** [comment]
May be relate to https://github.com/facebook/prophet/issues/888
@bletham Could you give a number of smallest size ?

**Comment by bletham** [comment]
I'm not exactly sure; my current plan is to put a switch at 50, if you find a dataset with more than 50 points that hangs please do let me know.

(I think at 50 the difference in time between L-BFGS and Newton still shouldn't be too bad).

**Comment by eromoe** [comment]
Thank you , I would have a try .

**Comment by bletham** [comment]
Pushed to PyPI
