### ISSUE TITLE
I can not find this mistake or I'm not understanding

### ISSUE THREAD

**Issue by larka06** [facebook/prophet#872]
Command "/home/larry/.virtualenvs/djangodev/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-y0zfxl7s/pywatchman/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ex1a4ldf/install-record.txt --single-version-externally-managed --compile --install-headers /home/larry/.virtualenvs/djangodev/include/site/python3.7/pywatchman" failed with error code 1 in /tmp/pip-install-y0zfxl7s/pywatchman/

**Comment by larka06** [comment]
I have searched the web with google and I either do not understand or I can not find the answer. I do not know which is the case.

**Comment by bletham** [comment]
This error is for a different package, you might want to ask over here: https://github.com/facebook/watchman/tree/master/python/pywatchman
