### ISSUE TITLE
kernel dies when plotting (libpng error)

### ISSUE THREAD

**Issue by qingbinlee** [facebook/prophet#874]
I'm using Prophet v0.4. When I run 

> m.plot()

 function in jupyter notebooks, the kernel keeps showing kernel dead. The error message is

> libpng error: Wrote palette index exceeding num_palette
> double free or corruption (!prev)

However, when I run the same code in terminal, it works well.

**Comment by jbanik85** [comment]
There's been a discussion going on this topic #857 ; did you take a look into this?

**Comment by qingbinlee** [comment]
@jbanik85 I have looked at topic #857. However, the problem I encounter is different than that one. The code (i.e. the code in quick_start.ipynb) works in ternimal but it causes kernel dead in jupyter notebook

**Comment by bletham** [comment]
Yeah this sounds like a different issue. There are a few open issues related to kernel dying but they're all happening during fit and are related to the Stan optimization. This is the first I've heard of an issue in plot.

Is there a particular dataset that is producing this, or does it happen if you try to run one of the example notebooks like this one: https://github.com/facebook/prophet/blob/master/notebooks/quick_start.ipynb

What version of matplotlib do you have?
```
import matplotlib
matplotlib.__version__
```

**Comment by qingbinlee** [comment]
Hi @bletham 
I have tried to run [https://github.com/facebook/prophet/blob/master/notebooks/quick_start.ipynb]. All the notebooks encounter this issues. 

I'm using ubuntu and I create a conda virtual enviroment for running experiments. The matplotlib is 3.0.3

**Comment by bletham** [comment]
Perhaps try breaking it out into the individual steps and see which step is producing the error. This is the entirety of what is done to produce the plot:

```
from matplotlib import pyplot as plt
from matplotlib.dates import MonthLocator, num2date
from matplotlib.ticker import FuncFormatter

fcst = m.predict()

fig = plt.figure(facecolor='w', figsize=figsize)
ax = fig.add_subplot(111)
fcst_t = fcst['ds'].dt.to_pydatetime()
ax.plot(m.history['ds'].dt.to_pydatetime(), m.history['y'], 'k.')
ax.plot(fcst_t, fcst['yhat'], ls='-', c='#0072B2')
ax.fill_between(fcst_t, fcst['yhat_lower'], fcst['yhat_upper'],
                color='#0072B2', alpha=0.2)
ax.grid(True, which='major', c='gray', ls='-', lw=1, alpha=0.2)
ax.set_xlabel('ds')
ax.set_ylabel('y')
fig.tight_layout()
```
