### ISSUE TITLE
Compute Forecast Intervals for Aggregates

### ISSUE THREAD

**Issue by henningsway** [facebook/prophet#875]
I would like to derive CIs for the aggregated prediction of my holdout set (let's say two weeks).

I think, I have to simulate various predictions, add them up individually and look at the distributions of the aggregates, see https://robjhyndman.com/hyndsight/forecast-intervals-for-aggregates/

Is there a recommended way of doing this with prophet? (Looking for an equivalent to `forecast::simulate()` I guess)

**Comment by bletham** [comment]
What you'll want to do here is use the `predictive_samples` function (https://github.com/facebook/prophet/blob/master/R/R/prophet.R#L1466).
You give it a dataframe of the same format that you would give `predict` (column of dates, and any extra regressors), and it will return a list with posterior samples for the trend and for yhat at those dates. The number of samples will be the `uncertainty.samples` that you specify when instantiating the model with `prophet`. You could then aggregate those samples across days and compute the aggregated CI as desired.

Does that sound like what you're looking for?

**Comment by henningsway** [comment]
absolutely  :100:, thank you!
