### ISSUE TITLE
Fall back to Newton optimizer even if algorithm is specified as kwarg

### ISSUE THREAD

**Issue by bletham** [facebook/prophet#877]
Discussion is in #700.
* If optimization fails with default L-BFGS, then it is repeated with Newton.
* If algorithm is explicitly specified as a kwarg, then this isn't done and the optimization failure is raised.

This should be changed to fallback to Newton even if algorithm is specified.

**Comment by whitehatty** [comment]
Open PR:
https://github.com/facebook/prophet/pull/890

**Comment by bletham** [comment]
Pushed
