### ISSUE TITLE
Variance prediction

### ISSUE THREAD

**Issue by bibinmjose** [facebook/prophet#878]
https://github.com/facebook/prophet/blob/730e59e2f73e9466f31a0797535c0888241672c8/python/fbprophet/forecaster.py#L1116

Anybody working on predicting variance along with confidence intervals ?

**Comment by bletham** [comment]
What exactly do you mean? `predict` does return uncertainty intervals as described in https://facebook.github.io/prophet/docs/uncertainty_intervals.html

**Comment by bibinmjose** [comment]
@bletham yes it gives uncertainty. I was asking if it can give variance as well. I fixed by returning variance as a parameter when calling self.uncetainity.

https://github.com/facebook/prophet/issues/878#issuecomment-471130283

**Comment by bletham** [comment]
I don't fully understand. What variance are you trying to get? The variance of the noise term in the model?
