### ISSUE TITLE
Getting started with R

### ISSUE THREAD

**Issue by kchurchwell** [facebook/prophet#879]
I've tried several examples - quick start, etc. And I always get the same error.

SAMPLE CODE
library(prophet)
context("Prophet tests")

DATA <- read.csv('C:\\Users\\k05048\\Documents\\R\\data.csv')
N <- nrow(DATA)

train <- DATA[1:floor(N/2),]
future <- DATA[(ceiling(N/2)+1):N,]

DATA$ds <- prophet:::set_date(DATA$ds)
DATA

m <- prophet(DATA)

ERROR:
Disabling daily seasonality. Run prophet with daily.seasonality=TRUE to override this.
Error in mutate_impl(.data, dots) : 
  Evaluation error: This function should not be called directly

I try last_trace()
rlang::last_trace()
     x
  1. +-prophet::prophet(DATA)
  2. | \-prophet::fit.prophet(m, df, ...)
  3. |   \-prophet:::make_all_seasonality_features(m, history)
  4. |     \-prophet:::regressor_column_matrix(m, seasonal.features, modes)
  5. |       \-`%>%`(...)
  6. |         +-base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
  7. |         \-base::eval(quote(`_fseq`(`_lhs`)), env, env)
  8. |           \-base::eval(quote(`_fseq`(`_lhs`)), env, env)
  9. |             \-prophet:::`_fseq`(`_lhs`)
 10. |               \-magrittr::freduce(value, `_function_list`)
 11. |                 \-function_list[[i]](value)
 12. |                   +-dplyr::mutate(., col = seq_len(dplyr::n()))
 13. |                   \-dplyr:::mutate.tbl_df(., col = seq_len(dplyr::n()))
 14. |                     \-dplyr:::mutate_impl(.data, dots)
 15. +-base::tryCatch(...)
 16. | \-base:::tryCatchList(expr, classes, parentenv, handlers)
 17. |   +-base:::tryCatchOne(...)
 18. |   | \-base:::doTryCatch(return(expr), name, parentenv, handler)
 19. |   \-base:::tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
 20. |     \-base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
 21. |       \-base:::doTryCatch(return(expr), name, parentenv, handler)
 22. \-base::evalq(seq_len(dplyr::n()), <environment>)
 23.   \-base::evalq(seq_len(dplyr::n()), <environment>)
 24.     \-dplyr::n()

And, then, last_error()

> rlang::last_error()
<error>
message: This function should not be called directly
class:   `rlang_error`
backtrace:
  1. prophet::prophet(DATA)
 22. [ base::evalq(...) ] with 1 more call
 24. dplyr::n()

**Comment by kchurchwell** [comment]
[data.zip](https://github.com/facebook/prophet/files/2946917/data.zip)

**Comment by bletham** [comment]
Thanks for providing the data and the clear code to reproduce.

Actually when I run this code I don't get any error. I suspect it may be due to a difference in the version of either `rlang` (which is raising the error) or `dplyr`. Could you check their versions with
```
library(prophet)
sessionInfo()
```

**Comment by kchurchwell** [comment]
Here's the output below.  Thank you so much for your help!


> library(prophet)
Error: package ‘Rcpp’ required by ‘prophet’ could not be found
In addition: Warning message:
package ‘prophet’ was built under R version 3.4.4 
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.3 tools_3.4.3

**Comment by kchurchwell** [comment]
Next, I went back and installed Rcpp ( I thought this was already there,.. so, i tried to install it again)

install.packages("Rcpp")
Installing package into ‘C:/Users/k05048/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/Rcpp_1.0.0.zip'
Content type 'application/zip' length 4347026 bytes (4.1 MB)
downloaded 4.1 MB

package ‘Rcpp’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\k05048\AppData\Local\Temp\RtmpkjCnkb\downloaded_packages
> library(prophet)
Loading required package: Rcpp
Loading required package: rlang
Error: package or namespace load failed for ‘prophet’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘dplyr’
In addition: Warning messages:
1: package ‘prophet’ was built under R version 3.4.4 
2: package ‘Rcpp’ was built under R version 3.4.4 
3: package ‘rlang’ was built under R version 3.4.4

**Comment by kchurchwell** [comment]
Hi - Thanks for the help - I upgraded R and it appears to be working now.  Thanks again!

**Comment by bletham** [comment]
hm yeah that's strange that it installed Prophet but not the dependencies (Rcpp, dplyr). Glad that an upgrade fixed it, I'm really not sure what happened here.
