### ISSUE TITLE
pip install unirest error

### ISSUE THREAD

**Issue by tjyven** [facebook/prophet#881]
Seen many members having problems with pip install but still havent seen a solution that works for me. Using the command "pip install unirest" and get the error:
Command "python setup.py egg_info" failed with error code 1 in C:\Users\andre\AppData\Local\Temp\pip-install-3u8_s9of\poster\

Have upgraded the setuptools which I see many recommends.

**Comment by bletham** [comment]
This repo is for a different package, I think you'll have more luck asking over at https://github.com/Kong/unirest-python
