### ISSUE TITLE
Issues adding as a 3rdparty dependency for pants

### ISSUE THREAD

**Issue by disha-dp** [facebook/prophet#883]
I tried adding fbprophet to pants 3rdparty requirement like below:

python_requirement_library(
  name='fbprophet',
  requirements=[
    python_requirement('fbprophet==0.4.post2'),
  ])

facing issues with pystan, the error is:

  File "setup.py", line 44, in run
    build_stan_model(target_dir)
  File "setup.py", line 27, in build_stan_model
    from pystan import StanModel
ImportError: No module named pystan

This is on python 2.7.11. I also tried using fbprophet0.3.post2 but that didn't seem to resolve the issue as well. 
Any clues on what should be done for this transitive `fbprophet` dependency on `pystan` ?

**Comment by disha-dp** [comment]
Looked into how pystan is used in the code. Why is the StanModel read and pickled 
and later pickle.load is applied inside the forecaster.py code?  

Alternatively, the forecaster can import pystan and read the StanModel, passing it the necessary parameters. Is there a concern around performance issues?

**Comment by bletham** [comment]
The model is shipped as a stan file which is compiled down to C++ with pystan on the local machine. This compiling takes about 2 minutes, and so we do it once at install time, pickle the compiled model and store it along with the other installed files. Then at import time, we can just load up the already compiled model.

So pystan has to be installed before fbprophet can be installed. I'm not familiar with pants, do they allow something like setup_requires where you can specify to install pystan first?
