### ISSUE TITLE
FBProphet negative resistance / Limit value / marginal value

### ISSUE THREAD

**Issue by alstjq9295** [facebook/prophet#884]
Hi!
First, thank you for your help with the fbprophet.

`
from datetime import date, datetime, timedelta
import pandas as pd
import numpy as np
from pandas import Series, DataFrame
import cx_Oracle
from fbprophet import Prophet
import matplotlib.pyplot as plt

conn = cx_Oracle.connect("-------------")
db = conn.cursor()
db.execute("select * from TEST01 where EVT_COD = 'BANDWIDTH' AND USR_PF_NO = 2910 AND YYYYMMDDHH >= 2019031000 AND YYYYMMDDHH < 2019031300")
res = db.fetchall()
db.close()
conn.close()
df = pd.DataFrame(res)[[2,4]]
df.columns = ["ds","y"]
df["ds"] = pd.to_datetime(df["ds"], format="%Y%m%d%H")
df["cap"] = df["y"].max()*1.1
df["floor"] = 0
m = Prophet(daily_seasonality=True, weekly_seasonality=True,growth="logistic")
m.fit(df)
future = m.make_future_dataframe(periods=24, freq="H")
future["cap"] = df["y"].max()*1.1
future["floor"] = 0
forecast = m.predict(future)
plz = m.plot(forecast)`

![Cap 2019-03-14 11-08-11-043](https://user-images.githubusercontent.com/48229415/54326395-a23d6400-4649-11e9-9bdb-aa114d1f9641.png)
![Cap 2019-03-14 11-08-56-146](https://user-images.githubusercontent.com/48229415/54326396-a23d6400-4649-11e9-9925-d526d53da525.png)

This is my code and prediction graph.
If you look at the graph, the predicted value is negative.
Negative yhat_upper is visible in the learning(training) data.
I think this means that the forecast can go down below zero.
All I want is never to send yhat_upper below zero.
Does "growth="logistic" never come out below zero?
Do you have such a condition or parameter?

**Comment by whuizhe** [comment]
Try adjusting parameters ‘seasonality_scale’ or ‘changepoint_prior_scale’ or 'seasonality_mode' in Prophet
           
                daily_seasonality=True
                changepoint_prior_scale=0.01
                seasonality_mode='multiplicative'
                seasonality_prior_scale=50.0
                interval_width=0.80

**Comment by alstjq9295** [comment]
> Try adjusting parameters ‘seasonality_scale’ or ‘changepoint_prior_scale’ or 'seasonality_mode' in Prophet
> 
> ```
>             daily_seasonality=True
>             changepoint_prior_scale=0.01
>             seasonality_mode='multiplicative'
>             seasonality_prior_scale=50.0
>             interval_width=0.80  
> ```

**Comment by alstjq9295** [comment]
thanks, but it doesn't make yhat_upper goes negative value.

**Comment by bletham** [comment]
What's happening here is that the logistic growth function applies only to the trend component of the model - it ensures that the trend will be between `floor` and `cap`. If you look at `m.plot_components(fcst)`, you should see that that is the case.

But with additive seasonality, `yhat = trend + seasonality` and so if there is at any point a negative seasonal effect, that will drive `yhat` to be negative. That is what is happening here.

The best thing to do in this case is just to clamp negative values to 0.

**Comment by alstjq9295** [comment]
The conclusion is that it is best to keep the negative values fixed at 0.
Thank you for giving me a definite answer.
Have a nice day!
