### ISSUE TITLE
import fbprophet fails and kills ipython session.

### ISSUE THREAD

**Issue by princethewinner** [facebook/prophet#887]
on import fbprophet kills the ipython session via below error.

```
Python 3.6.8 |Anaconda custom (64-bit)| (default, Dec 30 2018, 01:22:34) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.3.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import fbprophet                                                                                                                                             

In [2]: X11 connection rejected because of wrong authentication.                                                                                                     
qt.qpa.screen: QXcbConnection: Could not connect to display analytics-lab:10.0
Could not connect to any X display.

```
Is there a way where fbprophet can be imported without X11 connection?

**Comment by princethewinner** [comment]
After some digging, I found that this issue is coming because of matplotlib default backend. As a workaround following things seems to work.

```
import matplotlib
matplotlib.use('agg')
import fbprophet
```
As an other workaround, the following changes can be made directly into the matplotlibrc file (https://matplotlib.org/users/customizing.html)

change 
```
backend      : TkAgg
```
 to
```
backend      : Agg
```

**Comment by jbanik85** [comment]
Just a curiosity: are you using Mac (OS X)? I generally use Windows 10, but I did once try to use it in my Macbook, and IIRC there was a problem with Matplotlib, which did not allow me to plot.

**Comment by princethewinner** [comment]
No, I am using Ubuntu. I have faced a similar problem with other libraries as well, which import matplotlib internally.

**Comment by bletham** [comment]
Is there an error or warning or something that we can catch when matplotlib is imported to avoid this?
