### ISSUE TITLE
FutureWarning: 'ds' is both an index level and a column label

### ISSUE THREAD

**Issue by whitehatty** [facebook/prophet#891]
In `setup_dataframe` line 250 of `forecaster.py`:
```                
        df = df.sort_values('ds')
        df.reset_index(inplace=True, drop=True)
```

If `df` contains index and column with same name the following warning is generated:
```
fbprophet/forecaster.py:250: FutureWarning: 'ds' is both an index level and a column label.
 Defaulting to column, but this will raise an ambiguity error in a future version
```

Warning (and future issue) can be solved by putting either of the following lines before the sorting:
- `df.index.name = None`
- `df = df.rename_axis(None)`
or by calling `reset_index` before and after the call to `sort_values`

**Comment by bletham** [comment]
Thanks for identifying this, there are a few FutureWarnings popping up with the latest pandas that we'll have to go through and clean up for the next version.

**Comment by whitehatty** [comment]
I can open a PR later today if you tell me which approach you prefer better (out of those I listed or something else)

**Comment by bletham** [comment]
That'd be great, I don't have a preference for the approach.

**Comment by bletham** [comment]
Actually I haven't been able to produce this, how did you run into it?

**Comment by whitehatty** [comment]
If your pandas dataframe df has a timestamp column ds (which is what prophet expect) and you call df.resample(..., on=‘ds’) before passing the df to prophet ds becomes an index too.

So the problem is how data is manipulated before passing it to prophet, because prophet does not clean it up when setting up the df for internal use.

**Comment by t3ja** [comment]
is there a work around for this currently?

**Comment by bletham** [comment]
@t3ja does `df.index.name = None` before passing the data into prophet do it?

**Comment by maverick100** [comment]
Can I work on this issue,if its not closed yet ?

**Comment by whitehatty** [comment]
I am sorry I didn’t follow up on this sooner.

Setting the index name to None works, but maybe you want to wait to see if Facebook devs want the change within prophet or let it be on the user.

IMO it is alright as it is literally a one line change.

**Comment by bletham** [comment]
A change inside prophet I think would make sense.

**Comment by fdroessler** [comment]
I hope it was ok to pick this up @maverick100 @whitehatty

**Comment by whitehatty** [comment]
Absolutely, I had completely forgot about it

**Comment by Nithindinesh24** [comment]
df.index.name = None, works fine .thanks @bletham bletham

**Comment by bletham** [comment]
Fix is now pushed to PyPI
