### ISSUE TITLE
Unable to install fbprophet in anaconda

### ISSUE THREAD

**Issue by amruutharao** [facebook/prophet#892]
I have installed the package fbprophet using the following command 
 conda install -c conda-forge fbprophet .
I have checked the list of packages installed and it shows that fbprophet is successfully installed. 

In my jupyter notebook, when i am trying to import prophet i get an error as follow. 
"ModuleNotFoundError: No module named 'fbprophet'" .

I tried using pip install fbprophet but it does not work because of issues in pystan. 
If someone knows how to install fbprophet command and import prophet , please reply . 

I use the following configuration.
Python : 2.7.15
anaconda2

**Comment by amruutharao** [comment]
@dghete ,@Gordonei , @bletham, @ivonnics , @seanjtaylor

**Comment by bletham** [comment]
I'm guessing that the notebook is not using the Anaconda python (but perhaps is using system python). You can check in the notebook what python is being used:
```
import sys
print(sys.executable)
```
see also https://stackoverflow.com/questions/52913748/how-to-choose-your-conda-environment-in-jupyter-notebook

**Comment by amruutharao** [comment]
I have checked the path it is pointing to using above command and i could understand that the path it is pointing to is 
C:\Users\****\AppData\Local\Continuum\anaconda3\python.exe. 

Not sure if i need to re configure my jupyter notebook to point to conda environment since i use tabpy server and it was affected due to an unstable package ( tornado ).

**Comment by bletham** [comment]
I don't actually use conda myself and so cannot be of much help in figuring out issues related to conda environments.

**Comment by ivonnics** [comment]
I would recommend @amruutharao to reinstall Anaconda and then, install fbprophet in a separate environment:
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

**Comment by ivonnics** [comment]
FYI @amruutharao :      
https://stackoverflow.com/questions/22585235/python-anaconda-how-to-safely-uninstall

**Comment by amruutharao** [comment]
I have re installed the anaconda environment . 
1. I tried to install it with pip install fbprophet.
but i get the error that  " no module named pystan"

2. I also tried using 
conda install -c conda-forge fbprophet . It shows " solving the environment " ... forever. 
I am having more issues than before and am not sure why

**Comment by bletham** [comment]
You definitely want to use conda forge to install it in conda. Maybe try
```
conda update conda
```
first?

**Comment by amruutharao** [comment]
I have tried that i ran the command  "conda install -c conda-forge fbprophet"


UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda==2018.12=py37_0 -> curl==7.63.0=h2a8f88b_1000 -> krb5[version='>=1.16.1,<1.17.0a0'] -> tk[version='>=8.6.7,<8.7.0a0']
  - anaconda==2018.12=py37_0 -> mkl-service==1.1.2=py37hb782905_5
  - anaconda==2018.12=py37_0 -> numexpr==2.6.8=py37hdce8814_0
  - anaconda==2018.12=py37_0 -> scikit-learn==0.20.1=py37h343c172_0
  - fbprophet
Use "conda info <package>" to see the dependencies for each package.

**Comment by bletham** [comment]
what does the conda info show as the dependencies for fbprophet? nothing listed there seems like it should be an issue.

**Comment by kevinwbolger** [comment]
https://ipython.readthedocs.io/en/stable/install/kernel_install.html#kernels-for-different-environments

Follow instructions here. You need to follow the section where it says:

'Using virtualenv or conda envs, you can make your IPython kernel in one env available to Jupyter in a different env. To do so, run ipykernel install from the kernel’s env, with –prefix pointing to the Jupyter env:'

**Comment by luanaformiga** [comment]
I've had the same problem. But it works after I follow this steps:

On Prompt install Ephem:
conda install -c anaconda ephem

Install Pystan:
conda install -c conda-forge pystan

Finally install Fbprophet
conda install -c conda-forge fbprophet

**Comment by jjjacques** [comment]
Thank You @luanaformiga 
running this command also install ephem and psystan
$conda install -c conda-forge fbprophet

**Comment by ryan1110-hen** [comment]
Hey, I have conda, python and prophet downloaded. However I am getting an error message that says 

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-8402a205f64c> in <module>
      2 import matplotlib as mpl
      3 import matplotlib.pyplot as plt
----> 4 from fbprophet import Prophet
      5 from fbprophet.plot import plot_plotly
      6 import plotly.offline as py

//anaconda3/lib/python3.7/site-packages/fbprophet/__init__.py in <module>
      6 # of patent rights can be found in the PATENTS file in the same directory.
      7 
----> 8 from fbprophet.forecaster import Prophet
      9 
     10 __version__ = '0.5'

//anaconda3/lib/python3.7/site-packages/fbprophet/forecaster.py in <module>
     20 from fbprophet.make_holidays import get_holiday_names, make_holidays_df
     21 from fbprophet.models import prophet_stan_model
---> 22 from fbprophet.plot import (plot, plot_components, plot_forecast_component,
     23                             plot_seasonality, plot_weekly, plot_yearly,
     24                             seasonality_plot_df)

ModuleNotFoundError: No module named 'fbprophet.plot'

When I go to download fbprophet.plot it says it already exists but it then says "conda create"
after doing that it doesn't seem to resolve the issue.  Here is my python code currently entered:

import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
from fbprophet import Prophet
from fbprophet.plot import plot_plotly
import plotly.offline as py
pd.plotting.register_matplotlib_converters()
# Import the data
call_volume = pd.read_csv('/Users/ryanhenderson/Downloads/Apollo-master/call-daily-demand.csv')
chat_volume = pd.read_csv('/Users/ryanhenderson/Downloads/Apollo-master/chat-daily-demand.csv')
email_volume = pd.read_csv('/Users/ryanhenderson/Downloads/Apollo-master/email-daily-demand.csv')
# Fit the model, and pass any settings for the forecasting procedure to the constructor.
call_model = Prophet(daily_seasonality = False)
call_model.add_country_holidays(country_name = 'US')
chat_model = Prophet(daily_seasonality = False)
chat_model.add_country_holidays(country_name = 'US')
email_model = Prophet(daily_seasonality = False)
email_model.add_country_holidays(country_name = 'US')
# Pass the fit method the historical data
call_model.fit(call_volume)
chat_model.fit(chat_volume)
email_model.fit(email_volume)
#Extend the dataframe into the future
call_future = call_model.make_future_dataframe(periods = 530)
chat_future = chat_model.make_future_dataframe(periods = 530)
email_future = email_model.make_future_dataframe(periods = 530)
# Assign each row in future a predicted value which is named yhat
# The forecast object here is a new dataframe that includes a column yhat with the forecast,
# as well as columns for components and uncertainty intervals.
call_forecast = call_model.predict(call_future)
chat_forecast = chat_model.predict(chat_future)
email_forecast = email_model.predict(email_future)
# Plot the forecast!
py.init_notebookmode()
call_daily_forecast = plot_plotly(call_model, call_forecast)
chat_daily_forecast = plot_plotly(chat_model, chat_forecast)
email_daily_forecast = plot_plotly(email_model, email_forecast)
py.iplot(call_daily_forecast)
py.iplot(chat_daily_forecast)
py.iplot(email_daily_forecast)

any ideas on what I need to do? thanks in advance

**Comment by imohamedimran** [comment]
> I've had the same problem. But it works after I follow this steps:
> 
> On Prompt install Ephem:
> conda install -c anaconda ephem
> 
> Install Pystan:
> conda install -c conda-forge pystan
> 
> Finally install Fbprophet
> conda install -c conda-forge fbprophet

Thank you SO very much, lunaformiga

**Comment by JamieL22** [comment]
WARNING:pystan:MSVC compiler is not supported
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/

**Comment by TelaproluHaritha** [comment]
@JamieL22  i got the same error

**Comment by bhaskoro-muthohar** [comment]
> I've had the same problem. But it works after I follow this steps:
> 
> On Prompt install Ephem:
> conda install -c anaconda ephem
> 
> Install Pystan:
> conda install -c conda-forge pystan
> 
> Finally install Fbprophet
> conda install -c conda-forge fbprophet

It works like a charm. You saved me!

**Comment by JamieL22** [comment]
Tried again with your lead  bhaskoro-muthohar.  Using the Visual Studio 2017, Tools |  Python Tools | Python environment.   Version 3.6 from VS has all three commands:
Install ephem 3.7.7.1
Installl pystan 2.19.1.1
install fbprophet 0.6 failed

I see there is also a version 
covid-19-prophet

This too fails.

**Comment by ank-1rma** [comment]
> I've had the same problem. But it works after I follow this steps:
> 
> On Prompt install Ephem:
> conda install -c anaconda ephem
> 
> Install Pystan:
> conda install -c conda-forge pystan
> 
> Finally install Fbprophet
> conda install -c conda-forge fbprophet

thanks, finally after 2 days

**Comment by huangwan612** [comment]
> I've had the same problem. But it works after I follow this steps:
> 
> On Prompt install Ephem:
> conda install -c anaconda ephem
> 
> Install Pystan:
> conda install -c conda-forge pystan
> 
> Finally install Fbprophet
> conda install -c conda-forge fbprophet

THANK YOU SO MUCH! @luanaformiga finally solved my problem!

**Comment by azdaly** [comment]
> I've had the same problem. But it works after I follow this steps:
> 
> On Prompt install Ephem:
> conda install -c anaconda ephem
> 
> Install Pystan:
> conda install -c conda-forge pystan
> 
> Finally install Fbprophet
> conda install -c conda-forge fbprophet

This worked great for me! Just be aware that it won't work with pyhon 3.9 <=. I had to downgrade to python 3.7.

**Comment by Rutikab12** [comment]
> I've had the same problem. But it works after I follow this steps:
> 
> On Prompt install Ephem:
> conda install -c anaconda ephem
> 
> Install Pystan:
> conda install -c conda-forge pystan
> 
> Finally install Fbprophet
> conda install -c conda-forge fbprophet

Yes this process helps. Thank You.

**Comment by gur-p-reet** [comment]
I've had the same problem. But it works after I follow this steps:

On Prompt install Ephem:
conda install -c anaconda ephem

Install Pystan:
conda install -c conda-forge pystan

Finally install Fbprophet
conda install -c conda-forge fbprophet

Thanks a lot @luanaformiga

**Comment by Anirban095** [comment]
> I've had the same problem. But it works after I follow this steps:
> 
> On Prompt install Ephem: conda install -c anaconda ephem
> 
> Install Pystan: conda install -c conda-forge pystan
> 
> Finally install Fbprophet conda install -c conda-forge fbprophet

I am using streamlit where I am using fbprophet. After doing all this steps too I am seeing ModuleNotFoundError

**Comment by iftesha1** [comment]
1. Create a virtual environment using  
   conda create --name myenv

2. Activate the environment using 
    conda activate myenv

3. Install ephem using
     conda install -c anaconda ephem

4. Install pystan using 
     conda install -c conda-forge pystan

5. Install the fbrprophet using 
    conda install -c conda-forge fbprophet

6. At the end install holidays
   pip install holidays==0.9.12

7. If it still doesn't work try this at last
  conda install psycopg2
