### ISSUE TITLE
How to fitting daily data correctly??

### ISSUE THREAD

**Issue by Gypsying** [facebook/prophet#897]
Dear developers,
I have every minute data and want to make a prediction for every minute the next hour,
here is my forecast by prophet:
![image](https://user-images.githubusercontent.com/17995262/54746291-bc0d1700-4c06-11e9-8aad-bf2e1ba2894c.png)
![image](https://user-images.githubusercontent.com/17995262/54746547-61c08600-4c07-11e9-936d-185ed9a5d349.png)

As you can see, the data is daily, the whole trend is ok, but there is a little increase everyday which doesn't fitting correctly,
Any parameters need to adjust to fit that case?

Looking forward to your reply.
Thanks

**Comment by vhpietil** [comment]
You need to increase the order of the daily seasonality

**Comment by Gypsying** [comment]
> You need to increase the order of the daily seasonality

Thank you for the reply, my code like that:
`m = Prophet(
    yearly_seasonality=False,
    weekly_seasonality=False,
    daily_seasonality=True,
    n_changepoints=30,
    changepoint_range=0.8,
    changepoint_prior_scale=0.5,
    interval_width=1.0,
)
m.add_seasonality(name='daily', period=1440, fourier_order=30, prior_scale=0.8)
m.fit(df)
future = m.make_future_dataframe(periods=60,freq='min')
forecast = m.predict(future)`

Although i change the fourier_order from 3 to 30, but the result doesn't fitting better...

Just to be clear, my input is 8 days' minute data.

**Comment by vhpietil** [comment]
I dont think you need to add daiy seasonality if you have daily_seasonality=Tru. Try daily_seasonality=10

**Comment by Gypsying** [comment]
> I dont think you need to add daiy seasonality if you have daily_seasonality=Tru. Try daily_seasonality=10

You are right!!!

![image](https://user-images.githubusercontent.com/17995262/54796012-69287380-4c89-11e9-9094-fe803449d4c5.png)

Thank you so much!    Wish you a happy day!!
