### ISSUE TITLE
MAPE value incongruence between plot_cross_validation_metric and performance_metrics df

### ISSUE THREAD

**Issue by pmaji** [facebook/prophet#899]
@bletham -- I think I saw you tagged the last time this plot came up. But I am confused as to where the grey dots are coming from. I thought that all of the grey dots in the chart attached were taken from the MAPE column in the dataframe on which I called df.describe(), and from the source code that appears to be the case, but there are grey dots that are far larger than the max shown in the df.describe(). 

I guess the tl;dr is that I am seeing grey dots in the chart that have super high MAPE values, but they aren't in the df, and I can't figure out where they are being taken from...

![Screen Shot 2019-03-21 at 7 18 04 PM](https://user-images.githubusercontent.com/25461122/54790917-38572880-4c0e-11e9-84d6-72cbf8058d5c.jpg)

**Comment by bletham** [comment]
The `df_p` that you are generating is computing the metrics with moving averages with a window size of 10%. This is what is plotted in the blue line. You can see that the maximum of the blue line is the 0.83 that is the max in `df_p`.

The gray dots come from doing the same calculation with a rolling window of 0 (that is, no averaging at all):
https://github.com/facebook/prophet/blob/master/python/fbprophet/plot.py#L463
so each represents the absolute percent error (no mean involved) for each pair (y_hat, y) that was forecasted during the cross validation.

**Comment by pmaji** [comment]
Thank you @bletham ! You're totally right, my bad for not seeing that. I wrote some code to prove that this is the case by manually calculating the residuals and cross-checking them against the plot. If you're interested, you can see that in the vignette I just finished showing off some of Prophet's basic functionalities here: https://github.com/pmaji/data-science-toolkit/blob/master/time-series/forecasting_with_prophet.ipynb

**Comment by bletham** [comment]
@pmaji looks great, thanks for sharing!
