### ISSUE TITLE
Series.nonzero() deprecation warning

### ISSUE THREAD

**Issue by ispmarin** [facebook/prophet#900]
When running a mode fit, I´m getting the following warning:
```
/home/user/lib/venvs/ts/lib/python3.5/site-packages/fbprophet/forecaster.py:880: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  min_dt = dt.iloc[dt.nonzero()[0]].min()
```
using prophet version 0.4.post2 on Debian Stretch.

**Comment by bletham** [comment]
Thanks, we'll definitely have to clean this up before the next release.

**Comment by raybellwaves** [comment]
Any advice on how to do this? I can take this on.

**Comment by raybellwaves** [comment]
I actually learnt this today:

```
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
```

**Comment by bletham** [comment]
@raybellwaves I think this one should just be a matter of replacing `.nonzero()` with `.to_numpy().nonzero()` in
https://github.com/facebook/prophet/blob/master/python/fbprophet/forecaster.py#L899

**Comment by raybellwaves** [comment]
@ispmarin Can you provide reproducible code that gives that warning?

**Comment by ericmjalbert** [comment]
@raybellwaves Here is some minimal code that brings up the warning for me:
```
from fbprophet import Prophet
import pandas as pd

df = pd.DataFrame({"ds": pd.date_range("2019-01-01", "2019-01-02"), "y": 1})

m = Prophet()
m.fit(df)
```

On MacOS using: `pandas==0.24.2` and `fbprophet==0.4.post2`

**Comment by ispmarin** [comment]
:+1:

**Comment by bletham** [comment]
Pushed to PyPI
