### ISSUE TITLE
about prophet and kalman filter

### ISSUE THREAD

**Issue by zcsh** [facebook/prophet#903]
Dear Prophet authors and everyone,
I am trying forecasting a time series using both Prophet and Kalman filter, a state space model, recently. One issue I am interested in is if there are any conceptual similarities and/or dissimilarities between these two algorithms.  Anyone has investigated into the bottom principle of both algorithms?
thanks for any replying.

**Comment by bletham** [comment]
I don't think there is a very deep connection between the two methods. The Kalman filter is a state space model that models the evolution from one time step to the next with a linear operator. Prophet is a regression model that models the entire time series with a piecewise linear function plus specific seasonality components. The Kalman filter is a more general model, whereas Prophet explicitly models features common to many business time series, like weekly and yearly seasonality. They're really quite different, and I think the best I could do is to refer to the paper here: https://peerj.com/preprints/3190.pdf
