### ISSUE TITLE
Upswing forecast of Prophet 

### ISSUE THREAD

**Issue by soumenms2015** [facebook/prophet#905]
I can observe that the forecast of Prophet model is always increased although it maintains the similar trend like past because of the additive model nature. But this might not be the case!! How to get rid of it?

**Comment by jbanik85** [comment]
I cannot comment specifically on your case, but I have noticed that it sometimes happen if you have a overfit. Try reducing the changepoint_prior_scale to a lower value. 

I have also seen, when  if the process you are modeling has a zero growth/very low growth. I have found better forecasts when I switched n_changepoints to a lower value (default is 25). 

Again, I don't know if these approaches are going to solve your problem. May be for a more effective response, you should post more details (if possible, your raw data), and plot of your forecast, and different components.

**Comment by bletham** [comment]
If you post the output of `m.plot` that would be really helpful for giving more concrete feedback on what is happening here.

The model does take whatever the trend is in the last part of the time series and project that forward. If there have been many trend changes in the history, that will be reflected in wide uncertainty intervals. If the trend is continuing to go up but you know it should level off at some specific point, then that can be done as described here: https://facebook.github.io/prophet/docs/saturating_forecasts.html
