### ISSUE TITLE
Feature Request: BoxCox Transformation

### ISSUE THREAD

**Issue by rohan-gt** [facebook/prophet#906]
Can the pre-processing transformation for multiplicative or non-normal time series be parameterised to include both log and BoxCox transformations or better yet just BoxCox since the log transform is a subset of the BoxCox family?

**Comment by bletham** [comment]
I'm pretty hesitant to bake these transformations into the package since the components are no longer directly interpretable. Is there any significant benefit to having this built-in vs. just doing it before passing the data into Prophet?
