### ISSUE TITLE
"Found NaN in column" for regressors

### ISSUE THREAD

**Issue by 123Rukza** [facebook/prophet#908]
Hello, I'm trying to solve a time series problem using Prophet and I'm unable to add any external regressors. I keep getting the same error for each variable I tried. I cross checked with each variable for the availability of NaNs and I'm 100% sure NaN values are not there. I'm following the general walkthrough on the official website and my code looks similar to the following,

`m = Prophet(growth='linear',changepoint_prior_scale=0.01, holidays = holidays)`
`m.add_regressor('cols')`
`m.fit(train_X)`

`preds = m.make_future_dataframe(periods=24,freq='H')`
`preds['cols'] = df['cols']`

`f = m.predict(preds)`

As soon as the last line is executed the following error is thrown

> Found NaN in column cols

And also the df dataframe has enough future data for the prediction to happen. What could be the root cause of this issue.

**Comment by 123Rukza** [comment]
Okay I found the solution for this. I was doing some preprocessing on the data and dropping a few rows here and there. Therefore there were gaps in the pandas index. Running the code below fixed my problem.

`df.reset_index(drop=True)`

**Comment by bletham** [comment]
Glad you were able to find the source! I think a `pd.merge` between preds and df on column ds might also be a safe way to get extra regressor values attached without introducing NaNs from missing rows.

**Comment by timkofu** [comment]
@bletham With `pd.merge`, it removes the additional periods, and makes future the same length as the training set.

I have a multivariate five year dataset, with five other features in addition to `y`. I have a train test split, where the training set is the first 4 years. I want it to predict the 5th year, so I can compare the results with the actual 5th year data.

I make the `future` dataframe with `make_future_dataframe(periods=365)`. I `pandas.concat` the future and train DFs (as `pandas.merge` cuts off the blank 5th year) `future_regressors = pandas.concat([future, train[['f1', 'f2', 'f3', 'f4', 'f5']]], axis=1)`. Prophet however wants the 5 regressors to have values in the 5th year (which it expresses by complaining about the NaNs from the beginning of the 5th year), but the data doest exist in the training set.

What's the best way to go about this?

**Comment by timkofu** [comment]
Found the answer on [this SO post](https://stackoverflow.com/a/58781257/433717), specifically:

> Note that the additional variables should have values for your future (test) data. If you don't have them, you could start by predicting add1 and add2 with univariate timeseries, and then predict y with add_regressor and the predicted add1 and add2 as future values of the additional variables.

**Comment by timkofu** [comment]
Found the answer on [this SO post](https://stackoverflow.com/a/58781257/433717), specifically:

> Note that the additional variables should have values for your future (test) data. If you don't have them, you could start by predicting add1 and add2 with univariate timeseries, and then predict y with add_regressor and the predicted add1 and add2 as future values of the additional variables.
