### ISSUE TITLE
Feature Request: Add Median Absolute Percent Error to diagnostics

### ISSUE THREAD

**Issue by raybellwaves** [facebook/prophet#911]
Median Absolute Percent Error may be a useful metric for noisy data with multiple holidays.

**Comment by bletham** [comment]
That makes a lot of sense. It would be added to https://github.com/facebook/prophet/blob/master/python/fbprophet/diagnostics.py like the others (but would look a little different since it would be a rolling median instead of a rolling mean).

**Comment by ryankarlos** [comment]
@bletham seems that `mdape` is already included in master with tests - should this be closed or is there any further enhancement required ?

**Comment by bletham** [comment]
This is done in Py, but I'll leave it open since for us to translate it into the R too.

**Comment by ryankarlos** [comment]
ok happy to submit a PR

**Comment by ryankarlos** [comment]
take

**Comment by bletham** [comment]
That'd be great!

**Comment by emmaliden** [comment]
It looks to me as if there is some confusion as to if the mdape is an included metric in Python or not. I'm looking in the code in here:

https://github.com/facebook/prophet/blob/master/python/fbprophet/diagnostics.py 

In the comments on lines 305-311 and lines 335-339 a list of default performance metrics are given and mdape is not included. On row 345 on the other hand a list called valid_metrics is created and mdape is included in this list. Function mdape is also defined further down (on row 568).

Just from reading the code I'm not sure what the actual behavior would be but when using the package I don't seem to get mdape as a default and I haven't been able to make it work by including it in a list of metrics as an input either.

**Comment by ryankarlos** [comment]
@emmaliden  Are you trying this with prophet v0.6 or the version from master branch ? so `mdape` is definitely included as a metric in python. The docstrings need updating for both the cases which you point out (including the notebook example)- i've pushed a PR including those changes.

```
>>df = pd.read_csv('examples/example_wp_log_peyton_manning.csv')
>>df.head()
 
           ds         y
0  2007-12-10  9.590761
1  2007-12-11  8.519590
2  2007-12-12  8.183677
3  2007-12-13  8.072467
4  2007-12-14  7.893572

>>m = Prophet()
>>m.fit(df)

>>from fbprophet.diagnostics import cross_validation
>>df_cv = cross_validation(m, initial='730 days', period='180 days', horizon = '365 days')
>>df_cv.head()

>>from fbprophet.diagnostics import performance_metrics
>>df_p = performance_metrics(df_cv)
>>df_p.head()
 
  horizon       mse      rmse       mae      mape     mdape  coverage
0 37 days  0.493403  0.702427  0.504660  0.058481  0.050009  0.676565
1 38 days  0.499306  0.706616  0.509672  0.059061  0.049334  0.676565
2 39 days  0.521533  0.722172  0.515789  0.059662  0.049502  0.675194
3 40 days  0.528744  0.727148  0.518585  0.059961  0.049254  0.678849
4 41 days  0.536127  0.732207  0.519498  0.060030  0.049334  0.683874
```

**Comment by emmaliden** [comment]
@ryankarlos I'm using v0.6 . I'm working in an environment where I only have access to conda (not pip) and that was the version that I got there. Is it not up to date with what is here?

**Comment by bletham** [comment]
@emmaliden we haven't yet pushed out a new version since mdape was added. I expect we will soon but in the meantime you'd have to either install the latest master branch from source, or compute it manually from the output of `cross_validation`.

**Comment by emmaliden** [comment]
@bletham Okay. Thank you. I’ll do that.
