### ISSUE TITLE
Additional regressors methodology

### ISSUE THREAD

**Issue by AnupaS** [facebook/prophet#912]
Can someone please explain what methodology Prophet uses for fitting additional regressors?

**Comment by bletham** [comment]
The basic model (ignoring holidays) is
```
y(t) = trend(t) + s(t)
```
where `s(t)` is the seasonal effect. If you look at the paper (https://peerj.com/preprints/3190.pdf) equation (6), seasonality is modeled with a big linear term `X(t) \beta`. Each column of `X(t)` there is a regressor used to model seasonality (weekly seasonality uses 6 columns). The vector `\beta` is fit to the data.

So the model is actually
```
y(t) = trend(t) + X(t) \beta
```

For additional regressors, they are just included alongside the seasonality as additional columns in X(t), and the coefficient in `\beta` is fit in the same way. So if you have some extra regressor `z(t)`, it would be equivalent to
```
y(t) = trend(t) + X(t) \beta + z(t) \beta_z
```
where (scalar) `\beta_z` is fit to the data.

Does that clarify things?

**Comment by AnupaS** [comment]
> The basic model (ignoring holidays) is
> 
> ```
> y(t) = trend(t) + s(t)
> ```
> where `s(t)` is the seasonal effect. If you look at the paper (https://peerj.com/preprints/3190.pdf) equation (6), seasonality is modeled with a big linear term `X(t) \beta`. Each column of `X(t)` there is a regressor used to model seasonality (weekly seasonality uses 6 columns). The vector `\beta` is fit to the data.
> 
> So the model is actually
> 
> ```
> y(t) = trend(t) + X(t) \beta
> ```
> For additional regressors, they are just included alongside the seasonality as additional columns in X(t), and the coefficient in `\beta` is fit in the same way. So if you have some extra regressor `z(t)`, it would be equivalent to
> 
> ```
> y(t) = trend(t) + X(t) \beta + z(t) \beta_z
> ```
> where (scalar) `\beta_z` is fit to the data.
> 
> Does that clarify things?

**Comment by AnupaS** [comment]
I meant which parameter estimation technique is used, like bayesian regression, least squares estimation etc.?

**Comment by bletham** [comment]
By default it will do MAP estimation of the Bayesian model, which (since there is a Normal noise model) is equivalent to a penalized least squares estimation. In particular, it is least squares estimation with a L1 (lasso) penalty on the trend change magnitudes and an L2 (ridge) penalty on the seasonality/regressor coefficients. So, for additional regressors you can think about it as being ridge regression.
