### ISSUE TITLE
Disabling logging doesn't work properly

### ISSUE THREAD

**Issue by cesarob** [facebook/prophet#913]
I spotted that importing *Prophet* was the source  of having duplicated logs and changing the log level of the library in the standard way didn't work.

```
logging.getLogger('fbprophet').setLevel(logging.ERROR)
```

Having a look to the code I see you are always calling *logging.basicConfig*. See
https://github.com/facebook/prophet/blob/master/python/fbprophet/forecaster.py#L26-L29.

I don't get why you do that being a library. As right now you are just setting in the logger a NullHandler, you migh wish to initialize it to NOTSET level that thats all. This way you could tune the level of the logs in the library and delegate in any defined root logger.

**Comment by bletham** [comment]
We emulated PyStan when setting up the logging, and there are some directions over there on how to customize the logger:
https://github.com/stan-dev/pystan/blob/develop/doc/logging.rst

Is there something that you want to do that isn't supported by the instructions there?

**Comment by burk** [comment]
I just had a similar issue. Suddenly debug-logs did not appear for a service that used to have that enabled. We used `basicConfig` to set this up, but after importing fbprophet, this stopped working.

The problem is that you cannot call `basicConfig` more than once (and we imported fbprophet earlier than calling `basicConfig`.

So it seems wrong to do it from a library that can be imported in a number of places. See the docs of `basicConfig`:
```
Do basic configuration for the logging system.

    This function does nothing if the root logger already has handlers
    configured. It is a convenience method intended for use by simple scripts
    to do one-shot configuration of the logging package.
```

**Comment by bletham** [comment]
If logging handlers have been set before importing fbprophet, then `basicConfig` will not be called. That's my understanding anyway, we really followed PyStan on this one and if there is a better way to have logging "just work" by default but allow easy overriding I'd love to hear it.

**Comment by S-Black** [comment]
I have had a similar issue and adding `logger.propagate = False` to my code under the declaration of my logger object has solved it.
