### ISSUE TITLE
Question about seasonal components on non-daily data 

### ISSUE THREAD

**Issue by mrastgoo** [facebook/prophet#916]
Hello, 

Thank you for the wonderful library. 
I am newbie in time series forecast and I have a question regarding seasonality indices that I can get using `weekly` or `yearly` coefficients provided by `self.predict_seasonal_components()` method. 

I am working with weekly data, over the past 4 years (52 samples per year, 208 samples total ) and I realized that `plot_weekly` and `plot_yearly` are using daily frequencies. 
So I will get a coefficient for each day of the week, using `plot_weekly`  for instance. However since I don't have daily data, and the model is built using weekly data, is it still relevant to have daily coefficients in a week ? 

Going through the library I figured out how can I get the parameters using weekly frequencies (see below), however I would like to know if having non-daily data I still can trust the plot_weekly and plot_weekly or like below I should change the dataframe passed to  `model.predict_seasonal_components` based on my data

```
days = \
(pd.date_range(start='2017-01-01', periods=52, freq='W') + pd.Timedelta(days= 0))

df = seasonality_plot_df(model, days)
seas= model.predict_seasonal_components(df)
seas_weekly_coef  = seas['weekly']

```
Thanks for your response in advance.

**Comment by bletham** [comment]
That's correct that the weekly and yearly seasonality plots show the seasonality at daily intervals. But the underlying model is actually continuous. So what the plot is showing are samples of a continuous function and not the model coefficients themselves.

(In the model, the number of coefficients will be twice the seasonality fourier order, which will be default be 6 for weekly seasonality and 20 for yearly seasonality.)

As for the appropriateness with weekly data:

With weekly data, the weekly seasonality will not be identifiable and should be disabled. It actually should be turning itself off by default, if that isn't happening then I'd appreciate if you could upload the list of dates in the timeseries so I can figure out why it isn't being disabled.

Yearly seasonality should be just fine with weekly data. There is some discussion in the documentation about interpreting yearly seasonality with monthly data (https://facebook.github.io/prophet/docs/non-daily_data.html#monthly-data), but with weekly data the frequency should be high enough that the yearly seasonality will be pretty well pinned down and you should have to worry about those issues.
