### ISSUE TITLE
Non-parametric changepoint detection

### ISSUE THREAD

**Issue by luke14free** [facebook/prophet#919]
Hi, I just wanted to share that I was successfully able to integrate non-parametric changepoint detection in my pymc3 version of prophet. I was surprised by how easily it fits even with basic metropolis.

Just in case you are curious about it the relevant code is here:
https://github.com/luke14free/pm-prophet/blob/master/pmprophet/model.py#L233

Have a good week end

**Comment by bletham** [comment]
The example notebook is really cool, thanks for sharing. I'll have to go through the code and check it out.
