### ISSUE TITLE
import error fbprophet

### ISSUE THREAD

**Issue by Zmey56** [facebook/prophet#920]
I am trying to import  fbprophet and i get this error message:

ImportError: /home/USER/anaconda3/lib/python3.6/site-packages/pandas/_libs/../../../../libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/USER/anaconda3/lib/python3.6/site-packages/pandas/_libs/window.cpython-36m-x86_64-linux-gnu.so)

Does anyone can help me solve this problem?

My environment:
Ubuntu : 18.04
python : 3.6.8
pip : 19.0.3
gcc --version : 4.8.5

**Comment by bletham** [comment]
it looks like the error is being raised by pandas, so I'm wondering if it may be something messed up with the pandas installation. Could you try import pandas and see what it does?

**Comment by cofibit** [comment]
Hi @Zmey56 have you found the solution for your issue? I too am getting the same on Ubuntu 18.04

**Comment by bletham** [comment]
@cofibit what happens if you just do
```
import pandas as pd
```
