### ISSUE TITLE
Using Actual Values to Update Forecast

### ISSUE THREAD

**Issue by ahash52** [facebook/prophet#921]
Hi there,

Not sure if this is a prophet question or a general time series question but...

I create my prophet models based on a training and test set (on a monthly basis). My test set goes until 12/2017 and forecasts for months in 2018 and 2019. I get very low MAPEs for each data set. However, if I populate the model with 2018 actuals, I get 2019 forecasts that are very off from actuals; further off than using actual data points up until 12/2017. I would think including "perfect" data would give me more accurate forecasts. Why is that? Does this mean I cannot update my models on a monthly basis with actuals? Or if I do decide to do that, I would have to retune the parameters?

Thanks!

**Comment by bletham** [comment]
I would also generally expect that including more recent data would improve forecasts, but maybe there is something happening in 2018 that is messing up the fit. Would it be possible to include the `m.plot` plots of the forecasts with and without 2018 data? then I might be able to comment on what is happening in 2018 that could be causing issues.
