### ISSUE TITLE
High Variance for First Forecasted Value 

### ISSUE THREAD

**Issue by ahash52** [facebook/prophet#922]
I am running my prophet model on monthly data forecasting out the next 8 months. I am noticing when building out my models the MAPE is low (~3.7%) for the entire 8 months (when comparing to actuals) but much of the MAPE variance is coming from the first forecasted value (~12%). It seems to be way under-forecasting the first value, but forecasting all other future months okay. Any reason why? And I can fix this?
![prophet plot](https://user-images.githubusercontent.com/23070309/55690915-7bbed000-594c-11e9-9aa1-8ae8c666a585.png)

Thanks!

prophet( 
    seasonality.mode = 'multiplicative',
    holidays.prior.scale = .007,
    changepoint.range = .9,
    seasonality.prior.scale = .04,
    changepoint.prior.scale = .16,
    n.changepoints=28,
    yearly.seasonality = 4
  ) %>%
  add_regressor('regressor', mode = 'multiplicative') %>%
  add_regressor('regressor', mode = 'multiplicative') %>%
  add_country_holidays(country_name = 'US') %>%
  fit.prophet(df)

      yhat      y
1 461297.3 525242
2 498762.7 500708
3 523313.4 505759
4 446240.5 446248
5 618981.5 630015
6 862448.2 862530
7 701370.0 680711
8 550155.4 505561

**Comment by bletham** [comment]
Looking at the time series, it does seem to be pretty flat for that month in past months, so I'm wondering if there was something unusual in that month. How does it compare to yhat_lower and yhat_upper? If you post the figure with the forecast plus the validation points then I might be able to comment but I don't have a whole lot to suggest based on the forecast plot, which seems to be pretty fine other than the annual spike in the first few years. Additive seasonality might work better for capturing those peaks.
