### ISSUE TITLE
Regressors not Changing Forecast

### ISSUE THREAD

**Issue by ahash52** [facebook/prophet#925]
Is there a way I can change how much the regressors affect forecasts? It seems that when I use the 'add_regressor' functionality, the regressor is not making any changes to the forecast. Even if I increase the holidays prior scale, I do not see a change in forecast taking place.

**Comment by bletham** [comment]
If you look at the components plot, you will be able to see what the effect of the extra regressor is on the component (like the plot in https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#additional-regressors).

If the extra regressor is not correlated with the time series, it may just not being used much and you'll see very small values in the components plot. The extent to which the regressor is used is fit from the data and there isn't a way to force the forecast to give more weight to a regressor. But make a plot of y vs. the extra regressor and see if they're correlated.

**Comment by ahash52** [comment]
Thank you @bletham. I will keep that in mind when making future models.
