### ISSUE TITLE
External regressor with nonlinear effect on the target variable

### ISSUE THREAD

**Issue by alexgawrilow** [facebook/prophet#929]
Is it possible to create a prophet model, where the target variable `y` has a **non-linear** dependency on some external variable, for example temperature?
I constructed a toy-example, where the temperature for each day is drawn from a normal distribution between -20 and 20 and my target variable depends on the temperature.
Everything works fine if my model has a linear dependency on the temperature, let's say y(t) = temperature(t) + some noise. But if the dependency is non-linear, for example y(t) = abs(temperature(t)) + noise, prophet is not able to predict `y`. In this toy example I avoided to add a trend and seasonal component in the toy data for clarity.
```
from fbprophet import Prophet
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

temp = np.random.uniform(-20, 20, size=2*365)
y_noise = np.random.normal(size=2*365)
y = np.abs(temp) + y_noise

ds = pd.date_range(start="2018-01-01", periods=2*365, freq="d")
df = pd.DataFrame({"ds": ds, "y": y, "temp": temp})
train = df[:365]
test = df[365:]
```
If `y` is plotted on the time axis, the data looks pretty random:
```
train.plot(x="ds", y="y")
plt.show()
```
![1](https://user-images.githubusercontent.com/40760987/56292988-876a7d80-6128-11e9-949a-ab92e85d5aba.png)
But of course the data can be forecasted using the external regressor `temp` as can be seen if `y` is plotted with the external regressor on the x-axis.
```
train.plot.scatter(x="temp", y="y")
plt.show()
```
![2](https://user-images.githubusercontent.com/40760987/56293145-dadccb80-6128-11e9-8440-da8f806af729.png)
The simple prophet model learns some random noise but is not able to correctly forecast the target variable from the external regressor. This can be seen if the forecasted values are plotted together with the actual values over time.
```
m = Prophet()
m.add_regressor("temp")
m.fit(train)
future = test.drop("y", axis=1)
forecast = m.predict(future)

forecast.merge(test, on="ds").plot(x="ds", y=["y", "yhat"])
plt.show()
```
![3](https://user-images.githubusercontent.com/40760987/56294104-a8cc6900-612a-11e9-9db8-86c5c7976d3d.png)
Plotting the forecasted values and the actual values over the external variable shows that the naive prophet model is not able to forecast the target variable given the external regressor.
```
plt.figure()
plt.scatter(x=test["temp"], y=test["y"], label="y")
plt.scatter(x=test["temp"], y=forecast["yhat"], label="yhat")
plt.xlabel("temp")
plt.legend(loc="upper center")
plt.show()
```
![4](https://user-images.githubusercontent.com/40760987/56294962-483e2b80-612c-11e9-8ab7-c43b8c42f302.png)
One workaround would be to split the external regressor into two external regressors: one for temperatures smaller 0 and one for temperatures greater 0. Of course this is only possible in my toy-model since the underlying dependency is known. With real data, where the dependency on the external variable is usually unknown, this is not possible.
```
df["temp_smaller_0"] = df["temp"].apply(lambda x: x if x < 0 else 0)
df["temp_greater_0"] = df["temp"].apply(lambda x: x if x >= 0 else 0)
m.add_regressor("temp_smaller_0")
m.add_regressor("temp_greater_0")
```
Now the model is able to forecast the target variable with the external regressor splitted into two.
![5](https://user-images.githubusercontent.com/40760987/56297773-432fab00-6131-11e9-94d9-611cbb0e0dce.png)
![6](https://user-images.githubusercontent.com/40760987/56297777-462a9b80-6131-11e9-8225-29d5d3aa3694.png)
Is there a good way to train a model with external regressor, where the dependency from the external regressor on the target variable is non-linear? I'm thinking about a piecewise linear function with tunable number of change points similar to the trend component of prophet or some polynomial approximation, where the order of the polynomial can be given and the coefficients are fitted to the data.

**Comment by bletham** [comment]
That isn't currently possible; the model does assume the effect to be either additive or multiplicative, like so:
```
additive:       y(t) = trend(t) + seasonality(t) + beta * regressor(t)
multiplicative: y(t) = (1 + seasonality(t) + beta * regressor(t)) * trend(t)
```
Like you noted, nonlinear relationships would have to be applied prior to model fitting , and then the transformed regressor included in the model.

There unfortunately really isn't a good way right now to incorporate learning the nonlinear function into the model fitting process. The model is specified in both the Stan and the Python so you'd have to go through and make edits in both of them in a few different places.

We are right now working on centralizing the model code to be just in the Stan, so then it should in principle be easier to make these sorts of customizations by just modifying Stan code, and still being able to use the rest of the features in the package. But I think estimating nonlinear functions on top of regressors is probably out of the scope of the main package.
