### ISSUE TITLE
"error: command 'gcc' failed with exit status 1" with pystan 2.19 on travis/docker

### ISSUE THREAD

**Issue by bletham** [facebook/prophet#930]
Installing fbprophet on Travis is currently failing with "error: command 'gcc' failed with exit status 1" when pystan 2.19 is installed. @Gypsying pointed out in #326 that this can is mitigated by setting pystan<=2.18.1.

I'm not able to reproduce this locally yet (on Fedora 29) and am not sure what is the source, or the fix to get it working with pystan 2.19.

**Comment by MGES** [comment]
Do you have  solved this problem?

**Comment by bletham** [comment]
@MGES not yet, still not certain what the issue is.

**Comment by bletham** [comment]
The issue here is that by default travis runs on an old distribution of Ubuntu that uses GCC 4.8.4.

GCC 4.8.4 does not support C++14, and Stan 2.19 requires C++14.

In https://github.com/facebook/prophet/commit/a6a58646869b9e79448e64b308e143be4de26c35 I updated our travis configuration to use Ubuntu Xenial, which uses GCC 5.4.0 and does support C++14. The package now installs without error.

[log.txt](https://github.com/facebook/prophet/files/3175171/log.txt)

**Comment by bletham** [comment]
Resolved

**Comment by dbwiddis** [comment]
Adding a brief note to help others who land here, because this issue helped me as well. I'm stuck on an earlier gcc (4.4.6) and the 2.18.1 version of pystan still gave the same symptoms as above, but 2.14 appears to work.

**Comment by JulioSimon** [comment]
> Adding a brief note to help others who land here, because this issue helped me as well. I'm stuck on an earlier gcc (4.4.6) and the 2.18.1 version of pystan still gave the same symptoms as above, but 2.14 appears to work.

I can confirm that PyStan 2.14 works with earlier gcc (4.*) in the Amazon Linux AMI, in case someone has problems there.
