### ISSUE TITLE
Ability to retrieve data from `plot_components`

### ISSUE THREAD

**Issue by jaskiratr** [facebook/prophet#932]
Hi, is there a recommended way to retrieve plot data from `m.plot_components`?
At the moment, I'm able to extract it as tuple of arrays from the plots that are generated. Just wondering if there is a better approach. Thanks!

```py
lines = m.plot_components(forecast)

# Trend Values
trend = lines.get_axes()[0]
trend.lines[0].get_data()

# Weekly Trend
w_trend = lines.get_axes()[1]
w_trend.lines[0].get_data()

# Daily Trend
d_trend = lines.get_axes()[2]
d_trend.lines[0].get_data()
```

**Comment by bletham** [comment]
That's the best way to extract it from the output of `m.plot_components`, but if your goal is to get each plot separately then they actually all exist as separate functions.

You can see in the code right here how the trend, weekly, and daily component plots are generated: https://github.com/facebook/prophet/blob/master/python/fbprophet/plot.py#L140

Those functions (`plot_forecast_component`, `plot_weekly`, and `plot_yearly`) are in that same file and can be imported from fbprophet.plot.

Each of those functions has a docstring that explains what the arguments are. You can either generate the matplotlib axes on which you want the plot to be created beforehand and pass it in as the `ax` argument, or if you don't pass in the axes it will generate a new matplotlib figure for the plot. It returns the artists objects (not the matplotlib figure object), but you could get it with `plt.gcf()`.

**Comment by jaskiratr** [comment]
Thank you for the input. I'll try it out in some time.
