### ISSUE TITLE
Modify Axis of plot

### ISSUE THREAD

**Issue by snu11** [facebook/prophet#935]
I would like to control the Y axis interval (of trend and season individually) l to better see the result of plot_components.

How Can I do so?

**Comment by bletham** [comment]
`plot_components` returns a matplotlib figure with each component as a child axes. You can access and modify the axes using matplotlib commands, like so
```
fig = m.plot_components(forecast)
fig.get_children()[0].set_ylim([0, 10])
```

You may find it easier to work directly with the functions that generate each component plot. For instance, you can do
```
from fbprophet.plot import plot_weekly
```
and you can pass in a matplotlib axes object that you create and the weekly seasonality plot will be created on that object (for which you could then adjust the ylim as above). You can read about how to do that in the docstring:
https://github.com/facebook/prophet/blob/master/python/fbprophet/plot.py#L243

and the other plotting functions are also all in that same file.
