### ISSUE TITLE
change what plot_plotly() returns

### ISSUE THREAD

**Issue by pysr1** [facebook/prophet#937]
I love the new plot_plotly() function recently added to plots.py. Is there any way a slight change could be made to it to make it more useful.

currently the function returns a plotly offline object (line 651 to 652):  
```
fig = go.Figure(data=data, layout=layout)
return plotly.offline.iplot(fig) 
```

could the function be changed slightly to just return the plotly figure like this:

```
fig = go.Figure(data=data, layout=layout)
return fig 
```

This would: 
* Make it easier to use outside a jupyter notebooks
* Easier to customize 
* Make it capable of being put into dash apps
* Make it easier to upload to plotly

**Comment by Olof-Hojvall** [comment]
Hi, I created that Plotly plot and gave a short comment specifically on what to return in the PR at https://github.com/facebook/prophet/pull/915 . I also saw the advantage of returning the Go figure, but have only used Plotly for notebooks myself so don't have any opinion on what to return myself.

**Comment by pysr1** [comment]
I think the largest advantage to returning the plotly figure instead of the plotly offline object is so that it would make it easier to integrate into a [plotly dash](https://github.com/plotly/dash) app.  

The [Facebook prophet paper](https://peerj.com/preprints/3190.pdf) states :

"Fitting is very fast, allowing the analyst to interactively explore many model specifications, for example in a Shiny application (Chang et al. 2015)."

Many have called dash python's shiny equivalent.  It would be great to be able to easily integrate the plot into a dash app. I think this is the best argument to return the plotly figure.  Either way, thank you for creating the new function!

**Comment by bletham** [comment]
like @Olof-Hojvall , I also only use plotly in a notebook and so didn't have much of an opinion on this either but it does seem like there's value to returning the figure so let's go ahead and make the change. It seems that it would just be one more line to use in a notebook.
