### ISSUE TITLE
Constraining intervals to stay inside specified capacity bounds

### ISSUE THREAD

**Issue by abhinav-kat0ch** [facebook/prophet#943]
If I want to get uncertainty intervals for my predictions, which have a specified upper bound, how can I also constrain the intervals to also stay within those bounds? Adding the columns 'cap' and 'floor' keep the predictions within the range but the intervals tend to fall outside of it. Is there any way of solving this issue? 

Thanks.

**Comment by bletham** [comment]
The floor and cap put bounds only on the trend component (you'll see this in the components plot). Seasonality and the noise term can thus push both yhat and its bounds outside the floor/cap. The best you can do at the moment to keep it inside the bounds is to just clamp yhat, yhat_lower, and yhat_upper to the bounds.
