### ISSUE TITLE
Would you be interested at adding preprocessing steps?

### ISSUE THREAD

**Issue by lovemeblender** [facebook/prophet#944]
Hello and congratulations for this awesome project. 

I was wondering if you would be interested at enlarging the pipeline and add steps such as data validation/cleaning, controls etc. 

If you are, among other things, Nelson rules would be particularly interesting to be added and I would love to help with that.

**Comment by bletham** [comment]
This is related to #647 and #906, which both requested having a box-cox transformation built-in as a preprocessing step.

As discussed in my comment there (https://github.com/facebook/prophet/issues/647#issuecomment-413027578), the difficulty with preprocessing transformations is that makes the forecast components no longer interpretable, which I think is a big plus of the method. So I'm generally not too keen on having a whole lot of transformation happening. If there is a specific transformation that would be generally useful and not impact interpretability then that could be useful, but I think expanding the pipeline to include a lot of other steps is a bit outside the scope of the package.

**Comment by lovemeblender** [comment]
Thank you for your answer :)

The suggested method (i.e. [Nelson rules](https://en.wikipedia.org/wiki/Nelson_rules)) is more of a data quality assurance step so it doesn't interfere with the data. It makes sense that preprocessing might significantly widen the scope of the project and it doesn't do the forecasting per se. 

However, if you feel that a series of quality checks could help (I know several people implementing their own checks in the pipeline before using Prophet including myself) I would be delighted to help!

**Comment by bletham** [comment]
Yeah I think for tests like that it would make sense to have a separate package.
