### ISSUE TITLE
Forecasting multiple items - For loop in Python

### ISSUE THREAD

**Issue by CodeVaris** [facebook/prophet#946]
Hi all!

So Prophet is working great I have to say, but I have many things that I want to use the forecasting from Prophet for. Surprisingly it is very difficult to find a discussion anywhere on how to do this in Python.

I found this the most helpful so far:
https://stackoverflow.com/questions/49237785/forecasting-values-for-each-category-using-prophet-in-python/

It basically forecasts two different items and places them into a Pandas Dataframe. I have no idea how to correctly get it into a CSV/Excel and the answer also isn't provided in the answers there.
As you can see on the right, Pandas drops the ouput from Prophet into a new index row...:

![ProphetIssueOuput](https://user-images.githubusercontent.com/45242630/56848393-bf23b300-68e8-11e9-9d78-7d784cdd7aa8.PNG)

So does anyone have a solution for writing a for loop in Python and then writing the output from Prophet into a CSV or Excel file?

**Comment by bletham** [comment]
The output of `predict` is a pandas dataframe. The easiest way to stitch together many predictions would probably be to just concatenate them with `pandas.concat`. You could do something like this:
```
# Suppose data is in a dictionary from time series name to history dataframe
dfs = {
    'time_series1': df1,
    'time_series2': df2,
    'time_series3': df3,
}
# Loop through all time series and make forecasts
fcst_all = pd.DataFrame()  # store all forecasts here
for name, df in dfs.items():
    m = Prophet().fit(df)
    fcst = m.predict(future)
    fcst['time_series_name'] = name  # Add this to the dataframe to keep track of which forecast is which
    fcst_all = pd.concat((fcst_all, fcst))

fcst_all.to_csv('all_forecasts.csv', index=False)
```

**Comment by CodeVaris** [comment]
Thank you very much!!

**Comment by ELEUCHI** [comment]
jjh

**Comment by ELEUCHI** [comment]
Hello,
how can i fit prophet model and make prediction with multiple dataframe ?

**Comment by johnnykahits** [comment]
Hi, I'm working on a model like this. How do you measure the accuracy of the model?
