### ISSUE TITLE
Data changed from 7 days a week to weekdays only.

### ISSUE THREAD

**Issue by viviminghsieh** [facebook/prophet#952]
Our data has 7 days data per week historically. however, the business changed recently and only operates on weekdays now. Any suggestions how to forecast data like this?

Thanks!
[daily_18.xlsx](https://github.com/facebook/prophet/files/3136348/daily_18.xlsx)

**Comment by maneeshdisodia** [comment]
just take 5-day data only. I have the same problem back, by eliminating Saturday and Sunday from my historical data, I get a good forecast with high confidence. and also make sure to forecast, only on a forecasted data frame with similar interval dates. like 
`0        2019-04-25
1         2019-04-26
2         2019-04-29
3         2019-04-30
4         2019-05-01
5         2019-04-25
6         2019-04-26
7         2019-04-29
8         2019-04-30
9         2019-05-01
10        2019-04-25
11        2019-04-26
12        2019-04-29
13        2019-04-30`

**Comment by bletham** [comment]
+1 for @maneeshdisodia's answer. The only thing I'd be careful of here is that the change from daily to weekdays-only could plausibly change the nature of the weekly seasonality. For instance maybe customers that previously came Sat or Sun are now more likely to come on Friday. Prophet assumes constant seasonality, so if there is a significant change in seasonality it will hurt performance. You can look at the M-F seasonality before/after the change and make sure they're consistent.

Other than that, just be sure to read the documentation here https://facebook.github.io/prophet/docs/non-daily_data.html#data-with-regular-gaps for a few considerations of data with regular gaps like this.

**Comment by viviminghsieh** [comment]
Thank you for both of your replies.
I tried to plot the M-F seasonality after the change. I have 5 weeks data after the change. However, I got **"Error in FUN(X[[i]], ...) : object 'trend' not found"** when using prophet_plot_components(). 

How can I plot the seasonality with data after the change? Thanks!

**Comment by bletham** [comment]
You have to pass in a dataframe of forecasts to `prophet_plot_components` (the output of `predict`), I'm guessing you just passed in a dataframe of the data.

You could fit a model to the whole time series, make a prediction on the dates in the history, and then compare model y_hat to actual y and see if you are systematically under/over forecasting on particular days of the week, before and after the change. In the scenario I posed above, you might find that after the change y_hat is consistently much less than y after the change. If there isn't a correlation between errors and day-of-week, then you're probably OK.

You could also fit separate models for data before/after the change and then compare the seasonalities in each of those models. If feasible, it'd be best to enable MCMC for this comparison (so you can see the uncertainty in the seasonality).
