### ISSUE TITLE
how to predict thousands or millions of related time series

### ISSUE THREAD

**Issue by tangyong** [facebook/prophet#953]
From "DeepAR: Probabilistic Forecasting with Autoregressive Recurrent Networks" as follows:

"In recent years, a new type of forecasting problem has become increasingly important in many applications.Instead of needing to predict individual or a small number of time series, one is faced with forecasting thousands or millions of related time series."

So, I want to ask how to handle the above case using  prophet?

Thanks!

**Comment by bletham** [comment]
There isn't currently any functionality for multivariate forecasting like this (#49 is the open issue).

I do have a comment in that issue (here: https://github.com/facebook/prophet/issues/49#issuecomment-430383681) about how if you are trying to forecast a bunch of demographic subgroups from some total then there is a way to do that using extra regressors, but that's the closest functionality there is for predicting related time series.

**Comment by tangyong** [comment]
Thanks reply!  I will close this issue and come back #49
