### ISSUE TITLE
'prophet' object has no attribute 'seasonality_plot_df'

### ISSUE THREAD

**Issue by caoyc001** [facebook/prophet#955]
I run the data according to the example of this website.
https://www.aquaq.co.uk/datablog/time-series-machine-learning-uk-crime-statistics/
code show as below：
 seasonalTrend['y'] = m.predict_seasonal_components(m.seasonality_plot_df(seasonalTrend['month']))['yearly']
Then I got this error：'prophet' object has no attribute 'seasonality_plot_df'
Is this example wrong, or what other causes this problem?

**Comment by bletham** [comment]
That was using an older version of fbprophet and that method was moved. You can now get it from
```
from fbprophet.plot import seasonality_plot_df
```

**Comment by rachellsivan** [comment]
hi, I got the same problem as you, did you fix it yet?

**Comment by SaM-92** [comment]
I have the same issue here as well! :)  Could you fix it @rachellsivan ? 

'AttributeError: 'Prophet' object has no attribute 'seasonality_plot_df''
