### ISSUE TITLE
A known pattern for only on day of the week

### ISSUE THREAD

**Issue by ChaymaeHarfoush** [facebook/prophet#956]
I have a **Known pattern for Fridays** of a time series.
And the series have a dominated daily pattern.
**While forecasting; the Friday pattern isn't shown it's shown as a normal day**, while setting weekly and daily seasonality to true
Is there a solution to deal with Fridays with different method?

**Comment by bletham** [comment]
I don't fully understand the issue. Let me know if this is correct:

You have a time series with sub-daily data. There is daily seasonality on each day. The daily seasonality is different on Friday than on other days, and you want to model it differently.

Is that correct? By "known" do you mean you know the actual shape of the seasonality on Friday? Do you know it for other days too?
