### ISSUE TITLE
Is int-type prediction supported?

### ISSUE THREAD

**Issue by 4thfever** [facebook/prophet#959]
Hello, 

I'm new to fbprophet so sorry at first if I pose a stupid question.
My question is that, is integer type input and output with certain range supported by fbprophet?
For ex, I have a dataset like:
ds    y
ds1  0
ds2  2
ds3  1
ds4  3
ds5  0
Can I have a good result using prophet? I tried on prophet but get only result like 1.45647.

Thanks a lot!

**Comment by bletham** [comment]
No, the underlying model assumes additive Gaussian noise, so float.

If your ints are large enough then rounding would probably work just fine, but for small values like these I don't expect the model to perform well. 

What is needed for this is the Poisson or Negative Binomial likelihood in #337, which is in progress but there are some challenges there so it will still be some time before that's ready.

**Comment by 4thfever** [comment]
Thanks a lot @bletham  It's nice to have your answer, I will try Pytorch for my program.

**Comment by engineeryashsaxena** [comment]
@bletham Are there any updates regarding considering  Poisson or Negative Binomial likelihood ?

**Comment by bletham** [comment]
@engineeryashsaxena I added a comment to #337, which I realized I had never updated after implementing a NB likelihood last summer. The short answer is that the NB likelihood came with a lot of numerical issues and so I don't expect it to ever be a broadly useful tool. My comment in #337 links to the PR with the likelihood that you can patch if you'd like to try it out, and it also links to two other issues that provide discussion for what the issues were and some alternative approaches.
