### ISSUE TITLE
StanModel' object has no attribute 'fit_class'

### ISSUE THREAD

**Issue by TaurusYin** [facebook/prophet#960]
![image](https://user-images.githubusercontent.com/5126301/57377789-deb6b780-71d5-11e9-9886-cd38c77d1c4b.png)

Hello,

I got the same problem and previously I check the previous solution in terms of reinstalling the prophet/numpy/.. package but still failed.

The environment is our internal FC system just like a docker environment. I use pip install -t . to package all the useful dependencies into the FC system and then get the problem. 

I found pystan will produce the C++ stanmodel in the /tmp folder, but it looks like prophet failed to load the module. I am not sure why the model name is unique(make it different by unix time) 
The problem is related to the GCC environment or something? Could you please give some hint?

**Comment by bletham** [comment]
Are you seeing this messages during pip install?

Can you check that pystan is working properly? Run this code:
```
import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this will take a minute
y = model.sampling(n_jobs=1).extract()['y']
y.mean()  # should be close to 0
```
