### ISSUE TITLE
Some Prophet functionality and diagnostics not available in RStudio

### ISSUE THREAD

**Issue by MelvinUpton** [facebook/prophet#961]
Some Prophet functions like cross_validation and add_seasonality not working in RStudio (Error: could not find function "cross_validation"). Do I need an updated version of R/RStudio to access these functions? 

Note: the model fitting process works

**Comment by bletham** [comment]
Can you check what version of prophet you have installed?
```
library(prophet)
sessionInfo()
```

**Comment by MelvinUpton** [comment]
I see now that the Prophet package is out of date (0.1). I was confused because RStudio returned that the package was up-to-date, however, I believe that I may have missed some of the installation procedure when I installed the package which has limited the functionality.
