### ISSUE TITLE
why does it return 0? not show the fig?

### ISSUE THREAD

**Issue by whykid83** [facebook/prophet#962]
import pandas as pd
from fbprophet import Prophet
from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()

url= 'https://raw.githubusercontent.com/facebook/prophet/master/examples/example_wp_log_peyton_manning.csv'

df = pd.read_csv(url)
df.head()

m = Prophet()
m.fit(df)

future = m.make_future_dataframe(periods=365)

forecast = m.predict(future)
forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()

fig1 = m.plot(forecast)

**Comment by whykid83** [comment]
it was solved in
#83

**Comment by AlanJoseTom** [comment]
After this line of code 
fig1 = m.plot(forecast)
please add 
plt.show(dont forget to import matplotlib.pyplot )
