### ISSUE TITLE
Logistic Regression Producing Zero Trend

### ISSUE THREAD

**Issue by danielrobinson1** [facebook/prophet#964]
Hi,

I'm occasionally running into this issue when using the logistic growth model, where the trend component is returned as zero (or very close to zero):

<img width="451" alt="dyplot" src="https://user-images.githubusercontent.com/7037391/57528805-3155b800-732b-11e9-88a7-f87a74249dcb.PNG">

![components](https://user-images.githubusercontent.com/7037391/57528814-34e93f00-732b-11e9-9351-605246a58589.png)

The code I'm using is the following (in R):

inputdata$cap   <- 1
inputdata$floor <- 0
m               <- prophet(inputdata, growth = 'logistic', changepoint.prior.scale = 0.1)
future          <- make_future_dataframe(m, periods = 1, freq = 'week')
future$cap      <- 1
future$floor    <- 0
forecast        <- predict(m, future) 

Most of the time this code works fine for me but a couple of times out of 100 I run into this issue. I've never seen this with the Linear growth model. Sorry if this has been raised before. Is it something I'm doing wrong?

**Comment by bletham** [comment]
That's certainly a bad fit, any chance you could attach the data so I could look at it more closely?

**Comment by danielrobinson1** [comment]
Sure, attached. Thanks Ben

[input_data.zip](https://github.com/facebook/prophet/files/3181510/input_data.zip)

**Comment by bletham** [comment]
It looks like the L-BFGS optimizer used to fit the model is just really having a hard time here. I'm not exactly sure why. The initial values for the parameters look pretty good, but then the optimizer takes a bad step early on and gets stuck. Usually when this happens it would terminate abnormally and then we'd fall back to another optimizer, but in this case it's actually terminating normally.

I'm not really sure why L-BFGS is failing so badly here, but the other Stan optimizers (Newton and BFGS) seem to not have the same problem. You can get a much more reasonable fit here by doing:
```
m <- prophet(growth = 'logistic', changepoint.prior.scale = 0.1, algorithm='Newton')
```

The Newton optimizer is a bit slower than L-BFGS, but tends to be a bit more robust, and seems to work better here.

**Comment by danielrobinson1** [comment]
Thanks for the reply Ben, I'll give that a try.

**Comment by jdeboer** [comment]
I wasn't encountering this issue before, but for some reason it has now started although I didn't make any changes to my code. However, setting `algorithm='Newton'` has resolved the problem for me.
