### ISSUE TITLE
fable interface to the prophet model

### ISSUE THREAD

**Issue by mitchelloharawild** [facebook/prophet#966]
The [fable package for R](https://fable.tidyverts.org/) implements a tidy interface for time series forecasting using [tsibble](https://tsibble.tidyverts.org/) tidy temporal data.

It would be great if an interface to the prophet library could be added to this framework as it would allow for:

* Seamless integration with data manipulation and visualisation tools from the tidyverse
* Batch forecasting for many time series with (soon to be added) parallel support (#49, #625)
* Transformations with automatic back-transformation of forecasts (#647, #492)
* Accuracy evaluation tools (in-sample, out-of-sample, and cross validation) (#786)
* Consistent formula interface with other tidy forecasting models
* Support for ensemble modelling and other combination model classes (such as decomposition forecasting)
* (Soon to be added) support for hierarchical and grouped reconciliation of forecasts

I expect that this would be better implemented as a second package that calls either the R or python version of prophet. I've put together a prototype that wraps the python version (although it is probably better to wrap R instead) and it seems to work nicely. Keeping things separate is preferable to avoid conflicts in function names, and as this feature would be available to R users only (a python version of fable is not implemented or planned).

**Comment by bletham** [comment]
That sounds really cool, do keep us posted here how it's going! I agree that it sounds like a second package on top would make the most sense here.

**Comment by bletham** [comment]
And if there are interface adjustments on the Prophet side you need, definitely let us know.

**Comment by mitchelloharawild** [comment]
Great - I've made the repo public. The documentation still needs improving, but if you could have a look through the README and let me know what think that would be very helpful.
https://github.com/mitchelloharawild/fable.prophet

The only change that would make compatibility between fable and prophet easier would be extending the simulation method to accept a vector of innovations (https://github.com/mitchelloharawild/fable.prophet/issues/4).

**Comment by bletham** [comment]
I'm not totally sure what you mean. Is it this function: 
https://github.com/facebook/prophet/blob/b0c30454b6111a4a64763999823d3b2630f4196a/R/R/prophet.R#L1473

and what would the better signature look like?

**Comment by mitchelloharawild** [comment]
Yes - that's the one. The signature in fable.prophet would be very similar: `generate.prophet <- function(x, new_data, ...)`, where `x` is the model and `new_data` are the times to generate data for. However fable also allows you to specify your own vector of innovations/errors (via the ".innov" column in `new_data`, but this may not be the best approach). This is important as it allows you to compute intervals from bootstrap sampled innovations.

Essentially allowing a user specified vector which would replace `rnorm()` if specified would be useful:
https://github.com/facebook/prophet/blob/b0c30454b6111a4a64763999823d3b2630f4196a/R/R/prophet.R#L1569

**Comment by bletham** [comment]
Could you explain what is meant by a vector of innovations? I'm not familiar with that terminology. The normal errors are assumed in the likelihood function with which model parameters are fit and so it seems like a potential issue to replace them post-fit.

**Comment by mitchelloharawild** [comment]
Innovations are prediction errors - the 1-step-ahead residuals of your fitted model. From what I can tell, you obtain some appropriate noise level from Stan and use that to sample normal errors from the distributional assumption. It is useful to additionally allow user defined vectors of errors (rather than sampling them). A common usage of this would be to instead use sampled errors (bootstrapped) from the model's residuals rather than sampling new values from the normal distribution. This can be useful when the innovations/prediction errors/residuals are not normally distributed, as uncertainty for intervals would then be measured by the historical errors (rather than a normal distribution). More details in the _Prediction intervals from bootstrapped residuals_ section of https://otexts.com/fpp3/prediction-intervals.html

I agree that it's usually a bad idea to replace model parameters post-fit, but this is not what this change would do. Instead it allows more control over the way in which uncertainty is represented in the residuals.

**Comment by mitchelloharawild** [comment]
I've now converted the `fable.prophet` package to use the R version of `prophet`. In doing so I'm no longer able to simulate intervals directly because some functions aren't exported.
https://github.com/mitchelloharawild/fable.prophet/blob/c8d5e5b9031a961a6b9ab0b0ff2d866402a35e1d/R/model.R#L234-L240

If there's some nice way to directly simulate future paths, then it would be possible to add the simulated distributions back.

**Comment by bletham** [comment]
If it's a matter of exporting, could calling `prophet:::sample_posterior_predictive` work?

**Comment by mitchelloharawild** [comment]
I've looked around a bit further and it seems that `prophet::predictive_samples` is what I'm looking for here. 

It would still be nice to allow a vector of noise as inputs for here (and consequently, as an argument of `prophet::predictive_samples`):
https://github.com/facebook/prophet/blob/b0c30454b6111a4a64763999823d3b2630f4196a/R/R/prophet.R#L1569

**Comment by jaredlander** [comment]
@bletham cran doesn't like using `:::` to use unexported functions. It looks like @mitchelloharawild found a different solution, but wanted to get that out there for future issues.

**Comment by mitchelloharawild** [comment]
@bletham 
There has been one issue preventing upload to CRAN for a while now.
Any package examples using prophet seem to take a long time to run on win-builder.
It seems all examples in this package are within `\dontrun{}`, which the CRAN maintainers don't like.

How did you go about submitting this package to CRAN without examples?

**Comment by bletham** [comment]
@mitchelloharawild Every time we push to CRAN we end up with some new set of issues for win-builder.. @seanjtaylor takes the brunt of that and would the person who knows.

**Comment by mitchelloharawild** [comment]
Great, thanks. I'll persist with CRAN and see how it goes. The main issue is the lack of minimal examples due to long estimation times on win-builder. Are you aware of any performance issues on the win-builder setup?

**Comment by jaredlander** [comment]
Looping in @jgabry who probably has a lot of experience with that.

**Comment by mitchelloharawild** [comment]
Thanks @jaredlander - I recall looking into the prophet and not seeing anything that would slow execution to the extremes seen on win-builder, so perhaps it is an issue with win-builder and (r)stan.

**Comment by jaredlander** [comment]
Could be something with the makeconf (or something like that if I'm misremembering)? I know that has caused issues for Stan but I have no basis other than that. Hopefully @jgabry knows.

**Comment by mitchelloharawild** [comment]
Closing as [{fable.prophet}](http://pkg.mitchelloharawild.com/fable.prophet/) is now on CRAN :tada:

**Comment by bletham** [comment]
Congratulations!
