### ISSUE TITLE
Handling lot of timeseries datasets

### ISSUE THREAD

**Issue by mukunthanviznxt** [facebook/prophet#967]
Hi, 
    I am having  around 700 datasets for univariate timeseries forecasting.
Some of timeseries datasets have similar pattern and some others have different pattern.   
 Should I concentrate training prophet in each and every dataset? or is there any other possibility like getting one trained prophet model and applying that for all other datasets?

Thanks
Mukunthan R

**Comment by vhpietil** [comment]
If your datasets have long enough history, you should train each model separately. I don't think you could train model with one dataset and apply it to another dataset.

**Comment by mukunthanviznxt** [comment]
Hi vhpietil, 
      Thanks for response. What I observed from taking a dataset and modeling is,  
the trend changepoint.prior.scale changing from 0.001to 0.002 will produce good result in one dataset and for other dataset, I need to check from 0.001 to all possibilities upto 0.4. 
This requires setting large range of values for grid search,some other datasets are seasonal and it is somewhat manual task.
 Is there any automated way of hyperparameter tuning in prophet so that I can apply to all of my 700 datasets?

**Comment by vhpietil** [comment]
There is no automated hyperparameter tuning in prophet.
