### ISSUE TITLE
Make release 0.5 (python) available on github

### ISSUE THREAD

**Issue by Froskekongen** [facebook/prophet#968]
I discovered version 0.5 was available on pypi. It would be great to have the same release on github along with a changelog.

**Comment by davedgd** [comment]
@Froskekongen: I echo the request for an updated changelog with this release, given that the current readme.md on GitHub only covers up to 0.4: 

https://github.com/facebook/prophet/blob/master/README.md#version-04-20181218

It would also be great to have changelogs available in other locations as well if possible (e.g., on CRAN there is no changelog [news.html] posted for the R version: https://cran.r-project.org/web/packages/prophet/index.html).

Regarding the pypi release vs. availability on GitHub, it seems to me the Python source code is available on GitHub under the python folder (with the R version under its respective folder as well):

https://github.com/facebook/prophet/tree/master/python

**Comment by bletham** [comment]
The release process can take a few days (conda-forge build, building CRAN binaries - actually still ongoing, rebuild docs,...) so you beat us too it :-) The release has now been tagged and #978 describes the main changes.
