### ISSUE TITLE
how to predict time series with one hour period

### ISSUE THREAD

**Issue by smeilence** [facebook/prophet#971]
my data with one hour period ，use the default param cannot predict well . Can I change same param to fit the model  better when predict data  with short period

**Comment by smeilence** [comment]
@bletham

**Comment by bash-j** [comment]
Have you followed the documentation example?

https://facebook.github.io/prophet/docs/non-daily_data.html#sub-daily-data

Notice the freq parameter for make_future_dataframe

**Comment by bletham** [comment]
By period you mean you have data points for every hour? Or your time series only lasts for an hour? If you post the plot generated by `m.plot(forecast)` that would be very helpful for helping to give some tips on what might be happening.

**Comment by smeilence** [comment]
@bletham Thanks for your reply ，my description is not clear enough， I mean now I have one minute interval data points，the time series lasts for 24 hours ，but this data‘s seasonlity is about 1 hour or shorter，so Daily seasonlity and  Weekly seasonality cannot be used ， can I set a Customized seasonlity like one hour？

**Comment by bletham** [comment]
Yes, if you have a seasonal fluctuation with a period of 1 hr then there shouldn't be any issue in using a custom seasonality with period 1/24.
