### ISSUE TITLE
ValueError: Wrong number of items passed 3270, placement implies 26.

### ISSUE THREAD

**Issue by vsagar8888** [facebook/prophet#973]
I am getting below error while executing the line "forecast = m.predict(future)" in the given link
https://facebook.github.io/prophet/docs/quick_start.html 

versions used:
import numpy
numpy.version
'1.16.0'
import fbprophet
fbprophet.version
'0.4'

ValueError Traceback (most recent call last)
in ()
----> 1 forecast = m.predict(future)

/sys_apps_01/python/python342/lib/python3.4/site-packages/fbprophet/forecaster.py in predict(self, df)
1144 df['trend'] = self.predict_trend(df)
1145 seasonal_components = self.predict_seasonal_components(df)
-> 1146 intervals = self.predict_uncertainty(df)
1147
1148 # Drop columns except ds, cap, floor, and trend

/sys_apps_01/python/python342/lib/python3.4/site-packages/fbprophet/forecaster.py in predict_uncertainty(self, df)
1346 Dataframe with uncertainty intervals.
1347 """
-> 1348 sim_values = self.sample_posterior_predictive(df)
1349
1350 lower_p = 100 * (1.0 - self.interval_width) / 2

/sys_apps_01/python/python342/lib/python3.4/site-packages/fbprophet/forecaster.py in sample_posterior_predictive(self, df)
1310 iteration=i,
1311 s_a=component_cols['additive_terms'],
-> 1312 s_m=component_cols['multiplicative_terms'],
1313 )
1314 for key in sim_values:

/sys_apps_01/python/python342/lib/python3.4/site-packages/fbprophet/forecaster.py in sample_model(self, df, seasonal_features, iteration, s_a, s_m)
1378
1379 beta = self.params['beta'][iteration]
-> 1380 Xb_a = np.matmul(seasonal_features.values, beta * s_a) * self.y_scale
1381 Xb_m = np.matmul(seasonal_features.values, beta * s_m)
1382

/sys_apps_01/python/python342/lib/python3.4/site-packages/pandas/core/series.py in array_wrap(self, result, context)
502 """
503 return self._constructor(result, index=self.index,
--> 504 copy=False).finalize(self)
505
506 def array_prepare(self, result, context=None):

/sys_apps_01/python/python342/lib/python3.4/site-packages/pandas/core/series.py in init(self, data, index, dtype, name, copy, fastpath)
264 raise_cast_failure=True)
265
--> 266 data = SingleBlockManager(data, index, fastpath=True)
267
268 generic.NDFrame.init(self, data, fastpath=True)

/sys_apps_01/python/python342/lib/python3.4/site-packages/pandas/core/internals.py in init(self, block, axis, do_integrity_check, fastpath)
4395 if not isinstance(block, Block):
4396 block = make_block(block, placement=slice(0, len(axis)), ndim=1,
-> 4397 fastpath=True)
4398
4399 self.blocks = [block]

/sys_apps_01/python/python342/lib/python3.4/site-packages/pandas/core/internals.py in make_block(values, placement, klass, ndim, dtype, fastpath)
2950 placement=placement, dtype=dtype)
2951
-> 2952 return klass(values, ndim=ndim, fastpath=fastpath, placement=placement)
2953
2954 # TODO: flexible with index=None and/or items=None

/sys_apps_01/python/python342/lib/python3.4/site-packages/pandas/core/internals.py in init(self, values, placement, ndim, fastpath)
118 raise ValueError('Wrong number of items passed %d, placement '
119 'implies %d' % (len(self.values),
--> 120 len(self.mgr_locs)))
121
122 @Property

ValueError: Wrong number of items passed 3270, placement implies 26.

Will this issue is solved by upgrading fbprophet version or it is different issue ?

**Comment by vsagar8888** [comment]
@bletham, could you please look into this ?

**Comment by lmerchante** [comment]
Hi vsagar8888, I don't know if this helps, I got similar error and fixed it upgrading holidays, numpy and pyparsing. This is the sequence:

pip install fbprophet==0.4 --upgrade
pip install holidays==0.9.8 --upgrade
pip install numpy==1.15.4 --upgrade
pip install pyparsing==2.3.0 –upgrade

This is the complete list of versiones that makes it work for me:

fbprophet==0.4
  - convertdate [required: >=2.1.2, installed: 2.1.3]
    - ephem [required: >=3.7.5.3,<3.8, installed: 3.7.6.0]
    - pytz [required: >=2014.10,<2020, installed: 2019.1]
  - Cython [required: >=0.22, installed: 0.29.7]
  - holidays [required: >=0.9.5, installed: 0.9.10]
    - python-dateutil [required: Any, installed: 2.8.0]
      - six [required: >=1.5, installed: 1.12.0]
    - six [required: Any, installed: 1.12.0]
  - lunardate [required: >=0.1.5, installed: 0.2.0]
  - matplotlib [required: >=2.0.0, installed: 2.2.3]
    - backports.functools-lru-cache [required: Any, installed: 1.5]
    - cycler [required: >=0.10, installed: 0.10.0]
      - six [required: Any, installed: 1.12.0]
    - kiwisolver [required: >=1.0.1, installed: 1.1.0]
      - setuptools [required: Any, installed: 41.0.1]
    - numpy [required: >=1.7.1, installed: 1.16.3]
    - pyparsing [required: >=2.0.1,!=2.1.6,!=2.1.2,!=2.0.4, installed: 2.4.0]
    - python-dateutil [required: >=2.1, installed: 2.8.0]
      - six [required: >=1.5, installed: 1.12.0]
    - pytz [required: Any, installed: 2019.1]
    - six [required: >=1.10, installed: 1.12.0]
    - subprocess32 [required: Any, installed: 3.5.3]
  - numpy [required: >=1.10.0, installed: 1.16.3]
  - pandas [required: >=0.20.1, installed: 0.24.2]
    - numpy [required: >=1.12.0, installed: 1.16.3]
    - python-dateutil [required: >=2.5.0, installed: 2.8.0]
      - six [required: >=1.5, installed: 1.12.0]
    - pytz [required: >=2011k, installed: 2019.1]
  - pystan [required: >=2.14, installed: 2.19.0.0]
    - Cython [required: >=0.22,!=0.25.1, installed: 0.29.7]
    - numpy [required: >=1.7, installed: 1.16.3]

**Comment by vsagar8888** [comment]
@lmerchante, thanks for the comment. But I am using numpy version: 1.16.0 , I am not sure this is causing problem with fbprophet version: 0.4

**Comment by lmerchante** [comment]
I was also using 1.16, but I read this: https://github.com/facebook/prophet/issues/808 and had a try.

**Comment by bletham** [comment]
You would need to be sure to get the post-release (fbprophet==0.4.post2). But, we just pushed v0.5 and so the surest way to be sure you have the fix is to re-install fbprophet and make sure you have v0.5.
