### ISSUE TITLE
Multivariate time series in Prophet?

### ISSUE THREAD

**Issue by playma** [facebook/prophet#975]
Will Prophet work for multivariate time series?

**Comment by bletham** [comment]
There's discussion of this in #49. In short, there is no support for multivariate time series, however if you have a situation where there is a top-level thing you want to forecast along with demographic subgroups, then you can try what is described in this comment: https://github.com/facebook/prophet/issues/49#issuecomment-430383681

**Comment by playma** [comment]
@bletham Thanks
