### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by supreme-core** [facebook/prophet#976]
**Running pip3 install yields:**

=======================================================================
Collecting fbprophet
  Downloading https://files.pythonhosted.org/packages/33/fb/ad98d46773929079657706e6b2b6e366ba6c282bc2397d8f9b0ea8e5614c/fbprophet-0.5.tar.gz (49kB)
    100% |████████████████████████████████| 51kB 979kB/s 
Requirement already satisfied: Cython>=0.22 in /usr/local/lib/python3.7/dist-packages (from fbprophet) (0.29.7)
Requirement already satisfied: pystan>=2.14 in /usr/local/lib/python3.7/dist-packages (from fbprophet) (2.19.0.0)
Requirement already satisfied: numpy>=1.10.0 in /usr/local/lib/python3.7/dist-packages (from fbprophet) (1.16.2)
Requirement already satisfied: pandas>=0.23.4 in /usr/local/lib/python3.7/dist-packages (from fbprophet) (0.24.2)
Requirement already satisfied: matplotlib>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from fbprophet) (3.0.3)
Requirement already satisfied: lunardate>=0.1.5 in /usr/local/lib/python3.7/dist-packages (from fbprophet) (0.2.0)
Collecting convertdate>=2.1.2 (from fbprophet)
  Downloading https://files.pythonhosted.org/packages/74/83/d0fa07078f4d4ae473a89d7d521aafc66d82641ea0af0ef04a47052e8f17/convertdate-2.1.3-py2.py3-none-any.whl
Collecting holidays>=0.9.5 (from fbprophet)
  Downloading https://files.pythonhosted.org/packages/16/09/c882bee98acfa310933b654697405260ec7657c78430a14e785ef0f1314b/holidays-0.9.10.tar.gz (73kB)
    100% |████████████████████████████████| 81kB 6.9MB/s 
Collecting setuptools-git>=1.2 (from fbprophet)
  Downloading https://files.pythonhosted.org/packages/05/97/dd99fa9c0d9627a7b3c103a00f1566d8193aca8d473884ed258cca82b06f/setuptools_git-1.2-py2.py3-none-any.whl
Requirement already satisfied: pytz>=2011k in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23.4->fbprophet) (2018.9)
Requirement already satisfied: python-dateutil>=2.5.0 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23.4->fbprophet) (2.8.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.0.0->fbprophet) (1.0.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.0.0->fbprophet) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.0.0->fbprophet) (2.4.0)
Collecting ephem<3.8,>=3.7.5.3 (from convertdate>=2.1.2->fbprophet)
  Downloading https://files.pythonhosted.org/packages/c3/2c/9e1a815add6c222a0d4bf7c644e095471a934a39bc90c201f9550a8f7f14/ephem-3.7.6.0.tar.gz (739kB)
    100% |████████████████████████████████| 747kB 13.8MB/s 
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from holidays>=0.9.5->fbprophet) (1.12.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from kiwisolver>=1.0.1->matplotlib>=2.0.0->fbprophet) (40.6.3)
Installing collected packages: ephem, convertdate, holidays, setuptools-git, fbprophet
  Running setup.py install for ephem ... error
    Complete output from command /usr/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-6ccy1f3a/ephem/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-0hvyysgo/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/ephem
    copying ephem/cities.py -> build/lib.linux-x86_64-3.7/ephem
    copying ephem/__init__.py -> build/lib.linux-x86_64-3.7/ephem
    copying ephem/stars.py -> build/lib.linux-x86_64-3.7/ephem
    creating build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_stars.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_dates.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_constants.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_satellite.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_jpl.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_launchpad_244811.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_cities.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_rst.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_usno_equinoxes.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/__init__.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_angles.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_usno.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_bodies.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_github_issues.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_locales.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_observers.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_launchpad_236872.py -> build/lib.linux-x86_64-3.7/ephem/tests
    creating build/lib.linux-x86_64-3.7/ephem/doc
    copying ephem/doc/faq.rst -> build/lib.linux-x86_64-3.7/ephem/doc
    copying ephem/doc/angle.rst -> build/lib.linux-x86_64-3.7/ephem/doc
    copying ephem/doc/newton.rst -> build/lib.linux-x86_64-3.7/ephem/doc
    copying ephem/doc/coordinates.rst -> build/lib.linux-x86_64-3.7/ephem/doc
    copying ephem/doc/catalogs.rst -> build/lib.linux-x86_64-3.7/ephem/doc
    copying ephem/doc/reference.rst -> build/lib.linux-x86_64-3.7/ephem/doc
    copying ephem/doc/index.rst -> build/lib.linux-x86_64-3.7/ephem/doc
    copying ephem/doc/date.rst -> build/lib.linux-x86_64-3.7/ephem/doc
    copying ephem/doc/tutorial.rst -> build/lib.linux-x86_64-3.7/ephem/doc
    copying ephem/doc/CHANGELOG.rst -> build/lib.linux-x86_64-3.7/ephem/doc
    copying ephem/doc/radec.rst -> build/lib.linux-x86_64-3.7/ephem/doc
    copying ephem/doc/rise-set.rst -> build/lib.linux-x86_64-3.7/ephem/doc
    copying ephem/doc/examples.rst -> build/lib.linux-x86_64-3.7/ephem/doc
    copying ephem/doc/quick.rst -> build/lib.linux-x86_64-3.7/ephem/doc
    creating build/lib.linux-x86_64-3.7/ephem/tests/jpl
    copying ephem/tests/jpl/oberon.txt -> build/lib.linux-x86_64-3.7/ephem/tests/jpl
    copying ephem/tests/jpl/mars.txt -> build/lib.linux-x86_64-3.7/ephem/tests/jpl
    copying ephem/tests/jpl/phobos.txt -> build/lib.linux-x86_64-3.7/ephem/tests/jpl
    copying ephem/tests/jpl/uranus.txt -> build/lib.linux-x86_64-3.7/ephem/tests/jpl
    copying ephem/tests/jpl/saturn.txt -> build/lib.linux-x86_64-3.7/ephem/tests/jpl
    copying ephem/tests/jpl/neptune.txt -> build/lib.linux-x86_64-3.7/ephem/tests/jpl
    copying ephem/tests/jpl/hyperion.txt -> build/lib.linux-x86_64-3.7/ephem/tests/jpl
    copying ephem/tests/jpl/europa.txt -> build/lib.linux-x86_64-3.7/ephem/tests/jpl
    copying ephem/tests/jpl/jupiter.txt -> build/lib.linux-x86_64-3.7/ephem/tests/jpl
    creating build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/risettran_moon.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/riset_sun.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/astrom_antares.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/apptopo_deneb.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/moon_phases.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/riset_moon.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/astrom_mercury.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/apptopo_moon.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/appgeo_sun.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/appgeo_jupiter.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/astrom_neptune.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/risettran_rigel.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/appgeo_deneb.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/appgeo_moon.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/apptopo_sun.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    running build_ext
    building 'ephem._libastro' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/extensions
    creating build/temp.linux-x86_64-3.7/libastro-3.7.6
    creating build/temp.linux-x86_64-3.7/extensions/data
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Ilibastro-3.7.6 -I/usr/include/python3.7m -c extensions/_libastro.c -o build/temp.linux-x86_64-3.7/extensions/_libastro.o
    x86_64-linux-gnu-gcc: error trying to exec 'cc1': execvp: No such file or directory
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-6ccy1f3a/ephem/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-0hvyysgo/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-6ccy1f3a/ephem/
You are using pip version 18.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command

**Comment by supreme-core** [comment]
I tried to run pystan script outside of fbprophet as per instruction on 
https://github.com/facebook/prophet/issues/346#issuecomment-342712220

Script ran unsuccessfully.

**Comment by bletham** [comment]
Hm so pystan it seems it not working. Can you check what version of gcc you have? Pystan 2.19 requires C++14, which is not handled by old versions of gcc, I'm wondering if that might be the issue.

**Comment by supreme-core** [comment]
To get the latest version of gcc g++
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-8 g++-8
gcc-8 --version

Pystan install went through okay but I still can't install fbprophet
So, I reinstall build-essential package
sudo apt-get install build-essential --reinstall

It complains about compilation with x86_65-linux-gnu-gcc, and the version I have 7.4

Collecting fbprophet
  Downloading https://files.pythonhosted.org/packages/33/fb/ad98d46773929079657706e6b2b6e366ba6c282bc2397d8f9b0ea8e5614c/fbprophet-0.5.tar.gz (49kB)
     |████████████████████████████████| 51kB 561kB/s 
Requirement already satisfied: Cython>=0.22 in /usr/local/lib/python3.7/dist-packages (from fbprophet) (0.29.7)
Requirement already satisfied: pystan>=2.14 in /usr/local/lib/python3.7/dist-packages (from fbprophet) (2.19.0.0)
Requirement already satisfied: numpy>=1.10.0 in /usr/local/lib/python3.7/dist-packages (from fbprophet) (1.16.2)
Requirement already satisfied: pandas>=0.23.4 in /usr/local/lib/python3.7/dist-packages (from fbprophet) (0.24.2)
Requirement already satisfied: matplotlib>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from fbprophet) (3.0.3)
Requirement already satisfied: lunardate>=0.1.5 in /usr/local/lib/python3.7/dist-packages (from fbprophet) (0.2.0)
Collecting convertdate>=2.1.2 (from fbprophet)
  Downloading https://files.pythonhosted.org/packages/74/83/d0fa07078f4d4ae473a89d7d521aafc66d82641ea0af0ef04a47052e8f17/convertdate-2.1.3-py2.py3-none-any.whl
Collecting holidays>=0.9.5 (from fbprophet)
  Downloading https://files.pythonhosted.org/packages/16/09/c882bee98acfa310933b654697405260ec7657c78430a14e785ef0f1314b/holidays-0.9.10.tar.gz (73kB)
     |████████████████████████████████| 81kB 2.7MB/s 
Collecting setuptools-git>=1.2 (from fbprophet)
  Downloading https://files.pythonhosted.org/packages/05/97/dd99fa9c0d9627a7b3c103a00f1566d8193aca8d473884ed258cca82b06f/setuptools_git-1.2-py2.py3-none-any.whl
Requirement already satisfied: pytz>=2011k in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23.4->fbprophet) (2018.9)
Requirement already satisfied: python-dateutil>=2.5.0 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23.4->fbprophet) (2.8.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.0.0->fbprophet) (2.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.0.0->fbprophet) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.0.0->fbprophet) (1.0.1)
Collecting ephem<3.8,>=3.7.5.3 (from convertdate>=2.1.2->fbprophet)
  Downloading https://files.pythonhosted.org/packages/c3/2c/9e1a815add6c222a0d4bf7c644e095471a934a39bc90c201f9550a8f7f14/ephem-3.7.6.0.tar.gz (739kB)
     |████████████████████████████████| 747kB 6.3MB/s 
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from holidays>=0.9.5->fbprophet) (1.12.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from kiwisolver>=1.0.1->matplotlib>=2.0.0->fbprophet) (40.6.3)
Building wheels for collected packages: fbprophet, holidays, ephem
  Building wheel for fbprophet (setup.py) ... error
  ERROR: Complete output from command /usr/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-_whfedar/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-9vdftyph --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/fbprophet
  creating build/lib/fbprophet/stan_model
  INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_861b75c6337e237650a61ae58c4385ef NOW.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for fbprophet
  Running setup.py clean for fbprophet
  Building wheel for holidays (setup.py) ... done
  Stored in directory: /home/eric/.cache/pip/wheels/2d/cc/52/784fca01997448402695e3d0356d2f9c814d545bbcdef45d26
  Building wheel for ephem (setup.py) ... error
  ERROR: Complete output from command /usr/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-_whfedar/ephem/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ic6z2ivs --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/ephem
  copying ephem/cities.py -> build/lib.linux-x86_64-3.7/ephem
  copying ephem/__init__.py -> build/lib.linux-x86_64-3.7/ephem
  copying ephem/stars.py -> build/lib.linux-x86_64-3.7/ephem
  creating build/lib.linux-x86_64-3.7/ephem/tests
  copying ephem/tests/test_stars.py -> build/lib.linux-x86_64-3.7/ephem/tests
  copying ephem/tests/test_dates.py -> build/lib.linux-x86_64-3.7/ephem/tests
  copying ephem/tests/test_constants.py -> build/lib.linux-x86_64-3.7/ephem/tests
  copying ephem/tests/test_satellite.py -> build/lib.linux-x86_64-3.7/ephem/tests
  copying ephem/tests/test_jpl.py -> build/lib.linux-x86_64-3.7/ephem/tests
  copying ephem/tests/test_launchpad_244811.py -> build/lib.linux-x86_64-3.7/ephem/tests
  copying ephem/tests/test_cities.py -> build/lib.linux-x86_64-3.7/ephem/tests
  copying ephem/tests/test_rst.py -> build/lib.linux-x86_64-3.7/ephem/tests
  copying ephem/tests/test_usno_equinoxes.py -> build/lib.linux-x86_64-3.7/ephem/tests
  copying ephem/tests/__init__.py -> build/lib.linux-x86_64-3.7/ephem/tests
  copying ephem/tests/test_angles.py -> build/lib.linux-x86_64-3.7/ephem/tests
  copying ephem/tests/test_usno.py -> build/lib.linux-x86_64-3.7/ephem/tests
  copying ephem/tests/test_bodies.py -> build/lib.linux-x86_64-3.7/ephem/tests
  copying ephem/tests/test_github_issues.py -> build/lib.linux-x86_64-3.7/ephem/tests
  copying ephem/tests/test_locales.py -> build/lib.linux-x86_64-3.7/ephem/tests
  copying ephem/tests/test_observers.py -> build/lib.linux-x86_64-3.7/ephem/tests
  copying ephem/tests/test_launchpad_236872.py -> build/lib.linux-x86_64-3.7/ephem/tests
  creating build/lib.linux-x86_64-3.7/ephem/doc
  copying ephem/doc/faq.rst -> build/lib.linux-x86_64-3.7/ephem/doc
  copying ephem/doc/angle.rst -> build/lib.linux-x86_64-3.7/ephem/doc
  copying ephem/doc/newton.rst -> build/lib.linux-x86_64-3.7/ephem/doc
  copying ephem/doc/coordinates.rst -> build/lib.linux-x86_64-3.7/ephem/doc
  copying ephem/doc/catalogs.rst -> build/lib.linux-x86_64-3.7/ephem/doc
  copying ephem/doc/reference.rst -> build/lib.linux-x86_64-3.7/ephem/doc
  copying ephem/doc/index.rst -> build/lib.linux-x86_64-3.7/ephem/doc
  copying ephem/doc/date.rst -> build/lib.linux-x86_64-3.7/ephem/doc
  copying ephem/doc/tutorial.rst -> build/lib.linux-x86_64-3.7/ephem/doc
  copying ephem/doc/CHANGELOG.rst -> build/lib.linux-x86_64-3.7/ephem/doc
  copying ephem/doc/radec.rst -> build/lib.linux-x86_64-3.7/ephem/doc
  copying ephem/doc/rise-set.rst -> build/lib.linux-x86_64-3.7/ephem/doc
  copying ephem/doc/examples.rst -> build/lib.linux-x86_64-3.7/ephem/doc
  copying ephem/doc/quick.rst -> build/lib.linux-x86_64-3.7/ephem/doc
  creating build/lib.linux-x86_64-3.7/ephem/tests/jpl
  copying ephem/tests/jpl/oberon.txt -> build/lib.linux-x86_64-3.7/ephem/tests/jpl
  copying ephem/tests/jpl/mars.txt -> build/lib.linux-x86_64-3.7/ephem/tests/jpl
  copying ephem/tests/jpl/phobos.txt -> build/lib.linux-x86_64-3.7/ephem/tests/jpl
  copying ephem/tests/jpl/uranus.txt -> build/lib.linux-x86_64-3.7/ephem/tests/jpl
  copying ephem/tests/jpl/saturn.txt -> build/lib.linux-x86_64-3.7/ephem/tests/jpl
  copying ephem/tests/jpl/neptune.txt -> build/lib.linux-x86_64-3.7/ephem/tests/jpl
  copying ephem/tests/jpl/hyperion.txt -> build/lib.linux-x86_64-3.7/ephem/tests/jpl
  copying ephem/tests/jpl/europa.txt -> build/lib.linux-x86_64-3.7/ephem/tests/jpl
  copying ephem/tests/jpl/jupiter.txt -> build/lib.linux-x86_64-3.7/ephem/tests/jpl
  creating build/lib.linux-x86_64-3.7/ephem/tests/usno
  copying ephem/tests/usno/risettran_moon.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
  copying ephem/tests/usno/riset_sun.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
  copying ephem/tests/usno/astrom_antares.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
  copying ephem/tests/usno/apptopo_deneb.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
  copying ephem/tests/usno/moon_phases.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
  copying ephem/tests/usno/riset_moon.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
  copying ephem/tests/usno/astrom_mercury.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
  copying ephem/tests/usno/apptopo_moon.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
  copying ephem/tests/usno/appgeo_sun.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
  copying ephem/tests/usno/appgeo_jupiter.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
  copying ephem/tests/usno/astrom_neptune.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
  copying ephem/tests/usno/risettran_rigel.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
  copying ephem/tests/usno/appgeo_deneb.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
  copying ephem/tests/usno/appgeo_moon.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
  copying ephem/tests/usno/apptopo_sun.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
  running build_ext
  building 'ephem._libastro' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/extensions
  creating build/temp.linux-x86_64-3.7/libastro-3.7.6
  creating build/temp.linux-x86_64-3.7/extensions/data
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Ilibastro-3.7.6 -I/usr/include/python3.7m -c extensions/_libastro.c -o build/temp.linux-x86_64-3.7/extensions/_libastro.o
  x86_64-linux-gnu-gcc: error trying to exec 'cc1': execvp: No such file or directory
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for ephem
  Running setup.py clean for ephem
Successfully built holidays
Failed to build fbprophet ephem
Installing collected packages: ephem, convertdate, holidays, setuptools-git, fbprophet
  Running setup.py install for ephem ... error
    ERROR: Complete output from command /usr/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-_whfedar/ephem/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-fb7atl5z/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/ephem
    copying ephem/cities.py -> build/lib.linux-x86_64-3.7/ephem
    copying ephem/__init__.py -> build/lib.linux-x86_64-3.7/ephem
    copying ephem/stars.py -> build/lib.linux-x86_64-3.7/ephem
    creating build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_stars.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_dates.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_constants.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_satellite.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_jpl.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_launchpad_244811.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_cities.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_rst.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_usno_equinoxes.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/__init__.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_angles.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_usno.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_bodies.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_github_issues.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_locales.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_observers.py -> build/lib.linux-x86_64-3.7/ephem/tests
    copying ephem/tests/test_launchpad_236872.py -> build/lib.linux-x86_64-3.7/ephem/tests
    creating build/lib.linux-x86_64-3.7/ephem/doc
    copying ephem/doc/faq.rst -> build/lib.linux-x86_64-3.7/ephem/doc
    copying ephem/doc/angle.rst -> build/lib.linux-x86_64-3.7/ephem/doc
    copying ephem/doc/newton.rst -> build/lib.linux-x86_64-3.7/ephem/doc
    copying ephem/doc/coordinates.rst -> build/lib.linux-x86_64-3.7/ephem/doc
    copying ephem/doc/catalogs.rst -> build/lib.linux-x86_64-3.7/ephem/doc
    copying ephem/doc/reference.rst -> build/lib.linux-x86_64-3.7/ephem/doc
    copying ephem/doc/index.rst -> build/lib.linux-x86_64-3.7/ephem/doc
    copying ephem/doc/date.rst -> build/lib.linux-x86_64-3.7/ephem/doc
    copying ephem/doc/tutorial.rst -> build/lib.linux-x86_64-3.7/ephem/doc
    copying ephem/doc/CHANGELOG.rst -> build/lib.linux-x86_64-3.7/ephem/doc
    copying ephem/doc/radec.rst -> build/lib.linux-x86_64-3.7/ephem/doc
    copying ephem/doc/rise-set.rst -> build/lib.linux-x86_64-3.7/ephem/doc
    copying ephem/doc/examples.rst -> build/lib.linux-x86_64-3.7/ephem/doc
    copying ephem/doc/quick.rst -> build/lib.linux-x86_64-3.7/ephem/doc
    creating build/lib.linux-x86_64-3.7/ephem/tests/jpl
    copying ephem/tests/jpl/oberon.txt -> build/lib.linux-x86_64-3.7/ephem/tests/jpl
    copying ephem/tests/jpl/mars.txt -> build/lib.linux-x86_64-3.7/ephem/tests/jpl
    copying ephem/tests/jpl/phobos.txt -> build/lib.linux-x86_64-3.7/ephem/tests/jpl
    copying ephem/tests/jpl/uranus.txt -> build/lib.linux-x86_64-3.7/ephem/tests/jpl
    copying ephem/tests/jpl/saturn.txt -> build/lib.linux-x86_64-3.7/ephem/tests/jpl
    copying ephem/tests/jpl/neptune.txt -> build/lib.linux-x86_64-3.7/ephem/tests/jpl
    copying ephem/tests/jpl/hyperion.txt -> build/lib.linux-x86_64-3.7/ephem/tests/jpl
    copying ephem/tests/jpl/europa.txt -> build/lib.linux-x86_64-3.7/ephem/tests/jpl
    copying ephem/tests/jpl/jupiter.txt -> build/lib.linux-x86_64-3.7/ephem/tests/jpl
    creating build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/risettran_moon.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/riset_sun.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/astrom_antares.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/apptopo_deneb.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/moon_phases.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/riset_moon.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/astrom_mercury.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/apptopo_moon.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/appgeo_sun.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/appgeo_jupiter.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/astrom_neptune.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/risettran_rigel.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/appgeo_deneb.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/appgeo_moon.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    copying ephem/tests/usno/apptopo_sun.txt -> build/lib.linux-x86_64-3.7/ephem/tests/usno
    running build_ext
    building 'ephem._libastro' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/extensions
    creating build/temp.linux-x86_64-3.7/libastro-3.7.6
    creating build/temp.linux-x86_64-3.7/extensions/data
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Ilibastro-3.7.6 -I/usr/include/python3.7m -c extensions/_libastro.c -o build/temp.linux-x86_64-3.7/extensions/_libastro.o
    x86_64-linux-gnu-gcc: error trying to exec 'cc1': execvp: No such file or directory
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/usr/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-_whfedar/ephem/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-fb7atl5z/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-_whfedar/ephem/

**Comment by bletham** [comment]
One thing to note is that the pystan install will complete successfully even if it is not functional and compiling Stan programs fails. It does seem that PyStan is still not working (but you can try the little test program again to be sure). I have pretty limited ability to debug pystan install issues. Make sure you have python development tools installed (apt-get install python3-dev), but otherwise I think I'll have to refer you to the Pystan issue tracker for help.
