### ISSUE TITLE
ANNOUNCEMENT: v0.5 release

### ISSUE THREAD

**Issue by bletham** [facebook/prophet#978]
Hi all,
We just pushed out v0.5 to PyPI and CRAN. The most notable new features are:

**Conditional seasonalities.**
It is not uncommon to have situations where a seasonality depends on other seasonal factors. For instance, daily seasonality might be different on weekdays vs. weekends. Weekly seasonality might be different during the summer vs. the rest of the year. These situations can now be easily modeled by adding a custom seasonality that uses a binary column to indicate when it should be turned on/off. See the example in the documentation, where we have different weekly seasonalities for the on-season and off-season: https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#seasonalities-that-depend-on-other-factors

**Improved cross validation estimates.**
Previously cross validation was done with a rolling average across all error samples, without any grouping by horizon. We now group by horizon prior to averaging, which will provide better estimates for cases with regularly spaced data (e.g., daily data). For a more detailed description of how it worked previously and what was changed, see my comment here: https://github.com/facebook/prophet/issues/839#issuecomment-462524968 . For irregularly spaced data, the results will be the same as before.

**Plotly plot in Python.**
There has for some time been an interactive plot in R via dygraphs, and now there is an interactive plot in Python using Plotly. Code to produce the plot is at the bottom of the quickstart: https://facebook.github.io/prophet/docs/quick_start.html#python-api
(Once we figure out how to get the actual plot to show up in the documentation it will be there too).

**bugfixes.**
A bunch of bugfixes, especially around some not-backwards-compatible-changes introduced by pandas 0.24.

Thanks to everyone for contributing, and especially to @Olof-Hojvall who implemented both conditional seasonalities and the plotly plot.

**Comment by lopezco** [comment]
Hello everybody, thank you all for the the work done with this library.

I would like to use in production some of the code that was added after the v0.5 release and I was wondering... Are there plans to release a new version any time soon?
