### ISSUE TITLE
cannot load prophet on R 3.6.0 i386

### ISSUE THREAD

**Issue by nhkim1302** [facebook/prophet#981]
I cannot load prophet package on R 3.6.0 i386 using `library(prophet)`. 
It works well on R 3.6.0 x64.
The error message is as follows:
```
Registered S3 methods overwritten by 'ggplot2':
  method         from 
  [.quosures     rlang
  c.quosures     rlang
  print.quosures rlang
Error: package or namespace load failed for ‘prophet’:
 .onLoad failed in loadNamespace() for 'prophet', details:
  call: sink(type = "output")
  error: invalid connection
Additional info: Warning(s): 
In system(cmd, intern = !verbose) :
  running command 'C:/PROGRA~1/R/R-36~1.0/bin/i386/R CMD SHLIB file3d08e756937.cpp 2> file3d08e756937.cpp.err.txt' had status 1
```

Here's my session info.
```
> session_info()
- Session info ---------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.0 (2019-04-26)
 os       Windows 10 x64              
 system   i386, mingw32               
 ui       Rgui                        
 language (EN)                        
 collate  Korean_Korea.949            
 ctype    Korean_Korea.949            
 tz       Asia/Seoul                  
 date     2019-05-23  
```
Note that I have installed Rtools.
```
> find_rtools(TRUE)
Scanning R CMD config CC...
cc_path: C:/RBuildTools/3.5/mingw_32/bin/gcc 
install_path: C:/RBuildTools/3.5 
VERSION.txt
Rtools version 3.5.0.4 
Found compatible gcc from R CMD config CC
[1] TRUE
```

**Comment by bletham** [comment]
hm I'm not totally sure what is happening here, but usually a exit with status 1 from the C++ compiler indicates that something isn't working there correctly, and in particular that rstan isn't working. Could you check if rstan is working by running this:
```
library(rstan)
model_code <- 'parameters {real y;} model {y ~ normal(0,1);}'
fit <- stan(model_code=model_code)  # this will take a minute
mean(extract(fit)$y)  # should be close to 0
```

**Comment by nhkim1302** [comment]
At first, I got an compilation error. After searching on google, I created the 'Makevars' file.
Then the rstan is working now. But still unable to load prophet on R 3.6.0 i386.
The 'Makevars' file's contents is as follows:
```
CXX14FLAGS= -O3 -Wno-unused-variable -Wno-unused-function
CXX14 = g++ -std=c++1y
```

**Comment by bletham** [comment]
It looks like there have been some tooclhain related install difficulties for rstan in Windows starting with rstan 2.17.4 (https://discourse.mc-stan.org/t/failing-to-install-rstan-2-18-on-win10-x64/6044/4). There are some suggestions in that thread, including just falling back to rstan 2.17.3. There may be a solution in that thread, but otherwise I don't have much ability to debug rstan issues in Windows, and I'd have to refer you over to the rstan issue tracker.
