### ISSUE TITLE
cross_validation function isn't recognising the input y values from the fitted prophet model

### ISSUE THREAD

**Issue by pinkumbrella14** [facebook/prophet#984]
I have a few months' worth of hourly data and am trying to use the first 3 months' worth of data for training and then predict the next 7 days' worth of hours. I am able to run the prophet, future, and forecast functions, but run into an issue when I use the fitted prophet model in the cross_validation function, which states “Unknown or uninitialised column: 'y'.” and the y values are all reset to 0.

Below is the code that I am using in the cross_validation function:
subset_cv <- cross_validation(model = m, 
                              initial = 24 * 92, 
                              horizon = 24* 7, 
                              units = "hours"
                             )

I am not sure how to trouble shoot this...

**Comment by bletham** [comment]
I'm not sure what's happening here, could you post the full traceback for the error? You can get it by running `traceback()` right after you get the error.

And when you say y values are reset to 0, in what dataframe are you referring to?
