### ISSUE TITLE
Plotting cross validation metrics as a function of training period size

### ISSUE THREAD

**Issue by ashleyholt** [facebook/prophet#988]
Is there a way to use the cross validation utility to evaluate prediction performance as a function of training period size, or can this be accomplished be iterating through a range of `initial` periods to quantify the minimum requirements for training data availability?

**Comment by bletham** [comment]
The cross_validation function starts with a history of size "initial", makes a forecast, and then increases the history to be of size "initial + period", makes a forecast, increases history to "initial + 3 * period", etc.

If you run cross_valdation on a model (e.g., you can try it with the data in the documentation https://facebook.github.io/prophet/docs/diagnostics.html via the notebook https://github.com/facebook/prophet/blob/master/notebooks/diagnostics.ipynb), then result dataframe (let's call it `df_cv` like in the documentation) will have a column cutoff which will have multiples values. These values are "initial", "initial + period", "initial + 2 * period", etc. So, for an appropriate selection of initial and period, `df_cv` should already have the results you need. The size of the training set used for each prediction will just be `cutoff - min(df['ds'])`.

Let me know if that makes sense.
