### ISSUE TITLE
ImportError: cannot import name plot_plotly

### ISSUE THREAD

**Issue by MainHanzo** [facebook/prophet#990]
Hello, I am trying to run Prophet on a windows machine.
And I am running into a problem after installing prophet and plotly:

I followed the quick start instruction which ask me to do this in cmd:
from fbprophet.plot import plot_plotly
And I received this as a result:
ImportError: cannot import name plot_plotly

I am not sure why I am having this prob, I installed plotly through pip and the prophet through Anaconda. For some reason I have difficulty installing plotly through conda.
I don't know if they are compatible, or it's the problem of my sys path.

Thanks for your attention

**Comment by bletham** [comment]
The import should work even if plotly isn't installed (calling the function itself would just raise an error). Can you verify that you are trying this with v0.5 of fbprophet?
```
import fbprophet
print(fbprophet.__version__)
from fbprophet.plot import plot_plotly
```

**Comment by MainHanzo** [comment]
Thank you! It's a version error. I don't know why when i install prophet using a windows machine and anaconda, it installed a 0.3 version. I used pip to update prophet and all works well now.
