### ISSUE TITLE
fbprophet centOS error: command 'gcc' failed with exit status 4

### ISSUE THREAD

**Issue by a83076555** [facebook/prophet#991]
Running setup.py install for fbprophet ... error
    ERROR: Complete output from command /root/pyweb/data_platforms/data_platforms/venv/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-rse0olnc/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-24k5hhos/install-record.txt --single-version-externally-managed --compile --install-headers /root/pyweb/data_platforms/data_platforms/venv/include/site/python3.7/fbprophet:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/fbprophet
    creating build/lib/fbprophet/stan_model
    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_861b75c6337e237650a61ae58c4385ef NOW.
    error: command 'gcc' failed with exit status 4
    ----------------------------------------
ERROR: Command "/root/pyweb/data_platforms/data_platforms/venv/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-rse0olnc/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-24k5hhos/install-record.txt --single-version-externally-managed --compile --install-headers /root/pyweb/data_platforms/data_platforms/venv/include/site/python3.7/fbprophet" failed with error code 1 in /tmp/pip-install-rse0olnc/fbprophet/

**Comment by bletham** [comment]
From what I can tell, exit status 4 means running out of memory (https://raspberrypi.stackexchange.com/questions/15284/problems-installing-lxml/15299#15299). Could you check what your RAM usage is like during compilation? You need at least 4GB of memory for the install.

**Comment by bletham** [comment]
Running this pystan code will likely also trigger the issue and be a simpler test case. Can you see if it runs?
```
import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this will take a minute
y = model.sampling(n_jobs=1).extract()['y']
y.mean()  # should be close to 0
```
