### ISSUE TITLE
How do create a single df from "m,forecast"

### ISSUE THREAD

**Issue by davidjayjackson** [facebook/prophet#997]
First I want to thanks Ben for creating a script to  predict sunspot activity you can see the script here (I've attached the plot) :
https:// www.kaggle.com/davidjackson0513/ben-prophet-sunspots

My question how can I create a combine "m,forecast" data.frame in order to plot with ggplot2 or plotly? 
Ben, Thanks a again for the script

David 

![My2019](https://user-images.githubusercontent.com/46544155/58754119-e0536280-8497-11e9-8654-3d740e291f1b.png)

**Comment by bletham** [comment]
Everything needed to create the plot is already in the forecast dataframe returned by `predict`, and probably the best guide to see where different elements are is to just check out the plotting code here:
https://github.com/facebook/prophet/blob/ebb304680d126e5d3a83d4ef9eb1f50cb5965273/R/R/plot.R#L48

**Comment by davidjayjackson** [comment]
Ben,
I've run your code example against three different sunspot datasets and the
result week to limit to between 6-12 more months of solar minimum. (:

How does prophet handle missing values (NA)? One of the sunspots datasets
has 3200 missing values. Between 1810 - 1850?

Thanks again.
David

**Comment by bletham** [comment]
NAs are just filtered from the history. The model itself has no problem with missing dates in the history since it does not assume any paticular data frequency. It's a regression model, so it is able to automatically impute the values for missing dates.
